### ISSUE TITLE
Self-signed certificate does not have Authority Key Identifier field set

### ISSUE THREAD

**Issue by RavilN** [randombit/botan#1007]
Hello,
When I create self-signed certificate with is_CA flag true (with intent to use it as CA certificate), it has only Subject Key Identifier extension field set, but the Authority Key Identifier field is omitted. 
When I try to use child certificate signed with this CA certificate in an application, it fails to recognize the CA  certificate as valid, because one of checks to figure out if the certificate in a chain is a root CA certificate, is to verify that Subject Key Identifier matches with the Authority Key Identifier. 
I did check a few root certificates from known issuers like DigiCert, GeoTrust etc, they all have this field set to the same 20 byte value as Subject Key Identifier.
I tried to set the extension in X509_cert_options, following the same logic as Subject Key Identifier is set in the create_self_signed_cert function (extensions.add(new Cert_Extension::Authority_Key_ID(pub_key) ), but as a result when I view the created certificate by certificate viewer, I see whole public key instead of 20 bytes which is displayed for the the Subject Key Identifier.
I tried to use fingerprint of the key, with SHA-1 and SHA-256 algorithms, but fingerprint would not be the same as Subject Key Identifier either.

How can I set the Authority Key Identifier extension for self-signed certificate to the same value as for SKI?

Thank you, Ravil

**Comment by RavilN** [comment]
After some experimenting, I figured out that the SHA-1 hash of privateKey->subject_public_key() gives me the same value as for Subject Key Identifier. So I think my problem is resolved.
Not sure, if the logic of creating self-signed CA certificate should be modified to include Authority Key Identifier.

**Comment by randombit** [comment]
It may make sense to have explicit AKID=SKID since it is then very clear that it is a self-signed certificate.

I will check what the various roots do.

**Comment by randombit** [comment]
Fixed
