### ISSUE TITLE
Missing tests for Python wrappers and FFI module

### ISSUE THREAD

**Issue by randombit** [randombit/botan#101]
Should be quick to effectively run the whole test suite a second time via python.

**Comment by webmaster128** [comment]
Is this about the botan python wrapper? If yes, is the idea to have tests written in Python that call the wrapper functions? Any Python testing framework in mind?

**Comment by randombit** [comment]
Yes, I was planning on having a parallel set of tests in Python. Right now neither the python wrapper itself nor the C ABI module (ffi) are being tested at all during CI.

Haven't thought as far as which testing framework to use, `unittest` seems the obvious choice as I'd prefer everything continue to work out of the box on a plain Python interpreter if possible. But this isn't an area I know well so feel free to suggest something.

**Comment by cordney** [comment]
Both ffi and the python wrapper now have a set of tests run in CI and coverage reported also (ffi is at 45% coverage, python wrapper at 79%). Is there anything to do here?

**Comment by randombit** [comment]
Test coverage can always be better, but that's a given. With at least a basic framework in place I think this can be closed.

**Comment by cordney** [comment]
I am currently working on more tests for ffi, expect a PR in the next days.
