### ISSUE TITLE
Subject Alternative Name is not transferred from certificate sign request

### ISSUE THREAD

**Issue by RavilN** [randombit/botan#1010]
Hello,

I tried to create certificate sign request (CSR) using PKCS10_Request from PEM content, and then sign it using X509_Ca::sign_request method. The CSR has in it subject alternative name (I can see it by command botan_cli asn1print <fileName>). But the resulting signed certificate does not have this field.

Could you please suggest what am I doing wrong, or this feature is just not implemented?

**Comment by RavilN** [comment]
As a workaround I modified X509_ca.cpp line 80 to:
   if (req.extensions().get(Botan::OID("2.5.29.17")).get() == 0) //"X509v3.SubjectAlternativeName"));
   {
       extensions.replace(
            new Cert_Extension::Subject_Alternative_Name(req.subject_alt_name()));
   }
and now I have SAN set. The problem is that PKCS10_Request::subject_alt_name returns empty value, although it is defined in extensions.

**Comment by randombit** [comment]
Sorry for leaving this issue idle for so long - it has been fixed in #884 now and will be addressed in 2.4.0 release.
