### ISSUE TITLE
Can't Configure the Build On Windows10

### ISSUE THREAD

**Issue by JarvanWong** [randombit/botan#1016]
I followed this link"https://botan.randombit.net/manual/building.html#on-windows".
I finished the first step($ python configure.py --cc=msvc),and cmd showed:INFO: Botan 1.10.16 build setup is complete.
Then I went on the next stop($ nmake),and cmd showed
`cl /MD /Ibuild\include /O2  /EHs /GR /W3 /wd4275 /wd4267 /DBOTAN_DLL=__declspec(dllexport) /nologo /c src\algo_base\symkey.cpp /Fobuild\lib\algo_base_symkey.obj
symkey.cpp
src\algo_base\symkey.cpp(8): fatal error C1083: Can not open include file: “botan/symkey.h”: No such file or directory
NMAKE : fatal error U1077: “"E:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\cl.EXE"”: return code“0x2”
Stop.`

How to deal with this?

**Comment by webmaster128** [comment]
Do you strictly need Botan 1.10? All new development should use the latest Botan 2 release, which includes hundreds of build system improvements, including a lot of Windows specific fixes. It would be much easier to start from there.

**Comment by randombit** [comment]
Closing this as inactive. If you are still having problems please open a new ticket. As webmaster128 said however you would be much better of using Botan 2.
