### ISSUE TITLE
Can we remove --with-visibility/--without-visibility?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#1020]
The configure.py options ` --with-visibility`/`--without-visibility` are both hidden from the user documentation. with_visibility defaults to True. Is there a reason we need to keep them?

**Comment by randombit** [comment]
Both flags can be removed, I think they were added in 8b2e5f9d9 because at the time some versions of GCC we supported (<= 3.4) did not support the visibility flags so there needed to be some way to disable it.
