### ISSUE TITLE
Single amalgamation build not working using clang on OS X

### ISSUE THREAD

**Issue by porchdog** [randombit/botan#1021]
Using the amalgamation build with the following command line:

./configure.py --amalgamation --single-amalgamation-file --disable-modules=pkcs11

and trying to build it with the following command:

clang++ -std=c++1z -c botan_all.cpp

I'm seeing the compile fail with the following error:

fatal error: error in backend: Cannot select: intrinsic %llvm.x86.aesni.aesenclast
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.5.0
Thread model: posix

Is the configuration step above incorrect or is this a bug in the generated file?

**Comment by webmaster128** [comment]
The build command is insufficient. Try: `clang++ -std=c++1z -c botan_all.cpp -maes -mpclmul -mssse3 -msse2 -mavx2`

**Comment by porchdog** [comment]
That did it.  Thanks very much.
