### ISSUE TITLE
Botan Reference Manual, Release 2.1.0 Page 22

### ISSUE THREAD

**Issue by fluber** [randombit/botan#1025]
1 #include <botan/auto_rng.h>                                                                               
  2 #include <botan/symkey.h>
  3 #include <botan/secmem.h>
  4 #include <botan/pipe.h>
  5 #include <botan/key_filt.h>
  6 #include <botan/cipher_mode.h>
  7 #include <iostream>
  8 #include <fstream>
  9 using namespace Botan;
 10 using SymmetricKey = OctetString;
 11 
 12 int main(int argc, char* argv[])
 13 {
 14     AutoSeeded_RNG rng;
 15     SymmetricKey key(rng, 16); //a random 128-bit key
 16     InitializationVector iv(rng, 16); //a random 128-bit IV
 17 
 18     Pipe pipe(get_cipher("AES-128/CBC", key, iv, ENCRYPTION));
 19 
 20     pipe.process_msg("secrets1");
 21     pipe.process_msg("secrets2"); //there is a exception ....
 22 
 23     secure_vector<byte> c1 = pipe.read_all(0);
 24     byte c2[4096] = { 0 };
 25     size_t got_out = pipe.read(c2, sizeof(c2), 1);
 26     return 0;
 27 }

=================================================

Breakpoint 1, main (argc=1, argv=0x7effee94) at AES.cpp:14
14	    AutoSeeded_RNG rng;
(gdb) step
15	    SymmetricKey key(rng, 16); //a random 128-bit key
(gdb) step
16	    InitializationVector iv(rng, 16); //a random 128-bit IV
(gdb) step
18	    Pipe pipe(get_cipher("AES-128/CBC", key, iv, ENCRYPTION));
(gdb) step
20	    pipe.process_msg("secrets1");
(gdb) step
21	    pipe.process_msg("secrets2");
(gdb) step
terminate called after throwing an instance of 'Botan::Exception'
  what():  False assertion 'The nonce is fresh for this message' (expression m_fresh_nonce) in get @./src/lib/filters/cipher_filter.cpp:49

Program received signal SIGABRT, Aborted.
0x768ddf70 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 

============================================

This example is from the doc "botan.pdf"  page 22.  

the second call process_msg will raise a exception, so strange...

**Comment by randombit** [comment]
This is #864

**Comment by randombit** [comment]
Fixed now in #1202
