### ISSUE TITLE
No way to copy hash state

### ISSUE THREAD

**Issue by dewyatt** [randombit/botan#1037]
Currently there does not appear to be any method to copy the state of a hash (please correct me if I'm wrong).

Specifically, something similar to OpenSSL's `EVP_MD_CTX_copy` would be useful. As the documentation for that function states:
> This is useful if large amounts of data are to be hashed which only differ in the last few bytes.

I wanted to start a discussion on whether this is a feature that would be accepted, if we were to submit a PR (no promises!).

This work is done on behalf of [Ribose Inc](https://www.ribose.com) (@riboseinc).

**Comment by randombit** [comment]
This is available but in a somewhat non-obvious way (and TBH I'm not sure if it's available/works correctly for all hash functions). But I confirm it works for MD5, and probably works for SHA-1/SHA-2 also.

```
#include <botan/md5.h>
#include <botan/hex.h>
#include <iostream>

int main()
{
   Botan::MD5 md5;

   md5.update("foo");

   Botan::MD5 md5_x(md5);
   md5_x.update("bar");

   std::cout << hex_encode(md5.final()) << "\n";
   std::cout << hex_encode(md5_x.final()) << "\n";
}
```

This outputs

```
ACBD18DB4CC2F85CEDEF654FCCC4A4D8
3858F62230AC3C915F300C664312C63F
```

which are the correct MD5 hashes for "foo" and "foobar". I also checked that this worked for a long-ish (127 byte) initial string.

That said it might be nice to have this available in a way that was easier to access, as with the current method you have to know the exact type to use. Unfortunately we already used `clone` to mean something different (return a new clean object of the same type).
