### ISSUE TITLE
How to troubleshoot handshake failures?

### ISSUE THREAD

**Issue by louiz** [randombit/botan#1038]
With some servers, the TLS handshake fails: the tls_alert() callback gets called, and the value of Botan::TLS::Alert::type() is HANDSHAKE_FAILURE.

This can be reproduced for example on irc.ppirc.net, with the following command:

```
$ botan tls_client --print-certs --port=6697 irc.ppirc.net
Alert: handshake_failure                                                       
```

but it works fine with openssl:
```
$ openssl s_client -connect irc.ppirc.net:6697
[…]
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session: 
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
[…]
```

Is there a way to see why the handshake failed, and if this can be fixed (by a policy file, or something)

**Comment by randombit** [comment]
Unfortunately the TLS protocol just gives us this one bit of information from the alert, and `handshake_failure` can mean nearly anything. This case is easy to debug thanks to the OpenSSL output (thanks for including that): the default TLS policy in Botan prohibits RSA ciphersuites. So here the client offered some DH/ECDH ciphersuites but the server did not find anything it was willing to negotiate and rejected our connection. The default policy also requires at least 2048 bit RSA keys, this server is still using 1024 bit - that would have caused an exception with an informative error on client side after it received the server cert (along with sending an uninformative `handshake_failure` alert back to the server).

With those changes everything seems to work:

```
$ cat weak_rsa.txt
key_exchange_methods = RSA
minimum_rsa_bits = 1024
$ ./botan tls_client irc.ppirc.net --port=6697 --policy=weak_rsa.txt
Certificate validation status: Certificate issuer not found
Handshake complete, TLS v1.2 using RSA_WITH_AES_256_GCM_SHA384
Session ID 5908E26E1755799685248611A0790D6903123C1119A6A2ABCB222503CBA5F38C
Session ticket FC8E39F127C3BF340884389839...
:cirno.ppirc.net NOTICE AUTH :*** Looking up your hostname...
:cirno.ppirc.net NOTICE AUTH :*** Checking ident...
```

But in general debugging these issues is not so easy. There are some logging callbacks defined in `TLS::Callbacks` but they are not currently called at any point, if it were possible for the application to log messages as they are processed (like `openssl s_client -msg/-trace` does) that would make debugging this kind of thing simpler.

If the policy changes above solve the connection problem you're seeing can you close this issue? Thanks.

**Comment by louiz** [comment]
Thank you very much for the quick and detailed explanation! Indeed this policy file fixes it, I can just use it directly in my project as-is.
