### ISSUE TITLE
No option for Hash to compute the digest and maintain state

### ISSUE THREAD

**Issue by dewyatt** [randombit/botan#1039]
Currently, all hash implementations will clear() when obtaining the digest.

I'm not sure this is intuitive, as the clear() function is available to call explicitly if needed.
(On the other hand, the naming of BufferedComputation::final makes this clearer)

What are thoughts on this behavior being modified?
What if, for example, BufferedComputation had an additional current_result() method, or something similar? I have not looked in depth at this, I just want to gather initial feedback.

Please share your thoughts!

To understand our interest in this: Ruby has a Digest framework ([Digest::Instance](https://ruby-doc.org/stdlib-2.3.0/libdoc/digest/rdoc/Digest/Instance.html)) that we would ideally like to derive from, but it has some requirements that we can't currently meet with Botan.

Related: #1037 

This work is done on behalf of [Ribose Inc](https://www.ribose.com) (@riboseinc).

**Comment by randombit** [comment]
I think the cleanest thing is, for applications that need this functionality, use `HashFunction::copy_state` (added in #1056) and do something like

```
std::unique_ptr<HashFunction> finalized_hash = running_hash->copy_state();
std::vector<uint8_t> this_digest = finalized_hash->final();
// then continue using running_hash to compute digest
```

Thoughts?

**Comment by dewyatt** [comment]
@randombit Yep, #1037 was pretty much my fallback plan for this. With that now complete (thanks!), we should be able to create a compatible alternative to ruby's OpenSSL::Digest, using Botan.

(I just tested and indeed this should be good! I'll do a PR for the FFI interface+tests soon.)
