### ISSUE TITLE
Adding Documentation

### ISSUE THREAD

**Issue by ReidHonan** [randombit/botan#1046]
Hey everyone,

I am looking at contributing some documentation to this project, I noticed in the doc/todo.rst that specific documentation has been requested surrounding specific topics like RSA. Can people elaborate on what they would like in these documents? RSA is a topic I am familiar with, and just need to know what the documents should contain.

**Comment by randombit** [comment]
Thank you for the kind offer, more documentation would be most welcome. What I had in mind was a series of docs oriented towards developers looking to accomplish specific tasks but who may not be too familiar with the underlying concepts. For example for RSA it might contain:

- Brief outline of the algorithm and what it is capable of.
- Key generation w/example. Talk about safe vs unsafe parameters.
- Serializing keys for transport/storage, and restoring in memory (PKCS8::load_key, etc)
- Example of encrypting and decrypting a session key with discussion of the necessity of a padding scheme (homomorphic properties of unpadded RSA), choice of PKCSv1.5 vs OAEP, why you don't want to encrypt the plaintext message itself with RSA, etc.
- Similar for signatures

**Comment by randombit** [comment]
Closing as inactive. @ReidHonan doc PRs welcome anytime :)
