### ISSUE TITLE
Stateful_RNG should allow internal state (de)serialisation

### ISSUE THREAD

**Issue by reneme** [randombit/botan#1049]
Please understand this mainly as a request for comments. I'd like to double-check if this idea is reasonable before going ahead with an implementation attempt.

We would like to be able to access the internal state of `Stateful_RNG` implementations, specifically the `HMAC_DRBG`. Currently there is neither a public method nor is the state (i.e. `m_V` in case of `HMAC_DRBG`) accessible for derived classes. The goal is to serialise and recreate a `Stateful_RNG` given its internal state.

Rationale: Our application provides an initialisation phase where a lot of entropy is supposed to be gathered. This entropy is initially used to generate long-lived RSA key-pairs. However we would like to preserve this entropy for later application sessions. Hence, the serialised `Stateful_RNG`'s state would be encrypted, authenticated and stored on disk. A future session could then deserialise the `Stateful_DRBG`, reseed it with fresh entropy and continue using it.

Another use case for such an extension could be more deterministic debugging and/or testing with a previously known RNG seed value.

Concretely I'd like to add two (probably pure-virtual) methods to `Stateful_RNG` and implement them for `HMAC_DRBG`:
```C++
/** retrieve the current state of the RNG */
secure_vector<uint8_t> Stateful_RNG::serialize() const;

/** initialize RNG with given state */
void Stateful_RNG::deserialize(const secure_vector<uint8_t> &s);
```

Alternatively we thought about generating some random data (f.e. 512 bytes) with the initially seeded RNG, store these bytes encrypted on disk and use it for reseeding a fresh RNG in the next session. While this approach would not require any code changes in Botan, I am wondering if it has other negative implications. Furthermore it probably doesn't support the 'deterministic debugging' use case mentioned above.

I would be grateful for an opinion from your side.

**Comment by randombit** [comment]
I can envision cases where being able to serialize and restore the RNG state is useful but I'm not sure what you're describing is one of them - considering you are additionally seeding with fresh entropy anyway, you are not relying on the RNG being deterministic between process executions which I think would be the main benefit. Also `deserialize` feels like a very 'poke-self-in-eye' kind of API, eg consider an application doing this that doesn't add additional entropy and isn't very careful to never deserialize more than once with the same state - bad news. I agree it would aid in debugging sometimes, but I'm hesitant to add it just for that.

The approach of saving off some RNG output and using it for later seed material seems much safer to me. It also avoids the risk that an attacker who recovers the serialized state might be able to backtrack and use it to attack the RSA key generation. HMAC_DRBG seems quite strong so I don't think that's likely, but given you are initially using it to generate "long-lived RSA key-pairs" what I'd suggest is first do your expensive seeding operation, generate the RSA keys, followed by another quick reseeding (say just the standard poll), followed by generating 128-512 bytes of follow-on seed material. (Or if you're feeling extra-cautious, even do a quick reseed between each RSA key.) The reseed acts as a firewall preventing any possible backtracking attempt.

**Comment by noloader** [comment]
Its probably worth mentioning that most RNG threat models include a logical boundary that presumes an attacker does not have access to state. When an RNG is provided in-process, its kind of a moot point.

However, when the crypto is provided out-of-process, like Microsoft CNG or GPG (GPG can use separate processes and libassuan for message passing), then it blows the threat model out of the water.

**Comment by reneme** [comment]
We went ahead and implemented the alternative solution I sketched in the initial question. Thanks a lot for you opinions on that.
