### ISSUE TITLE
Problem verifying s/mime signed message

### ISSUE THREAD

**Issue by e-identity** [randombit/botan#1050]
I try to check/verify s/mime multipart/signed formatted emails created with thunderbird as part of a bigger project. The message can be decomposed including the full content of the smime.ps7 part, the signature can be correctly rsa decrypted from the given certificate, as can be verified by the correct values of the fixed bits in the emsa signature protocol (last lines in the attached file). However, i'm not able to generate the hash value of the signed entity. I tried some of variations in the CRLF count at the end (or beginning) of the entity, but in vain. Any suggestions how to carry on will be welcome.

[smime-fail.txt](https://github.com/randombit/botan/files/1010673/smime-fail.txt)

**Comment by e-identity** [comment]
solved

**Comment by randombit** [comment]
I'm glad and apologies for not having time to look at this. For posterity can you briefly mention what the problem was?
