### ISSUE TITLE
Will not build on/for arm64 with Ubuntu and GCC 5.4.0.

### ISSUE THREAD

**Issue by rthornthwaite** [randombit/botan#1062]
The problem is the code is trying to use X86 assembly instructions.    It does not correctly check to see if the target is X86 or not.   I disabled the conditional compile so that the code would just use the C++ implementation of the problem functions.    If it is too much trouble to do the conditional compile correctly I would just use the C++ functions.    
[diff.txt](https://github.com/randombit/botan/files/1048812/diff.txt)

**Comment by randombit** [comment]
Can you mention what version this is and where you got the source? The `#ifdef Q_OS_UNIX` mentioned in your diff is a Qt macro and is not used anywhere in Botan; perhaps this is some Qt or KDE fork?

FWIW cross compilation to arm64 works fine and is tested in CI. Try git master or the 2.1.0 release.

**Comment by rthornthwaite** [comment]
I am sorry.   I was actually trying to build qt-creator-opensource-4.3.0.  For which botan is a third party library.  I see it is Botan 1.10.2, 2012-06-17.  I have it building now with my patch.   It seems like this is a bug for Qt.
