### ISSUE TITLE
Doxygen build is failing due to various errors

### ISSUE THREAD

**Issue by zgyarmati** [randombit/botan#1067]
On current master HEAD the Doxygen build is failing at several points due to warnings treated as errors.
There are 2 types of errors:

1. for some platform-specific methods (line sha1_armv8_compress_n()) the declarations are hidden with ifdefs, but the definition not: the compilation is ok but Doxygen notes it.
2. some @params in the doxygen comment are not in sync with the actual arguments.

PR with the fixes will follow soon.

**Comment by randombit** [comment]
Thanks. Unfortunately the Doxygen included in Ubuntu 14.04 on Travis CI doesn't support the -W option (turning warnings into errors) so sometimes problems sneak in without triggering a CI failure.
