### ISSUE TITLE
unfinished change in master cipher_filter.cpp

### ISSUE THREAD

**Issue by fxdupont** [randombit/botan#1071]
The m_nonce code in src/lib/filters/cipher_filter.cpp on master or ed25519 branches was simplified but the initialization was not updated in Cipher_Mode_Filter::Cipher_Mode_Filter:
`m_nonce(mode->default_nonce_length() == 0),`
now the m_nonce member is a vector so its constructor no longer take a bool but simply takes a length (typically 0 or the length of the iv), correct code is:
`m_nonce(mode->default_nonce_length()),`

I can pull a request if it is easier to integrate for you.

**Comment by randombit** [comment]
Fixed now, yes?
