### ISSUE TITLE
comments about ed25519 branch

### ISSUE THREAD

**Issue by fxdupont** [randombit/botan#1072]
I am working on ed25519/x25519 code so I have two comments:
 - the code for `explicit Curve25519_PrivateKey(const secure_vector<uint8_t>& secret_key);` is missing and BTW the comment `@param secret_key DER encoded private key bits` is likely wrong (and it was copied to src/lib/pubkey/ed25519/ed25519.h where it is clearly wrong).

 - even it is still an Internet Draft today *please* comply with draft-ietf-curdle-pkix-04.txt, e.g., using the 1.3.101.11x OIDs and CurvePrivateKey type for privateKey field in PKCS#8 / RFC5958. This should make next Botan compatible with next OpenSSL.

 - of course it should be fine to have ed448/x448 support too...

If you agree about the second point I can manage to code missing stuff and pull a request.

**Comment by randombit** [comment]
Thanks for the comments. I was not familiar with the curdle draft but absolutely we should follow a standard convention wherever one exists. PR would be great otherwise I'll make the changes for curdle

Re 448 agree would be nice to have, not planning on working on that anytime in the near term though.

**Comment by fxdupont** [comment]
I am doing the PR. BTW I can see the ed25519 branch was just merged...

**Comment by randombit** [comment]
Yes was merged on Friday

**Comment by fxdupont** [comment]
I worked on it in my GitHub botan repo (branch curdle. It seems to work well.
List of changes are:
 - #1071 fix (not related but it broke the SoftHSMv2 application)
 - Curve25519_PrivateKey constructor from secret_key
 - the 2 OIDs from private to draft-ietf-curdle-pkix values
 - simplified the {Curve,Ed}25519 public key encoding (they are DER encoded at themselves, or with other worlds raw public keys are used)
 - changed the {Curve,Ed}25519 private key encoding according to draft-ietf-curdle-pkix (32 byte Octet string)
 - moved algorithm identifier parameters to empty (vs NULL which is not accepted by OpenSSL)
It works well with my application (SoftHSMv2, own eddsa2 branch) including key import which reads a PKCS#8 file, so I am pulling a request...

**Comment by randombit** [comment]
This can be closed now, right?

**Comment by fxdupont** [comment]
Yes, it was merged so we can close it.
