### ISSUE TITLE
BOTAN_PARALLEL_FOR used after pulling AES S-box into cache

### ISSUE THREAD

**Issue by Myriachan** [randombit/botan#1077]
In 2.1.0, I just saw this piece of code in src/lib/block/aes/aes.cpp:

```
   // Hit every cache line of TE
   uint32_t Z = 0;
   for(size_t i = 0; i < TE.size(); i += cache_line_size / sizeof(uint32_t))
      {
      Z |= TE[i];
      }
   Z &= TE[82]; // this is zero, which hopefully the compiler cannot deduce

   BOTAN_PARALLEL_FOR(size_t i = 0; i < blocks; ++i)
```

You can't rely upon the cache remaining consistent across threads.  For example, what would happen if one of the assigned threads is assigned to a different core, or worse, a different NUMA node than the thread that preloaded the cache?  There's also the problem that the commands the compiler inserts to synchronize among threads could call into the OS kernel, and the S-box might get evicted from the cache as a result.

This only matters on systems without a constant-time AES implementation: non-x86 systems, and x86 systems without SSSE3 (or AES-NI).

**Comment by randombit** [comment]
Sorry about the late reply on this, yes probably a bad idea. Switched back to `for` in b00481848. Thank you for the report.
