### ISSUE TITLE
BigInt::random_integer distribution not uniform

### ISSUE THREAD

**Issue by 983** [randombit/botan#108]
Code:
https://github.com/randombit/botan/blob/master/src/lib/math/bigint/big_rand.cpp#L45

Test:
```cpp
#include <vector>
#include <iostream>
#include <botan/bigint.h>
#include <botan/rng.h>

using namespace Botan;

int main(){
	std::vector<int> bins(10, 0);

	RandomNumberGenerator *rng = RandomNumberGenerator::make_rng();

	for (int i = 0; i < 10000; i++){
		BigInt b = BigInt::random_integer(*rng, 0, bins.size());
		size_t x = b.to_u32bit();
		bins[x]++;
	}

	for (size_t i = 0; i < bins.size(); i++){
		std::cout << i << ": " << bins[i] << std::endl;
	}

	return 0;
}
```

Example output:
```
0: 954
1: 976
2: 1237
3: 1280
4: 945
5: 932
6: 912
7: 897
8: 948
9: 919
```

2 and 3 appear more often than expected. Note that this happens all the time, not just by chance.

Explanation:
http://stackoverflow.com/questions/10984974/why-do-people-say-there-is-modulo-bias-when-using-a-random-number-generator

Also BigInt::randomize does not work as I would have expected it to:

```cpp
#include <vector>
#include <iostream>
#include <botan/bigint.h>
#include <botan/rng.h>

using namespace Botan;

int main(){
	std::vector<int> bins(10, 0);

	RandomNumberGenerator *rng = RandomNumberGenerator::make_rng();

	for (int i = 0; i < 10000; i++){
		BigInt b;
		b.randomize(*rng, 3);
		size_t x = b.to_u32bit();
		bins[x]++;
	}

	for (size_t i = 0; i < bins.size(); i++){
		std::cout << i << ": " << bins[i] << std::endl;
	}

	return 0;
}
```

Output:
```
0: 0
1: 0
2: 0
3: 0
4: 2508
5: 2429
6: 2526
7: 2537
8: 0
9: 0
```

I would have expected it to generate random 3 bit integers, so something in the range [0, 8) but instead it generates numbers in the range [4, 8) and the code is not commented to explain this behaviour.

https://github.com/randombit/botan/blob/master/src/lib/math/bigint/big_rand.cpp#L29

**Comment by webmaster128** [comment]
Great catch!

Problem 1: I think it is bug that should be relatively easy to fix. Thanks for the test case which I am integrating into the test suite.

Problem 2: The line you highlighted makes sure that the highest bit is always set. In fact `b.randomize(*rng, n)` means a leading 1 and `n-1` random positions: `[1 x  x x x x x x .... x]` to the entropy in the result is `n-1` bits. Whether or not this is desired, I don't know.

**Comment by webmaster128** [comment]
I have a patch for problem 1 that produces the following ratios in 100,000 iterations:

```
0: 0.0999
1: 0.0999
2: 0.1
3: 0.101
4: 0.101
5: 0.0994
6: 0.0988
7: 0.0988
8: 0.101
9: 0.0995
```

Expected is 10 % = 0.1 for each digit. Is there a measurement to say whether or not this a a good distribution?

**Comment by 983** [comment]
[You can never be sure.](http://dilbert.com/strip/2001-10-25)

Such a simple test is good enough to tell if something is horribly wrong but ensuring that everything is correct might be impossible.
One can get closer with the [Diehard](https://en.wikipedia.org/wiki/Diehard_tests) and [Dieharder](http://www.phy.duke.edu/~rgb/General/dieharder.php) tests, but in some cases the tests will randomly fail and there is nothing we can do about it.

**Comment by webmaster128** [comment]
Okay I am happy with my test now (allowing 9-11 % per digit at 10,000 runs) which consistently failed before the patch and consistently passes after the patch.

I'll push a pull request soon. Need to do some rebasing first.

**Comment by 983** [comment]
My statistics are a bit rusty, so take everything below with a grain of salt.

The distribution for 10k coin flips looks like [this](http://www.wolframalpha.com/input/?i=probability+of+10000+coin+flips).
According to the section titled [Perfectly Normal](https://www.fourmilab.ch/rpkp/experiments/statistics.html) the normal distribution should look like [this](http://www.wolframalpha.com/input/?i=exp%28-%28x-10000+%2F2%29^2%2F%282*sqrt%2810000+%2F4%29^2%29%29%2F%28sqrt%282*pi%29*sqrt%2810000+%2F4%29%29).
To me those look quite similar so lets hope that this was correct and carry on.
Given the normal distribution we can integrate and see [how often we will reach more than 5000 + 10% * 5000 = 5500](http://www.wolframalpha.com/input/?i=integrate+exp%28-%28x-10000+%2F2%29^2%2F%282*sqrt%2810000+%2F4%29^2%29%29%2F%28sqrt%282*pi%29*sqrt%2810000+%2F4%29%29+from+5500+to+infinity).
Multiply that by two to include the ones less than 4500 and we get roughly [1.5e-23](http://www.wolframalpha.com/input/?i=erfc%285+sqrt%282%29%29).
I would guess that such a low probability of failure is a sufficiently strong indicator that something went wrong to justify a second test run if it was not.

**Comment by webmaster128** [comment]
That is a great start, thanks. Isn't the question how big the rage [5000-x, 5000+x] must be, such that in 95 % of the cases, the sum is in that range? I think this is common practice when defining [significance](https://en.wikipedia.org/wiki/Statistical_significance).

Given your formular, that range is [4900, 5100]: [calculation](http://www.wolframalpha.com/input/?i=2+*+integrate+exp%28-%28x-10000+%2F2%29^2%2F%282*sqrt%2810000+%2F4%29^2%29%29%2F%28sqrt%282*pi%29*sqrt%2810000+%2F4%29%29+from+5100+to+infinity).

Assuming we want the test to fail in 0.05 % (one out of 2000) of the cases, we can set the range to [5000-175, 5000+175].

175 / 5000 = 3.5 % is much more strict then what I set for the single value checks.

Could you please review #221 and add a note there when it is okay? I fixed problem 1 and documented problem 2.
