### ISSUE TITLE
Botan::X509_CA::X509_CA

### ISSUE THREAD

**Issue by huang229** [randombit/botan#1083]
X509_Certificate ca_cert(arg_ca_cert);

		std::auto_ptr<PKCS8_PrivateKey> privkey(
			PKCS8::load_key(arg_ca_key, rng, arg_passphrase)
		);

		X509_CA ca(ca_cert, *privkey);
Botan::X509_CA::X509_CA   There is no overloaded function takes two parameters

**Comment by randombit** [comment]
Hi. I'm not sure I understand what the question is. But maybe you are porting code forward from 1.10 to 2.x? In which case, you must additionally pass a string specifying what hash function to use to sign requests (eg "SHA-256" or "SHA-384") as well as an RNG. Hope this helps.

**Comment by huang229** [comment]
thank you.
