### ISSUE TITLE
botan 1.10.16 - linux arm 64 support

### ISSUE THREAD

**Issue by adnan-kamili** [randombit/botan#1091]
When trying to build for linux arm 64 I get following error:

`./configure.py --cc=gcc --cpu=armv8-a --no-autoload --gen-amalgamation --enable-modules=rsa,eme_pkcs,emsa3,emsa4,sha1,auto_rng,cbc,kdf2,asm_engine,pthreads,unix_procs`

> Error: Unknown or unidentifiable processor "armv8-a"

**Comment by randombit** [comment]
Sorry for the delay - arm64 is not supported in 1.10, that branch predates arm64 processors by several years.

**Comment by adnan-kamili** [comment]
What is the minimum gcc compiler version support by 1.11.x or 2.x branch. Are there any breaking or api changes in moving from 1.10 to 1.11 branch.

**Comment by webmaster128** [comment]
1.11.x was the development branch for 2.x, so 2.x is your friend. See compiler support here: https://github.com/randombit/botan#current-stable-release

There are a lot of API changes (Botan 2.x is c++11) but as far as I know there is no migration guide.

**Comment by noloader** [comment]
> What is the minimum gcc compiler version support ...

With respect to GCC and ARMv8, you want GCC 4.9 or higher. GCC 4.8 support for Aarch32 and AArch64 is spotty. GCC 4.8 doe snot even bother to define [ARM ACLE macros](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0053c/IHI0053C_acle_2_0.pdf), like `__ARM_FEATURE_CRC32` and `__ARM_FEATURE_CRYPTO`.

**Comment by randombit** [comment]
You are in luck, I noticed that Debian had some downstream patches for 1.10 adding support for various architectures including Aarch64 which I just merged upstream in 16f3c8ce. That will be included in the next 1.10 release, tentatively scheduled for early October.

**Comment by adnan-kamili** [comment]
Hi @randombit thanks for considering to add the support. Any update on this feature, badly need this.

**Comment by randombit** [comment]
@adnan-kamili Basic support was added in 1.10.17

This doesn't include CPU specific extensions for Aarch64 though (SHA, AES, GCM) which are only in 2.x

**Comment by adnan-kamili** [comment]
@randombit thanks, what does cpu specific extensions specifically mean, I suppose it would only affect performance and not the functionality

**Comment by randombit** [comment]
@adnan-kamili Correct, everything works just not as fast
