### ISSUE TITLE
Could not find any algorithm named

### ISSUE THREAD

**Issue by FloBeh** [randombit/botan#1100]
Hello, I have a problem with the AES encryption/decryption.
If I try to use AES-128 with ECB or CTR mode i everytime get the Message:

> terminate called after throwing an instance of 'Botan::Algorithm_Not_Found' what():  Could not find any algorithm named "AES-128/CTR"

In my code I'm trying to decrypt a Ciphertext from a file in which is some encrypted text in Base 64 encoding.
I try it as follows:
`vector<byte> key = hex_decode("47656865696D65725363686CC3BC7373");
    vector<byte> IV = hex_decode("496E697469616C6973696572756E6773");
    DataSource_Stream in("../data/aescipher.txt");
    Pipe pipe(new Base64_Decoder, get_cipher("AES-128/CTR", key, IV, DECRYPTION));
    pipe.process_msg(in);
    cout << "Der entschlüsselte text lautet: " << endl << pipe.read_all_as_string(0) << endl`

but I get the error message from above. If I try it with CFB-Mode instead of CTR mode I get no Error but the text will not fully decrypt. So why do I get the Error message wit CTR-Mode. Is there something wrong in my Code?

Same Problem if I want to encrypt with ECB mode:

`Pipe pipe(get_cipher("AES-128/ECB", key, ENCRYPTION)`

Is there something wrong with my Code or is it any failure in the library??

Greetings 
FloBeh

**Comment by LesnyRumcajs** [comment]
It seems ECB has been unfortunately removed from Botan. I really don't know why, a tool should not be blamed for other people's ignorance. Sure, ECB should not be used in most applications but I'd still want to use it with legacy stuff.

https://botan.randombit.net/news.html#version-2-0-0-2017-01-06

**Comment by randombit** [comment]
The right name for CTR is `CTR-BE`

**Comment by randombit** [comment]
"AES-128/CTR" works now
