### ISSUE TITLE
Install path ignores --prefix when --destdir is set

### ISSUE THREAD

**Issue by zgyarmati** [randombit/botan#1101]
i'm setting up an OBS rpm build for botan, but i can't figure how the
configure.py scripts designed to work.
For me the expected behavior (coming from autotools and co.) would be that after

./configure.py --destdir=/home/bla/BUILDROOT/ --prefix=/usr

the install tree will be under /home/bla/BUILDROOT/usr, so the following dirs will be created:

/home/bla/BUILDROOT/usr/bin
/home/bla/BUILDROOT/usr/include
...

But actually the --prefix seems to be ignored and the files installed under
/home/bla/BUILDROOT/bin
/home/bla/BUILDROOT/include
...

I could set the whole path '/home/bla/BUILDROOT/usr/' as --prefix, but then
`botan config prefix`  and also the installed .pc pkgconfig file will show that full path,
while the final install dir (after packaging) will be /usr/, so these would be broken.

It might be that i overlooked something, what do you think? For me it seems to be a bug in the build scripts...

I think the preferable behavior would be if the `make install` target would take also
a DESTDIR argument (like autotools and most of the makefile generators do), and install
the whole tree (in the subdirs specified with --libdir, --prefix, etc) under that top-level DESTDIR.

**Comment by webmaster128** [comment]
I think destdir should move out of configure.py into the install step entirely. See also https://github.com/randombit/botan/pull/997

**Comment by zgyarmati** [comment]
Oh, i overlooked that PR but looks good. @danimo, would you update it? (as it conflicts atm), and i would be happy to test it.
