### ISSUE TITLE
botan-cli: Unable to sign certificate from ca cert/key with password

### ISSUE THREAD

**Issue by skajter** [randombit/botan#1104]
Same happened on OSX/Windows, tested on both platforms.

./botan-cli keygen --passphrase=secret >> ca_key.pem
./botan-cli gen_self_signed ca_key.pem ROOT_CA --key-pass="secret" --ca >> ca_crt.crt
./botan-cli keygen >> srv_key.pem
./botan-cli gen_self_signed srv_key.pem Server >> srv_crt.crt
./botan-cli gen_pkcs10 srv_key.pem Server >> srv_csr.pem
./botan-cli sign_cert --ca-key-pass=secret ca_crt.crt srv_key.pem srv_csr.pem >> srv_crt.crt

At end we have 2 certificates: One CA and one for 'Server'.

Problem is that when CA sign CSR, and Server cert is signed by CA, Server cert is not validated in chain.

Im using XCA tool, to have look that is working or not.

**Comment by skajter** [comment]
Typos in command ;) - obviously there no quotes on --key-pass:

`./botan-cli keygen --passphrase=secret > ca_key.pem
./botan-cli gen_self_signed ca_key.pem ROOT_CA --key-pass=secret --ca > ca_crt.crt
./botan-cli keygen > srv_key.pem
./botan-cli gen_self_signed srv_key.pem Server > srv_crt.crt
./botan-cli gen_pkcs10 srv_key.pem Server > srv_csr.pem
./botan-cli sign_cert --ca-key-pass=secret ca_crt.crt srv_key.pem srv_csr.pem > srv_crt.crt`

**Comment by skajter** [comment]
on website from doec:

sign_cert --ca-key-pass= --hash=SHA-256 --duration=365 ca_cert ca_key pkcs10_req

When i use like it should be

./botan-cli sign_cert --ca-key-pass=secret ca_crt.crt ca_key.pem srv_csr.pem

Output:
Error: Invalid argument Decoding error: PKCS #8 private key decoding failed: Invalid argument Decoding error: BER: Tag mismatch when decoding got 22/224 expected 16/32

But when i use sev_key.pem then is sign (no errors), just no validate in chain.

**Comment by securitykernel** [comment]
I looked through the sign_cert CLI code and found a bug. It currently ignores the --ca-key-pass parameter and tries to read the CA key as an unencrypted key, that is the reason for the exception you get. The fix is in https://github.com/randombit/botan/pull/1106, thank you for reporting this bug. It would be nice to hear back from you if the fix works for you.

**Comment by skajter** [comment]
Working like expected! Thanks.

Sorry for long delay on testing phase ... anyway you can have look over test code in:

https://github.com/skajter/botan_qt_test

Idea was to have 'auto build' for botan in qmake environment, then use cli to create all required certificates.
