### ISSUE TITLE
X.509 path validation with unknown critical extended key usages 

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#1105]
The path validation will fail if there is an unknown critical extension. So far so good. But if there is an unknown critical extended key usage the validation will NOT fail. Seems to be a bug.

**Comment by randombit** [comment]
Bug

**Comment by briansmith** [comment]
I don't understand this bug report. The library either understands EKU or it doesn't. If it understands EKU then it should accept it when marked critical.

Whether the EKU extension contains an unknown usage doesn't matter. Either the application doesn't care about which EKU the certificate is valid for (bad form, but allowed), or it does care that 1 or more usages are listed. As long as those usages are listed it doesn't matter if additional, perhaps unrecognized, usages are listed.

**Comment by randombit** [comment]
I think @briansmith is right here - EKU is only expressing some operations for which the key may be used but does not affect certificate verification. So in any case the certificate should verify. The application can/should check and respect the extended usages, but critical vs not doesn't seem to matter in the EKUs interpretation. @neusdan thoughts?

**Comment by randombit** [comment]
Closing as I think briansmiths interpretation is correct. @neusdan feel free to reopen if you think otherwise.
