### ISSUE TITLE
 The botan2.1.0 can compile the debug version？

### ISSUE THREAD

**Issue by huang229** [randombit/botan#1108]
The botan2.1.0 can compile the debug version？thank you！

**Comment by securitykernel** [comment]
If you mean whether you are able to compile botan for debugging, then there are three options to `configure.py`:

* --with-debug-info: include debug symbols
* --no-optimizations: disable all optimizations
* --debug-mode: combines both of the former two options

Usually, you want to use the last option for debugging. See also `./configure.py --help` for a list of all options to configure your botan build.

**Comment by huang229** [comment]
Thank you for your help.   answer:  python configure.py --cc==msvc --debug-mode
