### ISSUE TITLE
http_util and OCSP online checks

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#1109]
During a source review for fixing #1107, I figured that OCSP online checks are guarded by `#if defined(BOTAN_HAS_ONLINE_REVOCATION_CHECKS)` in [x509_path.cpp](src/lib/x509/x509path.cpp). `BOTAN_HAS_ONLINE_REVOCATION_CHECKS` is defined in [x509_path.h](src/lib/x509/x509path.h):

```
#if defined(BOTAN_TARGET_OS_HAS_THREADS) && defined(BOTAN_HAS_HTTP_UTIL)
  #define BOTAN_HAS_ONLINE_REVOCATION_CHECKS
#endif
```

We can assume that nearly every OS has threading support, so it's only about http_util. That means if module http_util is not enabled in the build, OCSP online checks will be silently omitted. In a standard build, http_util will be enabled. But when using one of the module policies bsi, modern or nist, http_util will not be enabled. Can we do better?

I thought about setting `load_on -> auto` for http_util, which would always enable the module unless --no-autoload or --minimized-build is set. http_util does not have any OS dependencies in info.txt, but instead provides an implementation using boost asio (`BOTAN_HAS_BOOST_ASIO`) and Unix sockets (`BOTAN_TARGET_OS_HAS_SOCKETS`). If neither is available, the functions will throw an exception at runtime. For Windows builds without boost though, X.509 path validation will fail when OCSP online checks are made, which is maybe not good behaviour. Is there any alternative solution?

**Comment by slicer4ever** [comment]
I've modified http_util.cpp to support windows by changing the following(built for msvc17):

#elif defined(BOTAN_TARGET_OS_HAS_SOCKETS)
#ifdef _WIN32
#include <winsock2.h>
#include <WS2tcpip.h>

#define close closesocket

int write(int SockFD, const char *Buf, size_t Len) {
	return send(SockFD, Buf, Len, 0);
}

int read(int SockFD, char *Buf, size_t BufLen) {
	return recv(SockFD, Buf, (int)BufLen, 0);
}

typedef size_t ssize_t;
#else
  #include <sys/types.h>
  #include <sys/socket.h>
  #include <netdb.h>
  #include <unistd.h>
  #include <netinet/in.h>
#endif
#else
  //#warning "No network support enabled in http_util"
#endif

**Comment by securitykernel** [comment]
Thanks for the suggestion, I think this is the first step towards improving the situation. Based upon your initial work, I added support for Windows sockets to http_util (and along the way, also to tls_client and tls_server CLI) in #1138.

**Comment by randombit** [comment]
OK with me

**Comment by securitykernel** [comment]
I am wondering whether to put http_util in the required or in the if_available block. Is there a use case where a user wants to disable http_util explicitly, e.g., to disable OCSP online checks on a platform where http_util is not supported and would throw a runtime exception during path validation?

**Comment by randombit** [comment]
Let's do `if_available` for now - I think IncludeOS at least may need some extra help to perform the checks at runtime, and requiring the HTTP module means if there is no network support the whole validation attempt fails which is probably undesirable.

I think the better fix eventually is to change the OCSP online check to gracefully handle HTTP/network level errors (either caused by transient problems or lack of network access). Then we can make http_util mandatory.

**Comment by randombit** [comment]
I believe everything related to this issue is completed.
