### ISSUE TITLE
Botan for Python

### ISSUE THREAD

**Issue by Bobur070** [randombit/botan#1118]
The Error is:
Traceback (most recent call last):
  File "C:/Users/1/PycharmProjects/telegrambot/main.py", line 7, in <module>
    import botan
ImportError: No module named 'botan'

import botan
botan_key = '.................................................'
uid = message.from_user
message_dict = message.to_dict()
event_name = update.message.text
print(botan.track(constants.botan_key,uid, message_dict, event_name))

Please help to resolve this issue

**Comment by securitykernel** [comment]
botan.py was renamed to botan2.py in versions starting from 2.1.0, so you would need to `import botan2.py`. Sorry for the inconvenience.

**Comment by randombit** [comment]
Nothing more to be done here, closing
