### ISSUE TITLE
ANSI X9.23 Nullptr

### ISSUE THREAD

**Issue by JFrangen** [randombit/botan#1126]
According to https://botan.randombit.net/manual/symmetric_crypto.html#modes-of-operation
I do 

std::unique_ptr<Botan::Cipher_Mode> cipher(Botan::get_cipher_mode("AES-128/CBC/ANSI_X9.23",  Botan::ENCRYPTION));

(and I  have also tried many variations of the string ANSI_X9.23 including some variants with "()" after trying to analyse the source code).

The resulting unique ptr is always a pullptr.

std::unique_ptr<Botan::Cipher_Mode> cipher(Botan::get_cipher_mode("AES-128/CBC/PKCS7", Botan::ENCRYPTION));
is working.

What is the correct string for using AES128 CBD and ANSI.

**Comment by randombit** [comment]
You want just "X9.23", no "ANSI_" prefix

**Comment by randombit** [comment]
I think with "X9.23" this works ok, please open a new issue if you're still having problems.
