### ISSUE TITLE
Embedding into CMake project

### ISSUE THREAD

**Issue by nickfromXXII** [randombit/botan#1140]
Is it possiblre to embed Botan 2.x into CMake project?

**Comment by webmaster128** [comment]
The most solid way to do this right now is probably to generate amalgamation files and add those to your existing CMake project. You need one set of amalgamation files per os/cpu

**Comment by nezyaka** [comment]
@webmaster128 Is there another way?

_Sent from my Samsung SM-J510FN using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by webmaster128** [comment]
The two other ways I am aware of are

1. use the Botan build system, build a static or dynamic lib and link this lib from your cmake project
2. try the experimental CMakeLists.txt you get when you configure using `./configure.py --with-cmake [...]`

**Comment by webmaster128** [comment]
Did you find a way that worked for you? Is this issue soved?

**Comment by ksanderon** [comment]
Other way is to use `./configure` (with prefix path specified) and `make` with `install target`

later in your cmake list add something like:
```
find_library(BOTAN2 botan2 PATHS <YOUR INSTALL PREFIX PATH>)
```

look at: [find_library]( https://cmake.org/cmake/help/v3.0/command/find_library.html) for more details.

**Comment by randombit** [comment]
Closing since it's not clear there is anything additional we need to do on our side.

**Comment by loomismeister** [comment]
> The most solid way to do this right now is probably to generate amalgamation files and add those to your existing CMake project. You need one set of amalgamation files per os/cpu

This is not a very scalable solution. Projects will quickly spiral out of control by necessarily including custom hpp/cpp per supported environment.

---

>try the experimental CMakeLists.txt you get when you configure using ./configure.py --with-cmake 

This is closer to a real solution. A proper cmake solution could be done where the botan package is exported. You would then allow developers a sane way of including Botan with the following:
```
find_package(Botan REQUIRED)
add_executable(X main.cpp)
target_link_libraries(X Botan::Botan)
```
However, given that the current botan approach is using python, it could be intractable to maintain a proper cmake export package. The experimental cmakelists that is generated currently --with-cmake in configuration doesn't follow best practices for cmake and rightly warns users not to use it.

---

> Other way is to use `./configure` (with prefix path specified) and `make` with `install target`
> 
> later in your cmake list add something like:
> 
> ```
> find_library(BOTAN2 botan2 PATHS <YOUR INSTALL PREFIX PATH>)
> ```
> look at: [find_library](https://cmake.org/cmake/help/v3.0/command/find_library.html) for more details.

find_library is not a good solution. As soon as you switch environments you are going to run into a nightmare where you have to guess at install paths for the separate systems. 

Its close to what a user is going to be required to do for a real solution given that the library doesn't support proper cmake integration, which is creating a custom FindBotan.cmake module. You can see people are already doing out of necessity in many github projects.
* https://github.com/louiz/batajelo/blob/master/cmake/Modules/FindBOTAN.cmake
* https://lab.louiz.org/louiz/biboumi/blob/master/cmake/Modules/FindBOTAN.cmake
* https://github.com/kaaproject/kaa/blob/master/client/client-multi/client-cpp/Modules/FindBotan.cmake
* https://github.com/niclabs/tchsm-libdtc/blob/master/cmake/FindBotan.cmake
* ...

The list goes on and on with people making custom find modules, but it's the only real solution for a 3rd party library which doesn't support modern cmake usage.

See this section on *If you want it done right do it yourself*
https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/#if-you-want-it-done-right-do-it-yourself

**Comment by mikeloomisgg** [comment]
Thinking about it more, a config file could probably be installed which would allow the desired 
`find_package(Botan REQUIRED)` behavior even though cmake isn't being used as the native build generator.

Instead of --with-cmake creating a cmakelists file that generates the build system, it could just generate an imported library target and then export that for cmake's find_package. This is much like what the FindBotan.cmake file already does when finding the library built as a normal external project.

This is a pretty painless solution to provide cmake support for consumers of the library, as only 1 or 2 files would need to be added. I think a switch would have to be added to the configure.py so you don't force a cmake dependency for anyone that tries to install botan.

**Comment by skrueger8** [comment]
I'm using `FindPkgConfig` with `pkg_check_modules()` for Botan2 in my projects:

```
find_package(PkgConfig)
pkg_check_modules(BOTAN2 botan-2)

if(BOTAN2_FOUND)
  add_executable(botan2_example botan2_example.cpp)
  target_link_libraries(botan2_example PRIVATE ${BOTAN2_LIBRARIES} ${BOTAN2_LDFLAGS})
  target_include_directories(botan2_example PRIVATE ${BOTAN2_INCLUDE_DIRS})
  target_compile_options(botan2_example PRIVATE ${BOTAN2_CFLAGS_OTHER})
endif()
```

But I'd much prefer if botan2 would include a `find_package()` cmake module.
