### ISSUE TITLE
ECDSA signing fails on messages of all zeros

### ISSUE THREAD

**Issue by dewyatt** [randombit/botan#1143]
I noticed that ECDSA raw signing a message of all zeros ends up failing because of the third argument to `mul_add` being 0.

I realize how unlikely it would be for such a digest to be valid, but I still wonder if this would be considered a bug.

https://github.com/riboseinc/rnp/pull/356#issuecomment-320494030

**Comment by randombit** [comment]
I think the restriction in `mul_add` is wrong, and as far as I can tell there is nothing stopping from ECDSA signing a message which hashes to all zeros.
