### ISSUE TITLE
compressed EC public keys

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1159]
Does Botan support serialisation / deserialisation of a 'compressed' representation of an EC public key? (only X coordinate of the point on EC + sign). Any example?
If it doesn't provide facilities for this functionality , out-of-the box, how shall I proceed, any suggestions? I've just finished reading the entire manual in PDF.

**Comment by randombit** [comment]
Yes point compression is supported out of the box (and actually used by default for ECC public key encoding). Point decompression is performed automatically if a compressed point is provided as input to the `OS2ECP` primitive.

Bug that there is nothing mentioning this in the docs.
