### ISSUE TITLE
Missing overrides in some files results in linker error with code built using clang/llvm

### ISSUE THREAD

**Issue by jthomo** [randombit/botan#116]
Sorry I am not sure how to show the patch, but it might be useful for someone if they are having the same problem.

diff -dur a/src/lib/pubkey/curve25519/curve25519.h .b/src/lib/pubkey/curve25519/curve25519.h
--- a/src/lib/pubkey/curve25519/curve25519.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/curve25519/curve25519.h	2015-06-18 22:27:10.272147938 +0000
@@ -19,7 +19,7 @@
 
       size_t estimated_strength() const override { return 128; }
 
-      size_t max_input_bits() const { return 256; }
+      size_t max_input_bits() const override { return 256; }
 
       bool check_key(RandomNumberGenerator& rng, bool strong) const override;
 
diff -dur a/src/lib/pubkey/dl_algo/dl_algo.h .b/src/lib/pubkey/dl_algo/dl_algo.h
--- a/src/lib/pubkey/dl_algo/dl_algo.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/dl_algo/dl_algo.h	2015-06-18 22:27:50.465900130 +0000
@@ -20,11 +20,11 @@
 class BOTAN_DLL DL_Scheme_PublicKey : public virtual Public_Key
    {
    public:
-      bool check_key(RandomNumberGenerator& rng, bool) const;
+      bool check_key(RandomNumberGenerator& rng, bool) const override;
 
-      AlgorithmIdentifier algorithm_identifier() const;
+      AlgorithmIdentifier algorithm_identifier() const override;
 
-      std::vector<byte> x509_subject_public_key() const;
+      std::vector<byte> x509_subject_public_key() const override;
 
       /**
       * Get the DL domain parameters of this key.
@@ -88,7 +88,7 @@
                                        public virtual Private_Key
    {
    public:
-      bool check_key(RandomNumberGenerator& rng, bool) const;
+      bool check_key(RandomNumberGenerator& rng, bool) const override;
 
       /**
       * Get the secret key x.
diff -dur a/src/lib/pubkey/ecc_key/ecc_key.h .b/src/lib/pubkey/ecc_key/ecc_key.h
--- a/src/lib/pubkey/ecc_key/ecc_key.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/ecc_key/ecc_key.h	2015-06-18 22:28:53.137521307 +0000
@@ -44,12 +44,12 @@
       */
       const PointGFp& public_point() const { return public_key; }
 
-      AlgorithmIdentifier algorithm_identifier() const;
+      AlgorithmIdentifier algorithm_identifier() const override;
 
-      std::vector<byte> x509_subject_public_key() const;
+      std::vector<byte> x509_subject_public_key() const override;
 
       bool check_key(RandomNumberGenerator& rng,
-                     bool strong) const;
+                     bool strong) const override;
 
       /**
       * Get the domain parameters of this key.
diff -dur a/src/lib/pubkey/gost_3410/gost_3410.h .b/src/lib/pubkey/gost_3410/gost_3410.h
--- a/src/lib/pubkey/gost_3410/gost_3410.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/gost_3410/gost_3410.h	2015-06-18 22:24:53.081027234 +0000
@@ -42,7 +42,7 @@
       */
       std::string algo_name() const { return "GOST-34.10"; }
 
-      AlgorithmIdentifier algorithm_identifier() const;
+      AlgorithmIdentifier algorithm_identifier() const override;
 
       std::vector<byte> x509_subject_public_key() const;
 
@@ -86,7 +86,7 @@
                            const BigInt& x = 0) :
          EC_PrivateKey(rng, domain, x) {}
 
-      AlgorithmIdentifier pkcs8_algorithm_identifier() const
+      AlgorithmIdentifier pkcs8_algorithm_identifier() const override
          { return EC_PublicKey::algorithm_identifier(); }
    };
 
diff -dur a/src/lib/pubkey/if_algo/if_algo.h .b/src/lib/pubkey/if_algo/if_algo.h
--- a/src/lib/pubkey/if_algo/if_algo.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/if_algo/if_algo.h	2015-06-18 22:26:07.590542822 +0000
@@ -27,11 +27,11 @@
       IF_Scheme_PublicKey(const BigInt& n, const BigInt& e) :
          n(n), e(e) {}
 
-      bool check_key(RandomNumberGenerator& rng, bool) const;
+      bool check_key(RandomNumberGenerator& rng, bool) const override;
 
-      AlgorithmIdentifier algorithm_identifier() const;
+      AlgorithmIdentifier algorithm_identifier() const override;
 
-      std::vector<byte> x509_subject_public_key() const;
+      std::vector<byte> x509_subject_public_key() const override;
 
       /**
       * @return public modulus
@@ -71,7 +71,7 @@
                            const AlgorithmIdentifier& alg_id,
                            const secure_vector<byte>& key_bits);
 
-      bool check_key(RandomNumberGenerator& rng, bool) const;
+      bool check_key(RandomNumberGenerator& rng, bool) const override;
 
       /**
       * Get the first prime p.
diff -dur a/src/lib/pubkey/mce/mceliece_key.h .b/src/lib/pubkey/mce/mceliece_key.h
--- a/src/lib/pubkey/mce/mceliece_key.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/mce/mceliece_key.h	2015-06-18 22:24:03.181361945 +0000
@@ -44,7 +44,7 @@
          return get_message_word_bit_length();
          };
 
-      AlgorithmIdentifier algorithm_identifier() const;
+      AlgorithmIdentifier algorithm_identifier() const override;
 
       size_t estimated_strength() const;
 
diff -dur a/src/lib/pubkey/pk_keys.h .b/src/lib/pubkey/pk_keys.h
--- a/src/lib/pubkey/pk_keys.h	2015-03-30 02:14:22.000000000 +0000
+++ .b/src/lib/pubkey/pk_keys.h	2015-06-18 22:30:46.473856607 +0000
@@ -106,7 +106,7 @@
       * @return PKCS #8 AlgorithmIdentifier for this key
       * Might be different from the X.509 identifier, but normally is not
       */
-      virtual AlgorithmIdentifier pkcs8_algorithm_identifier() const
+      virtual AlgorithmIdentifier pkcs8_algorithm_identifier() const 
          { return algorithm_identifier(); }
 
    protected:

**Comment by webmaster128** [comment]
If you are trying to contribute code, please open a [pull request](https://help.github.com/articles/using-pull-requests/). Otherwise add a detailed explanation about what the issue is and separate Code from the issue text. Thanks.
