### ISSUE TITLE
Visual Studio 2017+ nmake error

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1160]
build\include\botan/build.h(412): fatal error C1189: #error:  "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
NMAKE : fatal error U1077:  (...) return code '0x2'

removing the following line helped
`#if defined(BOTAN_TARGET_ARCH_IS_X86_64) && ((defined(_MSC_VER) && !defined(_WIN64)) || \
                                             (defined(__clang__) && !defined(__x86_64__)) || \
                                             (defined(__GNUG__) && !defined(__x86_64__)))
    #error "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
#endif`

but, then there's another error:
 error C3861: '_umul128': identifier not found

.. =/

....I was running an x86 version of VS command prompt. please close the issue.

**Comment by randombit** [comment]
No problem - the `#error` is there specifically to catch this situation since it happens with some non-zero regularity ;)
