### ISSUE TITLE
amalgemation and compile time errors

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1163]
please delete this post :P I am sorry.. I have unnecessarily  added the 'botan_all.cpp' file to my project. I haven't begun using this library yet but I already almost love it (I've had some experience with libsodium/nacl/bouncy/crypto++ . I love to have Montgomery Curve25519/X25519 **and**.. older secp160r2 in one place. and the library does not intend to protect me from myself. then the lib supports the filters/sinks philosophy but is supposed to work wonderfully without it.... just unbelievable.. and there is a manual in PDF...

**Comment by webmaster128** [comment]
Hi rafalsk, good to here you made it work :) You can close this issue yourself.
