### ISSUE TITLE
 Curve25519 support needs refactoring?

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1165]
The code responsible for handling of Curve25519 and Weiserstrass based EC crypto could be a little more integrated. I am aware of all of the differences but still. 

The question is -  how do I serialise / deserialise Curve25519_PublicKey and Curve25519_PrivateKey ?

`Curve25519_PrivateKey(const AlgorithmIdentifier& alg_id,
                            const secure_vector<uint8_t>& key_bits);

I've found this. What can I pass as 'alg_id` ? 

**Update1:**
ok...I've found..
Curve25519_PrivateKey::private_key_bits() 

and... this
std::vector<uint8_t> Curve25519_PublicKey::public_key_bits() const
   {
   return m_public;
   }

why isn't m_public DER encoded? and the question about alg_id still holds

**Update2:**
I've found alg_id can be anything among { "Curve25519","McEliece",""ECDSA","SM2_Enc",""RSA"", etc.}
That is where the library doesn't feel so well structured. What would be the reason for putting "RSA" as a parameter to 
`Curve25519_PrivateKey(const AlgorithmIdentifier& alg_id,  const secure_vector<uint8_t>& key_bits);
?

**Remarks**
`If we were in the perfect world (and we are not) the documentation could include some description of the lower level functionalities as well. Actually there already is a section in the manual which promises the very thing but it is like 1 page long.``

**Update 3:**
`Curve25519_PublicKey::Curve25519_PublicKey(const AlgorithmIdentifier&,
                                           const std::vector<uint8_t>& key_bits)
   {
   m_public = key_bits;

   size_check(m_public.size(), "public key");
   }
what is the purpose of AlgorithmIdentifier if it is not used anywhere?

**Update 4 **
Curve25519_PublicKey has a couple of constructors. 
one promises to accept a DER encoded key
`/**
      * Create a Curve25519 Public Key.
      * @param alg_id the X.509 algorithm identifier
      * @param key_bits DER encoded public key bits
      */
Curve25519_PublicKey(const AlgorithmIdentifier& alg_id,
                           const std::vector<uint8_t>& key_bits);

yet in the body of the function, alg_id is not used and key_bits is *not* decoded, just assigned to m_public.
`the very same thing happens in 
 /**
      * Create a Curve25519 Public Key.
      * @param pub 32-byte raw public key
      */
      explicit Curve25519_PublicKey(const std::vector<uint8_t>& pub) : m_public(pub) {}

which is supposed to take RAW data. As of the current state the two constructors introduce confusion while achieving the same thing, which is assigning raw data to m_public.
***Update 5***
The private_key_bits() returns DER encoded data while public_key_bits() returns RAW data which can be misleading.
*Update 6*
The Curve25519_PrivateKey constructor decodes data encoded in BER, while Curve25519_PrivateKey::private_key_bits()  encodes data in *D*ER ??

While it is only a wrapper, as for now, there is a complete chaos in this part of the library.
I haven't dived into the details of the BER/DER implementation and I supposed that you implement only a smalll subset

*Update 7*
I was curious if you really took the effort  to implement a real BER encoder and guess what, it turns out there is none:) everything is done in DER (after quick glance) even though function name promises BER.
`std::vector<uint8_t> Request::BER_encode() const
   {
   return DER_Encoder().start_cons(SEQUENCE)
        .start_cons(SEQUENCE)`
*Update 8*
Refering to enum value by its index is tremendously prone to errors:
`  encode_entries(der, m_alt_info, "DNS", ASN1_Tag(2)); // very often in the code
you already use C++11 so I propose to use the notation of ASN1_Tag::Value instead`
*Update 9*
Some constructors do the size checking / validation others do not

**Comment by randombit** [comment]
> why isn't m_public DER encoded? and the question about alg_id still holds

Don't blame me, that's how the IETF standardized the encoding (see
https://www.ietf.org/id/draft-ietf-curdle-pkix-05.txt for the spec and #1076 for the change). 

> What would be the reason for putting "RSA" as a parameter to `Curve25519_PrivateKey(const AlgorithmIdentifier& alg_id, const secure_vector<uint8_t>& key_bits);

Uh none I can think of? I guess what you mean is, this constructor ignores its argument completely, instead of verifying that the parameters are actually empty. Which it should do.

> Curve25519_PublicKey has a couple of constructors [...]

This is confusing by virtue of the changes made for CURDLE (#1076). The first constructor is used when decoding a value from an ASN.1 subjectPublicKeyInfo. The second is used when you have a raw public key derived from some other means. It so happens that X25519 keys in PKIX are just the raw byte string of the public key with no additional encoding, so the two constructors have much the same effect. This is a purely a coincidence, and before #1076 was not true. If you have a raw octet string, use the second constructor.

> I was curious if you really took the effort to implement a real BER encoder and guess what, it turns out there is none:) everything is done in DER (after quick glance) even though function name promises BER.

Well DER is a strict subset of BER so technically a DER encoder is also a BER encoder... but yes probably those functions would have been better named s/BER/DER/

> Refering to enum value by its index is tremendously prone to errors:

That's not an index into the enum, that's a literal tag value of 2.

**Comment by rafalsk** [comment]
@randombit , kindly thank you for looking into this and for all of your in-depth reponses.

**Comment by rafalsk** [comment]
I haven't compiled with debug symbols but this should be easy to reproduce.
`Botan::AutoSeeded_RNG rng;
Botan::secure_vector<uint8_t> privKeyDER;
Botan::Curve25519_PrivateKey privKey = Botan::Curve25519_PrivateKey(rng);
privKeyDER = privKey.private_key_bits();`
throws "vector<T> too long"
