### ISSUE TITLE
Compiler version detection when creating amalgamation for other platforms

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#1170]
We're creating amalgamation files for all our target systems on one machine, typically a developer's Linux. This is required since we use the simplicity of amalgamation files to be able to copy them into our own build system.

Now with compiler version case distinctions, we cannot configure for other systems anymore. This is not a big deal yet since we're not using the modules requiring a specific version, but it is still an issue for the future.

So I am curious to know how plans are for compiler features before I go into touching configure scripts. The current issue could be fixed by providing a --cc-version at configure time, which skips the automatic check. I remember comments about (configure time) feature detection instead of compiler versions. This makes things nasty since we don't have the chance to provide all those information and keep it up-to-date. Compile time checks may be the better choice in many cases, but they do not really work for enabling/disabling modules.

Is the ability to cross-configure (required by cross-generating of amalgamations) a feature to be preserved at all?

**Comment by randombit** [comment]
Yeah that's a decent use case, and one I hadn't really considered. I could see how you'd want to have one person responsible for upgrading dependencies, then checking the generated source into version control for building on multiple targets.

In the short term, --cc-version flag seems fine.

For feature detection we can do a similar bypass. Whenever I get around to that I will be sure to also support flags like `--with-os-features=getauxval,...` and `--with-cc-features=sha_intrin,...`. Then (on your side) you'd probably have a script for generating the amalgamations on your various targets that specified the relevant flags for your target platforms. Does this seem like it would work?

**Comment by webmaster128** [comment]
> In the short term, --cc-version flag seems fine.

Fine, I can take care of that if you want. Would it be okay to define --cc-version as the minimal compiler version the configuration needs? That would simplify compiler updates as well as improve the apple clang version mapping (e.g. `apple-clang >= 800` => `cc-version >= 3.9`) supporting all apple clang versions, not only the hardcoded ones.

> Then (on your side) you'd probably have a script for generating the amalgamations on your various targets that specified the relevant flags for your target platforms.

Right. Additionally the script applies custom patches to the amalgamation where needed.

> Does this seem like it would work?

Perfect

**Comment by randombit** [comment]
Taking it as the minimum seems fine given the intended usage.
