### ISSUE TITLE
how to specify TLS Extensions

### ISSUE THREAD

**Issue by yutianzhe30** [randombit/botan#1186]
Hello, in my TLS implementation, i want to specify the TLS extenstions. It seems the only way is by editing source codes in /src/lib/tls . I just wonder if there is a better way to do that, thank you

**Comment by randombit** [comment]
Currently there is no better way to control this. I would be open to adding some method that allows the application to control which extensions are sent, can you better explain your use case?

**Comment by randombit** [comment]
@yutianzhe30 There are callbacks now that can be used to control which extensions are set, including removing standard extensions or adding custom ones. This feature will be available starting in Botan 2.5

**Comment by yutianzhe30** [comment]
thank you ,that's great
