### ISSUE TITLE
C++14 compilation

### ISSUE THREAD

**Issue by bazineta** [randombit/botan#1191]
We use Botan in a C++14 application, running on OSX and a few flavors of Linux. In order to preserve what remains of our sanity, the application is always statically linked, we always use clang as the compiler, and always build as a static library.

To paraphrase Yoda, once you start down the C++14 path, forever will it dominate your destiny; you're pretty much committed to using the libc++ version of the library for everything. To accomplish this with Botan, we make the following two modifications:

1. Modify clang.txt to use `-std=c++14 -stdlib=libc++` instead of `-std=c++11`.
2. Modify the Makefile's header.in, appending `%{cc_compile_flags}` to the `LINKER` flag, so that the binary and test builds get the proper flags to link with the stdc library instead of the default.

That works for us, and it's minimally invasive. This issue serves to inform others that might be in the same boat as to how we go about it, and to allow others to say 'hey, you're being an idiot there, here's an easier way to go about that.'

**Comment by randombit** [comment]
Thanks for the note. Questions

- Is it really required to compile botan with `-std=c++14`, or is `-std=c++11 -stdlib=libc++` sufficient?

- Have you tried configuring with `--cc-abi-flags=-stdlib=libc++`? Whatever you pass to that option ends up on both the compile and link invocations, so you probably wouldn't have to edit the makefile anymore.

**Comment by mouse07410** [comment]
I'm using Botan-2 (current Github master) on OS X with `-std=c++11` and everything is fine. For Xcode (clang) you don't have to specify `-stdlib=libc++` (it won't take `libstdc++` anyway).

I suggest that changing the default from C++11 to C++14 is premature at this point. A lot of software around is still at C++11 (or even earlier) level.

**Comment by bazineta** [comment]
Yes, using `--cc-abi-flags=-stdlib=libc++` does indeed appear to be sufficient on all platforms, and therefore doesn't require modifications. Thanks!

**Comment by randombit** [comment]
> I suggest that changing the default from C++11 to C++14 is premature at this point.

Botan-2 is C++11 until the end of time. Botan-3 (whenever it happens, probably ~2019) will involve a refresh of minimum compiler versions and adopting C++14 or more likely C++17.

**Comment by mouse07410** [comment]
> Botan-3 (whenever it happens, probably ~2019) will involve a refresh of minimum compiler versions and adopting C++14 or more likely C++17.

Might I ask what are the plans for Botan-3? I.e., in what way it would differ from -2?  

Also, clang doesn't yet support C++17 (and it is unclear how stable would that support be in 2019, even if included). Probably C++14 is a safer bet, IMHO.

**Comment by bazineta** [comment]
C++17 just closed this week, so I'd think anything about it regarding compiler support to be a bit speculative at present, though historically speaking, clang hasn't let any grass grow under its feet.

However, to summarize the original issue, while our application requires C++14, the library does not. However, inasmuch as we do use the libc++ library, that is required, so use of `--cc-abi-flags=-stdlib=libc++` was required, and does work for us, without any changes required to the distribution.

**Comment by randombit** [comment]
"Clang 5 and later implement all the features of the C++ 2017 Draft International Standard." - http://clang.llvm.org/cxx_status.html And GCC 7 already also has full support. MSVC is still behind but Microsoft has been much better about standards compliance in recent years so I'm sure they'll catch up eventually.

As to major differences between Botan-2 and Botan-3 I couldn't really say at this point. We're still pretty early in the Botan-2 release cycle I probably won't even start thinking about -3 until sometime late next year. In terms of public API changes far fewer than between 1.10 and 2.0, and with a better upgrade path. But obvious features we could make use of would include `std::optional`, generalized `constexpr` and `if constexpr`, the standard filesystem API, structured binding expressions, `__has_include`, etc.

**Comment by ioquatix** [comment]
It doesn't matter whether you build with c++11 or c++14. All c++11 code is forward compatible with c++14, and it shouldn't change the output static library. If your upstream code depends on C++14, that's fine, but it shouldn't affect the compilation of botan?

**Comment by randombit** [comment]
@ioquatix Correct, there should be no issues compiling an application with C++14 (or C++17) against a libbotan compiled with C++11. I kind of referenced that in my first comment without being explicit about it.

(I think there are a few corner-case ABI implications around `constexpr` functions going from C++11 to C++14 due to different rules, but that doesn't affect us anyway because we avoid `constexpr` entirely since it is missing in MSVC 2013.)

**Comment by randombit** [comment]
Some good info here (maybe for the wiki?) but nothing actionable, so closing.
