### ISSUE TITLE
i686 test failures

### ISSUE THREAD

**Issue by bkircher** [randombit/botan#1192]
./botan-test on i686 arch fails, mostly GOST-R-34.11 and GOST 34.10 as far as I can see.

```
Failure 1: GOST-R-34.11-94 producer 'base' unexpected result for hashing
Produced: 6C64FEE4914BC2AE5283B9AA6677FC2F76DCA508F504E475C5D8AA53999D5646
Expected: 981E5F3CA30C841487830F84FB433E13AC1101569B9C13584AC483234CD656C0
XOR Diff: F47AA1D8324746BAD500B62E9D34C23CDACDA45E6E98F72D8F1C2970D54B0086 (124 bits different)
```

53 failures in total.

Complete build log attached.

[build.log.txt](https://github.com/randombit/botan/files/1284186/build.log.txt)

**Comment by randombit** [comment]
Already fixed in master in 3e1312d90, thanks for the report. You can backport that patch if GOST hash matters to you.

**Comment by bkircher** [comment]
Thanks!

(FYI, neither care much for GOST nor i686. I try to get a botan2 package into Fedora. See [here](https://bugzilla.redhat.com/show_bug.cgi?id=1487067). Current Fedora package still based on 1.10)

**Comment by randombit** [comment]
That's great thank you. Definitely open up issues if you run into any other problems
