### ISSUE TITLE
Overly aggressive .gitignore Makefile exclusion

### ISSUE THREAD

**Issue by bazineta** [randombit/botan#1194]
We check all dependencies, such a s Botan, into git. Botan ships with a .gitignore containing `Makefile*`, which results in the following files being excluded from checkin:
```
src/build-data/makefile/*
src/contrib/perl-xs/Makefile.PL
```
It would seem that using `/Makefile` instead of 'Makefile*' in the .gitignore would be the thing.

**Comment by webmaster128** [comment]
On which platform does this happen? Which git version?

Both paths are recognized as changed after file changes on Ubuntu Linux (git version 2.11.0):

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/build-data/makefile/gmake.in
	modified:   src/contrib/perl-xs/Makefile.PL
```

**Comment by bazineta** [comment]
OSX Sierra, using the Tower client, which uses the system git, 2.11.0.

**Comment by webmaster128** [comment]
Okay the second path pattern was only recognized because it is already checked in. Similar new paths like `src/contrib/perl-xs/Makefile.NEWFILE` are ignored.

The first path pattern seems to match because OSX is case-insensitive by default.

The proposed change makes sense to me. Could you open a PR?

**Comment by bazineta** [comment]
Yes, I'll open a PR. Thanks.

**Comment by bazineta** [comment]
PR #1195.

**Comment by randombit** [comment]
Merged, thanks for the report + fix
