### ISSUE TITLE
CLI tests fail on Windows

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1198]
I don't understand the problem, and debugging via CI logging sucks, so I'm just going to skip running the tests on Windows for now. Example run:

https://ci.appveyor.com/project/randombit/botan/build/1.0.2958/job/bmhy8ys9rf09m9ij

```
Running 'python .\src/scripts/cli_tests.py .\botan-cli.exe':
FF.......FFF.....F.....F.......F...F..F...FFF...FFFF..FFFF..FF...FF.F.FFFFFFFFFF.F...F..F...FFF...FFFF..FFFF..FF......FFFFFFFFFFFFF.F.F.F.FFFFF.F.F.F.F.F.F.F.F.F.FFFFFFFFFFFFFF........F.FFF..F...FFFFF....F..FF.FF........F.FF......F.FFFF.....F......FF....FF.FF...FFFFFFFFFFF...FFF....FF...FFF.FFFFF...FFF..F.FF...FFF..FFFF.F.F.F.F.F.F.F.F.FFF.FFFFFFFFFF
======================================================================
FAIL: test_aes-128_cfb_no_001_decrypt (__main__.TestSequence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\src/scripts/cli_tests.py", line 98, in do_test_expected
    self.assertEqual(expected, actual)
AssertionError: '6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710' != u'6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0d0a52eff69f2445df4f9b17ad2b417be66c3710'
...
```

**Comment by webmaster128** [comment]
`'X'` vs. `u'X'` smells like a Python 2 issue. I think this tests are not made to work with Python 2.

**Comment by randombit** [comment]
They work fine under Python 2 on my machine. In addition to the '' vs u'' some of them have different bytes. It may be some kind of encoding issue.

**Comment by webmaster128** [comment]
Right. And even the ones that look similar have different bytes in between

6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e51
30c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710

6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e51
30c81c46a35ce411e5fbc1191a**0d**0a52eff69f2445df4f9b17ad2b417be66c37
10

which is LF in `expected` and CR-LF in `actual`.

**Comment by webmaster128** [comment]
This patch resolves the binary mode issue for std::cout on Windows using Windows specific APIs. std::cout.setf(std::ios::binary) did not work for me but I'm not a pro in C++ streams.

```diff
diff --git a/src/cli/encryption.cpp b/src/cli/encryption.cpp
index a09101f..77e1ade 100644
--- a/src/cli/encryption.cpp
+++ b/src/cli/encryption.cpp
@@ -14,6 +14,9 @@
 #include <iterator>
 #include <sstream>

+#include <io.h>
+#include <fcntl.h>
+
 using namespace Botan;

 namespace Botan_CLI {
@@ -112,6 +115,7 @@ class Encryption : public Command

          auto direction = flag_set("decrypt") ? Cipher_Dir::DECRYPTION : Cipher_Dir::ENCRYPTION;
          auto data = do_crypt(VALID_MODES[mode], input, key, iv, ad, direction);
+         _setmode( _fileno( stdout ),  _O_BINARY );
          std::copy(data.begin(), data.end(), std::ostreambuf_iterator<char>(output()));
          }
    };
```

However, this patch should probably be generalized somehow for all cli interfaces when using the shared output() method.

There are still other failures left but this change helps for a lot of tests.

**Comment by randombit** [comment]
The other half may be related to https://blog.elsdoerfer.name/2008/04/26/sending-binary-data-through-stdout-on-windows/ - so the input maybe is being corrupted as well when its sent by `subprocess`.

Maybe for the CLI tests it is best to extend the encryption tool to support input files (currently only supports stdin, easy addition) and then have the cli tests call it with --output flag + an input file both pointing to temps, and so avoid the whole stdin/stdout issue entirely.

But in any case we'll want something like your patch, this comes up also for hex and base64 decoding, and would apply also to any code doing compression/decompression (that's not implemented currently). But we probably don't want it on all the time, because then text outputs will be misformatted. Hrm. I'll think about this one.
