### ISSUE TITLE
Botan-2 IV carryover in CFB mode is different from Botan-1.10

### ISSUE THREAD

**Issue by librehat** [randombit/botan#1200]
As previously reported in #864 and "fixed" in #1044, the IV carryover for ciphers work fine for stream ciphers such as ChaCha and in CTR modes. However, a different behaviour is demonstrated in Shadowsocks (https://github.com/shadowsocks/shadowsocks-qt5/issues/542)

I've tried out bf-cfb, camellia-128-cfb, and aes-128-cfb, they all failed to connect to previous shadowsocks builds. Meanwhile chacha20, salsa20, aes-128-ctr worked well. Hence I think there is still a "bug" (or say breaking change from Botan-1.10) in CFB mode when nonce needs to be carried over.

**Comment by randombit** [comment]
Ah delightful. Since I tested the change in #1044 against PyCrypto's CFB, likely the problem is actually going to end up being "1.10's CFB is incorrect". So I may need to add some kind of special handling to 2.x CFB so that interop is possible. Anyway I'll take another look at this soon.

**Comment by randombit** [comment]
Confirmed, I have a testcase that shows different behavior between the versions. Blocker for 2.3

**Comment by randombit** [comment]
Ah the problem seems to be in 2.2, feedback_bits=8 works but larger values cause incorrect results when carrying over IV. The test I added in 2.2 only checks 8 bit feedback, not block-size feedback which is what shadowsocks seems to use.

**Comment by randombit** [comment]
@librehat Can you try the patch in https://github.com/randombit/botan/pull/1202?

**Comment by librehat** [comment]
Sure I'll check it out tomorrow when I get some spare time. Thank you!

**Comment by librehat** [comment]
Hi, I can confirm this fixes the problem in CFB mode (tried out with AES-256-CFB)

**Comment by randombit** [comment]
Excellent thank you
