### ISSUE TITLE
older curves

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1201]
I know I know. Thing is I need to use secp128r2. In the current times of blockchain technologies etc. we might want to restrain ourselves from deleting insecurely looking parameter sets as some of us might do have some exotic, yet completely valid, storage-efficient, usage scenarios.

Would you just please skim through the below changes and see if I've forgotten about anything  so to bring secp128r2 back to life? thanks.

in Oids.cpp
added line:
`"if (name == "secp128r2") return OID("1.3.132.0.29");"`

in ec_named.cpp in PEM_for_named_group
added line:
```
"	if (name == "secp128r2")
		return
		"-----BEGIN EC PARAMETERS-----"
		"MH8CAQEwHAYHKoZIzj0BAQIRAP////3///////////////8wJAQQ1gMZmNGzu/6/"
		"Wcybv/mu4QQQXu78o4DQKRncLGVYu22KXQQhBHtqpdheVymD5vsyp83rwUAntpFq"
		"iU067nEG/oBfw0tEAhA/////f////74AJHIGE7WjAgEE"
		"-----END EC PARAMETERS-----";"
```

in botan_all.cpp in PEM_for_named_group
added line:
```
"if (name == "secp128r2")
		return
		"-----BEGIN EC PARAMETERS-----"
		"MH8CAQEwHAYHKoZIzj0BAQIRAP////3///////////////8wJAQQ1gMZmNGzu/6/"
		"Wcybv/mu4QQQXu78o4DQKRncLGVYu22KXQQhBHtqpdheVymD5vsyp83rwUAntpFq"
		"iU067nEG/oBfw0tEAhA/////f////74AJHIGE7WjAgEE"
		"-----END EC PARAMETERS-----";"
```

in botan_all.cpp lookup
added line:
`if (name == "secp128r2") return OID("1.3.132.0.29");`

**Comment by randombit** [comment]
That looks about right, though`botan_all.cpp` is a generated file so you should need to edit it, just regenerate after modifying the source.

TBH I'm pretty skeptical there is much valid use case for `secp128r2` given it can be broken by anyone able to rent some hardware on EC2 for a few weeks (days?)

Anyway if you really want it, there is an easier escape hatch available to you than editing the source:

./configure.py --house-curve=curve.pem,secp128r2,1.3.132.0.29,fe99

The first three fields should be obvious, the last field (fe99) is the identifier used in TLS negotiation and must be in the range 0xfe00 to 0xfeff. Here I picked fe99 arbitrarily.

**Comment by rafalsk** [comment]
@randombit , so there still is an escape hatch, magnificent peace of work.

I shall take to heart your advise. The curve would be used to encrypt data which is to be made public in a matter of seconds / hours anyway. This part of the system, constitutes sort of a 'game' in which it doesn't pay the attacker to attempt to crack the encryption, since the potential costs of doing so would be incomperably lower than the reward. As a result, it is better for a potential 'attacker' to wait.
