### ISSUE TITLE
BER encoder and secure_vector

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1204]
is there / could there be a way to get a regular std::vector out of  DER_Encoder::get_contents() ? Just in case someone wanted to encode data which is not confidential.

**Update:** I've found the _Botan::unlock_ method which converts from secure_vector to std::vector. Just a small idea. Will close soon.

**Comment by randombit** [comment]
Yes in many cases the overhead of the pool allocate / memory zeroing is unnecessary and it would be nice if there was some way to indicate that storing as a `std::vector` is ok. The ASN.1 code is pretty old and not very flexible, there is a major redesign on the roadmap but is probably 1-2 years away.

There is also `DER_Encoder::get_contents_unlocked` which just calls `unlock` under the hood.

**Comment by noloader** [comment]
> Yes in many cases the overhead of the pool allocate / memory zeroing is unnecessary and it would be nice if there was some way to indicate that storing as a std::vector is ok. 

Related, see [Issue 346, Security issue (DoS) in Crypto++ ASN1 decoder](https://github.com/weidai11/cryptopp/issues/346). It caught a CVE.

The Crypto++ library had to add a `SetMark` method in its secure allocator so the over-commit would not be zeroized and lead to a transient DoS. The idea is, if `SetMark` is not called then the entire contents are zeroized. If an application calls `SetMark`, they can control how many bytes are zeroized before an exception is thrown.

**Comment by rafalsk** [comment]
Thank you for all the feedback and honest responses. 
I've been working now and will be working with Botan for 10+ hours a day for the foreseeable future to come and so the secure_vector subject could be worked around once more, especially the places where it is being used as in the example of values returned by BER/DER coders and public keys. I begun to incoprorate Botn's secure_vectors into the rest of the project where applicable and been advertising the library in IRC. very very good project.

**Comment by randombit** [comment]
Closing. Full support of this is on the roadmap but not coming to botan2.
