### ISSUE TITLE
Decrypt RSA encrypted payload in Java

### ISSUE THREAD

**Issue by stefanmoro** [randombit/botan#1225]
Hi,

I'm currently building a system where I want to encrypt a 16byte value using a 2048 bit RSA key in C++ using botan and then decrypt that value in Java using JCE. The key is created using openssl and the public key is exported to DER and PEM formats. I'm using the RSA/ECB/OAEPWithSHA-256AndMGF1Padding transformation in Java and “EME1(SHA-256)” encryption algorithms and padding scheme in botan.

When encrypting/decrypting in Java using the generated private/public key, everything works fine:

```java
        // Init RSA encrypt cipher
        Cipher rsaEncryptCipher;
        File pubFile = new File("pubkey.der");
        FileInputStream pubFin = new FileInputStream(pubFile);
        byte[] publicKeyByteArray = new byte[(int)pubFile.length()];
        pubFin.read(publicKeyByteArray);
        final PublicKey publicKey = KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(publicKeyByteArray));
        rsaEncryptCipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        rsaEncryptCipher.init(Cipher.ENCRYPT_MODE, publicKey);

        // Init RSA decrypt cipher
        Cipher rsaDecryptCipher;
        File priFile = new File("prikey.der");
        FileInputStream priFin = new FileInputStream(priFile);
        byte[] privateKeyByteArray = new byte[(int)priFile.length()];
        priFin.read(privateKeyByteArray);
        final PrivateKey privateKey = KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(privateKeyByteArray));
        rsaDecryptCipher = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        rsaDecryptCipher.init(Cipher.DECRYPT_MODE, privateKey);

        // Run test
        final byte[] originalText = DatatypeConverter.parseHexBinary("DEADBEEFDEADBEEFDEADBEEFDEADBEEF");
        System.out.println("Original: " + DatatypeConverter.printHexBinary(originalText));
        final byte[] cipherText = rsaEncryptCipher.doFinal(originalText);
        System.out.println("Cipher  : " + DatatypeConverter.printHexBinary(cipherText));
        final byte[] plainText = rsaDecryptCipher.doFinal(cipherText);
        System.out.println("Plain   : " + DatatypeConverter.printHexBinary(plainText));
```
Plain ends up the same as original and the ciphered is 256 bytes of jibberish.

However, when I use the following C++ code to encrypt a value:
```c++
    std::string originalText("DEADBEEFDEADBEEFDEADBEEFDEADBEEF");
    std::vector<uint8_t> originalTextBytes = Botan::hex_decode(originalText);

    // Load key
    Botan::Public_Key* pubKey = Botan::X509::load_key("pubkey.der");

    // Encrypt with pk
    std::unique_ptr<Botan::RandomNumberGenerator> rng(new Botan::AutoSeeded_RNG);
    Botan::PK_Encryptor_EME enc(*pubKey, *rng.get(), "EME1(SHA-256)");
    std::vector<uint8_t> ct = enc.encrypt(originalTextBytes, *rng.get());

    std::cout << "CIPHERTEXT: " << Botan::hex_encode(ct) << std::endl;
}
```

And then run that resulting ciphertext through the Java decryption, I get the following error:
```java
javax.crypto.BadPaddingException: Decryption error
        at sun.security.rsa.RSAPadding.unpadOAEP(RSAPadding.java:499)
        at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:293)
        at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
        at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)

```

Doesn't "EME1(SHA-256)" correspond to the Java "RSA/ECB/OAEPWithSHA-256AndMGF1Padding"? If not, what is the recommended padding scheme to use in java and botan to get this to work.

Thanks
Stefan

**Comment by stefanmoro** [comment]
Update:
I just tried using "RSA/ECB/OAEPWithSHA-1AndMGF1Padding" transformation in Java and “EME1(SHA-1)” encryption algorithms and padding scheme in botan and that worked.

Do you guys have any clues to why this works but not the SHA-256 solution?
Are there any major drawbacks, security or otherwise, with using SHA-1 instead of 256?

Thanks

**Comment by randombit** [comment]
I am not so familiar with JCE but this stackoverflow post

https://stackoverflow.com/questions/32161720/breaking-down-rsa-ecb-oaepwithsha-256andmgf1padding

suggests that JCE "OAEPWithSHA-256AndMGF1Padding" is actually SHA-256 plus MGF1 with SHA-1, whereas botan uses the same hash for both operations. Which would explain why SHA-1 works (SHA-1 + MGF/SHA-1 on both sides) but SHA-256 doesn't (SHA-256 + MGF/SHA-1 vs SHA-256 + MGF1/SHA-256).

The answer in that post suggests using JCE's `OAEPParameterSpec` and it seems would allow using SHA-256 for the MGF1 operation as well. Alternately, OAEP with SHA-1 is probably fine, collision attacks are not an issue. Though SHA-256 is certainly a better choice these days.

**Comment by stefanmoro** [comment]
Jack,

Thanks for the quick feedback and pointing me to that post.
It turns out to be exactly like you said, i need to force SHA-256 for the MGF1 operation as well which can be accomplished by:
```java
    OAEPParameterSpec oaepParams = new OAEPParameterSpec(
                "SHA-256", "MGF1", new MGF1ParameterSpec("SHA-256"), PSource.PSpecified.DEFAULT);
    rsaDecryptCipher.init(Cipher.DECRYPT_MODE, privateKey, oaepParams);
```

Many thanks!

**Comment by randombit** [comment]
I should mention that with #1503 merged we now support Java's "RSA/ECB/OAEPWithSHA-256AndMGF1Padding" with "OAEP(SHA-256,MGF1(SHA-1))"
