### ISSUE TITLE
Align usage of string for SHA-1/SHA-160/SHA1

### ISSUE THREAD

**Issue by ma30002000** [randombit/botan#1235]
In hash_id.cpp and hash.cpp, the check for SHA_160 is
`if (name == "SHA-160" || name == "SHA-1" || name == "SHA1")`
while 
openssl_hash.cpp features
`if(name == "SHA-160")`
and
bearssl_hash.cpp uses
`if(name == "SHA-160" || name == "SHA-1")`

There are also several more checks only for "SHA-160" and "SHA-1" only distributed throughout the code. In my case trying to use the ECDHE_RSA_WITH_AES_256_CBC_SHA via OpenSSL did not succeed.
Adapting the check in openssl_hash.cpp to the one in hash_id.cpp made it work.
Shouldnt these strings/checks be aligned? Why are there three identifiers for the (apparently) same thing anyway?

**Comment by randombit** [comment]
> Why are there three identifiers for the (apparently) same thing anyway?

Various bad historical reasons.

> Shouldnt these strings/checks be aligned?

Yes

**Comment by ma30002000** [comment]
Should the strings be aligned (if yes, to which one) or the checks?

**Comment by randombit** [comment]
Anywhere any of these strings is accepted, all of them should be.

Ie any such comparison should be 
`if (name == "SHA-160" || name == "SHA-1" || name == "SHA1")`
