### ISSUE TITLE
data_src.cpp has a missing include

### ISSUE THREAD

**Issue by fwsGonzo** [randombit/botan#1238]
When building for IncludeOS it has a special `#if defined (...OS_HAS_FILESYSTEM)` which might interfere with the relatively new `cast_uint8_ptr_to_char`:

```c++
./src/lib/utils/data_src.cpp:109:12: error: implicit instantiation of undefined template
      'std::__1::basic_istream<char, std::__1::char_traits<char> >'
   m_source.read(cast_uint8_ptr_to_char(out), length);
```

It might just be safe to remove the if defined altogether. :+1: 
I would have made a PR but I'm not sure how kosher it is to just remove an intentional ifdef like that. :cactus:

**Comment by randombit** [comment]
Thanks for the report, fixed now.

Does IncludeOS have a filesystem library now? If so we can enable it for IncludeOS, but I'd be inclined to keep the guard macros since we may want it for other filesystem free targets in the future.
