### ISSUE TITLE
Incorrect Issuer field in the CRL signed by intermediate CA Certificate

### ISSUE THREAD

**Issue by RavilN** [randombit/botan#1242]
Use case: I have CA Certificate B, which is signed by CA Certificate A, which are created by third party application XCA. These certificates with private keys are imported using Botan.
When I create new CRL or update existing CRL for CA Certificate B using Botan, save it into file, and open by Windows viewer, then it shows that issuer of that CRL is A. 
But actual issuer of the CRL should be B (subject of the CA Certificate, used to sign the CRL).
When I try to use this CRL in application, which uses MbedTls to validate CRLs, validation fails.

If I generate and export CRL for CA Certificate B by that third party application XCA, then for it Windows displays correct issuer - B.

So apparently Botan somehow puts CA Certificate's issuer name into CRL, instead of subject name.
Observed in Botan version 2.1.0. I did not see in Release Notes for followinf versions that this kind issue was fixed, therefore did not test with latest released version.

**Comment by randombit** [comment]
Very strange, I don't have time to investigate this right now but it definitely sounds like a bug.

**Comment by randombit** [comment]
Wow, turns out to be a very simple bug - we always put the wrong field in the CRL (the issuer of the CA certificate, vs the subject of the CA certificate). This was missed by the test suite which only tests creating CRL from a self-signed root, in which case the subject and issuer were the same. This should be fixed now in master, thank you very much for the report.

**Comment by randombit** [comment]
This fix will be released in 2.4.0, which is scheduled for early January.

**Comment by RavilN** [comment]
Hi,
I have tried to apply the fix to version 2.3.0, and confirming that now the issue is resolved.
Thank you for your work!
