### ISSUE TITLE
Varying results for X509 path validation

### ISSUE THREAD

**Issue by fweissberg** [randombit/botan#1283]
Hi everyone,

consider the following X509 certificate hierarchy. Apologies for the 'graphics' but my efforts to paste nice ascii art failed.

(1)(Test Root)--->(Test Sub CA)--->(Test EE)
(2)(Untrusted Root)-->(Test Sub CA)--->(Test EE)
(The issuer for Test EE is Test Sub CA. There exist two certificate files containing a certificate for "Test Sub CA, the first is issued by Test Root, the other is issued by Untrusted Root)

In particular, the issuer DN for the Test EE certificate is ambiguous. There are two potentially valid certificates for Test Sub CA. Generally and in practice, both certificates for Test Sub CA could be valid in overlapping time intervals. In this case, they would probably be issued by the same CA.

Currently, when looking for the issuer of a certificate, Botan will find the first certificate with matching DN and key identifier if available. Therefore, the ordering of certificates in the certstores and vectors given to PKIX::build_certificate_path matter.

In this case, if PKIX::build_certificate_path builds path (2), the verification fails while there exists a valid path (1) given all the certificates.

It's not too hard to write a function that builds all possible paths (if we still assume that our certificate hierarchy is a tree or if we detect cycles). x509_path_validate could then be rewritten such that it checks all the constructed paths. However, it's not immediately clear to me how to handle the errors that are encountered while building and validating.

For example, if we built more than one path and later notice that one of them is not valid due to a wrong signature, do we want to make the caller notice? If multiple paths are built and all of them are invalid, which error do we show. All of them? What about errors while building the path? Maybe we encounter a cycle and want to make the caller notice this.

So far, x509_path_validate only returns one Path_Validation_Result. This would need to change if detailed error reporting on multiple possible paths is desired.

Any thoughts on the subject?

**Comment by randombit** [comment]
Interesting issue, thanks for raising this.

> (1)(Test Root)--->(Test Sub CA)--->(Test EE)
> (2)(Untrusted Root)-->(Test Sub CA)--->(Test EE)

My first inclination here is that there is no reason to return multiple results, as long as we can find at least one path that does successfully validate. That is, the user does not (typically) care that there is some alternate path that could be constructed (but would not validate), as long as there is at least one path (ending in a trusted root) that *does* validate.

It's a little trickier if no path validates; if we found multiple (potentially valid) paths, but none of them validate, we potentially have two different error results, and no real way of telling which one is more "useful" to the user. I suppose in that case, what we can do is have a new API which returns a vector of validation results. If validation is successful, it returns just the successful validation. If it failed, it returns all the failed paths/results. Then the existing functions (which only return a single validation result) would return just a single result arbitrarily (eg the first element of the vector). Applications which are interested in seeing all of the failed validation results can use the new API.

I'm curious how OpenSSL, NSS etc behave in such situations.

If you happen to have an existing set of certificates (ideally actually generated by a commercial CA) that demonstrate the issue that you can share, that would be very helpful.

**Comment by fweissberg** [comment]
Thanks for your reply. Your suggestions make sense to me.

Sadly, the status of the set of certificates is unclear at the moment. This set (or a version of it)  is meant to be contributed back to botan along with a proposed patch in the end.

I will not be able to work on the issue next week. However, I hope that I can come back to you with something the week after.

**Comment by fweissberg** [comment]
Here is the set of certificates I used:
[CERT_PATH_COMMON_14.tar.gz](https://github.com/randombit/botan/files/1477608/CERT_PATH_COMMON_14.tar.gz)

It was not generated by a commercial CA but it is part of a larger set of test cases we are currently working on.
I expect to be working on this particular issue next week.

**Comment by randombit** [comment]
Fixed with #1363 right?

**Comment by fweissberg** [comment]
That's right. In fact, the test case referenced in my last comment was merged with #1363, as well.
