### ISSUE TITLE
Is there a way to use custom key for AES 256

### ISSUE THREAD

**Issue by midasSSS** [randombit/botan#1288]
I need to set one custom key, e.g. 

> g88MdhDZXpf46974H8pday2PJ3XCiPnT

in order to access API. What is the way to encrypt and decrypt string in this case. I am using c++

**Comment by randombit** [comment]
Uh, not sure I understand what you mean by "custom key". That key looks to be base64 encoded. So you would first decode it to a binary string (using utils in `botan/base64.h`), and then with the binary value of the string in hand call `set_key` on an `AES_256` object. Then `encrypt`, `decrypt` as required.

**Comment by randombit** [comment]
The key you posted seems to be 192 bits so that's what I used here...

```
#include <botan/aes.h>
#include <botan/base64.h>

using namespace Botan;

int main()
   {
   AES_192 aes;
   aes.set_key(base64_decode("g88MdhDZXpf46974H8pday2PJ3XCiPnT"));

   uint8_t block[16] = { 0 };

   aes.encrypt(block);
   }
```

**Comment by randombit** [comment]
This is just doing ECB mode. If you need something like CBC you need a `Cipher_Mode` class, read the docs here https://botan.randombit.net/manual/symmetric_crypto.html

**Comment by midasSSS** [comment]
Thank you. And how it should be if I need to encrypt a specific string, e.g. "Test string"? Because I need to pass encrypted string to API.

**Comment by randombit** [comment]
Well, format it into 16 byte increments (presumably the API docs for whatever you're talking to specify exactly how that should look), then call encrypt?

**Comment by midasSSS** [comment]
What am I doing wrong? I understand that it looks delirious)))

`AES_192 aes;`
   ` aes.set_key(base64_decode("g88MdhDZXpf46974H8pday2PJ3XCiPnT"));`
    `Botan::AutoSeeded_RNG rng;`
    `Botan::InitializationVector IV(rng, 16);`
   ` Botan::Pipe pipe(Botan::get_cipher("AES-256/CBC", aes, IV, Botan::ENCRYPTION), new Botan::Hex_Encoder);`
   ` pipe.process_msg("Test string");`
    `std::string str = pipe.read_all_as_string(0);`
   ` uint8_t block[16] = { 0 };`
    `aes.encrypt(block);`

**Comment by randombit** [comment]
That seems fine, assuming the API is expecting CBC ciphertexts

**Comment by midasSSS** [comment]
I get errors with this code, what should I modify? The API just requires to encrypt (aes-256-cbc) the string with the key provided above. Can you provide me the final code?

**Comment by randombit** [comment]
> The API just requires to encrypt (aes-256-cbc) the string with the key provided above.

That's not possible, because you posted a 192 bit key...

**Comment by midasSSS** [comment]
Ok, can you provide if this is the key: 

> 695111980410A4C8E5154DEC4B40B9BF4128C722E2DABA0BB9267B0AF7083CB1

?

**Comment by randombit** [comment]
Yeah, that's 64 hex chars == 32 bytes == 256 bits

**Comment by midasSSS** [comment]
That's right! But I mean c++ code

**Comment by randombit** [comment]
```
Botan::AutoSeeded_RNG rng;
Botan::InitializationVector IV(rng, 16);
Botan::SymmetricKey key("695111980410A4C8E5154DEC4B40B9BF4128C722E2DABA0BB9267B0AF7083CB1");
Botan::Pipe pipe(Botan::get_cipher("AES-256/CBC", key, IV, Botan::ENCRYPTION), new Botan::Hex_Encoder);
pipe.process_msg("Test string");
std::string str = pipe.read_all_as_string(0);
```

**Comment by midasSSS** [comment]
That is great, thank you! Just in case if I need 192 byte key, what will be the code?

**Comment by randombit** [comment]
Exactly the same except "AES-192/CBC"
