### ISSUE TITLE
TLS Policies marked final

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#1292]
In 27482d71e00dcf106735ef824ded70cf25c6150f, amongst others, the `TLS_Policy` instances were marked as `final`. Before, I used a custom policy in my application by deriving from `BSI_TR_02102_2` and limiting the possible ciphersuites by overriding a few virtual methods, like so:

```c++
class ClientPolicy : public Botan::TLS::BSI_TR_02102_2
{
	public:
		std::vector<std::string> allowed_ciphers() const override
		{
			return { "AES-256/GCM" };
		}

		std::vector<std::string> allowed_signature_hashes() const override
		{
			return { "SHA-384" };
		}

		std::vector<std::string> allowed_macs() const override
		{
			return { "AEAD" };
		}

		std::vector<std::string> allowed_key_exchange_methods() const override
		{
			return { "DH" };
		}

		std::vector<std::string> allowed_signature_methods() const override
		{
			return { "RSA" };
		}

		std::vector<std::string> allowed_ecc_curves() const override
		{
			// currently we don't support ECC
			return {};
		}

		bool require_cert_revocation_info() const override
		{
			// currently we don't want any CRL or OCSP checks
			return false;
		}
};
```

Now with `BSI_TR_02102_2` marked as final, I can no longer derive from it, forcing me to either copy member function implementations from it into my policy class, or by holding a `BSI_TR_02102_2` member and writing out all virtual methods of my policy class to call the member functions of `BSI_TR_02102_2`. Neither is very comfortable. I wonder whether this is a valid use case to have the policy classes not being marked as `final`.

**Comment by randombit** [comment]
What you're doing seems totally reasonable to me - the policies should not be `final`. I will revert.

**Comment by randombit** [comment]
Fixed, thanks

**Comment by securitykernel** [comment]
Nice, thanks!
