### ISSUE TITLE
Using std::string with Botan::secure_allocator

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#1295]
Is this somehow possible? Something like this:

```C++
using secure_string = std::basic_string<char, std::char_traits<char>, Botan::secure_allocator<char> >;	
secure_string test = "abcd";
```

This gives some compile errors. My guess is that the `Botan::secure_allocator` has to be extended to support this.

**Comment by randombit** [comment]
Both g++ 7.2 and clang++ 5.0 compile that without problems. Maybe missing something MSVC needs though.

**Comment by randombit** [comment]
This http://forums.codeguru.com/showthread.php?485765-basic_string-allocator hints the allocator needs `rebind` for `std::string` to work, maybe give it a try.

**Comment by neusdan** [comment]
Awesome thanks. I'll prepare a PR.
