### ISSUE TITLE
Remove exceptions?

### ISSUE THREAD

**Issue by ruipacheco** [randombit/botan#1299]
So I feel this is a moonshot but worth thinking about:

Exceptions are hard to track and incur a significant performance cost and I'd like my code to build with `-fno-exceptions`. C++11 includes `<system_error>`, a way to standardise the use of error codes. [This](https://stackoverflow.com/questions/21821673/understanding-the-system-error-facility-in-c11) and [this](https://akrzemi1.wordpress.com/2017/07/12/your-own-error-code/) are good examples on how to use it.

Would it be feasible to remove exceptions from Botan and replace them with `std::error_code`?

**Comment by randombit** [comment]
I agree there are good reasons to use error returns vs exceptions (in at least some situations), but that would be a huge API change at this point, so not on the table for Botan-2.

When we finally adopt C++17 (in 3.x, this is years away) we can use `std::variant` and `std::optional` and it would be easier to create APIs that return error codes. But being able to remove all throws and and disable exception handling entirely is extremely unlikely.

**Comment by ruipacheco** [comment]
I don't think it's difficult given that you throw exceptions in only a few places. The hard part would be on how to handle exceptions with dynamic string creation, ie, `"This happened because " + ec.message()`.

But I hear you and I will close the issue.
