### ISSUE TITLE
Botan::TLS::Channel::peer_cert_chain() returns empty list on resumed connections

### ISSUE THREAD

**Issue by ma30002000** [randombit/botan#1303]
Botan::TLS::Channel::peer_cert_chain() returns an empty list on resumed TLS connections although the peer certificate is serialized in the session cache information.

This is due to peer_cert_chain() accessing channel->m_active_state->m_server_certs->m_certs, which is empty since it was never set. On a non-resumed key exchange, this field is set on receipt of the certificate (tls_client.cpp line 373 (master). If I add the following to line 169 in tls_client.cpp (and add a corresponding constructor to Botan::TLS::Certificate), it works:
`state.server_certs(new Certificate(session_info.peer_certs()));`
I am however not sure on the implications of that change. Probably something similar needs to be done on the server side as well...

```
diff --git a/src/lib/tls/tls_messages.h b/src/lib/tls/tls_messages.h
index 4370f6fe2..6c7166341 100644
--- a/src/lib/tls/tls_messages.h
+++ b/src/lib/tls/tls_messages.h
@@ -364,6 +364,7 @@ class BOTAN_UNSTABLE_API Certificate final : public Handshake_Message
       size_t count() const { return m_certs.size(); }
       bool empty() const { return m_certs.empty(); }
 
+       Certificate(const std::vector<X509_Certificate>& cert_list);
       Certificate(Handshake_IO& io,
                   Handshake_Hash& hash,
                   const std::vector<X509_Certificate>& certs);
diff --git a/src/lib/tls/msg_certificate.cpp b/src/lib/tls/msg_certificate.cpp
index a2a48ceea..151d28612 100644
--- a/src/lib/tls/msg_certificate.cpp
+++ b/src/lib/tls/msg_certificate.cpp
@@ -17,6 +17,8 @@ namespace Botan {
 
 namespace TLS {
 
+Certificate::Certificate(const std::vector<X509_Certificate>& cert_list) : m_certs(cert_list) {}
+
 /**
 * Create a new Certificate message
 */
diff --git a/src/lib/tls/tls_client.cpp b/src/lib/tls/tls_client.cpp
index ce19f04c9..a54d1b55e 100644
--- a/src/lib/tls/tls_client.cpp
+++ b/src/lib/tls/tls_client.cpp
@@ -167,6 +167,7 @@ void Client::send_client_hello(Handshake_State& state_base,
                                    next_protocols));
 
                state.resume_master_secret = session_info.master_secret();
+                state.server_certs(new Certificate(session_info.peer_certs()));
                }
             }
          }

```

**Comment by randombit** [comment]
Thanks for raising. I'm not sure if the patch you propose is exactly the fix we want but I'll look at it more soon.

**Comment by randombit** [comment]
This also affects server-side sessions that used client certificate authentication

**Comment by randombit** [comment]
@ma30002000 I believe with #1342 this is now fixed in master, though so far I've only done manual testing (ie there is no unit test that confirms the fix). It would be great if you could confirm the issue is resolved with your application.
