### ISSUE TITLE
Build fails on FreeBSD GCC 4.8 due to missing std::to_string

### ISSUE THREAD

**Issue by ruipacheco** [randombit/botan#1305]
I'm trying to build the latest botan on the latest FreeBSD with gcc48 and get the following error:

```
../src/external/botan_all.h: In constructor 'Botan::Invalid_Key_Length::Invalid_Key_Length(const string&, std::size_t)':
../src/external/botan_all.h:1255:27: error: 'to_string' is not a member of 'std'
                           std::to_string(length))
                           ^
../src/external/botan_all.h: In constructor 'Botan::Invalid_IV_Length::Invalid_IV_Length(const string&, std::size_t)':
../src/external/botan_all.h:1266:42: error: 'to_string' is not a member of 'std'
          Invalid_Argument("IV length " + std::to_string(bad_len) +
                                          ^
../src/external/botan_all.h: In member function 'Botan::BER_Decoder& Botan::BER_Decoder::get_next_value(T&, Botan::ASN1_Tag, Botan::ASN1_Tag)':
../src/external/botan_all.h:2960:21: error: 'to_string' is not a member of 'std'
                     std::to_string(obj.value.size()) +
...
../src/external/botan_all.h:2962:21: error: 'to_string' is not a member of 'std'
                     std::to_string(sizeof(T)));
```

This code works under gcc48 on the latest macOS.

**Comment by randombit** [comment]
This is strange. `std::to_string` is supposed to be defined in `<string>` which we include at the top of the exception header.  Does this compile?

```
#include <string>

int main()
{
    std::to_string(0);
    return 0;
}
```

This https://stackoverflow.com/questions/26832199/getting-gcc-in-c11-mode-to-work-on-freebsd suggests adding `-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH -D_GLIBCXX_USE_C99_MATH_TR1`

Clang may be better supported than GCC on FreeBSD these days.

**Comment by ruipacheco** [comment]
```
ruipacheco@freebsd ~/d/c/ninja> g++48 test.cpp 
test.cpp: In function 'int main()':
test.cpp:5:5: error: 'to_string' is not a member of 'std'
     std::to_string(0);
     ^
ruipacheco@freebsd ~/d/c/ninja> g++48 -D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH -D_GLIBCXX_USE_C99_MATH_TR1 test.cpp  
test.cpp: In function 'int main()':
test.cpp:5:5: error: 'to_string' is not a member of 'std'
     std::to_string(0);
     ^
ruipacheco@freebsd ~/d/c/ninja> 
```

I think I passed the flags correctly?

**Comment by webmaster128** [comment]
Are you in c++11 mode?

**Comment by ruipacheco** [comment]
The CMake for the original error is:

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`

**Comment by ruipacheco** [comment]
`g++48 -D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH -D_GLIBCXX_USE_C99_MATH_TR1 -std=c++11 test.cpp  `

Seems to work for the small test. I'll review my CMake file but it's the exact same I use for FreeBSD.

**Comment by ruipacheco** [comment]
From my build.ninja on FreeBSD:

`FLAGS = -DASIO_STANDALONE -std=c++11 -pedantic -Wno-padded -Wno-undef -Wno-old-style-cast -gdwarf-2 -g -lstdc++ -rpath=/usr/local/lib/gcc48 -g   -std=gnu++11`

I believe all is correct.

**Comment by ruipacheco** [comment]
```
ruipacheco@freebsd ~/d/c/ninja> g++48 -std=c++11 test.cpp  
test.cpp: In function 'int main()':
test.cpp:5:5: error: 'to_string' is not a member of 'std'
     std::to_string(0);
     ^

```

**Comment by ruipacheco** [comment]
I fixed my issue on FreeBSD by passing `-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH -D_GLIBCXX_USE_C99_MATH_TR1` to CMake.

**Comment by ruipacheco** [comment]
Let me know if I should close this or if we should leave it for your internal use.

**Comment by randombit** [comment]
Leave it open, if we are failing to build out of the box on a common FreeBSD setup that's a problem. I'll try to investigate this before 2.4.

**Comment by randombit** [comment]
Checked into this more. It looks like the newer GCC package (6.4) does have this fixed, at least it works for me on FreeBSD 11 x64. Based on https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=193528 it appears FreeBSD is not planning on fixing this for the gcc 4.8 or 5.x packages.

Since there is a gcc package version available that does work, FreeBSD seems to agree it's a problem with their gcc, and gcc is not the default compiler I'm going to close. I guess we could add special logic to handle adding `-D_GLIBCXX_USE_C99` to build flags if we detect such a broken compiler on FreeBSD but for mentioned reasons it does not seem worth it.

**Comment by randombit** [comment]
This same error seems to show up on NetBSD 5.1 with GCC 4.8, same workaround
