### ISSUE TITLE
pipe constructor

### ISSUE THREAD

**Issue by lambdafu** [randombit/botan#1306]
I tried to use pipe.append() to dynamically construct my filter chain, and got the deprecation warning. This is the best I could come up with now:

```
  Botan::Filter* f1 = new Botan::Hash_Filter(m_algo);
  Botan::Filter* f2 = new Botan::Hex_Encoder();
  Botan::Filter* f3 = new Botan::DataSink_Stream(std::cout);
  std::shared_ptr<Botan::Pipe> pipe;
  if (m_raw)
    pipe = std::make_shared<Botan::Pipe>(f1, f3);
  else
    pipe = std::make_shared<Botan::Pipe>(f1, f2, f3);
```

Is there a better pattern?  I realize that Pipe steals the pointers, and thus using a std::vector<Botan::Filter*> is a bit fragile.  But constructing an initializer_list dynamically is not straight forward.
I am only trying to construct the filters dynamically, I do not want to change them after processing has started.

**Comment by randombit** [comment]
Pipe's constructor will ignore null arguments, so you could do something like this (untested):

```
  std::shared_ptr<Botan::Pipe> pipe;
  pipe = std::make_shared<Botan::Pipe>(
      new Botan::Hash_Filter(m_algo),
      (m_raw) ? nullptr : new Botan::Hex_Encoder(),
      new Botan::DataSink_Stream(std::cout)
  );
```

It may be worth adding a variant of `append` which works like the current version, except that it throws if any messages have already been processed. Thus allowing dynamic setup but prohibiting runtime modification.

**Comment by lambdafu** [comment]
Thanks, that variation at least has only a single constructor, so I don't need the shared pointer.  Nice :)

**Comment by randombit** [comment]
I've added a variant of `append` that only allows modification before the first message is processed in #1307. So I think we're set here, but please reopen or open a new issue if you have further problems/questions.

**Comment by lambdafu** [comment]
Thanks! Looking good! :beach_umbrella:
