### ISSUE TITLE
Current master lost ability to build LaTeX docs

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1337]
First the generated Makefile had "SPHINX_OPTIONS" parameter with possible values "html" and "latex", and the command `sphinx-build -b $SPHINX_OPTION . . .`.

Then this got reduced to simply a command `sphinx-build -b html . . .` in the generated Makefile. So the Makefile still could be edited to generate LaTeX docs.

Now there's nothing relevant in the makefile, and one has to mess around with `src/scripts/build_docs.py`, changing
```
. . . . .
   if with_sphinx:
        cmds.append(['sphinx-build', '-q', '-b', 'html', '-c', cfg['sphinx_config_dir'],
                     '-j', str(get_concurrency()), manual_src, manual_output])
. . . . .
```

Would you please restore the ability to set LaTeX build with something less drastic than surgery on the guts of the new build system?

**Comment by randombit** [comment]
Ah, yeah we can add a new option to enable pdf build.

Prebuilt version is online @ https://botan.randombit.net/manual/botan.pdf

**Comment by randombit** [comment]
Fixed - ``configure.py --with-pdf --with-sphinx`` + ``make docs`` will generate the PDF.

**Comment by mouse07410** [comment]
@randombit Thank you! Fix confirmed.

Do you think `src/scripts/cleanup.py` should remove `build/doc.stamp` file? Otherwise it seems that the docs aren't rebuilt...

**Comment by randombit** [comment]
Ah yes thanks.

**Comment by randombit** [comment]
Fixed
