### ISSUE TITLE
cc_lang_flags missing in generated build.h

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#1353]
The 2.3.0-to-master diff shows the following change in build.h:

```diff
@@ -32,19 +32,19 @@
 * 'configure.py --amalgamation --no-autoload --disable-shared --enable-modules=aes,auto_rng,cmac,eme_oaep,emsa_pssr,gcm,hkdf,rsa,sha1,sha2_32,sha2_64,srp6,xts,system_rng,dev_random,proc_walk,aes_ni,clmul --os=linux --cpu=x86_64 --cc=clang --cc-min-version=0.0'
 *
 * Target
-*  - Compiler: clang++ -fstack-protector -m64 -pthread -std=c++11 -D_REENTRANT -O3
+*  - Compiler: clang++ -fstack-protector -m64 -pthread -O3
 *  - Arch: x86_64/x86_64
 *  - OS: linux
 */
```

This looks a bit scary but I guess, the now called cc_lang_flags are just missing. However, I lost track of the compile flag management and guess some deduplication may be useful here, so I don't want to fix this myself.

**Comment by randombit** [comment]
I think this was an artifact of splitting out the optimization flags vs the language flags in #1318 as part of #1237
