### ISSUE TITLE
Return warnings in x509_path_validate

### ISSUE THREAD

**Issue by fweissberg** [randombit/botan#1359]
Hi,
currently some constraints on X509 objects are not considered by Botan. For example, serial numbers of Certificates and CRLs shall be non-negative and there are upper bounds on the lengths of Distinguished Name components.
However, the examples probably should not prevent the path validation from succeeding. Should we add a mechanism to return warnings to the user? Right now, the validation fails if the overall status code is different from VERIFIED, OCSP_RESPONSE_GOOD or VALID_CRL_CHECKED.
Path_Validation_Result::successful_validation() could return true if the status with the highest severity is below the error threshold and a future Path_Validation_Result::no_warnings() could return true if the overall status code is one of VERIFIED, OCSP_RESPONSE_GOOD or VALID_CRL_CHECKED.

**Comment by randombit** [comment]
Yes a warning mechanism would be useful in several other contexts, for example if the verification enabled weak hashes like SHA-1 we could still include a warning if a weak hash was actually used during the verification.

This should be pretty easy, carve out a block of `Certificate_Status_Code` before `FIRST_ERROR_STATUS` (say the range 500-999), add `FIRST_WARNING_STATUS` == 500, and then special case result codes in the range `[FIRST_WARNING_STATUS...FIRST_ERROR_STATUS)` in `merge_revocation_status`.

For negative serial numbers we'd actually have to track the sign on decoding, as it is we just encode `abs(serial_number)` as an octet string and ignore the sign. TBH not sure what the best handling here is - what if a CA signs two certs one with serial number `X` and another with `-X`? Ugh. But it seems negative serial numbers are common enough that Golang explicitly removed their check https://github.com/golang/go/commit/a0ea93dea5f5741addc8c96b7ed037d0e359e33f

The checks on DN lengths should be centralized in a function on `X509_DN`.

We're only a week away from feature freeze for 2.4.0 and I probably won't have time to work on this myself before then, but would take a PR.

**Comment by fweissberg** [comment]
In fact, I am working on some stuff along those lines that is in internal review right now. Hopefully, we will be able to send a PR early next week (we will also send a proposal for improved path building (https://github.com/randombit/botan/issues/1283)).

**Comment by randombit** [comment]
Fixed in #1363
