### ISSUE TITLE
debug option missing?

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#136]
I tried compiling with the option --enable-debug (this works for version 1.10.9) but get an error saying no such option in the version 1.11.17

C:\BotanCrypto\Botan-1.11.17>python configure.py --prefix=C:\BotanCrypto\Botan-1
.11.17\DEBUG_BUILD --no-autoload --enable-modules=fpe_fe1 --cc=msvc --cpu=x86 --
enable-debug
Usage: configure.py [options]

configure.py: error: no such option: --enable-debug

**Comment by webmaster128** [comment]
There is `--debug-mode` and `--build-mode=debug` now but to be honest, I don't know what they do. See `./configure.py --help`

**Comment by webmaster128** [comment]
Could you solve your debug problem using one of the options?

**Comment by erotavlas** [comment]
yes 
for version 1.10.9 I used --enable-debug
for version 1.11.17 I used --debug-mode

**Comment by webmaster128** [comment]
Fine, thanks :)
