### ISSUE TITLE
AlgorithmIdentifier parameters encoded in X.509 certificate with ECDSA

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#1366]
We noticed compatibility problems with JSSE/BouncyCastle when trying to verify a certificate generated with Botan. When comparing the ASN.1 dump with that of a similiar certificate generated using JSSE/BouncyCastle, we noticed that Botan encodes the curve OID (in this case brainpool512r1) in the AlgorithmIdentifier parameters, whereas BouncyCastle does not.

See [this](https://lapo.it/asn1js/#3082038C308202F1A003020102020601606FF33CD2300A06082A8648CE3D04030430133111300F06035504030C085443434C49454E543020170D3939313233313233303030305A180F32303939313233313233303030305A30133111300F06035504030C085443434C49454E5430819B301406072A8648CE3D020106092B240303020801010D03818200040319E9E2B6FD16CB28533CFBC5BF33CE372B1767BB5862E3FF3C80BD2CFDC4C4ECDF9C2E191F89A91C0AB35363BFC72FB77EC6E82F93D7D6D4415FBF6CADC71F4EAD7DC176697444D4F6C4F52595BDCE6D33E547B620E1173EFAD196A10300E9A24B2E2B7C64130D7994C5F9244DE41C9C64EEA89500D284964296B2B0DEEAC2A38201EA308201E6300C0603551D130101FF0402300030400603551D230439303780141E43075472773564B65E8DB4B07BE4082C096169A117A41530133111300F06035504030C085443434C49454E54820601606FF33CD23012060B2B0601040181EB7D0B020204030201013031060B2B0601040181EB7D0B0201042204205A3954CBA812BA55F5D2D473C7CAEB3C7D021098DE716BF1A515ECB38C4B41C53081AE060B2B0601040181EB7D0B010304819E30819B301406072A8648CE3D020106092B240303020801010D0381820004A61C018C9E61E91AF85A5C935B7348545228EB8E5F10A9AA822C62EF478BAADB7903ED48B68BF91F666573889AA63EAA3B9A3A100371A77A3E69851421553E8B6526ADF0C32F0360761FE85CE44493B6EC7BABB1ECA167898C8DA94410FEB781A89FF7424D58A3B23F126FBA0AA4F25E334EF3E9758386283319EBFDE961BFFD30819B060C2B0601040181EB7D0B01030104818A048187308184024057603A3807713FB796DC33A5CD76B9759EB6E2A9AEAE50A156E164C7EDF1FD2C6028280CD0142B39743E6B91EA7D4EDF885BFFE1957015F6DB1453CEE23CF0AD02402AF4BAE7739D8DBE1B7B85E0BB5292A08694D485856FF5F1E714A5DB4FF8766DFF16FE2EEA6639EDF0DFA3B06FC7AB012DDEB8167ACF476AE10741689CCAC2E0300A06082A8648CE3D04030403818800308184024011FE88034F547919ED185E8308174A0EEDF9E2AC9B11CB2C859E9E3A8FE654BD43A710D4E83C4951145765ED10E14BC2410023FA7B42683D0978DD7976C8687502401B717FD32F669DEC9C29DBF81D7574ABA2BF8C8037AEF56949F19B9DE11277C850C2AFDC5ACB3385DB748B7E9890AEBA3B811A91C5DE578AF36F3B7BADD1B367) certificate dump generated using BouncyCastle vs. [this](https://lapo.it/asn1js/#308203C53082031FA003020102021100AF8006B7BD6166EBBA7A774794EF8842301506082A8648CE3D04030406092B240303020801010D305A310B3009060355040613024445314B304906035504030C42526F6864652026205363687761727A204379626572736563757269747920547275737465644368616E6E656C2047656E657261746564204365727469666963617465301E170D3137313231383138303930375A170D3137313232303138303930375A305A310B3009060355040613024445314B304906035504030C42526F6864652026205363687761727A204379626572736563757269747920547275737465644368616E6E656C2047656E657261746564204365727469666963617465305A301406072A8648CE3D020106092B240303020801010D03420002A12B956CF4434C0CDCF5DCBBFF3E89D8D595C25D697FDC0F351ABD3BB17184C8AEBBA8FD2D5803C870DBFF9131E5A25E51E14D71AFE27C79B49AF4CB8DEFC2D3A38201B8308201B430490603551D0E04420440CD4FF04FB730A07844E4069097A93A9A118DC1B6C7E9487503DC8721BE5BF2571CA44407D14991A716A2BE969D5A77E50AC0F3D38E8745A8E4774E42ABB3F970300E0603551D0F0101FF040403020780300C0603551D130101FF04023000306B060B2B0601040181EB7D0B0103045C305A301406072A8648CE3D020106092B240303020801010D03420003A7E813EF2FDF97C3A65B2474D06E99C45596FA7C58D86175CDB3725150D3092C5E6A8736F39A7B97F85ED898CF6F1DEE10C0F2A1D4524D43894F5C56743ECF083031060B2B0601040181EB7D0B0201042204205A3955A8A44F6246B4A5B6E7DA846A94195D41BE9D6ACA9BCE9707DE5675ABAD3012060B2B0601040181EB7D0B02020403020102308194060C2B0601040181EB7D0B0103010481830481808F468AEA8558BBD300FA4E59D9EAB60F8E1EFE66DD3E67F8F7EAE96BE8A69022B8104BE710C85577E2067AA90DC83A28B03B1D4000FE78EF1FB2E7D676E83872964F3EF8AFD8E70D43933BDBD3FAC3503EDBEE38FAB100B101027A5FD8A2F5486E243C9096AA4FF1A61E32840F089661BD9195E6CF30F0FB9BF15E9250625BC5301506082A8648CE3D04030406092B240303020801010D03818800308184024065D1D5D4418E705E44273F57D4E4D6BCA7BA3D7E3DFCDE7361D507B766EB8125802A1E9C5CAAFAC3FB35E40AB0D67C518BF3B557C2B520780A5C29F53AA11CDB02403872CA199F9DEF78A72DC89FB89BD33883AC1BA35A5681CF83B64B0E4B81E8B547AAFF3B25E484D25A6BBAB90DAEF22356BB67D8B4FA9EBA74371AA0ED749585) certificate dump generated using Botan. Also compare it to [this](https://lapo.it/asn1js/#308203DF30820385A0030201020210623106933FCAC2AB0D3F90C6DE4DE78E300A06082A8648CE3D040302308192310B3009060355040613024742311B30190603550408131247726561746572204D616E636865737465723110300E0603550407130753616C666F7264311A3018060355040A1311434F4D4F444F204341204C696D69746564313830360603550403132F434F4D4F444F2045434320446F6D61696E2056616C69646174696F6E20536563757265205365727665722043412032301E170D3137303630313030303030305A170D3138303630313233353935395A30643121301F060355040B1318446F6D61696E20436F6E74726F6C2056616C6964617465643121301F060355040B1318506F73697469766553534C204D756C74692D446F6D61696E311C301A06035504031313626C6F672E636C6F7564666C6172652E636F6D3059301306072A8648CE3D020106082A8648CE3D030107034200047026010A7B8B1D066318BC5CB1811355969A22FC78C941AAD1C47FD00E8799A94B1F517C3817F40F245917A012B25705C41C3AC4578FBDBC1A1F3688732A0167A38201E8308201E4301F0603551D2304183016801440096167F0BC83714FDE12082C6FD4D42B763D96301D0603551D0E04160414E5692F941E7559B20BBF7F9CED3233A0FCA12ECB300E0603551D0F0101FF040403020780300C0603551D130101FF04023000301D0603551D250416301406082B0601050507030106082B06010505070302304F0603551D2004483046303A060B2B06010401B23101020207302B302906082B06010505070201161D68747470733A2F2F7365637572652E636F6D6F646F2E636F6D2F4350533008060667810C01020130560603551D1F044F304D304BA049A0478645687474703A2F2F63726C2E636F6D6F646F6361342E636F6D2F434F4D4F444F454343446F6D61696E56616C69646174696F6E5365637572655365727665724341322E63726C30818806082B06010505070101047C307A305106082B060105050730028645687474703A2F2F6372742E636F6D6F646F6361342E636F6D2F434F4D4F444F454343446F6D61696E56616C69646174696F6E5365637572655365727665724341322E637274302506082B060105050730018619687474703A2F2F6F6373702E636F6D6F646F6361342E636F6D301106082B0601050507011804053003020105301E0603551D11041730158213626C6F672E636C6F7564666C6172652E636F6D300A06082A8648CE3D0403020348003045022100FF387B514F3101C53160DA2B93037C065B28EBF01F502F8B0B5E47D98C6B8B3E022059F299598A2D3235B82CCECB353FCA395D5630ED5D5C8EFA348302DBDBC9EE82) pulled from blog.cloudflare.com.

We looked at [RFC 5758](https://tools.ietf.org/html/rfc5758#page-4) which says:

> When the ecdsa-with-SHA224, ecdsa-with-SHA256, ecdsa-with-SHA384, or
   ecdsa-with-SHA512 algorithm identifier appears in the algorithm field
   as an AlgorithmIdentifier, the encoding MUST omit the parameters
   field.  That is, the AlgorithmIdentifier SHALL be a SEQUENCE of one
   component, the OID ecdsa-with-SHA224, ecdsa-with-SHA256, ecdsa-with-
   SHA384, or ecdsa-with-SHA512.

So I think Botan's behaviour is wrong here.

**Comment by randombit** [comment]
If I'm reading things correctly the problem stems from this code in `choose_sig_format` in `x509_ca.cpp`:

```
   sig_algo = AlgorithmIdentifier(OIDS::lookup(algo_name + "/" + padding),                                                                                                                                                                                                       
                                  key.algorithm_identifier().get_parameters());           
```

So for ECC this should be empty, instead of the key's parameters. For RSA it should probably? be empty. Or maybe NULL? And for DSA, I have no idea.

**Comment by randombit** [comment]
Oh wait you linked to the section of the RFC that specifically says DSA params should also be empty

**Comment by randombit** [comment]
Ah ok:

RSA PKCSv1.5 "SHALL" be NULL https://tools.ietf.org/html/rfc3279#section-2.2.1
DSA+ECDSA "SHALL" be empty

And RSA PSS is the PSS parameters blob (https://tools.ietf.org/html/rfc5756) but we don't support creating PSS sigs yet.

**Comment by securitykernel** [comment]
And also:

GOST 34.10 "SHALL" be empty (https://tools.ietf.org/html/rfc4491#section-2.2.1)

Could not find an RFC for ECGDSA/ECKCDSA, but I think we can assume expected behaviour is similar to ECDSA.
