### ISSUE TITLE
nmake fails on windows - botan version 1.11.17

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#137]
When trying to build the current development version (from http://botan.randombit.net/download.html) 1.11.17 in Windows I am encountering error when running nmake

C:\BotanCrypto\Botan-1.11.17>python configure.py --prefix=C:\BotanCrypto\Botan-1
.11.17\DEBUG_BUILD  --cc=msvc --cpu=x86
   INFO: Platform: OS="Windows" machine="AMD64" proc="Intel64 Family 6 Model 42
Stepping 7, GenuineIntel"
   INFO: Guessing target OS is windows (use --os to set)
   INFO: Canonicalizized CPU target x86 to x86_32/x86_32
   INFO: Target is msvc-windows-x86_32-x86_32
   INFO: Skipping, by request only - cvc
   INFO: Skipping, dependency failure - md4_x86_32 md5_x86_32 serpent_x86_32 ses
sions_sqlite3 sha1_x86_32
   INFO: Skipping, incompatible CPU - sha1_x86_64
   INFO: Skipping, incompatible OS - asm_x86_32 asm_x86_64 beos_stats dev_random
 egd fd_unix locking_allocator proc_walk unix_procs
   INFO: Skipping, incompatible compiler - mp_x86_32 mp_x86_64 rdrand simd_altiv
ec threefish_avx2
   INFO: Skipping, loaded only if needed by dependency - dyn_load mp_generic sim
d_scalar
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlit
e3 zlib
   INFO: Using MP module mp_x86_32_msvc
   INFO: Using SIMD module simd_sse2
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 alloc aont asn1 auto_
rng base base64 bcrypt benchmark bigint block blowfish camellia cascade cast cbc
 cbc_mac ccm cfb chacha chacha20poly1305 clmul cmac codec_filt comb4p compressio
n crc24 crc32 credentials cryptoapi_rng cryptobox ctr curve25519 datastor des dh
 dl_algo dl_group dlies dsa eax ec_gfp ec_group ecb ecc_key ecdh ecdsa elgamal e
me_oaep eme_pkcs1 eme_raw emsa1 emsa1_bsi emsa_pkcs1 emsa_pssr emsa_raw emsa_x93
1 entropy ffi filters fpe_fe1 gcm gost_28147 gost_3410 gost_3411 has160 hash has
h_id hex hkdf hmac hmac_drbg hmac_rng hres_timer http_util idea idea_sse2 if_alg
o kasumi kdf kdf1 kdf2 keccak keypair lion mac mars mce mceies md2 md4 md5 mdx_h
ash mgf1 misty1 mode_pad modes mp mp_x86_32_msvc noekeon noekeon_simd nr numbert
heory ocb ofb oid_lookup openpgp par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pe
m pk_pad poly1305 prf_tls prf_x942 pubkey rc2 rc4 rc5 rc6 rfc3394 rfc6979 rmd128
 rmd160 rng rsa rw safer salsa20 seed serpent serpent_simd sessions_sql sha1 sha
1_sse2 sha2_32 sha2_64 simd simd_sse2 siphash siv skein srp6 stream system_rng t
ea threefish tiger tls tss twofish utils whirlpool win32_stats x509 x919_mac x93
1_rng xtea xtea_simd xts
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using hardlink to link files into build dir (use --link-method to chang
e)
   INFO: Botan 1.11.17 (released dated 20150619) build setup is complete

C:\BotanCrypto\Botan-1.11.17>nmake

Microsoft (R) Program Maintenance Utility Version 11.00.61030.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl /MD /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /W3 /wd4275 /wd426
7 /Ibuild\include /nologo /c src\lib\asn1\alg_id.cpp /Fobuild\obj\lib\asn1_alg_i
d.obj
alg_id.cpp
build\include\botan/secmem.h(76) : error C2143: syntax error : missing ',' befor
e '...'
        build\include\botan/secmem.h(83) : see reference to class template insta
ntiation 'Botan::secure_allocator<T>' being compiled
build\include\botan/secmem.h(77) : error C2061: syntax error : identifier 'Args'

build\include\botan/secmem.h(93) : error C2988: unrecognizable template declarat
ion/definition
build\include\botan/secmem.h(93) : error C2059: syntax error : 'using'
build\include\botan/secmem.h(97) : error C4430: missing type specifier - int ass
umed. Note: C++ does not support default-int
build\include\botan/secmem.h(97) : error C2143: syntax error : missing ',' befor
e '<'
build\include\botan/asn1_obj.h(84) : error C2143: syntax error : missing ';' bef
ore '<'
build\include\botan/asn1_obj.h(84) : error C4430: missing type specifier - int a
ssumed. Note: C++ does not support default-int
build\include\botan/asn1_obj.h(84) : error C2238: unexpected token(s) preceding
';'
c1xx : fatal error C1903: unable to recover from previous error(s); stopping com
pilation
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0
\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

**Comment by webmaster128** [comment]
Which compiler do you use? MSCV is only supported in version 2013 and newer.

**Comment by erotavlas** [comment]
I was using msvc in Visual Studio 2012. Same as  I used for Botan version 1.10.9

**Comment by webmaster128** [comment]
Visual Studio 2012 is not supported anymore in Botan 1.11.x, sorry.
