### ISSUE TITLE
How to save an encrypted string to text file and read it back as plain text

### ISSUE THREAD

**Issue by bangusi** [randombit/botan#1376]
I am new to Botan and encryption in general. My requirement is simple.
My platform is Windows 7.
Compiler VS 2017
I want to save plain text string ( preferably  wide string a.ks. `std:;wstring` ) as encrypted text in a text file and be able to read it back ( decrypt? ).
I have come across example code that shows one way ( encrypt like this one
```
AutoSeeded_RNG rng;
int a = 1;
std::string strr = "my plain text string to be encrypted";
std::cout << Botan::generate_bcrypt(strr, rng, a) << std::endl; 
```

**Comment by randombit** [comment]
bcrypt is not for encryption, it is a one-way hash that is intentionally hard to compute. It is used for example for password authentication.

There are some simple pre-built functions for passphrase encryption in `botan/cryptobox.h`. They only support byte strings as input so you'll have to convert your `wstring` somehow (eg using UTF-8 encoding).

Basic usage:

```
AutoSeeded_RNG rng;
std::string pass = "very secret";
std::string input = "my plain text";
std::string blob = CryptoBox::encrypt(reinterpret_cast<const uint8_t>(input.data()), input.size(), pass, rng);
std::string got_back = CryptoBox::decrypt(blob, pass);
```

**Comment by bangusi** [comment]
Thanks @randombit . Is there a way to suppress the boiler plate header / footer that is automatically attached the to the encrypted message?

**Comment by randombit** [comment]
You can't disable the PEM formatting (this should be supported, but isn't - these functions are rather old and the functionality is a little non-orthongonal)  but there are functions to reverse the transformation back to raw binary (in `botan/pem.h`)

```std::vector<uint8_t> binary_blob = PEM_Code::decode_check_label(blob, "BOTAN CRYPTOBOX MESSAGE")```

If you want the base64 encoding but not the headers you can just strip out the headers using regular `std::string` operations, or decode to binary and then base64 encode using the functions in `base64.h`).

**Comment by bangusi** [comment]
The return value of seems to be `secure_vector<uint8_t>` but I get the idea.
