### ISSUE TITLE
Naming Windows library botand in debug mode

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#1404]
Since 4e2ad46cd58bc273bea919de6691988540b1ed16 the "special" debug library naming for Windows  was reverted from `botand.dll` to `botan.dll`.

This is inconvenient for us. When we start the release executable we load `botan.lib/botan.dll` and in debug mode we load `botand.dll/botand.lib`. We've put both DLLs into a path which is present in the `PATH` variable. Now thats no longer possible when both DLLs are named the same.

There is already a `--program-suffix` for configure.py. A similar `--lib-suffix` would also help here.

**Comment by randombit** [comment]
I'm ok with a `--lib-suffix`. I will look at this along with the issues raised in #1403

**Comment by randombit** [comment]
--library-suffix added
