### ISSUE TITLE
2.4.0: RSA, PK_Encryptor lies about maximum_input_size()

### ISSUE THREAD

**Issue by ksanderon** [randombit/botan#1410]
Hi, yesterday I'v checked that for some padding schemes(probably all) `maximum_input_size` method of  PK_Encryptor return very small value. Much smaller than really accepted by encryptor.

I'v checked it with 1024, 2048 and 4096 key sizes and on linux and mac.

Returned values are really small - like 20-30 bytes depending on padding scheme.

**Comment by randombit** [comment]
Confirmed, very strange. Looks to affect ElGamal also.

**Comment by randombit** [comment]
Oh I see it - there is confusion between bits and bytes. First we check the key for its maximum bit input length. Then we pass it to the padding scheme (as bits) to inquire how much space it needs. The EME function returns the space available as *byte*. But then another function assumes it is speaking of bits, and reduces by a factor of 8.

**Comment by randombit** [comment]
Having network issues so I can't push the fix right now, but will land on master in a bit.

**Comment by randombit** [comment]
Fixed!
