### ISSUE TITLE
My .NET wrapper is broken after upgrading to Botan 1.11.17

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#142]
I have been working on a managed .NET wrapper for Botan version 1.10.9 and I finally had it working, but after upgrading to the version 1.11.17 and Visual Studio 2013, it is no longer functioning and there are problems resolving several types in addition to the following errors.

  	1	IntelliSense: #error directive: <mutex> is not supported when compiling with /clr or /clr:pure.	c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\mutex	8	4	BotanCrypto_ManagedWrapper

	2	IntelliSense: linkage specification is incompatible with previous "bsearch_s" (declared at line 439)	c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h	588	33	BotanCrypto_ManagedWrapper

	3	IntelliSense: linkage specification is incompatible with previous "bsearch" (declared at line 443)	c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h	591	33	BotanCrypto_ManagedWrapper

	4	IntelliSense: linkage specification is incompatible with previous "qsort_s" (declared at line 448)	c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h	595	16	BotanCrypto_ManagedWrapper

	5	IntelliSense: linkage specification is incompatible with previous "qsort" (declared at line 452)	c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h	599	16	BotanCrypto_ManagedWrapper

	7	IntelliSense: identifier "SecureVector" is undefined	y:\Visual Studio 2012\BotanCrypto_ManagedWrapper\BotanCrypto_ManagedWrapper\BotanCrypto_ManagedWrapper.cpp	109	2	BotanCrypto_ManagedWrapper

	10	IntelliSense: identifier "LibraryInitializer" is undefined	y:\Visual Studio 2012\BotanCrypto_ManagedWrapper\BotanCrypto_ManagedWrapper\BotanCrypto_ManagedWrapper.h	16	3	BotanCrypto_ManagedWrapper

EDIT: Later I created a new empty CLR project and added the library to it.  This time I only got one complaint regarding <mutex>

    #error directive: <mutex> is not supported when compiling with /clr or /clr:pure.

I need to allow CLR support in my managed wrapper.  What can be modified to make it work like it did in version 1.10.9?

If posting my project to github will be helpful, let me know.  I'd appreciate any help to get my wrapper working again.

**Comment by webmaster128** [comment]
I have no clue about .NET but it would be worth having a look at it.

Did you think about making it open source using a liberal license like MIT or Botan's BSD license? I think it would be great for the entire Botan project to have a .NET wrapper available that can be used in commercial software.

**Comment by erotavlas** [comment]
I found this post on stackOverflow it sounds very similar to the situation I have.

http://stackoverflow.com/q/26585714/1462656

The suggestion is to do this
"The only way to sail around the compile error is to wrap the native code in a C++ source file that's compiled without /clr in effect so your C++/CLI code never sees the mutex"

Any ideas?

**Comment by erotavlas** [comment]
I was thinking to post what I have so far, I'm only interested in using the FPE module so that is all I have been working on.  

However I don't think a.NET wrapper will work any more for the newer versions of Botan that include <mutex>  Which modules depend on it?  I can get around the error by compiling Botan to exclude those modules.

**Comment by webmaster128** [comment]
I think it is not easy to get rid of mutex. Even after I did a lot of fixes at the module dependencies, there are `<mutex>`s left.

```
./configure.py --no-autoload --enable-modules=fpe_fe1 --disable-shared --via-amalgamation
```

botan_all.h:

```
[...]
#include <algorithm>
#include <chrono>
#include <cstddef>
#include <cstring>
#include <deque>
#include <exception>
#include <functional>
#include <iosfwd>
#include <istream>
#include <map>
#include <memory>
#include <mutex>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>

/*
[...]
```

**Comment by erotavlas** [comment]
I noticed it was added to many areas of the code.  So now I'm working on an alternative way to create the wrapper.  I'm creating an unmanaged C++ wrapper project around the library methods I want to use.  And I have a CLR wrapper that calls the C++ wrapper.  Hopefully I'll still be able to compile the managed project with the /clr option since I'm guessing it won't see the mutex.

**Comment by webmaster128** [comment]
Okay, let me close this for now. Removing the dependency of `<mutex>` is definitely out of scope. If you have further specific problems, just open a new issue.
