### ISSUE TITLE
Make install not work if build without os filesystem feature.

### ISSUE THREAD

**Issue by ksanderon** [randombit/botan#1422]
CLI application do not check if filesystem is enabled, so for example `src/cli/tls_client.cpp` cannot be build and there is no option to disable building cli app as part of install task.

Probably the same issue will be with other os features like sockets.

**Comment by ksanderon** [comment]
Additionally there will be nice if there could be in `configure.py` way to see all possible os features list.

**Comment by randombit** [comment]
Filesystem-free build fixed now. Disabling sockets was ok. And `configure.py --list-os-features` added.

**Comment by ksanderon** [comment]
Nice ;)
