### ISSUE TITLE
cross-compilation to windows fails

### ISSUE THREAD

**Issue by aido93** [randombit/botan#1423]
Hello!

I try to cross-compile this library under linux to windows but it fails:

../mxe/usr/bin/x86_64-w64-mingw32.shared-g++ -fstack-protector -m64 -pthread   -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -I/usr/x86_64-w64-mingw32/include -c src/lib/base/symkey.cpp -o build/obj/lib/base_symkey.o
In file included from build/include/botan/rng.h:13:0,
                 from src/lib/base/symkey.cpp:9:
build/include/botan/mutex.h:19:14: error: 'mutex' in namespace 'std' does not name a type
 typedef std::mutex mutex_type;
              ^
In file included from src/lib/base/symkey.cpp:9:0:
build/include/botan/rng.h:257:15: error: 'mutex_type' does not name a type
       mutable mutex_type m_mutex;
               ^
build/include/botan/rng.h: In member function 'virtual void Botan::Serialized_RNG::randomize(uint8_t*, std::size_t)':
build/include/botan/rng.h:217:26: error: 'mutex_type' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                          ^
build/include/botan/rng.h:217:36: error: template argument 1 is invalid
          lock_guard_type<mutex_type> lock(m_mutex);
                                    ^
build/include/botan/rng.h:217:43: error: 'm_mutex' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                                           ^
build/include/botan/rng.h:217:38: warning: unused variable 'lock' [-Wunused-variable]
          lock_guard_type<mutex_type> lock(m_mutex);
                                      ^
build/include/botan/rng.h: In member function 'virtual bool Botan::Serialized_RNG::is_seeded() const':
build/include/botan/rng.h:223:26: error: 'mutex_type' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                          ^
build/include/botan/rng.h:223:36: error: template argument 1 is invalid
          lock_guard_type<mutex_type> lock(m_mutex);
                                    ^
build/include/botan/rng.h:223:43: error: 'm_mutex' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                                           ^
build/include/botan/rng.h:223:38: warning: unused variable 'lock' [-Wunused-variable]
          lock_guard_type<mutex_type> lock(m_mutex);
                                      ^
build/include/botan/rng.h: In member function 'virtual void Botan::Serialized_RNG::clear()':
build/include/botan/rng.h:229:26: error: 'mutex_type' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                          ^
build/include/botan/rng.h:229:36: error: template argument 1 is invalid
          lock_guard_type<mutex_type> lock(m_mutex);
                                    ^
build/include/botan/rng.h:229:43: error: 'm_mutex' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                                           ^
build/include/botan/rng.h:229:38: warning: unused variable 'lock' [-Wunused-variable]
          lock_guard_type<mutex_type> lock(m_mutex);
                                      ^
build/include/botan/rng.h: In member function 'virtual std::__cxx11::string Botan::Serialized_RNG::name() const':
build/include/botan/rng.h:235:26: error: 'mutex_type' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                          ^
build/include/botan/rng.h:235:36: error: template argument 1 is invalid
          lock_guard_type<mutex_type> lock(m_mutex);
                                    ^
build/include/botan/rng.h:235:43: error: 'm_mutex' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                                           ^
build/include/botan/rng.h:235:38: warning: unused variable 'lock' [-Wunused-variable]
          lock_guard_type<mutex_type> lock(m_mutex);
                                      ^
build/include/botan/rng.h: In member function 'virtual std::size_t Botan::Serialized_RNG::reseed(Botan::Entropy_Sources&, std::size_t, std::chrono::milliseconds)':
build/include/botan/rng.h:243:26: error: 'mutex_type' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                          ^
build/include/botan/rng.h:243:36: error: template argument 1 is invalid
          lock_guard_type<mutex_type> lock(m_mutex);
                                    ^
build/include/botan/rng.h:243:43: error: 'm_mutex' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                                           ^
build/include/botan/rng.h:243:38: warning: unused variable 'lock' [-Wunused-variable]
          lock_guard_type<mutex_type> lock(m_mutex);
                                      ^
build/include/botan/rng.h: In member function 'virtual void Botan::Serialized_RNG::add_entropy(const uint8_t*, std::size_t)':
build/include/botan/rng.h:249:26: error: 'mutex_type' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                          ^
build/include/botan/rng.h:249:36: error: template argument 1 is invalid
          lock_guard_type<mutex_type> lock(m_mutex);
                                    ^
build/include/botan/rng.h:249:43: error: 'm_mutex' was not declared in this scope
          lock_guard_type<mutex_type> lock(m_mutex);
                                           ^
build/include/botan/rng.h:249:38: warning: unused variable 'lock' [-Wunused-variable]
          lock_guard_type<mutex_type> lock(m_mutex);
                                      ^
Makefile:118: ошибка выполнения рецепта для цели «build/obj/lib/base_symkey.o»
make: *** [build/obj/lib/base_symkey.o] Ошибка 1

**Comment by randombit** [comment]
It appears your MinGW install doesn't support `std::mutex`. Which is apparently quite common problem for MinGW on Windows (https://stackoverflow.com/questions/17551722/getting-stdthread-mutex-to-work-under-win7-with-mingw-and-g-4-7-2) but I haven't seen this problem on MinGW cross builds before (works fine on both Ubuntu and Arch). Where did your MinGW come from?

You should be able to work around the problem by configuring with `--without-os-features=threads`

**Comment by aido93** [comment]
> Where did your MinGW come from?

From debian repo and from mxe-project. Both give the same result

**Comment by aido93** [comment]
Ok. With this flag I have:

src/tests/unit_tls.cpp: In function 'Botan_Tests::Test::Result Botan_Tests::{anonymous}::test_dtls_handshake(Botan::TLS::Protocol_Version, Botan::Credentials_Manager&, const Botan::TLS::Policy&, const Botan::TLS::Policy&, Botan::RandomNumberGenerator&, Botan::TLS::Session_Manager&, Botan::TLS::Session_Manager&)':
src/tests/unit_tls.cpp:760:21: error: 'std::this_thread' has not been declared
                std::this_thread::sleep_for(std::chrono::microseconds(rng.next_byte() % 128));

**Comment by randombit** [comment]
Build problem in 023a245 which should apply cleanly against 2.4.0

I'll try setting up a Debian VM to repro later.

**Comment by aido93** [comment]
if I comment this line out, then I have

../mxe/usr/bin/x86_64-w64-mingw32.static-g++ -fstack-protector -m64 -pthread  build/obj/cli/asn1.o build/obj/cli/cc_enc.o build/obj/cli/cli.o build/obj/cli/cli_rng.o build/obj/cli/compress.o build/obj/cli/encryption.o build/obj/cli/main.o build/obj/cli/math.o build/obj/cli/psk.o build/obj/cli/pubkey.o build/obj/cli/speed.o build/obj/cli/timing_tests.o build/obj/cli/tls_client.o build/obj/cli/tls_http_server.o build/obj/cli/tls_proxy.o build/obj/cli/tls_server.o build/obj/cli/tls_utils.o build/obj/cli/utils.o build/obj/cli/x509.o -L. -lbotan-2 -ladvapi32 -lcrypto -lws2_32 -lz -o botan.exe
/home/builder/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xe5b): undefined reference to `__imp_GetDeviceCaps'
/home/builder/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xe88): undefined reference to `__imp_CreateCompatibleBitmap'
/home/builder/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xe9e): undefined reference to `__imp_GetObjectW'
/home/builder/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xf57): undefined reference to `__imp_GetDIBits'
/home/builder/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/5.4.0/../../../../x86_64-w64-mingw32.static/lib/../lib/libcrypto.a(rand_win.o):rand_win.c:(.text+0xfe5): undefined reference to `__imp_DeleteObject'

**Comment by randombit** [comment]
Similar error here https://curl.haxx.se/mail/lib-2014-12/0182.html looks like OpenSSL had a dependency on gdi32.lib?

I guess either disable OpenSSL support or edit the makefile and add `gdi32.lib` to `LIB_LINKS_TO` variable.

**Comment by aido93** [comment]
Yes, appending -lgdi32 to LIB_LINKS_TO works.

**Comment by ksanderon** [comment]
@aido93 , if you not really need to use mingw because of some serious requirements, considerate using llvm clang. First of all it just works and aditionally it work very well on and for windows ;) Most important thing is that it support even a lot of features which are specific to windows close to way msvc handle these, when mingw try do it different way which cause a lot of problems in ABI etc.

**Comment by aido93** [comment]
Ok. How to link application with statically-built library?
I tried:
1) simple add -lbotan-2:

x86_64-w64-mingw32.static-g++ -fno-stack-protector -Wl,-s -Wl,-subsystem,console -mthreads -o release/activator.exe release/main.o release/mainwindow.o release/license.o release/activator_plugin_import.o release/qrc_activator.o release/moc_mainwindow.o release/moc_license.o  -L../../builder/mxe/usr/x86_64-w64-mingw32.static/lib/botan-2 -lbotan-2 -L/home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platforms /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/platforms/libqwindows.a -lwinspool -L/home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5EventDispatcherSupport.a -L/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5FontDatabaseSupport.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5ThemeSupport.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5AccessibilitySupport.a -L/home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqgif.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqicns.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqico.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqjp2.a -ljasper /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqjpeg.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqmng.a -lmng -llcms2 -lpthread /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqtga.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqtiff.a -ltiff -llzma -ljpeg /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqwbmp.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/imageformats/libqwebp.a -L/home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/bearer /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/bearer/libqgenericbearer.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/plugins/bearer/libqnativewifibearer.a /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5Widgets.a -luxtheme -ldwmapi /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5Gui.a -lcomdlg32 -loleaut32 -limm32 -lopengl32 -lharfbuzz -lcairo -lgobject-2.0 -lfontconfig -lm -lusp10 -lmsimg32 -lpixman-1 -lffi -lexpat -lfreetype -lbz2 -lpng16 -lharfbuzz_too -lfreetype_too -lglib-2.0 -lshlwapi -lpcre -lintl -liconv /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5Network.a -ldnsapi -liphlpapi -lssl -lcrypto -lgdi32 -lcrypt32 /home/builder/mxe/usr/x86_64-w64-mingw32.static/qt5/lib/libQt5Core.a -lmpr -lversion -lws2_32 -lkernel32 -luser32 -lshell32 -luuid -lole32 -ladvapi32 -lwinmm -lz -lpcre2-16 release/activator_resource_res.o

/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_oid.o):asn1_oid.cpp:(.text+0xe4): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_oid.o):asn1_oid.cpp:(.text+0x644): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_oid.o):asn1_oid.cpp:(.text+0x96e): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_oid.o):asn1_oid.cpp:(.text+0xef7): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_oid.o):asn1_oid.cpp:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_str.o):asn1_str.cpp:(.text+0x56f): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_str.o):asn1_str.cpp:(.text+0x889): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_str.o):asn1_str.cpp:(.text$_ZN9__gnu_cxx12__to_xstringINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEET_PFiPT0_yPKS8_PcEySB_z[_ZN9__gnu_cxx12__to_xstringINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEET_PFiPT0_yPKS8_PcEySB_z]+0xd4): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_ber_dec.o):ber_dec.cpp:(.text+0x23a): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_ber_dec.o):ber_dec.cpp:(.text+0x347): undefined reference to `__stack_chk_fail'
/home/builder/mxe/usr/x86_64-w64-mingw32.static/lib/libbotan-2.a(asn1_ber_dec.o):ber_dec.cpp:(.text+0x526): more undefined references to `__stack_chk_fail' follow

2) add also -fstack-protector to QMAKE_LFLAGS. Application can be compiled but it crashes in runtime.

**Comment by ksanderon** [comment]
this stuff is because of -fstack-protector one time and -fno-stack-protector another time. try compile your app on linux, check under valigrind if you do not have mamory access related issues. Additionally as I suggested try clang instead mingw because it is full of odd/outdated stuff.

**Comment by randombit** [comment]
Closing since I think @ksanderon answered the question on stack-protector correctly. @aido93  feel free to open a new issue if you are still having problems.
