### ISSUE TITLE
Method signature for Botan::FPE::fe1_encrypt

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#143]
In the documentation located here http://botan.randombit.net/manual/fpe.html

There is an example how to encrypt a credit card number using the FPE::fe1_encrypt method like this

```
BigInt c = FPE::fe1_encrypt(n, cc_ranked, key, sha1(acct_name));
```

Where the last parameter (the tweak) is created using the sha1 method as defined in the example like this

```
std::vector<byte> sha1(const std::string& acct_name)
   {
      SHA_160 hash;
      hash.update(acct_name);
      return unlock(hash.final());
   }
```

Now this method returns a value of type std::vector<byte>  However in the current stable release version 1.10.9 the method signature of the fe1_encrypt function is

```
BigInt BOTAN_DLL fe1_encrypt(const BigInt& n, const BigInt& X,
                         const SymmetricKey& key,
                         const MemoryRegion<byte>& tweak);
```

Where the last parameter is supposed to be of type MemoryRegion<byte>

On further investigation I noticed that in version 1.11.17 the method signature is changed to 

```
BigInt BOTAN_DLL fe1_encrypt(const BigInt& n, const BigInt& X,
                         const SymmetricKey& key,
                         const std::vector<byte>& tweak);
```

This signature matches more closely with the example posted in the documentation.

I have two questions about this
1 - Why the change?
2 - Can you provide details how to create and pass a tweak of type MemoryRegion<byte> for version 1.10.9?

Also it would be nice to note the version for which the examples apply to in the documentation

Thanks

**Comment by randombit** [comment]
Sorry for losing this issue @erotavlas 

The examples in the documentation should all apply to the latest version, any deviation from that is a bug.

The documentation on the website at that time was derived from the 1.11 documentation rather than the 1.10 docs. So it used `std::vector` for the tweak.

The tweak in FPE can be any value that is not expected to repeat. If the same tweak and input are used, identical ciphertexts result.

**Comment by MCCoolMoDAue** [comment]
I am also interested into how to conveniently create a `MemoryRegion` for a tweak.
So far I've done something like:
`	Botan::byte tweakData[6] = { 'A', 'B' , 'C', 'D', 'E', 'F' };
	const Botan::SecureVector<Botan::byte> tweak(tweakData, 6);`
but that seems a bit ugly.

**Comment by randombit** [comment]
In 1.10 that's about the best that can be done.

In 2.x `secure_vector` is just `std::vector` with a custom allocator so you can use initializer lists etc.
