### ISSUE TITLE
Add configure.py parameter to set library file name [FEATURE]

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1439]
As mentioned in the opening of #1403 (third bullet point), the naming of the library files is not consistent across platforms. 

It got me thinking: couldn't a  parameter be added to `configure.py` allowing the user to customize the name of the library?

This

```
 Installation options:
    --program-suffix=SUFFIX         append string to program names
    --library-suffix=SUFFIX         append string to library names
    --prefix=DIR                    set the install prefix
    --docdir=DIR                    set the doc install dir
    --bindir=DIR                    set the binary install dir
    --libdir=DIR                    set the library install dir
    --mandir=DIR                    set the install dir for man pages
    --includedir=DIR                set the include file install dir
```

could get a new option such as `--library-file-name=NAME` and become this

```
 Installation options:
    --program-suffix=SUFFIX         append string to program names
    --library-suffix=SUFFIX         append string to library names
    --library-file-name=NAME        set the library file name
    --prefix=DIR                    set the install prefix
    --docdir=DIR                    set the doc install dir
    --bindir=DIR                    set the binary install dir
    --libdir=DIR                    set the library install dir
    --mandir=DIR                    set the install dir for man pages
    --includedir=DIR                set the include file install dir
```

... allowing one to run `configure.py [...] --library-file-name=botan`, producing `botan.dll|lib` `botan.so|a`  etc depending on the target and ensuring uniform naming conventions across one's builds.

What say ye?

**Comment by randombit** [comment]
OK I guess. Probably good for people doing cross platform apps who otherwise are forced to accommodate different naming conventions. Just adds more complexity in here and more corner cases that we already aren't testing very well.

**Comment by DevSidious** [comment]
I think this potential new **optional** parameter would be a non intrusive addition. After all, nothing changes unless it is explicitly passed to `configure.py`. Would you care expanding on the subject of the corner cases that aren't yet tested very well? I can help with the testing.

**Comment by randombit** [comment]
Basically the various permutations of --library-suffix, --library-file-name, and shared object naming (which is already system-dependent). And how do the options combine - does `--library-file-name=floofy --library-suffix=bunny` produce `libfloofy.so` or `libfloofybunny.so`?

**Comment by randombit** [comment]
And sure we can just ignore all of that and throw in an option, but typically if something exists people expect it to work, so I'd prefer making sure it works and we understand the goals before the change is made.

**Comment by DevSidious** [comment]
Considering two hypothetical parameters such as `--override-library-name=NAME` and `--override-program-name=NAME`, their usage would be a clear statement for `configure.py`: **do not take any decisions when it comes to naming stuff, instead use what you are being told**.

This statement would basically render options such as `--program-suffix=SUFFIX` and `--library-suffix=SUFFIX` **redundant**.: we want to name our stuff according to what's passed to `--override-library-name=NAME` and/or `--override-program-name=NAME`. 

If one passes `--program-suffix` and/or `--library-suffix` together with `--override-library-name `and/or `--override-program-name`, the cleanest way to deal with this situation would be to **output a warning** and proceed to ignore `--library-suffix` and `--program-suffix`.

Scenarios:

1. One wants to name the library **libbotansky250**, while maintaining the old naming conventions for everything else:

`configure.py --blah-blah --override-library-name="libbotansky250"`

- program names stay the same: botan-cli, botan-test
- libraries become: libbotansky250.dll, libbotansky250.lib, libbotansky250.so etc

2. One wants to make use of both `--override-program-name` and `--override-library-name`

`configure.py --blah-blah --override-library-name="libbotansky250" --override-program-name="botansky250"`

- program names become: botansky250-cli, botansky250-test
- one gets: libbotansky250.dll, libbotansky250.lib, libbotansky250.so etc

For both 1. and 2. above, if one misunderstands the purpose of `override-*` and does something along the lines of:

`configure.py --blah-blah --library-suffix=whatever --override-library-name="libbunny250"`

This would result in:

a. A warning such as: "Using `--override-library-name=libbotansky250`" presumes you wish to take full control of library naming. Ignoring `--library-suffix=whatever`.
b. `configure.py` proceeds with `--override-library-name="libbotansky250`" and discounts `--library-suffix=whatever` and friends.

This scenario would not affect in any way what people are already used to, however it would make Botan's already powerful configuration engine even more flexible.

Depending on effort this may or may not be the path you wish to engage on. It's just a possible model.
