### ISSUE TITLE
Regression in retrieving X509 subject dn fields

### ISSUE THREAD

**Issue by dewyatt** [randombit/botan#1446]
I'm not sure if this was intentional, I didn't see anything in the news that would indicate any public pieces would change here.

I saw a few tests fail in ruby-botan w/2.4.0 and at least one of them would be from this:
```c++
#include <iostream>
#include <botan/x509cert.h>

int main(int argc, char *argv[]) {
    Botan::X509_Certificate cert("CSCA.CSCA.csca-germany.1.crt");
    for (auto& s: cert.subject_info("Email")) {
        std::cout << s << "\n";
    }
}
```

With 2.2.0, this will output the email address `csca-germany@bsi.bund.de` as expected. In 2.4.0, there is no output. (I didn't test any other versions)

**Comment by randombit** [comment]
Not intended. Probably introduced by #884

**Comment by randombit** [comment]
Workaround, use "RFC822" instead (works in all versions).

**Comment by dewyatt** [comment]
@randombit Thanks for the workaround, looks like it works well. :)

**Comment by randombit** [comment]
Fixed
