### ISSUE TITLE
Incorrect header path in includes

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1453]
`configure.py --blah-blah --blah-blah --prefix="C:/Temp/botan"`

```
PS C:\Temp> tree botan

C:\TEMP\BOTAN
├───bin
├───docs
│   └───botan-2.5.0
│       └───manual
├───include
│   └───botan-2
│       └───botan
└───lib
```

All header files reside in `include/botan-2/botan`, however they reference each other via (for example)
`#include <botan/block_cipher.h>`. Needless to say the `botan` sub-folder does not exist. 

This is unexpected.

**Comment by randombit** [comment]
The idea is applications use `-I${prefix}/include/botan-2`. The reason for the extra subdir here is to support parallel installation of other major versions (eg old botan-1.10, or future botan-3). This is important eg for Linux distros, several of which do ship botan 1.10 and 2.0. So I think this is expected (at least from developers perspective). But maybe should be more clearly documented.

**Comment by DevSidious** [comment]
I see. 

However, I do use quite a number of dependencies in my project. 

- All of them supply an include folder with headers for development;
- Some of them are even shipped with various Linux distros (notably Intel Threading Building Blocks);
- **None of them however leave me with an include folder wherein header files include other header files at non existing locations**;

Except Botan.

From a development perspective, building and installing Botan, leaves me with an extra step: run a script and "fix" the includes so that I can configure say `CMakeLists.txt` with something like `INCLUDE_DIRECTORIES("/opt/dev/libs/botan/2.5.0/include")`.

So I guess I'm stuck with "fixing" the includes?

**Comment by randombit** [comment]
Presumably none of the other libraries you are using are maintaining multiple parallel branches, either. (I'll note for example on my system OpenSSL, GTK, libpng, SDL among many others use versioned include dirs)

I do not understand why you would need to edit the installed headers. Just set the include path.

**Comment by DevSidious** [comment]
Consider a CMake enabled IDE such as say CLion. One needs to specify where the header files are so that one is able to instruct the IDE where to find them.

Say one has 2 Botan builds, one for debug and one  for release.

```
PS C:\dev\libs\botan> tree debug

C:\DEV\LIBS\BOTAN\DEBUG
├───bin
├───docs
│   └───botan-2.5.0
│       └───manual
├───include
│   └───botan-2
│       └───botan
└───lib
```

```
PS C:\dev\libs\botan> tree release

C:\DEV\LIBS\BOTAN\RELEASE
├───bin
├───docs
│   └───botan-2.5.0
│       └───manual
├───include
│   └───botan-2
│       └───botan
└───lib
```

One needs to tell one's IDE where to find the includes, resulting in:

`INCLUDE_DIRECTORIES("C:/dev/libs/botan/${CMAKE_BUILD_TYPE_LOWERCASE}/include/botan-2/botan")`

Or simply have a common folder containing Botan's header files:

`INCLUDE_DIRECTORIES("C:/dev/libs/botan/include")`

At this stage, the IDE knows where to find Botan's headers.

Next, one includes say  `aes.h` in one's project. `aes.h` includes `block_cipher.h`. `block_cipher.h` residing in the same folder as `aes.h`. However that's not where `aes.h` is looking for it. 

`aes.h`:

`#include <botan/block_cipher.h>`

instead of

`#include <block_cipher.h>`

Examples generated on Windows but it's the same story if one wants to develop on Ubuntu or Mac.

**Comment by randombit** [comment]
I still do not understand. Wouldn't you do

INCLUDE_DIRECTORIES("C:/dev/libs/botan/${CMAKE_BUILD_TYPE_LOWERCASE}/include/botan-2")

And include the header as `<botan/aes.h>`?

**Comment by DevSidious** [comment]
> Wouldn't you do
> 
> INCLUDE_DIRECTORIES("C:/dev/libs/botan/${CMAKE_BUILD_TYPE_LOWERCASE}/include/botan-2")
> 
> And include the header as <botan/aes.h>?
> 
> 

That won't work. There is no subfolder `botan `in `C:/dev/libs/botan/${CMAKE_BUILD_TYPE_LOWERCASE}/include/botan-2`.  

Botan dumps all it's header files in one folder: `include`. Howerver all those headers reference other headers as they exist in  a sub-folder `botan` whereas all of them exist in the sam folder.

Given this: 

`INCLUDE_DIRECTORIES("C:/dev/libs/botan/${CMAKE_BUILD_TYPE_LOWERCASE}/include/botan-2")` 

I would reference aes.h as `#include "aes.h"`. No problem there. 

However, `aes.h` needs `block_cipher.h`. And since `aes.h` has this line `#include <botan/block_cipher.h>` instead of `#include <block_cipher.h>`, the IDE will look for block_cipher.h in a non existing sub-folder `botan` instead of the same folder as `aes.h`.

**Comment by DevSidious** [comment]
Ok, scratch that. I found corrupted CMake caches that messed up my stuff. Sorry about that.
