### ISSUE TITLE
Slow RSA key generation on Windows 10

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1455]
Summary:

- It takes **17.3 seconds** on average to generate a 2048 bit RSA key on Windows 10 - i7 CPU @ 3.4 Ghz (4 cores).
- It takes **7.5 seconds** on average to generate a 2048 bit RSA key on a Linux VPS (2 cores @ 2.4 Ghz).
- It takes **15.5 seconds** on average to generate a 2048 bit RSA key on Linux, ARM32 (4 cores @ max 1.3 Ghz).
- It takes **2.9 seconds** on average to generate a 2048 bit RSA key on Linux ARM64 (4 cores).

**Clearly, Windows seems to stand apart. What am I missing here?**

Details:

`configure.py --debug-mode --disable-shared-library`

`Windows X86_64 `

`wmic cpu get name, numberofcores, maxclockspeed`

```
MaxClockSpeed  Name                                     NumberOfCores
3401           Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz  4
```

```
Created 512 RSA 2048 keys with ChaChaRNG   : Average seconds per key: 17.3036
Created 512 RSA 2048 keys with system_rng(): Average seconds per key: 17.0162
```

`Linux X86_64`

`lscpu`

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 77
Model name:            Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
Stepping:              8
CPU MHz:               2393.902
BogoMIPS:              4787.80
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
```

```
Created 512 RSA 2048 keys with ChaChaRNG   : Average seconds per key: 7.54821
Created 512 RSA 2048 keys with system_rng(): Average seconds per key: 7.48921
```

`Linux ARM32`

`lscpu`

```
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 2 (v7l)
CPU max MHz:           1333.0000
CPU min MHz:           666.5000
```

```
Created 512 RSA 2048 keys with ChaChaRNG   : Average seconds per key: 15.4672
Created 512 RSA 2048 keys with system_rng(): Average seconds per key: 15.5516
```

`Linux ARM64`

`lscpu`

```
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
```

```
Created 512 RSA 2048 keys with ChaChaRNG   : Average seconds per key: 2.9906
Created 512 RSA 2048 keys with system_rng(): Average seconds per key: 2.97329
```

**Comment by webmaster128** [comment]
`--debug-mode` adds `/Zi` to the compiler flags, which implies `/DEBUG`. In MSVC `/DEBUG` enabled all kind of checks and sanitisers that do much more when the default debug settings on other environments.

Could you try again without `--debug-mode`?

**Comment by randombit** [comment]
Also (on all platforms) `--debug-mode` disables all optimizations. It's very possible that MSVC's no-optimized builds are "less optimized" than a GCC no-optimized build (eg IIRC GCC still does SSA transformations with `-O0`).

If you want an optimized build with debug symbols use `--with-debug-info`.

**Comment by DevSidious** [comment]
I actually have another build of Botan with `configure.py --optimize-for-size --with-os-features=threads --disable-shared-library` set up for the Release build configuration. 

I did test in Release mode and was getting 'bout the same numbers on Windows. However it turns out my IDE was silently ignoring my Release settings and was building in Debug all the time.

Now that I took care of this, I'm getting seemingly "right" numbers on Windows: 1s/key on average.

What's shocking, is that although I was expecting a performance a drop in Debug, I wasn't expecting a 17x drop, nor was I expecting such a massive difference between MSVC and GCC. 

Quite interesting results, to say the least.

@webmaster128  & @randombit: thanks boys. 

Closing this.

**Comment by webmaster128** [comment]
FYI: if you want to test Botan's prime generation performance independently of your application, you can use the command-line interface compiled with the library: `./botan speed random_prime`.

I [observed a significantly wore performance on 32 bit Windows than on 32 bit Linux](https://github.com/randombit/botan/issues/256) (not accurate because of different hardware) but these results may be outdated. It somehow lost relevance to me, so I never investigated this further.
