### ISSUE TITLE
undefined reference to `vtable for Botan::ECDH_PrivateKey'

### ISSUE THREAD

**Issue by ZRobison** [randombit/botan#1456]
Hi,

I've been using Botan for a c++ project using mingw_64. For the most part everything seems to work fine, but I have run into a problem using the ECDH_PrivateKey. 

On compiling I get the following errors:
`(.rdata$.refptr._ZTVN5Botan15ECDH_PrivateKeyE[.refptr._ZTVN5Botan15ECDH_PrivateKeyE]+0x0): undefined reference to `vtable for Botan::ECDH_PrivateKey'`
`(.rdata$.refptr._ZTTN5Botan15ECDH_PrivateKeyE[.refptr._ZTTN5Botan15ECDH_PrivateKeyE]+0x0): undefined reference to `VTT for Botan::ECDH_PrivateKey'`

Even if a copy and past the code directly from the example code given (including the headers), [https://botan.randombit.net/manual/pubkey.html#id7](url), I still get an error. (You actually need to add a ';' to 'Botan::AutoSeeded_RNG rng' in there to get that code to compile) 

 The g++ flags I am using are: ` -std=c++11 -static -static-libgcc -static-libstdc++ -Wall -DDEBUG` 

Cheers

**Comment by randombit** [comment]
Thanks for pointing out the error in the doc, fixed.

I'm not sure why you're seeing this linking problem. It does not appear on Linux, I just checked with the same example. Can you build/run the tests successfully?

**Comment by ZRobison** [comment]
Before hand I couldn't build the docs or tests (which I just assumed was a windows thing as it had been mentioned in other issues)

I played with the script files and Makefile till i got it working on my windows machine. For those who have similar trouble the changes I made are:

build_docs.py:
`close_fds=True,`  change to `close_fds=sys.platform != "win32",` 

build_test.py:
Add python to every Popen call:
`subprocess.Popen(['python',`

Makefile:
remove ./ from these
```
CLI           = botan-cli.exe           
TEST          = botan-test.exe
LIBRARIES     = botan.dll
```


Yes I can run the tests and one fails. Here is the output:

```
Testing Botan 2.4.0 (release, dated 20180108, revision git:1e93b85fb5a4d628b80a9812b38b842b5c8b4363, distribution unspecified)
Starting tests drbg_seed:1515D4BA58B8B2C8
block:
AES-128 ran 15054 tests in 36.66 msec all ok
AES-192 ran 17550 tests in 24.67 msec all ok
AES-256 ran 20046 tests in 28.74 msec all ok
stream:
hash:
SHA-224 ran 14 tests all ok
SHA-256 ran 3494 tests all ok
SHA-384 ran 57 tests all ok
SHA-512 ran 57 tests all ok
SHA-512-256 ran 7 tests all ok
mac:
modes:
aead:
kdf:
pbkdf:
hmac_drbg:
util:
CT utils ran 20 tests all ok
Util load/store ran 229 tests all ok
Util round_down ran 6 tests all ok
Util round_up ran 11 tests all ok
asn1:
ASN.1 ASCII encoding ran 2 tests all ok
ASN.1 ASCII parsing ran 1 tests all ok
ASN.1 BMP string (UCS-2) parsing ran 1 tests all ok
ASN.1 UTF-8 encoding ran 2 tests all ok
ASN.1 UTF-8 parsing ran 1 tests all ok
ASN.1 universal string (UCS-4) parsing ran 1 tests all ok
BER nested indefinite length ran 1 tests all ok
BER stack recursion ran 1 tests all ok
asn1_printer:
ASN1_Pretty_Printer ran 5 tests all ok
charset:
Charset ran 14 tests all ok
Charset negative tests ran 5 tests all ok
cpuid:
CPUID ran 6 tests all ok
entropy:
hostname:
Hostname ran 21 tests all ok
iv_carryover:
mp_unit:
bigint_cnd_abs ran 6 tests all ok
bigint_cnd_add ran 4 tests all ok
bigint_cnd_sub ran 4 tests all ok
bigint_cnd_swap ran 12 tests all ok
octetstring:
OctetString ran 14 tests all ok
os_utils:
OS::get_high_resolution_clock ran 2 tests 1 FAILED
Failure 1: OS::get_high_resolution_clock high resolution timestamp does not duplicate produced 923861347547 unexpected value
OS::get_process_id ran 2 tests all ok
OS::get_processor_timestamp ran 1 tests all ok
OS::get_system_timestamp_ns ran 2 tests all ok
testcode:
Test Framework ran 17 tests all ok
util_dates:
Date parsing ran 81 tests all ok
calendar_point::to_string ran 1 tests all ok
Tests complete ran 56752 tests in 1.75 sec 1 tests failed
```

**Comment by ZRobison** [comment]
So have fully rebuilt it. Now the tests run a more comprehensive test set...

All the tests pass:
`Tests complete ran 2594026 tests in 60.22 sec all tests ok`

Including the ECDH tests.
```
ecdh_kat:
ECDH/Raw frp256v1 key agreement ran 25 tests in 79.48 msec all ok
ECDH/Raw secp192r1 key agreement ran 25 tests in 83.30 msec all ok
ECDH/Raw secp224r1 key agreement ran 25 tests in 83.46 msec all ok
ECDH/Raw secp256r1 key agreement ran 25 tests in 100.05 msec all ok
ECDH/Raw secp384r1 key agreement ran 25 tests in 168.00 msec all ok
ECDH/Raw secp521r1 key agreement ran 25 tests in 234.40 msec all ok
ecdh_keygen:
ECDH brainpool256r1 keygen ran 15 tests in 32.89 msec all ok
ECDH brainpool384r1 keygen ran 15 tests in 48.28 msec all ok
ECDH brainpool512r1 keygen ran 15 tests in 92.82 msec all ok
ECDH frp256v1 keygen ran 15 tests in 27.18 msec all ok
ECDH secp256r1 keygen ran 15 tests in 33.14 msec all ok
ECDH secp384r1 keygen ran 15 tests in 50.59 msec all ok
ECDH secp521r1 keygen ran 15 tests in 83.60 msec all ok
ecdh_unit:
ECDH key exchange ran 4 tests all ok
```

But I still get the vtable errors....

**Comment by randombit** [comment]
Thanks for mentioning the build problems. I was not aware of any of these issues. Some questions:

> ``build_docs.py: close_fds=True, change to close_fds=sys.platform != "win32",`` 

What happens if we close fds on Windows? I don't understand the issue.

> build_test.py:

Do you mean `src/scripts/build_tests.py`? An end user should not need to run this, this is just for developer testing. (The script should probably be renamed to make this more clear). The tests build as part of the make target.

> Makefile: remove ./ from these ...

CLI           = botan-cli.exe           
TEST          = botan-test.exe
LIBRARIES     = botan.dll
SCRIPTS_DIR    = src/scripts

OK these looks to be the same issue as in #1450 

But so far nobody has explained what the actual problem is.

> Change these lines to this : PYTHON_EXE     = python

Ordinarily this is the full path to the python executable, does this not work on Windows?

I'm still confused by the link error. Can you create an ECDSA or RSA key? Are you sure you are linking against the export library?

**Comment by ZRobison** [comment]
Calling configure with this call:

` python configure.py --os=mingw --link-method=hardlink`

Errors encountered when trying to use make:

- With the ./, if these are not removed make throws errors like this:
 `make: *** No rule to make target `.\libbotan-2.a', needed by `libs'.  Stop.`
  Could just be a make mingw specific thing?

- During make I get some warnings about unused variables.

- If `PYTHON_EXE     = python `not changed (the '\\''s disappear)
```
C:\ProgramData\Anaconda3\python.exe src\scripts/build_docs.py --build-dir="build"
/usr/bin/sh: C:ProgramDataAnaconda3python.exe: command not found
make: *** [build\doc.stamp] Error 127
```

- if `SCRIPTS_DIR    = src/scripts` not changed (the '\\' disappear)
```  C:\ProgramData\Anaconda3\python.exe: can't open file 'srcscripts/build_docs.py': [Errno 2] No such file or directory make: *** [build\doc.stamp] Error `2```

- if `fds=sys.platform != "win32"` not changed (seems to be a windows only problem, and this is a portable fix):
```
     File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 624, in __init__
    "close_fds is not supported on Windows platforms"
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
make: *** [build\doc.stamp] Error 1
```

When I first ran make the tests would not build so I tried to build them using the py file. But this time they seemed to build just fine without me changing anything. 


In my project I use class's from hash, stream_cipher and ECDSA keys/signatures. These work fine, but as soon as I try to use ECDH_PrivateKey I get the linking error.

**Comment by DevSidious** [comment]
> I'm not sure why you're seeing this linking problem. It does not appear on Linux, I just checked with the same example. 

Nor does it appear on Windows with MSVC.

**Comment by ZRobison** [comment]
Found the problem :/. Its always lame whens its something really simple... With my scons builder I made, I added botan-2 to libs in the wrong order for the test program. So when building the tests it didn't link properly. Then when building the example program I copied the flags over from the test... :( 

At least i hope some of the debugging I did is useful from something....

**Comment by randombit** [comment]
@ZRobison The MinGW build problems you encountered should be fixed now. If you run into any further problems please don't hesitate to open an issue.
