### ISSUE TITLE
build fails on Windows VS2013 when building specific module (fpe_fe1)

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#146]
I'm trying to build excluding all modules except those required for fpe_fe1
I'm using this command in Visual Studio 2013 Developer command prompt

    python configure.py --prefix=C:\BotanCrypto\Botan-1.11.17\DEBUG_BUILD --cc=msvc --cpu=x86 --build-mode=debug --no-autoload --enable-modules=fpe_fe1

Python version is 3.4

At the end nmake fails with this error 

       fatal error C1083: Cannot open include file: 'botan/numthry.h': No such file or directory

The result is as follows

INFO: Platform: OS="Windows" machine="AMD64" proc="Intel64 Family 6 Model 42
Stepping 7, GenuineIntel"
   INFO: Guessing target OS is windows (use --os to set)
   INFO: Canonicalizized CPU target x86 to x86_32/x86_32
   INFO: Target is msvc-windows-x86_32-x86_32
   INFO: Skipping, by request only - cvc
   INFO: Skipping, incompatible CPU - sha1_x86_64
   INFO: Skipping, incompatible OS - asm_x86_32 asm_x86_64 beos_stats dev_random
 egd fd_unix locking_allocator proc_walk unix_procs
   INFO: Skipping, incompatible compiler - mp_x86_32 mp_x86_64 rdrand simd_altiv
ec threefish_avx2
   INFO: Skipping, loaded only if needed by dependency - adler32 aead aes aes_ni
 aes_ssse3 aont asn1 base64 bcrypt benchmark blowfish camellia cascade cast cbc
cbc_mac ccm cfb chacha chacha20poly1305 clmul cmac codec_filt comb4p compression
 crc24 crc32 credentials cryptoapi_rng cryptobox ctr curve25519 datastor des dh
dl_algo dl_group dlies dsa dyn_load eax ec_gfp ec_group ecb ecc_key ecdh ecdsa e
lgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa1_bsi emsa_pkcs1 emsa_pssr emsa_raw
emsa_x931 ffi filters gcm gost_28147 gost_3410 gost_3411 has160 hash_id hkdf hma
c_drbg hres_timer http_util idea idea_sse2 if_algo kasumi kdf kdf1 kdf2 keccak k
eypair lion mars mce mceies md2 md4 md4_x86_32 md5 md5_x86_32 mgf1 misty1 mode_p
ad mp_generic noekeon noekeon_simd nr numbertheory ocb ofb oid_lookup openpgp pa
r_hash passhash9 pbes2 pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 pubkey
 rc2 rc4 rc5 rc6 rfc3394 rfc6979 rmd128 rmd160 rsa rw safer salsa20 seed serpent
 serpent_simd serpent_x86_32 sessions_sql sessions_sqlite3 sha1 sha1_sse2 sha1_x
86_32 simd simd_scalar simd_sse2 siphash siv skein srp6 system_rng tea threefish
 tiger tls tss twofish whirlpool win32_stats x509 x919_mac x931_rng xtea xtea_si
md xts
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlit
e3 zlib
   INFO: Using MP module mp_x86_32_msvc
   INFO: Loading modules alloc auto_rng base bigint block entropy fpe_fe1 hash h
ex hmac hmac_rng mac mdx_hash modes mp mp_x86_32_msvc pbkdf rng sha2_32 sha2_64
stream utils
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using hardlink to link files into build dir (use --link-method to chang
e)
   INFO: Botan 1.11.17 (released dated 20150619) build setup is complete

C:\BotanCrypto\Botan-1.11.17>nmake

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

 cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\base\init.cpp /Fobuild\obj\lib\base_init.obj
init.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\base\lookup.cpp /Fobuild\obj\lib\base_lookup.obj
lookup.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\base\scan_name.cpp /Fobuild\ob
j\lib\base_scan_name.obj
scan_name.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\base\symkey.cpp /Fobuild\obj\l
ib\base_symkey.obj
symkey.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\codec\hex\hex.cpp /Fobuild\obj
\lib\codec_hex.obj
hex.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\entropy\entropy_srcs.cpp /Fobu
ild\obj\lib\entropy_srcs.obj
entropy_srcs.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\hash\mdx_hash\mdx_hash.cpp /Fo
build\obj\lib\hash_mdx_hash.obj
mdx_hash.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\hash\sha2_32\sha2_32.cpp /Fobu
ild\obj\lib\hash_sha2_32.obj
sha2_32.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\hash\sha2_64\sha2_64.cpp /Fobu
ild\obj\lib\hash_sha2_64.obj
sha2_64.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\mac\hmac\hmac.cpp /Fobuild\obj
\lib\mac_hmac.obj
hmac.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\mac\mac.cpp /Fobuild\obj\lib\m
ac.obj
mac.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\big_code.cpp /Fobu
ild\obj\lib\math_bigint_big_code.obj
big_code.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\big_io.cpp /Fobuil
d\obj\lib\math_bigint_big_io.obj
big_io.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\big_ops2.cpp /Fobu
ild\obj\lib\math_bigint_big_ops2.obj
big_ops2.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\big_ops3.cpp /Fobu
ild\obj\lib\math_bigint_big_ops3.obj
big_ops3.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\big_rand.cpp /Fobu
ild\obj\lib\math_bigint_big_rand.obj
big_rand.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\bigint.cpp /Fobuil
d\obj\lib\math_bigint.obj
bigint.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\bigint\divide.cpp /Fobuil
d\obj\lib\math_bigint_divide.obj
divide.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_asm.cpp /Fobuild\ob
j\lib\math_mp_asm.obj
mp_asm.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_comba.cpp /Fobuild\
obj\lib\math_mp_comba.obj
mp_comba.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_karat.cpp /Fobuild\
obj\lib\math_mp_karat.obj
mp_karat.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_misc.cpp /Fobuild\o
bj\lib\math_mp_misc.obj
mp_misc.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_monty.cpp /Fobuild\
obj\lib\math_mp_monty.obj
mp_monty.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_mulop.cpp /Fobuild\
obj\lib\math_mp_mulop.obj
mp_mulop.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\math\mp\mp_shift.cpp /Fobuild\
obj\lib\math_mp_shift.obj
mp_shift.cpp
        cl /MDd /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /Od /Zi /DDEBUG /W3 /
wd4275 /wd4267 /Ibuild\include /nologo /c src\lib\misc\fpe_fe1\fpe_fe1.cpp /Fobu
ild\obj\lib\misc_fpe_fe1.obj
fpe_fe1.cpp
src\lib\misc\fpe_fe1\fpe_fe1.cpp(9) : fatal error C1083: Cannot open include fil
e: 'botan/numthry.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

**Comment by webmaster128** [comment]
Nice catch. That looks like a bug in the dependency system. Module `fpe_fe1` depends on `numbertheory` but this dependency is not set.

Can you try `--enable-modules=fpe_fe1,numbertheory`?

**Comment by erotavlas** [comment]
this time it fails with this error

Creating library .\botan.lib and object .\botan.exp
        cl /MDd /EHs /GR /Od /Zi /DDEBUG /D_CONSOLE /W3 /wd4275 /wd4267 /Ibuild\
include /nologo /c src\cmd\asn1.cpp /Fobuild\obj\app\asn1.obj
asn1.cpp
src\cmd\asn1.cpp(11) : fatal error C1083: Cannot open include file: 'botan/der_e
nc.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

**Comment by webmaster128** [comment]
Okay there are other errors in the command line tool. Thanks for spotting that! You can build the lib without the command line tool:

```
python configure.py --prefix=C:\BotanCrypto\Botan-1.11.17\DEBUG_BUILD --cc=msvc --cpu=x86 --build-mode=debug --no-autoload --enable-modules=fpe_fe1,numbertheory
nmake botan.dll
```

**Comment by erotavlas** [comment]
What about 
    nmake install

Usually I run that so it copies the files I need to the folder my Visual Studio project is pointing to.
Should I just wait for an update?  Or is it something I can quickly fix myself?

**Comment by webmaster128** [comment]
Well, nmake install just copies some files like

* `build\include\botan\*.h`
* `botan.dll`
* `botan.lib`

If you know what you need, you can copy it manually.

The other option is to drop the `--no-autoload` argument which will cause all the basic modules to be included in the build. Then `nmake` should work as expected.

**Comment by erotavlas** [comment]
Yes it works fine without the --no-autoload option, however since I was having that other issue with the mutex in my CLR wrapper, I thought I would try to build with the minimum necessary modules for my use (just the fpe_fe1 module) in hopes I could get rid of the dependency on mutex

**Comment by webmaster128** [comment]
I am on it. I'll make it compile everything and avoid hacks like `nmake botan.dll`. You'll hear from me next week.

**Comment by webmaster128** [comment]
You can try (at your own risk) the following branch this pull request: #148. It is made to make your original configuration work.

```
git clone https://github.com/webmaster128/botan.git
git checkout fpefe1-only
```

The code there has not been reviewed by anyone, so don't use it in production software. I might rebase the branch, i.e. if `git pull` does not work, you need to clone again.
