### ISSUE TITLE
Illegal_Point exception thrown when creating CSRs with ECDSA keys in a build with reduced modules

### ISSUE THREAD

**Issue by xentec** [randombit/botan#1482]
When using Botan(git:master) to create a CSR with it's own ECDSA(secp256r1) key and SHA-256 an `Illegal_Point` exception is always thrown from `/src/lib/pubkey/ec_group/point_gfp.cpp:710`: "OS2ECP: Decoded point was not on the curve".

**Comment by randombit** [comment]
Works for me. What are we doing that is different?

```
$ ./botan keygen --algo=ECDSA > ecc.key
$ ./botan gen_pkcs10 ecc.key localhost | openssl req -verify
verify OK
-----BEGIN CERTIFICATE REQUEST-----
...
```

Also worth mentioning there have been a *lot* of changes/optimizations in ECC over the last week or two in master. It is possible something is broken. Does the test suite pass?

**Comment by xentec** [comment]
Oh, sorry. I made a mistake using a Botan build with a minimized number of modules. 
Out of curiosity: which module is missing here to allow CSR creation as described above?
`tls,ecdsa,system_rng,sha2_32_x86,curve25519,ed25519,chacha20poly1305,chacha_sse2,clmul_ssse3`

**Comment by randombit** [comment]
I think everything with your module list is ok. `x509` includes all the cert/CSR code but that is pulled in implicitly by tls.

No matter what configuration you have, you should definitely not be getting a point decoding error. So I want to investigate this more.

**Comment by randombit** [comment]
Unfortunately I cannot reproduce.

What compiler (+version), OS, and CPU are you using?

**Comment by xentec** [comment]
GCC 7.3.0 on Linux 4.15.6 (Arch Linux) running on an Intel Core i5 M520.

**Comment by randombit** [comment]
Uh oh. I am attempting to repro using GCC 7.3.0 on Linux 4.15.6 on Arch.

Were you attempting to generate the CSR via command line interface or via C++ API?

**Comment by xentec** [comment]
Both.
But... I've been trying to reproduce the bug again with the latest master, but it seems to be gone now. Will investigate a bit more with older revisions lated.

**Comment by randombit** [comment]
One possibility, if you were doing `git pull && make` without an intervening run of `configure.py` (which deletes the entire object dir) is you got caught in a binary compatibility issue. If a structure changed size and some of the relevant files were recompiled but others were not, you would end up with code accessing data at the wrong locations in memory. For example 300cc7e5523 recently changed the size of `CurveGFp_Repr` and might have this effect.

**Comment by randombit** [comment]
@xentec Any luck reproducing? If not I think I'm going to chalk it up to ABI issue and close.

**Comment by xentec** [comment]
Oh, sorry for the late response. Nope, not reproduceable anymore.
