### ISSUE TITLE
Website currently unavailable

### ISSUE THREAD

**Issue by alex** [randombit/botan#1488]
https://botan.randombit.net/ is currently not responding

**Comment by randombit** [comment]
Thanks for mentioning. I bounced the machine to pick up a new kernel upgrade earlier today and it appears not to have come back up. Exciting!

**Comment by alex** [comment]
Oh noes

**Comment by randombit** [comment]
Ah the machine came back up but systemd in its infinite systemd-ness decided it didn't want to apply the network configuration. Thanks systemd.

Up now.
