### ISSUE TITLE
Setting the serial number for X509 certificates

### ISSUE THREAD

**Issue by phwork** [randombit/botan#1489]
When using `X509_CA`, the serial number of the certificate is always generated randomly (`make_cert`).
`X509_Cert_Options` allows setting a serial number, but only for the subject (`"X520.SerialNumber"`).
It would be nice to be able to control the serial number of certificates.

Simply adding a serial number argument to make_cert seems trivial, but adding a 10. argument to that function might not be the best option.
Are there already any plans to change the api?

**Comment by randombit** [comment]
No plans in that direction because nobody has mentioned it as an issue. It would be quite easy to support, but can you explain why a 128 bit random serial is not good for your application?

**Comment by phwork** [comment]
Thanks for the feedback.
We encountered this issue while migrating an application from another crypto library to botan, where it was possible to explicitly specify the serial number (despite the recommendation concerning predictable serial numbers).

**Comment by randombit** [comment]
So basically your system assumes (in the database or whatever) that cert serials are issued in sequence?

**Comment by phwork** [comment]
This is probably a corner case; the default behaviour of the application uses a simple counter, which we did not want to change so that users don't notice any changes (we wanted to migrate to Botan without changing the behaviour of the application / keeping changes as minimal as possible).

**Comment by randombit** [comment]
Can you take a look at #1491 and see if that change will work for you.

**Comment by phwork** [comment]
Great, LGTM - this fixes the issue. Thank you very much.

**Comment by randombit** [comment]
Fixed by #1491, closing
