### ISSUE TITLE
Custom attributes in X509_DN are not encoded

### ISSUE THREAD

**Issue by phwork** [randombit/botan#1490]
It is possible to add custom attributes to `X509_DN` by calling `add_attribute`.
The attributes are not written by `X509_DN::encode_into` because only a list of hardcoded attributes is considered.
This affects the certificate generation using `X509_CA::make_cert` and prevents the use of custom attributes in the subject. Is this behaviour intentional?

See also #1489 - same question here: are there already any plans to change the api?

**Comment by randombit** [comment]
That behavior is intentional in the sense that I wrote the code and that's what it does. But it is not really optimal, no.

There probably shouldn't actually be any need to change the API here. Just encode all the DN entries rather than only picking the ones to encode out of a hardcoded list.

**Comment by randombit** [comment]
Should be fixed by #1492

**Comment by phwork** [comment]
Thanks, I don't know if I can test/verify it soon, but the tests lgtm.

**Comment by randombit** [comment]
OK I believe everything here is all set  with #1492 merged, so I'm going to close the issue but feel free to reopen if something is missing.
