### ISSUE TITLE
Decrypt AES/CBC/PKCS7

### ISSUE THREAD

**Issue by anonyme0** [randombit/botan#1493]
Can anyone tell me how to decrypt the output of this code example :
https://botan.randombit.net/manual/cipher_modes.html#code-example

I have tried something like that but I don't know what to do next:
    
    const std::string plaintext("Your great-grandfather gave this watch to your granddad for good luck. Unfortunately, Dane's luck wasn't as good as his old man's.");
    const std::vector<uint8_t> key = Botan::hex_decode("2B7E151628AED2A6ABF7158809CF4F3C");
    Botan::secure_vector<uint8_t> pt(plaintext.data(), plaintext.data()+plaintext.length());
    
    std::unique_ptr<Botan::Cipher_Mode> enc(Botan::get_cipher_mode("AES-128/CBC/PKCS7", Botan::ENCRYPTION));
    enc->set_key(key);
    enc->start(rng.random_vec(enc->default_nonce_length()));
    enc->finish(pt);
    
    std::cout << "Encrypted:\n" << Botan::hex_encode(pt) << std::endl;
    
    /* DECRYPTION */
    
    std::unique_ptr<Botan::Cipher_Mode> dec(Botan::get_cipher_mode("AES-128/CBC/PKCS7", Botan::DECRYPTION));
    dec->set_key(key);
    enc->start(rng.random_vec(dec->default_nonce_length()));
    enc->finish(pt);

Thanks

**Comment by randombit** [comment]
The doc is not so clear here.

First, to decrypt you need to capture the IV and send it along with the ciphertext:

```
auto iv = rng.random_vec(enc->default_nonce_length());
enc->start(iv);
enc->process(buffer);
```

Then send both the ciphertext and the iv to the receiver, who does:

```
dec->start(iv);
dec->process(buffer);
```

Both sides need to use the same nonce, or the decryption doesn't work.

**Comment by anonyme0** [comment]
Thanks! But now I realize that I didn't chose the right algorithm to begin with. I want to encrypt a small string (<100 bytes) with a key and store it in a file, with the possibility of decrypting it at any moment (by re-launching the application, and thus not knowing the nonce). Is there any algorithm, in Botan, that would correspond to my needs? I have looked through the docs, but as I am fairly new to cryptography, I wasn't able to pinpoint the right thing.

**Comment by randombit** [comment]
Ordinarily you would just save the nonce along with the ciphertext by sticking them together into a single array.

It sounds like the best algorithm for what you are doing is SIV, which does not require a nonce (though it can include one) and retains full security even if no nonce is used or if the nonce is repeated. (This is unlike many other cipher modes, which break badly when this happens.) Using SIV is same as CBC above except with "AES-128/SIV".

**Comment by anonyme0** [comment]
I thought the nonce had to remain secret, but now that you said it, it's quite obvious it doesn't, or else it would be a key. One last thing then: how do I print the fully decrypted result (not in hex)?

**Comment by randombit** [comment]
Assuming your plaintext is a text string you just need to copy the bits out of the buffer:

`std::string s(reinterpret_cast<const char*>(buf.data()), buf.size())`

**Comment by anonyme0** [comment]
It gives me something like that:
V\204\340\234x\246\326-\303\343\317\252\262\272\355o\343\273í:1\363\345\347(U\273\233\\274\246\210t/Ѕ\263\317\315M\323\371\203E;\212x\336\372MzO\267\361l\3273tqn\222\253N\222\236\275"\263(?\205\262\373~۽\206^N+\215\247k\326j\223\372"媯^&\222\271\255\205\271N\255\276\364\305A,^\247%\320Ȳ\271M0\343\243	\240N)K@E\232\257\264"|e\233|}\3114\263Ʊ\207

**Comment by anonyme0** [comment]
Oh nevermind it was a just mistake in my code: I used the encryption object to decrypt the string. Now everything works just fine! Thanks a lot for your time!
