### ISSUE TITLE
Build failure on armv7hl

### ISSUE THREAD

**Issue by thmo** [randombit/botan#1495]
On Fedora Rawhide, I get these errors for armv7hl (gcc 8.0.1, botan 2.4.0):

~~~
g++ -fstack-protector -pthread -mfpu=neon -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c src/lib/block/noekeon/noekeon_simd/noekeon_simd.cpp -o build/obj/lib/block_noekeon_simd.o
In file included from build/include/botan/internal/simd_32.h:27,
                 from src/lib/block/noekeon/noekeon_simd/noekeon_simd.cpp:9:
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/8/include/arm_neon.h: In constructor 'Botan::SIMD_4x32::SIMD_4x32(uint32_t, uint32_t, uint32_t, uint32_t)':
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/8/include/arm_neon.h:10413:1: error: inlining failed in call to always_inline 'uint32x4_t vld1q_u32(const uint32_t*)': target specific option mismatch
 vld1q_u32 (const uint32_t * __a)
 ^~~~~~~~~
In file included from src/lib/block/noekeon/noekeon_simd/noekeon_simd.cpp:9:
build/include/botan/internal/simd_32.h:105:28: note: called from here
          m_neon = vld1q_u32(B);
                   ~~~~~~~~~^~~
make: *** [Makefile:174: build/obj/lib/block_noekeon_simd.o] Error 1
~~~
~~~
g++ -fstack-protector -pthread -mfpu=neon -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c src/lib/block/serpent/serpent_simd/serpent_simd.cpp -o build/obj/lib/block_serpent_simd.o
In file included from build/include/botan/internal/simd_32.h:27,
                 from src/lib/block/serpent/serpent_simd/serpent_simd.cpp:10:
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/8/include/arm_neon.h: In constructor 'Botan::SIMD_4x32::SIMD_4x32(uint32_t, uint32_t, uint32_t, uint32_t)':
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/8/include/arm_neon.h:10413:1: error: inlining failed in call to always_inline 'uint32x4_t vld1q_u32(const uint32_t*)': target specific option mismatch
 vld1q_u32 (const uint32_t * __a)
 ^~~~~~~~~
In file included from src/lib/block/serpent/serpent_simd/serpent_simd.cpp:10:
build/include/botan/internal/simd_32.h:105:28: note: called from here
          m_neon = vld1q_u32(B);
                   ~~~~~~~~~^~~
make: *** [Makefile:183: build/obj/lib/block_serpent_simd.o] Error 1
~~~
~~~
g++ -fstack-protector -pthread -mfpu=neon -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c src/lib/block/shacal2/shacal2_simd/shacal2_simd.cpp -o build/obj/lib/block_shacal2_simd.o
In file included from build/include/botan/internal/simd_32.h:27,
                 from src/lib/block/shacal2/shacal2_simd/shacal2_simd.cpp:9:
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/8/include/arm_neon.h: In constructor 'Botan::SIMD_4x32::SIMD_4x32()':
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/8/include/arm_neon.h:6761:1: error: inlining failed in call to always_inline 'uint32x4_t vdupq_n_u32(uint32_t)': target specific option mismatch
 vdupq_n_u32 (uint32_t __a)
 ^~~~~~~~~~~
In file included from src/lib/block/shacal2/shacal2_simd/shacal2_simd.cpp:9:
build/include/botan/internal/simd_32.h:65:30: note: called from here
          m_neon = vdupq_n_u32(0);
                   ~~~~~~~~~~~^~~
make: *** [Makefile:189: build/obj/lib/block_shacal2_simd.o] Error 1
~~~

I am not sure what's going wrong here, any help welcomed.

There are multiple `-mfpu=` options, the latter coming from the global `CXXFLAGS` used for building packages on Fedora, maybe those conflict.

**Comment by randombit** [comment]
I am not so much an expert in ARM but I believe `-mfpu=vfpv3-d16` indicates a non-NEON FPU, so basically (AIUI) all NEON is disabled by these flags. I should mention that -mfpu=neon is only used on specific files that use NEON intrinsics, and we only jump to those if `getauxval` indicates NEON support at runtime, so the binaries would be safe to run even on non-NEON systems.

I am definitely not an expert in how Fedora builds ARM packages so I'm not sure what the resolution is. If the intention is that NEON is not supported at all, then use `--disable-neon`. Otherwise I guess what needs to happen is that we should place ISA enabling flags like this *after* `$(BUILD_FLAGS)` in the makefile, so that general use flags don't override us. So I think you should follow up with Fedora on this point. If it is just a matter of changing location of the flags it is a trivial fix but I don't want to do that if it turns out not to be the desired behavior.

**Comment by thmo** [comment]
As far as I understand, Fedora packages for arm32 must also run on systems with a non-NEON FPU, that's why the build systems's `CXXFLAGS` has  `-march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16` (as a minimum requirement).

That said, any code is free to detect and use NEON at runtime.

So, if all code coming from the `**/*simd.cpp` files is guarded by `getauxval`, I think overriding `-mfpu` would not only be ok, but actually necessary to build the code.

As a reference, see e.g. [this mail](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/E3LJ7WTPPWKIOH7J3YVHQ5SUCONQ4KHJ/) basically saying that deliberately enabling `-mfpu-neon` for specific code fragments selected at runtime is ok.

**Comment by randombit** [comment]
OK great. Can you try 16355df? It should apply cleanly against 2.4.0

**Comment by thmo** [comment]
Seems to work.

Unfortunately I currently don't have access to a non-NEON machine, so I cannot really test whether the `getauxval` switch works there - but I suppose this has been tested independently already.

**Comment by randombit** [comment]
It has been tested but probably not in a while - I don't have any non-NEON ARM machines around anymore.

**Comment by randombit** [comment]
Closing since it looks like patch resolve the build issue. If there is any situation where we jump to NEON code on a non-NEON enabled device that is certainly a bug (but this seems unlikely given the code structure).

**Comment by thmo** [comment]
So, I got help in `#fedora-arm`. Someone kindly built the package on his Trim-Slice, which doesn't have a NEON. The `simd_32` test crashed with an illegal instruction. Build logs are here: https://pwhalen.fedorapeople.org/botan2/build.log

**Comment by randombit** [comment]
It seems I can replicate the problem with x86 also, by using `qemu-i386 -cpu pentium2` (which did not have SSE2 instructions). Oddly the crash happens in the branch where we are returning with no results after checking cpuid.

Ah and now I think I understand what is going on. We build the file containing the SIMD tests with -mfpu=neon/-msse2/whatever, in order to enable use of the intrinsics. But the compiler doesn't distinguish between enabling the intrinsics, and using it for any other codegen purposes. So probably gcc is emitting some NEON instruction for string compare or whatever, which of course does not work.

Good news is this issue only affects the tests. I'll work on a fix.

**Comment by randombit** [comment]
Should be fixed now

**Comment by thmo** [comment]
Just confirming that the fix also helps on the trimslice.
