### ISSUE TITLE
debug assertion failed issue

### ISSUE THREAD

**Issue by ronchristie52** [randombit/botan#1496]
Can anyone help me figure out what I'm doing wrong in this code?

I'm trying to modify a bit of code that was originally created (and worked well) with Botan 1.10.4 to work with the 2.4.0 library. The project is written in a language called Harbour, which is the reason for the rather odd constructs. Basically, it's straight C code, with interface functions that retrieve arguments (the hb_parc(x) functions) and return results (the hb_retc() function) to the calling program. The cLogLog() function is a simple data logger (fprintf() style, more or less).

It's designed to accept a short (2-300 bytes) message, generate a signature and return the concatenation of the message and the signature to the caller as a C pointer.

The code below dies with a Debug Assertion Failed _BLOCK_TYPE_IS_VALID(pHead->nBlockUse) when the function goes out of scope. I know that assertion means I'm trashing a block of memory somehow, but I can't see where I'm going wrong. The program is compiled with VS2013, if that makes a difference.

Thanks in advance for any help from clearer-eyed souls out there.

#pragma warning(disable:4996 4250 4275)
#include <stdafx.h>
#include <cstdlib>
#include <string>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <memory>
#include "dbginfo.h"
#include "hbapi.h"
#include <botan/pubkey.h>
#include <botan/dsa.h>
#include <botan/base64.h>
#include <botan/auto_rng.h>
#include <botan/lookup.h>
#include <botan/version.h>
#include <botan/parsing.h>
#include <botan/init.h>
#include <botan/rng.h>
#include <botan/secmem.h>
#include <botan/x509_key.h>
#include <botan/pkcs8.h>
#include <botan/data_src.h>

extern "C" void cLogLog(char *, ... );

//extern "C"
//{
//#ifdef WIN32
//#include <Rpc.h>
//#else
//#include <uuid/uuid.h>
//#endif
//}

using namespace Botan;

namespace {

}

extern "C" void HB_FUN_DSASIGN()
{
   int nAt;
   char buffer[16384] = { 0 };
   char Signature[16384] = { 0 };
   byte buf[16384] = { 0 };
   byte * bufaddr=&buf[0];
   char * cBuffer=(char *) &buffer[0];
   std::string passphrase(hb_parc(3));
   std::string message(hb_parc(2));
   std::string encoded;
   AutoSeeded_RNG rng;
   std::auto_ptr<PKCS8_PrivateKey> key(PKCS8::load_key(hb_parc(1), rng, passphrase));
   std::vector<uint8_t> signature;
   DSA_PrivateKey* dsakey = dynamic_cast<DSA_PrivateKey*>(key.get());
   if (!dsakey) {
      cLogLog("The loaded key is not a DSA key!");
      hb_retc("");
      return;
   }
   PK_Signer signer(*dsakey, "EMSA1(SHA-1)");
   DataSource_Memory in(message);
   
   cLogLog("DSASIGN sees arg 1=%s, arg2=%s, arg3=%s", hb_parc(1), hb_parc(2), hb_parc(3));
   while(size_t got = in.read(buf, sizeof(buf))) {
      signer.update(buf, got);
   }
   cLogLog("after in.read");
   strcpy(cBuffer,(char *) bufaddr);
   cLogLog("after strcpy 0");
   signature = signer.signature(rng);
   encoded = base64_encode(signature);
   strcpy(Signature, encoded.c_str());
   cLogLog("after strcpy 1");
   nAt=strlen(cBuffer);
   strcpy(&cBuffer[nAt],"-----BEGIN SIGNATURE-----");
   nAt+=25;
   strcpy(&cBuffer[nAt], Signature);
   cLogLog("after strcpy 2");
   nAt=strlen(cBuffer);
   strcpy(&cBuffer[nAt],"-----END SIGNATURE-----");
   cLogLog("after strcpy 3");
   hb_retc(cBuffer);
}

```

**Comment by randombit** [comment]
I'm not aware of any changes between 1.10 and 2.x that would trigger this issue and don't notice any particular problems in the posted code. It might help to test your binary with a memory checker like https://github.com/DynamoRIO/drmemory

Unrelated, but I notice this code:

```
DataSource_Memory in(message);
...
while(size_t got = in.read(buf, sizeof(buf))) {
signer.update(buf, got);
}
```

could be replaced by

```
signer.update(message);
```

then you don't need `buf`.

Also are you sure your input is short? Otherwise `strcpy(cBuffer,(char *) bufaddr)` will corrupt your stack.

The last section of code looks pretty error prone. In C++ it would be easier to do everything with `std::string` - `message + "-----BEGIN SIGNATURE-----" + encoded + "-----END SIGNATURE-----"`

**Comment by ronchristie52** [comment]
Hi guys,
I gave Dr. Memory a try, and it didn't report anything useful, but I've run into another roadblock I'm hoping you can help with. 

A lot of commentary about the assertion failure related to issues with memory allocation/deallocation between .dll boundaries, so I decided to try building Botan as a static library and trying that route. To do so, I did:

configure.py --disable-shared --cpu=x86_32

to get a 32-bit .lib. Configure ran successfully. However, when I issued the make command, I got:

cli_rng.obj : error LNK2019: unresolved external symbol "private: static unsigned __int64 Botan::CPUID::g_processor_features" (?g_processor_features@CPUID@Botan@@0_KA) referenced in function "public: static bool __cdecl Botan::CPUID::has_cpuid_bit(enum Botan::CPUID::CPUID_bits)" (?has_cpuid_bit@CPUID@Botan@@SA_NW4CPUID_bits@12@@Z)
speed.obj : error LNK2001: unresolved external symbol "private: static unsigned __int64 Botan::CPUID::g_processor_features" (?g_processor_features@CPUID@Botan@@0_KA)
math.obj : error LNK2019: unresolved external symbol "unsigned short const * const Botan::PRIMES" (?PRIMES@Botan@@3QBGB) referenced in function "private: class std::vector<class Botan::BigInt,class std::allocator<class Botan::BigInt> > __thiscall Botan_CLI::Factor::remove_small_factors(class Botan::BigInt &)" (?remove_small_factors@Factor@Botan_CLI@@AAE?AV?$vector@VBigInt@Botan@@V?$allocator@VBigInt@Botan@@@std@@@std@@AAVBigInt@Botan@@@Z)
tls_client.obj : error LNK2019: unresolved external symbol "public: static unsigned int Botan::TLS::Channel::IO_BUF_DEFAULT_SIZE" (?IO_BUF_DEFAULT_SIZE@Channel@TLS@Botan@@2IA) referenced in function "public: virtual void __thiscall Botan_CLI::TLS_Client::go(void)" (?go@TLS_Client@Botan_CLI@@UAEXXZ)
tls_server.obj : error LNK2001: unresolved external symbol "public: static unsigned int Botan::TLS::Channel::IO_BUF_DEFAULT_SIZE" (?IO_BUF_DEFAULT_SIZE@Channel@TLS@Botan@@2IA)
.\botan-cli.exe : fatal error LNK1120: 3 unresolved externals

As I indicated earlier, I'm using VS2013 Community, running under Win 7 SP1. Any help would be greatly appreciated.

**Comment by randombit** [comment]
Hm. Not sure what to make of this one. Static libraries seem to build ok with MSVC in CI. I do not use Windows so unfortunately am not in a good position to investigate this.

All three symbols (PRIMES, g_processor_features, IO_BUF_DEFAULT_SIZE) are static integer values, but I don't see much connection besides that.

But, it looks like all three issues are related to building the command line util. Did the static library itself build? And if so, were you able to link against it?

**Comment by ronchristie52** [comment]
Hi again,
Two part reply.
First part - the unresolved external problem disappeared after building the library with nmake instead of make. I had an old mingw installation on my dev. machine and it was interfering - mingw and VS don't play well together, it seems.
Second part - the static build under msvc ran into another problem. As I indicated earlier I'm using VS2013, so the following may not apply to VS2015 or VS2017 as the library structure changed for those versions, but I thought I'd follow up with you anyhow. In your configuration file ./src/build-data/cc/msvc.txt there's a section labeled mach_abi_linking where there are two values "all" and "all-debug", but both contain the compiler switch "/MDx" which sets up the use of either the multithreaded .dll or the multithreaded debug .dll runtimes, but there's no option for the static variant of the library. For me, the fix was trivial - I simply edited the makefile, changing /MD to /MT and re-ran it. As far as I'm concerned, you can close this issue at this point.

**Comment by randombit** [comment]
Did switching to a static library resolve the issue you were seeing with stack corruption? If so that is good for us to know if someone else has a similar problem in the future.

The  choice of runtime library is a known bug #210 I hope to address it before next release.

**Comment by ronchristie52** [comment]
Yes, it's working properly now.
