### ISSUE TITLE
Python bindings and packaging

### ISSUE THREAD

**Issue by thmo** [randombit/botan#1497]
The Python3 bindings call `dlopen` on `libbotan-2.so`. However, for the Fedora RPM packages, the package for the library itself only contains
```
/usr/lib64/libbotan-2.so.4.4.0
/usr/lib64/libbotan-2.so.4 -> libbotan-2.so.4.4.0
```
whereas the `libbotan-2.so` symlink is packaged in the `botan2-devel` subpackage (standard schema for all library packages).

In order to use the Python bindings, one would have to install the `botan2-devel` package.

So, I think it would make sense to `dlopen` on `libbotan-2.so.4` instead.

**Comment by randombit** [comment]
Unfortunately that ties the Python binding to the specific version of the library, when that is not otherwise required. We can try it as a fallback though.

**Comment by randombit** [comment]
Fixed in ab87904 should backport to 2.4.0 without problems.

**Comment by randombit** [comment]
Oh I flubbed the patch so you will also need 5a0598bde3edf9d0a597ad1414722ee8d9cf226f if you want to backport.

**Comment by thmo** [comment]
There's a typo in that commit (see comment there): It checks the return value of `botan_ffi_supports_api` to be `1`, but it should check for `0`.

**Comment by thmo** [comment]
Heh, comments crossed :smile:

**Comment by thmo** [comment]
For the record, I guess a cleaner solution would be to use ctypes' `find_libraray`:
```
$ python -c "from ctypes.util import find_library; print find_library('botan-2')"
libbotan-2.so.4
```
