### ISSUE TITLE
CVC test failing

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#150]
I found a failing CVC test, that is not run in the CI:

```
$ ./configure.py --enable-modules=cvc
$ make
$ ./botan-test cvc
Exception escaped test: Decoding error:  decoding failed
Tests 1 FAILs
```

Since I have no clue what CVC actually is, I'd like to leave it to someone else to dig into it.

**Comment by randombit** [comment]
Obviated by CVC's removal in 1.11.30
