### ISSUE TITLE
Botan TLS socket wrapper

### ISSUE THREAD

**Issue by theom** [randombit/botan#1507]
Not sure if I can post this here but I've implemented a small socket wrapper that uses Botan TLS. I've made the full source code available on [GitHub](https://github.com/theom/tls-socket).

My goal was to create a relatively pain free drop-in for the regular read and write calls in order to make it easier to upgrade existing code and I think I've achieved that, at least up to a point. There are some missing parts and I will try to update the code as I gain more experience in using it but I find it useful in my projects and I hope someone else will too.

I've also written a [short blog post](http://blog.axonehf.com/?p=1) briefly describing how the class works, along with how to use it.

Friendly comments and suggestions are welcome.

**Comment by randombit** [comment]
Nice! I imagine this would be pretty useful to some people. Maybe include a link in the wiki? https://github.com/randombit/botan/wiki/Users

Maybe we should have a distinct page for libraries which can be used in conjunction with/expand on the abilities of the library.

**Comment by theom** [comment]
Thanks, I really do hope someone will find the socket useful.

Yes, I think it would be useful to have a separate page that keeps track of libraries extending Botan. I imagine having it on a page of its own would make it easier to categorize things compared to putting it in a separate section on the current Users page.

**Comment by theom** [comment]
Should I go ahead and add the page?

**Comment by randombit** [comment]
Certainly go ahead

**Comment by theom** [comment]
Done. (please edit as you see fit)

You can also close this issue if you feel it's 'in the way'.

**Comment by randombit** [comment]
I also copied descriptions of a few of the other interesting libraries (rnp, cppssh, softhsm) to that page.

Closing this issue since there is nothing further that is actionable on our side.
