### ISSUE TITLE
EMSA-PKCS1-v1_5 encoding difference

### ISSUE THREAD

**Issue by astepanov83** [randombit/botan#1510]
I noticed a difference in how you implement EMSA-PKCS1-v1_5 encoding scheme and how it's defined in  RFC 3447/8017.

In you code you generate first:
`T[0] = 0x01;`

The RFCs say this:
`EM = 0x00 || 0x01 || PS || 0x00 || T.`
The difference is in a zero byte that goes at the beginning.

Tests wouldn't reveal this. There could be problems when verifying RSA signature generated by other code.

**Comment by randombit** [comment]
This is kind of non-obvious but I believe the reason it works is the output is limited to 1 less than the number of bits in the modulus (this happens in `RSA_Private_Operation::max_input_bits`) which ends up having the same effect as prefixing the padding with a leading zero byte. RSA operates on integers and the leading zero does not contribute in any way after the EM string is converted to an integer.

I'm somewhat confused by what you mean by "Tests wouldn't reveal this". If no test can reveal it, then there is no functional difference. :) Of course if you have an instance of a signature which does not verify then we would want to take a look at that.

**Comment by astepanov83** [comment]
I mean that if you generate a signature and validate it using Botan only in some test, you won't be able to detect whether the encoding scheme is conformant to RFC or not.

Yes, I'm going to test this function using gnupg: I will have something generated and signed with RSA key (in gpg) and then I will verify a signature using Botan. Gnupg uses EMSA-PKCS1-v1_5 encoding when signing with RSA keys. If I run into a problem, I'll report it.

Anyway, I think the issue can be considered as closed. I thought maybe there was a problem that noone noticed.

**Comment by astepanov83** [comment]
I mean that if you generate a signature and validate it using Botan only, then you won't detect whether the encoding scheme is conformant to RFC or not.

Yes, I'm going to test it using GnuPG: I will generate an RSA key and sign something with it. Then I will verify a signature using Botan. Gpg uses EMSA-PCKS1-v1_5 encoding when signing with RSA keys. If something goes wrong, I'll report it.

Anyway, I think the issue can be considered as closed. I thought there was a problem that noone noticed.

**Comment by randombit** [comment]
Ah yes if we only tested against ourselves this would be easy to miss. However in the test suite we have at least hundreds (maybe thousands) of instances of PKCSv1.5 signatures generated by other implementations and we generate the same value for each.

WRT GnuPG, the `rnp` project (https://github.com/riboseinc/rnp) is a PGP library that uses Botan for all cryptographic operations. Their test suite compares against GPG and there have not been any discrepancies found.
