### ISSUE TITLE
2.4.0 VS 2013 x64 failing test

### ISSUE THREAD

**Issue by DennisWeldy** [randombit/botan#1515]
I’ve downloaded and configured Botan 2.4.0 and get a failing test:
os_utils:
	OS::get_high_resolution_clock ran 2 tests all ok
	OS::get_process_id ran 2 tests all ok
	OS::get_processor_timestamp ran 1 tests 1 FAILED
	Failure 1: OS::get_processor_timestamp Processor timestamp does not duplicate produced unexpected result '0' expected '1'
	OS::get_system_timestamp_ns ran 2 tests all ok

My configuration is:
	configure.py --cpu=X64 --with-build-dir=Release I’m using Visual Studio 2013. 
I’m running the tests via.
               Release\botan-test
Fails in both release and debug. 

All of the other tests run nicely. 

I searched my archive from the mailing list but didn’t see anything about it. 

OS is Windows 7 64-bit. 

For what it’s worth, after building and running on a Mac (10.13) all tests ran fine.

**Comment by randombit** [comment]
We've seen reports of this a few times. I think it is a combination of the test being very picky, and something odd with QueryPerformanceCounter - since really it should not be repeating outputs. If you re-run the test (`./botan-test os_utils`) does it fail repeatedly or just every so often? Is this on physical hardware or a VM?

In any case the test failure is harmless so you don't need to worry about it. I think we will clean this up for 2.5 though since a failing test does tend to make people nervous.

**Comment by DennisWeldy** [comment]
Every so often, and it is on physical hardware.
Glad to hear it is harmless, I’ll proceed to upgrade to 2.4.0.

Thanks.
Dennis

**Comment by randombit** [comment]
I've changed the test so this should not happen again. Thanks for reporting this.

**Comment by DennisWeldy** [comment]
I set a break so I could see the difference during a passing case:
                              proc_ts1              71446076926     const unsigned __int64
                              proc_ts2              71446076927     unsigned __in64

Dennis

From: Dennis Weldy
Sent: Wednesday, March 28, 2018 2:23 PM
To: 'randombit/botan' <reply@reply.github.com>; randombit/botan <botan@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [randombit/botan] 2.4.0 VS 2013 x64 failing test (#1515)

Every so often, and it is on physical hardware.
Glad to hear it is harmless, I’ll proceed to upgrade to 2.4.0.

Thanks.
Dennis

**Comment by randombit** [comment]
Ok so QueryPerformanceCounter must not being using the TSC register, since way more than 1 cycle has passed between the two calls (rdtsc alone being 25-100 cycles). On some hardware maybe Windows falls back to HPET or some other lower resolution timer even if TSC is available.

**Comment by DennisWeldy** [comment]
Yep, looks to be the case.

https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx#direct_tsc_usage
On systems where the TSC is not suitable for timekeeping, Windows automatically selects a platform counter (either the HPET timer or the ACPI PM timer) as the basis for QPC.

I’m using an Intel I7-2960XM

Dennis
