### ISSUE TITLE
Minor distribution patch related to rst2man invocation

### ISSUE THREAD

**Issue by lfam** [randombit/botan#1516]
Hello!

I'm working on packaging Botan for GNU Guix.

Our Docutils package provides `rst2man.py`. This appears to be the choice of the Docutils developers since we don't patch docutils or build it with any modifications.

However, Botan's build scripts look for `rst2man`. The program is available under this name on some distros.

I think we will patch Botan's `build_docs.py` script as shown below to work around this issue. I'm notifying you in accordance with your request in the Botan manual, section [Notes for Distributors](https://botan.randombit.net/manual/packaging.html#minimize-distribution-patches). Please let me know if you see any problems with this.

```diff --git a/src/scripts/build_docs.py b/src/scripts/build_docs.py
index 1787016..60e6575 100755
--- a/src/scripts/build_docs.py
+++ b/src/scripts/build_docs.py
@@ -158,7 +158,7 @@ def main(args=None):
         cmds.append(['cp', manual_src, manual_output])
 
     if with_rst2man:
-        cmds.append(['rst2man', os.path.join(manual_src, 'cli.rst'),
+        cmds.append(['rst2man.py', os.path.join(manual_src, 'cli.rst'),
                      os.path.join(cfg['build_dir'], 'botan.1')])
 
     cmds.append(['touch', doc_stamp_file])
```

**Comment by randombit** [comment]
Thank you, both for doing the packaging work and for letting me know about this issue. The script is available under both names on my distro so I did not give it any further thought.

Unfortunately it looks like it is *only* available as `rst2man` on Debian. So the right course of action is probably to probe PATH for both variants. I will try to address this before 2.5 release next week.

**Comment by randombit** [comment]
We now search for rst2man or rst2man.py in PATH and use whichever is found so I believe this issue is resolved
