### ISSUE TITLE
Multiple test errors replicating "Travis-Fuzzers" build on *Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by mgierlings** [randombit/botan#1518]
I just tried to closely replicate the Travis-Fuzzer build on my local system.

```
Kubuntu 16.04.4 LTS
4.4.0-116-generic #140-Ubuntu SMP
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

./configure.py --disable-shared --unsafe-fuzzer-mode --with-debug-info --build-fuzzers=test --with-sanitizers --disable-modules=locking_allocator,mem_pool --without-os-features=threads
```

I manually added `fno-omit-frame-pointer` to `CXX` in the Makefile. Running the test bench with this setup I see:

```
...
ECDSA/Raw(SHA-384) signature generation ran 8 tests in 63.80 msec all ok
ECDSA/Raw(SHA-512) signature generation ran 8 tests in 53.74 msec all ok
ecdsa_unit:
src/tests/unit_ecdsa.cpp:306:51: runtime error: load of value 99, which is not a valid value for type 'Compression_Type'
ECDSA Unit ran 56 tests all ok
ecdsa_verify:
ECDSA/Raw signature verification ran 63 tests in 267.66 msec all ok
...
Entropy source system_rng ran 3 tests in 0.01 msec all ok
ffi:
build/include/botan/internal/ffi_util.h:110:26: runtime error: member call on address 0x6030007a4d90 which does not point to an object of type 'botan_struct'
0x6030007a4d90: note: object is of type 'botan_mp_struct'
 91 01 00 16  90 c4 2e 03 00 00 00 00  d2 b9 28 c8 be be be be  40 ce 1f 01 60 60 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'botan_mp_struct'
FFI ran 24 tests all ok
FFI CBC cipher ran 33 tests all ok
...
OID add string ran 3 tests all ok
os_utils:

Program received signal SIGILL, Illegal instruction.
std::_Function_handler<int(), Botan_Tests::(anonymous namespace)::OS_Utils_Tests::test_cpu_instruction_probe()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/5/functional:1857
1857		    std::forward<_ArgTypes>(__args)...);
(gdb) bt
#0  std::_Function_handler<int(), Botan_Tests::(anonymous namespace)::OS_Utils_Tests::test_cpu_instruction_probe()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/5/functional:1857
#1  0x000000000280bbf1 in std::function<int ()>::operator()() const (this=0x7fffffff9fb0) at /usr/include/c++/5/functional:2267
#2  Botan::OS::run_cpu_instruction_probe(std::function<int ()>) (probe_fn=...) at src/lib/utils/os_utils.cpp:417
#3  0x000000000099c312 in Botan_Tests::(anonymous namespace)::OS_Utils_Tests::test_cpu_instruction_probe (this=<optimized out>) at src/tests/test_os_utils.cpp:178
#4  Botan_Tests::(anonymous namespace)::OS_Utils_Tests::run (this=<optimized out>) at src/tests/test_os_utils.cpp:42
#5  0x0000000000c039c3 in Botan_Tests::Test_Runner::run_tests (this=this@entry=0x7fffffffd350, tests_to_run=std::__debug::vector of length 153, capacity 153 = {...}, test_run=test_run@entry=0, 
    tot_test_runs=tot_test_runs@entry=1) at src/tests/test_runner.cpp:261
#6  0x0000000000c15ca0 in Botan_Tests::Test_Runner::run (this=this@entry=0x7fffffffd350, requested_tests=std::__debug::vector of length 0, capacity 0, data_dir="src/tests/data", pkcs11_lib="", provider="", 
    log_success=log_success@entry=false, run_online_tests=false, run_long_tests=false, abort_on_first_fail=false, drbg_seed="", runs=1) at src/tests/test_runner.cpp:196
#7  0x0000000000440198 in main (argc=<optimized out>, argv=<optimized out>) at src/tests/main.cpp:100
```

**Comment by randombit** [comment]
I think GCC 5 sanitizers are more strict than what is in 4.8. All errors are expected.

> runtime error: load of value 99, which is not a valid value for type 'Compression_Type'

Intentionally testing handling of out of range enum.

> runtime error: member call on address 0x6030007a4d90 which does not point to an object of type 'botan_struct'

Intentionally freeing a struct using the wrong FFI function (to verify that we detect this without corrupting memory).

> SIGILL in Botan_Tests::(anonymous namespace)::OS_Utils_Tests::test_cpu_instruction_probe()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)

Intentionally invoking an undefined instruction (on x86, `ud2`) to verify our code to catch SIGILL works.

I planned on adding a flag to the tests that causes any intentional undefined behavior to be skipped for the benefit of sanitizers.

**Comment by mgierlings** [comment]
Okay, thanks for clearing this up. I encountered one more issue with this configuration on another machine:

`
X509test path validation softfail ran 4 tests in 10.00 msec 2 FAILED
Failure 1: X509test path validation softfail test warnings produced unexpected result '0' expected '1'
Failure 2: X509test path validation softfail test warnings string produced unexpected result '' expected '[0] OCSP URL not available'
`
If this was expected as well I'd say this can be closed.

**Comment by randombit** [comment]
> Failure 1: X509test path validation softfail test warnings produced unexpected result '0' expected '1'
> Failure 2: X509test path validation softfail test warnings string produced unexpected result '' expected '[0] OCSP URL not available'

That's because disabling threads also breaks `std::async` which is currently used in OCSP. Probably we should skip the test in that configuration.

**Comment by randombit** [comment]
Added an `--avoid-undefined` option to signal the  tests to avoid any ub and fixed the problem where the softfail tests didn't work without threads.
