### ISSUE TITLE
Extended X509 path validation fails suddenly in 2.4.0

### ISSUE THREAD

**Issue by bkircher** [randombit/botan#1521]
Output: 

```
Failure 1: Extended X509 path validation 01 path validation result produced unexpected result 'Certificate has expired' expected 'Verified'
```

Steps to reproduce:

```
$ git checkout 2.4.0
$ ./configure.py --disable-static-library
$ make
$ LD_LIBRARY_PATH=. ./botan-test
```

**Comment by randombit** [comment]
Test certs expired Mar 31st, we should be validating against a fixed reference time rather than the system clock.

**Comment by randombit** [comment]
Fixed now, thanks.  For 2.4.0 you can either backport 575fdea or just wait for 2.5 which comes out tomorrow.
