### ISSUE TITLE
bigint test does not finish when built with Arch Linux default makepkg config

### ISSUE THREAD

**Issue by orangecms** [randombit/botan#1529]
Edit: I first thought the below issue was related to the configuration I passed to botan, but it seems rather that the flags passed to the compiler, linker etc are the issue.

I have the following configuration (2.5.0 release): `./configure.py --prefix=/usr`

When I build and run `./botan-test`, the bigint unit test never finishes (I kept it running for half a day and then stopped):
```
bc_pad:
ESP ran 15 tests in 0.01 msec all ok
NoPadding ran 10 tests in 0.01 msec all ok
OneAndZeros ran 13 tests in 0.01 msec all ok
PKCS7 ran 12 tests in 0.01 msec all ok
X9.23 ran 13 tests in 0.01 msec all ok
bcrypt:
bcrypt ran 367 tests in 1.79 sec all ok
bigint_unit:
^C
==> ERROR: Aborted by user! Exiting...
==> ERROR: A failure occurred in check().
    Aborting...
```

I need compression lib support for [NeoPG](https://github.com/das-labor/neopg), which is why [I created another package in the Arch User Repository (AUR)](http://aur.archlinux.org/packages/botan-with-compression). The configuration there is `./configure.py --prefix=/usr --with-bzip --with-zlib`.

Arch Linux has a build tool called `makepkg`, which takes a `PKGBUILD` file (the build recipe) and has some default config in  `/etc/makepkg.conf`. I copied the compile flags etc., and they are sufficient to reproduce the issue in isolation:
```bash
#!/usr/bin/bash

export CARCH="x86_64"
export CHOST="x86_64-pc-linux-gnu"

#-- Compiler and Linker Flags
# -march (or -mcpu) builds exclusively for an architecture
# -mtune optimizes for an architecture, but builds for whole processor family
export CPPFLAGS="-D_FORTIFY_SOURCE=2"
export CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
export CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
#-- Make Flags: change this for DistCC/SMP systems
export MAKEFLAGS="-j8"
#-- Debugging flags
export DEBUG_CFLAGS="-g -fvar-tracking-assignments"
export DEBUG_CXXFLAGS="-g -fvar-tracking-assignments"

./configure.py --prefix=/usr #--with-bzip --with-zlib
make -j8
./botan-test # <--- hangs at bigint_unit:
```

Compiler in use: `g++ (GCC) 7.3.1 20180312`

Addendum: When I build without the above flags, the tests pass just fine after a minute.

**Comment by orangecms** [comment]
I could reproduce the issue on another machine with a different CPU, also amd64, using `g++ (Gentoo Hardened 7.3.0 p1.0) 7.3.0`. I have narrowed it down to the `-O2` optimization flag. However, with LLVM (`CXX=clang++`), the issue goes away. :tada:

I see in the default config of Botan (https://github.com/randombit/botan/blob/c1e5b7193c493ec3d8946fadeb89c05c912b10c5/src/build-data/cc/gcc.txt#L12) that the optimization is set to `-O3`, which confuses me a bit. Per [Gentoo's docs](https://wiki.gentoo.org/wiki/GCC_optimization#-O), this seems to be discouraged:
> -O3: the highest level of optimization possible. It enables optimizations that are expensive in terms of compile time and memory usage. Compiling with -O3 is not a guaranteed way to improve performance, and in fact, in many cases, can slow down a system due to larger binaries and increased memory usage. -O3 is also known to break several packages. Using -O3 is not recommended. However, it also enables -ftree-vectorize so that loops in the code get vectorized and will use AVX YMM registers.

Anyway, it would be great if this could be fixed. I will be overriding the default flags for a temporary solution.

**Comment by randombit** [comment]
@xyproto @orangecms Would it be better for the main Arch package to just enable the compression support? Since zlib and bzip2 are basically mandatory on Arch anyway, adding the additional dependencies doesn't seem a problem.

**Comment by xyproto** [comment]
@randombit I will look into enabling both O3 and compression support for the botan package on Arch Linux.

**Comment by orangecms** [comment]
@randombit Soooo... I have run quite some builds yesterday, and I first also thought it would probably be the `-no-plt` flag. However, I only set `-O2` to reproduce the issue. I'm now on a third machine (Gentoo again this time :D), and I can still reproduce it.

Now I just tried the above patch, and it solves the problem. Yay!

@xyproto I'd really love to have compression support in our upstream package as well - then I can abandon the AUR package and we do not double the work. :)

And sorry @randombit - I hadn't found the issue when I was searching here. I should have expanded it to include closed issues; stupid me. :upside_down_face: I'm closing this now and looking forward to 2.6.0. Thank you for the great work! <3

**Comment by orangecms** [comment]
A final note: I tried with GCC 5.4.0 now, and the issue goes away again. It could really just be a bug in GCC7, since it works with clang and GCC5. :shaved_ice:

**Comment by randombit** [comment]
I think it really is our problem, inline asm with incorrect constraints/clobbers is kind of infamous for working fine for years and then suddenly breaking with a slight change in context (eg different compiler register placement, or a restructuring of the code that surrounds the inline asm).

**Comment by randombit** [comment]
I just got a report that Debian is also affected by this, and now that I look at it further I see that with `-O2` we also miscompile, but with `-O3` everything is ok. Since I only tested with -O3 this was missed in testing.
