### ISSUE TITLE
passes_sanity_check() declines years after 2100

### ISSUE THREAD

**Issue by fschoenm** [randombit/botan#1536]
We are currently running into an issue with the function ``passes_sanity_check()`` that declines a certificate because the validity ends after the year 2100. On the mailing list, I found an [old thread from 2012](https://lists.randombit.net/pipermail/botan-devel/2012-April/001563.html) that already described this problem. 

At that time, you wrote that you will probably set it to a higher limit. Is there a follow-up to this topic?

**Comment by randombit** [comment]
Nothing happened here. I will increase it to 2200. Also I notice we are sloppy about checking days, we accept Feb 31st as valid for example. I'll fix that also.

**Comment by randombit** [comment]
Fixed now, thanks
