### ISSUE TITLE
Deprecate and remove MSVC 2013 support

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1557]
Timeline:

 - 2.7.0 (July 2018): Add a build time warning (in configure.py output) if 2013 is detected
 - 2.8.0 (October 2018): Forcing acknowledgement of deprecation at build time
 - 2.9.0 (Jan 2019): MSVC 2013 support removed, constexpr allowed

**Comment by randombit** [comment]
Current support for bakefile is limited to VC 2013. In fact it appears latest release of bakefile only supports up to VC2013. So possibly bakefile build is also dropped as part of this change. @neusdan thoughts?

**Comment by neusdan** [comment]
Visual Studio can migrate old project files to newer versions and the current Bakefile master repo already supports VS 2015 and 2017. So I think it's still useful.

On the other side it would be nice if we find an alternative to Bakefile which is more maintained.

**Comment by randombit** [comment]
CMake can generate VC project files, right? So maybe the answer is extend CMake support to also handle this case, then drop bakefile.

Alternately we could generate project files directly, but that probably gets ugly quickly.
