### ISSUE TITLE
BCrypt doesn't work onWindows

### ISSUE THREAD

**Issue by flipback** [randombit/botan#1565]
I use function check_bcrypt to check password:
```C++
                auto pass = "";
                auto hash = "$2a$10$I0fc8gzfwMLFS2H79LFxHOJ6CMd8jB7s1MizshLwQqrwe5DlMJnNC";
                if (Botan::check_bcrypt(pass, hash)) {
                    LOG_INFO("Success");
                } else {
                    LOG_INFO("Unsuccess");
                }
```
This code works perfect in Linux and the function returns true as it must do. On Windows it returns false.

Linux version is compiled by gcc-6.3.3 for x64 architecture. Windows version uses VisualStudio 2017 compiler for x86 architecture.
Botan's version is 2.6.

**Comment by webmaster128** [comment]
Could you convert the parameters into std::string explicitly and then check `hash.size()`

**Comment by flipback** [comment]
@webmaster128  I've just checked it. The size is 60 and I use UTF-8 for my source files.

**Comment by webmaster128** [comment]
okay, good. Can you use a debugger to see at which point of https://github.com/randombit/botan/blob/2.6.0/src/lib/passhash/bcrypt/bcrypt.cpp#L133 check_bcrypt returns `false`?

**Comment by flipback** [comment]
I added some debug messages in check_bcrypt :

```C++
  if(hash.size() != 60 ||
      hash[0] != '$' || hash[1] != '2' || hash[2] != 'a' ||
      hash[3] != '$' || hash[6] != '$')
      {
		std::cerr << "***** Wrong format *****" << (int) hash.size() << std::endl;
      return false;
      }

Out (see ***** Wrong format *****):
```
2018-05-09 14:37:08:647 INFO  [8380] [D:\Projects\server-io\src\security\authentication_provider.cpp:48]   Size of hash outside of check_bcrypt 60
***** Wrong format *****-858993460
2018-05-09 14:37:08:657 INFO  [8380] [D:\Projects\server-io\src\security\authentication_provider.cpp:53]   unsuccess
```

I don't know how to explain this result! Outsied of function the hash string has size 60, but inside it seems to be broken.

**Comment by flipback** [comment]
@webmaster128  I guess the problem is in compiler flags and options. I use botan as a DLL library.

**Comment by webmaster128** [comment]
okay, yes. That looks broken. Your DLL is compiled for 32 bit?

Did you use the same version of the C++ standard library for DLL and main program?

**Comment by flipback** [comment]
I've changed my application to link botan as a static library. It didn't link botan right now because I had to configure the library to debug mode. Now it works ok. I suppose  I had the same problem with DLL. Sorry , that I've taken your time, I have must check the compilation options before to open the bug.

**Comment by webmaster128** [comment]
@flipback No problem! I'm glad to hear it works now
