### ISSUE TITLE
Regarding C++17

### ISSUE THREAD

**Issue by meldavis** [randombit/botan#1566]
Related to #1191.

I needed to test the feasibility of statically linking botan to a C++17 application compiled with MSVC (which is now fully C++17 conformant.) I expected to make pages of code edits.  I'm extremely happy to report that I needed to make only one teeny change in the library and one tiny change in the test. 

**In the library:**
The filesystem header is std now.
https://github.com/randombit/botan/blob/8f3f7743472ba625a0bb249cd06651ed13325b87/src/lib/utils/filesystem.cpp#L38
changed to:
```c++
#if (_MSVC_LANG >= 201703L)
   using namespace std::filesystem;
#else
   using namespace std::tr2::sys;
#endif
```

**In the test:** 
```std::random_shuffle``` is gone. Must use ```std::shuffle``` (which is compatible with both C++11 and C++17) with a RandomBitGenerator object.

https://github.com/randombit/botan/blob/8f3f7743472ba625a0bb249cd06651ed13325b87/src/tests/test_x509_path.cpp#L581-L590

changed to:

```c++
         struct random_bit_generator {
            size_t s;
            using result_type = size_t;
            const static result_type min() { return 0; }
            const static result_type max() { return std::numeric_limits<size_t>::max(); }
            result_type operator()() {
                Test::rng().randomize(reinterpret_cast<uint8_t*>(&s), sizeof(s));
                return s;
            };
         } rbg;

         for(size_t r = 0; r < 16; r++)
            {
            //std::random_shuffle(++(certs.begin()), certs.end(), uniform_shuffle);
            std::shuffle(++(certs.begin()), certs.end(), rbg);

```

I configured botan with this command and ran the test with no errors. Great!
```
python configure.py --disable-shared-library --debug-mode --cc-abi-flags=/std:c++latest
```

I expect gcc and clang would compile to c++17 with a similar change in the 'filesystem' header.

**Comment by randombit** [comment]
Fixed now in master, thanks again.
