### ISSUE TITLE
PDF documentation index mis-formatted

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1573]
Some lines that are too long and should wrap, do not wrap - overlapping with the next column instead.
This is what it looks like:

![screen shot 2018-05-22 at 11 47 04](https://user-images.githubusercontent.com/5923577/40385043-5c7368a2-5dd3-11e8-81ac-0bd3ea9c0de0.png)
![screen shot 2018-05-22 at 11 47 29](https://user-images.githubusercontent.com/5923577/40385045-5e2ec7e0-5dd3-11e8-8042-0804e2c184c5.png)

**Comment by randombit** [comment]
I imagine TeX just doesn't know where it should break when there are no spaces. Probably the fix is to go to 1 column for the index? It appears Sphinx allows one to insert arbitrary LaTeX via the configuration so maybe it can be fixed that way.

**Comment by randombit** [comment]
I found something in the Sphinx docs that helped.

http://www.sphinx-doc.org/en/stable/config.html#options-for-latex-output

**Comment by mouse07410** [comment]
Thank you, perfect now.
