### ISSUE TITLE
Allow disablement of dynamic load function

### ISSUE THREAD

**Issue by bazineta** [randombit/botan#1576]
In days of yore, lo, even unto several months ago, those with a sufficient level of paranoia as to statically link things, could, in addition, disable dynamic load support via use of:

```
--without-os-features=dlopen
```

While I see that it's with good reason that many features of this nature have been folded into the POSIX determinations, etc., I think that there are valid reasons for wanting to disable dynamic load support even if the system provides it, and the old approach was a convenient way to achieve that.

At present, it seems that manually hacking `dyn_load.cpp` is the way to do this now; it'd be nice to have the option again.

**Comment by randombit** [comment]
Yeah good point.

You should be able to do this without hackery with `--disable-modules=dyn_load` (that's the only code that actually calls `dlopen` since it's our shared lib wrapper).

**Comment by randombit** [comment]
It may be worth moving `dlopen` back outside of the main POSIX flag for this.

**Comment by bazineta** [comment]
`--disable-modules=dyn_load` tested and does what we're looking for, thanks!
