### ISSUE TITLE
Visual C++ 2013 does not support noexcept

### ISSUE THREAD

**Issue by LightBender** [randombit/botan#16]
I have solved this problem for now with a sed call in my build script. But I thought it would be good to note it here. According to Microsoft the next release of VC++ will support noexcept.

sed -i 's/noexcept//g' ../TitaniumCore/Botan_WIN*

**Comment by webmaster128** [comment]
Most if the work is done in https://github.com/randombit/botan/commit/c84b150c50093c680f18f0792bf7d52f157b01fe. There is only one occurrence of plain `noexcept` left in `src/lib/math/ec_gfp/curve_gfp.h` as pointed out in https://github.com/randombit/botan/pull/56.

**Comment by neusdan** [comment]
Can be closed now. #56

**Comment by patlecat** [comment]
Excellent, thanks :)

**Comment by webmaster128** [comment]
@LightBender @randombit Can someone close this one please to keep issues list clean? Thanks!
