### ISSUE TITLE
Add FPE to python binding

### ISSUE THREAD

**Issue by joaonc** [randombit/botan#1612]
Or maybe this should be _Add FPE to [FFI (C89) Interface](https://botan.randombit.net/manual/ffi.html).

Maybe I'm not seeing it right, but I can't seem to find a way to use the [FPE_FE1](https://botan.randombit.net/manual/fpe.html) (Format Preserving Encryption) in Python. Don't see it declared in the [Python Binding](https://botan.randombit.net/manual/python.html) file included in the botan installation.

Is there a way to do it?

**Comment by randombit** [comment]
You are correct, currently FPE is not exposed in either C or Python APIs right now. Certainly doable, just requires writing the code. ;)

I would happily take a patch. Otherwise I will get to eventually, sometime between next month and next year as schedule permits.

**Comment by randombit** [comment]
#1625 adds FPE1 to the C API. However adding it to the Python API requires figuring out how we want to handle large integer types. Currently `botan_mp_t` is not exposed to Python and it's not so clear if it is worthwhile to do so, vs instead supporting a conversion from Python's `int` type.

We'll need some kind of `BigInt` / `int` conversion anyway for other purposes, it is not even possible to read an RSA public key's modulus from Python currently which is lame.

**Comment by randombit** [comment]
#1646 adds FPE to the Python wrapper. It will be available in a release when 2.8 comes out in early October or you can just pull latest master. Hope this helps!
