### ISSUE TITLE
Running the .exec file on another mac without installing , building the botan library

### ISSUE THREAD

**Issue by latifuluman** [randombit/botan#1623]
Firstly thanks for the usefull project. I have install the library to my Mac OSX Sierra. I build. It works on my mac. I want to run the .exec file on other macs. When I clikc the .exec file on another mac I encounteer with meaningless output since the botan is not installed in the target mac. **Is there any way to run the .exec file on another mac without installing the botan library to target mac.** (like including the related code pieces to .exec file)

**Comment by randombit** [comment]
I think all you need to do here is statically link `libbotan-2.a` into your final binary. The easiest way to do this is probably to just built Botan as static only using configure.py flag `--disable-shared-library`.

It may also be possible to ship the shared object side by side with your binary, but I don't know the details of how this would work on OSX.

**Comment by randombit** [comment]
@latifuluman Hopefully above resolved the question, feel free to open a new issue if you are having further problems.
