### ISSUE TITLE
Tests fail when CARCH != x86_64

### ISSUE THREAD

**Issue by tcely** [randombit/botan#1627]
For `x86_64` everything passed. The rest all failed with:

```
signature verification verification threw exception with error ECDSA_do_verify failed: error:10FFF06A:elliptic curve routines:CRYPTO_internal:point at infinity
```

The build logs showing the errors:
[botan-2.7.0-r0-aarch64.log.txt](https://github.com/randombit/botan/files/2202559/botan-2.7.0-r0-aarch64.log.txt)
[botan-2.7.0-r0-armhf.log.txt](https://github.com/randombit/botan/files/2202560/botan-2.7.0-r0-armhf.log.txt)
[botan-2.7.0-r0-ppc64le.log.txt](https://github.com/randombit/botan/files/2202561/botan-2.7.0-r0-ppc64le.log.txt)
[botan-2.7.0-r0-x86_64.log.txt](https://github.com/randombit/botan/files/2202562/botan-2.7.0-r0-x86_64.log.txt)
[botan-2.7.0-r0-x86.log.txt](https://github.com/randombit/botan/files/2202563/botan-2.7.0-r0-x86.log.txt)

**Comment by randombit** [comment]
Thanks. Can you please try the patch in #1628?

This error does not affect proper functionality except that it means certain interestingly malformed ECDSA signatures would be rejected by an exception instead of returning `false` from the signature verification routine.

**Comment by randombit** [comment]
FTR I was not able to replicate this on ppc64le with OpenSSL 1.0.2k

**Comment by tcely** [comment]
Not every architecture is finished at the moment, but the patch looks to be working so far.

**Comment by tcely** [comment]
All the builds finished and tests passed. Thanks again!
