### ISSUE TITLE
Prebuilt binaries in releases instead of a plain sources

### ISSUE THREAD

**Issue by Xottab-DUTY** [randombit/botan#1633]
We can configure CI to output artifacts you know..
Compiling takes too much time, that's why I'm asking about this. (Yes, ~5 minutes is too much)

It would be easier to integrate this lib, if we could use precompiled bins.

**Comment by randombit** [comment]
I would rather not be in the business of distributing binaries. Especially, I do not want to distribute binaries created by untrusted systems.

Virtually every major package manager or distro already has binaries available (https://github.com/randombit/botan/wiki/Distros) and most are good at following new releases. If the compile time is too large I would suggest using one of those.
