### ISSUE TITLE
Cannot invoke test_python.py

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1644]
MacOS 10.13.6, Xcode-9.4.1, Macports-installed python-3.6.6 and 2.7.15. Current Botan2 master.

Copied `src/python/botan2.py` and `src/scripts/test_python.py` to `~/Library/Python/site-packages/`. 
From Botan source directory:
```
$ python src/scripts/test_python.py 
Traceback (most recent call last):
  File "src/scripts/test_python.py", line 11, in <module>
    import botan2
ImportError: No module named botan2
$ python3 src/scripts/test_python.py 
Traceback (most recent call last):
  File "src/scripts/test_python.py", line 11, in <module>
    import botan2
ModuleNotFoundError: No module named 'botan2'
$ python3 ~/Library/Python/site-packages/test_python.py 
.............
----------------------------------------------------------------------
Ran 13 tests in 7.297s

OK
$ diff -u ~/Library/Python/site-packages/test_python.py src/scripts/test_python.py
$ cd src/scripts
$ python3 test_python.py 
Traceback (most recent call last):
  File "test_python.py", line 11, in <module>
    import botan2
ModuleNotFoundError: No module named 'botan2'
$ cd ../python/
$ python3 ../scripts/test_python.py 
Traceback (most recent call last):
  File "../scripts/test_python.py", line 11, in <module>
    import botan2
ModuleNotFoundError: No module named 'botan2'
$ 
```

Before this change, I was able to run `test_python.py` from anywhere, and it would run correctly. 

P.S. I personally liked better the original verbose behavior of `test_python.py` than the current terse "Ran 13 tests, OK". Is it possible to tell this script to be more verbose about what it's doing?

**Comment by randombit** [comment]
> Before this change, I was able to run test_python.py from anywhere, and it would run correctly.

I'm not really sure what has changed that would cause the difference since both just `import botan2`. Anyway you can use `PYTHONPATH`:

`$ PYTHONPATH=src/python python ./src/scripts/test_python.py`
...

> Is it possible to tell this script to be more verbose about what it's doing?

It is just using the Python `unittest` framework. It looks like there is a `--verbose` option but it is not particularly verbose, just lists the tests as they are executed. Seemingly no way to dump the value of the individual assertions.

**Comment by mouse07410** [comment]
> Anyway you can use `PYTHONPATH`

Yes that worked, thanks!
