### ISSUE TITLE
build botan win10/64 mingw-gcc python problem (make)

### ISSUE THREAD

**Issue by meir100** [randombit/botan#1645]
try to use this command: 
python configure.py --cc=gcc --os=mingw
after: botan --> user manual --> building the library: (on windows).

   INFO: configure.py invoked with options "--cc=gcc --os=mingw"
   INFO: Autodetected platform information: OS="Windows" machine="AMD64" proc="Intel64 Family 6 Model 23 Stepping 10, GenuineIntel"
   INFO: Guessing target processor is a x86_64 (use --cpu to set)
   INFO: Canonicalized CPU target AMD64 to x86_64
   INFO: Shared libs not supported on mingw, disabling shared lib support
   INFO: Auto-detected compiler version 8.1
   INFO: Auto-detected compiler arch x86_64
   INFO: Target is gcc:8.1-mingw-x86_64
   INFO: Skipping (dependency failure): certstor_sqlite3 sessions_sqlite3
   INFO: Skipping (incompatible CPU): aes_power8
   INFO: Skipping (incompatible OS): darwin_secrandom dev_random fd_unix getentropy proc_walk
   INFO: Skipping (incompatible compiler): aes_armv8 pmull sha1_armv8 sha2_32_armv8 sm4_armv8
   INFO: Skipping (no enabled compression schemes): compression
   INFO: Skipping (requires external dependency): bearssl boost bzip2 lzma openssl sqlite3 tpm zlib
WARNING: win32_stats: This module can cause false positives with antivirus systems
   INFO: Loading modules: adler32 aead aes aes_ni aes_ssse3 aont aria asn1 auto_rng base base32 base64 bcrypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac ccm cecpq1 certstor_sql cfb chacha chacha20poly1305 chacha_rng chacha_sse2 checksum clmul clmul_ssse3 cmac codec_filt comb4p cpuid crc24 crc32 cryptobox ctr curve25519 des dh dl_algo dl_group dlies dsa dyn_load eax ec_group ecc_key ecdh ecdsa ecgdsa ecies eckcdsa ed25519 elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy ffi filters fpe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_drbg hotp http_util idea idea_sse2 iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion locking_allocator mac mce mceies md4 md5 mdx_hash mem_pool mgf1 misty1 mode_pad modes mp newhope nist_keywrap noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pgp_s2k pk_pad pkcs11 poly1305 poly_dbl prf_tls prf_x942 psk_db pubkey rc4 rdrand rdrand_rng rdseed rfc3394 rfc6979 rmd160 rng rsa salsa20 scrypt seed serpent serpent_simd sessions_sql sha1 sha1_sse2 sha1_x86 sha2_32 sha2_32_bmi2 sha2_32_x86 sha2_64 sha3 shacal2 shacal2_simd shacal2_x86 shake shake_cipher simd siphash siv skein sm2 sm3 sm4 socket sp800_108 sp800_56a sp800_56c srp6 stateful_rng stream streebog system_rng thread_utils threefish_512 threefish_512_avx2 tiger tls tls_cbc tss twofish utils whirlpool win32_stats x509 x919_mac xmss xtea xts
   INFO: Defaulting to assuming little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
  ERROR: Error linking src\lib\asn1\alg_id.h into build\include\botan: symbolic link privilege not held

make command does not work, i get:

make.exe System Error
the code execution cannot proceed because libintl3.dll was
not found. reinstalling the program may fix this problem.

can the dev team change this "make" into something like:
mingw32-make -f  makefile.mingw

**Comment by randombit** [comment]
> ERROR: Error linking src\lib\asn1\alg_id.h into build\include\botan: symbolic link privilege not held

Thanks, we disable using symlinks on Windows by default but the logic did not kick in for MinGW or Cygwin targets. I'll fix this shortly. You can work around this with `--link-method=hardlink`.

> the code execution cannot proceed because libintl3.dll was not found. 

This sounds like some problem with your MinGW install and not something we can fix.
