### ISSUE TITLE
CMake missing .cmake file

### ISSUE THREAD

**Issue by pip010** [randombit/botan#1649]
I managed to config: ./configure.py -cc=msvc --os=windows --with-cmake
then build using cmake gui in out of source dir, however when I use on the client side find_package(botan) and point to the build folder : 

>   By not providing "FindBOTAN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "BOTAN", but
  CMake did not find one.

  

> Could
 not find a package configuration file provided by "BOTAN" with any of
  the following names:

    

> BOTANConfig.cmake

   

> 

 botan-config.cmake

 

> 

Add the installation prefix of "BOTAN" to CMAKE_PREFIX_PATH or set
  "BOTAN_DIR" to a directory containing one of the above files.  If "BOTAN"
  provides a separate development package or SDK, be sure it has been
  installed.

am I missing something?

**Comment by mikeloomisgg** [comment]
@pip010 find_package will only find targets that were exported during the installation, which Botan doesn't currently do.

As I suggested here: #1140, you need to provide a FindBOTAN.cmake file as that error warning suggests if you want to include this with find_package.

Here is a gist, I've only tested this on windows. https://gist.github.com/mikeloomisgg/0ecc7850d375abfbfe19535cf0e20c4b

**Comment by randombit** [comment]
Closing this as stale. If you are still having problems feel free to open a new issue. KeepassXC has some nice cmake helpers that may be useful as a reference.
https://github.com/keepassxreboot/keepassxc/tree/develop/cmake
