### ISSUE TITLE
Build opensource project in Visual studio 2010 using CMake

### ISSUE THREAD

**Issue by AmilaTK** [randombit/botan#1655]
I receved this 2 error messages while building a project using CMake 3.6.1.
CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
Could NOT find SDL2 (missing: SDL2_INCLUDE_DIRS SDL2_LIBS SDL2_DLLS)
Call Stack (most recent call first)
C:/Program Files/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
modules/FindSDL2.cmake:57 (find_package_handle_standard_args)
CMakeLists.txt:11 (find_package)

I would be very greatfull if anyone professional can give me some suggetion to reslove this issue

Thank you very much.

**Comment by randombit** [comment]
> Visual studio 2010

This almost certainly will not work. The earliest version of Visual Studio that Botan supports in 2013, and that is being dropped in a couple of releases (#1557). 2015 or 2017 is best.

Also, the errors you post seem entirely related to SDL are you sure this is a problem with Botan library?

**Comment by randombit** [comment]
Closing this as incative, @AmilaTK feel free to repoen if you are still having problems.
