### ISSUE TITLE
Testing on Debian : Missing data test files

### ISSUE THREAD

**Issue by devcompil** [randombit/botan#1661]
Compiling on debian is ok but botan-test is looking for files in src/test/* 

Example :
`...`
`Failure 1: Test error Could not open input file 'src/tests/data/x509_dn.vec`
`Failure 1: I/O error: DataSource: Failure opening file src/tests/data/x509/name_constraint/Root_Email_Name_Constraint.crt`
`Failure 1: I/O error: DataSource: Failure opening file src/tests/data/x509/misc/contains_utf8string.pem`

and so on.

Copying /my botan folder/src/tests/ in /my build folder/src/tests solves (manually) the problem.

**Comment by randombit** [comment]
This shouldn't happen. Can you explain what steps you took in the build up to the point you see the above errors?

**Comment by devcompil** [comment]
I wanted to build botan in a specific directory.
When I configured, the option --with-build-dir=<dir> the generated Makefile could not buid (no rule to build the target "src/lib/asn1/alg_id.cpp"). May be another issue but I did not go further for the moment.

So I decided to create my build folder and ran the configure script in it :
`$ cd build-folder`
`$ botan-folder/configure --prefix=<install folder> --cc=gcc --cpu=x86_64 --os=linux`

My build-folder contains the "build" sub-directory and the Makefile (only).
After building I ran the botan-test program.
When I copy the botan-folder-/src/tests/data in my <build folder> all tests passes :-)

**Comment by randombit** [comment]
Thank you now I understand. Your usage seems fine, I just tried it and it doesn't work for me either, something looks to be wrong with the build dir option. I will have a look at this soon.

`botan-test` has an option `--data-dir=` (defaults to `src/tests/data`) which you can use to direct the tests the data in the source release without having to make a copy.

**Comment by randombit** [comment]
Closing this - I think `--data-dir=` option covers it
