### ISSUE TITLE
Building on Windows with debug info selects wrong runtime

### ISSUE THREAD

**Issue by fschoenm** [randombit/botan#1683]
I noticed that the configure script seems to select the wrong MSVC runtime when building with debug info. My exact command line was ``configure.py --cpu=x86_64 --disable-shared --with-debug-info``. I wanted to build a static lib in release mode but still generate PDB symbol files. However, that leads to the compiler using the ``/MDd`` parameter instead of ``/MD``.

The configure script has the following part:

    if options.msvc_runtime is None:
        if with_debug_info:
            yield 'rt-debug'
        else:
            yield 'rt'

I'm not sure about the intention here. Shouldn't the check be for the ``--debug-mode`` parameter instead of the ``--with-debug-info`` parameter?

**Comment by randombit** [comment]
I am not sure, because I really don't know much about Windows development...

My assumption would have been, if you want debug info, you also want the debug runtime. Is this incorrect?

**Comment by randombit** [comment]
(BTW you can work around this with `--msvc-runtime=MD`)

**Comment by fschoenm** [comment]
> My assumption would have been, if you want debug info, you also want the debug runtime. Is this incorrect?

Those are different issues. If you do a release/optimized build you will have to use the release runtime (``/MD`` or ``/MT``), for a debug build you will have to use the debug runtime (``/MDd`` or ``/MTd``). If I understood it correctly, that's what the ``--debug-mode`` flag is for.

Debug info (PDB files for Visual C++) let's you e.g. see the call stack if you're debugging the code. That's useful for release builds too in some situations. Because in Visual C++, the symbols are not part of the object files but placed in separate files, there's no harm in always generating it.

(Right now I'm using the ``msvc-runtime`` work-around. I still think that the default behavior is wrong.)

**Comment by randombit** [comment]
I will take your word for it - changed in bc7e113
