### ISSUE TITLE
Clarification of the Botan::Credentials_Manager in the documentation

### ISSUE THREAD

**Issue by Daedronus** [randombit/botan#1686]
In the documentation for the TLS Clients here:
https://botan.randombit.net/manual/tls.html#tls-clients

It mentions that Client_Credentials in the function trusted_certificate_authorities returns a array like this:

return { new Botan::Certificate_Store_In_Memory("cas") };

this implies that someone else owns the certificate store and it will be freed at a later point, right?
Is this correct or the code would actually leak the memory if the code is written like this?

**Comment by randombit** [comment]
The docs are misleading here, any certificate stores returned are owned by the credentials manager and just returned by pointer for polymorphism purposes.

I will improve the docs.
