### ISSUE TITLE
Botan 1.10.17 - error: integer constant is too large for ‘long’ type

### ISSUE THREAD

**Issue by adnan-kamili** [randombit/botan#1688]
I created an amalgamated build on CentOS 5.11 using following command:

`./configure.py --cc=gcc --os=linux --cpu=x86_32 --no-autoload --gen-amalgamation --enable-modules=rsa,eme_pkcs,emsa3,emsa4,sha1,auto_rng,cbc,kdf2,asm_engine,pthreads,unix_procs,pbes2,sha2_32,des`

When I try to compile the code I get lot of errors of following type:

`error: integer constant is too large for ‘long’ type`

I checked the code, it contains some long integers at the lines where error is reported. How can I fix this issue?

**Comment by adnan-kamili** [comment]
Adding following flags during compilation fixed the issue:

`-Wno-long-long -fpermissive`

These are only required for gcc 4.1, what do these flags do? Is it safe to add them for gcc 4.7?

**Comment by randombit** [comment]
It is safe to use these flags for any gcc version.  In a non-amalgamation build, both flags you mention are used by default. I am not sure that `-fpermissive` is required here, I had thought that was only necessary for gcc 4.4 and below.

Be aware that 1.10 branch is rapidly approaching end of life, after end of this year no further patches will be applied.
