### ISSUE TITLE
Problem when ClientHello is retransmitted in DTLS

### ISSUE THREAD

**Issue by falko-strenzke** [randombit/botan#1691]
I think there is a problem with Botan's DTLS Server implementation: when the client runs into a receive timeout after having sent his (potentially fragmented) clientHello, then it will retransmit the clientHello. In this case, the Botan Server fails to create the initial handshake state. This is due to the check in tls_channel.cpp: Channel::process_handshake_ccs()

<pre>
  ...
   else if(record_sequence == 0)
            {
            create_handshake_state(record_version);
            }
   ...
</pre>

The retransmitted clientHello will have a record sequence other than 0. The retransmission of the clientHello message is treated in the same way as all the other messages. This is also necessary as it may be retransmitted with a different fragmentation.

I think the solution is simply to remove the check:

<pre>
  ...
   else
            {
            create_handshake_state(record_version);
            }
   ...
</pre>

**Comment by randombit** [comment]
Thanks I will look into this very soon.
