### ISSUE TITLE
ed25519 signature does not support RFC 8032 pre-hashed

### ISSUE THREAD

**Issue by andreihu** [randombit/botan#1699]
Hello everyone,

 I am trying to integrate botan into a networking server and use it to verify ed25519 signed udp messages (generated by rust's signatory crate). So far i have failed to validate signatures. I have taken some samples from RFC8032 (https://tools.ietf.org/html/rfc8032#section-7.1) and to my surprise this one was also not successful.

Here goes my test code:
```
#define CATCH_CONFIG_MAIN

// thirdparty
#include <catch.hpp>
#include <botan/ed25519.h>
#include <botan/pubkey.h>
#include <botan/auto_rng.h>
#include <botan/rng.h>
#include <cppcodec/hex_lower.hpp>

using namespace cppcodec;

// taken from rfc8032 test vectors: https://tools.ietf.org/html/rfc8032#section-7.1
TEST_CASE("ed25519", "[crypto]") {
    std::string secret_key = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
    std::string public_key = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";

    std::string message = "";
    std::string signature = "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b";

    // Botan::Ed25519_PrivateKey sk(hex_lower::decode(secret_key));
    Botan::Ed25519_PublicKey pk(hex_lower::decode(public_key));
    std::unique_ptr<Botan::RandomNumberGenerator> rng(new Botan::AutoSeeded_RNG);
    REQUIRE(pk.check_key(*rng, false));
    Botan::PK_Verifier verifier(pk, "SHA-512");

    REQUIRE(verifier.verify_message(hex_lower::decode(message), hex_lower::decode(signature)));
}
```

Can anyone help me finding out what am i doing wrong here?

Thanks
 Andras

**Comment by randombit** [comment]
With ``Botan::PK_Verifier verifier(pk, "SHA-512");`` you are asking for Ed25519 with SHA-512 pre-hashing, which is what RFC calls Ed25519ph. If you change "SHA-512" to "Pure", the signature verifies.

The downside of the "pure" version is the entire message must be kept in memory until the signature is generated, where prehashing allows O(1) memory for any message (at the cost of making the scheme vulnerable to hash collisions).

This should be better documented.

**Comment by andreihu** [comment]
Hi @randombit ,

Thanks for your answer. You're correct, changing the prehash to "Pure" fixed the test case, and this is also verifying the signatures emitted by signatory crate. Since we're processing udp packets, the memory requirement is not a problem for us, so thank to you our problems are solved.

However I have also created a test case for SHA-512 (ed25519ph), this is still not successful. I hope that i haven't made a copy-paste error. Here it is:
```
// taken from rfc8032 test vectors: https://tools.ietf.org/html/rfc8032#section-7.3
TEST_CASE("ed25519ph", "[crypto]") {
    // std::string secret_key = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
    std::string public_key = "ec172b93ad5e563bf4932c70e1245034c35467ef2efd4d64ebf819683467e2bf";

    std::string message = "616263";
    std::string signature = "98a70222f0b8121aa9d30f813d683f809e462b469c7ff87639499bb94e6dae4131f85042463c2a355a2003d062adf5aaa10b8c61e636062aaad11c2a26083406";

    // Botan::Ed25519_PrivateKey sk(hex_lower::decode(secret_key));
    Botan::Ed25519_PublicKey pk(hex_lower::decode(public_key));
    std::unique_ptr<Botan::RandomNumberGenerator> rng(new Botan::AutoSeeded_RNG);
    REQUIRE(pk.check_key(*rng, false));
    Botan::PK_Verifier verifier(pk, "SHA-512");

    REQUIRE(verifier.verify_message(hex_lower::decode(message), hex_lower::decode(signature)));
}
```

**Comment by randombit** [comment]
Outstanding. It appears Ed25519 as defined in RFC 8032 vs as defined for OpenPGP are not compatible. Since the Ed25519 code was written to support a PGP impl, it followed that interpretation. 8032 includes an additional context string into the hash input.

**Comment by randombit** [comment]
RFC 8032 variant implemented, need to document it
