### ISSUE TITLE
AES-XTS minimum_final_size() too large?

### ISSUE THREAD

**Issue by boricm** [randombit/botan#1706]
Hi everybody,

I noticed `XTS_Mode::minimum_final_size()` (botan/src/lib/modes/xts/xts.cpp) is one byte larger than the AES block size. As far as I understand the standard, the minimum size should be 128 bit, which equals the AES block size.
Any ideas on why minimum_final_size is one byte larger?

Source of documentation: 
[http://luca-giuzzi.unibs.it/corsi/Support/papers-cryptography/1619-2007-NIST-Submission.pdf](http://luca-giuzzi.unibs.it/corsi/Support/papers-cryptography/1619-2007-NIST-Submission.pdf)

Cheers,
Michael

**Comment by randombit** [comment]
I had thought XTS's ciphertext stealing required all inputs be at least 1 byte more than a full block. But it looks like the XTS test vectors from NIST include tests with 128-bit inputs so maybe I misinterpreted something.

**Comment by randombit** [comment]
You were correct, spec allows inputs to be just one block. Fixed in d5e4860, thank you for the report!

**Comment by boricm** [comment]
You're welcome! Thanks for the quick response!
