### ISSUE TITLE
SignatureHashAlgorithm Intolerance

### ISSUE THREAD

**Issue by ic0ns** [randombit/botan#1708]
Hey,
the newest Version of Botan (github/master) seems to be Intolerant to Unknown SignatureAndHash Algorithms. When you send an unknown SigHashAlgo to Botan it responds with a ServerHello, Certificate Alert[InternalError]:

>07:26:26 [main] INFO : SendAction - Sending messages (client): CLIENT_HELLO, 
>07:26:26 [main] INFO : ReceiveAction - Received Messages (client): SERVER_HELLO, CERTIFICATE, Alert(FATAL,INTERNAL_ERROR), 

In the console it prints 
>Connection problem: Unknown signature algorithm enum

If offered the following algorithms:
    DSA_MD5
    DSA_SHA1
    DSA_SHA224
    DSA_SHA256
    DSA_SHA384
    DSA_SHA512
    RSA_MD5
    RSA_SHA224
    RSA_SHA256
    RSA_SHA384
    RSA_SHA512
    ECDSA_MD5
    ECDSA_SHA1
    ECDSA_SHA224
    ECDSA_SHA256
    ECDSA_SHA384
    ECDSA_SHA512
    GOSTR34102001_GOSTR3411
    GOSTR34102012_256_GOSTR34112012_256
    GOSTR34102012_512_GOSTR34112012_512

Once i only send common ones it works. I am not completely sure, but i think this is related to the SHA224 ones.

I left everything in its default configuration and used the provided botan tls_server
This behavior can be triggered with the TLS-Attacker Client in the default configuration.
Best Regards
Robert

**Comment by randombit** [comment]
Ouch, thank you. I also see this using OpenSSL 1.1.1. I have a patch that resolves things, PR coming shortly.

**Comment by randombit** [comment]
Fixed now in #1709 and there is a test to make sure this problem does not recur. Thank you very much for the report.
