### ISSUE TITLE
Add a unittesting framework

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#171]
While Botans test suit serves relatively well for vector based data in files, it is incredible hard to use for just adding a test for a tiny low-level function.

When we open up development, we need to make sure that people are able to easily add tests for what they are working on. There needs to be a framework where everyone finds the right spot to just add one or two lines a la

> EXPECT_THAT(myfunction(myinput), EQUALS(myoutput))

I myself am developing a testing suite outside of Botan that tests
* base64 encoding / decoding which was broken for 0-length input
* `Botan::EAC_Time` because I introduces stream based string formatting
* `Botan::X509_Time` because I introduces stream based string formatting
* `to_string(secure_vector<byte>)` which I need for #170 

All those tests would be a pain in the ass to add to the Botan test suite.

During my work for 1.11.18 I found that the Botan test suite is very hard to maintain. A lot of stuff needs to be done manually, which is covered by any testing framework out of the box:
* Test reports have been missing
* Test counts and fails need to be counted manually
* Tests need to be registered manually and the test functions need to be present even if a test is skipped

A testing framework would fix all that an has major advantages:
* Readable test code
* Test benchmarking and timeouts

Given that Botan 2.0 should have a test coverage well over 90 % before release, we need to push that.

We are using Google Test / Google Mock at Kullo which serves as very well. But there might be similar alternatives. I know that the folks in this project are very careful with external dependencies but in this case I think the value is incredibly high.

**Comment by neusdan** [comment]
I've made some good experience with "Catch": https://github.com/philsquared/Catch
Its lightweight and header only. There is also a single header version. Here are some of the main features summarized: https://github.com/philsquared/Catch/blob/master/docs/why-catch.md

It would be nice if the test framework provide support for test cases with randomized inputs. This is missing in Catch as far as i know.

**Comment by webmaster128** [comment]
Wow, this is a huge hint! I never heard of catch but headers-only a superb plus for Botan where no linking module system like cmake is provided.

With headers-only one can integrate catch tests into the existing botan test suite by just adding catch as a submodule and defining some BOTAN_HAS_CATCH constant. So it can be integrated smoothly and iteratively without ever breaking the current build commands.

> It would be nice if the test framework provide support for test cases with randomized inputs. This is missing in Catch as far as i know.

Of which use case are you exactly thinking of. In general unitests should avoid non-deterministic behaviour because a failing test that is not reproducible is hard to debug.

**Comment by neusdan** [comment]
The tests with randomized input don't have to be part of the normal unit tests. They could be part of a extra fuzzing test suite.

**Comment by webmaster128** [comment]
Okay one could think of that. But still I have no idea what exactly you are trying to test with random input and why that makes sense.

**Comment by neusdan** [comment]
The simplest case is to check if the test / the application crashs. This can be extended further to activate ubsan and asan / valgrind to do some dynamic analysis.

**Comment by webmaster128** [comment]
Dude, I am really loving this. Catch covers everything I need so far and the one-file approach is very handy to integrate: #179

**Comment by randombit** [comment]
I agree the test suite as is is not sufficient for general testing of the sort that is needed. However I'm not particularly convinced on any of the options available. Catch being header only is a plus compared to the alternatives, and its design seems somewhat sane especially compared to Boost.Test which I found overly complicated. I'm not convinced that the extra complexity of capturing the expression values via template programming is worth it, compared to having explicit TEST_EQUAL TEST_LT etc macros. But if Catch proves a problem in practice, likely it could be swapped out easily with a simple replacement that perhaps doesn't colorize the screen or so on, and until then it would provide a framework for rewriting the tests to use this style which would be a big improvement.

A fuzzing framework for the library APIs would be an excellent addition and could be built on top of catch. Right now basic fuzzing is used in a few places (PK encryption and signatures) but should be extended to many different areas.

Fuzzing could also be done with a framework to support afl (http://lcamtuf.coredump.cx/afl/) which just wants to feed single flat files in as quickly as possible, which could be done with an addition to the command line tool.

**Comment by webmaster128** [comment]
> I'm not convinced that the extra complexity of capturing the expression values via template programming is worth it

Are you talking about Catch or Boost.Test here? I don't know how the Catch macros are implemented but is that important for us as a user of a testing framework?

> compared to having explicit TEST_EQUAL TEST_LT etc macros

Having no special macros for different test expressions is a great improvement for readability, because you can read the test from left to right in a very natural human fashion. Compare for example there Google Test lines:

```
EXPECT_GT(vec.size(), 0);
EXPECT_THAT(vec.size(), Gt(0));
```

The first one reads *expect greater than vector size two* while the second one reads *expect that vector size is greater than 0*.

The following example might look overly complicated at the first look, makes a great consistent readable test

```
EXPECT_TRUE(myFunction());
EXPECT_THAT(myFunction(), EQ(true));
```

A test is read 1000 times more often than it is written and a testing framework should allow us to express our intent in the same way we think.

This test readability works well with the `CHECK()` macro of Catch right now and matchers like `CHECK_THAT(myFunction(), EQ(true));` are in development.

>  it could be swapped out easily with a simple replacement that perhaps doesn't colorize the screen or so on

Don't you like colours? I am sure we can turn them of easily. If not, we can write a custom reporter that does the output. There are already 4 reporters includes so it will be easy to come up with the desired output format.

I have no experience or opinion for that fuzzing framework.

**Comment by webmaster128** [comment]
Output is now smaller and colour-free: https://travis-ci.org/randombit/botan/jobs/70305067 #179. Catch's colours really did not add value here in the bigger build context.

**Comment by randombit** [comment]
Sorry I did not mean specifically a problem with colors, more that Catch seemed like a very large header with a lot of features and it was not clear at a quick glance this morning what benefit it provided and if it was worth the complexity of importing. Your argument on readability is well taken and having looked at Catch further I do see the advantage as compared to standard assert macros, so I retract my concerns. Also, feel free to turn the colors back on if you prefer.

**Comment by webmaster128** [comment]
I just accidentally merged my not yet perfect PR on Catch tests :/ I guess this is the kind of thing that happens to you one in a lifetime: Change PR title and confirm using the "Merge" button ...

Anyway, I could revert that now but I think it does not harm. Catch already delivers a great amount of value and integrates well with the existing Botan infrastructure. I am going to need it one way or another for #185 and more to come.

If anything is not clear, I am always happy for code review comments on master as well as PRs.
