### ISSUE TITLE
Generate CSR using crypto token

### ISSUE THREAD

**Issue by PouriaN** [randombit/botan#1713]
Hello
I want to create CSR using crypto token(pkcs#11)
Do you implement a solution to accomplish this task?

**Comment by randombit** [comment]
I don't think there is an example of this. But, `PKCS10_Request::create` take a `Private_Key` reference, which may be of any type, such as a `PKCS11_RSA_PrivateKey` which was created on a card. The individual steps (creating a key on a PKCS11 token, and creating a CSR using some arbitrary key) should be documented.

**Comment by randombit** [comment]
There is no specific example of this. But `PKCS10_Request::create` takes an arbitrary `Private_Key` which could be eg `PKCS11_RSA_PrivateKey`. The two steps of creating a key on a token, and creating a CSR from some arbitrary private key, should be already documented.

**Comment by PouriaN** [comment]
Thank you for invaluable guidance

**Comment by randombit** [comment]
Closing this as it seems the question was addressed but if you have further questions or issues feel free to open a new issue.
