### ISSUE TITLE
Build issue in botan - 2.7.0

### ISSUE THREAD

**Issue by Abinayasandhiya** [randombit/botan#1721]
Hello,

We are trying to build botan - 2.7.0 on RedHat 7 machine as per the building steps of botan README.
Facing below issue:

``g++ -fPIC -fvisibility=hidden -fstack-protector -m64 -pthread -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -msha -mssse3 -Ibuild/include -Ibuild/include/external -c src/lib/block/shacal2/shacal2_x86/shacal2_x86.cpp -o build/obj/lib/block_shacal2_x86.o
/tmp/ccI2EANu.s: Assembler messages:
/tmp/ccI2EANu.s:46: Error: no such instruction: `sha256rnds2 %xmm0,%xmm4,%xmm3'
/tmp/ccI2EANu.s:48: Error: no such instruction: `sha256rnds2 %xmm0,%xmm1,%xmm2'
/tmp/ccI2EANu.s:53: Error: no such instruction: `sha256rnds2 %xmm0,%xmm3,%xmm4'
/tmp/ccI2EANu.s:54: Error: no such instruction: `sha256rnds2 %xmm0,%xmm2,%xmm1'
/tmp/ccI2EANu.s:57: Error: no such instruction: `sha256rnds2 %xmm0,%xmm4,%xmm3'
/tmp/ccI2EANu.s:58: Error: no such instruction: `sha256rnds2 %xmm0,%xmm1,%xmm2'
/tmp/ccI2EANu.s:62: Error: no such instruction: `sha256rnds2 %xmm0,%xmm3,%xmm4'
/tmp/ccI2EANu.s:63: Error: no such instruction: `sha256rnds2 %xmm0,%xmm2,%xmm1'
/tmp/ccI2EANu.s:111: Error: no such instruction: `sha256rnds2 %xmm0,%xmm1,%xmm2'
/tmp/ccI2EANu.s:117: Error: no such instruction: `sha256rnds2 %xmm0,%xmm2,%xmm1'
/tmp/ccI2EANu.s:120: Error: no such instruction: `sha256rnds2 %xmm0,%xmm1,%xmm2'
/tmp/ccI2EANu.s:122: Error: no such instruction: `sha256rnds2 %xmm0,%xmm2,%xmm1'
make: *** [build/obj/lib/block_shacal2_x86.o] Error 1
``

Please find our server details:

``[root@abi-qtcreator-test Botan-2.7.0]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@abi-qtcreator-test Botan-2.7.0]$ gcc --version
gcc (GCC) 6.3.1 20161221
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@abi-qtcreator-test Botan-2.7.0]$ clang --version
clang version 7.0.0 (tags/RELEASE_700/rc3)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/x86_64/7.0.0.g631a/bin
``

Can anyone help us to fix this issue.

**Comment by randombit** [comment]
Same as #1718 gcc is recent enough but the binutils is too old so instructions are not recognized. Try adding `configure.py` flags `--disable-sha --disable-avx2`

I'll work on a more satisfactory solution which probably involves either sniffing the binutils version or a configure time check to make sure code using the intrinsics can be compiled.

**Comment by randombit** [comment]
I do not have time to work on a configure-time check for the intrinsics working so for now I am just documenting the issue so someone who runs into it has a hint about what to do.

I am closing this issue but feel free to open a new issue if you have further problems with building after using the above mentioned flags.
