### ISSUE TITLE
FFI Incremental decoding failed in ffi

### ISSUE THREAD

**Issue by chux0519** [randombit/botan#1723]
In GCM mode, update_granularity is equal to tag_size, causing incremental decoding to fail in ffi.

see [ffi_cipher.cpp#L163](https://github.com/randombit/botan/blob/master/src/lib/ffi/ffi_cipher.cpp#L163)

**Comment by randombit** [comment]
Thanks - there is supposed to be a test to check for this but it looks like it is checking for it being greater than or equal to, which is not sufficient.

(Really the code in FFI should be rewritten to avoid this limitation, I don't think it is intrinsic to the interface, but one thing at a time)

**Comment by randombit** [comment]
Fixed in #1724 and test fixed in 6c0b880
