### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by Tymolc** [randombit/botan#1725]
https://botan.randombit.net/manual/credentials_manager.html# seems to be outdated. The return value of `trusted_certificate_authorities(const std::string &type, const std::string &context)` is `std::vector<Certificate_Store*>` and not `std::vector<X509_Certificate>`

**Comment by randombit** [comment]
Thank you for bringing this to my attention. Some of these docs have not been updated in a couple of years and still reflect APIs as they initially were in the development versions. I'll do a pass over the cred manager and TLS docs when I have a chance.
