### ISSUE TITLE
Working on an asio::ssl::stream<> replacement based on botan's TLS

### ISSUE THREAD

**Issue by reneme** [randombit/botan#1731]
We are actively developing a client application that mainly communicates via HTTP and already uses botan for several cryptographic tasks. Now, we would like to replace its networking layer (currently WinHTTP and SChannel) with an open source implementation.

For a socket abstraction we are planning to use boost::asio. To avoid the addition of OpenSSL as a second crypto library we are looking into a replacement for asio's `ssl::stream<>` based on botan. Its not yet clear whether this will be a compatible drop-in replacement but we would take `asio::ssl::stream<>` as a guide line.

To the best of our knowledge to date there is no such implementation available as open source. Since some (optional) functionality in botan is already based on ASIO: Would you be interested in accepting such an ssl stream implementation as a contribution to the library?

**Comment by randombit** [comment]
Keep in mind also it is perfectly possible to use the existing TLS API with asio, see for example https://github.com/randombit/botan/blob/master/src/cli/tls_proxy.cpp and https://github.com/randombit/botan/blob/master/src/cli/tls_http_server.cpp

That said an explicit asio integration would probably be useful to others and yes I would accept a PR for this. This could be packaged in a sub-module of tls.

Style thing I'll mention from the outset, in my install of Boost the asio SSL support is spread out over 27 headers which to me seems really excessive especially as most are under 200 LOC. Something like say 3-5 headers seems more reasonable to me here.

I'm going to be unavailable quite a bit in the next few weeks but if you have any questions about direction or how to do something feel free to ask here.

**Comment by ChrisBFX** [comment]
@reneme  I've worked on exactly the same thing last week. It's still pretty much work in progress but the basic functionality is done. You can check it out here: https://github.com/krumedia/asio-botan-stream
Would be great if you can provide some kind of feedback if this would be useful for you, or if don't like the architecture at all.

**Comment by reneme** [comment]
Thanks for your reply @ChrisBFX. Indeed your implementation seems to be on a good track and might serve as a basis for what we have in mind as well. Are you planning to develop this to become production ready?

**Comment by Tymolc** [comment]
We opened PR #1839 to implement this feature.

**Comment by reneme** [comment]
Since this is merged and integrated into our application, I take the liberty to close this.
Thanks a lot to all contributors. :)

**Comment by pedro-vicente** [comment]
Is there a version for asio standalone (non boost) ?
and if not , would it be possible to change the current botan source to use the standalone asio ?

https://think-async.com/Asio/

**Comment by hrantzsch** [comment]
> Is there a version for asio standalone (non boost) ?
> and if not , is it doable to modify the botan source above to use the standalone asio ?
> 
> https://think-async.com/Asio/
> 
> 
> 

No, this would be a bit difficult unfortunately. We require other parts of boost system, namely beast, as well.
