### ISSUE TITLE
When using library-suffix import library still links to botan.dll

### ISSUE THREAD

**Issue by Eelke76** [randombit/botan#1739]
As the botan release builds are not compatible with debug builds (atleast when using Visual Studio 2017) I like to fix this using two builds with different filenames. I used `--library-suffix=d` for the debug build. The build generated the files with correct names. botand.dll and botand.lib being the important ones for me. However when I link my debug build to botand.lib it still loads botan.dll (which is my release build) and thus crashes.

I discoverd that the botan-cli.exe of my debug build does load the botand.dll. So maybe it is something in how the linker is called. My own project is being build using QMake.

**Comment by randombit** [comment]
I'm not sure why this would occur. I don't even have a Windows machine anymore so it is not so easy for me to reproduce or diagnose.

**Comment by Eelke76** [comment]
Sorry I screwed something up with all the tests I did. Had some old versions of the libs in different sub folders and it was somehow picking up one of those. Working fine now.

**Comment by randombit** [comment]
BTW I should mention for anyone who find this issue in the future

> As the botan release builds are not compatible with debug builds (atleast when using Visual Studio 2017)

This is purely an issue of how MSVC does multiple runtimes (release vs debug) which are incompatible with each other. With any other compiler, a debug build of the library is ABI compatible with a release build. I believe you can actually create a debug build of the library with the release runtime and it will work, but apparently this breaks the debugger so is not a particularly helpful thing to do.
