### ISSUE TITLE
Test RSA Encryption failing occasionally on OS X

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#174]
This is not the first time I see the RSA Encryption failing on OSX.
- 2015-06-29 Kullo CI (I ran the test 10 times but could not reproduce): https://ci.kullo.net:8154/go/pipelines/using-botan/208/test-botan/1
- ~~2015-07-08 Travis OS X (static lib): https://travis-ci.org/randombit/botan/builds/69974147~~
- 2015-07-12 Kullo CI OS X 10.10: https://gist.github.com/webmaster128/e0286f9dee4f2a433960
- ~~2015-07-15 Travis OS X (shared lib): https://travis-ci.org/randombit/botan/jobs/70995185~~

**Comment by mouse07410** [comment]
On Jul 7, 2015, at 18:44 , Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:

This is not the first time I see the RSA Encryption failing on OSX.

  *   2015-06-29 Kullo CI (I ran the test 10 times but could not reproduce): https://ci.kullo.net:8154/go/pipelines/using-botan/208/test-botan/1
  *   2015-07-08 Travix OS X: https://travis-ci.org/randombit/botan/builds/69974147

Not sure what this problem is or how it manifests itself - but I’ve been building Botan on OS X with the latest (whatever version happens to be at the time) Xcode clang (currently Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)), and all the RSA-related tests consistently passed.
--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by webmaster128** [comment]
How much data do you have? This failure is very rare, maybe 1 out of 100 or 1 out of 1000. I'll keep observing.

**Comment by mouse07410** [comment]
Hmm... 1:100, perhaps... 1:1000 - certainly not... Looks like we need a special test...? And I might have a good platform to run it on...

Sent from my iPad

On Jul 8, 2015, at 01:57, Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


How much data do you have? This failure is very rare, maybe 1 out of 100 or 1 out of 1000. I'll keep observing.

**Comment by webmaster128** [comment]
Added a new fail to the list with a bit more information.

> test 23 failed: False assertion 'RSA decrypt consistency check' (expression m == m_powermod_e_n(x)) in raw_decrypt @src/lib/pubkey/rsa/rsa.cpp:157

> RSA Encryption 123 tests 1 FAILs

**Comment by mouse07410** [comment]
So the blinding appears to be screwed?

On Jul 12, 2015, at 7:46 , Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


Added a new fail to the list with a bit more information.

test 23 failed: False assertion 'RSA decrypt consistency check' (expression m == m_powermod_e_n(x)) in raw_decrypt @src/lib/pubkey/rsa/rsa.cpp:157

RSA Encryption 123 tests 1 FAILs

—
Reply to this email directly or view it on GitHub<https://github.com/randombit/botan/issues/174#issuecomment-120711024>.

--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by webmaster128** [comment]
I have no clue what this is about and I am not an expert in this field, so I am not really confident to debug it.

**Comment by randombit** [comment]
That does suggest a computational error. Maybe blinding, maybe a bug in the modexp or etc. Interesting that this is only? seen on OS X. Is the common element here Apple's Clang? A more extended RSA soak test that dumped all the relevant values in the case of an inconsistency would help in reproing this.

The segmentation fault in https://travis-ci.org/randombit/botan/jobs/70995185 looks to be a distinct issue.

**Comment by webmaster128** [comment]
Added a different ticket for the segfault issue: #255. The `RSA decrypt consistency check` is still an issue here

**Comment by randombit** [comment]
I believe 9aa2b72 will fix the consistency check error, but want to wait for a while before declaring it resolved since it's possible that more than one bug could trigger such an error.
