### ISSUE TITLE
Request: switch order of "tests" and "docs" 

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1746]
Could you please switch the order in which components are built in the generated Makefile?

From 
```
all: libs cli docs tests
```
to
```
all: libs cli tests docs
```

Thanks!

**Comment by randombit** [comment]
Explain reasoning please.

**Comment by mouse07410** [comment]
I'm struggling with document processing on the new machine. But I managed to get the build working, so would like to be able the tests to run automatically, and succeed or fail *before* it gets to building documentation.

I realize that one can configure the build to simply disable documentation, but there doesn't seem to be an advantage in the current order of things - if the tests do not pass, do you really need the documentation how to use the library?

I also realize that the reasoning is not super-convincing - but the change isn't huge either, and shouldn't impact anything...?

**Comment by randombit** [comment]
> so would like to be able the tests to run automatically, and succeed or fail before it gets to building documentation.

Tests do not run out of `test` target, that just builds the binary.

Still seems harmless enough change.
