### ISSUE TITLE
[question] Trigger botan build with or without googleunittest

### ISSUE THREAD

**Issue by 4u4us** [randombit/botan#1748]
Currently default build contains googleunittest, am I right? 
If yes, then I would like to add a new switch, e.g. --without-gtest, in configure.py and install.py to trigger a build not containing googleunittest. I suppose an extra makefile template, e.g makefile_with_gtest.in, would be needed in build-data folder. Switching between makefile.in and makefile_with_gtest.in would happen in configure.py. And switching for copying the googleunittest executable would be in install.py .

thanks!

**Comment by randombit** [comment]
> Currently default build contains googleunittest, am I right?

No, the tests are written using a framework specific to the library, which can be found in https://github.com/randombit/botan/blob/master/src/tests/tests.cpp. Gtest is a fine unit test framework but insufficient for our purposes, we would still have ended up writing 90% of what we have now to supply the missing pieces, so it was easier to write 100% of it and avoid the dependency.

However, if we did use Gtest, then the changes you propose are exactly the steps one would take to resolve the issue.
