### ISSUE TITLE
Getting unresolved external symbol error

### ISSUE THREAD

**Issue by doctor-yes** [randombit/botan#1760]
I'm using Botan 2.7.0 Amalgamation and Qt 5.11.2 (MSVC 2015, 32 bit) + Creator 4.7.2, and I'm getting these unresolved external symbol errors in one project but another project seems to have no problem... I was using MinGW on these projects and trying to switch to MSVC, I used this to setup the configure. What am I missing? Thanks.

python ./configure.py --cc=msvc --cpu=x86 --minimized-build --single-amalgamation-file --amalgamation --enable-modules=rsa,auto_rng,sha1,emsa1,hmac,win32_stats

Unresolved external symbol errors:

botan_all.obj:-1: error: LNK2019: unresolved external symbol __imp__GetMessagePos@0 referenced in function "public: virtual unsigned int __thiscall Botan::Win32_EntropySource::poll(class Botan::RandomNumberGenerator &)" (?poll@Win32_EntropySource@Botan@@UAEIAAVRandomNumberGenerator@2@@Z)

botan_all.obj:-1: error: LNK2019: unresolved external symbol __imp__GetMessageTime@0 referenced in function "public: virtual unsigned int __thiscall Botan::Win32_EntropySource::poll(class Botan::RandomNumberGenerator &)" (?poll@Win32_EntropySource@Botan@@UAEIAAVRandomNumberGenerator@2@@Z)

botan_all.obj:-1: error: LNK2019: unresolved external symbol __imp__GetInputState@0 referenced in function "public: virtual unsigned int __thiscall Botan::Win32_EntropySource::poll(class Botan::RandomNumberGenerator &)" (?poll@Win32_EntropySource@Botan@@UAEIAAVRandomNumberGenerator@2@@Z)

botan_all.obj:-1: error: LNK2019: unresolved external symbol __imp__GetCursorPos@4 referenced in function "public: virtual unsigned int __thiscall Botan::Win32_EntropySource::poll(class Botan::RandomNumberGenerator &)" (?poll@Win32_EntropySource@Botan@@UAEIAAVRandomNumberGenerator@2@@Z)

botan_all.obj:-1: error: LNK2019: unresolved external symbol __imp__GetCaretPos@4 referenced in function "public: virtual unsigned int __thiscall Botan::Win32_EntropySource::poll(class Botan::RandomNumberGenerator &)" (?poll@Win32_EntropySource@Botan@@UAEIAAVRandomNumberGenerator@2@@Z)

**Comment by randombit** [comment]
Are you sure you are linking to `user32.lib`? Those APIs are defined there.

**Comment by randombit** [comment]
Weird. Does the ordering of libs match in the two projects? Like does botan come before user32 in the one that works, and after in the one that fails? I cannot remember if Windows linker cares about this, but Unix linkers do.

**Comment by doctor-yes** [comment]
Hmmm, I redo the project by copying the non-working project files into a working one, and now it is working... Weird... But thanks a lot for the help.

**Comment by randombit** [comment]
Build problems :shrug:

It sounds like you are all set now so I am closing this.
