### ISSUE TITLE
Problem on build qtcreator 4.7.2

### ISSUE THREAD

**Issue by zoro0312** [randombit/botan#1763]
INFO: /home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py invoked with options "--cc=gcc --cc-bin=g++ --amalgamation --minimized-build --disable-shared --enable-modules=aes,aes_ssse3,auto_rng,bigint,block,cbc,ctr,des,dh,dsa,ec_group,ecdh,ecdsa,entropy,filters,hmac,mode_pad,pubkey,rsa,sha1,sha1_sse2,sha1_x86,sha2_32,sha2_32_x86,sha2_64,simd,system_rng,emsa_pkcs1,pbes2,pbkdf2 --without-documentation --cxxflags=-pipe -Wno-noexcept-type -Wno-unused-parameter -fPIC"
   INFO: Autodetected platform information: OS="Linux" machine="aarch64" proc="aarch64"
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing target processor is a arm64 (use --cpu to set)
   INFO: Canonicalized CPU target aarch64 to arm64
   INFO: Auto-detected compiler version 5.4
   INFO: Auto-detected compiler arch arm64
   INFO: Target is gcc:5.4-linux-arm64
   INFO: Skipping (incompatible CPU): aes_ni aes_power8 aes_ssse3 rdrand_rng rdseed sha1_sse2 sha1_x86 sha2_32_bmi2 sha2_32_x86
   INFO: Skipping (incompatible OS): darwin_secrandom getentropy win32_stats
   INFO: Skipping (not requested): aes_armv8 dev_random dyn_load proc_walk rdrand sha1_armv8 sha2_32_armv8 x509
   INFO: Loading modules: aes asn1 auto_rng base base64 bigint block cbc cpuid ctr des dh dl_algo dl_group dsa ec_group ecc_key ecdh ecdsa emsa1 emsa_pkcs1 emsa_pssr entropy filters hash hash_id hex hmac hmac_drbg kdf keypair mac mdx_hash mgf1 mode_pad modes mp numbertheory pbes2 pbkdf pbkdf2 pem pk_pad pubkey rng rsa sha1 sha2_32 sha2_64 simd stateful_rng stream system_rng utils
   INFO: Defaulting to assuming little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
  ERROR: Traceback (most recent call last):
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 3160, in <module>
    sys.exit(main(argv=sys.argv))
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 3154, in main
    do_io_for_build(cc, arch, osinfo, using_mods, build_paths, source_paths, template_vars, options)
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 3013, in do_io_for_build
    (amalg_cpp_files, amalg_headers) = AmalgamationGenerator(build_paths, using_mods, options).generate()
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 2584, in generate
    amalgamation_headers, included_in_headers = self._generate_headers()
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 2504, in _generate_headers
    pub_header_amalag = AmalgamationHeader(self._build_paths.public_headers)
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 2364, in __init__
    contents = AmalgamationGenerator.strip_header_goop(filepath, raw_content)
  File "/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/configure.py", line 2459, in strip_header_goop
    raise InternalError("No header guard end found in " + header_name)
InternalError: No header guard end found in /home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/src/libs/botan/../3rdparty/botan/src/lib/asn1/alg_id.h

An internal error occurred.

Don't panic, this is probably not your fault!

Please report the entire output at https://github.com/randombit/botan or email
to the mailing list https://lists.randombit.net/mailman/listinfo/botan-devel

You'll meet friendly people happy to help!
Makefile:475: recipe for target 'build/Makefile' failed
make[3]: *** [build/Makefile] Error 1
make[3]: Leaving directory '/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/build/src/libs/botan'
Makefile:59: recipe for target 'sub-botan-make_first' failed
make[2]: *** [sub-botan-make_first] Error 2
make[2]: Leaving directory '/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/build/src/libs'
Makefile:313: recipe for target 'sub-libs-make_first-ordered' failed
make[1]: *** [sub-libs-make_first-ordered] Error 2
make[1]: Leaving directory '/home/nvidia/Documents/qtcreator/qt-creator-opensource-src-4.7.2/build/src'
Makefile:46: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2

I' am trying to build qtcreator on my dev board, but I'v got this problem, does anyone can help?

**Comment by randombit** [comment]
I'm guessing based on the fact that BMI2 SHA-256 is listed but AVX2 ChaCha is not that this is version 2.7. This is a very strange error (which I can not replicate with stock 2.7) as it seems to indicate `src/lib/asn1/alg_id.h` has no line matching `#endif\n`. Perhaps Qt Creator shipped some modified source. Can you look at that file and see what the last lines are?

Unrelated, but you probably want to enable the modules using ARMv8 crypto extensions (`aes_armv8`, `sha1_armv8`, `sha2_32_armv8`)

**Comment by revast** [comment]
I also have a porblem, with build qtcreator 4.7.2 debian package sources  from debian unstable on ubuntu 18.04:
```
g++ -c -pipe -Wno-noexcept-type -g -O2 -fdebug-prefix-map=/media/vault/compiles/qtcreator/qtcreator-4.7.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++1y -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DQTCSSH_LIBRARY -D'RELATIVE_PLUGIN_PATH="../lib/x86_64-linux-gnu/qtcreator/plugins"' -D'RELATIVE_LIBEXEC_PATH="../lib/x86_64-linux-gnu/qtcreator/libexec"' -D'RELATIVE_DATA_PATH="../share/qtcreator"' -D'RELATIVE_DOC_PATH="../share/qtcreator/doc"' -DIDE_LIBRARY_BASENAME=\"lib/x86_64-linux-gnu\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_DISABLE_DEPRECATED_BEFORE=0x050600 -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I../../../src -I/media/vault/compiles/qtcreator/qtcreator-4.7.2/src -I/media/vault/compiles/qtcreator/qtcreator-4.7.2/src/libs -I/media/vault/compiles/qtcreator/qtcreator-4.7.2/tools -I/media/vault/compiles/qtcreator/qtcreator-4.7.2/src/plugins -I/media/vault/compiles/qtcreator/qtcreator-4.7.2/src/libs -isystem /usr/include/botan-2 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc/release-shared -isystem /usr/include/libdrm -I.uic -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o .obj/release-shared/sshkeygenerator.o /media/vault/compiles/qtcreator/qtcreator-4.7.2/src/libs/ssh/sshkeygenerator.cpp
/media/vault/compiles/qtcreator/qtcreator-4.7.2/src/libs/ssh/sshkeygenerator.cpp: In member function ‘void QSsh::SshKeyGenerator::generateOpenSslPublicKeyString(const KeyPtr&)’:
/media/vault/compiles/qtcreator/qtcreator-4.7.2/src/libs/ssh/sshkeygenerator.cpp:159:55: error: ‘const class Botan::PointGFp’ has no member named ‘encode’
         q = convertByteArray(ecdsaKey->public_point().encode(PointGFp::UNCOMPRESSED));
                                                       ^~~~~~

```

**Comment by randombit** [comment]
@revast I think your problem is different. `PointGFp::encode` was added in version 2.5.0, but Ubuntu 18.04 ships with 2.4.0. You can probably use the 2.6 package from cosmic.

**Comment by revast** [comment]
ok thanks! I have now tried to build 4.8 from source, which worked!

**Comment by SergeyBalbir** [comment]
It seems to be a line ending issue. Can happens when building files on Linux that were edited on Windows.
LF ending is expected when CR LF is the actual ending in the file. (Happened to me when building using Windows docker). Ugly fix possible: _header_guard_pattern = re.compile('^#define BOTAN_.*_H_[ \t\n\r\f\v]$') and line == '#endif[ \t\n\r\f\v]' in cunfigure.py

**Comment by randombit** [comment]
@SergeyBalbir Converting a file to DOS line endings I can reproduce the issue, thank you.

Interestingly it seems to only affect Python2; Python3 behaves correctly.
