### ISSUE TITLE
Need test-cases for Botan-2.8.0

### ISSUE THREAD

**Issue by vvijayan28** [randombit/botan#1785]
Hi, I am new to Botan. I compiled the latest version Botan by using https://botan.randombit.net/manual/building.html# link.

Now I don't know how to check the Botan functionality. Kindly add some sample scripts or commands for verification.

Thanks.

**Comment by randombit** [comment]
Run `botan-test` to execute the test suite.

**Comment by vvijayan28** [comment]
I didn't get botan-test binary in root filesystem. So I am unable to confirm the Botan functionality. Let me if there is any test-cases or simple c file to test some Cryptography functionality.

**Comment by vvijayan28** [comment]
Ok Fine.  I copied build source and checked botan-test thanks.
