### ISSUE TITLE
MSVC C4250 Inheritance via dominance warning

### ISSUE THREAD

**Issue by mikeloomisgg** [randombit/botan#1786]
MSVC gives warnings while linking to the botan library.

```
C:\botan\include\botan-2\botan/ecc_key.h(168): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::estimated_strength' via dominance
C:\botan\include\botan-2\botan/ecc_key.h(108): note: see declaration of 'Botan::EC_PublicKey::estimated_strength'
C:\botan\include\botan-2\botan/ecc_key.h(168): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::key_length' via dominance
C:\botan\include\botan-2\botan/ecc_key.h(107): note: see declaration of 'Botan::EC_PublicKey::key_length'
C:\botan\include\botan-2\botan/ecc_key.h(168): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::check_key' via dominance
C:\botan\include\botan-2\botan/ecc_key.h(63): note: see declaration of 'Botan::EC_PublicKey::check_key'
C:\botan\include\botan-2\botan/ecc_key.h(168): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::algorithm_identifier' via dominance
C:\botan\include\botan-2\botan/ecc_key.h(59): note: see declaration of 'Botan::EC_PublicKey::algorithm_identifier'
C:\botan\include\botan-2\botan/ecc_key.h(168): warning C4250: 'Botan::EC_PrivateKey': inherits 'Botan::EC_PublicKey::Botan::EC_PublicKey::public_key_bits' via dominance
C:\botan\include\botan-2\botan/ecc_key.h(61): note: see declaration of 'Botan::EC_PublicKey::public_key_bits'
C:\botan\include\botan-2\botan/ecdsa.h(94): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::algo_name' via dominance
C:\botan\include\botan-2\botan/ecdsa.h(46): note: see declaration of 'Botan::ECDSA_PublicKey::algo_name'
C:\botan\include\botan-2\botan/ecdsa.h(94): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::message_parts' via dominance
C:\botan\include\botan-2\botan/ecdsa.h(48): note: see declaration of 'Botan::ECDSA_PublicKey::message_parts'
C:\botan\include\botan-2\botan/ecdsa.h(94): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::message_part_size' via dominance
C:\botan\include\botan-2\botan/ecdsa.h(50): note: see declaration of 'Botan::ECDSA_PublicKey::message_part_size'
C:\botan\include\botan-2\botan/ecdsa.h(94): warning C4250: 'Botan::ECDSA_PrivateKey': inherits 'Botan::ECDSA_PublicKey::Botan::ECDSA_PublicKey::create_verification_op' via dominance
C:\botan\include\botan-2\botan/ecdsa.h(54): note: see declaration of 'Botan::ECDSA_PublicKey::create_verification_op'
```

Info from botan/build.h:
```C++
/*
* This file was automatically generated running
* 'configure.py --disable-shared-library --without-documentation --debug-mode'
*
* Target
*  - Compiler: cl /MDd /bigobj /EHs /GR /D_ENABLE_EXTENDED_ALIGNED_STORAGE /Zi /FS
*  - Arch: x86_64
*  - OS: windows
*/

#define BOTAN_VERSION_MAJOR 2
#define BOTAN_VERSION_MINOR 8
#define BOTAN_VERSION_PATCH 0
```

These warnings could be silenced. Could use pragma or suppress the warning entirely with an MSVC compiler flag `/wd4250`.

**Comment by randombit** [comment]
Currently this warning is silenced when building the library. It has never been clear to me what this warning is actually supposed to accomplish. It is just telling you what happens, when you use a virtual base (use of which is certainly a design problem, in retrospect, but sadly not one we can do much about now without breaking a lot of code).

It is very unfortunate that it warns when application code compiles. Having noisy headers is not a good attribute in a library. That said I am not inclined to disable any warnings (from any compiler) via pragmas in headers. The user enabled the warning, the code in the header triggers the warning, therefore the user should see the warning.

But, perhaps there is some way we can change the code that removes the warning. This is hinted in https://stackoverflow.com/questions/6864550/c-inheritance-via-dominance-warning, though the suggested solution (adding `using base::method` decls) is said to either not work or behave buggily in MSVC. However that discussion occurred in 2011 and as of now the earliest MSVC we support is 2015, so maybe things have changed.

Can you try editing a header to add a few such `using` declarations and see if it helps?

**Comment by mikeloomisgg** [comment]
You raise good points, I can't imagine a scenario where someone is harmed by suppressing this warning in particular but like you point out it's a little *evil* to do.

I tried `using` declarations but that didn't change the warnings.

There are no more warnings by explicitly defining the functions to call the base methods, but that is an incredible amount of cruft to add to the library.
```C++
Class EC_PrivateKey : public virtual EC_PublicKey, public virtual Private_Key {
[...]

// No more inheritance via dominance warning
size_t estimated_strength() const override { 
    return EC_PublicKey::estimated_strength();
};
}
```


Another alternative is to target code with the warning suppression. Less code but feels even more like environmental pollution.
```C++
#pragma warning( push )
#pragma warning( disable : 4250)
[Class declaration]
#pragma warning( pop )
```

As a cmake target I just export the `/wd4250` flag only for the environment where this warning exists.

**Comment by reneme** [comment]
I believe this issue was recently addressed in: https://github.com/randombit/botan/pull/3462
