### ISSUE TITLE
Building arm64 for iPhone

### ISSUE THREAD

**Issue by ne0h** [randombit/botan#180]
Hi,

i'm trying to build botan-1.11.18 for arm64 iPhone:

`./configure.py --cpu=armv7 --cc=clang --cc-bin="clang++ -stdlib=libc++ -arch armv7 -arch armv7s -arch arm64 -mios-version-min=7.0 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/" --with-bzip2 --disable-ssse3 --disable-avx2 --disable-altivec --disable-sse2 --disable-modules=rdrand,clmul`

When i'm running `make` i get this error:

````➜  Botan-1.11.18  make
clang++ -stdlib=libc++ -arch armv7 -arch armv7s -arch arm64 -mios-version-min=7.0 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/ -pthread -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -c ./src/lib/asn1/alg_id.cpp -o build/obj/lib/asn1_alg_id.o
clang++ -stdlib=libc++ -arch armv7 -arch armv7s -arch arm64 -mios-version-min=7.0 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/ -pthread -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -c ./src/lib/asn1/asn1_alt_name.cpp -o build/obj/lib/asn1_alt_name.o
In file included from ./src/lib/asn1/asn1_alt_name.cpp:16:
In file included from build/include/botan/loadstor.h:13:
build/include/botan/bswap.h:58:11: error: unknown register name 'r3' in asm
        : "r3", "cc");
          ^
1 error generated.
make: *** [build/obj/lib/asn1_alt_name.o] Error 1````

**Comment by webmaster128** [comment]
Interesting. `build/include/botan/bswap.h:58` is code that should only be used if `BOTAN_USE_GCC_INLINE_ASM` and `BOTAN_TARGET_CPU_IS_ARM_FAMILY` is defined. The second one makes sense, but the first one doesn't since you don't use GCC, do you?

Can you add the output of `clang++ --version`?

**Comment by ne0h** [comment]
Thanks for your quick answer!

The output is:
`➜  Botan-1.11.18  clang++ --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix`

**Comment by ne0h** [comment]
Should it normally work?

**Comment by webmaster128** [comment]
Well that is the goal, yes. But I don't know how many applicatins use Botan on iOS.

Can you attach your build configuration file `build.h` from `build/include/botan/build.h` (use gist or pastebin, please)

**Comment by ne0h** [comment]
Sure:

https://gist.github.com/ne0h/de072c4c9657bc97f6af

**Comment by randombit** [comment]
It is possible the inline asm is wrong for 64-bit ARM, or it is ok for GCC with 64-bit but not Clang. I probably never tested with Clang on an ARM, and I've also never tested on 64-bit ARM.

The specific exclusion of ARM was due to a performance issue I observed with an older version of GCC (4.3 or 4.4, probably?) as described in the comment. It is perhaps no longer an issue with recent GCCs.

BOTAN_GCC_VERSION is also defined under Clang as it keys of __GNUC__ which Clang defines. That is desired here since both compilers support bswap builtins.

**Comment by ne0h** [comment]
Did you ever built botan for iPhones with arm64 successfully?

**Comment by randombit** [comment]
I have never built botan for iOS, but I have received reports of successful compilation and use. I don't think any of those were for 64-bit though.

The simple fix to get you going is to use __builtin_bswap instead, removing the  `&& !defined(BOTAN_TARGET_CPU_IS_ARM_FAMILY)` at the start of reverse_bytes function in bswap.h.

Likely the inline asm version needs to be used only on 32-bit ARM

**Comment by ne0h** [comment]
Cool, thank you, this compiles!
I'm going to open a new issue if we have further problems.

**Comment by ne0h** [comment]
I have updated botan to version 1.11.29 and tried again to build the lib for arm64 (iPhone), but there is still the same error as mentioned above.
Am I missing something obvious?

Thanks in advance!

**Comment by webmaster128** [comment]
Did you check the updates iOS build instructions?

https://github.com/randombit/botan/blob/master/doc/manual/building.rst#for-ios-using-xcode

Please add your exact updates build commands and error messages here to make debugging possible.

**Comment by ne0h** [comment]
No, i'm sorry! Works perfectly now :)
