### ISSUE TITLE
Cipher_Mode core on exit

### ISSUE THREAD

**Issue by MacroKnow** [randombit/botan#1806]
Hi:
I just put the Local variables to global ,it core when exit. why?

botan version:2.8.0，x86_64 ,CentOS Linux release 7.2.1511, gcc version 7.2.0

// code like
#include <botan/cipher_mode.h>
#include <botan/hex.h>
#include <iostream>
#include <unistd.h>

std::unique_ptr<Botan::Cipher_Mode> enc;
int main() {
    const std::string plaintext("1234");
    const std::string key2 = "2B7E151628AED2A6ABF7158809CF4F3C";
    Botan::SymmetricKey skey(key2);
    enc = Botan::Cipher_Mode::create("AES-128/CBC/PKCS7", Botan::ENCRYPTION);
    enc->set_key(skey);
    Botan::secure_vector<uint8_t> iv; 
    for(int i =0; i<16; i++) {
        iv.emplace_back('0');
    }   
    Botan::secure_vector<uint8_t> pt(plaintext.data(), plaintext.data()+plaintext.length());
    enc->start(iv); 
    enc->finish(pt);
    return 0;
}

**Comment by randombit** [comment]
Likely due to the mlock'ed pool, see #761 

If you need static objects you must disable the mlock pool either at build time with `--disable-modules=locking_allocator` or at runtime by setting env variable `BOTAN_MLOCK_POOL_SIZE` to 0.

**Comment by randombit** [comment]
Would like to address the crash but closing this as dup of #761
