### ISSUE TITLE
Error compiling botan_all.cpp

### ISSUE THREAD

**Issue by jimcruse** [randombit/botan#1809]
I was trying to compile botan all on raspberry pi, and got a fault about trying to inline function:
See attached file
declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor  -Ibuild/include -Ibuild/include/external -c botan_all.cpp -o build/obj/lib/botan_all.oIn file included from botan_all_internal.h:4919:0,                 from botan_all.cpp:9:/usr/lib/gcc/arm-linux-gnueabihf/6/include/arm_neon.h: In constructor â Botan::SIMD_4x32::SIMD_4x32(uint32_t, uint32_t, uint32_t, uint32_t)â : /usr/lib/gcc/arm-linux-gnueabihf/6/include/arm_neon.h:9035:1: error: inlining failed in call to always_inline â uint32x4_t vld1q_u32(const uint32_t*)â :  target specific option mismatch vld1q_u32 (const uint32_t * __a) ^~~~~~~~~In file included from botan_all.cpp:9:0:botan_all_internal.h:4997:28: note: called from here          m_neon = vld1q_u32(B);                   ~~~~~~~~~^~~Makefile:92: recipe for target 'build/obj/lib/botan_all.o' failed

**Comment by jimcruse** [comment]
If you want more details , please emAil me crusejim@gmail.com, I can email the err file

**Comment by jimcruse** [comment]
If you want more details , please emAil me crusejim@gmail.com, I can email the err file

**Comment by randombit** [comment]
Sorry for the delay. I think the short answer here is that ARMv6 doesn't support NEON, you would need to pass `--disable-neon` to turn that off.
