### ISSUE TITLE
combine_relnotes is missing

### ISSUE THREAD

**Issue by cdesjardins** [randombit/botan#181]
When I use the following commands I get an error:

    $ ./configure.py --disable-shared --disable-modules=tls --prefix=/home/chrisd/sw/repo/install --libdir=/home/chrisd/sw/repo/install/lib/botan/Release --build-mode=release --via-amalgamation --disable-avx2 --maintainer-mode
    $ make install

The error produced from the make install is:

    cp ./doc/manual/*.rst build/docs/manual
    ./src/scripts/install.py --destdir=/home/chrisd/sw/repo/install --build-dir="build" --bindir=bin --libdir=/home/chrisd/sw/repo/install/lib/botan/Release --docdir=share/doc --includedir=include
    Traceback (most recent call last):
      File "./src/scripts/install.py", line 22, in <module>
        import combine_relnotes
    ImportError: No module named combine_relnotes
    make: *** [install] Error 1

I suspect that this file was not added to the repo...

**Comment by randombit** [comment]
Actually combine_relnotes was removed from the repo, as now the release notes are just kept as a single file. But CI is not testing the install process and clearly I didn't test it either.

**Comment by webmaster128** [comment]
I think `make install` can easily be added to the CI as soon as #183 is in.
