### ISSUE TITLE
exception handling?

### ISSUE THREAD

**Issue by larry-l** [randombit/botan#1813]
Hello Folks:

   I'm trying to understand Botan exception handling.  

   Using Botan 2.8.0.  

   The first test is to see how Botan reacts when a key fails due to an EAX check.  

   An exception is thrown.  The exception's what() function returns a string containing this text:

      "Integrity failure: EAX tag check failed"

   In general, how does the application know the cause of an exception?  

   In particular, how does the application know if an EAX check fialed?  

   Do I check that the text the exception's what()  function returns is an exact match to "Integrity failure: EAX tag check failed"?  

   Will the text associated with that exception be consistent for different versions of Botan?  

   Is there a list of messages associated with other exceptions?

   Or is there an entirely different mechanism an application can use to determine what caused an exception to be thrown?

      Thanks
      Larry

**Comment by randombit** [comment]
> Will the text associated with that exception be consistent for different versions of Botan?

In general you should assume the exact text of exception messages may change from release to release; they are not part of our semantic versioning guarantee.

The way to detect this situation is instead by catching objects of `Botan::Integrity_Failure&` which is the subclass of `Botan::Exception` which is thrown when an AEAD tag check fails.

**Comment by larry-l** [comment]
Thanks:

   The Integrity_Failure is caught with the following information when I introduce an invalid decryption passphrase.  

    failure.error_type(); returns 107, the enumerator for DecodingFailure.  

    failure.error_code() returns 0.  

    As described above, failure.what() returns the text "Integrity failure: EAX tag check failed".  

   Does an error type of DecodingFailure and an error code of 0 unambiguously tell my application that the decryption failed because of an EAX tag check failure?

   I appreciate your assistance.

      Larry

**Comment by randombit** [comment]
> Does an error type of DecodingFailure and an error code of 0 unambiguously tell my application that the decryption failed because of an EAX tag check failure?

No it does not. In fact this could occur in several other contexts where some problem occurs with decoding data. The enum should be the (currently not existing) `InvalidTag` or something like this. This was an oversight when I added `error_type` in 2.9.0

Best solution is to explicitly `catch(Botan::Integrity_Failure&)` which will be unambiguous.
