### ISSUE TITLE
Libraryinitializer?

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#182]
I'm really confused now, because the documentation seems out of sync with the recent builds. 
For example there used to be a LibararyInitializer that was required to be created before using the library.  (version 1.10.9).  Now the documentation online 

http://botan.randombit.net/manual/firststep.html

still mentions this as a requirement.  However when I am using version 1.11.17  botan.h header file no longer includes the initi.h header which contain the definition for LibraryInitializer. 
Therefore Botan::LibraryInitializer is no longer found .

here is the difference
Version 1.10.9
```
/*
* A vague catch all include file for Botan
* (C) 1999-2007 Jack Lloyd
*
* Distributed under the terms of the Botan license
*/

#ifndef BOTAN_BOTAN_H__
#define BOTAN_BOTAN_H__

#include <botan/init.h>
#include <botan/lookup.h>
#include <botan/libstate.h>
#include <botan/version.h>
#include <botan/parsing.h>

#include <botan/rng.h>

#if defined(BOTAN_HAS_AUTO_SEEDING_RNG)
  #include <botan/auto_rng.h>
#endif

#endif
```

Version 1.11.17

```
/*
* A vague catch all include file for Botan
* (C) 1999-2007 Jack Lloyd
*
* Botan is released under the Simplified BSD License (see license.txt)
*/

#ifndef BOTAN_BOTAN_H__
#define BOTAN_BOTAN_H__

#include <botan/lookup.h>
#include <botan/version.h>
#include <botan/parsing.h>

#include <botan/rng.h>

#if defined(BOTAN_HAS_AUTO_SEEDING_RNG)
  #include <botan/auto_rng.h>
#endif

#endif
```

Can someone please help me get started.  All I want to use is the simple format preserving module, but this is turning into more work since each version you release seems to break something.

**Comment by randombit** [comment]
The include of `init.h` should be added back to `botan.h`, but in both 1.10 and 1.11 simply including `<botan/init.h>` in your code would provide the initializer class.

The manual is definitely out of date in a lot of areas, especially with regards to any changes in 1.11

**Comment by erotavlas** [comment]
If I'm starting fresh using version 1.11.17 do I even need to use the LibraryInitializer?  In the class definition it says 
/*
* Previously botan had state whose lifetime had to be explicitly
* managed by the application. As of 1.11.14 this is no longer the
* case, and this class is no longer needed and kept only for backwards
* compatability.
*/

**Comment by webmaster128** [comment]
At the moment it does nothing, so you can skip it for now. Make sure to read read changelog notes, in case that might change back.
