### ISSUE TITLE
Failed build 

### ISSUE THREAD

**Issue by jimcruse** [randombit/botan#1824]
I have whole log I can send , email any questions - crusejim@gmail.com
Error:
g++ -fstack-protector -pthread -std=c++11 -D_REENTRANT -O3 -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor  -Ibuild/include -Ibuild/include/external -c src/tests/test_c25519.cpp -o build/obj/test/test_c25519.o
In file included from /opt/gcc-8.2.0/include/c++/8.2.0/vector:69,
                 from build/include/botan/mem_ops.h:13,
                 from build/include/botan/secmem.h:12,
                 from build/include/botan/rng.h:11,
                 from src/tests/tests.h:12,
                 from src/tests/test_asn1.cpp:7:
/opt/gcc-8.2.0/include/c++/8.2.0/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {Botan_Tests::Test::Result}; _Tp = Botan_Tests::Test::Result; _Alloc = std::allocator<Botan_Tests::Test::Result>]’:
/opt/gcc-8.2.0/include/c++/8.2.0/bits/vector.tcc:413:7: note: parameter passing for argument of type ‘std::vector<Botan_Tests::Test::Result>::iterator’ {aka ‘__gnu_cxx::__normal_iterator<Botan_Tests::Test::Result*, std::vector<Botan_Tests::Test::Result> >’} changed in GCC 7.1
       vector<_Tp, _Alloc>::

**Comment by jimcruse** [comment]
I was using gcc-8.2.0

**Comment by randombit** [comment]
There is no error in the log snippet you gave. The warning is an ABI issue with GCC which we can do nothing about, but is harmless as long as all of the code is compiled by the same version of GCC. Discussed in #1589

**Comment by randombit** [comment]
@jimcruse I'm closing this since there seems to be nothing actionable here, just a warning from GCC that other versions of GCC had a bug. If there is a problem with the build beyond that feel free to reopen and include the relevant error.
