### ISSUE TITLE
Building static lib on Windows does not create PDB (debug symbols)

### ISSUE THREAD

**Issue by fschoenm** [randombit/botan#1831]
When building Botan as a static library with Visual C++ on Windows, there seems to be no way to get a PDB file containing the debug symbols. I'm using the following configure command line: ``python configure.py --cpu=x64 --disable-shared --with-debug-info --debug-mode``

There are PDB files created for botan-cli.exe and botan-test.exe but not for the library itself.

The debug symbols for EXE files are generated automatically by the linker but as far as I know, you would need to specify the ``/Fd`` parameter (with a PDB file name) for the compile calls on the library's source files to get debug symbols for a static library.

I would test that but I'm not really sure how to integrate a compiler parameter for only the library build steps.

**Comment by randombit** [comment]
Would we be better of using /Z7 when building a static library?

**Comment by fschoenm** [comment]
I've never used /Z7. I think it's a very old format to store symbols inside the binary while PDBs are the modern way to store debug information. Also, /Z7 has some limitations regarding compilation features though I don't know any details from the top of my head. 

Do you have a way to specify special parameters only for building the library and not the executables?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by randombit** [comment]
OK good to know re Z7 the MSVC docs are not clear about the difference.

> Do you have a way to specify special parameters only for building the library and not the executables?

Not precisely, but we can use the same logic as used for shared lib flags (-fPIC etc). I can write a patch for this tonight. In the meantime you can hack it with `nmake SO_OBJ_FLAGS=/Fd...` (at least assuming nmake allows overriding env variables on the command line, not sure, otherwise you could edit the makefile)

IIRC the reason the botan command line util is `botan-cli` on Windows is to work around the problem where the PDB for libbotan and the botan exe stomped on each other. So if we use this flag then we are able to rename the cli back to match the other platforms.

Maybe relevant? #432 makes it sound like the flag to use is /PDB not /Fd

**Comment by fschoenm** [comment]
I think #432 only refers to building a DLL. On Windows, shared libraries/DLLs (like executables) are built by the linker (link.exe) while static libraries are created by the library manager (lib.exe). link.exe has a parameter /PDB to set the output file for the debug information but lib.exe does not. So when building a static library, I think you have to use the /Fd parameter to create the debug information during compilation of the object files.

I hope it's possible to reflect that in your build tool.

**Comment by randombit** [comment]
I just pushed ad1896f0 which may or may not fix the issue. I have no way to test.

**Comment by fschoenm** [comment]
Thank you. I'll try it probably tomorrow when I'm back at work. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fschoenm** [comment]
I tried your commit and it seems to works in general with the following two issues:

1. Regarding ``debug -> "/Fd botan-symbols.pdb"`` in msvc.txt: There must be no space after /Fd and I would recommend naming the PDB file like the library: ``debug -> "/Fdbotan.pdb"`` (or is it possible to use the library's name here if it includes e.g. a suffix?).

2. The setting ignores the build directory (specified by --with-build-dir) and puts the PDB file just in the local directory. I don't know if there is some variable for the build directory that can be used in the msvc.txt.

**Comment by randombit** [comment]
I believe this is fixed now with 01dc31d please test and reopen if there are still problems.
