### ISSUE TITLE
loading a PKCS8-encoded RSA private key from a file (DataSource_Stream)

### ISSUE THREAD

**Issue by jbo3** [randombit/botan#1837]
I'm updating from botan 1.10.9 to 2.9.0 and one of my unit test fails. It seems loading a PKCS8-encoded RSA private key from a file fails. The code below demonstrates the problem. It generates a private key, saves it into file "private.key" and reloads it either from memory (works) or from the file (fails). It throws  "PKCS 8 private key decoding failed with BER: Value truncated".
```
int main(int argc, char **argv) {
    const std::string password = "joe";

    // generate key
    Botan::AutoSeeded_RNG rng;
    const size_t length = 1024;
    Botan::RSA_PrivateKey private_key(rng, length);
    const std::vector<uint8_t> key=Botan::PKCS8::BER_encode(private_key, rng, password);

    const std::string filename("private.key");
    // save to file.
    {
        std::ofstream ofile(filename, std::ios::out | std::ofstream::binary);
        std::copy(key.begin(), key.end(), std::ostreambuf_iterator<char>(ofile));
    }

    std::cout << "loading the key from memory.. ";
    {
        Botan::DataSource_Memory m(key);
        std::unique_ptr<Botan::Private_Key> private_key(Botan::PKCS8::load_key(m, rng, password));
    }
    std::cout << "ok\n";

    std::cout << "loading the key from file.. ";
    {
        Botan::DataSource_Stream in(filename);
        std::unique_ptr<Botan::Private_Key> private_key(Botan::PKCS8::load_key(in, rng, password));
    }
    std::cout << "ok\n";
}
```
The output:
```
$ ./issue.exe
loading the key from memory.. ok
loading the key from file.. PKCS #8 private key decoding failed with BER: Value truncated
```
OS: Windows 7
compiler: mingw gcc version 4.9.2

**Comment by randombit** [comment]
My guess would be `DataSource_Stream` defaults to reading using text input but you are writing binary data, so the data becomes corrupted. However I'm not sure how this would have worked in 1.10 either as the code for binary vs text seems to predate 1.10 by several years. In any case try initializing your `DataSource_Stream` with `(filename, true)` to request binary mode.

**Comment by jbo3** [comment]
`DataSource_Stream(filename, true)` fixes the problem. Thanks!
