### ISSUE TITLE
botan\secmem.h(86): error C2589: '(': illegal token on right side of '::'

### ISSUE THREAD

**Issue by larry-l** [randombit/botan#1852]
Developing on Windows 10 Pro, Visual Studio 2017 Community, C++.

Botan Version 2.9.  

I've built a simple application to understand version 2.x.  

My build goes well and the application works when everything associated with Botan is in the main module.  

If I add a static lib with nothing more than the following in it's source:

For some reason I can't display the includes with the quotes and angle brackets:

#include stdafx.h
#include Windows.h
#include iostream
#include string
#include vector
#include botan\symkey.h

two errors are generated when building that simple stub of a static library:

...\botan-2\botan\secmem.h(86): error C2589: '(': illegal token on right side of '::'
...\botan-2\botan\secmem.h(100): error C2589: '(': illegal token on right side of '::'

In the Librarian section of the static library's property pages Additional Dependencies specifies botan.lib and Additional Library Directories points to the directory that contains botan.lib.  

These are copy and pasted from the corresponding entries in the main modules for linker properties.  

These errors relate to the following lines in secmem.h:

template<typename T, typename Alloc>
size_t buffer_insert(std::vector<T, Alloc>& buf,
                     size_t buf_offset,
                     const T input[],
                     size_t input_length)
   {
   BOTAN_ASSERT_NOMSG(buf_offset <= buf.size());
   const size_t to_copy = std::min(input_length, buf.size() - buf_offset);  **<==========**
   if(to_copy > 0)
      {
      copy_mem(&buf[buf_offset], input, to_copy);
      }
   return to_copy;
   }

template<typename T, typename Alloc, typename Alloc2>
size_t buffer_insert(std::vector<T, Alloc>& buf,
                     size_t buf_offset,
                     const std::vector<T, Alloc2>& input)
   {
   BOTAN_ASSERT_NOMSG(buf_offset <= buf.size());
   const size_t to_copy = std::min(input.size(), buf.size() - buf_offset);  **<==========**
   if(to_copy > 0)
      {
      copy_mem(&buf[buf_offset], input.data(), to_copy);
      }
   return to_copy;
   }

What am I forgetting?

   Thanks
   Larry

**Comment by randombit** [comment]
This is almost certainly due to windows.h defining macros `min` and `max` which interferes with using the functions of the same name in C++. `#define NOMINMAX` before including windows.h to prevent this.

**Comment by larry-l** [comment]
Thanks, that almost did it.  

It didn't work at first, then I dropped the "1" and simply defined **NOMINMAX** in one of my property sheets, which I will use for any future builds of any applications that use STL.  

This NOMINMAX stuff bites me every once in a while.  This should fix it for good.  

I wouldn't have fixed this without your help.

**Comment by randombit** [comment]
Glad that did the trick

**Comment by JomaCorpFX** [comment]
Thanks. Simple spell but effective.
