### ISSUE TITLE
Fail to compile.

### ISSUE THREAD

**Issue by ghelmergh** [randombit/botan#1859]
code:

#include <botan/block_cipher.h>
#include <botan/hex.h>
#include <iostream>
int main ()
   {
   std::vector<uint8_t> key = Botan::hex_decode("000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F");
   std::vector<uint8_t> block = Botan::hex_decode("00112233445566778899AABBCCDDEEFF");
   std::unique_ptr<Botan::BlockCipher> cipher(Botan::BlockCipher::create("AES-256"));
   cipher->set_key(key);
   cipher->encrypt(block);
   std::cout << std::endl <<cipher->name() << "single block encrypt: " << Botan::hex_encode(block);

   //clear cipher for 2nd encryption with other key
   cipher->clear();
   key = Botan::hex_decode("1337133713371337133713371337133713371337133713371337133713371337");
   cipher->set_key(key);
   cipher->encrypt(block);

   std::cout << std::endl << cipher->name() << "single block encrypt: " << Botan::hex_encode(block);
   return 0;
   }
terminal : 
g++ -I/usr/include/botan-2/include/botan-2/ -Wall -o botann botan.cpp

errors: 

/tmp/ccWURgdm.o: In function `main':
botan.cpp:(.text+0x55): undefined reference to `Botan::hex_decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
botan.cpp:(.text+0xab): undefined reference to `Botan::hex_decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
botan.cpp:(.text+0x129): undefined reference to `Botan::BlockCipher::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
botan.cpp:(.text+0x2a4): undefined reference to `Botan::hex_decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/tmp/ccWURgdm.o: In function `void Botan::SymmetricAlgorithm::set_key<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&)':
botan.cpp:(.text._ZN5Botan18SymmetricAlgorithm7set_keyISaIhEEEvRKSt6vectorIhT_E[_ZN5Botan18SymmetricAlgorithm7set_keyISaIhEEEvRKSt6vectorIhT_E]+0x3d): undefined reference to `Botan::SymmetricAlgorithm::set_key(unsigned char const*, unsigned long)'
/tmp/ccWURgdm.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Botan::hex_encode<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool)':
botan.cpp:(.text._ZN5Botan10hex_encodeISaIhEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIhT_Eb[_ZN5Botan10hex_encodeISaIhEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIhT_Eb]+0x56): undefined reference to `Botan::hex_encode[abi:cxx11](unsigned char const*, unsigned long, bool)'
collect2: error: ld returned 1 exit status

**Comment by randombit** [comment]
You are not linking to the library, try `-lbotan2`. You may also need `-L` option if the library is not in the normal search path.

**Comment by ghelmergh** [comment]
terminal:
g++ -L/usr/include/botan-2/lib/ -I/usr/include/botan-2/include/botan-2/ -Wall -o botann botan.cpp -lbotan-2

It didnt fail this time but when I try to run the executable I get the following error message:
./botann: error while loading shared libraries: libbotan-2.so.10: cannot open shared object file: No such file or directory

Is that error related with environment variables?

**Comment by ghelmergh** [comment]
Update:
After a lot of google searching I found the best way to compile my program.

terminal:
g++ -L/usr/include/botan-2/lib -I/usr/include/botan-2/include/botan-2/  -Wl,-rpath=/usr/include/botan-2/lib/ -Wall -o botann botan.cpp -lbotan-2

**Comment by randombit** [comment]
It seems pretty weird the libs would be installed in `/usr/include/botan-2/lib` did you build the library and configure with something like `--prefix=/usr/include/botan-2`? Also fwiw almost all Linux distributions include a recent version of the library so you can just install the version from your package manager.

Anyway seems resolved so closing.
