### ISSUE TITLE
New GOSTs 2012

### ISSUE THREAD

**Issue by LumaRay** [randombit/botan#1860]
Hello! Any plans for GOST 34.11-2012 (hashing) and GOST 34.10-2012 (signing)?
These standards are mandatory in Russia since 01-01-2019.

**Comment by randombit** [comment]
GOST 34.11-2012 (aka Streebog hash) is already implemented.

GOST 34.10-2012, I am not sure what needs to change. My read of https://tools.ietf.org/html/rfc7091 is that the actual signature algorithm is the same as GOST 34.10-2001 except that now 512-bit curves are allowed. So maybe we just need to add whatever the official 512-bit curve is (assuming there is one?) and some more tests.

**Comment by LumaRay** [comment]
Well if so then probably you could mention this support in the description.

**Comment by randombit** [comment]
I checked and the test vector in RFC 7091 matches the same test in the GOST 34.10-2001 spec so I think everything is all set, besides needing to track down the official GOST 512-bit curve.

**Comment by mouse07410** [comment]
@LumaRay Does Russian standard mandate Grasshopper (Kuznechik) symmetric encryption algorithm yet?

**Comment by LumaRay** [comment]
Well actually I don't have deep knowledge in cryptography, I just research ways to use GOST signatures within my NodeJS software, especially by PKSC#11 interface when working with HSMs. So I stumbled upon this library which I like and decided to ask about new GOST support.
So as not a pro in cryptography, I thought you might have some articles about that difference in English. 
If not... I can tell that in an Russian article in Wikipedia ( https://ru.wikipedia.org/wiki/%D0%93%D0%9E%D0%A1%D0%A2_%D0%A0_34.10-2012 ) they have a section: "Отличия от ГОСТ 34.10-94".
Now in that section they say something about the GOSTs are very much the same, though the MAIN difference is that the old standard part of operations is carried out over Zp field, and in the new one - over a group of points on an ellyptic curve, that's why the requirements for p are less strict in the new standard compared to the old one.
They also say in the article that encryption algorithm is a little different and more... but it's hard for me to translate this mathematical language for you, here is a screenshot of the Wiki article section: https://www.screencast.com/t/M1m7mMBzKHbl
Maybe you could just compare the two RFCs in English and find the differences?

**Comment by LumaRay** [comment]
@mouse07410 As I can see, Grasshopper is GOST 34.12-2015, RFC7801.
I've translated a part of Wiki article: https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B7%D0%BD%D0%B5%D1%87%D0%B8%D0%BA_(%D1%88%D0%B8%D1%84%D1%80)
"This code is approved (along with the block code “Magma”) as a standard in GOST R 34.12-2015 “Information technology. Cryptographic protection of information. Block ciphers "by the order of June 19, 2015 No. 749-item. [1] The standard came into effect on January 1, 2016. [2]. The cipher code was developed by the Center for Information Protection and Special Communications of the Federal Security Service of Russia with the participation of JSC Information Technologies and Communication Systems (JSC InfoTeKS). Introduced by the Technical Committee for Standardization TC 26 "Cryptographic protection of information" [3] [4]."

**Comment by mouse07410** [comment]
> As I can see, Grasshopper is GOST 34.12-2015, RFC7801 ... It was developed by ...

Yes, I know. My question was "is it **mandated** yet"?

Frankly, I thought that after standardizing Kuzniechik, Magma would be decertified, and everybody would be required to move away from it - much like what happened in USA when AES replaced DES. But apparently, this is not the case with Magma? Kuzniechik was defined, but the only required block cipher is still Magma from 1981 (or was it 1979)?

**Comment by LumaRay** [comment]
> My question was "is it **mandated** yet"?

Actually my initial question was regarding signing and hashing algorythms, because according to Russian Federal Security Service's paper dated 31 Jan 2014, №149/7/1/3-58 "Regarding the order of switching to using new digital signature and hashing standards", it is mandatory for digital signature infrastructure in Russia to use new standards beginning 1 Jan 2019.
I haven't seen and couldn't find anything about Kuznechik/Magma - whether any of them is mandatory or not. I actually event don't know where to search, because there are lots of articles regarding changing signature/hashing requirements, and none - regarding block ciphers. 
I can only see from wiki that both Magma and Kuznechik are included in the GOST 34.12-2015 standard, which is active since 1 Jan 2016. 
And I don't know anything regarding being permitted or not to use these standards. I suppose, if there are public GOSTs and RFCs, this automatically reveals these algorythms to public and thus permits everyone to use them...

**Comment by randombit** [comment]
I had to look into this recently at work. The 256A param is still valid. However new OIDs are used for both keys and curves so some updates are required.

**Comment by randombit** [comment]
New 512-bit params are given in https://tools.ietf.org/html/rfc7836 256-bit params are https://tools.ietf.org/html/rfc4357

**Comment by randombit** [comment]
With #2055 and #2056 merged we now use the updated OIDs for new certs/CSRs/keys. There is also a test that we can successfully verify a known-good (CryptoPro CSP generated) GOST 34.10-2012 cert chain. So I believe this can be closed. If you run into any problems please open a new issue.
