### ISSUE TITLE
Build minimal TLS client support

### ISSUE THREAD

**Issue by Tomatin** [randombit/botan#1861]
Hi, I need build ( if is possible with amalgamation single file ) a TLS client support with minimal modules. Someone could help me ?

Thanks !

**Comment by randombit** [comment]
I think all you need here is

`--minimized --amalgamation --single-amalgamation --enable-modules=tls,system_rng`

If you also need support for TLS v1.0/v1.1 then add `tls_cbc` as an additional requirement.

If targetting x86 also add at least `aes_ni` and `clmul` to get hardware acceleration for GCM. Or for ARMv8, `aes_armv8` `pmull`, `sha2_32_armv8`.

To enable ChaCha support add `chacha20poly1305`, `chacha_simd32`, and (for x86) `chacha_avx2`

**Comment by Tomatin** [comment]
It's work for me ! Thanks !
