### ISSUE TITLE
Restrict TLS cipher suites to desired ones instead of negotiating cipher suites based on allowed algorithms

### ISSUE THREAD

**Issue by perec-jar** [randombit/botan#1867]
Greetings to all, 

in our company we want to restrict used TLS Cipher Suites to specific ones instead of letting Botan to generate those based on the TLS_Policy.

Background:

Botan uses a TLS_Policy object to define the TLS security settings, e.g., the allowed key exchange algorithms, hash functions and so on.

Cipher Suites are then derived based on what policy allows, which may lead to undesired Cipher Suites.

As an example, Botan only allows to define the algorithms, so it would also allow a client to negotiate for example TLS_**DHE**_ECDSA_WITH_AES_256_GCM_SHA384, whereas desired is only **ECDHE**_ECDSA ciphersuites.

I would appreciate the answer as to how restricting the TLS Cipher Suites can be achieved.

Best regards,

Sergii

**Comment by randombit** [comment]
There are two main options for this

- Implement `TLS::Policy::acceptable_ciphersuite`. In this scenario the list of ciphersuites is generated as usual (by `Policy::ciphersuite_list`) but only those for which `acceptable_ciphersuite` returns true are included in the final result.

- Implement `TLS::Policy::ciphersuite_list`. This allows full control for the application, simply return exactly the ciphersuites which you wish to use in preference order.

Hope this helps. I see neither of these functions is currently documented, which should be addressed.

**Comment by perec-jar** [comment]
Hello Jack, thank you very much for the answer. I will document these functions and provide a pull request.

**Comment by randombit** [comment]
Thanks for the patch
