### ISSUE TITLE
Implement a CertificateStore for CAs on Linux

### ISSUE THREAD

**Issue by alnkpa** [randombit/botan#1869]
## Problem Description

In the effort to provide a platform-independent CA trust store (started with the [macOS integration](https://github.com/randombit/botan/pull/1830)), we are thinking about adding an implementation on Linux.
In contrast to Windows and macOS which both offer a standard interface to access the root CAs trusted by the system, Linux does not provide something like that.
Instead every distribution puts the trusted CAs either in a large amalgamation PEM file, in one or more directories one PEM-file at a time or some conbination of both.
Frankly, it seems to be (slightly) different for every distribution and other crypto libraries have various approaches to the issue (see [this blog post](https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/) for a pretty comprehensive writeup).

So before we start and try to implement something, we'd like to have your opinion on that.

## Ideas towards a solution

* Let the consuming application figure out where to find the trusted CAs by
  * compile-time configuration (assuming their packaging depends on the distribution anyway)
  * provide *the correct* trust store location in the `Certificate_Store_Linux` constructor
  * provide a list of potential locations in the constructor

* Let Botan decide internally by means of magic ;-)
  * probably a prioritized list of potential file system locations
  * by having a compile-time configurable default location (like OpenSSL does, for example), encouraging distributions to set their specific default location properly in their packaged Botan
* Let Botan ship an individual list of trusted CAs (the [NSS approach](https://wiki.mozilla.org/NSS_Shared_DB_And_LINUX))
  * Chrome [goes that way on Linux](https://github.com/chromium/chromium/blob/master/docs/linux_cert_management.md) while using the dedicated system store APIs on the other platforms
* Let OpenSSL decide
  * as stated above, OpenSSL (apparently) is shipped with the correct path [baked into the distribution-provided packages](https://github.com/openssl/openssl/blob/master/crypto/x509/x509_def.c)
  * we could [get the path from OpenSSL](https://stackoverflow.com/questions/4138139/how-to-find-out-the-path-for-openssl-trusted-certificate); obvious at the expense of a required dependency to OpenSSL
* don't implement `Certificate_Store_Linux` at all and let the application take care of it entirely :-(

**Comment by randombit** [comment]
> Let the consuming application figure out where to find the trusted CAs

This dumps work on the application developers which is lame.

> Let Botan decide internally by means of magic ;-)

I would favor what you suggest here (a default list + the option for a distributor to set a desired path) as something that balances minimizing work for lib developers, app developers, and distributors. And for Linux we have the benefit that all? distros already package Botan so if you are using the distro provided package hopefully everything just works out of the box, as long as the distribution set the path correctly.

We would want to also have a way for applications to override any built-in paths, should they have some special circumstance where they wish to use non-default CAs, or minimize the number of trusted CAs. (Thus implementing also the option "provide the correct trust store location"; but only for applications which actually want to do that).

> Let Botan ship an individual list of trusted CAs (the NSS approach)

It seems like Mozilla spends a lot of time on vetting CAs, arguing about which can be trusted, etc. I would rather not add that to our workload. Additionally it means that our decisions will inevitably differ from that of the system certificate stores.

> Let OpenSSL decide

This would be ok but means that on builds without OpenSSL dependency (which is very common), the functionality would not work at all. I would rather keep OpenSSL just as an optional accelerator, vs something that is required to get something that works at all.

One (rather hacky) option would be to try using pyopenssl to get these paths at build time in configure then embed them into the build, without requiring an OpenSSL dependency on the library itself. It seems cleaner to just have a configure.py option though, if distributions are willing to tell OpenSSL where to find these files at build time they should be willing to do the same for us.

> don't implement Certificate_Store_Linux at all

:(

As to implementation, `Certificate_Store_In_Memory` implements most of the logic already, and we have some hacks in the CLI to read the system cert stores in https://github.com/randombit/botan/blob/master/src/cli/credentials.h#L40 but it would be great to have a solution that actually works out of the box everywhere.

I'm not suggesting using `Certificate_Store_In_Memory` directly, but you can probably copy and paste a good bit of the code, especially the existing constructor that reads a directory of files. Some existing `In_Memory` functionality doesn't apply to the Linux certstores, eg `add_certificate` and CRL handling. And it probably makes sense to have some method so application can refresh or rescan the directories(s) as needed.

**Comment by randombit** [comment]
Completed in #1885
