### ISSUE TITLE
pkg-config Libs.private

### ISSUE THREAD

**Issue by edge90** [randombit/botan#1870]
```
cd build
../configure.py --prefix=$BUILD_DIR --with-external-includedir=$OPENSSL_PREFIX/include --with-external-libdir=$OPENSSL_PREFIX/lib --os=mingw --cpu=x86_64 --minimized-build --enable-modules=rsa,dsa,ecdsa,ed25519,hmac,hmac_drbg,mode_pad,bigint,filters,block,auto_rng,x509,cbc,dh --with-openssl
```

I have built openssl 1.0.2 in an external folder and the compilation of botan works just fine. When I try to use botan via botan-2.pc the line `Libs.private: -lcrypto` causes the linker to link my system libcrypto which is a openssl 1.1.X lib.

Solution in my case:
Replace `Libs.private: -lcrypto` with `Requires: libcrypto`.

Edit:
The project requiring botan uses qmake.

```
PKG_CONFIG = pkg-config
CONFIG += link_pkgconfig
PKGCONFIG += botan-2
```

**Comment by randombit** [comment]
Thanks for the report. I think the problem is related to your use of static libraries?

It may make sense (for the purposes of `pkg-config`) to assume all of our dependencies are also `pkg-config`ed and use `Requires` instead. I would need to double check that is true for the TrouSerS library.

**Comment by randombit** [comment]
BTW using the CLI: `botan config cflags` and `botan config libs` probably will get you the correct result. I can understand this probably is less convenient than pkg-config though.

**Comment by Edgesystems** [comment]
Ok, I did some sed-ing to replace the lines (for my build script). Don't know if it's related to building statically (no alternative with mingw), if I recall correctly it was the same story on mac.

**Comment by randombit** [comment]
This has been obviated by the fact that OpenSSL provider has been removed now :)
