### ISSUE TITLE
Proposal: Compress releases using xz instead of gzip

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1872]
It seems like these days xz is quite common, my understanding it is built into macOS Finder now, 7-Zip supports it, and of course it works on Linux/Unix. It also saves quite a bit of space, reducing the release file by about 1.5 MiB:

Format | Size |  %gzip |
----------- | ----- | ------- |
gzip        | 7246839 | 100%
bzip2      | 6376353 | 88%
xz            | 5547524 | 76%

I'm going to add a notice to the 2.10 changelog and advertise the change on the mailing list. If no objections are raised then 2.11 onwards will be compressed with xz instead of gzip.

**Comment by jimcruse** [comment]
I understand that zpaq and kgb than xz

**Comment by randombit** [comment]
Balancing compression ratio and wide-spread availability, xz seems best. For instance afaik neither zpaq nor kgb are supported by macOS Finder. It's nice to save space but making someone install a special tool they wouldn't otherwise use just to decompress a release adds a lot of friction.

**Comment by bkircher** [comment]
As far as Fedora packaging is concerned this is fine.
