### ISSUE TITLE
TLS client with certificate validation

### ISSUE THREAD

**Issue by Tomatin** [randombit/botan#1873]
Hi. I need to write a TLS client with certificate validation. This client connects to a TLS server with some resources that do not require certificate validation and other resources that require it. 
Communication with resources that do not require the certificate is working correctly, but the other one does not.
I had read this post [https://github.com/randombit/botan/issues/282](url) and overwrite this methods:

1. cert_cain
2. private_key_for

In the first method I return the correct x509 certificate and in the second method I return the private key of this certificate. 

Question. Do I need to do something else ? 

Thanks in advance !

**Comment by randombit** [comment]
It sounds like you are doing what is required. Have you checked (eg using Wireshark) that the certificate is being sent over the wire?

**Comment by Tomatin** [comment]
Hi. When I overloaded the **cert_chain** and **private_key_for** methods, the TLS init transaction is aborted by this exception  "Policy refuses to accept signing with any hash supported by peer"
Let me show a fragment of code ...

credentials.h
```cpp
class client_credentials_manager : public Botan::Credentials_Manager
{
  public:
    client_credentials_manager( const std::string &path, const std::string &p_key );
    std::vector<Botan::Certificate_Store*> trusted_certificate_authorities( const std::string& type, const std::string& hostname ) override;
    std::vector<Botan::X509_Certificate> cert_chain( const std::vector<std::string> &cert_key_types, const std::string &type, 
                                                     const std::string &context );
    Botan::Private_Key* private_key_for( const Botan::X509_Certificate& crt, const std::string&, const std::string& ) override;
  protected:
    std::vector<std::shared_ptr<Botan::Certificate_Store>> certstores;
    std::unique_ptr<Botan::Private_Key> private_key;
    std::string cert_path;
    std::string pkey_path;
};
```
credentials.cpp
```cpp
std::vector<Botan::Certificate_Store*> client_credentials_manager :: trusted_certificate_authorities( const std::string& type, 
                                                                                                      const std::string& hostname )
{
  std::vector<Botan::Certificate_Store*> v;
        
  for ( auto const& cs : this->certstores )
  {
    v.push_back( cs.get() );
  }
        
  return( v );
}
    
client_credentials_manager :: client_credentials_manager( const std::string &path, const std::string &p_key )
{
  // Save the certifcate and private key path
  cert_path = path;
  pkey_path = p_key;

  try
  {
    if (( is_path_exist( path ) == true ) || ( path == "" ))   
    {
      // Load certicate(s) from folder 
      auto cs = std::make_shared<Botan::Certificate_Store_In_Memory>( path );
      this->certstores.push_back( cs );
    }
    else
    {
      // Load individual x509 certificate 
      auto cs = std::make_shared<Botan::Certificate_Store_In_Memory>( Botan::X509_Certificate( path ));
      this->certstores.push_back( cs );
    }
  }
  catch ( Botan::Exception &e ) 
  {
    throw_line( _err_invalid_certificate_ );
  }
}
  
std::vector<Botan::X509_Certificate> client_credentials_manager :: cert_chain( const std::vector<std::string> &cert_key_types, 
                                                                               const std::string &type, 
                                                                               const std::string &context )
{
  std::vector<Botan::X509_Certificate> certificate;

  if ( type == "tls-client" ) 
  {
    try
    {
      certificate.push_back( Botan::X509_Certificate( cert_path ));
    }
    catch ( Botan::Exception &e ) 
    {
      throw_line( _err_invalid_certificate_ );
    }
  }

  return( certificate );
}

Botan::Private_Key* client_credentials_manager :: private_key_for( const Botan::X509_Certificate& crt, const std::string &type, 
                                                                   const std::string &context )
{
  // Load private key
  try
  {
    Botan::DataSource_Stream somefile( pkey_path );
    private_key = Botan::PKCS8::load_key( somefile, "" );
  }
  catch ( Botan::Exception &e ) 
  {
    throw_line( _err_invalid_certificate_ );
  }

  return( private_key.get() );
}
```
ssl.cpp
```cpp
ssl_comm :: ssl_comm( const std::string certificate_name, const std::string password ) : 
            policy( "" ), session_mgr( Botan::system_rng() ), credentials( certificate_name, password )
{
  // Create botan callbacks 
  botan_io_callbacks = new Callbacks( this ); 

  // Set acceptable policies 
  policy.set( "signature_methods", "IMPLICIT" );
  policy.set( "key_exchange_methods", "RSA" );
  policy.set( "ciphers", "AES-128/GCM" );
  policy.set( "signature_hashes", "SHA-256" );
  policy.set( "minimum_rsa_bits","2048" );
 }

```
Thanks in advance !

**Comment by Tomatin** [comment]
Excuse me, can anyone help me ?

**Comment by randombit** [comment]
@Tomatin sorry I was away for a week. Your code looks ok at first glance. Are you sure that the server you are talking to is going to (always) use SHA-256? Because the error you get is basically, `signature_hashes` was set to SHA-256 only, but the server sent something else (likely SHA-384/SHA-512). You should be able to verify what the server sent by looking at the ServerKeyExchange message in wireshark.

**Comment by Tomatin** [comment]
Hi. Unfortunately I do not know in depth the SSL / TLS protocol. This server is a embedded box and works fine with python and java clients.  I have a WireShark capture. The Alert message say Level:2 and description "Handshake failure" ... 

Thanks in advance ! 



![image](https://user-images.githubusercontent.com/20709896/55982111-8cce5080-5c6e-11e9-8872-01abe1b2486a.png)

**Comment by randombit** [comment]
Try commenting out
  policy.set( "signature_hashes", "SHA-256" );

**Comment by Tomatin** [comment]
Hi. Thanks you !!! My application is working !. My solution was, I enabled more modules in the build. And set the policy like this:

  // Set acceptable policies 
  policy.set( "signature_methods", "IMPLICIT RSA ECDSA" );
  policy.set( "key_exchange_methods", "RSA CECPQ1 ECDH" );
  policy.set( "ciphers", "AES-128/GCM AES-256/GCM ChaCha20Poly1305" );
  policy.set( "signature_hashes", "SHA-512 SHA-384 SHA-256" );

Thank you very much for your support !!!
