### ISSUE TITLE
Usage Question: How to generate intermediate CA through CLI

### ISSUE THREAD

**Issue by volkan-ozdemir** [randombit/botan#1879]
Hello,

Is it possible to generate an intermediate CA through CLI or do I have to use API to set Is CA as true?

I tried following CLI commands but I'm getting "Error: X509_CA: This certificate is not for a CA":

botan keygen --algo=ECDSA > ROOT.key
botan gen_self_signed ROOT.key Root --organization=test --hash=SHA-256 --ca > ROOT.crt
botan keygen --algo=ECDSA > Intermediate.key
botan gen_pkcs10 Intermediate.key Intermediate --organization=test --hash=SHA-256 --ext-ku=X509v3.BasicConstraints,X509v3.KeyUsage > Intermediate.csr
botan sign_cert --hash=SHA-256 --duration=365 ROOT.crt ROOT.key Intermediate.csr > Intermediate.crt
botan keygen --algo=ECDSA > Leaf.key
botan gen_pkcs10 Leaf.key Leaf --organization=test --hash=SHA-256 > Leaf.csr
botan sign_cert --hash=SHA-256 --duration=365 Intermediate.crt Intermediate.key Leaf.csr > Leaf.crt

"Error: X509_CA: This certificate is not for a CA"

I'm guessing --ext-ku just adds the field to pkcs10 request but bitset should be manually set?

**Comment by randombit** [comment]
This is not currently supported, but should be. Thanks for raising the issue I will see if we can add this soon.

**Comment by randombit** [comment]
@volkan-ozdemir With #1889 merged this feature will be available in future releases.
