### ISSUE TITLE
compile but doesn't work (windows10)

### ISSUE THREAD

**Issue by Hug0Vincent** [randombit/botan#1896]
I have a fresh install of Windows10 with python3 and mingw-64 I used python ./configure.py -cc=GCC -os=mingw everything worked fine then I used make, everything compiled but when I tried to run  botant-test.exe it didn't work, no output at all I also tried to use an example provided with the doc it compiled but same issue no output. Anybody know what to do ? 

Thanks.

**Comment by randombit** [comment]
That is a pretty strange problem. Some things to try

* Does a basic hello world (just using std::cout) work?
* Does `botan --help --output=help.txt` create help.txt? Does it write anything to it?
* What is the return code when you run the prog?

**Comment by Hug0Vincent** [comment]
I tried this code : 

````
#include <botan/hash.h>
#include <botan/hex.h>
#include <iostream>

int main ()
   {
   std::unique_ptr<Botan::HashFunction> hash1(Botan::HashFunction::create("SHA-256"));
   std::cout << "OK" << std::endl;
}
````

No output... 

`.\botan-test.exe --help --output=help.txt`
No file created and no output same for botan.exe 

There is no return code something seems to happen but no error and no output 

```
PS C:\Users\user\Downloads\botan-master\botan-master> .\botan-test.exe
PS C:\Users\user\Downloads\botan-master\botan-master>
```

**Comment by randombit** [comment]
How about this?

```
#include <iostream>

int main ()
   {
   std::cout << "OK" << std::endl;
   }
```

**Comment by Hug0Vincent** [comment]
This works perfectly fine :

```
PS C:\Users\user\Documents\Project> g++ -o .\test.exe .\test.cpp
PS C:\Users\user\Documents\Project> .\test.exe
OK
PS C:\Users\user\Documents\Project>
```

**Comment by randombit** [comment]
Interesting. I'm not really sure what to suggest at this point. Maybe try debugger and trace through the execution to see where/why it exits. Or sprinkle printfs...

**Comment by giorgiozoppi** [comment]
try clang?

**Comment by randombit** [comment]
Closing as inactive. Still no idea how ^ would be happening.

**Comment by randombit** [comment]
@Hug0Vincent it looks like (based on #2187) this is a bug affecting recent versions of MinGW https://sourceforge.net/p/mingw-w64/bugs/755/ you can work around the problem by configuring with flag `--without-stack-protector`
