### ISSUE TITLE
python binding: PEM export of RSA private key

### ISSUE THREAD

**Issue by orzel** [randombit/botan#1899]
With botan 1.11 python binding, it was possible to get the "PEM" export of both public and private keys, using
```
private_pem = private_key.to_string()
public_pem = public_key.to_string()
```

Porting some code to botan 2.9.0, it doesn't seem possible anymore. I can have the pem export for  public key by doing:
```
public_key.encoding(True)
```
But nothing seems available for private key. I've checked the documentation, and also the python file on my distribution (gentoo): /usr/lib64/python2.7/site-packages/botan2.py

Please re-add this feature ?

**Comment by randombit** [comment]
Thanks for pointing this out, should be addressed by #1901
