### ISSUE TITLE
Support setting alternate lib/include paths at configure time

### ISSUE THREAD

**Issue by randombit** [randombit/botan#19]
Eg stuff like:

./configure.py --with-boost=/opt/boost_1_55
- look in /opt/boost_1_55/include and /opt/boost_1_55/lib resp

./configure.py --with-zlib=/usr --with-zlib-libdir=lib64
- where libdir is relative to the base dir

Or at least that's first thought. Should try to match autoconf conventions, assuming there are any.

**Comment by neusdan** [comment]
Partially resolved in PR #507 for external includes.

**Comment by randombit** [comment]
Fixed, closing
