### ISSUE TITLE
python binding: features dropped ?

### ISSUE THREAD

**Issue by orzel** [randombit/botan#1900]
Several features from the python binding in botan 1 can't be found in botan2. Is that work in progress, or is a dead end.. ?

Despite my previous report #1899 about PEM export for RSA key, i see at least the following:

1) Creating a private key from a PEM (x.509 base64 DER with ----BEGIN ... -----END)
it was possible using 
```
private_key2 = botan.RSA_PrivateKey(private_pem, rng, "")
```

2) The same for a public key. It was possible using
```
botan.RSA_PublicKey(str_public_key)
```

3) export a (public) key to BER. it was possible using
```
pubkey.to_ber()
```

**Comment by randombit** [comment]
> Is that work in progress, or is a dead end.. ?

Python binding is not seeing a lot of active development right now, but it's not supposed to be a dead end. It's just (unintentionally) incomplete. But you are right, all functionality you mention is currently missing. It is available in the C API (and is used for instance in the Rust binding), but missing from Python. Exporting public key as DER is added in #1901, I will add the other two shortly.

If you notice any other functionality that is missing please do open issues.

**Comment by randombit** [comment]
Related #1906

**Comment by randombit** [comment]
All the features you mention above as missing are now available in the latest version of the Python wrapper, so I'm closing this issue. You can test the new code just by copying master's `botan2.py` and running it against an existing release as no changes on the library side were required.

There are still many features available in the C API which are not exposed to Python, this is tracked in #1906.

**Comment by orzel** [comment]
I can confirm that in Botan 2.11.0 everything i need is available in the python binding.

One shortcoming is that for the python MsgAuthCode(), the length is hardcoded to '20', which is not the value used by our other end (coded in C++). This would be great to allow the python binding to specifgy the MAC length.

But this is a minor issue, not as much a blocker as those from this ticket (and ticket #1899 ).

Thanks a lot for implementing those bindings, and for Botan in general !

**Comment by randombit** [comment]
> One shortcoming is that for the python MsgAuthCode(), the length is hardcoded to '20', which is not the value used by our other end (coded in C++). This would be great to allow the python binding to specifgy the MAC length.

Do you mean by this, that for say HMAC-SHA-1 always the output is 20 bytes but in C++ you are truncating?
