### ISSUE TITLE
DTLS Server ERROR stops at Can't agree on a ciphersuite with client

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#1914]
I have a problem with simple DTLS server :( 

My Code is:
https://pastebin.com/L59Fu9ey

I tried it with Qt DTLS Client Example and BOTAN-cli tls_client both failed with Server throwing Exception "Cannot agree on ciphersuite with client"

Plattform is: Windows
sockets: Winsocks2 (no third party library)
x64

where is my mistake ?

Thanks for help.

**Comment by randombit** [comment]
I don't see anything obviously wrong. Try checking with wireshark and verifying that the client is sending the expected list of ciphersuites in the client hello (first message).

**Comment by seppy87** [comment]
Hallo,

here the Wireshark Extraction
https://pastebin.com/tZwqUC0F

**Comment by seppy87** [comment]
OK tested with gnuTLS on Windows. The testscript accepted and sended a Hello Verify to Qt DTLS Example. but why is botan refusing :/

**Comment by randombit** [comment]
I just noticed, your `DTLSPolicy` defaults to disabling both DTLS v1.0 and v1.2, and in `main` you set allowed MACs and such but never enable either protocol version.

If that is the problem, the error here is a bit confusing. There is supposed to be a check for this to detect policy configuration errors, but I think the code is getting confused by the ciphersuite signaling value for secure renegotiation.

**Comment by seppy87** [comment]
I checked. The Version will be enabled in the DTLSPolicy Construction

`DTLSPolicy::DTLSPolicy(DTLSVersion minimum)
{
	switch (minimum) {
	case DTLSVersion::DTLS_ANY:
		this->noexclusion = true;
	case DTLSVersion::DTLS_1_0:
		this->dtls10_enabled = true;
	case DTLSVersion::DTLS_1_2:
		this->dtls12_enabled = true;
		break;
	default:
		std::cerr << "This should not be reached!\n";
		break;
	}
}`

and the DTLSVersion is an enum class
`enum class DTLSVersion : unsigned int {
	DTLS_ANY = 0,
	DTLS_1_0 = 1,
	DTLS_1_2 = 2,
	DTLS_LATEST = 10,
};`

Maybe you have some code snippet to test, if my DLLs are correctly built.

**Comment by randombit** [comment]
You could check with

`./botan tls_server --type=udp --port=4444 server.crt server.key`

which creates a DTLS echo server running on UDP 4444.

Unfortunately `tls_server` in DTLS mode is broken on Linux due to a recent change you may need to apply the patch in #1924

**Comment by seppy87** [comment]
Hallo
I just made a minimal Code to test
https://pastebin.com/eNA0RtrK

with s.send I am receiving botan::internal_error exception

Wireshark says last two DTLS Packets are Server Hello Done and after Fatal Error

Any clues?

**Comment by randombit** [comment]
From later tickets it sounds like you got this working so closing this but feel free to reopen if still having problems.
