### ISSUE TITLE
SRP6 implementation fixed length of random number parameters "a" and "b"

### ISSUE THREAD

**Issue by courteous** [randombit/botan#1917]
I have 3 questions regarding the implementation

1) The file botan/srp6.h

contains method signature 

BigInt SRP6_Server_Session::step1(const BigInt& v,
                                  const std::string& group_id,
                                  const std::string& hash_id,
                                  RandomNumberGenerator& rng
								  );
there is a const variable declared there i.e. 
 const size_t b_bits = 256;

Why was this variable set to const there?

The rfc5054 section "2.5.3.  Server Key Exchange" (https://tools.ietf.org/html/rfc5054)
Explicitly says and i quote:

"
 ...
   where b is a random number that SHOULD be at least 256 bits in length
 ...  
"

it says at least but it does not says that it should be always be 256 bits! 

Is there a reason why the "b" is beeing set to a constant? 
The point i am trying to make here is that if that paramters will be constant there then the vector from the same RFC will  at least for me not pass the library. 

Does it make scene to externalize this parameter and make it variable?

2) the same with the method  signature

srp6_client_agree(const std::string& identifier,
                  const std::string& password,
                  const std::string& group_id,
                  const std::string& hash_id,
                  const std::vector<uint8_t>& salt,
                  const BigInt& B,
                  RandomNumberGenerator& rng)
 
const size_t a_bits = 256;

3) Is there a way to initialize the "RandomNumberGenerator& rng" with predefined hex string, thus we can pass the predefined vector , this question is again related to passing the vector from rfc5054 i.e. "Appendix B.  SRP Test Vectors" in this case i would like to pass BigInt directly.

Botan::BigInt bSecret("0xE487CB59D31AC550471E81F00F6928E01DDA08E974A004F49E61F5D105284D20");

I have made the changed to my local repo and pass BigInt instead RandomNumberGenerator and then the parameters verifier , k and B were computed correctly otherwise the B does not match the vector and i guess that it is expected, or am i missing something here?

many thanks in advanced 

Tito

**Comment by courteous** [comment]
An addition does it make to change the signature of those method to accept BigInt instead of RandomNumberGenerator since if the library will be used in a web application the seed could come from a web browser i.e. that random parameters "a" and b will be provided from an external application.

**Comment by randombit** [comment]
> it says at least but it does not says that it should be always be 256 bits!

You're right and this leads to undersized exponents when the SRP group is > 3072 bits, though I'm not particularly worried about a 2**128 Pollard rho attack.

> Does it make scene to externalize this parameter and make it variable?

Maybe for testing purposes. It seems like a dangerous toggle to give since setting it to say 128, everything "works" but is weak. I guess though since the RFC requires >= 256 bits we can just reject that case and then the user is no worse off than current behavior. So probably ok to make this a (defaulted) parameter.

> Is there a way to initialize the "RandomNumberGenerator& rng" with predefined hex string

Yes and no. There is no way to do this with the library PRNGs since usually a RNG that returns a constant string is a bad idea. However of course we need this for testing which is why there are several RNG impls that do such things in https://github.com/randombit/botan/blob/master/src/tests/test_rng.h you probably want the `Fixed_Output_RNG`.

> if the library will be used in a web application the seed could come from a web browser i.e. that random parameters "a" and b will be provided from an external application.

I do not understand why you would ever want to do this, can you explain more?

**Comment by randombit** [comment]
Addendum: if there really is a scenario where "random parameters "a" and b will be provided from an external application" is a good idea, then the whole resolution here is easy, provide a version of SRP APIs where the user provides a and b directly, current code (taking a RNG&) just creates random a/b then calls the new functions.

Currently the SRP test is just a round-trip with ourselves (https://github.com/randombit/botan/blob/master/src/tests/test_srp6.cpp) so from a testing perspective it would be good to improve here.

**Comment by courteous** [comment]
Jack many thanks for the quick reply.  I would like to explain some thing in order to clear what i mean here: 

The reason why a and b could be external are mainly 3

1) for testing purposes. You would like to test with all possible Vectors that currenly are defined in a RFC!!! This is very important since that gives you "kind of a good feeling" that all "might" work correctly.

2) Since a and b are the private keys in the SRP case. There are multiple requirements where the random seed is being provided from specialized  hardware and you want to use the input of that hardware.

3) in case the library is used with webassembly. You would like to allow the user to allow themselves to plug their own bits that they trust maybe that is the web browser or maybe a USB key that is providing this.  


many thanks 


Tito

**Comment by courteous** [comment]
in addition, please note that you already have externalized the group and the generator of the multiplicative group as well as the the hashing algorithm. In my opinion you are right that the value 256 should be the default one but the library should also give the ability to at least increase it as well.

**Comment by courteous** [comment]
in the step1 method  the random parameters is being converted into BigInt anyway i.e.
BigInt SRP6_Server_Session::step1x(const BigInt& v,
                                  const std::string& group_id,
                                  const std::string& hash_id,
                                  BigInt& b
								  )
....
//   m_b = BigInt(rng, b_bits);
...

so why not passing a well prepared Bigint in the first place?

**Comment by courteous** [comment]
In the step1 method the RandomNumberGenerator argument is beeing converted into BigInt . So why not passing a well prepared BigInt in the first place.

BigInt SRP6_Server_Session::step1(const BigInt& v,
                                  const std::string& group_id,
                                  const std::string& hash_id,
                                  RandomNumberGenerator& rng
								  )

....

//   m_b = BigInt(rng, b_bits);
...

**Comment by randombit** [comment]
I'm personally not so convinced re your points 2/3 however for testing the changes you suggest are necessary, and the SRP code definitely needs better tests that it has currently. I will look into this sometime soon.

**Comment by randombit** [comment]
Now with #1923  it is possible to set the length of the SRP secret exponents. Instead of hardcoding it to 256 bits, the default length is scaled based on the size of the SRP group. And there are full tests including the test from RFC 5054. So I think this can be closed. Thanks for your helpful comments.
