### ISSUE TITLE
SRP6 implementation  ( if B % N = 0 )   AND  ( if A % N = 0 ) validation

### ISSUE THREAD

**Issue by courteous** [randombit/botan#1921]
Most likely this is something that i am missing on my side here but still i wanted to ask where is the following check for the following requirement from rfc5054

The RFC states 

Section 2.5.3.  Server Key Exchange
...
The client MUST abort the handshake with an "illegal_parameter" alert
   if B % N = 0.
...

Section 2.5.4.  Client Key Exchange
...
  The server MUST abort the handshake with an "illegal_parameter" alert
   if A % N = 0.
...

**Comment by randombit** [comment]
This happens at

https://github.com/randombit/botan/blob/master/src/lib/misc/srp6/srp6.cpp#L93
https://github.com/randombit/botan/blob/master/src/lib/misc/srp6/srp6.cpp#L153

We require A and B be strictly in [1,p)

**Comment by courteous** [comment]
Hello Jack many thanks for the reply, 

can you explain why this is modulo check ,  i.e. i must say I am new to the code but this does not seem a modulo N . I might be wrong here , i am just trying to understand it. 

(B <= 0 || B >= p)

**Comment by courteous** [comment]
got it please ignore my last comment
