### ISSUE TITLE
SRP6 predefined RNG as a vector

### ISSUE THREAD

**Issue by courteous** [randombit/botan#1926]
Hello Jack, 

as discussed in Tiket #1917 

sometimes we would like to use the library with external rng.  Whether this is a good or bad idea is another conversation, but it is a requirement sometimes. 
That is exactly the case i am currently in. The following client srp call 

```
std::pair<BigInt,SymmetricKey>
BOTAN_PUBLIC_API(2,0) srp6_client_agree(const std::string& username,
                            const std::string& password,
                            const std::string& group_id,
                            const std::string& hash_id,
                            const std::vector<uint8_t>& salt,
                            const BigInt& B,
                            RandomNumberGenerator& rng)
```

becomes very difficult, because of the RandomNumberGenerator there. 

You have advised me that in this case a particular rng can be used i.e.  Botan_Tests::Fixed_Output_RNG, but the problem is that this class is part of the Botan_Tests namespace and not part of the Botan namespace that leads to multiple problems i.e. forcing us to link not only to one file.
Also multiple other problems are appearing such as the one below when you try to link to the Fixed_Output_RNG :
 
```

src/ref/libs.so: undefined reference to `Botan::RandomNumberGenerator::reseed_from_rng(Botan::RandomNumberGenerator&, unsigned long)'
src/ref/libs.so: undefined reference to `Botan::RandomNumberGenerator::randomize_with_ts_input(unsigned char*, unsigned long)'
src/ref/libs.so: undefined reference to `vtable for Botan::RandomNumberGenerator'
src/ref/libs.so: undefined reference to `Botan::RandomNumberGenerator::randomize_with_input(unsigned char*, unsigned long, unsigned char const*, unsigned long)'
src/ref/libs.so: undefined reference to `typeinfo for Botan::RandomNumberGenerator'

```

Does it make sense to put the freedom to the use to set his source of the seed  there. 
If i am wrong here can you please let me know if there is a build in way to preset the  RandomNumberGenerator with a vector of <uint8_t> in a way that i do not have to use Fixed_Output_RNG. I have tried Null_RNG and TPM_RNG but i do not seems to find a way to properly initialize them. Is there some dedicated external RNG ? 

Something like

```
const std::vector<uint8_t> a =  vars.get_req_bin("a");;
Fixed_Output_RNG a_rng(a);
const auto srp_resp = Botan::srp6_client_agree(username, password, group, hash, salt, B, a_bits, a_rng);

```
this works for botan itself during the test, but not if you link to a single file "libbotan-2.a"

many thanks in advanced.

Tito

**Comment by randombit** [comment]
> sometimes we would like to use the library with external rng. 

This is fine, and the API (across the library) goes out of its way to allow this. Just implement `RandomNumberGenerator` interface to call whatever RNG you want using whatever API is used for that. There is no explicit documentation on how to write your own RNG instance but it is pretty simple, especially if the RNG doesn't accept external inputs. For instance here is the complete `RandomNumberGenerator` for calling `arc4random`:

```
class System_RNG_Impl final : public RandomNumberGenerator
   {
   public:
      // No constructor or destructor needed as no userland state maintained

      void randomize(uint8_t buf[], size_t len) override
         {
         ::arc4random_buf(buf, len);
         }

      bool accepts_input() const override { return false; }
      void add_entropy(const uint8_t[], size_t) override { /* ignored */ }
      bool is_seeded() const override { return true; }
      void clear() override { /* not possible */ }
      std::string name() const override { return "arc4random"; }
   };
```

> Does it make sense to put the freedom to the use to set his source of the seed there.

Absolutely so, which is why the caller must pass a `RandomNumberGenerator&` instance, rather than all of the code implicitly referring to some fixed global RNG as is done in some other libraries.

**Comment by courteous** [comment]
Hello Jack,

many thanks for this. I did exactly what you suggested here and created  a class that extends RandomNumberGenerator. However, in my case the RNG does accept input i.e. it accept the random buffer as  "const std::vector<uint8_t>&" , when i do that i get the errors mentioned below and the problem is i do not know what they mean. Any idea?

here is the class:



```

#include <botan/srp6.h>
#include <botan/hash.h>
#include <botan/dl_group.h>
#include <botan/numthry.h>
#include <string>
#include <iostream>
#include <vector>

#include <botan/rng.h>
#include <chrono>
#include <deque>


#ifndef FIXED_RNG_HPP_
#define FIXED_RNG_HPP_

namespace platform {


class Fixed_RNG final : public Botan::RandomNumberGenerator
   {
   public:

      size_t reseed(Botan::Entropy_Sources&,
                    size_t,
                    std::chrono::milliseconds) override
         {
         return 0;
         }

//      virtual void reseed_from_rng(RandomNumberGenerator& rng,
//                                   size_t poll_bits = BOTAN_RNG_RESEED_POLL_BITS){
//    	  /* ignored */
//    	  std::cout << "Fixed RNG reseed_from_rng called " <<  rng << poll_bits  << std::endl;
//      }


      std::string name() const override
         {
         return "Fixed_RNG";
         }




      explicit Fixed_RNG(const std::vector<uint8_t>& in) {

		m_buf.insert(m_buf.end(), in.begin(), in.end());
	}



      void randomize(uint8_t buf[], size_t len) override
              {
    	  /* ignored */
    	  std::cout << "Fixed RNG randomized called " << buf  << len << std::endl;

              }

      bool accepts_input() const override { return false; }
      void add_entropy(const uint8_t[], size_t) override { /* ignored */ }
      bool is_seeded() const override { return true; }
      void clear() override { /* not possible */ }







   protected:


   private:
      std::deque<uint8_t> m_buf;
   };



   }




#endif 
```




src/ref/libs.so: undefined reference to `Botan::RandomNumberGenerator::reseed_from_rng(Botan::RandomNumberGenerator&, unsigned long)'
src/ref/libs.so: undefined reference to `Botan::RandomNumberGenerator::randomize_with_ts_input(unsigned char*, unsigned long)'
src/ref/libs.so: undefined reference to `vtable for Botan::RandomNumberGenerator'
src/ref/libs.so: undefined reference to `Botan::RandomNumberGenerator::randomize_with_input(unsigned char*, unsigned long, unsigned char const*, unsigned long)'
src/ref/libs.so: undefined reference to `typeinfo for Botan::RandomNumberGenerator'

**Comment by randombit** [comment]
Those symbols are all defined within the library, make sure you are using `-lbotan-2` to link.

**Comment by randombit** [comment]
Closing, feel free to reopen if still having problems.
