### ISSUE TITLE
Is there a difference between --gen-amalgamation and --via-amalgamation?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#193]
`./configure.py` source is a bit too complex because of this two similar/same options. Is there a good reason to keep both?

**Comment by randombit** [comment]
The only difference is that `--gen-amalgamation` builds the amalgamation files but builds via the normal sources. It was the original amalgamation option but probably can be removed as building the amalg but not using it for the build seems like an odd combination.

**Comment by webmaster128** [comment]
Okay fine. Then we can deprecate both `--gen-amalgamation` and `--via-amalgamation`, rename `--via-amalgamation` to just `--amalgamation` and drop `--gen-amalgamation` functionality?

**Comment by neusdan** [comment]
I think this can be closed with merging #621

**Comment by randombit** [comment]
Closing, thanks all
