### ISSUE TITLE
Test Boost in AppVeyor MSVC builds

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1930]
Re #1927

**Comment by reneme** [comment]
While finishing up our Windows build we realised that boost has [peculiar naming conventions](https://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html#library-naming) for its libraries. On Windows, static libraries are prefixed with `lib` (e.g. `libboost_system.lib`), "import libraries" are not (e.g. `boost_system.lib` stubbing for some `boost_system.dll`). And further there are some layers of name-based versioning, that are configurable at build time.

We tried to work around the `*.lib` suffix in #1940. That is not enough though, as we want to link statically, i.e. the `lib...` prefix would be required as well on windows. At this point we're not sure how to allow for both dynamic and static linkage with the `info.txt` machinery on Windows. Any thoughts on this?

We'll have a closer look at this tomorrow and (hopefully) also get to test it on AppVeyor in the process.

**Comment by reneme** [comment]
@randombit In case you read this soon: It would be cool if you could kill all AppVeyor builds except the latest one (with git sha: 2f64492).

**Comment by randombit** [comment]
@reneme I just killed all but the most recent commit.

For testing might help to temporarily prune the build matrix to a single build, get that one working, then re-add the others.

**Comment by reneme** [comment]
Thanks for reviewing and merging this. Would be great to run the asio tests on the other platforms some day too...

**Comment by randombit** [comment]
Sadly Travis really lags behind, Ubuntu 18.04 was released before 16.04 became available for CI. At that rate, we'll get 18.04 support in 2020 - and because in turn Ubuntu also specializes in releasing obsolete software, 18.04's Boost is too old anyway, so that doesn't help anyway :(

I think best chance is to move Travis to a Docker setup so we can control the image and pre-populate useful packages.

But for this ticket, closing, fixed in #1964
