### ISSUE TITLE
[usage question] write salt+iv to encrypted file

### ISSUE THREAD

**Issue by elimpnick** [randombit/botan#1933]
I've been trying to find the proper way to write the salt and IV to an encrypted file so it can be decrypted without hard-coding the salt and IV in the executable.  I'm using a `Pipe` and `DataSink_Stream`.  I've come across many examples here and there on how to do this, and I have something working, but I feel like this is definitely not the right way (or at least the prettiest way).

Here's my code snippet:

```
string input_file{ "testfile" };
string output_file{ "out.encrypted" };
string passphrase{ "mypassword" };

Botan::AutoSeeded_RNG rng;

Botan::PBKDF *pbkdf                   = Botan::get_pbkdf("PBKDF2(SHA-256)");
Botan::SecureVector<Botan::byte> salt = rng.random_vec(16);
Botan::SymmetricKey key               = pbkdf->derive_key(32,
                                                          passphrase,
                                                          &salt[0],
                                                          salt.size(),
                                                          10000);
Botan::InitializationVector iv(rng, 16);

cout << "Encryption key : " << key.to_string() << endl;
cout << "IV : " << iv.to_string() << endl;
cout << "Encrypting " << input_file << endl;

// ENCRYPT
std::ofstream outfile(output_file, std::ios::binary);
Botan::DataSource_Stream infile(input_file, true);
outfile.write(reinterpret_cast<const char *>(&salt[0]), salt.size());
outfile.write(iv.to_string().c_str(), iv.to_string().size());
Botan::Pipe pipe(get_cipher("AES-256/GCM", key, iv, Botan::ENCRYPTION),
                           new Botan::DataSink_Stream(outfile));

pipe.process_msg(infile);
```

My problem is with the two `outfile.write` lines, clearly there has to be a better way to do this? My decrypt  block is even worse... The compiler is also throwing a "implicit conversion changes signedness" warning due to the size() call.

Thanks!

**Comment by randombit** [comment]
I don't think you're doing anything wrong here, the C++ iostreams design is kind of junk for binary IO unfortunately. My main suggestion would be to encode the data using some scheme like protobuf or ASN.1, and then at least you have only one ugly reinterpret_cast when you write out the entire data. You can see an example of that kind of thing in https://github.com/randombit/botan/blob/master/src/cli/pk_crypt.cpp where an RSA encrypted key, nonce and ciphertext are all encoded into a single blob. You can base64 encode everything, which works well for streams which are very string oriented, but that increases storage requirements.

Only thing "wrong" I see with your code is you call iv.to_string() twice, and really there is no reason to use to_string at all (which hex encodes) when everything else is binary. Neither is a correctness issue, just (slightly) inefficient.

If you just need to encrypt something and don't particularly care about the format you can also use https://botan.randombit.net/manual/cryptobox.html which is a library-specific design but already built and tested.

**Comment by elimpnick** [comment]
Thanks for your response!  

For the `iv.to_string()` calls, if I remove `to_string`, then I'm stuck with another `reinterpret_cast` correct?

I'll look into encoding the data like you have in your example, looks like that's the cleanest option.  As for `cryptobox`, it seems fine but I'd rather have control over encryption ciphers and what not.

Thanks again!

**Comment by randombit** [comment]
> For the iv.to_string() calls, if I remove to_string, then I'm stuck with another reinterpret_cast correct?

Correct.

**Comment by elimpnick** [comment]
Thanks again.

I haven't been able to properly get rid of the `iv.to_string()` (can't seem to be able to read the IV back  properly). 
That said, I do have both working functions here for reference in case someone needs it.  There's definitely ways to improve this, I'd like to store the IV and read it back not as a string as it shows that encryption is being used.  Once I figure that one out, next step will be to replace PBKDF with PasswordHash/scrypt.

```
void encrypt_file(string input_file, string output_file, string passphrase) {
  Botan::AutoSeeded_RNG rng;

  Botan::SecureVector<Botan::byte> salt = rng.random_vec(16);
  Botan::PBKDF *pbkdf                   = Botan::get_pbkdf("PBKDF2(SHA-256)");
  Botan::SymmetricKey key               = pbkdf->derive_key(32,
                                                            passphrase,
                                                            &salt[0],
                                                            salt.size(),
                                                            10000);
  Botan::InitializationVector iv(rng, 16);

  cout << "Encryption key : " << key.to_string() << endl;
  cout << "IV : " << iv.to_string() << endl;

  ofstream ofs_file(output_file, std::ios::binary);


  ofs_file.write(iv.to_string().c_str(), 32);
  ofs_file.write(reinterpret_cast<const char *>(&salt[0]),
                 static_cast<std::streamsize>(salt.size()));
  cout << "Encrypting " << input_file << " to "  << output_file << endl;
  Botan::DataSource_Stream dss_file(input_file, true);
  Botan::Pipe pipe(get_cipher("AES-256/EAX", key, iv, Botan::ENCRYPTION),
                   new Botan::DataSink_Stream(ofs_file));

  pipe.process_msg(dss_file);
}
```

```
void decrypt_file(string input_file, string output_file, string passphrase) {
  ifstream ifs_file(input_file, std::ios::binary);

  vector<char> iv_buffer(32);

  ifs_file.read(&iv_buffer[0], 32);
  Botan::InitializationVector iv(&iv_buffer[0]);
  cout << "IV : " << iv.to_string() << endl;

  Botan::SecureVector<Botan::byte> salt_buffer(16);
  ifs_file.read(reinterpret_cast<char *>(&salt_buffer[0]), 16);
  Botan::SecureVector<Botan::byte> salt(salt_buffer);

  Botan::PBKDF *pbkdf     = Botan::get_pbkdf("PBKDF2(SHA-256)");
  Botan::SymmetricKey key = pbkdf->derive_key(32,
                                              passphrase,
                                              &salt[0],
                                              salt.size(),
                                              10000);

  cout << "Encryption key : " << key.to_string() << endl;

  Botan::DataSource_Stream dss_file(ifs_file);
  cout << "Decrypting " << input_file << " to " << output_file << endl;
  Botan::Pipe pipe(get_cipher("AES-256/EAX", key, iv, Botan::DECRYPTION),
                   new Botan::DataSink_Stream(output_file, true));

  pipe.process_msg(dss_file);
}
```
