### ISSUE TITLE
Issue: Data cannot be sent on inactive TLS | Certificate key type did not match ciphersuite

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#1934]
Hallo,

I have rewritten my Code. Here is my Code:
Quelle.cpp is the main function:
https://paste.ee/p/Na9Z0

I get an Error when I try to send it. My Server says:
Data cannot be sent on inactive TLS Connection

and botan-cli.exe tls_client myip --port=999 --type=udp throws following Error:
Error: Certificate key type did not match ciphersuite

return true or return false in Server::tls_session_established changed nothing.

Any tipp so I can continue my work :) ?

Thanks for help

**Comment by randombit** [comment]
I think the problem is here

```
		std::vector<Botan::X509_Certificate> cert_chain(const std::vector<std::string>& cert_key_types, const std::string& type, const std::string& context) override {
			return this->certChain;
		}
```

You ignore cert_key_types. So the tls server ends up selecting a ciphersuite that it thinks it has a certificate for, but then ends up sending a mismatch. Eg it negotiates ECDH_ECDSA_x but sends an RSA certificate.

There should be a check in the server to catch this kind of error.

**Comment by seppy87** [comment]
I have changed the cert_chain foo to 

```
std::vector<Botan::X509_Certificate> cert_chain(const std::vector<std::string>& cert_key_types, const std::string& type, const std::string& context) override {
			std::cout << "Type=" << type << '\n';
			std::cout << "Context=" << context << '\n';
			for (auto s : cert_key_types) {
				std::cout << "Key Type=" << s << '\n';
			}
			return this->certChain;
		}

```
The Results are:

> Type=tls-server
Context=
Key Type=RSA
Type=tls-server
Context=
Key Type=DSA
Type=tls-server
Context=
Key Type=ECDSA
Type=tls-server

I have generated the key and cert with botan-cli.exe 
key with botan-cli.exe keygen and the cert with
botan-cli.exe gen_self_signed private.key CN --country=DE

**Comment by randombit** [comment]
OK, so in that case have your callback return the cert chain only if asked for an RSA cert. For ECDSA/DSA, return an empty vector.

**Comment by seppy87** [comment]
Ok I have done it but it seems the client can't establish a trust :O

> c:\python\python-3.6.7.amd64>botan-cli.exe tls_client 192.168.1.119 --port=999 --type=udp --skip-system-cert-store
Certificate validation status: Cannot establish trust
Socket error: 0 No error
Socket error: 0 No error
Socket error: 0 No error
Socket error: 0 No error
Timeout detected

**Comment by randombit** [comment]
> Certificate validation status: Cannot establish trust

Would you ordinarily expect a TLS client to accept random self-signed certificates?

Generate a self-signed CA which then issues a server cert. Then trust your new CA.

Or, over override `tls_verify_cert_chain` to be a no-op. Don't forget to remove that before you deploy your code, though ... unless you want to accept random self-signed certs in prod.

**Comment by seppy87** [comment]
OK I made a CA and signed it.
botan-cli says

> botan-cli.exe tls_client 192.168.1.119 --port=999 --type=udp --trusted-cas=c:\rsakeys\ca.crt --print-certs
Certificate validation status: Verified
Timeout detected
Timeout detected
Timeout detected

and my server says:
Data cannot be sent on inactive TLS Connection
Still refuses to send :/

**Comment by randombit** [comment]
Based on latter comments it sounds like you got this issue resolved, feel free to reopen if still seeing problems.
