### ISSUE TITLE
Question about DSA_PrivateKey() generator (Qt IDE)

### ISSUE THREAD

**Issue by BadPistol97** [randombit/botan#1946]
#include <QCoreApplication>
    #include <botan/pubkey.h>
    #include <botan/dl_group.h>
    #include <botan/dsa.h>
    #include <iostream>
    using std::cout;
    using std::endl;  

    int main(int argc, char *argv[])
    {
        QCoreApplication a(argc, argv);
        std::unique_ptr<Botan::RandomNumberGenerator> random(new Botan::System_RNG);
        std::unique_ptr<Botan::DL_Group> group(new 
        Botan::DL_Group(*random.get(), Botan::DL_Group::Strong,1024));
        cout << endl << "ANSI_X9_42:" << endl << group->PEM_encode(Botan::DL_Group::ANSI_X9_42);
        
        // Not sure how to pass DL_Group object by reference here
        std::unique_ptr<Botan::DSA_PrivateKey> aKey(*random.get(),*group.get(),0);
        
      return a.exec();
        
     }

This is the code I have written in Qt. I wanted to create a DSA private key with DL_Group but the compiler is complaining no matching constructor.

Although the I found the function declaration in the documentation: 
_DSA_PrivateKey::DSA_PrivateKey(RandomNumberGenerator &rng, const DL_Group &group, constBigInt &x = 0)_

I'm still confused about how to pass the group object as a parameter. I try the same way passing RNG object using .get() function but it doesn't seem to work on DL_Group object. I am new to botan, I need help from you. Thanks in advance.

**Comment by randombit** [comment]
>     std::unique_ptr<Botan::DSA_PrivateKey> aKey(*random.get(),*group.get(),0);

You are try to initialize a unique_ptr with multiple arguments, I can understand how that seems like it should work, I missed it at first. Try

>     std::unique_ptr<Botan::DSA_PrivateKey> aKey(new Botan::DSA_PrivateKey(*random,*group));

Don't pass an explicit zero to generate a new key, it is the default arg anyway. And in the future likely the constructor will be split into two versions one taking the private key the other always generating.

PS DSA is both obsolete and slow; with 1024 bit params it is not too secure, and with secure (2048+ bit) params it is slower than ECDSA. Unless you have some external requirement for DSA seriously consider ECDSA or RSA instead.

**Comment by randombit** [comment]
Oh just noticed this 

>  Botan::DL_Group(*random.get(), Botan::DL_Group::Strong,1024));

That kind of group does not work for DSA. You want `DSA_Kosherizer`

**Comment by BadPistol97** [comment]
Thank you very much for your help. Now I try to create a ECDSA private key. I have problem understanding the EC_Group constructor now. I have found an example online which is:  
_Botan::EC_Group ecgroup("brainpool512r1");_

It works but it looks so different in the header file: 
`      
               EC_Group(const BigInt& p,
                const BigInt& a,
               const BigInt& b,
               const BigInt& base_x,
               const BigInt& base_y,
               const BigInt& order,
               const BigInt& cofactor,
               const OID& oid = OID( ));
               `

I don't understand why is this. Could you please help me with this?

**Comment by randombit** [comment]
That class several different constructors. The one you mention allows creating curves that are not builtin to the library. This is for rare and unusual situations only. Another constructor takes a string which allows specifying a curve name such as "secp256r1" or "brainpool512r1". In almost all situations that is the constructor you want.

secp256r1 is fast and widely accepted as secure so unless you have something specific in mind just use that.

**Comment by BadPistol97** [comment]
Alright, thank you very much.
