### ISSUE TITLE
Undefined reference to 'std::thread::_State::~_State() ' in rsa.cpp and thread_pool.cpp

### ISSUE THREAD

**Issue by BadPistol97** [randombit/botan#1947]
I created an ECDSA Private Key and I was making sure the key is working by invoking a function, _std::string PKCS8::PEM_encode(const Private_Key &key)_

But the compiler complained about the undefined reference to **std::thread::_State::~_State()** 
both in **rsa.cpp** and **thread_pool.cpp**. This happens too when I try to create a RSA Private Key but the compiler complains only the **rsa.cpp** .

Error shows like this: 
![image](https://user-images.githubusercontent.com/42179618/57636169-36d92980-75db-11e9-927e-ed6627502346.png)

Code: 

    #include <QCoreApplication>
    #include <botan/pubkey.h>
    #include <botan/ec_group.h>
    #include <botan/ecdsa.h>
    #include <iostream>
    #include <botan/pkcs8.h>
    #include <string.h>
    using std::cout;
    using std::endl;

    int main(int argc, char *argv[])
    {
        QCoreApplication a(argc, argv);

        std::unique_ptr<Botan::RandomNumberGenerator> random(new Botan::System_RNG);
         
        std::unique_ptr<Botan::EC_Group> group(new Botan::EC_Group("secp256r1"));

        std::unique_ptr<Botan::ECDSA_PrivateKey> aKey(new Botan::ECDSA_PrivateKey(*random,*group));
        
        std::string encoded;
    
         // this line caused the error.
        encoded = Botan::PKCS8::PEM_encode(*aKey);    
    
            return a.exec();
    }

**Comment by randombit** [comment]
Botan uses threads internally, you may have to add `-pthread` to gcc command line.

**Comment by BadPistol97** [comment]
I was using running this using Qt MinGW compiler but the library was not built using Qt own compiler. So I re-built the botan library and the code above works. Thanks
