### ISSUE TITLE
Should I use a RSA private key to encrypt a text or json file? 

### ISSUE THREAD

**Issue by BadPistol97** [randombit/botan#1952]
I am trying to encrypt a file containing data most probably in json format. My question is, is it suitable to use RSA private key to encrypt a file?

But when I create an encryptor, like this
`std::unique_ptr<Botan::PK_Encryptor_EME> encryptor(new Botan::PK_Encryptor_EME(*pubRSA,*random,"EME1(SHA-256)"));`

the maximum input size is just 62 bytes, I might need to compress a file that is more than 62 bytes even after compressing. 

Any alternative? Thank you

**Comment by randombit** [comment]
Usually RSA is only used to encrypt a short session key, then the data is encrypted using an AEAD mode like AES-256/GCM. For an example of this see https://github.com/randombit/botan/blob/master/src/cli/pk_crypt.cpp

**Comment by BadPistol97** [comment]
Okay. Now I am able to encrypt data from a text file with AEAD mode like this:

    
    #include <botan/rng.h>
    #include <botan/auto_rng.h>
    #include <botan/cipher_mode.h>
    #include <botan/hex.h>
    #include <iostream>
    #include <botan/aead.h>
    #include <fstream>
    #include <algorithm>
    int main()
    {
       Botan::AutoSeeded_RNG rng;

       std::ifstream read("botan.txt");

       std::string plaintext, x;

       if(read){

         while(read >> x)
            plaintext += x;

        read.close();

       }

        const std::vector<uint8_t> key = 
    Botan::hex_decode("76b3cc69f8f767dfae3985b5f8710f1943a1fa737896a3aa4f8ed7ae27147f0c");

       std::unique_ptr<Botan::AEAD_Mode> enc = Botan::AEAD_Mode::create("AES-256/GCM", 
    Botan::ENCRYPTION);

       enc->set_key(key);

       //generate fresh nonce (IV)
       Botan::secure_vector<uint8_t> iv = rng.random_vec(enc->default_nonce_length());

       // Copy input data to a buffer that will be encrypted
       Botan::secure_vector<uint8_t> pt(plaintext.data(), plaintext.data()+plaintext.length());


       enc->start(iv);
       enc->finish(pt);

        for(auto&& x : pt)
        std::cout << x << " ";

       return 0;
       }

But how to decrypt the encrypted secure_vector? I can't find the documentation for AEAD decryption. 
And it is a bad practice that I use website like https://www.browserling.com/tools/random-hex to generate a key for AEAD mode?

**Comment by randombit** [comment]
> But how to decrypt the encrypted secure_vector?

Exactly like encryption, except instead of generating a new nonce, use the one you generated during encryption, and pass `DECRYPTION` to `AEAD_Mode::create`.

> And it is a bad practice that I use website like https://www.browserling.com/tools/random-hex to generate a key for AEAD mode?

Um, yes? That is why there are cryptographically secure random number generators included in the library. `auto key = Botan::system_rng().random_vec(32);`

**Comment by randombit** [comment]
If you have further questions or problems feel free to open a new issue
