### ISSUE TITLE
RSA encryption key size restriction

### ISSUE THREAD

**Issue by florianthonig** [randombit/botan#1953]
Hey,
I want to use botan with extremely small RSA keys.
But unfortunately there is an assertion checking for min 384 bits.
The assertion was added here: b1e1e618eac3ca317414a57269b1b4b28cc10098
Could this be removed or is there a point I'm missing?

**Comment by randombit** [comment]
I assume you know that such tiny keys can be trivially broken. But, that restriction was just there to make Coverity happy that the subtraction didn't underflow, 384 bits was an arbitrary cutoff. I just changed it to 5 bits since that's the smallest mathematically possible RSA key.
