### ISSUE TITLE
Botan Private_Key/RSA_Private Progress Callback?

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#1965]
Hallo, I am trying to automate my Certificate Creation with a GUI (Qt).

can I setup a Callback when I create a RSA_PrivateKey? So I can Implement a "Please Wait, Key will be created. Including a Progressbar?

Greetings

**Comment by reneme** [comment]
Botan doesn't provide this out of the box and (technically) it does not really make sense either. The RSA key generation is a random process and can take anything from milliseconds to minutes (if you are really unlucky).

However, we had the same UX issue in our application and came up with a "solution" that proved to be good enough. Coincidentally we even have a [blog post](https://medium.com/nexenio/indicating-progress-of-rsa-key-pair-generation-the-practical-approach-a049ba829dbe) about that.

**Comment by randombit** [comment]
There used to be (a very long time ago) such a callback, but it didn't work well for the reason reneme mentions that RSA keygen times can be highly variable. You could tell something was happening but it is not possible to translate that to a % complete.

The CDF approach neXenio did seems pretty nice. Alternately, spawn keygen in a worker thread and have the UI do just a spinning animation to indicate to user "I'm still alive" without attaching a time estimate to it.

Another thing you could do: once the user enters the pane where they are entering the details of the certificate, immediately spawn a thread to generate the key in the background. By the time they have finished entering the details, the key is generated and no wait time.

**Comment by seppy87** [comment]
I will probably do what randombit suggested. I was worried that the user for the Certificate Manager will abort the generation with the Task Manager (he is Windows user) and report as a Bug. But RandomBit's approach would show at least that the Programm is still running and not frozen.

One Question about SSL in General:
The root CA:
Issuer = Subject DN

and the Server/client CA:
issuer = CA
Subject = Server/Client

Can there be Sub-CAs?
For my DTLS client. As Logging purpose. So I can determine who granted access to server, in case of need.

As Example
First logging with Subject DN
CN: Maximilian Nobody
Locality: Paris
etc...
Signer was Sub-CA CN: John Doe's CA.

**Comment by randombit** [comment]
Yes intermediate CAs are quite common and well supported. The root CA issues a CA cert (has basicConstraints is_CA=true) which in turn can issue end entity certs. This is also useful because it means that most of the time you can keep the root CA offline in cold storage.

**Comment by randombit** [comment]
Should document this issue and suggest solutions.
