### ISSUE TITLE
Can we make fs.h an internal header?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#198]
For some reason `fs.h` is a public header, which just contains

```
list_all_readable_files_in_or_under(const std::string& dir);
```

I don't think it is Botan's job to provide (poor) filesystem functionality to the user.

Given that we now have access to internal headers from tests as well (87ba413), I'd like to remove `fs.h` from the public interface. Is that okay?

**Comment by randombit** [comment]
Sounds good to me, this was only exposed for the tests.

**Comment by webmaster128** [comment]
Great. So it can also be moved out of the lib entirely into src/test? Then people don't have it in their amalgamation file and libraries.

**Comment by webmaster128** [comment]
Okay I just saw that `fs.h` is used in `Certificate_Store_In_Memory(const std::string& dir);`, which is then not very reliable due to missing error reporting. Anyways, I'll leave it in the lib for now, make it internal and ensure that you can differentiate between no FS access available and no file found in dir.
