### ISSUE TITLE
ffi.h: Wrong documentation

### ISSUE THREAD

**Issue by Thermi** [randombit/botan#1984]
The documentation states the following:
```
/**
* Initialize a random number generator object
* @param rng rng object
* @param rng_type type of the rng, possible values:
*    "system": System_RNG, "user": AutoSeeded_RNG
* Set rng_type to null or empty string to let the library choose
*/
BOTAN_PUBLIC_API(2,0) int botan_rng_init(botan_rng_t* rng, const char* rng_type);
```

However, calling botan_rng_init with rng_type being "" (empty string) makes the library return an error. Using "system" or "user" works fine though.

**Comment by randombit** [comment]
You're right thanks. A null pointer works here, but empty string is rejected.
