### ISSUE TITLE
Cannot build Botan: undefined reference to 'Botan::CPUID::state()'

### ISSUE THREAD

**Issue by PerraJ60** [randombit/botan#1993]
Has anybody experienced this? I am trying to build Botan (version 2.10.0)  in Windows 10, with mingw32, don't know if I use the correct flags. This is what I use: 

configure.py --prefix=$BUILD_DIR --with-external- includedir=$OPENSSL_PREFIX/include --with-external-libdir=$OPENSSL_PREFIX/lib --os=mingw --cpu=i386 --minimized-build --enable- modules=rsa,dsa,ecdsa,ed25519,hmac,hmac_drbg,mode_pad,bigint,filters,block,auto_rng,x509,cbc,dh --with-openssl
		
Very thankful for any help with this

**Comment by randombit** [comment]
I have never seen a problem like this before. Your build flags seem ok. To confirm, you see this while building the library? If you were building an application that had previously been built against 2.9 I would suspect a header/lib mismatch since `CPUID::state()` fn was only added in 2.10.0, so you would see an error like this if building against 2.10 headers but linking against something older. Maybe run `nm -C build/obj/lib/utils_cpuid.o` you should see something like

```
0000000000000000 b guard variable for Botan::CPUID::state()::g_cpuid
0000000000000050 T Botan::CPUID::state()
0000000000000008 b Botan::CPUID::state()::g_cpuid
```

**Comment by PerraJ60** [comment]
Thank you very much for your answer.
I know the previous version (2.9.0) at least builds correctly, using those flags. Why I decided to test the newer version was another problem that is well described here: https://stackoverflow.com/questions/943488/what-does-this-error-mean-in-the-botan-crypto-library
So, that "PRNG not seeded" is my real problem. Changing to next version is not necessarily needed. 
(I could make this as a separate thread here.)
However I tried running your command, looks like this:

`$ nm -C utils_cpuid.o

00000000 b .bss
00000000 d .data
00000000 r .eh_frame
00000000 r .eh_frame$_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_realloc_insertIJS5_EEEvN9__gnu_cxx17__normal_iteratorIPS5_S7_EEDpOT_
00000000 d .gcc_except_table
00000000 r .rdata
00000000 r .rdata$zzz
00000000 t .text
00000000 t .text$_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_realloc_insertIJS5_EEEvN9__gnu_cxx17__normal_iteratorIPS5_S7_EEDpOT_
         U _Unwind_Resume
         U Botan::string_join(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, char)
         U Botan::CPUID::CPUID_Data::detect_cpu_features(unsigned int*)
000001e0 T Botan::CPUID::CPUID_Data::runtime_check_endian()
000001a0 T Botan::CPUID::CPUID_Data::CPUID_Data()
000001a0 T Botan::CPUID::CPUID_Data::CPUID_Data()
000000f0 T Botan::CPUID::initialize()
00000070 T Botan::CPUID::has_simd_32()
000001f0 T Botan::CPUID::bit_from_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
00001670 T Botan::CPUID::print(std::ostream&)
00000000 T Botan::CPUID::state()
00000540 T Botan::CPUID::to_string[abi:cxx11]()
         U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const
00000000 T void std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_realloc_insert<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
         U std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)
         U operator delete(void*)
         U operator new(unsigned int)
         U __emutls_get_address
00000010 d __emutls_v._ZGVZN5Botan5CPUID5stateEvE7g_cpuid
00000000 d __emutls_v._ZZN5Botan5CPUID5stateEvE7g_cpuid
         U __gxx_personality_v0
         U __stack_chk_fail
         U __stack_chk_guard`

**Comment by PerraJ60** [comment]
Sorry, closed this thread by mistake, now open again :-)

**Comment by randombit** [comment]
OK for the seeding issue, I see now that you did not enable any entropy sources. The most reliable is probably `system_rng`; adding that to your 2.9 build should resolve that.

The `nm` output looks ok, and clearly includes the `CPUID::state()` function so it's really not clear what the problem might be. A shot in the dark: maybe there is some problem with thread local storage on MinGW. Try adding `--without-os-feature=threads`

**Comment by PerraJ60** [comment]
Thank you again, but I DO include auto_rng, is not that an entropy source?
But I followed your advice, added system_rng like this:
 
`configure.py --prefix=$BUILD_DIR --with-external-includedir=$OPENSSL_PREFIX/include --with-external-libdir=$OPENSSL_PREFIX/lib --os=mingw --cpu=i386 --minimized-build --enable-modules=rsa,dsa,ecdsa,ed25519,hmac,hmac_drbg,mode_pad,bigint,filters,block,auto_rng,system_rng,x509,cbc,dh --with-openssl`

But now this happens (with version 2.9.0 as well as 2.10.0):

```
build/obj/cli/speed.o:speed.cpp:(.text$_ZN9Botan_CLI5Speed2goEv[__ZN9Botan_CLI5Speed2goEv]+0x30d2): undefined reference to `Botan::system_rng()'
build/obj/cli/timing_tests.o:timing_tests.cpp:(.text+0x472): undefined reference to `Botan::system_rng()'
build/obj/cli/timing_tests.o:timing_tests.cpp:(.text+0x999): undefined reference to `Botan::system_rng()'
build/obj/cli/timing_tests.o:timing_tests.cpp:(.text+0x1415): undefined reference to `Botan::system_rng()'
build/obj/cli/timing_tests.o:timing_tests.cpp:(.text+0x180d): undefined reference to `Botan::system_rng()'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:68: botan.exe] Fel 1
```
 
However, look at the characters around Botan::system_rng(), they should be the same (???), now we have ` and '

**Comment by randombit** [comment]
> Thank you again, but I DO include auto_rng, is not that an entropy source?

No, `auto_rng` is a random number generator, which itself requires some source of entropy for seeding material. All such entropy sources are system specific since there is no portable way of getting random or unpredictable data.

It is interesting that system_rng is, like CPUID::state, a function which returns a reference to a static data. However unlike CPUID::state the data is not thread local, which seems to rule out a problem with thread support.

The `' quoting is just how gcc displays missing symbols and I don't think is related.

Another thing to try: build using `--amalgamation`.

What version of GCC are you using?

**Comment by PerraJ60** [comment]
```
$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 7.4.0
```
(not the newest one, I see! Strange, I have a very fresh install here on a brand new machine...)
I've read about that amalgation, quite interesting...

**Comment by PerraJ60** [comment]
```
$ gcc --version
gcc.exe (Rev1, Built by MSYS2 project) 7.4.0
```
(not the newest one, I see! Strange, I have a very fresh install here on a brand new machine...)
I've read about that amalgation, quite interesting...

**Comment by PerraJ60** [comment]
Upgrade now to gcc version 9.1.0, new try...

**Comment by PerraJ60** [comment]
No success after upgrading versions and also trying `--amalgation`  Also tried using win32_stat as a entropy source, didn't help at all, running the Qt application issues the same error as from the beginning:

```
terminate called after throwing an instance of 'Botan::PRNG_Unseeded'
  what():  PRNG not seeded: HMAC_DRBG(HMAC(SHA-384))
```

**Comment by randombit** [comment]
Re win32_stats it looks like you hit kind of a corner case with that. The Win32 stats is set to only return at most 128 bits of (estimated) entropy output, but a HMAC_DRBG with SHA-384 wants at least 384 bits of seed material. Normally the system RNG is the main source, the stats calls are mostly there as a last resort in case RtlGenRandom has a serious bug. Try editing es_win32.cpp and change POLL_TARGET (near top of function) from 128 to 384 and see if that makes a difference.

At this point I'm pretty baffled by this build problem though. Just for completeness can you try a) a build with no special options, just `configure.py && make` b) posting also `nm -C` output for `rng_system_rng.o`

**Comment by PerraJ60** [comment]
Thanks again! Interesting! 
That will be Friday's first task, since we have holiday tomorrow... I'll tell you! :-)

**Comment by PerraJ60** [comment]
Hi again!
That file you mention, `rng_system_rng.o`, or just `system_rng.o`  does not exist, never built.
Include paths look a bit strange to me:
#include <botan/internal/es_win32.h> from the cpp file where I am, that path doesn't exist, but I assume you are taking care of that in Config.py?
Can there be a race condition? I mean objects asked for before they are there?
I also tested a "blank" build, ( I took away the whole --enable-modules ) part, still no success, exactly the same error... :-\

**Comment by randombit** [comment]
> That file you mention, rng_system_rng.o, or just system_rng.o (or any *.o file containing "system") does not exist, never built.

Well, I guess that would explain why the symbol is not found ... but that seems pretty strange. If you look in the makefile, do you see the rules to generate the object file?

**Comment by PerraJ60** [comment]
You mean:
```
# Object Files
LIBOBJS=
``` ?
`rng_system_rng.o` is not mentioned here

**Comment by PerraJ60** [comment]
```
# Paths to relevant programs

CXX            = g++
LINKER         = $(CXX)
AR             = ar
AR_OPTIONS     = crs
PYTHON_EXE     = python.exe

# Compiler Flags

ABI_FLAGS      =  -fstack-protector -pthread
LANG_FLAGS     = -std=c++11 -D_REENTRANT
CXXFLAGS       = -O3 -momit-leaf-frame-pointer
WARN_FLAGS     = -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor
SO_OBJ_FLAGS   = 
LDFLAGS        = 

EXE_LINK_CMD   = $(LINKER) -LC:/Users/xxx/source/xxxxxxx/third-party-build-release/lib
POST_LINK_CMD  = 

LIB_LINKS_TO   = -lcrypto
EXE_LINKS_TO   = -L. -lbotan-2 $(LIB_LINKS_TO)

BUILD_FLAGS    = $(ABI_FLAGS) $(LANG_FLAGS) $(CXXFLAGS) $(WARN_FLAGS)

SCRIPTS_DIR    = ../src/scripts
INSTALLED_LIB_DIR = C:/Users/xxx/source/xxxxxxxxxxx/third-party-build-release/lib

# The primary target
all: libs cli tests docs

# Executable targets
CLI           = botan.exe
TEST          = botan-test.exe
LIBRARIES     = libbotan-2.a

cli: $(CLI)
tests: $(TEST)
libs: $(LIBRARIES)
docs: build/doc.stamp

# Misc targets

.PHONY = all cli libs tests docs clean distclean install

build/doc.stamp: ../doc/manual/*.rst
	$(PYTHON_EXE) $(SCRIPTS_DIR)/build_docs.py --build-dir="build"

clean:
	$(PYTHON_EXE) $(SCRIPTS_DIR)/cleanup.py --build-dir="build"

distclean:
	$(PYTHON_EXE) $(SCRIPTS_DIR)/cleanup.py --build-dir="build" --distclean

install: libs cli docs
	$(PYTHON_EXE) $(SCRIPTS_DIR)/install.py --prefix="C:/Users/xxx/source/xxxxxxxxxxxx/third-party-build-release" --build-dir="build" --bindir=bin --libdir=lib --docdir=share/doc --includedir=include
```

**Comment by randombit** [comment]
But you are sure `system_rng` is enabled in the build?? This is getting stranger and stranger. Can you exact configure invocation, output and also the complete generated Makefile?

**Comment by PerraJ60** [comment]
Yes. I tested also version 2.10, and the unreleased 2.11. In both these the `rng_system_rng.o` files are generated! I can give nm -C output for the 2.10 one

**Comment by PerraJ60** [comment]
```
$ nm -C rng_system_rng.o
00000000 b .bss
00000000 d .data
00000000 r .eh_frame
00000000 r .eh_frame$_ZN5Botan12System_ErrorD0Ev
00000000 r .eh_frame$_ZN5Botan12System_ErrorD1Ev
00000000 r .eh_frame$_ZN5Botan9ExceptionD0Ev
00000000 r .eh_frame$_ZN5Botan9ExceptionD1Ev
00000000 r .eh_frame$_ZNK5Botan12System_Error10error_codeEv
00000000 r .eh_frame$_ZNK5Botan12System_Error10error_typeEv
00000000 r .eh_frame$_ZNK5Botan9Exception10error_codeEv
00000000 r .eh_frame$_ZNK5Botan9Exception10error_typeEv
00000000 r .eh_frame$_ZNK5Botan9Exception4whatEv
00000000 d .gcc_except_table
00000000 r .rdata
00000000 r .rdata$_ZTIN5Botan12System_ErrorE
00000000 r .rdata$_ZTIN5Botan21RandomNumberGeneratorE
00000000 r .rdata$_ZTIN5Botan9ExceptionE
00000000 r .rdata$_ZTISt9exception
00000000 r .rdata$_ZTSN5Botan12System_ErrorE
00000000 r .rdata$_ZTSN5Botan21RandomNumberGeneratorE
00000000 r .rdata$_ZTSN5Botan9ExceptionE
00000000 r .rdata$_ZTSSt9exception
00000000 r .rdata$_ZTVN5Botan12System_ErrorE
00000000 r .rdata$_ZTVN5Botan9ExceptionE
00000000 r .rdata$zzz
00000000 t .text
00000000 t .text$_ZN5Botan12System_ErrorD0Ev
00000000 t .text$_ZN5Botan12System_ErrorD1Ev
00000000 t .text$_ZN5Botan9ExceptionD0Ev
00000000 t .text$_ZN5Botan9ExceptionD1Ev
00000000 t .text$_ZNK5Botan12System_Error10error_codeEv
00000000 t .text$_ZNK5Botan12System_Error10error_typeEv
00000000 t .text$_ZNK5Botan9Exception10error_codeEv
00000000 t .text$_ZNK5Botan9Exception10error_typeEv
00000000 t .text$_ZNK5Botan9Exception4whatEv
00000000 t .text.unlikely
         U _Unwind_Resume
00000000 b guard variable for Botan::system_rng()::g_system_rng
00000120 T Botan::system_rng()
000000c8 t Botan::system_rng() [clone .cold]
00000000 T Botan::System_Error::~System_Error()
00000000 T Botan::System_Error::~System_Error()
00000000 t Botan::(anonymous namespace)::System_RNG_Impl::add_entropy(unsigned char const*, unsigned int)
00000030 t Botan::(anonymous namespace)::System_RNG_Impl::clear()
000000d0 t Botan::(anonymous namespace)::System_RNG_Impl::randomize(unsigned char*, unsigned int)
00000000 t Botan::(anonymous namespace)::System_RNG_Impl::randomize(unsigned char*, unsigned int) [clone .cold]
00000070 t Botan::(anonymous namespace)::System_RNG_Impl::~System_RNG_Impl()
00000040 t Botan::(anonymous namespace)::System_RNG_Impl::~System_RNG_Impl()
00000040 t Botan::(anonymous namespace)::System_RNG_Impl::~System_RNG_Impl()
         U Botan::RandomNumberGenerator::reseed_from_rng(Botan::RandomNumberGenerator&, unsigned int)
         U Botan::RandomNumberGenerator::randomize_with_input(unsigned char*, unsigned int, unsigned char const*, unsigned int)
         U Botan::RandomNumberGenerator::randomize_with_ts_input(unsigned char*, unsigned int)
         U Botan::RandomNumberGenerator::reseed(Botan::Entropy_Sources&, unsigned int, std::chrono::duration<long long, std::ratio<1ll, 1000ll> >)
         U Botan::Dynamically_Loaded_Library::resolve_symbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
         U Botan::Dynamically_Loaded_Library::Dynamically_Loaded_Library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
         U Botan::Dynamically_Loaded_Library::~Dynamically_Loaded_Library()
         U Botan::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
00000000 T Botan::Exception::~Exception()
00000000 T Botan::Exception::~Exception()
00000000 T Botan::System_Error::error_code() const
00000000 T Botan::System_Error::error_type() const
00000020 t Botan::(anonymous namespace)::System_RNG_Impl::accepts_input() const
000000a0 t Botan::(anonymous namespace)::System_RNG_Impl::name() const
00000010 t Botan::(anonymous namespace)::System_RNG_Impl::is_seeded() const
00000000 T Botan::Exception::error_code() const
00000000 T Botan::Exception::error_type() const
00000000 T Botan::Exception::what() const
         U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned int&, unsigned int)
         U std::exception::~exception()
00000000 R typeinfo for Botan::System_Error
00000014 r typeinfo for Botan::(anonymous namespace)::System_RNG_Impl
00000000 R typeinfo for Botan::RandomNumberGenerator
00000000 R typeinfo for Botan::Exception
00000000 R typeinfo for std::exception
00000000 R typeinfo name for Botan::System_Error
00000020 r typeinfo name for Botan::(anonymous namespace)::System_RNG_Impl
00000000 R typeinfo name for Botan::RandomNumberGenerator
00000000 R typeinfo name for Botan::Exception
00000000 R typeinfo name for std::exception
         U vtable for __cxxabiv1::__class_type_info
         U vtable for __cxxabiv1::__si_class_type_info
00000000 R vtable for Botan::System_Error
0000004c r vtable for Botan::(anonymous namespace)::System_RNG_Impl
00000000 R vtable for Botan::Exception
00000020 b Botan::system_rng()::g_system_rng
         U operator delete(void*)
         U __cxa_allocate_exception
         U __cxa_free_exception
         U __cxa_guard_abort
         U __cxa_guard_acquire
         U __cxa_guard_release
         U __cxa_throw
         U __gxx_personality_v0
         U __stack_chk_fail
         U __stack_chk_guard
00000050 t __tcf_0
         U atexit
```

**Comment by PerraJ60** [comment]
This is confusing, agreed! Now, actually, I got the files also from the 2.9.0 version, but I do not know why it shows up now! This is 2.9.0:

```
$ nm -C rng_system_rng.o
00000000 b .bss
00000000 d .data
00000000 r .eh_frame
00000000 r .eh_frame$_ZN5Botan12System_ErrorD0Ev
00000000 r .eh_frame$_ZN5Botan12System_ErrorD1Ev
00000000 r .eh_frame$_ZN5Botan9ExceptionD0Ev
00000000 r .eh_frame$_ZN5Botan9ExceptionD1Ev
00000000 r .eh_frame$_ZNK5Botan12System_Error10error_codeEv
00000000 r .eh_frame$_ZNK5Botan12System_Error10error_typeEv
00000000 r .eh_frame$_ZNK5Botan9Exception10error_codeEv
00000000 r .eh_frame$_ZNK5Botan9Exception10error_typeEv
00000000 r .eh_frame$_ZNK5Botan9Exception4whatEv
00000000 d .gcc_except_table
00000000 r .rdata
00000000 r .rdata$_ZTIN5Botan12System_ErrorE
00000000 r .rdata$_ZTIN5Botan21RandomNumberGeneratorE
00000000 r .rdata$_ZTIN5Botan9ExceptionE
00000000 r .rdata$_ZTISt9exception
00000000 r .rdata$_ZTSN5Botan12System_ErrorE
00000000 r .rdata$_ZTSN5Botan21RandomNumberGeneratorE
00000000 r .rdata$_ZTSN5Botan9ExceptionE
00000000 r .rdata$_ZTSSt9exception
00000000 r .rdata$_ZTVN5Botan12System_ErrorE
00000000 r .rdata$_ZTVN5Botan9ExceptionE
00000000 r .rdata$zzz
00000000 t .text
00000000 t .text$_ZN5Botan12System_ErrorD0Ev
00000000 t .text$_ZN5Botan12System_ErrorD1Ev
00000000 t .text$_ZN5Botan9ExceptionD0Ev
00000000 t .text$_ZN5Botan9ExceptionD1Ev
00000000 t .text$_ZNK5Botan12System_Error10error_codeEv
00000000 t .text$_ZNK5Botan12System_Error10error_typeEv
00000000 t .text$_ZNK5Botan9Exception10error_codeEv
00000000 t .text$_ZNK5Botan9Exception10error_typeEv
00000000 t .text$_ZNK5Botan9Exception4whatEv
00000000 t .text.unlikely
         U _Unwind_Resume
00000000 b guard variable for Botan::system_rng()::g_system_rng
00000120 T Botan::system_rng()
000000c8 t Botan::system_rng() [clone .cold]
00000000 T Botan::System_Error::~System_Error()
00000000 T Botan::System_Error::~System_Error()
00000000 t Botan::(anonymous namespace)::System_RNG_Impl::add_entropy(unsigned char const*, unsigned int)
00000030 t Botan::(anonymous namespace)::System_RNG_Impl::clear()
000000d0 t Botan::(anonymous namespace)::System_RNG_Impl::randomize(unsigned char*, unsigned int)
00000000 t Botan::(anonymous namespace)::System_RNG_Impl::randomize(unsigned char*, unsigned int) [clone .cold]
00000070 t Botan::(anonymous namespace)::System_RNG_Impl::~System_RNG_Impl()
00000040 t Botan::(anonymous namespace)::System_RNG_Impl::~System_RNG_Impl()
00000040 t Botan::(anonymous namespace)::System_RNG_Impl::~System_RNG_Impl()
         U Botan::RandomNumberGenerator::reseed_from_rng(Botan::RandomNumberGenerator&, unsigned int)
         U Botan::RandomNumberGenerator::randomize_with_input(unsigned char*, unsigned int, unsigned char const*, unsigned int)
         U Botan::RandomNumberGenerator::randomize_with_ts_input(unsigned char*, unsigned int)
         U Botan::RandomNumberGenerator::reseed(Botan::Entropy_Sources&, unsigned int, std::chrono::duration<long long, std::ratio<1ll, 1000ll> >)
         U Botan::Dynamically_Loaded_Library::resolve_symbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
         U Botan::Dynamically_Loaded_Library::Dynamically_Loaded_Library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
         U Botan::Dynamically_Loaded_Library::~Dynamically_Loaded_Library()
         U Botan::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
00000000 T Botan::Exception::~Exception()
00000000 T Botan::Exception::~Exception()
00000000 T Botan::System_Error::error_code() const
00000000 T Botan::System_Error::error_type() const
00000020 t Botan::(anonymous namespace)::System_RNG_Impl::accepts_input() const
000000a0 t Botan::(anonymous namespace)::System_RNG_Impl::name() const
00000010 t Botan::(anonymous namespace)::System_RNG_Impl::is_seeded() const
00000000 T Botan::Exception::error_code() const
00000000 T Botan::Exception::error_type() const
00000000 T Botan::Exception::what() const
         U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned int&, unsigned int)
         U std::exception::~exception()
00000000 R typeinfo for Botan::System_Error
00000014 r typeinfo for Botan::(anonymous namespace)::System_RNG_Impl
00000000 R typeinfo for Botan::RandomNumberGenerator
00000000 R typeinfo for Botan::Exception
00000000 R typeinfo for std::exception
00000000 R typeinfo name for Botan::System_Error
00000020 r typeinfo name for Botan::(anonymous namespace)::System_RNG_Impl
00000000 R typeinfo name for Botan::RandomNumberGenerator
00000000 R typeinfo name for Botan::Exception
00000000 R typeinfo name for std::exception
         U vtable for __cxxabiv1::__class_type_info
         U vtable for __cxxabiv1::__si_class_type_info
00000000 R vtable for Botan::System_Error
0000004c r vtable for Botan::(anonymous namespace)::System_RNG_Impl
00000000 R vtable for Botan::Exception
00000020 b Botan::system_rng()::g_system_rng
         U operator delete(void*)
         U __cxa_allocate_exception
         U __cxa_free_exception
         U __cxa_guard_abort
         U __cxa_guard_acquire
         U __cxa_guard_release
         U __cxa_throw
         U __gxx_personality_v0
         U __stack_chk_fail
         U __stack_chk_guard
00000050 t __tcf_0
         U atexit
```

**Comment by PerraJ60** [comment]
[Makefile.txt](https://github.com/randombit/botan/files/3266346/Makefile.txt)

**Comment by PerraJ60** [comment]
I sent you the makefile above (had to set a *.txt extension)
Sending more files soon.

**Comment by PerraJ60** [comment]
[build_output_botan_2_9_0.txt](https://github.com/randombit/botan/files/3266447/build_output_botan_2_9_0.txt)

**Comment by PerraJ60** [comment]
Something else has happened now, LOTS of `undefined reference`

**Comment by randombit** [comment]
Are you sure there is not some other libbotan-2.a elsewhere on your system, such as in `C:/Users/per/source/communicator/third-party-build-release/lib`? Since that appears first in the link line it will be used in preference to the lib that was just built.

**Comment by PerraJ60** [comment]
Yes! Indeed there is a libbotan-2.a in that exact path. That directory should be emptied before the build? (I have kept the files there to save time, since it takes forever to build everything! Will give it all a new try now.

**Comment by randombit** [comment]
> That directory should be emptied before the build?

Well, the result here is that you are building botan-test which is expecting symbols from version X, but then linking it against an older or differently configured library. So the problem initially manifested as CPUID::data being missing, because that symbol was added in 2.10, and botan-test was built against the headers for 2.10 so it expected that symbol to exist, but then in the end it was linked against a completely different library which didn't have it.

**Comment by PerraJ60** [comment]
Yes. 
It all builds now, using system_rng. Now I am having other problems with the Qt application using it, so I have not been able to perform the final test to confirm that seeding issue won't com up again..

**Comment by PerraJ60** [comment]
Confirmed now the seeding issue is solved. Thank you very much for great help on this. 
There is however still a problem, that MIGHT have to do with Botan-2.

`[preferences::sftpConnectionError] - SFTP: Connection error "SSH protocol error: Server and client capabilities don't match. Client list was: aes128-cbc,3des-cbc.\nServer list was aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com.`" 

It seems Botan-2 is involved in the QSSH functionality. Could I add another flag to the  configure.py string?

**Comment by randombit** [comment]
I don't know anything about QSSH but yeah looks like enabling ctr and/or gcm would help.

**Comment by PerraJ60** [comment]
gcm, thank you, will try that also! :-)

**Comment by randombit** [comment]
The issue as originally described seems to be resolved so I'm closing this. If you have issues specific to QSSH it would be best to open an issue with them since it's not code I'm familiar with. Obviously feel free to open new issues if you run into additional problems.
