### ISSUE TITLE
Strange behavior of PBKDF 

### ISSUE THREAD

**Issue by frzdan** [randombit/botan#1998]
Hey, Im currently developing a password manager for an university project and implemented Key derivation and AEAD via Botan. The implementation of the crypto features is in its own class, CryptoClass.
Im using Scrypt to derive two different Keys with two different salts from the login password and then use these to either authenticate or encrypt/decrypt another key. The implementation for both these Keys is in the same method, only the parameters change.
The call to the key derivation function comes from a button click in a login mask in Qt, delivering the password as QString, the two salts are hardcoded for now (testing purposes).
Now the strange behavior: When I load up the program and try the login, everything works as expected. Same Authkey and EncryptionKey as before get derived and everything works smoothly.
Now, when i logout (basically just resetting the CryptoClass flags and key entries) without closing the program and use the exact same input as before, I get different results. There are three different scenarios:
1. the derived enryption key is valid, while the auth is not (meaning it derived to another value)
2. the derived auth is valid, the encryption key is not (meaning it derived to another value)
3. both arent valid (most often)

I also tried creating a new instance of CryptoClass instead of resetting the old one, but same result.
Since I´m pretty new to c++ and especially Botan, it`s not unlikely it`s an implementation error on my side, even though I basically copy-pasted the Scrypt Derivation from the Botan tests.
Are there any other hidden dependencies for the PBKDF except password and salt? It seemed to me like giving different results based on the internal state of the CryptoClass, which I really can´t wrap my head around.
I even tried to old PBKDF class which explicitly states to derive the same key when given the same input, but still the same problem. Since my whole encryption scheme depends on this Key derivation feature Im hoping maybe someone else experienced something similar and Id be glad for some help.

Thanks in advance
Daniel

**Comment by randombit** [comment]
If the password, salt, and parameters are the same, then you should always get the same derived key. My guess is you are doing something that ends up overwriting the salt. The easy way to test this is print out the salt and params each time and see if anything changes. You can encode the salt to hex using `hex_encode` fn in botan/hex.h

You could also try something like `valgrind` or Dr. Memory which can detect many memory issues, like overwriting past one array into another. Those are useful tools to have anyway, during C++ development.

**Comment by frzdan** [comment]
You were correct, I unintentionally overwrote the salt somehow and it all went downhill from there :P
Fixed it now, sorry for the overreaction, should have taken a day off and investigate it again before opening up a thread.

Btw. really awesome library, apart from implementation mistakes on my side it´s running nicely and the test srcs are a really big help.
Thx for the quick reply, keep up the great work 👍
