### ISSUE TITLE
base64_decode error

### ISSUE THREAD

**Issue by SourcePowered** [randombit/botan#2004]
string base64 = ("Some BASE64 Code");
string str = Botan::hex_encode(Botan::base64_decode(base64.c_str(), static_cast<size_t>(base64.size())));

But the str is not right, What's wrong with me? Thank you very much.

**Comment by randombit** [comment]
I do not understand what you mean by "not right"?

**Comment by SourcePowered** [comment]
Sorry, my statement is incorrect. The result of the final decoding is incorrect.

**Comment by SourcePowered** [comment]
Or, secure_vector<uint8_t> how to convert to std::string?

**Comment by randombit** [comment]
> The result of the final decoding is incorrect.

What output did you get? What output did you expect? Why did you expect that output?

> secure_vector<uint8_t> how to convert to std::string?

std::string s(reinterpret_cast<const char*>(v.data()), v.size());

**Comment by SourcePowered** [comment]
Thank you very much. Everything is OK. That's the wrong conversion of my string format.
