### ISSUE TITLE
Use of __GNUG__ in header files

### ISSUE THREAD

**Issue by tobiasbrunner** [randombit/botan#2013]
The use of `__GNUG__` in header files is problematic because it won't be defined when compiling a C program against botan's FFI bindings. I noticed this in relation to the `BOTAN_DEPRECATED` macro, which only produces a warning if `__GNUG__` is defined, that is, I didn't get any when compiling with gcc. It works as expected when the check is changed to `#elif defined(__GNUC__)`.

So it might be a good idea to change at least some of these checks similarly (I can see others in `compiler.h` that don't rely on there being a C++ compiler).

**Comment by randombit** [comment]
Thanks for reporting this sometimes I forget that compiler.h is also consumed by C compilers
