### ISSUE TITLE
Botan and STL

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#2035]
Hallo,

I am always running into equal errors. In the past I just fixed them by rearranging the Header file Order until it worked. But huger the Project closer to impossibility it comes.

When I include a header which includes a Header from STL or the header includes another header which includes a STL Header. The compiler is throwing errors that tells me that syntax errors or chrono is not a class or namespace.

Now do I have to include the STLs before OR after Botan?

Windows 10 and MSVC 2019

Greetings

**Comment by seppy87** [comment]
OK, the solution was to #undef max and #undef min which are stupid macros in windows.h

**Comment by randombit** [comment]
Yeah you can use `#define NOMINMAX 1` before including a windows header to stop this. There is nothing we can do about this issue.
