### ISSUE TITLE
Cross compiling with mingw fails, problem with std::mutex type

### ISSUE THREAD

**Issue by kaie** [randombit/botan#2039]
I followed the build advice from doc/building.rst for cross compiling to Windows:
* ./configure.py --os=mingw --cpu=x86_32 --cc-bin=i686-w64-mingw32-g++ --ar-command=i686-w64-mingw32-ar
* make

This fails with:
```
In file included from src/lib/asn1/oids.cpp:9:
build/include/botan/mutex.h:19:14: error: ‘mutex’ in namespace ‘std’ does not name a type
 typedef std::mutex mutex_type;
              ^~~~~
```
I think the type is undefined, because in file std_mutex.h from mingw the definition of class mutex is wrapped inside #ifdef _GLIBCXX_HAS_GTHREADS. I checked, and it is undefined.

IIUC botan requires threading parts from glib which isn't available?

This is seen with mingw version 8.3.0 on debian buster.

**Comment by randombit** [comment]
Yeah I am not clear what the issue is wrt MinGW, seems like it should be trivial to support Win32 threading constructs for `std`. But in any case you can avoid the issue with `--without-os-feature=threads` of course in that case, make sure not to use the resulting lib in MT code since there are no locks ;)

I should update the docs here seems like this is a common issue.

**Comment by kaie** [comment]
You might also want to change --ar to --ar-command in the cross compile instructions.

**Comment by kaie** [comment]
Looking at this page, it seems the mingw distributions vary in the set of libraries they include. Apparently glib isn't included in the debian distribution.

Maybe I'd need to try the same on a fedora system.

**Comment by randombit** [comment]
Threads work fine for me using i686 MinGW on Arch, so it is definitely something about the distribution.

This Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757259 suggests there is some sort of post-install configuration that is required to get threads on MinGW.

**Comment by randombit** [comment]
The documentation has been improved to fix the option to set the AR command and also mentions the MinGW thread problem. As to the threads being missing in MinGW this seems to be a distribution specific issue so you'd probably have better luck opening an issue with them.
