### ISSUE TITLE
Current master fails one test in CI

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#2041]
Travis CI setup:
- Ubuntu 14.04.5 LTS "trusty"
- gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Configuration:
```
Running 'python3 ./configure.py --prefix=/tmp/botan-install --cc=gcc --os=linux --disable-static --with-bzip2 --with-sqlite --with-zlib --with-lzma --with-openssl --cc-bin=ccache g++ --no-store-vc-rev' ...
   INFO: ./configure.py invoked with options "--prefix=/tmp/botan-install --cc=gcc --os=linux --disable-static --with-bzip2 --with-sqlite --with-zlib --with-lzma --with-openssl --cc-bin=ccache g++ --no-store-vc-rev"
```

Error:
```
. . . . .
INFO: Running cli_tls_socket_tests
  ERROR: Test cli_tls_socket_tests threw exception: unsupported operand type(s) for %: 'bytes' and 'int'
. . . . .
```
Here are the failing CI builds: 

- https://travis-ci.org/mouse07410/botan/jobs/559715990
- https://travis-ci.org/mouse07410/botan/jobs/559715991

**Comment by randombit** [comment]
Confused on multiple fronts here

Your branch seems to be a copy of upstream, but it is using trusty instead of xenial. Why?

Why is this test failing for you but not in our CI?

**Comment by mouse07410** [comment]
> Why is this test failing for you but not in our CI?

I don't know.

> Your branch seems to be a copy of upstream, but it is using trusty instead of xenial. Why?

My mistake. I've remedied this, will report results.

**Comment by mouse07410** [comment]
CI build is still running, but the previous failures disappeared. Apologies for the noise, and thank you for pointing out the problem in my fork!
