### ISSUE TITLE
List of modules available

### ISSUE THREAD

**Issue by ghost** [randombit/botan#2044]
I'd like to enable minimized-build with enable-modules option, but I'm unable to find a list of modules which I can choose from. 

If there isn't one it would be helpful for others to decide what exact modules they need :)

**Comment by randombit** [comment]
You can get just a list with `./configure.py --list-modules`, or by looking at the output when configure.py runs which gives the modules which are/are not being loaded. But you are right some more documentation/guidance would be useful here.

**Comment by randombit** [comment]
A decent way to start is just `--minimized-build` and enable things you know you need. If your app fails to build, repeat.

**Comment by randombit** [comment]
One thing that commonly trips people up is that all of the entropy sources are optional, but if non are enabled then things don't work so well. Enabling `system_rng` is a decent start (works as both a RNG directly + an entropy source for userspace RNG).

**Comment by Unc3nZureD** [comment]
Yes, thank you, but without knowing what modules are available it was hard to check which ones I need :) That --list-modules is sounds quite useful.
