### ISSUE TITLE
Ed25519 malleable signatures?

### ISSUE THREAD

**Issue by fxha** [randombit/botan#2049]
Thanks for your great work on this project and all contributors.

I have a question regarding Ed25519. Libraries such as Crypto++ and libsodium do a [malleability check](https://github.com/jedisct1/libsodium/blob/3f2701839458cb8dd19bf11badda2e50128b36b6/src/libsodium/crypto_sign/ed25519/ref10/open.c#L31) while signing that the public key is a canonical form and not lie on a small subgroup. Is this also done in Botan or is this not necessary - I don't found those checks after a quick search?

**Comment by randombit** [comment]
I would need to check more carefully but I believe we do the same (incomplete) malleability check as done in the original `ref10` which can be seen in the code as

```
   if(sig[63] & 224)
      {
      return false;
      }
```

so basically we reject some but not all of the possible signatures. You can see similar logic in libsodium source, guarded by `ED25519_COMPAT`.

**Comment by randombit** [comment]
> that the public key is a canonical form

This check is not done at all. It is not obvious to me why it would be necessary, maybe for blockchain like applications where it could affect consensus?

**Comment by randombit** [comment]
In further research I can't find any indications this leads to a security issue however I did find that RFC 8032 explicitly requires we check that S < l, so we should probably do that.

**Comment by fxha** [comment]
Yeah that's right and it shouldn't be an issue with normal protocols. The signature check for canonical form should improve that you don't compute further valid'ish signatures for the same message by trying random values but I would also add a note to the docs that Ed25519 is always malleable according the [official paper (page 7 - Malleability)](https://ed25519.cr.yp.to/ed25519-20110926.pdf).

**Comment by randombit** [comment]
This was fixed in #3338
