### ISSUE TITLE
ASIO TLS Stream: Client only?

### ISSUE THREAD

**Issue by bazineta** [randombit/botan#2053]
Looking over the new ASIO stream implementation in 2.11.0, I see examples and tests for client side, but not for server side. As this is a new implementation, I'm curious if server side is supported, or if this is a client-side only implementation. Thanks.

**Comment by randombit** [comment]
I believe it is only client side right now @hrantzsch can you confirm?

**Comment by hrantzsch** [comment]
Correct, the server side is not yet implemented. We won't get around to implement it in the near future I'm afraid.
@bazineta if you are interested in implementing it, I don't think it will be a huge amount of work and we will be happy to assist you. A good starting point would be to implement setting up the native_handle for the server side: https://github.com/randombit/botan/blob/fdf9970f921bf6b3e99c2a99ebc251b6e5dd760e/src/lib/tls/asio/asio_stream.h#L650

**Comment by nunojpg** [comment]
@hrantzsch btw, DTLS is supported or do you have any comments about how to get it working?

**Comment by hrantzsch** [comment]
DTLS is not supported by the Stream unfortunately. The first issue is that the Stream always instantiates the underlying `TLS::Client` with the default protocol version, which currently is TLS 1.2. (It would probably be good to do this more explicitly.)
The next, and more problematic, issue is that `boost::asio::udp::socket` does not offer the `read_some` and `write_some` methods that the Stream relies on.

**Comment by reneme** [comment]
Server-side is now implemented and merged. Any feedback on the feature is highly appreciated. Otherwise, I believe, this ticket can be closed now, right?
