### ISSUE TITLE
Catch-based test failures don't log anything useful

### ISSUE THREAD

**Issue by randombit** [randombit/botan#206]
The existing calls to the `CHECK` macro wrap the whole expression in an extra set of (). This seems to be to avoid triggering the GCC -Wparentheses warning, but it results in useless errors when a test fails, take this from base64 (modified to fail):

./src/tests/catchy/test_base64.cpp:39: FAILED:
  CHECK( ( Botan::base64_encode(in2) == "Zm0=" ) )
with expansion:
  false

because we're effectively just passing a boolean value to CHECK rather than something it can deconstruct. 

We need to either disable -Wparentheses (even just in the tests I'm definitely not much in favor of this one, as it is a useful warning), fix Catch (?), live with a lot of warnings when compiling the tests, or live with not getting useful output when a test fails. I'm not sure which of these options I dislike least.

**Comment by webmaster128** [comment]
Let's go for matchers. The following code displays full information and does not trigger a compiler warning:

```
CHECK_THAT(Botan::base64_encode(in2), Equals("Zm8"));
```

On the project page they wrote *Support for Matchers (early stages)* but this was two years ago. Let's see whether the basic matchers are working fine and fix a Catch matcher if necessary.

**Comment by webmaster128** [comment]
Okay it turned out that matchers are only implemented for `std::string`. I was able to come up with an additional matcher for `std::vector` that works with custom allocators as well (for `Botan::secure_vector<X>`. Integer matching is still missing but should be trivial to implement.

**Comment by webmaster128** [comment]
I got this now. The only problem to take care of is that Catch evaluates the expression multiple times when matchers are used. Thus we cannot put in non-const functions directly.
