### ISSUE TITLE
Add remove function to Botan::Extension class

### ISSUE THREAD

**Issue by ahura24** [randombit/botan#2065]
Hello and thanks for your awesome library.

We need to remove an extension from the Botan::Extensions class. This patch fix the bug of Botan::Extensions::replace function when throw and exception at create time of Extensions_Info structure and add a "remove" function for this class.

Regards,

[Add_remove_function_to_extensions.zip](https://github.com/randombit/botan/files/3500191/Add_remove_function_to_extensions.zip)

**Comment by randombit** [comment]
Hi @ahura24  thank you for sending the patch, it looks good at a first glance. Would it be possible for you to submit it as a proper PR? https://help.github.com/en/articles/about-pull-requests
