### ISSUE TITLE
Certificate_Store_MacOS does not search in 'login' keychain after updating to 10.14.6

### ISSUE THREAD

**Issue by reneme** [randombit/botan#2066]
We just realized that Apple seems to have changed the default behaviour of its trust store APIs. Therefore, starting with macOS 10.14.6, certificate trust roots are not found by `Certificate_Store_MacOS` if they are installed in the 'login' keychain. They need to reside in either "System" or "System Roots".

I'm not sure whether this is worth fixing or whether it is actually what we wanted from the beginning. In any case, it is a silent change in behaviour of `Certificate_Store_MacOS` (and of course the `System_Certificate_Store` as well) after applying a macOS update. RFC. :)

See the below screenshot of macOS's "Keychain Access".

<img width="175" alt="Screenshot 2019-08-15 at 15 51 28" src="https://user-images.githubusercontent.com/1562139/63099073-91847780-bf74-11e9-9141-3b1ed0bff521.png">

**Comment by randombit** [comment]
A `login` keystore sounds like it would be certs+keys for client auth that is managed by a particular user - that about right? In that case, it does seem unusual to get trust roots from such a store.

Is there any indication of why the API behavior changed? Also, is it even known how one would get at any trust roots kept in a `login` keystore that are no longer returned post-update?

**Comment by reneme** [comment]
> A login keystore sounds like it would be certs+keys for client auth that is managed by a particular user - that about right?

That's what I would assume as well. We learnt about the issue, because some team members had their in-house dev CA installed in their "login" chain and suddenly it stopped working. For the record: We're not 100% certain that 10.14.6 is responsible.

On the other hand, `Certificate_Store_MacOS` does [open the system chains only](https://github.com/randombit/botan/blob/master/src/lib/x509/certstor_system_macos/certstor_macos.cpp#L222). It's unclear to me, how this ever worked.

> Also, is it even known how one would get at any trust roots kept in a `login` keystore that are no longer returned post-update?

Most likely we could just try to open `~/Library/Keychains/login.keychain` the same way as linked above. I'd argue to not do that, though, and rather live with the changed behaviour. It seems to be the saner default, anyway, IMHO.

**Comment by reneme** [comment]
Okay, that's embarrassing. I think, we managed to stumble over our own configuration when introducing a new internal CA and drew conclusions too quickly. 🤦‍♂ Never mind, everything works as expected and the `login` keychain is _not_ searched.

Feel free to close, and sorry for the noise.

**Comment by randombit** [comment]
Everything working as expected, best possible resolution! :)

Thanks for taking time to analyze this.
