### ISSUE TITLE
Argon2 does not support outputs greater than 64

### ISSUE THREAD

**Issue by kelvinhammond** [randombit/botan#2078]
Argon2 throws `Not_Implemented("todo")` for outputs with a length greater than 64.

**Comment by kelvinhammond** [comment]
User provides a passphrase and I'm using it to generate 192 bytes of output for three different ciphers where I encrypt data separately, I can use the same key but I was trying to use a different key for each. Thank you for working on botan.

**Comment by randombit** [comment]
Fixed now in #2079 you can backport the change to 2.11.0 (patch should apply cleanly) or wait for 2.12 in October.
