### ISSUE TITLE
MSVC Blake2b slow

### ISSUE THREAD

**Issue by AtomicNibble** [randombit/botan#2089]
When I compile amalgamation on Windows using VS2017 x64 (CL version 19.16.27032.1) Blake2b is very slow.

Looking at the disassembly the compiler is not inlining any of the ROUND calls.

Benchmark:
```
Run on (12 X 3200 MHz CPU s)
CPU Caches:
  L1 Data 32K (x6)
  L1 Instruction 32K (x6)
  L2 Unified 262K (x6)
  L3 Unified 12582K (x1)

------------------------------------------------------------------------------
Benchmark       Time             CPU          Iterations UserCounters...
------------------------------------------------------------------------------
Blake2b         4690919 ns      4718960 ns    149        bytes_ps=211.911M/s
```
I switched out inline for [__forceinline](https://docs.microsoft.com/en-us/cpp/cpp/inline-functions-cpp?view=vs-2019) (a CL specific keyword) on `ROUND` & `G` and I get double the speed.

```
__forceinline void G(...);
__forceinline void ROUND(...);
```

```
------------------------------------------------------------------------------
Benchmark       Time             CPU          Iterations UserCounters...
------------------------------------------------------------------------------
Blake2b         2289119 ns      2299331 ns    299        bytes_ps=434.909M/s
```

I looked through the Botan source code and could see no conditional enable of __forceinline for Windows builds, is this something you actively avoid in the codebase?

Or something you would accept a patch for using macros to enable it only for supporting platforms.

Thanks.

**Comment by AtomicNibble** [comment]
I see SHA512 uses a macro to resolve this same problem `SHA2_64_F` I did the same for Blake2 `ROUND` and the speed gains are simular as expected, and this feels like a better solution.

Eg:

```
#define BLAKE2_ROUND(i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, iA, iB, iC, iD, iE, iF, V, M) \
   G(v[ 0], v[ 4], v[ 8], v[12], M[i0], M[i1]); \
   G(v[ 1], v[ 5], v[ 9], v[13], M[i2], M[i3]); \
   G(v[ 2], v[ 6], v[10], v[14], M[i4], M[i5]); \
   G(v[ 3], v[ 7], v[11], v[15], M[i6], M[i7]); \
   G(v[ 0], v[ 5], v[10], v[15], M[i8], M[i9]); \
   G(v[ 1], v[ 6], v[11], v[12], M[iA], M[iB]); \
   G(v[ 2], v[ 7], v[ 8], v[13], M[iC], M[iD]); \
   G(v[ 3], v[ 4], v[ 9], v[14], M[iE], M[iF]); 
```

**Comment by randombit** [comment]
Thanks for reporting. Interestingly, it seems (based on core count) you are running a fairly recent machine, but even with `__forceinline` the speed you get is about the same as what I see (with GCC) on a 9 year old i5-520; on a 4 GHz Skylake I get more like 920 MiB/s. So I would think there is still further potential for improving MSVC performance.

I would be ok adding a macro `BOTAN_FORCE_INLINE` which expanded to either `__forceinline`, GCC/Clangs `__attribute__((always_inline))` or plain `inline` depending on the compiler. We already have precedent for that with the various macros in `src/utils/compiler.h`. In general I prefer inline functions to macros as you get somewhat better typing, and sometimes macros collide in unfortunate ways in the amalgamation builds when we combine all the lib sources into a single file.

**Comment by randombit** [comment]
@AtomicNibble Could you try the patch in #2092 and verify it improves the performance?

**Comment by AtomicNibble** [comment]
I have quite a old CPU 3930k, been waiting for a 3900x for about 2 months so will reset once that arrives.

I will test the patch, thanks.

**Comment by AtomicNibble** [comment]
Patch looks good testing with MSCV.

**Comment by randombit** [comment]
Ah OK I didn't realize Intel made hex cores going back that far. Probably then nothing MSVC specific to worry about, re the perf you are seeing.
