### ISSUE TITLE
path stripped from Python executable

### ISSUE THREAD

**Issue by thmo** [randombit/botan#2130]
https://github.com/randombit/botan/blob/cda9a4096c4646f3d72d5238cfa0039d9dea2484/configure.py#L2064

Is there a reason to strip the path to the Python executable? If the executable is not in `$PATH`, later calls using `PYTHON_EXE` will fail, e.g.

https://github.com/randombit/botan/blob/cda9a4096c4646f3d72d5238cfa0039d9dea2484/src/build-data/makefile.in#L52

**Comment by randombit** [comment]
I can't remember why this was done but I can see how it would be a problem, fix coming up.

**Comment by thmo** [comment]
I think it was changed in 815a3a8d, as part of a fix to #1456. I might be mistaken, but stripping the path to the Python binary seems to have been used as sort of a workaround for path separator quoting issues on windows (judging from https://github.com/randombit/botan/issues/1456#issuecomment-368216574).

**Comment by randombit** [comment]
Thanks for digging that up. I will add quoting which I think addresses the issue with spaces in paths.
