### ISSUE TITLE
Build fails when building with `nmake`

### ISSUE THREAD

**Issue by reneme** [randombit/botan#2141]
Unfortunately [this PR](https://github.com/randombit/botan/pull/2131) broke the build when using `nmake` on Windows. It cannot deal with the quoted Python executable path and fails in [an obscure way](https://ci.appveyor.com/project/bincrafters/conan-botan/builds/27986216/job/vqq06otsdfd73qfd#L459):

```
        "C:\Python27\python.exe" src/scripts/build_docs.py --build-dir="build"
C:\Python27\python.exe: can't find '__main__' module in 'src'
NMAKE : fatal error U1077: 'C:\Python27\python.exe' : return code '0x1'
```

I [fixed the issue](https://github.com/bincrafters/conan-botan/pull/14) by switching the Conan recipe to `jom` for building, but other people might be less flexible in their choice of tooling.

**Comment by randombit** [comment]
Oh that's really unfortunate. I had assumed we could treat jom and nmake as equivalent. I will change at least one of the CI builds to use nmake to prevent such issues from recurring.
