### ISSUE TITLE
Investigate XTS test vectors

### ISSUE THREAD

**Issue by randombit** [randombit/botan#2146]
The comment in the data file has them all coming from P1619 and most of them seem to be, but some of the vectors do not appear in http://libeccio.di.unisa.it/Crypto14/Lab/p1619.pdf and others from the spec are missing in the vector file.

**Comment by ssd71** [comment]
I would like to work on this, I looked through the test vectors file and many vectors from the spec are omitted there, I will try to look harder for any vectors not in the spec, should I add in all the test vectors from the spec that are not in the data file

**Comment by randombit** [comment]
@ssd71 Thank you that would be most welcome. Yes all tests from the standard should be included. There are also some in the current xts.vec file that are seemingly not from IEEE 1619-2007 at all. Those tests should be retained but moved to just before where the OpenSSL generated vectors start with a comment along the lines of "# Source unknown"

Also ideally comment each vector with "# IEEE 1619-2007 vector N" so we can keep track of which tests are/are not included in the future.
