### ISSUE TITLE
ABI warnings on SSE2 usage in some situations

### ISSUE THREAD

**Issue by randombit** [randombit/botan#2153]
See #2139 and https://travis-ci.com/bincrafters/conan-botan/jobs/245340853#L648

**Comment by reneme** [comment]
... pulling [the discussion](https://github.com/randombit/botan/issues/2139#issuecomment-541751620) over here

> On another look that warning looks really odd, because it is happening in a x86-64 build, and the base amd64 ISA includes SSE/SSE2. So how could we be compiling "without SSE enabled"?

Actually I don't see the warning in the 64bit builds. The CI run  linked above builds on an `x86_64` machine but the target is cross-compiled to `x86`.

Potentially you got confused by [this line](https://travis-ci.com/bincrafters/conan-botan/jobs/245340853#L613), in the logs?

> Cross-build from 'Linux:x86_64' to 'Linux:x86'

**Comment by randombit** [comment]
Ah ok thank you, seeing this on x86-32 makes sense.

**Comment by randombit** [comment]
I haven't been able to reproduce this, probably it is gcc 4.8/4.9 specific. But what the fix should be seems straightforward.

[Also is it me or is it weird that bincrafters is using a 5 year old compiler?

**Comment by reneme** [comment]
> Also is it me or is it weird that bincrafters is using a 5 year old compiler?

They build `conan-botan` on GCC 4.9 to 8.0 and Clang 3.9 to 7.0; see [here](https://travis-ci.com/bincrafters/conan-botan/builds/131777986). From my experience, compilers are removed from the build as soon as they are officially not supported by the packaged project anymore.

Their goal is to also provide binaries for the most common compilers and configurations. Hence, the wide variety, I guess.

**Comment by randombit** [comment]
Fixed with #2156
