### ISSUE TITLE
Building with jom/nmake only works if using MSVC

### ISSUE THREAD

**Issue by cherevon** [randombit/botan#2160]
Cannot build the library because there is no libbotan-2.a
![image](https://user-images.githubusercontent.com/8018219/67022932-a8794e80-f10a-11e9-9365-8275cede6fef.png)

**Comment by cherevon** [comment]
With version 2.12.1 I am getting the same error

**Comment by randombit** [comment]
Embarcadero make is untested. We'd like to support any generic make (and current makefile supports GNU make, BSD make, jom and nmake without changes) and would accept changes to support Embarcadero but it's not something I have any interest in personally.

I don't understand the problem with jom though. We build with jom in CI. Are you using the latest version of jom?

If you are using g++ already though, it probably makes most sense to just use GNU make.

**Comment by cherevon** [comment]
I'm using jom version 1.1.3. It is the latest version downloaded with Qt
http://download.qt.io/official_releases/jom/jom.zip

mingw32_make.exe from MinGW 7.3 64 bit has built the library successfully =)

**Comment by randombit** [comment]
Oh I see the problem we have a conditional to emit `.PHONY` directive which used by Unix make. But jom and probably nmake don't understand and reject this syntax.

And we can't perform a conditional within the makefile itself, because conditional syntax differs between GNU make and nmake ...
