### ISSUE TITLE
Internal header message in amalgamation

### ISSUE THREAD

**Issue by AtomicNibble** [randombit/botan#2164]
With 2.12.1 amalgamation I get a build log full of `this header will be made internal in the future`

I've currently worked around it with the following patch

```
  #if defined(BOTAN_AMALGAMATION_H_)
    #define BOTAN_DEPRECATED(msg)
    #define BOTAN_DEPRECATED_HEADER(hdr)

  #elif defined(__clang__)
    #define BOTAN_DEPRECATED(msg) __attribute__ ((deprecated(msg)))
    #define BOTAN_DEPRECATED_HEADER(hdr) _Pragma("message \"this header is deprecated\"")
```

Thanks.

**Comment by randombit** [comment]
That's obnoxious sorry. I will fix that this weekend.

**Comment by AtomicNibble** [comment]
I don't need workaround with latest version, thanks.
