### ISSUE TITLE
TLS channel is active and closed at the same time

### ISSUE THREAD

**Issue by fschoenm** [randombit/botan#2171]
I'm not sure how we got there yet but in our TLS stack, we have a Botan TLS channel that returns ``true`` on both, ``is_active()`` and ``is_closed()``. This has been introduced with the change in #2054, so the behavior changed between 2.11.0 and 2.12.1.

This is confusing because the TLS reference says:

    .. cpp:function:: bool is_active()

      Returns true if and only if a handshake has been completed on
      this connection and the connection has not been subsequently
      closed.

    .. cpp:function:: bool is_closed()

       Returns true if and only if either a close notification or a
       fatal alert message have been either sent or received.

It was my understanding that both functions can never be true at the same time so we added an assertion to our code that now fails.

**Comment by fschoenm** [comment]
I checked in our code and found that the TLS channel is closed because we sent a ``CLOSE_NOTIFY`` alert on the connection to initiate shutting it down. It seems that right after, the channel counts as active and closed at the same time. I can work around that new behavior but I'm not sure if it was intended.

**Comment by randombit** [comment]
This was not an intentional change. Probably the easiest thing to do is probably modify `is_active` to check if `is_closed` and if so return false. There should also be a test of this so we don't see future regressions.

**Comment by randombit** [comment]
@fschoenm Can you try patch in #2174 - should resolve situation.

**Comment by fschoenm** [comment]
Thank you for the quick fix. This looks like it should definitely fix the issue with being active and closed at the same time, which violated our assertion.

I imagine there might also be a difference in the timing now that the TLS stack reports the channel closed earlier than before though that shouldn't be a problem. I hope to find some time in the next days to try your patch.

**Comment by fschoenm** [comment]
@randombit With your patch, all our tests pass again.
