### ISSUE TITLE
Python AttributeError when trying to export key with to_pem()

### ISSUE THREAD

**Issue by kaspro** [randombit/botan#2184]
I'm pretty new to Python so if there lies my issue please forgive me. I'm trying to export/print the public key to pem. The following is working:

`myPrivKey = botan2.PrivateKey('rsa', 4096, myRNG)`
`myPubKey = myPrivKey.get_public_key()`
`print(myPubKey.fingerprint())`

But executing `print(myPubKey.to_pem())`
...throws the error 

> AttributeError: 'PublicKey' object has no attribute 'to_pem'

...any hints?

**Comment by randombit** [comment]
Which version are you using? This function was only added in 2.11

If you are using an older version (but at least 2.8.0) you can use the current master `botan2.py` against the previous libbotan-2.so

**Comment by kaspro** [comment]
Darn, I'm using 2.10 (on Fedora 30). 

> Botan 2.10.0 (release, dated 20190330, revision git:3a459487df5de4cb411efdda0010e617d6903284, distribution Fedora)

Unfortunately just "exchanging" the botan2.py will throw me more errors on my code
`AttributeError: 'PrivateKey' object has no attribute '_PrivateKey__obj'`
`myPrivKey = botan2.PrivateKey('rsa', 4096, myRNG)`
`TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given`

I suppose I'll have to wait a bit until that's merged...

**Comment by randombit** [comment]
Oh sorry I had forgotten about this - the API of `PrivateKey` changed here in 2.11.0

In versions of the Python module 2.11 onwards you need:

`priv = botan2.PrivateKey.create('rsa', 4096, rng) `

Notice additional `.create`.

**Comment by kaspro** [comment]
Wow - that easy :)
Works like a charm, thanks a lot!
