### ISSUE TITLE
Bigint: array of words

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#219]
While trying to debug #108, I get very confused by the vector of words which the BigInt class uses internally to store data. The API is a mix of bits, bytes and words, where it is hard to imagine how long the later one is.

Is there a reason to store a BigInt as `secure_vector<word>` instead of `secure_vector<Botan::byte>`?

**Comment by 983** [comment]
`word`s might have been chosen over `byte`s because of performance.
One could cast bytes to words when doing math, but that would be a lot of work because the number of bytes might not always be divisible by four (or whichever number of bytes a word consists of here).

**Comment by randombit** [comment]
The size of `word` is system dependent and generally chosen to match the CPU word size, so 32 or 64 bits typically. Processing 64 bits at a time while say adding two 512 bit numbers will be roughly 1/8 the operations that doing so 8 bits at a time. This effect is even more pronounced with algorithms like simple multiplication which are O(n^2); there using 64 bit words is 64 times (8^2) fewer operations than byte at a time.

**Comment by webmaster128** [comment]
Great, thanks. I was not really aware of the component-wise math operations.
