### ISSUE TITLE
"botan config ldflags" returns incorrect library path

### ISSUE THREAD

**Issue by j-mckim** [randombit/botan#2199]
I built Botan with a prefix specified, e.g.

    ./configure.py --prefix=/tmp/botan

When the CLI botan of the build is queried to determine information about the build, it returns an incorrect -L library path, with duplicate components.

    jim@wandering:/tmp/botan/bin$ LD_LIBRARY_PATH=/tmp/botan/lib/ ./botan config ldflags
    -fstack-protector -m64 -pthread -L/tmp/botan//tmp/botan/lib

I am using Botan version 1.12.1

Done twice with different prefixes; same results.

**Comment by randombit** [comment]
Thanks for the report. I suspect this is related to the change in #2109

**Comment by randombit** [comment]
Also we should be testing `botan config` I think it is not included in the test scripts
