### ISSUE TITLE
Off-by-one error when converting BigInt to u32bit

### ISSUE THREAD

**Issue by 983** [randombit/botan#220]
https://github.com/randombit/botan/blob/master/src/lib/math/bigint/bigint.cpp#L145

Should be `if(bits() > 32)` instead of `if(bits() >= 32)`.

Otherwise this will throw an exception:
```
uint32_t x = 0xffffffff;
BigInt(x).to_u32bit();
```

**Comment by randombit** [comment]
Thanks for the report! I'll take this.

**Comment by webmaster128** [comment]
I think this is done, right?
