### ISSUE TITLE
PK_Verifier using hashes

### ISSUE THREAD

**Issue by royb3** [randombit/botan#2202]
I'm trying to verify ECDSA signatures, but I don't understand how to verify hashes directly. 

Is there a way to use pre-hashed data, instead of having the PK_Verifier calculate the hashes?

**Comment by randombit** [comment]
Yes if you specify "Raw" instead of a hash in initializing the `PK_Verifier`, then the passed in data is assumed to be prehashed.

**Comment by royb3** [comment]
So, I got this to work:
```
PK_Verifier verifier(*pubKey, "EMSA1(SHA-256)", DER_SEQUENCE);
string hash = "BLABLA2";
...
if(verifier.verify_message((uint8_t *)hash.data(), hash.length(), (uint8_t *)sig.data(), sig.size())
```
So should I change it to:
```
PK_Verifier verifier(*pubKey, "Raw", DER_SEQUENCE);
string hash = "949ceab33a84d800d04a49cc15c29bffb5f748d4a41b8cef1e649fda813f985b";
```
Although this is the hash for "BLABLA2", it doesn't get verified as OK.

**Comment by randombit** [comment]
It looks like you are providing the hash as hex, but PK_Verifier expects it as binary data. Try

auto hash = hex_decode("949ce...");

if(verifier.verify_message(hash.data(), hash.length(), (uint8_t *)sig.data(), sig.size())

**Comment by royb3** [comment]
Yes! That did it. 

Thank you for helping out so fast.
