### ISSUE TITLE
Windows build fails with --msvc-runtime=MT

### ISSUE THREAD

**Issue by pauljon** [randombit/botan#2209]
With a fresh Botan Git clone checked out to "2.12.1", the library is built fine with these commands, but the build fails when linking botan-cli.exe. I think the "/MT" (all values of --msvc-runtime) argument should just not be give to the linker.

python configure.py --cc=msvc --os=windows --disable-shared-library --msvc-runtime=MT
nmake

        link /MT /bigobj build\obj\cli\argon2.obj build\obj\cli\asn1.obj build\obj\cli\bcrypt.obj build\obj\cli\cc_enc.obj build\obj\cli\cli.obj build\obj\cli\cli_rng.obj build\obj\cli\codec.obj build\obj\cli\compress.obj build\obj\cli\encryption.obj build\obj\cli\entropy.obj build\obj\cli\hash.obj build\obj\cli\hmac.obj build\obj\cli\main.obj build\obj\cli\math.obj build\obj\cli\pbkdf.obj build\obj\cli\pk_crypt.obj build\obj\cli\psk.obj build\obj\cli\pubkey.obj build\obj\cli\sandbox.obj build\obj\cli\speed.obj build\obj\cli\timing_tests.obj build\obj\cli\tls_client.obj build\obj\cli\tls_http_server.obj build\obj\cli\tls_proxy.obj build\obj\cli\tls_server.obj build\obj\cli\tls_utils.obj build\obj\cli\tss.obj build\obj\cli\utils.obj build\obj\cli\x509.obj .\botan.lib crypt32.lib user32.lib ws2_32.lib  /OUT:.\botan-cli.exe
Microsoft (R) Incremental Linker Version 14.23.28107.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1146: no argument specified with option '/MT'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\link.EXE"' : return code '0x47a'
Stop.

**Comment by randombit** [comment]
I think this has already been fixed in master - can you try 51274b385?

**Comment by pauljon** [comment]
I reset my repo to tip of master and reran the scenario. I can confirm the fix on master and will assume the change will be picked up for the next release. Thank you.

**Comment by randombit** [comment]
Yes 2.13.0 is scheduled for January 6th and will be based on current master.

**Comment by pauljon** [comment]
Great, thanks. Not sure what your policy is on keeping resolved issues open, so not sure if I should close this. Close anytime you want.
