### ISSUE TITLE
Windows build fails to link with ZLib static library

### ISSUE THREAD

**Issue by pauljon** [randombit/botan#2210]
With a fresh Botan Git clone checked out to "2.12.1", the library is built fine with these commands, but the build fails when linking botan-cli.exe because it is trying to link with "z" instead of zlib.lib which is I think is the correct name for the ZLib static library on Windows.

python configure.py --cc=msvc --os=windows --disable-shared-library --with-zlib --with-external-includedir=E:\repo\vcpkg\installed\x64-windows-static\include --with-external-libdir=E:\repo\vcpkg\installed\x64-windows-static\lib
nmake

        link /LIBPATH:E:\repo\vcpkg\installed\x64-windows-static\lib /MD /bigobj build\obj\cli\argon2.obj build\obj\cli\asn1.obj build\obj\cli\bcrypt.obj build\obj\cli\cc_enc.obj build\obj\cli\cli.obj build\obj\cli\cli_rng.obj build\obj\cli\codec.obj build\obj\cli\compress.obj build\obj\cli\encryption.obj build\obj\cli\entropy.obj build\obj\cli\hash.obj build\obj\cli\hmac.obj build\obj\cli\main.obj build\obj\cli\math.obj build\obj\cli\pbkdf.obj build\obj\cli\pk_crypt.obj build\obj\cli\psk.obj build\obj\cli\pubkey.obj build\obj\cli\sandbox.obj build\obj\cli\speed.obj build\obj\cli\timing_tests.obj build\obj\cli\tls_client.obj build\obj\cli\tls_http_server.obj build\obj\cli\tls_proxy.obj build\obj\cli\tls_server.obj build\obj\cli\tls_utils.obj build\obj\cli\tss.obj build\obj\cli\utils.obj build\obj\cli\x509.obj .\botan.lib crypt32.lib user32.lib ws2_32.lib z  /OUT:.\botan-cli.exe
Microsoft (R) Incremental Linker Version 14.23.28107.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : warning LNK4044: unrecognized option '/MD'; ignored
LINK : warning LNK4044: unrecognized option '/bigobj'; ignored
LINK : fatal error LNK1181: cannot open input file 'z.obj'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\link.EXE"' : return code '0x49d'
Stop.

**Comment by randombit** [comment]
Can you try this patch?

```
--- a/src/lib/compression/zlib/info.txt
+++ b/src/lib/compression/zlib/info.txt
@@ -5,5 +5,6 @@ ZLIB -> 20160412
 load_on vendor
 
 <libs>
-all -> z
+windows -> zlib
+all!windows -> z
 </libs>
```

**Comment by pauljon** [comment]
After applying your patch and retrying, the CLI linker command line now omits any zlib library entry, so unresolved symbols for deflate, inflate, and friends are now present. I'm going to quickly try another workaround as a datapoint for you, so stay tuned.

**Comment by pauljon** [comment]
I had previously tried the following change to that zlib/info.txt file as an experiment and found it worked on Windows and I just confirmed that "zlib.lib" gets properly placed on the CLI linker command line with it.

`<libs>
all -> zlib.lib
</libs>`

It would not work on non-Windows, but hopefully helps with analysis.
