### ISSUE TITLE
argon2.h is future internal, but it contains argon2_(generate,check)_pwhash

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#2230]
While argon2.cpp functionality can be accessed with the mother factory class, what about the direct generate/check functions at argon2fmt.cpp?

Should this be split into a separate header?

I know there is a big chance this is already discussed, and it's not being changed yet awaiting for some API step, but just in case I report :)

**Comment by randombit** [comment]
Yeah the plan is to add an interface for formatted password hashes to PasswordHash along with the PBKDF functionality. But I should probably revert the deprecation at least until that is available.
