### ISSUE TITLE
Happy new year to us

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#2231]
Wishing happy holidays and a great 2020 to the Botan community, with continued great leadership from Jack.

**Comment by reneme** [comment]
Let me join in! I wish all of you a blissful and calm holiday season and a "Guten Rutsch" into 2020. Many thanks specially to @randombit for maintaining this great library and helping us 'round the clock with our questions and reviewing our contributions. :)

**Comment by securitykernel** [comment]
So true. Thanks @randombit for all your advice, help and commitment to maintaining this awesome library! I can not imagine a better expert than you are. You are an inspiring example of an open source software developer.

**Comment by nunojpg** [comment]
obsolete due to earth translation

**Comment by randombit** [comment]
Just got back from vacation, thanks all for your kind words and looking forward to a productive 2020.
