### ISSUE TITLE
what is recommended method for data transmission from app to server and vice versa

### ISSUE THREAD

**Issue by sherifomran** [randombit/botan#2232]
I want to ask about the recommendation of secure method for data encryption between an app and a server. 
2- is it possible to use botan php on a webserver, or it need some installation of extension to the php found 7.3.11 with openssl.

please advice .. 
thank you

**Comment by randombit** [comment]
Normally you would just use TLS for this. You can also pin the server certificate in the application to prevent a corrupt CA from creating a MITM cert. If you need additional encapsulation you can encrypt messages and then send them over HTTPS. One easy thing to do here would be to use the libsodium compatibility functions (in sodium.h) and then in PHP use the PHP libsodium binding.

I don't know of any PHP extensions for Botan. I think there was a Node.js extension but it hasn't been maintained in years.
