### ISSUE TITLE
TLS exception when receiving too much data

### ISSUE THREAD

**Issue by pfeatherstone** [randombit/botan#2238]
I'm using an asynchronous network connection underneath botan. When receiving data from the connection (asynchronously), I simply call TLS::Channel::received_data parsing ALL available data. When receiving too much data, e.g. multiple records, botan throws the exception : received a record that exceeds maximum size.

What's the best way to handle this?

**Comment by pfeatherstone** [comment]
Before that, I also receive : Invalid authentication tag: ChaCha20Poly1305 tag check failed

**Comment by pfeatherstone** [comment]
This only happens when sending large data quickly

**Comment by pfeatherstone** [comment]
I think what it is is receiving a non-integer number of records will cause "ChaCha20Poly1305 tag check failed" even though you are about to receive the rest of last record, by which time it's too late because the channel has sent an Alert message.

**Comment by pfeatherstone** [comment]
Yep I've confirmed this. I get around this by wrapping data I'm about to send from "tls_emit_data" into a bounded message then I unwrap it before sending the payload via TLS::Channel::received_data. 

It would be nice if TLS::Channel::received_data did this anyway to avoid extra memory allocations

**Comment by randombit** [comment]
That is really unexpected - `received_data` should be able to buffer any amount of data including multiple sequential records, and also cleanly handle partial records by buffering internally until the record is completed.

The error "Received a record that exceeds maximum size" should only occur when the actual bytes within the record header indicate a record length that is larger than allowed by the specification. That suggests a framing error, where we are accidentally interpreting some other random bytes as a TLS header.

As a stopgap here one thing that may help is that `recieved_data` will return the number of bytes at a minimum that should be read to process the next record. If a complete record was just read then this will return 5 (length of the TLS record header). So you can perhaps use this for framing and only provide exactly the number of bytes requested.

I'm going to be unavailable for most of this week but will investigate this ASAP probably early next week.

**Comment by pfeatherstone** [comment]
OK, i've made a colossal mistake. For some reason i thought received_data returned the number of bytes not processed within the provided input buffer. The documentation is clear, it returns the number of bytes remaining to complete a record. I assume this means that received_data always processes the entire input buffer.

**Comment by pfeatherstone** [comment]
It works now if I assume the entire input buffer is processed, regardless of whether or not it contains a non-integer number of records. The code has a "while(input_size)" loop which indicates this is true but it can throw an exception somewhere. So I guess the assumption is not necessarily true.

**Comment by randombit** [comment]
> I assume this means that received_data always processes the entire input buffer.

Yes exactly, it should always consume the entire buffer that was provided, and if a record is not complete that final partial record is retained so it can be completed and processed the next time `received_data` is called. (Or whenever the entire thing is available - it is acceptable (though slow) to call `received_data` even a byte at a time).

The only case where the entire buffer is not processed is if processing fails along the way (decryption failed or bad header or whatever) but in this case the TLS session has terminated with an error and the rest of the data can be discarded.

**Comment by pfeatherstone** [comment]
Cool. Then I think this can be closed. My bad.

**Comment by randombit** [comment]
Glad we got things sorted so quickly and that everything is behaving as expected. Or at least as documented.
