### ISSUE TITLE
Building --maintainer-mode with g++ supplies unknown -Wextra-semi

### ISSUE THREAD

**Issue by Vinschni** [randombit/botan#2239]
Use 1a6ad661ce64287ccbe26460ccc3aa4247d86ba8 and
```
g++ --version | head -1
g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
```
Configure with:
`./configure.py --minimized-build --enable-modules=xmss --debug-mode --maintainer-mode`
leads to:
```
make
g++: error: unrecognized command line option ‘-Wextra-semi’; did you mean ‘-Wextra’?`
```

gcc does not support this option, see [here](https://stackoverflow.com/questions/46518398/wextra-semi-is-not-supported-in-gcc).

**Comment by randombit** [comment]
GCC 8 and higher support `-Wextra-semi`. The maintainer mode build is only intended for developers to use with the latest release of GCC/Clang to detect issues early, and not meant for production builds. It adds `-Werror` and may/will fail to build in many scenarios.

There is no reason to use `--maintainer-mode` unless you plan on submitting changes to address any warnings that are flagged.

BTW for XMSS you probably need an RNG (`system_rng` or `hmac_drbg`) plus at least one hash. Plus optionally the hardware specific accelerations (eg `sha2_32_bmi2`, etc).
