### ISSUE TITLE
Amalgamation on other platforms

### ISSUE THREAD

**Issue by tobiasbrunner** [randombit/botan#2241]
I noticed that amalgamation doesn't work on ARM64 and PowerPC (tested on Travis CI, it works fine on AMD64) because the target values used in the GCC pragmas are not valid:

**ARM64**
```
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation header to botan_all_internal.h
   INFO: Writing amalgamation source to botan_all.cpp
   INFO: Writing amalgamation source to botan_all_neon.cpp
   INFO: Writing amalgamation source to botan_all_armv8crypto.cpp
   INFO: Writing amalgamation source to botan_all_armv8crypto_neon.cpp
   INFO: Botan 2.13.0 (revision git:ed360ab268544fd801b8ea68ff08b07610680052) (unreleased undated) build setup is complete
botan_all_armv8crypto_neon.cpp:12:34: error: target pragma ‘armv8crypto’ is invalid
 #pragma GCC target ("armv8crypto")
                                  ^
botan_all_armv8crypto_neon.cpp:15:27: error: target pragma ‘neon’ is invalid
 #pragma GCC target ("neon")
                           ^
make: *** [build/obj/lib/botan_all_armv8crypto_neon.o] Error 1
make: *** Waiting for unfinished jobs....
botan_all_armv8crypto.cpp:12:34: error: target pragma ‘armv8crypto’ is invalid
 #pragma GCC target ("armv8crypto")
                                  ^
make: *** [build/obj/lib/botan_all_armv8crypto.o] Error 1
botan_all_neon.cpp:12:27: error: target pragma ‘neon’ is invalid
 #pragma GCC target ("neon")
                           ^
make: *** [build/obj/lib/botan_all_neon.o] Error 1
```
**PowerPC**
```
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation header to botan_all_internal.h
   INFO: Writing amalgamation source to botan_all.cpp
   INFO: Writing amalgamation source to botan_all_altivec.cpp
   INFO: Writing amalgamation source to botan_all_powercrypto.cpp
   INFO: Botan 2.13.0 (revision git:ed360ab268544fd801b8ea68ff08b07610680052) (unreleased undated) build setup is complete
botan_all_powercrypto.cpp:12:34: error: #pragma GCC target "powercrypto" is invalid
 #pragma GCC target ("powercrypto")
                                  ^
make: *** [build/obj/lib/botan_all_powercrypto.o] Error 1
```

May be somewhat related to #2159.

**Comment by randombit** [comment]
Thanks for reporting.

Issue is we assume the name used for the instruction set extension matches what GCC uses for the `target` pragma, but this is only true for (most) x86 ISAs. We need to add a proper mapping that works for everything.

Same mapping will be useful in the SIMD code which currently has some hardcoded values.

**Comment by randombit** [comment]
Fixed now by #2245 so this should work starting in 2.14

If you need this sooner than that, 0881f2c should apply cleanly to 2.13.0 also

**Comment by tobiasbrunner** [comment]
Thanks, successfully tested the patch on Travis.

**Comment by randombit** [comment]
Thanks for checking. Just a FYI, with #2246 this is being fixed in a different way which avoids splitting up the amalgamation by ABI and instead relying on GCC/Clang's `__attribute__((target("X"))` support. Simpler because there is then just a single `.cpp` file and a single `.h` file, and it removes a lot of complicated code on the build side, at the cost of dropping support for very old GCC (basically just GCC 4.8 and 4.9) in the amalgamation. I've already tested amalgamation still works correctly for Aarch64 and POWER.
