### ISSUE TITLE
Integrate coverage reporting via codecov.io

### ISSUE THREAD

**Issue by cordney** [randombit/botan#225]
https://codecov.io provides a service similar to https://coveralls.io, but seems to have a better feature set, for example:

* Pull request comments
* Tree navigation
* Fail build via minimum coverage
* More beautiful interface
* Browser plugin to view coverage data directly in GitHub (this is a killer feature IMHO)

See https://codecov.io/#features for a full feature list. It is also free for open source projects and already integrated with Travis CI (no token needed as with coveralls.io). Just sign in via GitHub login and you can already submit coverage data.

I set up a branch in my fork to upload botan coverage data. I only needed to change one line in https://github.com/cordney/botan/blob/codecov.io/src/scripts/ci/after_success.sh#L11. Technically, invoking gcov would be sufficient to generate the data needed by codecov.io (see their example C project: https://github.com/codecov/example-c).

See the difference in reporting below:

codecov.io: https://codecov.io/github/cordney/botan?ref=codecov.io
coveralls.io: https://coveralls.io/builds/3127912

My motivation for contributing was mainly in seeing coverage statistics to help with increasing coverage and for that, IMHO codecov.io does a better job.

**Comment by webmaster128** [comment]
Thanks a lot. Perfect alternative to coveralls.io, which has not been able to parse gcov data for a while now.
