### ISSUE TITLE
using VPSUM for GCM breaks big endian ppc64

### ISSUE THREAD

**Issue by sharkcz** [randombit/botan#2252]
After the introduction of using VPSUM for GCM on Power in commit 901d89a3ffa113b06fa0e600d622d5d088a2fa9d I see failing tests on big endian ppc64 system (with power8 cpu). So I suspect it assumes little endian system. See 
[botan-ppc64-log.txt](https://github.com/randombit/botan/files/4133455/botan-ppc64-log.txt) for test results.

**Comment by randombit** [comment]
Thanks for the report. I don't have access to any systems with POWER8 support that are big-endian and 64-bit. (There is a POWER8 AIX ppc64 machine in GCC compile farm but the toolchain seems to be buggy, and is 32-bit only). So for now I will just disable support for VPSUM on big-endian ppc64.

**Comment by sharkcz** [comment]
I can provide access to a power8/ppc64 VM if needed.

**Comment by randombit** [comment]
@sharkcz That would be pretty useful here. There is a similar issue that the AltiVec AES code doesn't work on big-endian either, would be nice to fix that as well. You can mail me at jack@randombit.net. SSH keys are in https://github.com/randombit.keys, use the first (P384).
