### ISSUE TITLE
Is OpenPGP S2K still in?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#226]
In the documentation at http://botan.randombit.net/manual/pbkdf.html it is stated that

> “PBKDF1(digest)”, “PBKDF2(digest)”, and “OpenPGP-S2K(digest)”

are the currently defined PBKDF functions.

Is the last one still in? I did not find any implementation and what I found in the changelog about s2k was not clear to me.

**Comment by randombit** [comment]
It was dropped in b82642c328d98f2aaa1ac17aa0999e69e7152ae8 but apparently not documented for the release notes or algo list.

**Comment by randombit** [comment]
Reference removed from manual in fbcb17f2151a8408cd4de8de82ba77926c80b135
