### ISSUE TITLE
read Certificate_Extension from file 

### ISSUE THREAD

**Issue by bnadem** [randombit/botan#2266]
i want to read Certificate_Extension from file , content **like** 
[v3_ca]
subjectAltName=DNS:localhost,DNS:ppic09,IP:127.0.0.1,IP:192.168.1.18,**URI:urn**:test.application
basicConstraints=CA:TRUE
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer
keyUsage=digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth,clientAuth,codeSigning

is there possibliy to read, thanks

**Comment by randombit** [comment]
No there isn't any support for parsing extension values or extension formatting from a file ala OpenSSL. Probably would be useful, but nobody has sent a patch and I haven't had a need for it. Seems like it would be pretty easy to do? `X509_CA::make_cert` takes an `Extension` object so all you would need to do is parse the string then use that plus the PKCS10 request to guide creating the extensions.
