### ISSUE TITLE
Have multiple documentations for different branches

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#227]
Currently there is only one documentation at http://botan.randombit.net/manual/ which is sometimes outdated for 1.10 and sometimes too old for 1.11.

Would it be possible to have a documentation structure like

/manual/1.10/
/manual/1.11/
/manual/2.0/
/manual/2.1/

which just takes the docs from the corresponding branch? The same goes for doxygen.

**Comment by cordney** [comment]
:+1: 

From the feedback of new users of botan that must stick with 1.10 I often hear the complaint that the docs on the website don't match the source, so this would be a significant improvement.

**Comment by randombit** [comment]
Added https://botan.randombit.net/manual-1.10/ + https://botan.randombit.net/doxygen-1.10/namespaceBotan.html
