### ISSUE TITLE
commoncrypto_utils.h missing from amalgamation build

### ISSUE THREAD

**Issue by hekkihek** [randombit/botan#2271]
Botan/botan_all.cpp:2300:10: 'commoncrypto_utils.h' file not found

The header file is included like this (in three different places)

#include "commoncrypto_utils.h"

while other headers are included like

#include <botan/internal/commoncrypto.h>

Maybe the commoncrypto_utils.h should be included in similar style?

**Comment by randombit** [comment]
Yes that include style is wrong and causes it to be omitted from the amalgamation. Thanks for the report

**Comment by hekkihek** [comment]
This surely fixes the issue for my application, great, thanks!

**Comment by randombit** [comment]
Now merged to master so should be resolved for next release, thanks again for reporting this
