### ISSUE TITLE
commoncrypto_utils does not accept empty padding

### ISSUE THREAD

**Issue by hekkihek** [randombit/botan#2273]
This prevents simple block cipher creating like
Botan::BlockCipher::create("AES-256", "commoncrypto")

**Comment by hekkihek** [comment]
Added a pull request for the change described above, the option to link it to this issue is greyed out.

**Comment by hekkihek** [comment]
This is apparently more complicated since the suggested fix has the side effect to re-enable cipher modes which were disabled due to padding errors. Some cipher modes assume/require other default padding. Have to investigate this further and see if commoncrypto can support that.

My primary interest at this point is to enable just the block ciphers, so maybe I'll first device a fix to make a call like
Botan::BlockCipher::create("AES-256", "commoncrypto")
working.

That has nothing to do with cipher modes, so that should be relatively easy to fix without making any changes to the commoncrypto cipher modes.

**Comment by hekkihek** [comment]
Added pull request #2276 which does exactly the above.

**Comment by hekkihek** [comment]
Looks like the test suite doesn't like that the block cipher creator ignores a specified cipher mode (other providers will refuse to create a block cipher). I will improve the patch and provide a new pull request for that.

**Comment by hekkihek** [comment]
This is fixed in pull request #2278

**Comment by randombit** [comment]
#2278 is merged to master now, so closing. Thank you for the bug report and patch.
