### ISSUE TITLE
Is there a plan to support attribute certificate?

### ISSUE THREAD

**Issue by TheWaveLab** [randombit/botan#2281]
I pretty like this library,it's very useful, but there's not an implementation of attribute certificate,so is there a plan to support attribute certificate? I saw this in the to-do list. thx

**Comment by randombit** [comment]
No immediate plans, at least for me, nor have I heard about anyone else working on it. It is in the todo list because it is within scope and a PR adding it would be accepted. If you want a new feature best ways to get it are send patches or pay someone to work on it.
