### ISSUE TITLE
SRP computation of M1 hash out of BigInt

### ISSUE THREAD

**Issue by courteous** [randombit/botan#2282]
I am trying to compute a simple SRP M1 message. I did not find any method that can do that in Botan, thus wrote this simple test below by computing M1 as "M1 = H(A | B | SharedKey)."

When i run the test I see segmentation fault is occurring. Here is the  GDB backtrace of it.

`#0  0x0000555555dcd08d in update (this=0x0, in=...) at /Projects/botan/build/include/botan/buf_comp.h:41`

when i try to use the hashing function i.e. the line 
`
hash_fn->update(secA);`

Am I using the hashing function correctly at all ? Basically  this is the same method used in 

botan/src/lib/misc/srp6/srp6.cpp  

```

BigInt hash_seq(
                const std::string& hash_id,
                size_t pad_to,
                const BigInt& in1,
                const BigInt& in2)
```
just added the shared key additionaly to the function.

here is the complete example:

```
#ifndef TEST_SRP_PRIMITIVES_TEST_H_
#define TEST_SRP_PRIMITIVES_TEST_H_

#include <gtest/gtest.h>
#include <iostream>
#include <memory>
#include <string>
#include <botan/bigint.h>
#include <botan/hash.h>

using namespace Botan;
using namespace std;

TEST(Srp, SrpM1TestMain) {


	const Botan::BigInt  RFC5054TestVector_N_1024("0xEEAF0AB9ADB38DD69C33F80AFA8FC5E86072618775FF3C0B9EA2314C9C256576D674DF7496EA81D3383B4813D692C6E0E0D5D8E250B98BE48E495C1D6089DAD15DC7D7B46154D6B6CE8EF4AD69B15D4982559B297BCF1885C529F566660E57EC68EDBC3C05726CC02FD4CBF4976EAA9AFD5138FE8376435B9FC61D2FC0EB06E3");
	const Botan::BigInt  RFC5054TestVector_g_common_2("0x2");
	const Botan::BigInt  RFC5054TestVector_A("0x61D5E490F6F1B79547B0704C436F523DD0E560F0C64115BB72557EC44352E8903211C04692272D8B2D1A5358A2CF1B6E0BFCF99F921530EC8E39356179EAE45E42BA92AEACED825171E1E8B9AF6D9C03E1327F44BE087EF06530E69F66615261EEF54073CA11CF5858F0EDFDFE15EFEAB349EF5D76988A3672FAC47B0769447B");
	const Botan::BigInt  RFC5054TestVector_B("0xBD0C61512C692C0CB6D041FA01BB152D4916A1E77AF46AE105393011BAF38964DC46A0670DD125B95A981652236F99D9B681CBF87837EC996C6DA04453728610D0C6DDB58B318885D7D82C7F8DEB75CE7BD4FBAA37089E6F9C6059F388838E7A00030B331EB76840910440B1B27AAEAEEB4012B7D7665238A8E3FB004B117B58");
	const Botan::BigInt  RFC5054TestVector_SharedKey("0xB0DC82BABCF30674AE450C0287745E7990A3381F63B387AAF271A10D233861E359B48220F7C4693C9AE12B0A6F67809F0876E2D013800D6C41BB59B6D5979B5C00A172B4A2A5903A0BDCAF8A709585EB2AFAFA8F3499B200210DCC1F10EB33943CD67FC88A2F39A4BE5BEC4EC0A3212DC346D7E474B29EDE8A469FFECA686E5A");

	const string group_id = Botan::srp6_group_identifier(RFC5054TestVector_N_1024, RFC5054TestVector_g_common_2);
	DL_Group group(group_id);
	const size_t size_to_pad_to = group.p_bytes();

	const string hash_id = "SHA-256";
	unique_ptr<Botan::HashFunction> hash_fn(Botan::HashFunction::create(hash_id));

	cout << "Pad to               :" <<  size_to_pad_to << endl;
	cout << "HashId is            :" <<  hash_id << endl;
	cout << "A is                 :" <<  RFC5054TestVector_A.to_hex_string() << endl;
	cout << "B is                 :" <<  RFC5054TestVector_B.to_hex_string() << endl;
	cout << "SharedKey is         :" <<  RFC5054TestVector_SharedKey.to_hex_string() << endl;
	cout << "N is                 :" <<  RFC5054TestVector_N_1024.to_hex_string() << endl;
	cout << "g is                 :" <<  RFC5054TestVector_g_common_2.to_hex_string() << endl;


	static secure_vector<uint8_t>  secA = BigInt::encode_1363(RFC5054TestVector_A, size_to_pad_to);
	static secure_vector<uint8_t>  secB = BigInt::encode_1363(RFC5054TestVector_B, size_to_pad_to);
	static secure_vector<uint8_t>  secSharedKey = BigInt::encode_1363(RFC5054TestVector_SharedKey, size_to_pad_to);


	hash_fn->update(secA);
	hash_fn->update(secB);
	hash_fn->update(secSharedKey);

	BigInt M1 = BigInt::decode(hash_fn->final() );
	cout << "M1 is                :" <<  M1.to_hex_string() << endl;

}

#endif /* TEST_SRP_PRIMITIVES_TEST_H_ */
```

According to my calculations, taking into account that all the leading zeros are removed from the BigInt's should that should result to : 

M1 using SHA-256 hex   :   95a7d155f07d3dcfa4f9a9a7faddeb65f6b43d3a0ffbbfab08e601815a9d84b4
M1 using SHA-1  hex    :   6749c38891f5acb77ad49ac4c2c197a9d110486e

**Comment by randombit** [comment]
> #0 0x0000555555dcd08d in update (this=0x0, 

It looks like for some reason `HashFunction::create` is returning null here. If you use `create_or_throw` instead, an exception will be thrown instead of returning null. Don't see any obvious reason for SHA-256 to not be available though, unless you are using a very minimized build.

The use of `static` declaring `secA`, `secB`, `secSharedKey` looks odd but I'm not sure if it would cause a problem.

**Comment by courteous** [comment]
Jack many thanks for the quick reply. I just tired create_or_throw instead of create but that did not work as well i.e.
`
unique_ptr<Botan::HashFunction> hash_fn(Botan::HashFunction::create_or_throw(hash_id));`


then i got 

```
unknown file: Failure
C++ exception with description "Unavailable Hash SHA-256" thrown in the test body.
```
Am i using this correctly ?

**Comment by randombit** [comment]
That's pretty strange. How are you building the library? In `build.h` there is a comment at top that gives the command line invocation for configure, can you post that? When you built the library, did you run the tests?

**Comment by courteous** [comment]
Hello Jack, 

many thanks for your help. You were right the problem was that i was missing the following modules in the during build i.e. I added --enable-modules=sha1,sha2_32,sha2_64,sha3 and all works now. Many thanks again.
