### ISSUE TITLE
Simple scrypt test

### ISSUE THREAD

**Issue by courteous** [randombit/botan#2291]
I am trying to run the following simple scrypt test and running into the error 

`botan/build/include/botan/scrypt.h:13:13: error: this header will be made internal in the future [-Werror]
 BOTAN_FUTURE_INTERNAL_HEADER(scrypt.h)
`

from the ( [hadbook](https://botan.randombit.net/handbook/api_ref/pbkdf.html#scrypt) ) I have read that the scrypt method can be called directly from the namespace Botan starting from version 2.7.0. i.e.

> 
> Scrypt is not supported through PBKDF, only PasswordHash, starting in 2.8.0. In addition, starting in version 2.7.0, scrypt is available with this function:
> void scrypt(uint8_t output[], size_t output_len, const std::string &password, const uint8_t salt[], size_t salt_len, size_t N, size_t r, size_t p)

How can i mitigate this error, in order to use scrypt. 

```
#ifndef SCRYPT_TEST_H_
#define SCRYPT_TEST_H_

#include <gtest/gtest.h>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include <botan/bigint.h>
#include <botan/hash.h>
#include <botan/scrypt.h>

using namespace Botan;
namespace test::scrypt {

TEST(Scrypt, scriptSimpleHash) {
    // using recommended parameters https://botan.randombit.net/handbook/api_ref/pbkdf.html#scrypt
    size_t N = 32768;
    size_t r = 8;
    size_t p = 1;
    size_t dkLen = 32; // DesiredKeyLen this will match the output of sha-256 i.e. 256 bits / 8 = 32 bytes.

    const BigInt salt("0x72616e646f6d53616c74");   // randomSalt in hex
    const vector<uint8_t> saltVector = BigInt::encode(salt);
    size_t salt_size = saltVector.size();

    const string password = "SecurePassword;)";

    vector<uint8_t> output((uint32_t)dkLen);
    Botan::scrypt(
    			output.data(),
			dkLen,
    			password.c_str(),
			saltVector.data(),
			salt_size,
                        N,
			r,
			p
			);


}

}

#endif /* SCRYPT_TEST_H_ */
```

**Comment by courteous** [comment]
can someone confirm if I am using scrypt correctly in the above example?

**Comment by randombit** [comment]
Your usage of scrypt here is fine. The warning is just a heads up that in a future incompatible release the header will go away and you should instead use scrypt via `PasswordHash` interface.

**Comment by randombit** [comment]
For now I have removed the deprecation warning to scrypt.h it will be reapplied in a few releases after documentation has been updated.

**Comment by randombit** [comment]
The documentation and examples now describe the non-deprecated interface, but the current interface continues to work. Closing.
