### ISSUE TITLE
Get uncompressed ECDSA public key 

### ISSUE THREAD

**Issue by peterchen-cp** [randombit/botan#2292]
When generating an ECDSA key pair, they are apaprently stored in a compressed format. 

Can I get the uncompressed public key bits from an ECDSA_PublicKey?  
(ECDH has public_value(...::UNCOMPRESSED), but I can't find anything similar for ECDSA)

I need to transmit the public key to an embedded library that only takes uncompressed keys.

**Comment by randombit** [comment]
`key.public_point().encode(PointGFP::UNCOMPRESSED)` should do the trick.

**Comment by randombit** [comment]
Feel free to reopen if you are still having problems
