### ISSUE TITLE
MacOS: #2294 broke tests

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#2300]
macOS Catalina 10.15.3, Xcode-11.3.1, current master.
```
. . . . .
dyld: Library not loaded: /opt/local/lib/libbotan-2.13.dylib
  Referenced from: /Users/ur20980/Src/botan/./botan-test
  Reason: image not found
```

I expected that one wouldn't be able to run `./botan` without installing it first - but I didn't expect that one would have to install before testing.

**Comment by reneme** [comment]
Would it be a reasonable compromise for you to add a `make check` target that does the dynamic library gymnastics transparently?

**Comment by mouse07410** [comment]
@reneme I think so.

Or the README (and the docs) should be clear that even the tests won't work without some dynamic library gymnastics - and describe exactly what should be done.

**Comment by reneme** [comment]
@mouse07410 Does the referenced patch do the job for you?

**Comment by randombit** [comment]
Assuming `make check` is sufficient, closing
