### ISSUE TITLE
Building Botan for STM32 Cortex-M4 

### ISSUE THREAD

**Issue by saiftyfirst** [randombit/botan#2303]
Sub-issue 1:
I am trying to build botan into a library that will be used on an STM32 Cortex-M4. The recommended compiler for the microcontroller is arm-eabi-none-g++. 

According to the build-data files, I understand that the library does not support environment I am using. I would just like to confirm that or whether it is actually possible to it ? If so, any hints in the right direction would be great!

Sub-issue 2:
I would like to configure botan to run on a raspberry pi zero w (cm3) running a compatible linux distribution. I will cross-compile from an ubuntu system, so would be great if you could specify the combination of options I need for the configure script, namely --cpu, --os, --arch

**Comment by randombit** [comment]
It's not supported right now but it is probably very easily doable. I have an arm-eabi-none-g++ cross compiler installed though it doesn't seem to generate working binaries (even compiling `void main() {}` fails with an undefined reference to `_exit`, not sure why) but I was able to get everything to build up to the linking step with a few small patches. I have to run but I can post them tonight.

Some qs
- M4 doesn't have NEON, correct?
- This env is basically bare metal with no functionality for filesystem access etc? That's unfortunate in that the tests rely on filesystem access, I have an idea how to fix it for cases like this but it would be a bit of work and I haven't had time.
- General comment, you will need some solution for entropy gathering. Possibly the board you are using has onboard RNG that you can access?

For the Pi Zero, I think you would want something like

CXX=name-of-cross-compiler ./configure.py --cpu=arm32 --os=linux --disable-neon

**Comment by saiftyfirst** [comment]
Yes, you are correct on the first two. I would have to look into the random number generator.

Thanks, looking forward to the patches as well.

**Comment by randombit** [comment]
@saiftyfirst with #2304 merged we now have have support --os=none and CI confirms at least that the library builds with a arm-none-eabi gcc.

**Comment by saiftyfirst** [comment]
@randombit, I want to build the library for an armhf architecture. I do not see this is the build-data folder. What can I do ?

**Comment by randombit** [comment]
You need `--cpu=arm32` plus some combination of 

* ``--with-endian=little`` / ``--with-endian=big``
* possibly: ``--disable-neon``
* possibly: ``--extra-cxxflags=<whatever you might want passed to gcc, ex -mtune=...>``

**Comment by randombit** [comment]
Closing this issue as stale. I think everything works here now, or at least our `arm-none-eabi-g++` CI build works fine.
