### ISSUE TITLE
[Usage] Serving multiple Clients & Including CRLs

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#2313]
I have a problem.

With only one Client serving it works. But the Problem is after closing and connect again it stops working.
In sequential serving I could just destroy Server Object and create a new one after receiving close_notify. But serving two clients does not work on one Server. So I tried to create for every client one server and recognize the input via std::map<Network::Address,DTLS::Server*> 

`cpp
void koala::Network::UDP::DTLS::ServerWorker::run()
{
	Server* serv = new Server(this->sock, this->informations, this->policySettings);
	while (!this->quit) {
		std::vector<uint8_t> buffer;
		auto from = this->sock->receiveFrom(buffer);
		if (this->servers.find(from) == this->servers.end()) {
			this->servers[from] = serv;
			this->servers[from]->setFrom(from);
			this->servers[from]->setupCallback(this->foo_callback);
			//serv = new Server(this->sock, this->informations, this->policySettings);
		}
		(this->servers[from])->dataReceived(buffer);
	}
}`

but if I uncomment the serv = new ... in the while loop it stops serving any client. Is Botan::TLS::Server a kind of Singleton which disallows multiple instances?

Is there another event to show a connection/session is closed/timeouted except close_notify?

My Second question is:
I have not found CRL in the Credentials_Manager. Where do I include a CRL (Revoke List) so it disallows Certificates which were revoked?

Greetings

**Comment by randombit** [comment]
`TLS::Server` is certainly not a singleton and yes the idea is that each instance of `TLS::Server` handles exactly one server connection over its lifetime. For DTLS if you provide input to the wrong channel it will be silently ignored which may explain the behavior you are seeing.

The only event is for closed, which you can also check using `Server::is_closed()`. You can detect DTLS handshake timeouts/retries by the return value of `Server::timeout_check`, returning true if we are retrying.

For CRL checking (or other similar things like OneCRL, CT, Perspectives, etc) override `Callbacks::tls_verify_cert_chain` and perform whatever logic is desired.

**Comment by seppy87** [comment]
Hallo,
thanks. now I changed the map to std::map<std::string,DTLS::Server> and it worked to serve multiple clients.

the string is constructed = std::string rec [for recognization] = from.getIP()+":"+std::to_string(from.getPort);
the other mentioned things I will try now :)

**Comment by lieser** [comment]
As this has been inactive for a while I'm assuming your questions are answered. If not please reopen the issue.
