### ISSUE TITLE
[USAGE] DTLS Server | Client coorperation

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#2315]
Here is my code for DTLS Client:
https://paste.ee/p/Oufuz

And here is my code for DTLS Server:
https://paste.ee/p/BSMcg

KoalaSocket is just a wrapper for the normal WinSocks and Linux Sockets so I don't need to rewrite it for both systems
Utils are used for string conversions between char, char16_t, char32_t and wchar_t strings and vector of uint8_t to std::string and vice versa operations.

the _config.hpp files only contains DTLS_CLIENT_API definitions and DTLS_SERVER_API definitions and afaik the client have botan includes there

The DTLS Server works with the DTLS Example of Qt without problems (unchanged example from their site).

But botan-cli and my client are throwing this error: "Certificate did not match ciphersuite"

while my Server says:
add new Server=127.0.0.1:50197
TYPE=tls-server
CONTEXT=
1. CERT KEY TYPE =RSA
TYPE=tls-server
CONTEXT=
1. CERT KEY TYPE =ECDSA
TYPE=tls-server
CONTEXT=
1. CERT KEY TYPE =DSA
illegal_parameter

what is to be changed so it accepts?

Edit:
I have changed that the server is return this->certs if RSA is requested and {} in case of other.

now Server Hello Done appears but the message that the data can'T be sent on inactive connection,

**Comment by seppy87** [comment]
Now I changed cert_chain to return an empty vector return {};

But now it throws an Exception: No PSK set for identity

**Comment by lieser** [comment]
As this has been inactive for a while I'm assuming your questions are answered. If not please reopen the issue.
