### ISSUE TITLE
Add support for Skein's keyed mode of operation

### ISSUE THREAD

**Issue by wernerd** [randombit/botan#2319]
While working on some software which uses various HMAC algorithms I found an incompatibility between the results of Botan Skein HMAC and the results produced by the Skein reference implementation.

Checking the code shows that Botan uses a key schedule to compute a Skein HMAC in the same way it does it for SHA-256 for example. According to the Skein paper (http://www.skein-hash.info/sites/default/files/skein1.3.pdf) chapter 2.6, a Skein MAC should not use a key schedule because Skein optimizes MAC computations:

> ...
> Instead of starting with zero and processing the configuration block, start with zero, process the key, and then the configuration block. Or, looking at it the other way, Skein hashing is simply Skein-MAC with a null key. 
> ...

The Skein reference implementation provides an API to compute a Skein MAC:
```
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/* init the context for a MAC and/or tree hash operation */
/* [identical to Skein_256_Init() when keyBytes == 0 && treeInfo == SKEIN_CFG_TREE_INFO_SEQUENTIAL] */
int Skein_256_InitExt(Skein_256_Ctxt_t *ctx,size_t hashBitLen,u64b_t treeInfo, const u08b_t *key, size_t keyBytes)
{
...
}
```
To me it seems that the Botan Skein implementation is not complete in this regard and misses the necessary function to compute a real Skein MAC as implemented in the reference implementation.

**Comment by mouse07410** [comment]
You don't need HMAC with SHA-3 candidates.

**Comment by randombit** [comment]
Yes `H(k||m)` is fine for Skein [or Keccak, Blake2b etc] but that also is not Skein's keyed mode, which uses iirc a distinct tweak value to process the key bytes.

**Comment by wernerd** [comment]
Actually yes - we use Skein keyed mode in ZRTP protocol implementation as one of the possible MAC algorithms when negotiating the various algorithms. The goal of the project is to reduce the number of crypto, MAC etc modules and have only one library which supports the required algorithms. We think about amalgamation/minimized feature options to simplify compilation/building on different systems such as Android, iOS, Mac, Linux, Windows.

We use the keyed mode as a MAC (right, it's not an HMAC but Skein's keyed mode). In the reference implementation the difference between a normal hash and keyed mode is a few lines of code. 

Just for info here the function of the reference implementation which adds the key as a tweak before hashing the data:

```
int Skein_512_InitExt(Skein_512_Ctxt_t *ctx,size_t hashBitLen,u64b_t treeInfo, const u08b_t *key, size_t keyBytes)
{
    union
    {
        u08b_t  b[SKEIN_512_STATE_BYTES];
        u64b_t  w[SKEIN_512_STATE_WORDS];
    } cfg;                              /* config block */

    Skein_Assert(hashBitLen > 0,SKEIN_BAD_HASHLEN);
    Skein_Assert(keyBytes == 0 || key != NULL,SKEIN_FAIL);

    /* compute the initial chaining values ctx->X[], based on key */
    if (keyBytes == 0)                          /* is there a key? */
    {
        memset(ctx->X,0,sizeof(ctx->X));        /* no key: use all zeroes as key for config block */
    }
    else                                        /* here to pre-process a key */
    {
        Skein_assert(sizeof(cfg.b) >= sizeof(ctx->X));
        /* do a mini-Init right here */
        ctx->h.hashBitLen=8*sizeof(ctx->X);     /* set output hash bit count = state size */
        Skein_Start_New_Type(ctx,KEY);          /* set tweaks: T0 = 0; T1 = KEY type */
        memset(ctx->X,0,sizeof(ctx->X));        /* zero the initial chaining variables */
        Skein_512_Update(ctx,key,keyBytes);     /* hash the key */
        Skein_512_Final_Pad(ctx,cfg.b);         /* put result into cfg.b[] */
        memcpy(ctx->X,cfg.b,sizeof(cfg.b));     /* copy over into ctx->X[] */
#if SKEIN_NEED_SWAP
        {
            uint_t i;
            for (i=0;i<SKEIN_512_STATE_WORDS;i++)   /* convert key bytes to context words */
                ctx->X[i] = Skein_Swap64(ctx->X[i]);
        }
#endif
    }
    /* build/process the config block, type == CONFIG (could be precomputed for each key) */
    ctx->h.hashBitLen = hashBitLen;             /* output hash bit count */
    Skein_Start_New_Type(ctx,CFG_FINAL);

    memset(&cfg.w,0,sizeof(cfg.w));             /* pre-pad cfg.w[] with zeroes */
    cfg.w[0] = Skein_Swap64(SKEIN_SCHEMA_VER);
    cfg.w[1] = Skein_Swap64(hashBitLen);        /* hash result length in bits */
    cfg.w[2] = Skein_Swap64(treeInfo);          /* tree hash config info (or SKEIN_CFG_TREE_INFO_SEQUENTIAL) */

    Skein_Show_Key(512,&ctx->h,key,keyBytes);

    /* compute the initial chaining values from config block */
    Skein_512_Process_Block(ctx,cfg.b,1,SKEIN_CFG_STR_LEN);

    /* The chaining vars ctx->X are now initialized */
    /* Set up to process the data message portion of the hash (default) */
    Skein_Start_New_Type(ctx,MSG);

    return SKEIN_SUCCESS;
}

``` 
The difference to a normal hash is just the few lines to setup the key. The code after the key setup is the same as for normal hash. We set the `treeInfo` parameter to `SKEIN_CFG_TREE_INFO_SEQUENTIAL`

**Comment by randombit** [comment]
OK the use case seems legit and you are already using it so I will look at addressing this in near future.

**Comment by wernerd** [comment]
Thanks for the feedback to implement key mode.

I did a more or less quick check of Botan's Skein implementation. Due to the fact that Botan implements Skein-512 only (and Threefish-512) Botan may not be able to support Skein-256 keyed mode due to the setup of the chain data. The Skein reference implementation uses four 64-bit words as chain data when doing a 256 bit MAC. Botan always uses eight 64-bit words as chain data. 

For normal hash is not an issue. According to my tests the results of the reference implementation and Botan are the same when using 256 bit hash output (normal hashing has no chain data). However in keyed mode this seems to be an issue. 

As per Skein reference implementation the keyed mode uses Skein-256 (using four 64-bit chain words) for hash output <= 256 bit, uses Skein-512 (using eight 64-bit chain words) for hash output  256 > output size <= 512, and Skein-1024 (using sixteen 64-bit chain words) for has output sizes between > 512 and <= 1024.

**Comment by randombit** [comment]
Oh dear. Well first that's really weird of the Skein spec, given that all variants of the Skein hash support arbitrary output lengths. But also means this issue is significantly more complex, if you need Skein-256/Threefish-256, than what I had expected which was just adding a keyed mode to current Skein-512.

I suppose I'd accept a patch series adding Threefish-256 -> Skein-256 -> Skein-MAC but I will certainly not have free time to do it myself.

**Comment by wernerd** [comment]
I have threefish-256, -512 -1024 implementation (encrpyt/decrypt) for C, go, and Java on my system :-) . Let me check if I can bring over the missing parts to Botan
