### ISSUE TITLE
2.15.0 release

### ISSUE THREAD

**Issue by randombit** [randombit/botan#2327]
Release on July 6, 2020 freeze starting June 26th.

Focus on TLS/DTLS issues

- Review/merge #2320
- Review/merge #2284 
- #2316 
- #2310 
- tls-fuzzer in CI
- finish hash2curve

**Comment by nunojpg** [comment]
Closed with https://github.com/randombit/botan/commit/3ed6eaa3c1236aed844f5475e2df8b89b3286ac4
