### ISSUE TITLE
Amalgamated Build Fails on GCC <= 6.4 and older apple-clang

### ISSUE THREAD

**Issue by hrantzsch** [randombit/botan#2328]
Building Botan 2.14 fails on older compilers when configured with `--amalgamation`.

GCC fails with
```
botan_all.cpp: In static member function 'static void Botan::SIMD_8x32::transpose(Botan::SIMD_8x32&, Botan::SIMD_8x32&, Botan::SIMD_8x32&, Botan::SIMD_8x32&, Botan::SIMD_8x32&, Botan::SIMD_8x32&, Botan::SIMD_8x32&, Botan::SIMD_8x32&)':
botan_all.cpp:5562:62: internal compiler error: in convert_move, at expr.c:316
       __m256i BOTAN_FUNC_ISA("avx2") handle() const { return m_avx2; }
                                                              ^
```

apple-clang 9 fails with
```
fatal error: error in backend: Cannot select: intrinsic %llvm.x86.aesni.aesenclast
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
```

We discovered this when trying to update the conan package (you can get the [full logs here](https://github.com/conan-io/conan-center-index/pull/1311)). I reproduced the issue locally with GCC 4.8 and GCC 5.5. The Conan-Center CI fails when using GCC 6.4. However, GCC 6.5 is fine (tested locally).

**Comment by hrantzsch** [comment]
I added a Travis target to use amalgamation with gcc 4.8: https://travis-ci.org/github/hrantzsch/botan/jobs/673340516

**Comment by randombit** [comment]
Yeah I can repro the GCC ICE locally with 5.4 and 6.4.1. I'm not sure what we can do here especially given it works in a standard build. It also works if I do eg `--amal --mini --enable-modules=shacal2_avx2`. It seems at some point the code complexity increases and then we somehow trigger whatever GCC bug this is. So it seems unlikely that there is a localized fix. For the Conan builds I'd vote to just check for GCC < 7 and if so, disable AVX2 support. This just reduces performance for the handful of algos that have AVX2 implementations and doesn't have security implications.

The Clang issue is probably unrelated. But also a weird one. Literally the only places where we use aesenclast are in the 3 `AES_XXX::encrypt_n` implementations. And all three of those have annotations to use the `__attribute__((target(x)))` to enable AES-NI. First thing to try to test this (assuming you have a way of reproducing) is to disable `aes_ni` module and see if that resolves it. If it doesn't, then something very strange is going on. If it *does* fix it, then ... I'm again not sure how to proceed outside of disabling AES-NI support on affected compilers. This sounds somewhat terrible I know, but vperm AES will kick in to still provide a constant-time AES, albeit much slower than using hardware instructions.

Another q though, why are the Conan builds using amalgamation? Maybe the "fix" is not to disable AVX2 or AES-NI but just disable use of amalgamation on affected compilers?

**Comment by hrantzsch** [comment]
That's true, disallowing the amalgamated build with older GCCs should be fine for Conan.

As for Clang, we don't have an old Xcode installation available to try it out locally. Maybe I can convince Travis to try it for us.

**Comment by hrantzsch** [comment]
Indeed, Travis' xcode9.3 image runs apple-clang 9. But I could not reproduce the issue yet.

**Comment by hrantzsch** [comment]
Accidentally hit close issue...
I'll try again to reproduce it later, I think I need to use the amalgamation build.

**Comment by hrantzsch** [comment]
I was able to reproduce the apple-clang 9 issue on Travis ([see here](https://travis-ci.org/github/hrantzsch/botan/jobs/674738501#L313)). It fails only in the amalgamated build with AES-NI. Without amalgamation, AES-NI is fine; without AES-NI, the amalgamated build is fine.

Regarding Conan, I will simply not allow amalgamation on affected compilers, as you suggested.

I take it there is not much we can do on Botan side, so we probably don't need that configuration in the Botan CI.
