### ISSUE TITLE
BigInt::random_integer tests are non-deterministic, failing the CI

### ISSUE THREAD

**Issue by tiwoc** [randombit/botan#233]
The "Bigint random_integer" test in `src/tests/catchy/test_bigint.cpp` can fail even if everything is okay: It checks the distribution of 10'000 random digits and fails when any digit is outside of the 9-11% range.

[Example CI failure](https://travis-ci.org/randombit/botan/builds/73431381)

I'd suggest to not include any non-deterministic tests in the test suite that is automatically executed when running botan-tests, so that users don't get confused and CI systems don't fail randomly.

**Comment by webmaster128** [comment]
Looks like we need to make the given test weaker. While 9-11 % is not wide enough, the [initial bug](https://github.com/randombit/botan/issues/108) was leading to results between 8.9 % and 12.8 %. So 8 % <= ratio <= 12 % might be good.

Additionally we might need to pull the hardcore mathematics as discussed in https://github.com/randombit/botan/issues/108.

**Comment by webmaster128** [comment]
No problems for a long time now.
