### ISSUE TITLE
terminate called after throwing an instance of 'Botan::PRNG_Unseeded'

### ISSUE THREAD

**Issue by GaoGGGQY** [randombit/botan#2330]
I met a problem like this, has anybody met this before or give me some idea.

terminate called after throwing an instance of 'Botan::PRNG_Unseeded'
  what():  PRNG not seeded: HMAC_DRBG(HMAC(SHA-384))
Aborted (core dumped)

./configure.py --without-os-feature=threads,thread_local,posix1,filesystem,getauxval --minimized-build --disable-shared-library --enable-modules=ecdsa,auto_rng,ed25519,eckcdsa --link-method=copy

very thankful for any help for this :)

**Comment by randombit** [comment]
To use a userspace PRNG you must also enable at least one entropy source such as `system_rng`.
