### ISSUE TITLE
so_abi_version and release version mismatch

### ISSUE THREAD

**Issue by paolostivanin** [randombit/botan#2332]
Hi,
is it expected that the library version differs from the release version?

https://github.com/randombit/botan/blob/ca5780773c7a673e3457c5bb6fec38c54eab1fd2/src/build-data/version.txt#L5

Thanks

**Comment by randombit** [comment]
In this case yes, ABI version is bumped if ABI has changed but (AFAIK) there were no ABI changes between 2.13.0 and 2.14.0
