### ISSUE TITLE
[Question] How to export RSA private key in traditional format?

### ISSUE THREAD

**Issue by pgp** [randombit/botan#2335]
Currently, I'm able to generate a RSA key of a given bitlength, and export it in PKCS8 format, with the following:

```cpp
    int keySize = 2048;
    Botan::AutoSeeded_RNG rng;
    Botan::RSA_PrivateKey prv(rng,keySize);
    std::string prv_s = Botan::PKCS8::PEM_encode(prv);
    // then, write prv_s to file...
```

Is there any way to export the same key in "traditional" format instead?
Since there is a bit of confusion as for naming, I'm referring to the format that starts with "-----BEGIN RSA PRIVATE KEY-----", as discussed [here](https://crypto.stackexchange.com/questions/46893/is-there-a-specification-for-the-begin-rsa-private-key-format)

**Comment by randombit** [comment]
I think that encoding is the same as the inner encoding of PKCS8 so you could get it with `prv.private_key_bits()`, then PEM encode using `PEM_Code::encode(data, "RSA PRIVATE KEY")`

To decode you can PEM decode then pass the DER blob to the constructor https://github.com/randombit/botan/blob/master/src/lib/pubkey/rsa/rsa.cpp#L211

**Comment by pgp** [comment]
Well, just tried with an [online visualzer](https://8gwifi.org/PemParserFunctions.jsp), and the generated private key show similar structure to one generated with:
```sh
ssh-keygen -t rsa -b 2048 -m PEM
```
using a recent OpenSSH version. I'll do actual usage tests tomorrow for a further evidence.
For the sake of completeness, I'll also try generating EC keys with the proper label and test them.

**Comment by pgp** [comment]
Sorry for the delay, had forgotten to reply. The checks with RSA generated keys are OK, they work for key-based authentication at least on OpenSSH, [libssh](libssh.org) and SSHJ. For EC keys however, I think there is additional stuff in the private key payload, so the same strategy didn't work (actually, it worked only with OpenSSH, which has a more robust key type detection and works even with partially malformed data)
