### ISSUE TITLE
Botan Java Security Provider implementation (JCA/ JSSE)

### ISSUE THREAD

**Issue by yaziza** [randombit/botan#2339]
I have started with a JSP implementation for Botan this week. So far almost all hash algorithms are supported ( SHA-1, SHA-2, SHA-3, MD4, MD5, RIPEMD-160, BLAKE2b), HMAC is also implemented and i am currently working on AES.

You can find the code in my github repo: https://github.com/yaziza/botanj

If interested, i can transfer the repo here or send a pull request.

Feedback are highly appreciated.

And needless to say, contribution are more than welcome !

**Comment by randombit** [comment]
That's great to see, this is something several people have asked about.

I'm not sure if it makes sense to merge this here or not. Integrating the Java build with the rest might be more work/pain than is worthwhile, but I'll think on it further. In the meantime I've added a link in https://github.com/randombit/botan/wiki/Language-Bindings

**Comment by yaziza** [comment]
Thanks for linking the repo, that's what i want to achieve in order to get the attention of contributors.
