### ISSUE TITLE
Botan website is unavailable

### ISSUE THREAD

**Issue by alex** [randombit/botan#234]
Attempting to make a TCP connection fails:

```
~ $ telnet botan.randombit.net 80
Trying 66.228.45.112...
telnet: connect to address 66.228.45.112: Connection refused
Trying 2600:3c03::f03c:91ff:fe70:128c...
telnet: connect to address 2600:3c03::f03c:91ff:fe70:128c: No route to host
telnet: Unable to connect to remote host
```

**Comment by randombit** [comment]
Thanks. Looks like rolling over the log failed on Aug 01 because of an ABI incompatible upgrade to either OpenSSL or Apache itself, and systemd didn't think to try restarting. Restarted, back up now.

**Comment by alex** [comment]
Cheers, thanks!
