### ISSUE TITLE
Linker error while compiling application

### ISSUE THREAD

**Issue by veerjoladal** [randombit/botan#2343]
Hi,

I am trying to write a DTLS application using boost::asio and botan. During linking, I am getting lot of undefined reference errors. To narrow it down, I wrote a simple code as below:

```
#include <botan/rng.h>
#include <botan/auto_rng.h>

int main() {
    Botan::AutoSeeded_RNG rng;
}
```

Here's the gcc command:
`g++ -I/usr/local/include/botan-2 -fstack-protector -m64 -pthread -L/usr/local/lib -lbotan-2 -lboost_system -ldl -lrt test.cpp
`

Linker error:
```
/tmp/ccqvxtQs.o: In function `main':
test.cpp:(.text+0x15): undefined reference to `Botan::AutoSeeded_RNG::AutoSeeded_RNG(unsigned long)'
test.cpp:(.text+0x21): undefined reference to `Botan::AutoSeeded_RNG::~AutoSeeded_RNG()'
collect2: error: ld returned 1 exit status
```

`nm` command output on libbotan-2.so and test.o lists all these symbols.
Linker throws errors if I use any class from botan (i.e., issue is not specific to AutoSeeded_RNG).
 
The solution must be trivial, but am not able to figure it out. Many thanks for any help.

**Comment by randombit** [comment]
That's really strange. Everything you're doing here looks ok to me. And that `nm` lists the symbols is ... ??

How did you build/install the library? Can you paste full invocation of `configure.py` - if you have forgotten what you did the options used are pasted into the start of `build.h`

**Comment by veerjoladal** [comment]
I meant to say, `nm` on libbotan-2.so lists all the members of the class `Botan::AutoSeeded_RNG`.

This is the command I used for installation: `./configure.py --with-boost`.

**Comment by randombit** [comment]
Right sorry my response was unclear, I meant the fact that nm lists the symbols in the library but link fails claiming symbols are missing is really strange.

Can you try linking against static library `libbotan-2.a`? If that works/doesn't work/gives a different error, perhaps we'll gain a clue as to what is going wrong.

**Comment by veerjoladal** [comment]
If I link to static library, I get more linker errors:

```
# g++ -std=c++11 -I/usr/local/include/botan-2/ -fstack-protector -m64 -pthread -L/usr/local/lib  /usr/local/lib/libbotan-2.a asio_dtls.cpp
/tmp/ccoh9TOv.o: In function `Botan::RandomNumberGenerator::~RandomNumberGenerator()':
asio_dtls.cpp:(.text._ZN5Botan21RandomNumberGeneratorD2Ev[_ZN5Botan21RandomNumberGeneratorD5Ev]+0xb): undefined reference to `vtable for Botan::RandomNumberGenerator'
/tmp/ccoh9TOv.o: In function `Botan::System_RNG::name[abi:cxx11]() const':
asio_dtls.cpp:(.text._ZNK5Botan10System_RNG4nameB5cxx11Ev[_ZNK5Botan10System_RNG4nameB5cxx11Ev]+0x11): undefined reference to `Botan::system_rng()'
/tmp/ccoh9TOv.o: In function `Botan::System_RNG::randomize(unsigned char*, unsigned long)':
asio_dtls.cpp:(.text._ZN5Botan10System_RNG9randomizeEPhm[_ZN5Botan10System_RNG9randomizeEPhm]+0x15): undefined reference to `Botan::system_rng()'
/tmp/ccoh9TOv.o: In function `Botan::System_RNG::add_entropy(unsigned char const*, unsigned long)':
asio_dtls.cpp:(.text._ZN5Botan10System_RNG11add_entropyEPKhm[_ZN5Botan10System_RNG11add_entropyEPKhm]+0x15): undefined reference to `Botan::system_rng()'
/tmp/ccoh9TOv.o: In function `Botan::System_RNG::is_seeded() const':
asio_dtls.cpp:(.text._ZNK5Botan10System_RNG9is_seededEv[_ZNK5Botan10System_RNG9is_seededEv]+0xd): undefined reference to `Botan::system_rng()'
/tmp/ccoh9TOv.o: In function `Botan::System_RNG::accepts_input() const':
asio_dtls.cpp:(.text._ZNK5Botan10System_RNG13accepts_inputEv[_ZNK5Botan10System_RNG13accepts_inputEv]+0xd): undefined reference to `Botan::system_rng()'
/tmp/ccoh9TOv.o:asio_dtls.cpp:(.text._ZN5Botan10System_RNG5clearEv[_ZN5Botan10System_RNG5clearEv]+0xd): more undefined references to `Botan::system_rng()' follow
/tmp/ccoh9TOv.o:(.data.rel.ro._ZTVN5Botan10System_RNGE[_ZTVN5Botan10System_RNGE]+0x38): undefined reference to `Botan::RandomNumberGenerator::randomize_with_input(unsigned char*, unsigned long, unsigned char const*, unsigned long)'
/tmp/ccoh9TOv.o:(.data.rel.ro._ZTVN5Botan10System_RNGE[_ZTVN5Botan10System_RNGE]+0x40): undefined reference to `Botan::RandomNumberGenerator::randomize_with_ts_input(unsigned char*, unsigned long)'
/tmp/ccoh9TOv.o:(.data.rel.ro._ZTVN5Botan10System_RNGE[_ZTVN5Botan10System_RNGE]+0x60): undefined reference to `Botan::RandomNumberGenerator::reseed(Botan::Entropy_Sources&, unsigned long, std::chrono::duration<long, std::ratio<1l, 1000l> >)'
/tmp/ccoh9TOv.o:(.data.rel.ro._ZTVN5Botan10System_RNGE[_ZTVN5Botan10System_RNGE]+0x68): undefined reference to `Botan::RandomNumberGenerator::reseed_from_rng(Botan::RandomNumberGenerator&, unsigned long)'
/tmp/ccoh9TOv.o:(.data.rel.ro._ZTIN5Botan10System_RNGE[_ZTIN5Botan10System_RNGE]+0x10): undefined reference to `typeinfo for Botan::RandomNumberGenerator'
collect2: error: ld returned 1 exit status
```

**Comment by veerjoladal** [comment]
Even if I link to static library, I get the same errors:

```
# g++ -std=c++11 -I/usr/local/include/botan-2/ -fstack-protector -m64 -pthread -L/usr/local/lib -ldl -lrt  /usr/local/lib/libbotan-2.a test.cpp
/tmp/cckyTGwj.o: In function `main':
test.cpp:(.text+0x15): undefined reference to `Botan::AutoSeeded_RNG::AutoSeeded_RNG(unsigned long)'
test.cpp:(.text+0x21): undefined reference to `Botan::AutoSeeded_RNG::~AutoSeeded_RNG()'
collect2: error: ld returned 1 exit status
```

**Comment by randombit** [comment]
When you built did you run `botan-test`?

**Comment by veerjoladal** [comment]
No, I haven't

**Comment by veerjoladal** [comment]
I ran botan-test now. But there seems to be no problem. Got this result at the end
`Tests complete ran 2681661 tests in 17.53 sec all tests ok`

**Comment by randombit** [comment]
Are you sure there is not some additional set of Botan headers (eg in `/usr/include`) that are being picked up in your build? Also can you check what happens if you run `botan-test` with `LD_LIBRARY_PATH` set to `/usr/local/lib` ie forcing the tests to run agains the installed version of the lib

**Comment by veerjoladal** [comment]
I am sure that the headers and libraries are installed only to `/usr/local/` and there are no additional sets. Here's the output of `find` command.

```
# find /usr/ -name "*botan*"
/usr/local/bin/botan
/usr/local/include/botan-2
/usr/local/include/botan-2/botan
/usr/local/include/botan-2/botan/botan.h
/usr/local/lib/python2.7/site-packages/botan2.py
/usr/local/lib/pkgconfig/botan-2.pc
/usr/local/lib/libbotan-2.a
/usr/local/lib/libbotan-2.so.13.15.0
/usr/local/lib/libbotan-2.so.13
/usr/local/lib/libbotan-2.so
/usr/local/share/doc/botan-2.15.0
```

I ran `botan-test` after setting `LD_LIBRARY_PATH` to `/usr/local/lib`. All tests passed.

**Comment by veerjoladal** [comment]
I found out where was the problem. In `g++` command, when I mention the `libs` after the `cpp` file, then it compiles successfully.

This compiles and links successfully:
`g++ -I/usr/local/include/botan-2 -fstack-protector -m64 -pthread test.cpp -L/usr/local/lib -lbotan-2 -lboost_system -ldl -lrt`

But this fails at linking:
`g++ -I/usr/local/include/botan-2 -fstack-protector -m64 -pthread -L/usr/local/lib -lbotan-2 -lboost_system -ldl -lrt test.cpp` 

I am aware that the order in which libraries are linked is important. But this is the first time the order of libraries and source files caused a problem. If I remove all the `botan` content and retain only `boost::asio` content in my source file, then it links successfully irrespective of the order in which cpps and libs are mentioned.

If you have any more insights on this, please share. That will sure help a lot.

However, many thanks for your quick help! :)

**Comment by randombit** [comment]
Argh I totally missed that but yes I think this is expected because in general Unix/Linux `ld` is single pass, it goes through in the order specified on the command line and starts collecting lists of symbols which appear to be missing. Since at the point -lbotan-2 is encountered, there are no missing symbols which would be satisfied by including the lib, it is omitted entirely. Then it reached the end of the list and is missing symbols. You would think `ld` could track what symbols it has seen but already omitted as "unnecessary" and warn you about command line ordering, but no. That includes not just libraries but also .o or files that are about to be compiled to .o, afaik the linker doesn't really distinguish between system libs and something you just compiled, in terms of symbol lookup process. I'm pretty sure you would see the same behavior if you first compiled your `.cpp` file to `.o` with `g++ -c` then tried to link with it mentioned at the end of the invocation.

I'm not entirely sure why it worked for asio, but almost all of asio is inlined templates and if you happened to get "lucky" and your asio usage doesn't end up invoking anything from boost_system then the fact that boost system was also missing would not have been noticed by the linker.

Glad it's sorted now.
