### ISSUE TITLE
botan internal error occur when building qtcreator

### ISSUE THREAD

**Issue by hhnhhn117117** [randombit/botan#2350]
when building qtcreator from source, a error occur, the whole output from building process is so followed:
ubuntu@ubuntu:~/qt-creator-opensource-src-4.8.2$ make
cd src/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/src.pro ) && make -f Makefile 
make[1]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src'
cd shared/qbs/src/lib/corelib/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/lib/corelib/corelib.pro ) && make -f Makefile 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/lib/corelib'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/lib/corelib'
cd shared/qbs/src/lib/qtprofilesetup/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/lib/qtprofilesetup/qtprofilesetup.pro ) && make -f Makefile 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/lib/qtprofilesetup'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/lib/qtprofilesetup'
cd shared/qbs/src/app/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/app.pro ) && make -f Makefile 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app'
cd qbs/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs/qbs.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs'
cd qbs-create-project/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-create-project/qbs-create-project.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-create-project'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-create-project'
cd qbs-setup-android/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-android/qbs-setup-android.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-android'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-android'
cd qbs-setup-toolchains/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-toolchains/qbs-setup-toolchains.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-toolchains'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-toolchains'
cd qbs-setup-qt/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-qt/qbs-setup-qt.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-qt'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/qbs-setup-qt'
cd config/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/config/config.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/config'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/config'
cd config-ui/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/config-ui/config-ui.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/config-ui'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app/config-ui'
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/app'
cd shared/qbs/src/libexec/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/libexec/libexec.pro ) && make -f Makefile 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/libexec'
cd qbs_processlauncher/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/libexec/qbs_processlauncher/qbs_processlauncher.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/libexec/qbs_processlauncher'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/libexec/qbs_processlauncher'
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/libexec'
cd shared/qbs/src/plugins/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/plugins.pro ) && make -f Makefile 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins'
cd generator/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/generator.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator'
cd clangcompilationdb/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/clangcompilationdb/clangcompilationdb.pro ) && make -f Makefile 
make[4]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/clangcompilationdb'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/clangcompilationdb'
cd makefilegenerator/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/makefilegenerator/makefilegenerator.pro ) && make -f Makefile 
make[4]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/makefilegenerator'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/makefilegenerator'
cd visualstudio/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/visualstudio/visualstudio.pro ) && make -f Makefile 
make[4]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/visualstudio'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator/visualstudio'
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/generator'
cd scanner/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/scanner.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner'
cd cpp/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/cpp/cpp.pro ) && make -f Makefile 
make[4]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/cpp'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/cpp'
cd qt/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/qt/qt.pro ) && make -f Makefile 
make[4]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/qt'
make[4]: Nothing to be done for 'first'.
make[4]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner/qt'
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins/scanner'
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/src/plugins'
cd shared/qbs/ && ( test -e Makefile.static || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile.static /home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs/static.pro ) && make -f Makefile.static 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/shared/qbs'
cd libs/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/libs.pro ) && make -f Makefile 
make[2]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs'
cd botan/ && ( test -e Makefile || /home/ubuntu/Qt5.12.8/bin/qmake -o Makefile /home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/botan.pro ) && make -f Makefile 
make[3]: Entering directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan'
cd /home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/build && python /home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py --cc=gcc --cc-bin=g++ --amalgamation --minimized-build --disable-shared --enable-modules=aes,aes_ssse3,auto_rng,bigint,block,cbc,ctr,des,dh,dsa,ec_group,ecdh,ecdsa,entropy,filters,hmac,mode_pad,pubkey,rsa,sha1,sha1_sse2,sha1_x86,sha2_32,sha2_32_x86,sha2_64,simd,system_rng,emsa_pkcs1,pbes2,pbkdf2 --without-documentation --cxxflags='-pipe -Wno-noexcept-type -Wno-unused-parameter -fPIC -O3'
WARNING: Failed to load any module policy files
   INFO: /home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py invoked with options "--cc=gcc --cc-bin=g++ --amalgamation --minimized-build --disable-shared --enable-modules=aes,aes_ssse3,auto_rng,bigint,block,cbc,ctr,des,dh,dsa,ec_group,ecdh,ecdsa,entropy,filters,hmac,mode_pad,pubkey,rsa,sha1,sha1_sse2,sha1_x86,sha2_32,sha2_32_x86,sha2_64,simd,system_rng,emsa_pkcs1,pbes2,pbkdf2 --without-documentation --cxxflags=-pipe -Wno-noexcept-type -Wno-unused-parameter -fPIC -O3"
   INFO: Autodetected platform information: OS="Linux" machine="aarch64" proc="aarch64"
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing target processor is a arm64 (use --cpu to set)
   INFO: Canonicalized CPU target aarch64 to arm64
   INFO: Auto-detected compiler version 7.5
   INFO: Auto-detected compiler arch arm64
   INFO: Target is gcc:7.5-linux-arm64
   INFO: Skipping (incompatible CPU): aes_ni aes_power8 aes_ssse3 rdrand_rng rdseed sha1_sse2 sha1_x86 sha2_32_bmi2 sha2_32_x86 simd_avx2
   INFO: Skipping (incompatible OS): getentropy win32_stats
   INFO: Skipping (not requested): aes_armv8 dev_random dyn_load proc_walk rdrand sha1_armv8 sha2_32_armv8 x509
   INFO: Loading modules: aes asn1 auto_rng base base64 bigint block cbc cpuid ctr des dh dl_algo dl_group dsa ec_group ecc_key ecdh ecdsa emsa1 emsa_pkcs1 emsa_pssr entropy filters hash hash_id hex hmac hmac_drbg kdf keypair mac mdx_hash mgf1 mode_pad modes mp numbertheory pbes2 pbkdf pbkdf2 pem pk_pad pubkey rng rsa sha1 sha2_32 sha2_64 simd stateful_rng stream system_rng utils
   INFO: Defaulting to assuming little endian
   INFO: Using symlink to link files into build dir (use --link-method to change)
  ERROR: Traceback (most recent call last):
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 3199, in <module>
    sys.exit(main(argv=sys.argv))
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 3193, in main
    do_io_for_build(cc, arch, osinfo, using_mods, build_paths, source_paths, template_vars, options)
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 3052, in do_io_for_build
    (amalg_cpp_files, amalg_headers) = AmalgamationGenerator(build_paths, using_mods, options).generate()
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 2617, in generate
    amalgamation_headers, included_in_headers, isa_headers = self._generate_headers()
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 2515, in _generate_headers
    pub_header_amalag = AmalgamationHeader(self._build_paths.public_headers)
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 2367, in __init__
    contents = AmalgamationGenerator.read_header(filepath)
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 2451, in read_header
    return AmalgamationGenerator.strip_header_goop(filepath, raw_content)
  File "/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/configure.py", line 2463, in strip_header_goop
    raise InternalError("No header guard start found in " + header_name)
**InternalError: No header guard start found in /home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan/../3rdparty/botan/src/lib/asn1/alg_id.h**

An internal error occurred.

Don't panic, this is probably not your fault! Please open an issue
with the entire output at https://github.com/randombit/botan

You'll meet friendly people happy to help!
Makefile:331: recipe for target 'build/Makefile' failed
make[3]: *** [build/Makefile] Error 1
make[3]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs/botan'
Makefile:62: recipe for target 'sub-botan-make_first' failed
make[2]: *** [sub-botan-make_first] Error 2
make[2]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src/libs'
Makefile:315: recipe for target 'sub-libs-make_first-ordered' failed
make[1]: *** [sub-libs-make_first-ordered] Error 2
make[1]: Leaving directory '/home/ubuntu/qt-creator-opensource-src-4.8.2/src'
Makefile:47: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2

p.s. actually I found alg_id existing in the  folder.
Something wrong!

**Comment by randombit** [comment]
Dup of #1763

I think the fix is to either upgrade Botan within Qt Creator source *or* run `dos2unix` on `src/lib/asn1/alg_id.h`.

**Comment by hhnhhn117117** [comment]
I use dos2unix to change all the header files to UNIX format, it works now.
Very thanks !
