### ISSUE TITLE
Linking error when doing amalgamation build? [help wanted]

### ISSUE THREAD

**Issue by OptoCloud** [randombit/botan#2373]
Hi,
I am creating a project that uses CMake,
so i am selecting the correct arguments for the selected build in CMake, then executing python from CMake.
I am doing this over building a static library, because building a static library can get complex on windows with msvc.

It runs the configure script properly, and builds on linux.
But it has linking issues on windows?

To replicate linking errors:
```
git clone https://github.com/OptoCloud/TestingRep.git
cd TestingRep
git submodule init
git submodule update
mkdir build
cd build
cmake ..
nmake -j4
```
Or
Clone it and open it in visual studio, then try to compile it

Edit:

Generated output from CMake results in this:
```
python configure.py --minimized-build --without-documentation --amalgamation --enable-modules=hex,ecdh,chacha,pubkey,base64,bcrypt,system_rng,stream,kdf2 --os=windows --cc=msvc --cpu=x86_64 --msvc-runtime=MT
```

**Comment by randombit** [comment]
Sorry I do not have a windows machine I can test this one. Can you post the error you are seeing along with MSVC version info (output of `cl` on command line should be sufficient)

**Comment by OptoCloud** [comment]
sure;
[Output_CL.txt](https://github.com/randombit/botan/files/4797409/Output_CL.txt)
[Output_CMake.txt](https://github.com/randombit/botan/files/4797410/Output_CMake.txt)

**Comment by OptoCloud** [comment]
Looks like you need to pass
```
--disable-shared
```
even when you do a amalgamation build

So final commands:
linux:
```
python configure.py --os=windows --cc=msvc --cpu=x86_64 --amalgamation --disable-shared --minimized-build --without-documentation --enable-modules=hex,ecdh,chacha,pubkey,base64,bcrypt,system_rng,stream,kdf
```

I have to confirm that this works later tho

**Comment by randombit** [comment]
> Looks like you need to pass `--disable-shared` even when you do a amalgamation build

Absolutely yes, especially on Windows.

We might want to have some kind of warning here - building via the amalgamation (eg building a DLL from botan_all.cpp) is also allowed and does work, but if you're taking the generated code and inserting into some other build system it will either hit errors (on Windows) or add some unnecessary overhead (Linux).

**Comment by OptoCloud** [comment]
This solved it, thanks!
