### ISSUE TITLE
argon2_check_pwhash too slow?

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#2382]
I did not due much due diligence before opening this issue, but:

With a hash generated with CLI botan gen_argon2 default parameters, the argon2_check_pwhash takes about 90ms to verify in my PC with a botan built with default parameters.

I'm not into Argon2 so much, but for example the following benchmark lists their worst case verify with at 32ms:

https://github.com/matthewhartstonge/argon2

Probably I'm comparing different things, but would appreciate any comments.

**Comment by randombit** [comment]
I think that Go code is using different parameters for their benchmark M=32768 p=1 t=1 (see https://github.com/matthewhartstonge/argon2/blob/master/argon2_test.go#L15) vs M=65536 p=1 t=1 for the Botan cli) the larger memory size should approximately double the overall computational cost.

Additionally, that Go code is using Go's x/crypto Argon2 code https://github.com/golang/crypto/tree/master/argon2 which has some SSE2/SSE4 x86-64 assembly. Whereas Botan's Argon2 is just generic code with no machine specific SIMD optimizations. On my desktop machine (an i7-6700K) Botan's Argon2id with M=32768 p=1 t=1 runs in ~29 msec vs reported 22 msec for same params on a slightly newer but approximately close machine (i7-7700) so SIMD optimization seems to provide a ~30-40% improvement in overall Argon2 performance here.

**Comment by nunojpg** [comment]
Thanks for the review Jack.
