### ISSUE TITLE
bogus -m64 in cflags

### ISSUE THREAD

**Issue by mittorn** [randombit/botan#2384]
Trying to build libbotan on x32 abi(x86_64 ilp32) system, but getting x86_64 binary
What i expected:
```
ABI_FLAGS      =  -fstack-protector -pthread
```
in Makefile
and ELF 32-bit LSB shared object, x86-64 in output
What i got:
```
ABI_FLAGS      =  -fstack-protector -m64 -pthread
```
in Makefile
and ELF 64-bit LSB shared object, x86-64 in output

**Comment by randombit** [comment]
Probably our auto-detection isn't working correctly and it is configuring for x86-64. You can check this by looking in configure.py output for a line like

>    INFO: Guessing target processor is a x86_64 (use --cpu to set)

Try an explicit target

`--cpu=x32`

BTW x32 is not really tested at all (I think *maybe* it is building in Debian) so there may be issues. If you run into problems happy to try to fix but it's all going to be blind as I don't have any x32 systems.
