### ISSUE TITLE
Sign data with CLI

### ISSUE THREAD

**Issue by gowi** [randombit/botan#2387]
Hi, I've tried to sign some data with a newly generated private key using the CLI as described [here](https://botan.randombit.net/handbook/cli.html#public-key-cryptography)
```
C:\botan> ./botan keygen --algo=RSA --params= --passphrase= --pbe= --pbe-millis=300 --provider= --der-out > key.private
C:\botan> ./botan sign --der-format --hash=SHA-256 --emsa= key.private license.txt
Error: PKCS #8 private key decoding failed with PEM: No PEM header found
```
Other try:
```
C:\botan> ./botan keygen --algo=RSA --params= --passphrase= --pbe= --pbe-millis=300 --provider= --der-out > key.private
C:\botan> ./botan pkcs8 --pub-out --der-out key.private
Error: PKCS #8 private key decoding failed with PEM: No PEM header found
```
What is wrong here?

**Comment by securitykernel** [comment]
Which version are you using? On 2.14.0 and on master I see an error, too, albeit a different one: `Error: PKCS #8 private key decoding failed with BER: Tag mismatch when decoding object got INTEGER/UNIVERSAL expected SEQUENCE/CONSTRUCTED`, which unfortunately is a known bug (#379). When reading a DER encoded key, the CLI always assumes it is encrypted, letting the parsing of an unencrypted key, as in your case, fail. Try encoding the unencrypted key in PEM format by omitting the `--der-out` parameter to `keygen`.

In general, you can shorten your command line by omitting all the optional parameters. The docs you reference print all parameters just to explain each and everyone to users. The following should work fine:

```
C:\botan> ./botan keygen --algo=RSA > key.private
C:\botan> ./botan sign key.private license.txt
```

**Comment by gowi** [comment]
Hi, for some reasons I need to handle keys in DER format. Even if I use an encrypted key, I got an error in Botan 2.15.0:
```
c:\botan>botan keygen --passphrase=test --der-out > key.private

c:\botan>botan sign --der-format key.private license.txt
Error: PKCS #8 private key decoding failed with BER: Value truncated
```

**Comment by randombit** [comment]
Sorry about the very long followup time here.

Part of the problem may have been the use of `--der-format` which for `sign`/`verify` gives not the format of the key but rather the encoding of the signature. This option only makes sense for ECDSA and similar schemes, and not for RSA. This may have led to some of the errors seen here. I just made a change to give a usage error in this situation.

I cannot replicate the problem in your comment from Aug 10:

```
$ ./botan keygen --passphrase=test --der-out > key.private
$ ./botan sign --passphrase=test  key.private license.txt
a6WPPHytLTE...
```

**Comment by randombit** [comment]
#3177 allows loading unencrypted DER keys via the cli

**Comment by randombit** [comment]
Closing - I believe this is addressed now in master.
