### ISSUE TITLE
Possible memory leak in GCM_Mode Constructor

### ISSUE THREAD

**Issue by onavratil-monetplus** [randombit/botan#2388]
In gcm.cppp
```
 GCM_Mode::GCM_Mode(BlockCipher* cipher, size_t tag_size) :
    m_tag_size(tag_size),
    m_cipher_name(cipher->name())
    {
    if(cipher->block_size() != GCM_BS)
       throw Invalid_Argument("Invalid block cipher for GCM");
    m_ghash.reset(new GHASH);
    m_ctr.reset(new CTR_BE(cipher, 4)); // CTR_BE takes ownership of cipher

    if(m_tag_size != 8 && (m_tag_size < 12 || m_tag_size > 16))
       throw Invalid_Argument(name() + ": Bad tag size " + std::to_string(m_tag_size));
    }
```
`cipher` parameter is passed as a raw pointer. However, there are possible exceptions thrown on the first few lines before it gets owned by CTR_BE that may render the memory still allocated while the pointer is unreachable (out of scope).
Moreover, even the caller cannot expect that he is ought to free the memory pointed by `cipher` in case of an exception in the constructor, since another exception can be thrown after the instantiation of `CTR_BE` which takes the ownership of `cipher`.

**Comment by randombit** [comment]
You're right thank you for pointing this out.

**Comment by onavratil-monetplus** [comment]
Hi again ~
I don't intend to be mean, but the issue is not really gone.

`new` can throw `std::bad_alloc` in here:
`m_ctr(new CTR_BE(cipher, 4))`
In this case, the constructor does not get called. I was not 100%sure about this so i wrote a little test:
```c++
#include <iostream>
#include <vector>

class Whatever{
public:
    static inline int counter = 0;
    int myNumber = ++counter;
    static inline int consCalled = 0;
    static inline int destCalled = 0;
    uint64_t memorySpan[0xFFFFFFF];
    uint64_t memorySpan2[0xFFFFFFF];
    uint64_t memorySpan3[0xFFFFFFF];
    Whatever(){
        std::cout << "Constructor called " << myNumber << std::endl;
        consCalled++;
    }
    ~Whatever(){
        if(myNumber > counter - 10)
            std::cout << "Destructor called " << myNumber << std::endl;
        destCalled++;
    }
};


int main(int argc, char ** argv){
    Whatever *myvar = nullptr;
    std::vector<Whatever *> v;
    try{
        while(true){
            std::cout << "Creating another" << std::endl;
            Whatever *some = new Whatever(); 
            std::cout << "Pushing another" << std::endl;
            v.push_back(some);
        }
    }
    catch(const std::bad_alloc &e){
        std::cout << "Got bad alloc.." << std::endl;
    }

    for(const auto &a: v){
        delete a;
    }
    std::cout << "cons/dest: " << Whatever::consCalled << "/" << Whatever::destCalled << std::endl;
    return 0;
}
```
Turns out from the output (in my setting):
```txt
Constructor called 21844
Pushing another
Creating another
Constructor called 21845
Pushing another
Creating another
Got bad alloc..
Destructor called 21836
Destructor called 21837
Destructor called 21838
Destructor called 21839
Destructor called 21840
Destructor called 21841
Destructor called 21842
Destructor called 21843
Destructor called 21844
Destructor called 21845
cons/dest: 21845/21845
```
See that the bad alloc is thrown by the `new` operator. 
If `new` fails, the object is NOT created, thus constructor/destructor are NOT called. (Else there would be "Constructor called..." between "Creating another" and "Got bad alloc..".

If the memory allocation is very tough, and `new CTR_BE` in the initializer list fails, then the Cipher * is unreachable and not deleted again... 

What I would suggest as a fix:
use std::unique_ptr<Cipher> as a parameter. This can be later passed either as

```C++
GCM_Mode::GCM_Mode(std::unique_ptr<BlockCipher> cipher, size_t tag_size) :
   m_tag_size(tag_size),
   m_cipher_name(cipher->name())
   m_cipher_name(cipher->name()),
   m_ctr(new CTR_BE(cipher.release(), 4)),
```
OR better if CTR_BE adopts the same signature with unique_ptr:
```C++
   m_ctr(new CTR_BE(std::move(cipher), 4)),
```
Note that this should still allow to construct the cipher from raw pointer (for backwards compatibility) because of unique_ptr implicit constructor like this:
```c++
GCM_Mode myCipher(new SomeBlockCipher())
```

I suspect that this is not the only place where raw pointers are used in `Botan`, so potentially also not the only vulnerable snippet. Using raw pointers when working in project that is designed to use exception is very tricky...

**Comment by randombit** [comment]
Yes I see what you mean. That seems hard to address without changing that parameter to be a `unique_ptr`, which we cannot do for compatibility reasons as this is a public API. In a future major release `gcm.h` will be internal [applications will have to create modes via the factory methods] and then that change is possible. I would not be surprised if we had a lot of issues along these lines [leaks when an allocation fails]
