### ISSUE TITLE
AEAD handling of tag length of 0 inconsistency

### ISSUE THREAD

**Issue by guidovranken** [randombit/botan#2391]
Instantiating a cipher with the strings `AES-128/CCM(0)` or `AES-128/GCM(0)` or `AES-128/EAX(1)` will throw an exception (invalid tag length), but `AES-128/EAX(0)` does not and silently configures the tag length to 16. Is this intentional or a bug, eg. shouldn't `AES-128/EAX(0)` throw an exception as well?

**Comment by randombit** [comment]
Bug, thanks. Don't know why the logic was like that.
