### ISSUE TITLE
RNG segfault for multi threaded application.

### ISSUE THREAD

**Issue by larssilven** [randombit/botan#2397]
I have developed a pkcs#11 proxy implementation that transfers p11 calls done by an application to a p11 implementation on another host (the server).
When I do a stress test using the [SoftHSM2](https://github.com/opendnssec/SoftHSMv2) p11 implementation on the server I got a segfault. See [gdb.txt](https://github.com/randombit/botan/files/5162224/gdb.txt).
I used the [p11speed](https://github.com/opendnssec/p11speed) tool on the client side. Testing with 100 threads with each thread trying to do 100 signings has always failed. I will estimate that something in between 10 to 20 signings is usually done before the segfault.
By applying [patch-softhsm2.txt](https://github.com/randombit/botan/files/5162379/patch-softhsm2.txt) to softhsm version 2.6.1 everything works fine. I have done 100 threads with 10000 signings for each thread.
So it seems to be something wrong with Botan::Stateful_RNG when used with multi threaded applications.
Using openssl instead of botan when building softhsm is also working fine.
But the strange thing is that p11speed is working if I test directly (not using the proxy) with softhsm-botan.

Cheers,
Lars

**Comment by randombit** [comment]
Is SoftHSM using a single shared `AutoSeeded_RNG` among multiple threads? That is not good. These objects do not serialize access.

Can you try

```
-	rng = new Botan::AutoSeeded_RNG();
+	rng = new Botan::Serialized_RNG(new Botan::AutoSeeded_RNG());
```

and see if that resolves the crash?

[Possibly not always serializing is a mistake, I considered adding locks here sometime in the pre-2.0 timeframe but rejected it due to overhead. Then again, at least on Linux uncontended locks are very fast, so maybe the overhead doesn't matter]

**Comment by larssilven** [comment]
Yes with the serialization the auto RNG is working.

Comparing the RNGs I get this result.
System RNG:
100 threads, 1000 signatures per thread, 877.77 sig/s (RSA_PKCS 2048 bits)
Serialized auto RNG:
100 threads, 1000 signatures per thread, 847.97 sig/s (RSA_PKCS 2048 bits)

I also got an idea why the proxy is not working while running without the proxy is working:
Each thread in the p11speed test is using its own session handle when accessing the p11. But in the proxy server there is one TCP socket thread for each p11 call that is currently handled by the softhsm p11 and each of these threads are reused when new calls are received.
I think that the SoftHSM creates an RNG for each session handle. If not using the proxy then each thread will have its own RNG. But when using the proxy then after a while one thread will get another RNG.

**Comment by larssilven** [comment]
I agree that sharing a session between threads could be asking for problems and this problem is confirming it.
But the PKCS#11 spec says nothing about that sharing session between threads should not be done. What it says it that a session can not be used simultaneously by more than one p11 function call (you got to wait for the result of a call until the session is used again).
With my proxy two pkcs11 calls with same session id is never made simultaneously but call with same session ID could be done on different threads.
I will not do anything to change the proxy to use just one thread for each session. It is working for all pkcs#11 that I have tied so for but softhsm/botan. And now I know how to patch softhsm to get this to work as well.
But it would be nice if you could configure AutoSeed_RNG to be thread safe as default.
I will provide you with a comparison of 'Botan::AutoSeeded_RNG()' with 'Botan::Serialized_RNG(new Botan::AutoSeeded_RNG())' from a tests with p11speed without my proxy.

**Comment by randombit** [comment]
> With my proxy two pkcs11 calls with same session id is never made simultaneously but call with same session ID could be done on different threads.

I agree that seems like something that should plausibly work. I'm not that familiar with the full PKCS11 spec so maybe there is something about this. It might be worth asking the SoftHSM developers, especially as they would have to be the ones to change the RNG type they instantiate.

> But it would be nice if you could configure AutoSeed_RNG to be thread safe as default.

I think we'll move to serializing the RNG by default on any platform with threading support enabled. I don't think this will require a new major release so it may happen relatively soon (eg by end of this year - I am very busy at Signal right now and don't have much time to work on this lib at the moment outside of simple bug fixes).

> I will provide you with a comparison of 'Botan::AutoSeeded_RNG()' with 'Botan::Serialized_RNG(new Botan::AutoSeeded_RNG())' from a tests with p11speed without my proxy.

That would be useful information thank you.

**Comment by larssilven** [comment]
Tests with and without your SoftHSM patch  using Debian botan version 2.15.0+dfsg-2+b1

With your patch:
./p11speed --module ./libsofthsm2-botan-patch.so --slot 2024065425 --threads 100 --iterations 500 --mechanism RSA_PKCS --pin user0 --keysize 2048 --sign
.....
100 threads, 500 signatures per thread, 1408.67 sig/s (RSA_PKCS 2048 bits)

Without your patch:
./p11speed --module ./libsofthsm2-botan.so --slot 2024065425 --threads 100 --iterations 500 --mechanism RSA_PKCS --pin user0 --keysize 2048 --sign
......
100 threads, 500 signatures per thread, 1375.34 sig/s (RSA_PKCS 2048 bits)

So this confirms that locking don't take too much time.

**Comment by randombit** [comment]
We've had an internal lock on RNGs since #2399 so I don't think there is anything further we can do here.
