### ISSUE TITLE
botan randomly ber encodes rsa privatekeys  of non standrad size in undecodable format

### ISSUE THREAD

**Issue by cryptgithub** [randombit/botan#2400]
i haven't tested standard ras keys sizes (1024,2048,3076,...)
but for our key size 3067
botan sometimes (1 in 50 or more) ber encodes rsa key in a way that will throw exception when loading the key later 
functions used to save :: Botan::PKCS8::BER_encode(RsaPriKey)
please note that this only happen 1 in 50-100 and usually ok so you need to test lots of time 
in attachment there is an example of the output char array that throws BERDecodeErr
[rsakey3067.txt](https://github.com/randombit/botan/files/5215449/rsakey3067.txt)
please note that i'm almost sure the keys are not corrupted when storing or .. because if corrupted it should throw exception when decoding from ecies (that has authenticated aes-gcm as symmetric-enc)

i've seen more than 20keys with this problem , i also tested and they can't be loaded with crypto++ too, can give a few2 more samples

thanks in advance 

more unrelated info about what our app does :
for my university class project i was writing a offline  message sending program encrypt message with aes and generates one rsa key for each 50 messages (encrypt aes keys with that generate rsa key),encrypts the rsa private keys with master ecies key 
then write message to flash disk or any other way and reciveres reads the message by decrypting rsa keys with ecies and aes from rsa and message from aes

**Comment by cryptgithub** [comment]
botan is ok my app had problem like the one you said 
very very sorry for taking your time both for reading this and testing 3067 keys

additional info (what was the bug):
encryption and decryption of rsa key was ok 
the thing was my app used }}}} to separate decrypted rsa keys in file and later use the }}}} and {{{{ to read rsa keys from one file  to decrypt messages (in other app) 

problem was that some times rsa keys the the above ended in "}" (0x7d) and there our app just search for first occurrence of }}}}
and removed last byes of rsa key detected as separation flag 



thanks for your idea it helped me find the problem 
sorry for creating false issue

**Comment by randombit** [comment]
No problem glad we were able to get things sorted
