### ISSUE TITLE
Undefined references when linking to the shared library with its full path name

### ISSUE THREAD

**Issue by louiz** [randombit/botan#2410]
With this simple dummy code:

```c++
#include <botan/tls_policy.h>

int main()
{
  Botan::TLS::Datagram_Policy a{};
}
```

And linking this way:
```bash
g++ test.cpp -I/usr/include/botan-2 /usr/lib/libbotan-2.so
```
We get these errors:
```
/usr/bin/ld: /tmp/ccT7MyBG.o:(.rodata._ZTVN5Botan3TLS15Datagram_PolicyE[_ZTVN5Botan3TLS15Datagram_PolicyE]+0x88): undefined reference to `Botan::TLS::Policy::abort_connection_on_undesired_renegotiation() const'
…
```
But with this command, it works just fine:
```bash
g++ test.cpp -I/usr/include/botan-2 -lbotan-2
```
I don’t know why this is the case, and if it’s really a problem from Botan or not, but I couldn’t find a difference in `ld`'s man page between the whole path and the -lname option; it’s supposed to work, I think.
So I’m clueless on this matter.

Also note, only SOME symbols are missing, because the errors are a lot fewer if we specify `/usr/lib/libbotan-2.so` than if we specify no library at all. Some other parts of botan link just fine.

**Comment by randombit** [comment]
As far as I know `-lxx` and directly naming the path are identical as far as `ld` is concerned.

However are you sure that `-lbotan-2` links to `/usr/lib/libbotan-2.so` and not another version of the library somewhere else in the library search path? That would explain why only some symbols are missing. Alternately, are you sure that the headers and installed library version are in sync?

**Comment by louiz** [comment]
Ok, I feel really stupid now, -lbotan-2 was using /usr/lib64/libbotan-2.so which is the correct one. The other one was an old version.
Thanks, and sorry for wasting your time.
