### ISSUE TITLE
Error while Linking Botan: undefined reference to `Botan::AEAD_Mode

### ISSUE THREAD

**Issue by vgarridosm** [randombit/botan#2414]
Good Morning,
I have a little project in Red Hat in order to learn Botan, but while linking the error undefined reference to `Botan::AEAD_Mode is shown.
My compiler line command is: g++ -I/opt/Botan-CCN/build/include -I/opt/Botan-CCN/build/include/botan -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"main.o" -o "main.o" "../main.cpp"
My Linker line command is: g++ -L/usr/local/lib -o "ValidationTest"  ./GCM.o ./Menu.o ./main.o   -lbotan-2

I can't see where is the error. Any help?

**Comment by randombit** [comment]
It looks like you are using headers from /opt/Botan-CCN but trying to link against a library installed into /usr/local/lib - are you sure these are the same version? Also, why not use the distro provided package?

**Comment by vgarridosm** [comment]
> It looks like you are using headers from /opt/Botan-CCN but trying to link against a library installed into /usr/local/lib - are you sure these are the same version? Also, why not use the distro provided package?

I can't use the distro package because I need a special version of Botan. I have the sources and includes in /opt/Botan-CCN but i have copy the .a that they give me inside /usr/local/lib. Must it be in another path?

**Comment by vgarridosm** [comment]
I move the header into /usr/local/include/botan-2. Inside this folder i have two folders botan and externals. But the same issue happens

**Comment by randombit** [comment]
Can you please post your source (or at least the portion that calls the library), the command line you provided to `configure.py`, as well as the exact error message you are seeing?

**Comment by vgarridosm** [comment]
This is the source code:
`void GCM::encryptPayload()
{
  std::unique_ptr<Botan::AEAD_Mode> enc = Botan::AEAD_Mode::create("AES-128/GCM(16)", Botan::ENCRYPTION);
  enc->set_key(theKey,32);
  enc->set_associated_data(theAAD,16);
  enc->start(theIV,12);
  Botan::secure_vector<uint8_t> pt(thePayload, thePayload+16);
  enc->finish(pt);

}`
The command line was:
`sudo python configure.py
sudo make -j30`

The exact error message is:
undefined reference to `Botan::AEAD_Mode::create(std::string const&, Botan::Cipher_Dir, std::string const&)'

**Comment by randombit** [comment]
So you are trying to link against the static lib. What is the output from

$ ar t /usr/local/lib/libbotan-2.a | grep aead

**Comment by vgarridosm** [comment]
> ar t /usr/local/lib/libbotan-2.a | grep aead

The output is:

modes_aead.o
modes_aead_ccm.o
modes_aead_chacha20poly1305.o
modes_aead_eax.o
modes_aead_gcm_clmul_cpu.o
modes_aead_gcm_clmul_ssse3.o
modes_aead_gcm.o
modes_aead_gcm_ghash.o
modes_aead_ocb.o

**Comment by randombit** [comment]
Did you build and run the tests?

**Comment by vgarridosm** [comment]
> Did you build and run the tests?

I have the test, but when i executed it the error ` error while loading shared libraries: libbotan-2.so.15: cannot open shared object file: No such file or directory` is shown

**Comment by randombit** [comment]
If in `/usr/lib` it should work since that is part of the standard library path. Not sure what the problem here would be. Did you `make install` it into /usr/lib, or copy it? If you copied it by hand, are you sure the symlinks are set correctly?

**Comment by vgarridosm** [comment]
I have resolved the problem. I built again the library and the error disappears.
