### ISSUE TITLE
[Question] How to verify signature with ECDSA?

### ISSUE THREAD

**Issue by vgarridosm** [randombit/botan#2427]
Hi, 
I'm trying to verify a signature using ECDSA.
I have a curve (p, a, b, gx, gy, q and h ), a public key (thePublicKey), a message (thePayload) and a signature (theSignature) given by MIRACL library.
My code is:
```c++
Botan::EC_Group aGroup( p, a, b, gx, gy, q, h, Botan::OID::from_string( "ECDSA" ) );
Botan::AlgorithmIdentifier anAlgo("ECDSA", Botan::AlgorithmIdentifier::USE_NULL_PARAM);
Botan::ECDSA_PublicKey aPublicKey(anAlgo, thePublicKey);
Botan::PK_Verifier aVerifier( aPublicKey, "EMSA1(SHA-512)" , Botan::DER_SEQUENCE);
aVerifier.update( thePayload );
 aVerifier.check_signature( theSignature ) 
```

When I execute it, Botan throws an error:

``
terminate called after throwing an instance of 'Botan::Decoding_Error'
  what():  Cannot handle ImplicitCA ECC parameters
``

I don't understand how can I do this verification. Any help?

**Comment by randombit** [comment]
> Botan::AlgorithmIdentifier anAlgo("ECDSA", Botan::AlgorithmIdentifier::USE_NULL_PARAM);
> Botan::ECDSA_PublicKey aPublicKey(anAlgo, thePublicKey);

This encodes a public key which cannot be decoded because the group is not known. The constructor taking an AlgorithmIdentifier is largely for internal use by code which decodes ASN.1 encoded keys. Notice that the group is not being passed to the 

Instead use the constructor which takes an `EC_Group` and a `PointGFp`. The PointGFp in turn is constructed by passing the group along with the affine x/y coordinates.

> Botan::EC_Group aGroup( p, a, b, gx, gy, q, h, Botan::OID::from_string( "ECDSA" ) );

This OID usage is wrong - the OID passed here is to identify the curve. Since it seems like you are using a non-standard curve (?) the OID should be left as the default (empty) parameter.

**Comment by vgarridosm** [comment]
So, is it not possible to load an extern public key?
The curve is standard, is brainpool512.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by randombit** [comment]
Perfectly possible.

Also if it's a standard curve no need to specify the params

```
EC_Group group("brainpool512r1")
PointGFp point(group, x, y);
ECDSA_PrivateKey key(point, group);
```

**Comment by vgarridosm** [comment]
> Perfectly possible.
> 
> Also if it's a standard curve no need to specify the params
> 
> ```
> EC_Group group("brainpool512r1")
> PointGFp point(group, x, y);
> ECDSA_PrivateKey key(point, group);
> ```

In this example, you create a ECDSA_PrivateKey but I still don't know how to charge my public key (variable thePublicKey in my code).
This is my new version of the code based on your comments but still don't work.

```c++
Botan::EC_Group aGroup("brainpool512r1");
std::vector<uint8_t>X(thePublicKey.begin(), thePublicKey.begin()+64);
std::vector<uint8_t>Y(thePublicKey.begin()+64, thePublicKey.end());
Botan::BigInt xInt(X);
Botan::BigInt yInt(Y);
Botan::PointGFp aPoint = aGroup.point(xInt, yInt);
Botan::ECDSA_PublicKey aKey(aGroup, aPoint);
Botan::PK_Verifier aVerifier( aKey, "EMSA1(SHA-512)");
aVerifier.update( thePayload );
aVerifier.check_signature( theSignature ) 
   
```
