### ISSUE TITLE
[Question] Different cipher value than expected

### ISSUE THREAD

**Issue by vgarridosm** [randombit/botan#2428]
Good morning,
I'm doing a RSA encryption but the cipher value result is different than expected, because I checked it with other libraries.
I don't know where is the failure.
```c++
 Botan::AutoSeeded_RNG aRNG;
 auto N = Botan::BigInt(thePublicKey);
 Botan::RSA_PublicKey aPublicKey(N,65537);

 Botan::PK_Encryptor_EME anEncryptor(aPublicKey,aRNG,"Rsa");
 Botan::secure_vector<uint8_t> aPayload(thePayload.begin(),thePayload.end());
 auto aCypherText = anEncryptor.encrypt(aPayload, aRNG);

```
I have an external Public Key (thePublicKey) and a message to encrypt (thePayload)
Any help?

**Comment by randombit** [comment]
OAEP is randomized so there is a different ciphertext each time even with key and message held constant

**Comment by vgarridosm** [comment]
So, How should I do it so that it is not random? What should I use?
Can you give me an example?

**Comment by randombit** [comment]
Non-randomized RSA encryption is a very bad idea. All normally used RSA encryption methods are randomized, because otherwise it is trivial to test if a particular plaintext encrypts to some ciphertext. Example given some ciphertext C, and you know the message is from some limited set (say either "yes" or "no") you just encrypt both "yes" and "no" (which is trivial since the RSA public key is public) and compare the resulting ciphertexts to the one you are interested in.

It might help if you explain what you are trying to accomplish.

**Comment by vgarridosm** [comment]
My intention is to encrypt a text with a particular public key using RSA and then compare it with the encryption generated by another library.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by randombit** [comment]
In that case you need to override the respective random number generators so that OAEP or PKCS padding uses the same pad each time.

**Comment by vgarridosm** [comment]
Override? How?

**Comment by randombit** [comment]
In Botan that's done by providing a custom RNG instance such as https://github.com/randombit/botan/blob/master/src/tests/test_rng.h#L24

For whatever other library you are testing, you would have to ask the developers.

**Comment by mouse07410** [comment]
Why don't you *encrypt* with Botan and *decrypt* with other library, to ensure it results in the original plaintext? Then vs. versa?

**Comment by vgarridosm** [comment]
I probe it, but didn't work. Still have problems to encrypt RSA using Botan

**Comment by vgarridosm** [comment]
I also encrypt using the other library and decrypt using Botan and I have the same problem. Botan doesn't gave me the correct payload.

```  c++
std::string Q = "0xe6b3e40e8269a6c00f7d6ddff7b823fe932bf11a0fe91a52840bba446f22c3dd175aef24f48ffaa2cf986897fda53beda78a99cc287448a20711060da5ac848bdf66aca4f6701e108b0941ea553cfee1000285b76b31056c045c60b52c679451bb263cfcf3de393bf2d4e6be174fd051dc4fbe58a76cd88bbd6b377f0607c2b935af95138402668c060c8a4021ef02961f880c30e48b9296045982bc2d96e19c8ee0716e1ddf435a5b63fb2c52fbfe2d68f0e5a18da2636709e3c890613257009507e87a6321711f9891de77abaa48d003a70ce6ab127630181685648805de87141fa71c6bcb563c5d52b11739a6029dbda41343fd3247b0d82eb094739bfe6946248862cc685f5be7530295d8520fee299a1d66a15a333db9ec5359dbe7af4e9538cf55ca63b67b12611c11cc0e3c4bafc0828200eddf89ae0a6c7c01a92c14adc6f6f2e622e39bcabe08266408f62bd55619dcdd0d762f1779a425ceac5bd77604b9f500427e31fcd3cfda008d0b23fe0605ec8d6d997392f48f73d97ddcb856e5bc447b752acb40c5883b065a6251b9069b47aad5d6aa48782d68b598524fb0a03e7e8984ee2b239c58f4a789d1ba12434bd8e65360dfe5eb28720945c7ad47b0357c79aaf6f2b7baec10e4c1e5131bd907f517c0e37be538066de944a34025ba5ed23e0fcd2f00a7c0ce1c1c1eff18b8ff08be0fc61217593635b805664e7f50d12b771d7e3de3335ffb4edede4c26c4fa7044776f22e3e516f2193ede4d785e87d0e8aabc92e6f10a71bc719336468ad1175cc9c42d025d8e465e23157cefd1667809047988bcdd71f76fadc3525f1e34ce0fad2582c057c375b93c753e608d9933a0adf5d88b33de811a1c837b2b9cca6b75e8af8e4e8dbf3492d8d282c2a14f69246255b0bd7af7d2a3eefced5e6c05fd92073dd7f7fbeed93cc0acefeab89b8d98bbddfcaefc10db81cca42497cb8647985942a0fd2c4d98a702d74c26994ad5a74da7b544fc28f10c3d33101741191df1e733c62448c60aa7e9d94bd5a6e4cfe18af8c8225830257f83a304e059506534acd0bffc665b91fbf50bf09166583572d1bb99ae0e27be66b7ff1ba35d149554a7a383511eba953c16280488eeac5a632537455fcd4af5a67d551c3d6b09e40656bb0c03026b7f2f0c9e76d34ebfc90e13487dbb1f49d523263efc003ebbd2970936ec7f2b2e4f0295c0ef4e8ea4987ff10a63007f281ed6dcf62fb1a38f40fc8bcb6a75fcf3a4a62758c0f246d37ae1a223b9593954931d2301568a1d7d30c7a83975e6a19dffcfc37bb2000e0a7e8e2b1b085b5400839b414d5a38a00888bb8488e11debd6b97abcda230000";
std::string Msg = "098825DEC8B4DAB5765348CEE92C4C6A527A172E4A4311399B0B02914E75822F1789B583180ADEADE98C200B7B7670D7B9FBA19946F3D8A7FC8322F80CF67C";
Botan::BigInt p(P);
Botan::BigInt q(Q);
Botan::BigInt e(65537);
Botan::RSA_PrivateKey aKey(p, q, e);
Botan::PK_Decryptor_EME dec (aKey, aRNG, "Rsa");
auto aCypherText = dec.decrypt(Botan::hex_decode(theCipheredPayload));
```

**Comment by randombit** [comment]
Your `Q` ends in `0000` and is definitely not prime.

"Rsa" padding isn't a thing, you would specify PKCS1 or OAEP depending on what you used to encrypt.

**Comment by vgarridosm** [comment]
I know that RSA is not correct, it is just an example.
This Q is the same that use another library. I'm completely stuck.

**Comment by randombit** [comment]
> I know that RSA is not correct, it is just an example.

Can you decrypt the ciphertext with whatever other library you are using, with this invalid Q? Seems unlikely.

**Comment by vgarridosm** [comment]
Yes, I can.

**Comment by mouse07410** [comment]
I suggest re-doing this inter-library test with valid P and Q. 

And posting the correct code, ideally complete enough to compile and run, so others could try to reproduce the results on their platforms.
