### ISSUE TITLE
Hundreds of errors when compiling with Qt

### ISSUE THREAD

**Issue by binex-dsk** [randombit/botan#2436]
Normally, I can build my project just fine. But when I added some Qt stuff, and tried to compile it with qmake's generated Makefile, I get over 600 errors that I have found no way to fix. Errors are attached.

[ERRORS.txt](https://github.com/randombit/botan/files/5452584/ERRORS.txt)

I've tried for a few days and have found no solution to this. No matter what I get those secure_vector errors and more. What's wrong?

**Comment by randombit** [comment]
This is pretty weird. Are you sure there is not something wrong with your compiler install? Because errors like

```
/usr/include/c++/10.2.0/cstring: At global scope:
/usr/include/c++/10.2.0/cstring:77:11: error: ‘memchr’ has not been declared in ‘::’
   77 |   using ::memchr;
      |           ^~~~~~
/usr/include/c++/10.2.0/cstring:78:11: error: ‘memcmp’ has not been declared in ‘::’
   78 |   using ::memcmp;
      |           ^~~~~~
```

makes it appear that even the compiler's own headers are invalid or being rejected for some reason.

**Comment by binex-dsk** [comment]
It's using g++, and all my other things compile fine. Hell, when I added Qt it actually used to work fine on qmake, even with Botan.

I'm 99% sure it's that qmake just doesn't work right with Botan because my non-botan projects compile without issue with qmake. But like I said, it used to work fine with this. I tried modifying the generated Makefile to include the proper libraries but yeah, nothing seems to fix this. Reinstalled gcc and its libraries, still nothing.

**Comment by randombit** [comment]
I wonder if some macro is being defined by qmake which breaks something. I notice that in your error log there are even errors coming from Qt headers, which also seems kind of weird.

**Comment by binex-dsk** [comment]
Okay I seem to have fixed the problem with secure_vector (I forgot to include one of my files), but now yeah it's just those string things: [ERRORS.txt](https://github.com/randombit/botan/files/5453519/ERRORS.txt)

The only solution I've found is including <cstring> before including <string>, but that didn't help either.

**Comment by randombit** [comment]
Is it possible that some other (non-std) `string.h` is being found in your build?

**Comment by binex-dsk** [comment]
Oh, that explains it. I've got a file called `string.h` and I guess qmake doesn't like that. Thanks

**Comment by randombit** [comment]
The problem is it is likely coming before the standard headers in the header search path, so when cstring included <string.h> expecting to get the C string library it got your header instead

**Comment by binex-dsk** [comment]
Yeah, qmake included the project directory as an include path before the regular include paths, so I think it got that instead.
