### ISSUE TITLE
DTLS Server Error : No PSK set for identity (Alice ... ) //QT DTLS Example client

### ISSUE THREAD

**Issue by seppy87** [randombit/botan#2439]
Hallo,

I was rewriting my DTLS Server and I face a weird problem. When I try out with the QT DTLS it throws an Exception that no PSK Identity was set for Alice xx 

https://pastebin.com/u602372x

the original code worked but this one not. 
The Only thing I see is that the new code has the Certificate Object and only passing it to the ServerSession as pointers.

Anyone see why it the PSK won't be created?
Certs are identical to the one I used before.

**Comment by randombit** [comment]
If I'm understanding correctly the problem is just that you have PSK ciphersuites enabled (due to listing it in the policy) but don't have any PSKs that you can use. Unless you are intending to use PSK suites you should just remove "ECDHE_PSK", "DHE_PSK" and "PSK" from `allowedKeyExchangedMethods`

**Comment by seppy87** [comment]
Thank you. it worked.

Have you ever tried UDP Hole Punching/UDP NAT Traversal with DTLS?

**Comment by randombit** [comment]
Sorry no, I've only ever used it where both sides had a public IP (or were on same network internal), no NAT. I think usual solution is ICE or STUN, yeah?

**Comment by lieser** [comment]
As you haven't replied yet I'm assuming your questions are answered. If not please reopen the issue.
