### ISSUE TITLE
workfactor.h / BOTAN_FUTURE_INTERNAL_HEADER

### ISSUE THREAD

**Issue by bazineta** [randombit/botan#2458]
In testing the 2.17.0 release today, moving from the 2.15.0 release, I've got a warning that I'm unclear on:
```
workfactor.h:12:1: warning: this header will be made internal in the future [-W#pragma-messages]
BOTAN_FUTURE_INTERNAL_HEADER(workfactor.h)
```
We use this for `dl_exponent_size()`. Since this is still in the documentation, and there's no mention of it going away that I can find in the release notes, what's this message trying to tell me?

**Comment by randombit** [comment]
So, for some context, the overall purpose of this is to minimize the API, ABI, and header surface of the library, to make things easier to find and use, and not distracting people with headers that are basically for internal purposes.

Nothing is going away in future 2.x. However for 3.0 (what is now on master), I'm making as many headers as I can get away with internal or removing them entirely. (GH #2456 )

Can you briefly explain what you are using `dl_exponent_size` for? I am fine with reverting parts of #2456 in master (and removing the warning from future 2.x releases) for any particular header as long as there is an application which had a good reason to being using it.

**Comment by bazineta** [comment]
Thanks for the quick response. As part of a key exchange process, we use it as follows, where:

P is a `Botan::BigInt` P value
G is a `Botan::BigInt` G value
RNG is `inline static thread_local auto RNG = Botan::ChaCha_RNG{Botan::system_rng()};`

```
    // Compute a DH private key based on our P and G values.
    // Return the key to the caller, who is expected to hang on to it
    // until it's returned to us in client().
    //
    // Throws on error.
    
    std::unique_ptr<Botan::DH_PrivateKey>
    server()
    {
        static thread_local Botan::DL_Group dlg =
        {
            DL::P::value(),
            DL::G::value()
        };
        
        return std::make_unique<Botan::DH_PrivateKey>
        (RNG,
         dlg,
         Botan::BigInt(RNG,
                       Botan::dl_exponent_size(dlg.get_p().bits())));
    }
```
Doubtless there's a better way to go about this; you just can't swing a dead cat without hitting 12 people smarter than I am, so perhaps you'd be so kind as to advise what I should be doing instead, here.

**Comment by randombit** [comment]
Makes sense. The default value of the 3rd argument of `DH_PrivateKey` is zero. If the constructor is given 0, then it will generate a new random key using basically the same logic as you have in your application. This works with all versions going back to at least 1.10 and probably long before.

[As an aside, prefer to not specify an argument rather than using an explicit 0 - at some point I'm going to split the constructors into two, one which loads a key and the other which creates a new key - and then the one which creates the key will actually only have the 2 arguments of DL_Group and an RNG]

**Comment by bazineta** [comment]
Ah, yes, I see that in the documentation now -- this code has moved along through countless revisions of Botan, probably just never noticed that. I'll give it a try. This is our only use of the `workfactor.h` header.

**Comment by bazineta** [comment]
And the tests all pass, which I presume to be no surprise to you. Thanks for the pointer.
