### ISSUE TITLE
Too many dependencies on Linux

### ISSUE THREAD

**Issue by rcdailey** [randombit/botan#25]
There are far too many dependencies on Linux that prevent this library from building on Windows. For example, in this file:

    src\cmd\tls_client.cpp

There are socket library dependencies that require linux headers, whereas on Windows it should be using Winsock2.

This library has gone down the shitter apparently.

**Comment by webmaster128** [comment]
I think a lot of improvement happened in terms of Windows compatibility during the last year. MSVC 2013 is supported now, two CI systems run Windows builds, jom is supported as well as nmake. The future is bright :) I am closing this issue as it is partly outdated and partly too broad. Please follow up with concrete issues and PR.
