### ISSUE TITLE
option to build single/versionless lib for android

### ISSUE THREAD

**Issue by passi1995** [randombit/botan#2502]
Hi, I want to use Botan in a cross compiled Qt application for Windows and Android (x86 for AVDs and armv7).
After some try and error I'm able to build and use Botan in Windows but not in Android.
To build the Android libs I use a Ubuntu 20.04 machine and these commands:

```
./configure.py --os=android --cc=clang --cpu=x86 --link-method=copy
sudo ANDROID_SDK_VER=23 ANDROID_ARCH=i686 src/scripts/docker-android.sh
```

These commands run without any error and I get the build output files (includes and libs).
But if I want to use them in a Qt application I'm not able to include versioned .so files. I'm able to use the libbotan-2.so file without any compiler errors but right after the start of the app it crashes cause of missing library "libbotan-2.so.17".

So my question is if there is any way to build Botan for Android versionless? Or am I missing something?

**Comment by randombit** [comment]
I know of a couple of products using Botan on Android but I suspect they embed the library as a static lib inside a larger C++ `.so` with their own logic. So maybe our out of the box experience here is not so good. Can you try the following patch?

```
diff --git a/src/build-data/os/android.txt b/src/build-data/os/android.txt
index f8f61f7b4..54cdf4560 100644
--- a/src/build-data/os/android.txt
+++ b/src/build-data/os/android.txt
@@ -1,6 +1,9 @@
 
 soname_suffix "so"
 
+soname_pattern_base "lib{libname}.so"
+shared_lib_symlinks no
+
 <target_features>
 posix1
 posix_mlock
```

**Comment by passi1995** [comment]
Thanks for your feedback!

I tried your patch with the following result:

![image](https://user-images.githubusercontent.com/23127510/99902661-ba3f0500-2cbf-11eb-9d47-78b4b8b71181.png)

Now I got one single unversioned library (at least according to the name) but it's just a symlink...

**Comment by randombit** [comment]
Weird. If I do an Android build without Docker it is fine. Trying the repro this but the images are downloading slowly.

**Comment by passi1995** [comment]
If I can test something or support you, please let me know! Thank you very much for your efforts.

**Comment by passi1995** [comment]
Any news on this? Unversioned libs are necessary on Android as versioned libs are not supported...

**Comment by randombit** [comment]
@passi1995 Can you try the patch in #2539?

**Comment by passi1995** [comment]
Thank you! This fix works for me, I got a single unversioned  android lib.
