### ISSUE TITLE
Exception in pipe

### ISSUE THREAD

**Issue by unwx** [randombit/botan#2514]
_Exception at 0x738e319e, code: 0xc0000005: read access violation at: 0x11c9000, flags=0x0 (first **chance)._
(at 0x738e319e  <+   78>         rep movs byte ptr es:[edi],byte ptr [esi]) ("Disassembler (memcpy)")

I connected the botan library to the project, I write the code like one guy in the video, (C ++ QT DES Algorithm)
Here's the code itself:

```
using namespace std;
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    string inputText = "this is test text";

    string encryptedText;

    Botan::AutoSeeded_RNG rng;

    Botan::SymmetricKey key(rng, 8); 
    Botan::InitializationVector IV(rng, 8); 

    Botan::Pipe pipe(Botan::get_cipher("DES/CBC", key, IV, Botan::ENCRYPTION), new Botan::Hex_Decoder);

    pipe.process_msg(inputText);

    encryptedText = pipe.read_all_as_string();

    cout << "text :: " << inputText << endl;
    cout << "encrypted text :: " << encryptedText << endl;

    return a.exec();
}
```

**the exception crashes on line: ```(Botan::Pipe pipe(Botan::get_cipher("DES/CBC", key, IV, Botan::ENCRYPTION), new Botan::Hex_Decoder);```**

```
Botan::AutoSeeded_RNG rng;

    Botan::SymmetricKey key(rng, 16);
    Botan::InitializationVector IV(rng, 16);

    Botan::Pipe pipe(Botan::get_cipher("AES-128/CBC", key, IV, Botan::ENCRYPTION));

    pipe.process_msg(inputText);
```
**exception at "filter.h" (Keyed_Filter* cipher = get_cipher(algo_spec, direction);)**

compiler: -Desktop_x86_windows_msvc2019_pe_32bit;

**question, what am I doing wrong, how to fix it? thank you**

**Comment by randombit** [comment]
I don't see any particular problems here except that you are using `Hex_Decoder` when you presumably want `Hex_Encoder`, and using DES which is a terrible idea. If I change to `Hex_Encoder` and remove the Qt stuff your code works fine for me. How was the library you are using built?

**Comment by unwx** [comment]
thank you, that works

**Comment by unwx** [comment]
```
#include <QCoreApplication>

#include <iostream>
#include <string>

#include "botan/botan.h"
#include "botan/pipe.h"
#include "botan/hex_filt.h"

using namespace std;
int main(int argc, char *argv[])
{

    QCoreApplication a(argc, argv);

        string inputText = "this is test text";

        string encryptedText;

        Botan::AutoSeeded_RNG rng;

        Botan::SymmetricKey key(rng, 8);
        Botan::InitializationVector IV(rng, 8);

        Botan::Pipe pipe(Botan::get_cipher("DES/CBC", key, IV, Botan::ENCRYPTION));

        pipe.process_msg(inputText);

        encryptedText = pipe.read_all_as_string();

        cout << "text :: " << inputText << endl;
        cout << "encrypted text :: " << encryptedText << endl;

        return a.exec();
}
``` 
with this code, I also get an exception :(

collected the library as in the documentation for windows with  Visual Studio 2019 Developer Command Prompt v16.6.2

**Comment by randombit** [comment]
When you built, did you run the tests?

Does this crash, and if so on which line?

```
auto filt = Botan::get_cipher("DES/CBC", key, IV, Botan::ENCRYPTION);
printf("%p\n", filt);
Botan::Pipe pipe(filt);
```

Oh! And are you sure that the library and your application are built with the same MSVC runtime? Since I think mismatches there result in fairly opaque crashes.

You might have an easier time using the amalgamation build and then you can just stick the whole thing in to your applications build system.
