### ISSUE TITLE
Bug: crash of TLS::Server if next_proto constructor parameter not set

### ISSUE THREAD

**Issue by fishbach** [randombit/botan#252]
If you do not pass a next_proto function to the constructor of TLS::Server, the Server may crash at line 375 of tls_server.cpp:

if(state.client_hello()->supports_alpn())
    m_next_protocol = m_choose_next_protocol(state.client_hello()->next_protocols());

(Botan Version 1.11.19 / Mac OS X 10.10.5)

**Comment by randombit** [comment]
Confirmed, thanks. Patch should be as simple as

-if(state.client_hello()->supports_alpn())
+if(state.client_hello()->supports_alpn() && m_choose_next_protocol)

Adding a test case for it is a little more complicated.

**Comment by webmaster128** [comment]
Is this done with 1b5819f?

**Comment by randombit** [comment]
Was leaving this open missing a test, but with new callbacks type it's kind of moot anyway.
