### ISSUE TITLE
RSA Encryption test Segmentation fault: 11 on OS X

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#255]
- 2015-07-08 Travis OS X (static lib): https://travis-ci.org/randombit/botan/builds/69974147
- 2015-07-15 Travis OS X (shared lib): https://travis-ci.org/randombit/botan/jobs/70995185
- 2015-08-21 Travis OS X (static lib): https://travis-ci.org/randombit/botan/jobs/76545032
- 2015-08-22 Kullo CI: Crash without output https://gist.github.com/webmaster128/2405f020e6242c4bb3c7

**Comment by randombit** [comment]
Without a backtrace it is hard to proceed, and I don't have any OS X machines. But if someone can repro and get some basic information I'll check it out.

**Comment by randombit** [comment]
This crash hasn't been seen in many months so I'm going with either a compiler problem (given it was OS X only) or some bug of ours that has subsequently been fixed.
