### ISSUE TITLE
On AES 128 CCM, how to specify a different nonce size from the default?

### ISSUE THREAD

**Issue by krs0** [randombit/botan#2553]
the default value is 12 and I found no method of changing it to the 8 that I need.

here what I try to do:

	const std::vector<uint8_t> key = Botan::hex_decode("11111111111111111111111111111111");
	const std::vector<uint8_t> iv = Botan::hex_decode("6158C3EAFE9F53D7");
	std::vector<uint8_t> payload = Botan::hex_decode("FAEE38B16CF250F89C5ABCB43127CFAEE38B16CF250F89C5ABCB43127CFAEE38B16CF250F89C5ABCB431");
	Botan::secure_vector<uint8_t> results(1024);

	// Move vector to secure_vector
	Botan::secure_vector<uint8_t> ivs(iv.size());
	Botan::copy_mem(ivs.data(), iv.data(), iv.size());

	std::unique_ptr<Botan::Cipher_Mode> dec = Botan::Cipher_Mode::create("AES-128/CCM(8)", Botan::DECRYPTION);
	dec->start(ivs);
	dec->process(payload.data(), 42);
	dec->finish(results);

**Comment by randombit** [comment]
CCM is a confusing mode because there is a trade-off between the nonce length and the maximum length of the messages which can be encrypted. To get CCM that uses 8 byte nonces (equivalently, one that uses a 7 byte length field) use `AES-128/CCM(8,7)` where here 8 is your tag size (as you are doing above) and 7 is the CCM L parameter. The CCM nonce is always 15-L bytes.

(In retrospect we should have probably just allowed any nonce length and then it modifies L based on the currently in-use nonce, but Botan assumes L is fixed for the lifetime of the cipher object)

**Comment by krs0** [comment]
That worked!

Now I have the next problem, I need to specify the authentication data for decryption, but I have access only to base class members   and not to CCM_Decypher->set_ad().

I have tried a dynamic cast to CCM_Decryption but failed. Cant I just create an object of type CCM_Decryption?


```
	Botan::secure_vector<uint8_t> results(1024);
	std::unique_ptr<Botan::Cipher_Mode> dec = Botan::Cipher_Mode::create("AES-128/CCM(8,7)", Botan::DECRYPTION);
	dec->set_key(key);
	
	Botan::CCM_Decryption *ccm_dec{ dynamic_cast<Botan::CCM_Decryption*>(dec) };
	ccm_dec->set_ad(ad);
	
	dec->start(ivs);
	dec->process(pt.data(), pt.size());
	dec->finish(results);
```

**Comment by randombit** [comment]
You should never need to cast downwards to the actual mode implementation (and in fact in 3.0 these classes will not even be visible). Instead create them as `AEAD_Mode` which is a subclass of `Cipher_Mode`:

```
std::unique_ptr<Botan::AEAD_Mode> dec = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::DECRYPTION);
```

All of the functions for setting associated data are defined on `AEAD_Mode`

**Comment by krs0** [comment]
That worked too, I can now set ad data. But when decrypting I get now : exception: Botan::Invalid_Authentication_Tag 

Even though I set the same ad data for both encrypt and decrypt.

```
	const std::string plaintext("Test");
	const std::vector<uint8_t> key = Botan::hex_decode("11111111111111111111111111111111");
	const std::vector<uint8_t> iv = Botan::hex_decode("6158C3EAFE9F53D7");
	const std::vector<uint8_t> ad = Botan::hex_decode("0001020304050607");
	
	Botan::secure_vector<uint8_t> ivs(iv.size());
	Botan::copy_mem(ivs.data(), iv.data(), iv.size());

	Botan::secure_vector<uint8_t> ads(tagSize);
	Botan::copy_mem(ads.data(), ad.data(), ad.size());

	// Copy input data to a buffer that will be encrypted
	Botan::secure_vector<uint8_t> pt(plaintext.data(), plaintext.data() + plaintext.length());

	//Encryption
	std::unique_ptr<Botan::AEAD_Mode> enc = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::ENCRYPTION);
	enc->set_key(key);
	enc->set_ad(ad);
	enc->start(ivs);
	enc->finish(pt);

	// Decryption
	Botan::secure_vector<uint8_t> results(1024);

	std::unique_ptr<Botan::AEAD_Mode> dec = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::DECRYPTION);
	
	dec->set_key(key);
	dec->set_ad(ad);
	dec->start(ivs);
	dec->process(pt.data(), pt.size());
	dec->finish(results);
```

**Comment by randombit** [comment]
Everything is fine up to this point

```
	dec->process(pt.data(), pt.size());
	dec->finish(results);
```

What you are saying is, first process the actual CCM encrypted message, and then pretend there is an additional 1024 bytes of zeros which are also part of the message. This fails to decrypt because the CCM tag is probably not 00000...00. You want either

```
  dec->finish(pt);
```
[just decrypt everything in the buffer, in place replacing the ciphertext, chopping off the tag bytes]

or

```
  secure_vector<uint8_t> results; // note: empty here. You can set a capacity but size should be == 0
  dec->process(pt.data(), pt.size());
  dec->finish(results); // plaintext is placed into results
```
[decrypt without modifying the original buffer]

**Comment by krs0** [comment]
It worked. Thank you for all the support!

Here is what I ended up with. If someone wants to use it as an example for AES-CCM.

```
#include <botan/rng.h>
#include <botan/auto_rng.h>
#include <botan/cipher_mode.h>
#include <botan/ccm.h>
#include <botan/aes.h>
#include <botan/hex.h>

void AES_CCM_Encrypt_Decrypt()
{
	const std::string plaintext("Plain text");
	const std::vector<uint8_t> key = Botan::hex_decode("2B7E151628AED2A6ABF7158809CF4F3C");
	const std::vector<uint8_t> ad = Botan::hex_decode("0001020304050607");

	// Move text to be encrypted into a vector, that will be reused for result
	Botan::secure_vector<uint8_t> pt(plaintext.data(), plaintext.data() + plaintext.length());

	//Encryption
	std::unique_ptr<Botan::AEAD_Mode> enc = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::ENCRYPTION);

	//generate fresh nonce (IV)
	Botan::AutoSeeded_RNG rng;
	const Botan::secure_vector<uint8_t> iv = rng.random_vec(enc->default_nonce_length());
	
	enc->set_key(key);
	enc->set_ad(ad);
	enc->start(iv);
	enc->finish(pt);

	std::cout << enc->name() << " with iv " << Botan::hex_encode(iv) << " " << Botan::hex_encode(pt) << "\n";

	// Decryption
	std::unique_ptr<Botan::AEAD_Mode> dec = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::DECRYPTION);
	dec->set_key(key);
	dec->set_ad(ad);
	dec->start(iv);
	dec->process(pt.data(), pt.size());
	
	Botan::secure_vector<uint8_t> result;
	dec->finish(result);

	std::cout << dec->name() << " with iv " << Botan::hex_encode(iv) << " " << Botan::hex_encode(result) << "\n";
	
}
```
