### ISSUE TITLE
Speed up is_prime on 32 bit Windows (MSVC)

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#256]
On 32 bit Windows, `is_prime()` (probably the most expensive method in RSA key generation) performs poorly.

The following results are benchmarked using the new `./botan speed is_prime`

```
Linux64 Dell Laptop: 105
Linux64 Dell Tower: 85
Linux64 Office Server 1: 62
Linux32 Office Server 2: 14.50
Windows Server 64 Bit: 17
Windows Server 32 Bit: 3.30
```

![diagramm](https://cloud.githubusercontent.com/assets/2603011/9404544/e32c2df8-47f0-11e5-9eff-a975fce32b0a.png)

**Comment by randombit** [comment]
Assuming the 'Office Server' and 'Windows Server' are the same hardware running two different builds, the 4-5x slowdown of moving to 32 bits makes sense as the running time is dominated by multiple precision multiplications (O(n**2) algorithm, and we're operating on half as many bits per iteration). That in itself is a 4x slowdown of moving to 32-bit. Ad additionally on x86-32 we're stuck with just ~7 GPRs which doesn't help out.

The more surprising part for me is that even 64-bit Windows is so slow here. Profiling on Linux, the running time appears to be dominated by the modular exponentiation, so I am wondering if this signals a larger performance issue.

**Comment by webmaster128** [comment]
`Office Server 1`, `Office Server 2` and `Windows Server` are three different machines, so the numbers cannot be compared directly.

Compiling Botan on a development machine with GCC or clang in 64 and 32 bit mode leads to a performance slowdown of 3x for 32 bit. On Windows we have a 5.1x slowdown. So this is a significant difference.

This leads to the question: Is there anything Linux32 can do better then Windows32?

* On Windows, deactivating `mp_x86_32_msvc` assembler implementations and falling back to `mp_generic` does not change anything for this benchmark. So the assembler is either not perfect or the compiler can do good on it's own.
* Clang (-O3): Deactivating `mp_x86_32` causes a slowdown of 13 % => There is a 15 % assembler boost on Linux and OS X that is not available on Windows
* Clang (-O3): Deactivating `mp_x86_64` causes a slowdown of 16 % => There is a 19 % assembler boost on Linux and OS X that is not available on Windows
* **GCC (-O2)**: Deactivating `mp_x86_32` causes a slowdown of 14 % => There is a 17 % assembler boost on Linux and OS X that is not available on Windows
* **GCC (-O2)**: Deactivating `mp_x86_64` causes a slowdown of 33 % => There is a 50 % assembler boost on Linux and OS X that is not available on Windows
* `-O3` does not help GCC for this benchmark

The numbers in the chart above come from the compiler in bold, so Linux 64 wins a lot from it's assembler boost. So in a non-assember setup, there is only a 2.3x slowdown from 64 to 32 bit.

It is 2.3x vs. 5.1x.

**Comment by webmaster128** [comment]
Here I have some updated data, all values produced in the exact same Laptop:

```
Windows 32 bit MSVC 2013: 6.65
Windows 32 bit MSVC 2013 (no assembler): 6.65
Windows 32 bit MSVC 2015: 8.80
Windows 32 bit MSVC 2015 (no assembler): 8.50

Windows 64 bit MSVC 2013 (no assembler): 31.00
Windows 64 bit MSVC 2015 (no assembler): 31.50

Ubuntu 14.04 32 bit GCC 4.8: 12.10 / 12.00*
Ubuntu 14.04 32 bit GCC 4.8 (no assembler): 6.05 / 6.95*
Ubuntu 14.04 64 bit GCC 4.8: 39.50
Ubuntu 14.04 64 bit GCC 4.8 (no assembler): 28.00

* --disable-sse2 / build without amalgamation, see #259
```

We can very well see the expected factor 4x when comparing 32 bit vs. 64 bit. The fact that assembler helps nothing on Windows 32 MSVC but doubles is_prime speeds indicates that the missing word_madd2 and word_madd3 in mp_x86_32_msvc are essential.

Side note: If you are developing a 32 bit application, upgrade to MSCV 2015, which seems to have a way better optimizer.

**Comment by randombit** [comment]
With recent changes RSA keygen is much faster now, so I'm closing this.

We may want to remove the x86-32 asm for VC++ though.
