### ISSUE TITLE
Consuming Botan in managed C# - using the pkcs11interop.net library

### ISSUE THREAD

**Issue by Daniel-Pavic** [randombit/botan#2563]
Is it possible to consume the Standard pkcs11-part of the Botan CryptoLibrary using the pkcs11interop.net library (a C#-Wrapper for PKCS#11-Interop libraries) in general - or am I basically having a wrong approach?

**The problem:**
When trying to load the botan.dll in Pkcs11Interop-Wrapper (see https://pkcs11interop.net/) by ...

`using (IPkcs11Library pkcs11Library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, @"Botan\botan.dll", AppType.MultiThreaded)) {...}`

... I run into an Error: 
"Net.Pkcs11Interop.Common.UnmanagedException: Unable to get pointer for **C_GetFunctionList** function. Error code: 0x0000007F."

Error Detail: Procedure / Method not found (translated from German: Die angegebene Prozedur wurde nicht gefunden.)

**The approach:**
1. I was able to build Botan including pkcs#11 with Visual Studio and all "nmake check"-tests ran with result "OK"
2. I can see that pkcs#11 is included in the Botan.dll
3. I tried configure.py with options --debug-mode --with-debug-info
4. I try to load Botan.dll in the pkcs11interop.net - Wrapper and obtain the error message above.

**My understanding regarding the Botan-library** (pkcs#11-part):
1. It exists a low level C-API that encapsulates the Standard pkcs#11-API (see https://botan.randombit.net/handbook/api_ref/pkcs11.html). 
2. The low level API provides access to all functions that are specified by the standard.

**Questions:**
1. Is the low level API exposed in such a way that it can be consumed by an C# Interop Wrapper in order to be used "directly" in managed C# code? If so: why can't I load the Botal.dll into the Pkcs11Interop-Wrapper? Any ideas?
2. If the low level API is **NOT** exposed in such a way that it can be consumed by an C# Interop Wrapper: What can be done to change the existing code in order to consume the low level API in managed .NET code? 

Thank you for your time reading this - and even more important: 
Thank you for any help which is greatly appreciated!
- Daniel

**Comment by randombit** [comment]
No, Botan is not itself a PKCS11 library but instead only offers a C++ API on top of the low level C PKCS11 API. So we don't expose, or indeed even implement ourselves, functions such as `C_GetFunctionList` - these come from the PKCS11 library which is called by us. So, even if we modified our wrapper to expose these functions as part of our ABI, it would be exactly the same (from your position) as just using whatever PKCS11 library you had compiled Botan against. You might as well just use that library directly and skip the bother.

**Comment by Daniel-Pavic** [comment]
Yes, I indeed had a wrong understanding of the entire use and interplay of Botan regarding PKCS#11. Now that you gave me that hint I fell across the Module-class that needs to be involved in order to load any HSM-provider's shared library.

Thank you very much for clearing it up to me - and keep up the good work!
... And a late Merry Christmas and all the best for 2021! :-)
