### ISSUE TITLE
"botan2.BotanException: botan_pk_op_encrypt_create failed: -40 (Not implemented)" in Python Binding

### ISSUE THREAD

**Issue by smallbigcake** [randombit/botan#2564]
Hi,
I tried to use Python Binding botan2.py in my Python code. But I encountered a strange problem.
When I used PKEncrypt() function, it throwed an exception which said "botan_pk_op_encrypt_create failed: -40 (Not implemented)".

>\>>> import botan2
>\>>> pub_key = botan2.PublicKey().load("-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1ud9HnuqhQd9NFAk\nMbnjNHRAaDkshy7M2ebxEj6wCdJxuX3ZKn6S18QJ85mWcLsoN68Lh/PARWRJSG7e\njMD3Cs6gPjAj/Y7072VpvQ7MEJDSYHnKkWhnSB/+O43dHRQN6D5xlLvY69B2\nBe8qCxZ+f+jJjo3UpfiyYSrXNYex8/ov/mjYPnpZpaCO6K3CcOfDvALURFnayUEA\nDMx6ET2AonATc+Gp5UWetAkzlTyLbqpZngg9r9Ne7xtDaSeaHVahMF/cvaSE\nkUqADz6iKVYdIWKxCA7l4RuEf/+LxVUZOvjQEboiP9+TZ7peAK2AtZS8k8zjmmYy\n2QIDAQAB\n-----END PUBLIC KEY-----\n")

>\>>> botan2.PKEncrypt(pub_key, "FFFF33333")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/botan2.py", line 1143, in __init__
    _DLL.botan_pk_op_encrypt_create(byref(self.__obj), key.handle_(), _ctype_str(padding), flags)
  File "/usr/local/lib/python3.9/site-packages/botan2.py", line 84, in _errcheck
    raise BotanException('%s failed' % (fn.__name__), rc)
botan2.BotanException: botan_pk_op_encrypt_create failed: -40 (Not implemented)
I tried to search that error message but found no clue.

The only useful information I found was in [FFI document](https://botan.randombit.net/handbook/api_ref/ffi.html)

> enumeratorBOTAN_FFI_ERROR_NOT_IMPLEMENTED = -40
> This is returned if the functionality is not available for some reason. For example if you call botan_hash_init with a named hash function which is not enabled, this error is returned.

What does "enabled" mean? Is this some bug or it's just because I missed something?

I used Python 3.9.1 (compiled from source) and compiled botan 2.17.3.

Really appreciate if anyone helps.

**Comment by randombit** [comment]
>  What does "enabled" mean?

The build is configurable and allows algorithms to be enabled or disabled. So, for example if you wanted to hash something using SM3, but SM3 was not included in the build, then it would fail with this error.

In this case the reason is

botan2.PKEncrypt(pub_key, "FFFF33333")

Here you are trying to create an object which can encrypt using the key and with a padding mode of "FFFF33333". Since this isn't a recognized padding scheme, it returns not implemented.

Instead you probably want something like


```
        enc = botan2.PKEncrypt(pub_key, "OAEP(SHA-256)")
        rng = botan2.RandomNumberGenerator()
        ctext = enc.encrypt("FFFF33333", rng)
```

**Comment by smallbigcake** [comment]
Thanks a lot! Now I know the reason. So I passed the wrong padding mode parameter.
It works now after I give the right padding mode.😀
BTW, as I use Python 3.9, it seems the first parameter of enc.encrypt(b"FFFF33333", rng) should be bytes like b"FFFF33333".
