### ISSUE TITLE
Python Binding: Cannot Encrypt/Decrypt Message with AES-128/CBC？

### ISSUE THREAD

**Issue by smallbigcake** [randombit/botan#2566]
Hi,

Sorry for another question about Python Binding ABI.
I encountered another problem when I do SymmetricCipher with AES-128/CBC mode.
I ran some code like below.

```
#!/usr/bin/env python
import botan2

passphrase = "password"
plaintext = "this is plain text"

new_hash = botan2.HashFunction("MD5")
new_hash.update(passphrase)
key = new_hash.final()
print("len of key: %s" % len(key))

aes_enc = botan2.SymmetricCipher("AES-128/CBC")
aes_enc.set_key(key)
print("nonce length: %s" % aes_enc.default_nonce_length())
nonce = botan2.RandomNumberGenerator().get(aes_enc.default_nonce_length())
aes_enc.start(nonce)
res = aes_enc.finish(plaintext)
print(res)
```

It gave me an exception like
>Traceback (most recent call last):
  File "/root/test_aes.py", line 18, in <module>
    res = aes_enc.finish(plaintext)
  File "/usr/local/lib/python3.9/site-packages/botan2.py", line 799, in finish
    return self._update(txt, True)
  File "/usr/local/lib/python3.9/site-packages/botan2.py", line 787, in _update
    _DLL.botan_cipher_update(self.__obj, flags,
  File "/usr/local/lib/python3.9/site-packages/botan2.py", line 84, in _errcheck
    raise BotanException('%s failed' % (fn.__name__), rc)
botan2.BotanException: botan_cipher_update failed: -1 (Invalid input)

However, if I replaced the "AES-128/CBC" with "AES-128/GCM", its OK then.
>len of key: 16
nonce length: 12
b"\xa6-]\xf5\xd0(L\x8e\xa8\xe2\xb2\x10LFU\xf1\x9e\xbc\x14\xed\xe2'\x14\xf5m\x1a\x86\\>\x08\xd8f\xe1H"

So I started to wonder if it's because the botan itself doesn't support CBC any more?

I also tried to do the same with the CLI, like the following command.

> botan encryption --mode=aes-128-cbc --key=someSecret

But it gave me:
>Usage error: Invalid mode: 'aes-128-cbc'
valid modes are: aes-128-cfb aes-128-gcm aes-128-ocb aes-128-xts aes-192-cfb aes-192-gcm aes-256-cfb aes-256-gcm aes-256-xts chacha20poly1305
Usage: encryption --buf-size=4096 --decrypt --mode= --key= --iv= --ad=

Is there any way to use "AES-128/CBC" then? Because we have some legacy code that encrypts something with this mode. And we'd like to maintain the compatibility of old cipher text if possible.

Thank you for your time.

**Comment by randombit** [comment]
CBC is completely supported. I'm not sure why it wasn't included in the cli, I think just some oversight.

As to what's happening here - there is a bug in the Python module. It fails to account for modes which might expand the ciphertext (this is true only for CBC). Can you try the patch in #2567 ?

**Comment by smallbigcake** [comment]
Thanks for your fix.
I tried the patch in #2567 botan2.py. It's working now, both encrypt and decrypt.
