### ISSUE TITLE
Question - KVC generation function

### ISSUE THREAD

**Issue by mohsenomidi** [randombit/botan#2569]
Dear contributors, 

Thanks for useful and complete library, 
is there any function in the library to generate KVC (Key Check Value) for key sharing? I want to display the KVC to user to ensure the a key is correctly entered.

Thanks !

**Comment by randombit** [comment]
Not directly, but it's pretty easy to implement: (untested code but should put you in the right direction)

```
auto tdes = BlockCipher::create_or_throw("3DES");
tdes->set_key(key, key_len);
uint8_t zero_block[8] = { 0 };
tdes->encrypt(zero_block);
auto hex_kcv = hex_encode(zero_block);
return hex_kcv.substr(0, 6); // first 3 bytes == 6 hex chars
```

**Comment by mohsenomidi** [comment]
Thank you so much 🙏🙏🙏
