### ISSUE TITLE
Using AES 128 CCM with empty AD data

### ISSUE THREAD

**Issue by krs0** [randombit/botan#2574]
I have a request from my users to not use any AD with AES 128 CCM, because the previous python lib we were using allowed an empty string as AD.

How to set this in botan?

dec->authenticated(); returns true.
I have tried not setting or using a zero sized AD but then I get : Botan::Invalid_Authentication_Tag .

Below the code that works with ad set to some value.

```
#include <botan/rng.h>
#include <botan/auto_rng.h>
#include <botan/cipher_mode.h>
#include <botan/ccm.h>
#include <botan/aes.h>
#include <botan/hex.h>

void AES_CCM_Encrypt_Decrypt()
{
	const std::string plaintext("Plain text");
	const std::vector<uint8_t> key = Botan::hex_decode("2B7E151628AED2A6ABF7158809CF4F3C");
	const std::vector<uint8_t> ad = Botan::hex_decode("0001020304050607");

	// Move text to be encrypted into a vector, that will be reused for result
	Botan::secure_vector<uint8_t> pt(plaintext.data(), plaintext.data() + plaintext.length());

	//Encryption
	std::unique_ptr<Botan::AEAD_Mode> enc = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::ENCRYPTION);

	//generate fresh nonce (IV)
	Botan::AutoSeeded_RNG rng;
	const Botan::secure_vector<uint8_t> iv = rng.random_vec(enc->default_nonce_length());
	
	enc->set_key(key);
	enc->set_ad(ad);
	enc->start(iv);
	enc->finish(pt);

	std::cout << enc->name() << " with iv " << Botan::hex_encode(iv) << " " << Botan::hex_encode(pt) << "\n";

	// Decryption
	std::unique_ptr<Botan::AEAD_Mode> dec = Botan::AEAD_Mode::create("AES-128/CCM(8,7)", Botan::DECRYPTION);
	dec->set_key(key);
	dec->set_ad(ad);
	dec->start(iv);
	dec->process(pt.data(), pt.size());
	
	Botan::secure_vector<uint8_t> result;
	dec->finish(result);

	std::cout << dec->name() << " with iv " << Botan::hex_encode(iv) << " " << Botan::hex_encode(result) << "\n";
	
}
```

**Comment by randombit** [comment]
This should work (IIRC) but checking over the current CCM test vectors we do not currently test with an empty AD and there may be a bug here. I will look into this asap.

**Comment by randombit** [comment]
I can't reproduce this. If I take your code and comment out the calls to `set_ad` then everything continues to work. (Are you sure you are omitting the AD from both sides?)

**Comment by krs0** [comment]
I rechecked it and it works! Sorry about that.

Actually what I was doing: Encryption with AD not empty and then only tried to decrypt with AD empty. And of course I got Invalid_Authentication_Tag.

I am new to crypto, and I was expecting that the TAG at the end of the cipher is ignored when AD is not used. But I guess the TAG is calculated anyway by another mechanism and AD if used only changes the value of the TAG.

**Comment by randombit** [comment]
>  I was expecting that the TAG at the end of the cipher is ignored when AD is not used. But I guess the TAG is calculated anyway by another mechanism and AD if used only changes the value of the TAG.

Right, the tag authenticates the whole ciphertext as well as the AD.
