### ISSUE TITLE
Wrong value for ASN1_Tag::PRIVATE

### ISSUE THREAD

**Issue by sledgehammer999** [randombit/botan#2581]
According to [this](https://en.wikipedia.org/wiki/X.690#Encoding) the PRIVATE class has a value of `0b1100'000` aka `0xc0`

But it in https://github.com/randombit/botan/blob/854b79287818a01137aa78e59e36ab10240bf13b/src/lib/asn1/asn1_obj.h#L24
it is defined as
```c++
enum class ASN1_Tag : uint32_t {
   UNIVERSAL        = 0x00,
   APPLICATION      = 0x40,
   CONTEXT_SPECIFIC = 0x80,

   CONSTRUCTED      = 0x20,

   PRIVATE          = CONSTRUCTED | CONTEXT_SPECIFIC,
```

aka `0b1010'0000` or `0xa0`

Git blame shows that this was introduced with https://github.com/randombit/botan/commit/4e43080954be57e362feb1cc8202bfd42117e286 but I can't find any further info.

Is this truly a bug or is there a reason for defining the value as `0xa0`?

**Comment by randombit** [comment]
Thanks for pointing this out. I think actually the problem is that `PRIVATE` is named incorrectly and has nothing to do with private class in DER (which is not used by anything I've encountered). It actually is being used to handle context-specific explicitly tagged items. I'm not sure why I used private for this. Certainly it's wrong.

**Comment by sledgehammer999** [comment]
OK, that makes more sense now.

Btw, I noticed that you very recently converted it to `enum class`. Have you considered splitting the class and type tags to different `enum class`es to improve type safety even more?
Woud you object to such a PR?

**Comment by randombit** [comment]
Such a change makes sense. And if it is going to happen, now is the time (`master` is in runup to a 3.0-alpha where we already are breaking compat guarantees, but anything that is in final 3.0.0 we'll be stuck with for years).

**Comment by sledgehammer999** [comment]
Closing this as fixed by @2584.
