### ISSUE TITLE
Possibly wrong installation tree?

### ISSUE THREAD

**Issue by sledgehammer999** [randombit/botan#2591]
Let's say you configure a path prefix and then you install to it. Now the headers are under `<prefix-path>/include/botan-3/botan/*.h` but shouldn't it be either `<prefix-path>/include/botan/*.h` or `<prefix-path>/include/botan-3/*.h` instead?

Latest master branch. OS: Windows 7, Compiler: gcc 9.2.0 under msys2.

**Comment by randombit** [comment]
`botan-3/botan/x.h` is so that in your source you include as `botan/x.h`, the `botan-3` is so that `botan-2` and `botan-3` can be installed into the same include dir without conflicts. The intention is you would set your include path to include `<prefix-path>/include/botan-3`
