### ISSUE TITLE
Is it possible to use botan in a Windows driver project?

### ISSUE THREAD

**Issue by moccajoghurt** [randombit/botan#2604]
It would be awesome to use botan in a Windows driver I am currently maintaining. It seems like botan is only usable in user mode. Is this assumption correct or could it theoretically be compiled as a kernel mode library too?

**Comment by randombit** [comment]
We could define an alternative platform target that had limited functionality enabled, basically disabling support for filesystem, Win32 API calls, etc and then adding a few replacements for truly necessary things like getting randomness. This would not be too difficult, the way here has already been paved by support for IncludeOS (which does use Botan from within kernel mode) and bare metal embedded bulids.

Unfortunately it seems that Windows does not support C++ exceptions within the kernel which would be a huge problem. It might be possible to replace it all with SEH but I'm not sure if that's realistic.

**Comment by jeffRTC** [comment]
@moccajoghurt  

Check

https://github.com/Bareflank/standalone_cxx

They have exception support and works with Drivers basically you can write Modern C++ there

**Comment by randombit** [comment]
We'd be willing to support this if the patch was not too painful (disabling exceptions is, unfortunately, not in the cards with this codebase) but it seems like there is no current activity here so I'm closing this issue as stale.
