### ISSUE TITLE
commit 959f14f63b4a9950 breaks certifcate validation for SET with more than one RND

### ISSUE THREAD

**Issue by Janpopan** [randombit/botan#2611]
We changes from botan 2.6.0 to 2.17.3

But afte the change, we recive an exeption with some certificats.

We believe this is the reason:
In X509_DN::decode_from is a new check verify_end.
This change was made 07.05.2019 with commit 959f14f63b4a9950.

The certificates which cause the problem have in the subject one SET with more than one RND.

**Comment by randombit** [comment]
Thanks for reporting this. Is it possible for you to attach to this issue a certificate which has such a DN?

**Comment by Janpopan** [comment]
PN

**Comment by Janpopan** [comment]
[x509_certificate.zip](https://github.com/randombit/botan/files/5900558/x509_certificate.zip)

**Comment by Janpopan** [comment]
Any idea?

**Comment by randombit** [comment]
Sorry about the delay, fixed in #2630 I'll be backporting this to release-2 branch for upcoming 2.18.0 release as well

**Comment by Janpopan** [comment]
No backport for 2.18?

**Comment by randombit** [comment]
This should have been backported, sorry. I'll do it for 2.18.1

**Comment by randombit** [comment]
Backported now, so closing this. 2.18.1 release isn't scheduled yet but probably sometime later this month.

**Comment by Janpopan** [comment]
Thanks a lot! :-)
