### ISSUE TITLE
Change the names of the library objects

### ISSUE THREAD

**Issue by TypeYourName** [randombit/botan#2615]
Hello together,

is it possible (and if yes how?) to change the names of the library objects (libbotan-2.so.12, libbotan-2.so.12.1, etc.)?
Furthermore is it possible to create only special lib objects (e.g. libbotan.so) without the other ones?

I use Botan 2.12.1.

Thank you very much!

Best regards

**Comment by randombit** [comment]
No this is not currently possible. The build system does have support for different naming/versioning/symlink conventions used among different platforms so it wouldn't be terribly hard to add an override but this is not supported at the moment.

**Comment by jeffRTC** [comment]
@randombit  Jack, do you have any time to look into my issue? We have been stuck for over period of a month. I don't know if you have missed my messages. Just in case, letting you know. 

Apologize @TypeYourName  for bumping into this......

I still think we have made right choice than going to OpenSSL..

**Comment by jeffRTC** [comment]
@randombit  Else if you offer enterprise support, we would be happy to purchase it.
