### ISSUE TITLE
WASM: Invalid SRP parameter from server

### ISSUE THREAD

**Issue by agauniyal** [randombit/botan#2616]
I'm trying to use botan in browser(wasm) environment and built botan with following command -
```
CXX=em++ ./configure.py --cc=clang --cpu=llvm --os=emscripten
```
I'm building my library with this -
```
em++ -std=c++17 --bind -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -I../botan/build/include ../botan/libbotan-3.a srp_server_client.cpp -o a.html -s -s DISABLE_EXCEPTION_CATCHING=0
```
I also had to bind Botan::BigInt through embind because my interface was returning it so I did it like -
```cpp
#ifdef __EMSCRIPTEN__
#include <emscripten/bind.h>
using namespace emscripten;

EMSCRIPTEN_BINDINGS(SRPBigInt) {
  value_object<Botan::BigInt>("SRPBigInt");
}
#endif
```

Everything compiles and works perfectly until the call reaches `srp6_client_agree` method, which throws this exception - `Invalid SRP parameter from server`

Any pointers how I can debug it further? You can try out the code(along with instructions in README) here - https://github.com/agauniyal/srp_botan

**Comment by randombit** [comment]
> Any pointers how I can debug it further?

This only happens if the value is out of range ( <= 0 or >= the prime modulus) - print out the values that the server is sending and that the client is receiving, I bet something is getting mangled.
