### ISSUE TITLE
verify an ecdsa-with-SHA1 signature which is in wrongly encoded DER format

### ISSUE THREAD

**Issue by Janpopan** [randombit/botan#2617]
Hello,

we are using Botan 2.17.3 to verify an ecdsa-with-SHA1 signature which is in wrongly encoded DER format. The integer values are encoded using leading zeros, even if the second byte is less than 0x80.

Specifically, the input integer begins with `0x00 0x29`, and during the calculation of `reencoded` in `der_encode_signature(…)` this is correctly encoded as 0x29. Then, the length check in pubkey.cpp, line 374, stops our check because `reencoded.size()` is one less than length (only one of the integers' second bytes is less than 0x80):

```cpp
// pubkey.cpp line 374:
if(reencoded.size() != length ||
            same_mem(reencoded.data(), sig, reencoded.size()) == false)
            {
            throw Decoding_Error("PK_Verifier: signature is not the canonical DER encoding");
            }
```

We understand that Botan's result is encoded correctly, but think that the additional leading zero shouldn't lead to a failed signature check because the signature is mathematically correct. Do you see any chance to relax this check?

**Comment by randombit** [comment]
I would instead recommend, if you must support such signatures, to perform the ASN.1 decoding to retrieve the integer values, then use `BigInt::encode_fixed_length_int_pair` to re-encode it into the IEEE 1363 format.

**Comment by Janpopan** [comment]
Hello @randombit,

sorry for the very late response. We successfully implemented the workaround and it seems to work for us. Thank you for your help
