### ISSUE TITLE
Building latest master (97b6e1) with gcc 4.8.5 on solaris fails

### ISSUE THREAD

**Issue by miesi** [randombit/botan#262]
[botan]$ make
g++ -pthread -fstack-protector -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -c -O2 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Ibuild/include ./src/lib/alloc/locking_allocator/locking_allocator.cpp -o build/obj/lib/alloc_locking_allocator.o
./src/lib/alloc/locking_allocator/locking_allocator.cpp: In function 'std::size_t Botan::{anonymous}::reset_mlock_limit(std::size_t)':
./src/lib/alloc/locking_allocator/locking_allocator.cpp:30:16: error: 'RLIMIT_MEMLOCK' was not declared in this scope
    ::getrlimit(RLIMIT_MEMLOCK, &limits);
                ^
*** Error code 1
make: Fatal error: Command failed for target 'build/obj/lib/alloc_locking_allocator.o'

[botan]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/gcc/4.8/lib/gcc/i386-pc-solaris2.11/4.8.5/lto-wrapper
Target: i386-pc-solaris2.11
Configured with: /jenkins/jobs/oi-userland/workspace/components/gcc48/gcc-4.8.5/configure CC=/usr/gcc/4.8/bin/gcc CXX=/usr/gcc/4.8/bin/g++ F77=/usr/gcc/4.8/bin/gfortran FC=/usr/gcc/4.8/bin/gfortran CFLAGS='-g -O2' CXXFLAGS=' ' FFLAGS=' ' FCFLAGS= LDFLAGS=-m32 PKG_CONFIG_PATH=/usr/lib/pkgconfig --prefix=/usr/gcc/4.8 --mandir=/usr/gcc/4.8/share/man --bindir=/usr/gcc/4.8/bin --libdir=/usr/gcc/4.8/lib --sbindir=/usr/gcc/4.8/sbin --sbindir=/usr/gcc/4.8/bin --libdir=/usr/gcc/4.8/lib --libexecdir=/usr/gcc/4.8/lib --host i386-pc-solaris2.11 --build i386-pc-solaris2.11 --target i386-pc-solaris2.11 --with-boot-ldflags=-R/usr/gcc/4.8/lib --enable-plugins --enable-objc-gc --enable-languages=c,c++,fortran,lto,objc --without-gnu-ld --with-ld=/usr/bin/ld --with-build-time-tools=/usr/gnu/i386-pc-solaris2.11/bin --disable-libitm --with-gnu-as --with-as=/usr/bin/gas LDFLAGS=-R/usr/gcc/4.8/lib
Thread model: posix
gcc version 4.8.5 (GCC)

Which gcc 4.8 is supported?

**Comment by webmaster128** [comment]
Basically all versions of GCC 4.8 are supported. But Botan is not well tested on Solaris. I did not hear from someone building on Solaris for a year or so. To this is likely to be an OS issue. I fear you need to dig into that yourself.

**Comment by randombit** [comment]
It looks like Solaris does not have `RLIMIT_MEMLOCK`, and likely does not support locking any amount of memory from userspace.

**Comment by randombit** [comment]
@miesi Can you try updating your tree for the above and rebuilding? If you run into further problems, please use `make -k 2>&1 | tee build.log` so all errors will be captured in one go. Thanks.

**Comment by miesi** [comment]
@randombit Thanks! After a git pull it immediately started building. Will send another comment when it finished.

**Comment by miesi** [comment]
@randombit 32bit and 64bit build just worked. The shared library is not automatically created because the "-o" parameter to g++ is empty. In the Makefile created by configure.py it looks like this:

Link Commands
SONAME_PATCH    =
SONAME_ABI      =
SONAME_BASE     =

SHARED_LIB      = ./$(SONAME_PATCH)

editing the Makefile by hand shows also the need for '-lnsl' in 'LIB_LINKS_TO'

running the 32bit botan-test is possible (64bit is immediatly killed for a reason I need to investigate)

botan-test output:
[mieslingert@delle botan]$ ./botan-test 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 is a Catch v1.2.1 host application.
Run with -? for options

-----------------------------------------------------------
calendar_point to stl timepoint and back
  default test
-----------------------------------------------------------
./src/tests/catchy/test_utils.cpp:84
...........................................................

./src/tests/catchy/test_utils.cpp:93: FAILED:
  CHECK_THAT( out.hour Equals(14) )
with expansion:
  12 == 14

-----------------------------------------------------------
calendar_point to stl timepoint and back
  first possible time point
-----------------------------------------------------------
./src/tests/catchy/test_utils.cpp:84
...........................................................

./src/tests/catchy/test_utils.cpp:103: FAILED:
  CHECK_THAT( out.year Equals(1970) )
with expansion:
  1969 (0x7b1) == 1970 (0x7b2)

./src/tests/catchy/test_utils.cpp:104: FAILED:
  CHECK_THAT( out.month Equals(01) )
with expansion:
  12 == 1

./src/tests/catchy/test_utils.cpp:105: FAILED:
  CHECK_THAT( out.day Equals(01) )
with expansion:
  31 == 1

./src/tests/catchy/test_utils.cpp:106: FAILED:
  CHECK_THAT( out.hour Equals(00) )
with expansion:
  23 == 0

-----------------------------------------------------------
calendar_point to stl timepoint and back
  latest possible time point
-----------------------------------------------------------
./src/tests/catchy/test_utils.cpp:84
...........................................................

./src/tests/catchy/test_utils.cpp:118: FAILED:
  CHECK_THAT( out.hour Equals(23) )
with expansion:
  22 == 23

botan_kdf: Could not find any algorithm named "KDF2(SHA-1)"
botan_kdf: Could not find any algorithm named "KDF2(SHA-1)"
-----------------------------------------------------------
FFI KDF
-----------------------------------------------------------
./src/tests/test_ffi.cpp:171
...........................................................

./src/tests/test_ffi.cpp:180: FAILED:
  REQUIRE_THAT( botan_kdf("KDF2(SHA-1)", out_buf.data(), out_len, secret.data(), secret.size(), salt.data(), salt.size()) Equals(0) )
with expansion:
  -1 == 0

botan_privkey_create_rsa: Creating 'RSA/EMSA4(SHA-1)' failed: Could not find any algorithm named "EMSA4(SHA-1)"
botan_privkey_create_rsa: Creating 'RSA/EMSA4(SHA-1)' failed: Could not find any algorithm named "EMSA4(SHA-1)"
-----------------------------------------------------------
FFI RSA
-----------------------------------------------------------
./src/tests/test_ffi.cpp:200
...........................................................

./src/tests/test_ffi.cpp:206: FAILED:
  REQUIRE_THAT( botan_privkey_create_rsa(&priv, rng, 2048) Equals(0) )
with expansion:
  -20 == 0

botan_pk_op_sign_create: Creating 'ECDSA/EMSA1(SHA-384)' failed: Could not find any algorithm named "EMSA1(SHA-384)"
botan_pk_op_sign_create: Creating 'ECDSA/EMSA1(SHA-384)' failed: Could not find any algorithm named "EMSA1(SHA-384)"
-----------------------------------------------------------
FFI ECDSA
-----------------------------------------------------------
./src/tests/test_ffi.cpp:254
...........................................................

./src/tests/test_ffi.cpp:273: FAILED:
  CHECK_THAT( botan_pk_op_sign_create(&signer, priv, "EMSA1(SHA-384)", 0) Equals(0) )
with expansion:
  -20 == 0

botan_pk_op_sign_update: Bad magic 2155905152 in ffi object expected 451986335
./src/tests/test_ffi.cpp:280: FAILED:
  CHECK_THAT( retSignUpdate Equals(0) )
with expansion:
  -1 == 0

botan_pk_op_sign_finish: Bad magic 2155905152 in ffi object expected 451986335
./src/tests/test_ffi.cpp:286: FAILED:
  CHECK_THAT( retSignFinish Equals(0) )
with expansion:
  -1 == 0

./src/tests/test_ffi.cpp:254: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===========================================================
test cases:  38 |  34 passed |  4 failed
assertions: 378 | 366 passed | 12 failed

**Comment by webmaster128** [comment]
@miesi Could you please open two follow-up issues for that. I recently broke the Makefile. The test issues are another topic.

**Comment by webmaster128** [comment]
@miesi if you want a working Solaris Makefile in the next Botan release 1.11.20 (release 2015-09-07), please open issues for that. Otherwise you'll have to do the patching yourself.
