### ISSUE TITLE
There is no server.send_data()

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2637]
The doc  [Link](https://botan.randombit.net/handbook/api_ref/tls.html) highlights the function `server.send_data()` to encrypt the data, but I can't find it on your lib. 
 
So, the function is `send() `instead `send_data() `?

**Comment by randombit** [comment]
This should be `send` I'm not sure where `send_data` came from. Thanks for pointing that out.

**Comment by randombit** [comment]
Fixed now, thanks again
