### ISSUE TITLE
Gzip_Decompression a subclass of Stream_Compression?

### ISSUE THREAD

**Issue by tiwoc** [randombit/botan#264]
While reading about compression and decompression in Botan, I found that the Compression classes for the concrete algorithms are subclasses of Stream_Compression, and the Decompression classes are subclasses of Stream_Decompression. There's one exception, though: Gzip_Decompression subclasses Stream_Compression. Is this somehow intentional or is it just a bug?

![Class hierarchy of Compressor_Transform](https://cloud.githubusercontent.com/assets/1260821/9543317/61fedc7a-4d78-11e5-8fac-2291162e4d6b.png)

**Comment by randombit** [comment]
Indeed a bug, possible because the `make_stream` has the same signature in both classes, and returns the same type (`Compression_Stream`).

**Comment by webmaster128** [comment]
Is this done in https://github.com/randombit/botan/commit/1502e1efcb3ac37c4e0b0176b9c3042bcb6c9069?

**Comment by tiwoc** [comment]
Yes, it is. Thanks!
