### ISSUE TITLE
SSL_ERROR_RX_UNEXPECTED_SERVER_HELLO and Can't securely connect to this site

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2640]
I try to connect to site through the ProxyServer I built using Botan and IE11 Browser show `Can't securely connect to this site` as the error.

On Firefox, the error is `Error code: SSL_ERROR_RX_UNEXPECTED_SERVER_HELLO`

I don't like Firefox and Chrome because they burst too many requests and I find IE11 don't do that. I was able to capture the IE11 traffic flow on Wireshark. 

The TLS messages are successfully decoded by the time this error happen. I see them get printed on my console. 

Please see attached .zip folder (it has pcap file)

[error.zip](https://github.com/randombit/botan/files/6087818/error.zip)

**Comment by randombit** [comment]
Can you try the same browsers connecting to the `tls_proxy` and/or `tls_http_server` cli utils? (Both require building with Boost, to enable asio) last I checked with Firefox and Chrome both worked fine. If they do work then understanding the diff between those and what you wrote probably gives a hint. If they don't work then something is broken.

**Comment by randombit** [comment]
I can't say for certain but it sounds like what is happening is the browser is opening a new connection but the server hello is being sent on an existing (already active) session instead. Are you sure your socket->session mapping is correct?

**Comment by jeffRTC** [comment]
When I get connection, I store it in a map under the IP:PORT key only if there is no existing connection under that IP:PORT on the map.    

I have a  function named  `isTLS `which checks if message is TLS or not. I get the TCP message from connection and pass to this function and if it found that it's in fact a TLS message then I pass the message into `received_data `function of Botan.

I store a flag on the map that the connection in fact is TLS so the next time the connection comes, I can directly move into TLS. 

```
bool isTLS(const std::string &message)
{
    if (
        message.data()[0] == 20 || message.data()[0] == 21 ||
        message.data()[0] == 22 || message.data()[0] == 23 ||
        message.data()[0] == 24 ||
        (unsigned char)message.data()[0] == 128 || message.data()[0] == 0)
    {
        return true;
    }

    return false;
}

```

Once Botan finish `received_data`, I access the vector which contains the records that needs to be sent thru a socket.

```
        std::vector<std::string> encodedMessages; // Store Encoded (Out)

    public:
        void tls_emit_data(const uint8_t data[], size_t size) override
        {
            encodedMessages.emplace_back(data, data + size);
        }
```

I loop over the vector and send each message out using Socket.

In most times, this vector has 6 messages and in other cases 3 messages. Do I have to merge messages together and send them in one shot?

**Comment by jeffRTC** [comment]
I don't use ASIO instead I use evpp library. 

I've looked into your implementation on here, 

[Server](https://github.com/randombit/botan/blob/master/src/cli/tls_http_server.cpp)

I don't find any function like my `isTLS ` so I can't understand how does it separate HTTP versus TLS

**Comment by jeffRTC** [comment]
@randombit 

I've inspected your proxy server again. It appear that it return true instead false.

```
        bool tls_session_established(const Botan::TLS::Session &session) override
        {
            // the session with the tls client was established
            // return false to prevent the session from being cached, true to
            // cache the session in the configured session manager
            return false;
        } 
```

I return false because it's what was on your Doc's example. Should I return true here?

**Comment by randombit** [comment]
Caching (returning `true` from `tls_session_established`) is usually a good idea. I think the docs just show returning `false` because the default impl of that function returns `true` but it makes it confusing what the best behavior should be. Will update the docs.

**Comment by jeffRTC** [comment]
@randombit 

Apparently, you forget to include `tls_http_server` (and others) to Botan cli. 

This option was in docs, see [Link](https://botan.randombit.net/handbook/cli.html#tls-server-client)

I ran this on  Ubuntu 20,

`botan tls_http_server cert key --port=443 --policy=default --threads=0 --max-clients=0 --session-db --session-db-pass=123
`
It yields 

`Unknown command tls_http_server (try --help)`

These are available options on the current CLI so no way to test your code for now..

```
TLS:
   tls_ciphers        Lists all ciphersuites for a policy and TLS version
   tls_client         Connect to a host using TLS/DTLS
   tls_client_hello   Parse a TLS client hello message
   tls_server         Accept TLS/DTLS connections from TLS/DTLS clients
```

**Comment by randombit** [comment]
The proxy and http server are only available if you build with Boost support enabled. I'm not sure if the Ubuntu package includes that by default.

**Comment by jeffRTC** [comment]
I have now built  it with Boost support. Got certificate from Lets Encrypt and placed on Dir.

They also provided me a certificate chain file. Whatever, I copied that one too.

I entered to Dir and then attempt to start tls_server by issuing,

`botan tls_http_server cert=certificate.crt  key=private.key --port=443 --policy=default --threads=0 --max-clients=0
`
It failed with an error,

`Error: I/O error: DataSource: Failure opening file key=private.key
`

**Comment by randombit** [comment]
The cert and key areguments are mandatory and so unnamed - should just be `tls_http_server certificate.crt private.key ...`

**Comment by jeffRTC** [comment]
@randombit  Getting this error now,

`Error: PKCS #8 private key decoding failed with PKCS #8: Unknown PEM label RSA PRIVATE KEY`

**Comment by mouse07410** [comment]
Silly question: shouldn't it be BEGIN RSA PRIVATE KEY ?

**Comment by jeffRTC** [comment]
@mouse07410 It's already in the file, 

`-----BEGIN RSA PRIVATE KEY-----`

**Comment by jeffRTC** [comment]
@randombit  I remember from an earlier issue that the format is OpenSSL specific and need to be converted into Botan format but to do that I need a password which I lack. LetsEncrypt doesn't provides a password.

**Comment by mouse07410** [comment]
I wouldn't expect either Botan or OpenSSL to be able to work with a key in whatever format, if that key is encrypted with a password that you don't know and can't pass up the app to make that key usable (aka, decrypt it first).

**Comment by jeffRTC** [comment]
@mouse07410  The key is not encrypted with a password but to convert into Botan format from OpenSSL it asks for a key. 

These keys works fine with Apache, Nginx ...

**Comment by mouse07410** [comment]
@randombit considering how widely OpenSSL is deployed - IMHO it makes sense to add the ability to _import_ keys in OpenSSL format, at the very least.
