### ISSUE TITLE
Hash_DRBG implementation

### ISSUE THREAD

**Issue by Sinkmanu** [randombit/botan#2643]
Hello, first of all, congrats for this amazing tool. My question is just to confirm that Hash_DRBG is not implemented in Botan (in case it is not). 

In https://botan.randombit.net/handbook/dev_ref/reading_list.html Standard section We can see "NIST SP 800-90A http://csrc.nist.gov/publications/nistpubs/800-90A/SP800-90A.pdf HMAC_DRBG, Hash_DRBG, CTR_DRBG, maybe one other thing?" But looking the source code I did not find any source code relative to Hash_DRBG. Is it correct? Or exist a way to run Hash_DRBG with the current source code of Botan?

Thanks in advance

**Comment by randombit** [comment]
Sorry kind of confusing - that list is just a grab bag of bookmarks or potentially useful papers. And SP800-90A is the source for all of these RNG designs. But, Botan implements (only) HMAC_DRBG from NIST, because it is IMO the most conservative option. Do you have a specific need for Hash_DRBG?

**Comment by Sinkmanu** [comment]
Do not worry, It is just for a test which is in a Protection Profile (of the NIAPP) https://www.niap-ccevs.org/Profile/Info.cfm?PPID=447&id=447 specifically test FCS_RBG_EXT.1.1 which is for Random Bit Generation. 

> FCS_RBG_EXT.1.1 The TSF  shall  perform  all  deterministic  random  bit  generation  services in  accordance with  ISO/IEC  18031:2011  using  [selection: Hash_DRBG (any), HMAC_DRBG (any), CTR_DRBG (AES)].

Thus, currently Botan can not be used to test that a Hash_DRBG is correctly implemented because it does not have implemented Hash_DRBG.

**Comment by randombit** [comment]
Not sure if it's relevant to your usage but if you are using HMAC_DRBG in a similar context be aware that we may (or may not!) be missing some tests required by that PP. I know FIPS 140 requires a repeated output test which we are not bothering with, that PP may have similar requirements.
