### ISSUE TITLE
curve25519 cosmetic change?

### ISSUE THREAD

**Issue by gaborgsomogyi** [randombit/botan#2646]
I've started to use `curve25519` but it compiles the following way. Have I forgot something set/include or the `botan` need to be changed. The functionality works like charm but it would be good to make the warnings disappear.

I'm reporting this because I've not gone after the root cause so it may or may not cause issues in some cases...

```
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(100,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::algo_name' via dominance
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(18): message : see declaration of 'Botan::Curve25519_PublicKey::algo_name'
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(100,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::estimated_strength' via dominance
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(20): message : see declaration of 'Botan::Curve25519_PublicKey::estimated_strength'
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(100,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::key_length' via dominance
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(22): message : see declaration of 'Botan::Curve25519_PublicKey::key_length'
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(100,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::algorithm_identifier' via dominance
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(26): message : see declaration of 'Botan::Curve25519_PublicKey::algorithm_identifier'
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(100,4): warning C4250: 'Botan::Curve25519_PrivateKey': inherits 'Botan::Curve25519_PublicKey::Botan::Curve25519_PublicKey::public_key_bits' via dominance
1>D:\projects\CppTor\BotanLib\include\x64\botan-2\botan\curve25519.h(28): message : see declaration of 'Botan::Curve25519_PublicKey::public_key_bits'
```

**Comment by randombit** [comment]
These warnings are unfortunately unavoidable given how the public key hierarchy is defined, with heavy use of virtual inheritance and multiple bases. Doing it over again I would not have done it the same way but it is difficult to change now and doing so would break many calling applications.

As far as I am aware this warning is basically harmless - it is saying, "you used diamond inheritance, and now I am picking one implementation of the virtual function of the several possible" which is just as it should be doing. For that reason we disable C4250 when building the library. But it causes warnings in application code when these interfaces are used :(

We could have something which disables C4250 within these header files but I am in general against disabling warnings in library headers on the general principle that the person compiling the code enabled a warning, the code in the library does in fact do something which triggers that warning, and so we should not try to silence it. Given that the warning is harmless and somewhat intrinsic to our API maybe it makes sense to do so anyway, will need to think about it...

**Comment by gaborgsomogyi** [comment]
Good to hear it's analyzed and known.

Turning off warnings in library level would be really an overkill I agree since it may hide other potential severe issues.
On client side it's not a super big pain because in my case only 1 cpp file affected. However in long term it would be
good to find some solution. Security ppls can be worried when such warnings appears :)

As it's only a cosmetic issue closing it, thank!
