### ISSUE TITLE
TLS::Stream only works with callbacks as completion tokens

### ISSUE THREAD

**Issue by finalglyph** [randombit/botan#2648]
Hi,

First of all, thank you for developing this library. It certainly made my work easier.

I wrote a TLS server using boost.asio, boost.coroutine and `Botan::TLS::Stream`. Unfortunately, during development, I discovered that `Botan::TLS::Stream` does not work with coroutines.

Actually, the problem is that `Botan::TLS::Stream` does not correctly participate in boost.asio's ***extensible asynchronous model*** and, as a result, only supports callback functions as completion tokens.

While investigating this issue, I found C++ standard proposal [N4045](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4045.pdf), which does a great job of explaining the extensible asynchronous model (in chapters 7, 8 and 9).

The following minimal TLS (echo) server using boost stackful coroutines does not compile (Arch Linux, gcc 10.2, C++17, boost 1.75, Botan 2.17.3).

```cpp
#include <botan/credentials_manager.h>
#include <botan/x509cert.h> // for Botan::X509_Certificate
#include <botan/pk_keys.h> // for Botan::Private_Key
#include <botan/data_src.h> // for Botan::DataSource_Stream
#include <botan/pkcs8.h> // for Botan::PKCS8::load_key
#include <string>
#include <vector>
#include <memory> // for std::unique_ptr

class credentials_manager : public Botan::Credentials_Manager
{
public:

	credentials_manager(const std::string& cert_chain_file, const std::string& private_key_file)
	{
		for (Botan::DataSource_Stream stream{cert_chain_file}; !stream.end_of_data(); /**/)
		{
			m_cert_chain.emplace_back(stream);
		}

		if (Botan::DataSource_Stream stream{private_key_file}; !stream.end_of_data())
		{
			m_private_key = Botan::PKCS8::load_key(stream);
		}
	}

private:

	std::vector<Botan::X509_Certificate> find_cert_chain(const std::vector<std::string>& cert_key_types, const std::vector<Botan::X509_DN>& acceptable_cas, const std::string& type, const std::string& context) override
	{
		if (!std::count(cert_key_types.begin(), cert_key_types.end(), m_private_key->algo_name()))
		{
			return {};
		}

		return m_cert_chain;
	}

	Botan::Private_Key *private_key_for(const Botan::X509_Certificate& cert, const std::string& type, const std::string& context) override
	{
		if (cert != m_cert_chain.front())
		{
			return nullptr;
		}

		return m_private_key.get();
	}

	std::vector<Botan::X509_Certificate> m_cert_chain;
	std::unique_ptr<Botan::Private_Key> m_private_key;
};

#include <boost/asio/io_context.hpp>
#include <boost/asio/signal_set.hpp>
#include <boost/asio/ip/tcp.hpp>
#include <boost/asio/ip/address.hpp> // for boost::asio::ip::make_address
#include <boost/asio/spawn.hpp>
#include <boost/asio/buffer.hpp>
#include <boost/system/error_code.hpp>
#include <botan/tls_session_manager.h> // for Botan::TLS::Session_Manager_Noop
#include <botan/system_rng.h>
#include <botan/tls_policy.h> // for Botan::TLS::Strict_Policy
#include <botan/asio_context.h> // for Botan::TLS::Context
#include <botan/asio_stream.h> // for Botan::TLS::Stream
#include <thread>
#include <vector>
#include <utility> // for std::move
#include <exception>
#include <cstddef> // for std::byte, std::size_t
#include <signal.h> // for SIGINT, SIGTERM

namespace asio = boost::asio;

int main(int argc, char *argv[])
{
	credentials_manager credentials_manager{"cert-chain.pem", "private-key.pem"};
	Botan::TLS::Session_Manager_Noop tls_session_manager;

	int thread_count = 4;
	asio::io_context ioc{thread_count};
	asio::signal_set signal_set{ioc, SIGINT, SIGTERM};
	asio::ip::tcp::acceptor acceptor{ioc, {asio::ip::make_address("127.0.0.1"), 443}};

	asio::spawn(ioc, [&](asio::yield_context yc)
	{
		signal_set.async_wait(yc);

		ioc.stop();
	});

	asio::spawn(ioc, [&](asio::yield_context yc)
	{
		while (true)
		{
			asio::ip::tcp::socket connected_socket{ioc};

			acceptor.async_accept(connected_socket, yc);

			asio::spawn(ioc, [&, socket = std::move(connected_socket)](asio::yield_context yc) mutable
			{
				Botan::System_RNG rng;
				Botan::TLS::Strict_Policy tls_policy;

				Botan::TLS::Context tls_context{credentials_manager, rng, tls_session_manager, tls_policy};

				Botan::TLS::Stream<asio::ip::tcp::socket> tls_stream{std::move(socket), tls_context};

				try
				{
					tls_stream.async_handshake(Botan::TLS::Connection_Side::SERVER, yc);

					std::byte data[1024];

					while (true)
					{
						std::size_t bytes_read = tls_stream.async_read_some(asio::buffer(data), yc);

						for (auto data_to_be_written = asio::buffer(data, bytes_read); data_to_be_written.size() > 0; /**/)
						{
							data_to_be_written += tls_stream.async_write_some(data_to_be_written, yc);
						}
					}
				}
				catch (const std::exception& e)
				{
					boost::system::error_code ec;
					tls_stream.async_shutdown(yc[ec]);
				}
			});
		}
	});

	std::vector<std::thread> threads;

	for (auto i = 0; i < (thread_count - 1); ++i)
	{
		threads.emplace_back([&ioc](){ ioc.run(); });
	}

	ioc.run();

	for (auto& thread : threads)
	{
		thread.join();
	}
}
```

The first (and most relevant) compilation error looks like this:

```
/usr/include/botan-2/botan/asio_async_ops.h:88:35: error: no matching function for call to ‘boost::asio::basic_yield_context<...>::basic_yield_context(boost::asio::detail::coro_handler<...>)’
```

No errors occur if `boost::asio::ssl::stream` is used, so what does it do differently?

boost.asio's extensible asynchronous model relies heavily on the `boost::asio::async_result<...>` customization point. This "traits" class template is responsible for:
- determining the completion handler type from the completion token type and a desired completion handler signature
- determining the return type of the initiating (i.e. `async_*`) function
- getting the return value of the initiating function

The completion **token** is the object passed to `async_*` functions as a *placeholder* for the completion handler.
The completion **handler** is the function object that is actually *called* at the end of the asynchronous operation.
Basically, `boost::asio::async_result<...>` knows how to "convert" a completion token to a completion handler.

The `boost::asio::async_result<...>` primary template is a "no-op" (completion handler type = completion token type and all initiating functions return void). The primary template gets instantiated when the completion token is a callback function.

`boost::asio::async_result<...>` is specialized for completion token type `boost::asio::basic_yield_context<...>` (in "boost/asio/impl/spawn.hpp"). This "teaches" boost.asio to work with boost.coroutine.

As long as an initiating (i.e. `async_*`) function uses the `boost::asio::async_result<...>` trait properly, it **automatically** supports "all" completion token types (coroutines, futures, etc.).

Looking at the implementation of `boost::asio::ssl::stream::async_*`, these functions immediately call `boost::asio::async_initiate<...>`, to which they pass a function object. This function object receives the completion **handler** (the result of "converting" the completion **token**) as first argument. `boost::asio::async_initiate<...>` is a wrapper around `boost::asio::async_result<...>` that ensures its correct use.

Now, let's look at how `Botan::TLS::Stream::async_*` functions are implemented.

They use `boost::asio::async_completion<...>`, which is a lower-level wrapper around `boost::asio::async_result<...>` than function `boost::asio::async_initiate<...>`. `boost::asio::async_initiate<...>` (the "high-level wrapper") sometimes delegates to `boost::asio::async_result<...>::initiate<...>` instead of using `boost::asio::async_completion<...>` internally, so I would prefer to use `boost::asio::async_initiate<...>`. This is just a side note, though.

The problem is that `Botan::detail::Async*Operation<...>` is always instantiated with the completion **token** type (instead of the completion **handler** type).

When using boost stackful coroutines, the completion **token** type is `boost::asio::basic_yield_context<...>` and the completion **handler** type is `boost::asio::detail::coro_handler<...>`, so the above compilation error now makes sense.

Luckily, one can work around this mistake in `Botan::TLS::Stream` by inheriting from it and overwriting all its `anync_*` functions:

```cpp
#ifndef TLS_STREAM_REPLACEMENT_HPP
#define TLS_STREAM_REPLACEMENT_HPP

#include <boost/asio/async_result.hpp> // for boost::asio::async_initiate
#include <boost/asio/detail/handler_type_requirements.hpp> // for BOOST_ASIO_*_HANDLER_CHECK macros
#include <boost/asio/buffer.hpp> // for boost::asio::buffer_size
#include <boost/system/error_code.hpp>
#include <botan/asio_stream.h> // for Botan::TLS::Stream
#include <botan/asio_async_ops.h> // for Botan::TLS::detail::Async*Operation types
#include <botan/tls_channel.h> // for Botan::TLS::Channel
#include <botan/tls_magic.h> // for Botan::TLS::Connection_Side
#include <type_traits> // for std::decay_t
#include <utility> // for std::forward, std::move

template <typename NextLayer, typename Channel = Botan::TLS::Channel>
class tls_stream_replacement : public Botan::TLS::Stream<NextLayer, Channel>
{
public:

	using base = Botan::TLS::Stream<NextLayer, Channel>;

	using base::Stream;

	template <typename CompletionToken>
	auto async_handshake(Botan::TLS::Connection_Side side, CompletionToken&& completion_token)
	{
		return boost::asio::async_initiate<CompletionToken, void(boost::system::error_code)>(
			[this](auto&& completion_handler, Botan::TLS::Connection_Side side)
			{
				using completion_handler_t = std::decay_t<decltype(completion_handler)>;

				BOOST_ASIO_HANDSHAKE_HANDLER_CHECK(completion_handler_t, completion_handler) type_check;

				boost::system::error_code ec;
				base::setup_native_handle(side, ec);

				Botan::TLS::detail::AsyncHandshakeOperation<completion_handler_t, base> op
				{
					std::forward<completion_handler_t>(completion_handler),
					*this,
					ec
				};
			}, completion_token, side);
	}

	template <typename MutableBufferSequence, typename CompletionToken>
	auto async_read_some(const MutableBufferSequence& buffers, CompletionToken&& completion_token)
	{
		return boost::asio::async_initiate<CompletionToken, void(boost::system::error_code, std::size_t)>(
			[this](auto&& completion_handler, const auto& buffers)
			{
				using completion_handler_t = std::decay_t<decltype(completion_handler)>;

				BOOST_ASIO_READ_HANDLER_CHECK(completion_handler_t, completion_handler) type_check;

				Botan::TLS::detail::AsyncReadOperation<completion_handler_t, base, MutableBufferSequence> op
				{
					std::forward<completion_handler_t>(completion_handler),
					*this,
					buffers
				};
			}, completion_token, buffers);
	}

	template <typename ConstBufferSequence, typename CompletionToken>
	auto async_write_some(const ConstBufferSequence& buffers, CompletionToken&& completion_token)
	{
		return boost::asio::async_initiate<CompletionToken, void(boost::system::error_code, std::size_t)>(
			[this](auto&& completion_handler, const auto& buffers)
			{
				using completion_handler_t = std::decay_t<decltype(completion_handler)>;

				BOOST_ASIO_WRITE_HANDLER_CHECK(completion_handler_t, completion_handler) type_check;

				boost::system::error_code ec;
				base::tls_encrypt(buffers, ec);

				if (ec)
				{
					base::consume_send_buffer(base::m_send_buffer.size());
				}

				Botan::TLS::detail::AsyncWriteOperation<completion_handler_t, base> op
				{
					std::forward<completion_handler_t>(completion_handler),
					*this,
					ec ? 0 : boost::asio::buffer_size(buffers),
					ec
				};
			}, completion_token, buffers);
	}

	template <typename CompletionToken>
	auto async_shutdown(CompletionToken&& completion_token)
	{
		return boost::asio::async_initiate<CompletionToken, void(boost::system::error_code)>(
			[this](auto&& completion_handler)
			{
				using completion_handler_t = std::decay_t<decltype(completion_handler)>;

				BOOST_ASIO_SHUTDOWN_HANDLER_CHECK(completion_handler_t, completion_handler) type_check;

				auto adapted_handler =
					[inner_handler = std::forward<completion_handler_t>(completion_handler)]
					(boost::system::error_code ec, std::size_t) mutable
					{
						inner_handler(ec);
					};

				boost::system::error_code ec;
				base::try_with_error_code([&]{ base::native_handle()->close(); }, ec);

				Botan::TLS::detail::AsyncWriteOperation<decltype(adapted_handler), base> op
				{
					std::move(adapted_handler),
					*this,
					boost::asio::buffer_size(base::send_buffer()),
					ec
				};
			}, completion_token);
	}
};

#endif // TLS_STREAM_REPLACEMENT_HPP
```

If you replace `Botan::TLS::Stream` with `tls_stream_replacement` in the simple TLS server example above, it will compile (and probably work - my real server does).

In the original example (without `tls_stream_replacement`), if I had written `asio::async_write(tls_stream, asio::buffer(data, bytes_read), yc);` instead of the `for` loop in which I call `tls_stream.async_write_some`, this wouldn't have triggered a compilation error inside `Botan::TLS::Stream::async_write_some`. The reason for this behavior is that `boost::asio::async_write` first converts the completion token to a completion handler and then calls the stream's `async_write_some` function with the completion **handler** as completion token. This probably applies to all ***composed** asynchronous operations* and is the reason why I only had to overwrite `Botan::TLS::Stream`'s `async_handshake` and `async_shutdown` functions to get my real server to work.

Though unrelated to this issue, I also noticed that `Botan::TLS::Stream::async_shutdown` doesn't pass the error code from `native_handle()->close()` to `Botan::detail::AsyncWriteOperation<...>`'s constructor.

In conclusion, `Botan::TLS::Stream` is very close to being a "proper" replacement for `boost::asio::ssl::stream`, but falls short of this goal due to a small mistake that made it very "inconvenient" to use with completion tokens other than callbacks. I think it would be a shame not to address this issue, as coroutines simplify network programming quite a lot (for example).

**Comment by randombit** [comment]
Your proposal seems like a positive step. Thanks for the detailed writeup. @hrantzsch @reneme what do you think?

**Comment by hrantzsch** [comment]
Thank you for the detailed writeup indeed! We'll gladly look into it, but probably not any earlier than next week.

**Comment by finalglyph** [comment]
Glad to help! Thanks to this issue, my understanding of boost.asio has improved.

**Comment by finalglyph** [comment]
Yesterday I discovered another problem: the handler **wrapper** used by `Botan::TLS::Stream` inside `async_shutdown` does not "forward" the wrapped handler's ***executor***, which causes hard-to-debug crashes when coroutines are used.

In the following, I will explain my understanding of the situation, but keep in mind that I'm no boost.asio expert.

All of `Botan::TLS::Stream`'s `async_*` operations are ***composed** asynchronous operations* because they execute a sequence of "lower level" operations such as `Botan::TLS::Stream::next_layer_type::async_read_some`.

When implementing a composed asynchronous operation, care must be taken to invoke all "lower level" operations on the correct *executor* (and with the correct *allocator*).

If the composed operation's completion handler has an *associated executor*, then that is the executor on which all of the composed operation's steps should run. Otherwise, the IO object's (e.g. `Botan::TLS::Stream`'s) associated executor should be used.

In many cases (such as when callbacks are used as completion tokens), the completion handler doesn't have an associated executor, so composed asynchronous operations default to using the IO object's (e.g. socket's) associated executor, which is typically `boost::asio::io_context::executor_type` (type-erased by `boost::asio::io_context::any_io_executor`).

When a boost (stackful) coroutine is started using the typical call `boost::asio::spawn(io_context, [/*...*/](boost::asio::yield_context yc){ /*...*/ }`, `io_context.get_executor()` is wrapped in a *strand* and stored inside `yc` (the coroutine "handle"). Then, all completion **handlers** derived from `yc` (the completion **token**) will essentially have an object of type `boost::asio::strand<boost::asio::io_context::executor_type>` as *associated executor*. The important part is that this executor is **different** from `io_context.get_executor()`.

`Botan::TLS::Stream` does a good job of ensuring that the completion handler's associated executor and allocator, if any, are used by the lower level async operations. `Botan::TLS::detail::AsyncBase` correctly "forwards" the completion handler's executor and allocator by implementing `executor_type`/`get_executor` and `allocator_type`/`get_allocator`.

However, in `Botan::TLS::Stream<...>::async_shutdown`, the completion handler is **transformed** (adapted) before being passed to `Botan::TLS::detail::AsyncBase`'s constructor and the handler **adapter** type (`ShutdownHandlerWrapper`) does **not** forward the original completion handler's executor (simply by not "specifying" an associated executor). This causes all `async_write_some` steps that are part of `async_shutdown` to be executed on the **wrong** executor (the **stream**'s associated executor instead of the **handler**'s associated executor).

In the paragraph above I said "completion handler", but the current `Botan::TLS::Stream<...>::async_shutdown` transforms (adapts) the completion **token** instead of the completion **handler**, which is incorrect (for reasons mentioned in the first post). The explanation above is actually more directly applicable to my `tls_stream_replacement` workaround (see first post), which suffered from the same issue.

Here is the corrected `tls_stream_replacement<...>::async_shutdown`:

```cpp
#ifndef TLS_STREAM_REPLACEMENT_HPP
#define TLS_STREAM_REPLACEMENT_HPP

// same includes as before

#include <boost/asio/associated_executor.hpp>
#include <boost/asio/associated_allocator.hpp>

template <typename NextLayer, typename Channel = Botan::TLS::Channel>
class tls_stream_replacement : public Botan::TLS::Stream<NextLayer, Channel>
{
public:

	using base = Botan::TLS::Stream<NextLayer, Channel>;

	// same code as before

private:

	template <typename Handler, typename IoExecutor>
	struct handler_adapter
	{
		void operator()(boost::system::error_code ec, std::size_t)
		{
			handler(ec);
		}

		using executor_type = boost::asio::associated_executor_t<Handler, IoExecutor>;

		executor_type get_executor() const noexcept
		{
			return boost::asio::get_associated_executor(handler, io_executor);
		}

		using allocator_type = boost::asio::associated_allocator_t<Handler>;

		allocator_type get_allocator() const noexcept
		{
			return boost::asio::get_associated_allocator(handler);
		}

		Handler handler;

		IoExecutor io_executor;
	};

public:

	template <typename CompletionToken>
	auto async_shutdown(CompletionToken&& completion_token)
	{
		return boost::asio::async_initiate<CompletionToken, void(boost::system::error_code)>(
			[this](auto&& completion_handler)
			{
				using completion_handler_t = std::decay_t<decltype(completion_handler)>;

				BOOST_ASIO_SHUTDOWN_HANDLER_CHECK(completion_handler_t, completion_handler) type_check;

				boost::system::error_code ec;
				base::try_with_error_code([&]{ base::native_handle()->close(); }, ec);

				using write_handler_t = handler_adapter<completion_handler_t, typename base::executor_type>;

				Botan::TLS::detail::AsyncWriteOperation<write_handler_t, base> op
				{
					write_handler_t{std::forward<completion_handler_t>(completion_handler), base::get_executor()},
					*this,
					boost::asio::buffer_size(base::send_buffer()),
					ec
				};
			}, completion_token);
	}
};

#endif // TLS_STREAM_REPLACEMENT_HPP
```

As you can see, `tls_stream_replacement<...>::handler_adapter<...>` is equipped to "forward" the wrapped handler's executor (and allocator), so the handler wrapper no longer breaks the executor (and allocator) forwarding chain. This means that completion handlers derived from (boost, stackful) coroutines execute on the **handler**'s associated executor, not on the **stream**'s associated executor.

Before the fix, the following assertion failure was **sometimes** triggered from inside `async_shutdown`:

```
/usr/include/boost/coroutine/detail/push_coroutine_impl.hpp:258: void boost::coroutines::detail::push_coroutine_impl<void>::push(): Assertion `! is_running()' failed.
```

It happened while the server was executing multiple requests in parallel (i.e. on multiple threads at the same time), after it had successfully completed a number of (composed) asynchronous operations, including `async_shutdown`s.

I definitely don't understand the **entire** chain of events that lead to the crash, but it looks like using the wrong executor causes some sort of race condition in boost.asio or boost.coroutine.

There are a couple of threads on stackoverflow where people have run into the same issue ([1](https://stackoverflow.com/questions/54484514/void-boostcoroutinesdetailpush-coroutine-implvoidpush-assertion), [2](https://stackoverflow.com/questions/57667531/use-of-boost-coroutine-with-boost-asio-causes-assertion)). Everything I read there is consistent with my own observations and understanding (i.e. that the root cause is not dispatching to the coroutine's "special" executor).

Since I made the above `tls_stream_replacement` fix, my server hasn't crashed. It's too early to conclude that there are no more issues, though.

At any rate, `ShutdownHandlerWrapper` not "forwarding" the wrapped handler's executor (and allocator) is **definitely** an issue in `Botan::TLS::Stream`. It doesn't surface unless certain types of completion tokens (e.g. coroutine handles) are used, but can cause nasty crashes when it does. Luckily, it looks like this second issue can also be fixed relatively easily.
