### ISSUE TITLE
EC_Group - inconsistent behavior when converting from domain parameters to OID

### ISSUE THREAD

**Issue by finalglyph** [randombit/botan#2649]
Hi,

One of my use cases is reading the DER-encoded domain parameters of an elliptic curve from an external source and finding out which "named" curve they correspond to.

In other words, I sometimes need to get the OID of an elliptic curve (that is known by Botan) from its domain parameters.

I found that, while `Botan::EC_Group` **can** do this "DP to OID" conversion, it does not do it ***reliably*** unless a workaround is used.

The following test program demonstrates the specific situations I will describe below. My environment is Arch Linux, with gcc 10.2 and Botan 2.17.3.

```cpp
#include <botan/ec_group.h>
#include <botan/asn1_obj.h> // for Botan::OID
#include <fstream>
#include <vector>
#include <cassert>

void write_buffer_to_file(const std::vector<uint8_t>& buffer, const char *file_name)
{
	std::ofstream stream{file_name, std::ios::binary};
	stream.write(reinterpret_cast<const char *>(buffer.data()), buffer.size());
}

std::vector<uint8_t> read_buffer_from_file(const char *file_name)
{
	std::ifstream stream{file_name, std::ios::binary | std::ios::ate};
	std::vector<uint8_t> buffer(stream.tellg());
	stream.seekg(0);
	stream.read(reinterpret_cast<char *>(buffer.data()), buffer.size());
	return buffer;
}

void write_ec_param_to_file(const Botan::OID& ec_oid, const char *file_name)
{
	Botan::EC_Group ec_group{ec_oid};

	auto ec_param_der = ec_group.DER_encode(Botan::EC_Group_Encoding::EC_DOMPAR_ENC_EXPLICIT);

	write_buffer_to_file(ec_param_der, file_name);
}

Botan::OID read_ec_oid_from_file(const char *file_name)
{
	auto ec_param_der = read_buffer_from_file(file_name);

	Botan::EC_Group ec_group{ec_param_der};

	return ec_group.get_curve_oid();
}

int main(int argc, char *argv[])
{
	write_ec_param_to_file(Botan::OID::from_string("secp256r1"), "secp256r1.der");

	// expected and desirable behavior
	assert(read_ec_oid_from_file("secp256r1.der").to_formatted_string() == "secp256r1");

	// simulate application restart
	Botan::EC_Group::clear_registered_curve_data();

	// unexpected and undesirable behavior
	assert(read_ec_oid_from_file("secp256r1.der").has_value() == false);

	// as workaround, manually "register" the curve
	Botan::EC_Group{Botan::OID::from_string("secp256r1")};

	// workaround failed; an "unnamed" curve with the same parameters was already registered and has priority
	assert(read_ec_oid_from_file("secp256r1.der").has_value() == false);

	// simulate application restart
	Botan::EC_Group::clear_registered_curve_data();

	// manually register the curve of interest before any other operation involving it
	Botan::EC_Group{Botan::OID::from_string("secp256r1")};

	// workaround succeeded
	assert(read_ec_oid_from_file("secp256r1.der").to_formatted_string() == "secp256r1");
}
```

First, I create a `Botan::EC_Group` instance for the known curve "secp256r1". Then, I DER-encode it as domain parameters and write the resulting buffer to a file. Immediately afterwards, I read the file, construct another `Botan::EC_Group` from the file contents, and get the curve OID from this second `EC_Group` object.

As expected, the OID is available and coresponds to the name "secp256r1". So far, so good.

Now, let's suppose I restart my application and try to get a curve OID from the same file again. (Since I'm calling `Botan::EC_Group::clear_registered_curve_data` to simulate an application restart, you can probably already guess where this is going.)

As before, the curve is deserialized successfully, but this time the resulting `EC_Group` object has an "empty" OID. Since the "domain parameters to OID" conversion worked before the "restart", this outcome is quite unexpected.

After spending some time examining `Botan::EC_Group`'s implementation, I figured out that it stores the full representations of all curves it ever "worked with" in a global, thread-safe cache referred to as "registered curves". Built-in curves are first "loaded" into this cache before being used through `EC_Group` objects. If an `EC_Group` object exists (or existed) for a curve, then that curve's full representation is present in the global cache.

Having a cache as implementation detail is fine, as long as it is ***transparent*** to the library user. Its state should not influence what can and cannot be done with the library at a given time.

Getting back to the code, I now suspect the missing OID has to do with the fact that Botan never had a chance to "load" its built-in "secp256r1" curve the second time around, so I try to load and "register" it artificially, by constructing an `EC_Group` only for the constructor's side-effect of loading and registering the curve.

However, this does not work "after the fact". Previously, deserializing the `EC_Group` caused an "external" curve with the same domain parameters as "secp256r1" to be registered **without an OID**. Manually registering "secp256r1" then added **another** "secp256r1" representation to the cache, one that includes an OID. When the deserialization was re-attempted, cache lookup during `EC_Group` construction resolved to the first "secp256r1" entry in the cache - the one **without an OID**.

Finally, if (after another "restart") "secp256r1" is manually registered before any `EC_Group` object is constructed from its domain parameters (e.g. during application startup), getting its OID after deserializing it from domain parameters always works, and the cache never ends up with duplicate "secp256r1" representations.

Now, if you're wondering why I can't just encode the `EC_Group` as OID (instead of DP) and avoid this problematic "domain parameters to OID" conversion, that's because I have to work with an HSM that has "limited support" for certain elliptic curves. I must give it the curve as DP and it gives it to me back as DP. But elsewhere in my application, I must "present" the same curve by name (or OID).

So, getting a "domain parameters to OID" conversion to work **reliably** requires what can now only be called a *workaround*, even though I think it's reasonable to expect "DP to OID" conversions to **always** work (for the known curves).

The "root issues" are that built-in curves:
1. cannot be searched for by domain parameters (they can only be searched for by OID) and
2. cannot be accessed directly (without being first "loaded" into the cache).

A "quick fix" for the first root issue would require that practically **all** built-in curves be loaded (i.e. "expanded" from their hardcoded, string literal form) before **any** DP comparison is performed, since comparing two sets of domain parameters involves comparing `BigInt`s, and `Botan::BigInt`s cannot be constructed at compile-time.

In terms of memory overhead, the changes needed to properly support the "DP to OID" use case within the current framework would effectively be equivalent to running

```cpp
for (const auto& ec_name : Botan::EC_Group::known_named_groups())
{
	Botan::EC_Group{ec_name};
}
```

the first time an `EC_Group` object is constructed from domain parameters by the library user (or earlier). Needless to say, allocating memory for all those elliptic curve representations would be quite wasteful, as most library users probably won't *ever* need to get a curve's OID from its DP. To put it another way, the "easy fix for DP-to-OID" would be like **automatically** applying the above-mentioned workaround for every known curve. Therefore, I suppose the only "reasonable" expectation I can have is for Botan to either:
1. document the workaround somewhere or
2. add something like a static function `EC_Group::load_known_groups(const std::vector<Botan::OID>& ec_group_oids)` that the library user can call to "officially" enable the "DP to OID" use case only for a subset of the known curves. (Note that this would also provide some symmetry with the private-ish `EC_Group::clear_registered_curve_data`.)

The third, and **best** option I see would be to develop *compile-time elliptic curve representations* (i.e. objects like `Botan::EC_Group_Data` that can be constructed at compile time, and thus allocate no heap memory). Inspiration can be taken from [this compile-time BigNum library](https://github.com/niekbouman/ctbignum) and [its introductory paper](https://arxiv.org/abs/1804.07236). This solution would be by far the hardest to implement, but it's something that should probably be considered for any future `EC_Group` major rewrite, as it has the potential to increase runtime performance of elliptic curve operations.

Having all built-in curves "already fully loaded" after library compilation means that they wouldn't need to be loaded and "cached" at **runtime** and that their domain parameters (i.e. BigInts) would be directly comparable with those of "runtime-constructed" `EC_Group` objects, thereby solving both "root issues" above. The "DP to OID conversion" problem described here is, of course, too small to trigger such big changes in the library **by itself**. However, it's one more reason to consider going down the `constexpr` route in the future.

**Comment by randombit** [comment]
I don't think always loading all of the groups is viable because the whole approach is based around a desire to create + cache precomputed values (multiples of the generator, etc). On slower machine like a Raspberry Pi 2, loading a single group (and creating said precomputations) can be on the order of > 10 ms. So doing it for all groups could cause a nasty pause.

Certainly we can do something like `EC_Group::load_known_groups` that's not hard. But I'd like to see if we can do something a bit more satisfactory. One thing that might work is to have a secondary index which is from group order -> OID. Then if a EC group is loaded from params, we first attempt to look up the OID using the order, and either reuse the existing cache if it exist or if this is first use, attach the OID to the record. What do you think?

A const time integer library would be great! But, also a lot of work. :/ Thanks for linking to that ct library though, looks interesting.

> Manually registering "secp256r1" then added another "secp256r1" representation to the cache, one that includes an OID. When the deserialization was re-attempted, cache lookup during EC_Group construction resolved to the first "secp256r1" entry in the cache - the one without an OID.

This is definitely a library bug - this sequence is supposed to cause the two cached values to be merged with the OID set. I thought we even had a test of this, I guess not... Fixing this won't solve your general issue here, but at least make the behavior less obnoxious.

**Comment by randombit** [comment]
I think #2654 will resolve this problem - can you take a look?

**Comment by finalglyph** [comment]
Hi @randombit,

Thank you for the (very!) quick response and solution, and for going beyond my simple suggestions.

> I don't think always loading all of the groups is viable ...

I agree this should be avoided for performance reasons.

> One thing that might work is to have a secondary index which is from group order -> OID.

I reviewed pull request #2654 and have no issue with the general approach.

I see the group order match is followed up by a full DP comparison, so there are no concerns about an external, "unnamed" group having the same order as a built-in group being assigned the built-in group's OID.

By using the group order match as "hint" for a likely full DP match, you only have to allocate 1 `BigInt` per built-in curve instead of 6 (for the full set of domain parameters) during the DP match attempt.

Still, for every **distinct** and "unnamed" curve used with `EC_Group`, potentially more than 20 `BitInt`s will be constructed during the attempt to match the unnamed curve to a known OID (inside `EC_Group::EC_group_identity_from_order`). I suppose this is acceptable, though, as applications typically only use a small number of distinct elliptic curves.

> This is definitely a library bug - this sequence is supposed to cause the two cached values to be merged with the OID set.

I see you fixed it today in pull request #2651, thanks.

**Comment by randombit** [comment]
> Still, for every distinct and "unnamed" curve used with EC_Group, potentially more than 20 BitInts will be constructed during the attempt to match the unnamed curve to a known OID (inside EC_Group::EC_group_identity_from_order). I suppose this is acceptable, though, as applications typically only use a small number of distinct elliptic curves.

I don't think this is that costly especially compared to the overhead of the precomputations that happen when creating a new `EC_Group`. However here it really is easily avoidable because we can first extract the low 32 bits of the order, which are already perfectly unique given the current set of well known groups, and compare that first and only doing a full comparison afterwards. Then we will create at most 1 BigInt per lookup via order, and the majority of the cost will just be a sequence of 32-bit integer comparisons.

**Comment by finalglyph** [comment]
I see. That's a pretty good idea.

But I wasn't *concerned* about those `BigInt` allocations. I just wanted to point them out.

It's up to you whether you implement this additional optimization or not. Your changes so far (#2654) have already fixed this issue.

**Comment by randombit** [comment]
If that code wasn't generated I would worry about that optimization - it would be too easy to typo something. But with the script handling it, it seems like an easy win.

**Comment by randombit** [comment]
@finalglyph I believe #2654 (plus the prior #2651) addresses completely the problems described in this issue but I wanted to confirm that with you prior to merging 2654

**Comment by finalglyph** [comment]
Indeed, pull request #2654 does a great job of fixing the "DP to OID conversion" issue. (I see you also optimized lookup by order for the "no match" case.)

Thanks for the quick **and** thorough solution! This issue can be closed after the merge.
