### ISSUE TITLE
Botan::PKCS11::LowLevel doesn't have a getter for m_func_list_ptr

### ISSUE THREAD

**Issue by finalglyph** [randombit/botan#2650]
Hi,

This issue can also be considered a minor feature request.

After I construct a `Botan::PKCS11::LowLevel` object from a `Botan::PKCS11::FunctionListPtr` (AKA `CK_FUNCTION_LIST_PTR`), I would like to be able to get the `FunctionListPtr` stored inside my `LowLevel` object.

Right now, to be able to access both the "raw" PKCS#11 interface and Botan's "low level" wrapper over it, I have to keep both a `FunctionListPtr` and a `LowLevel` object as data members of my class, which is quite awkward.

I see very little reason for `Botan::PKCS11::LowLevel` to **not** have a `get_functions` (or similarly named) member function.

The main reason I must access the "raw" PKCS#11 interface is that I'm working with a PKCS#11 module (provided by a major HSM vendor) that implements *PKCS#11 API **extensions***. With this PKCS#11 module, the `CK_FUNCTION_LIST_PTR` populated by `C_GetFunctionList` actually points to an "extended" `CK_FUNCTION_LIST` structure, which has the layout of a standard `CK_FUNCTION_LIST` structure, except that it contains extra function pointers at the end for the extension functions. I must be able to call these extension functions, and the most straightforward way to do that would be through the `CK_FUNCTION_LIST_PTR` wrapped by `Botan::PKCS11::LowLevel` (which I'm using because it provides convenience when working with the "standard part" of PKCS#11).

I understand that Botan cannot "support" vendor extensions to the PKCS#11 API, but I think its low-level PKCS#11 API wrapper should be flexibile enough to "allow" use cases such as the above.

**Comment by randombit** [comment]
Your proposed change seems fine to me. @neusdan any thoughts?

**Comment by randombit** [comment]
@finalglyph AIUI all you need here is #2652 is this correct?

**Comment by finalglyph** [comment]
Thanks for the quick fix.

Yes, the getter is everything I asked for.

But if you're willing to go further to support "vendor extensions" use cases, it would make sense to also expose function `Botan::PKCS11::handle_return_value`. A library user working with an "extended" PKCS#11 API could extend (i.e. derive from) `Botan::PKCS11::LowLevel` and easily implement wrappers for extension functions that use the same error handling strategy as the wrappers for standard functions in the base class.

**Comment by randombit** [comment]
That seems totally reasonable to me. We could move it to a protected member fn as `LowLevel::handle_return_value` so it was available for use by subclasses. You would still be on your own for the higher level wrappers but at least it wouldn't be necessary to replicate code that already exists but currently just isn't available to a library user.

**Comment by finalglyph** [comment]
Great, thanks!

Feel free to close this issue after you've merged pull request #2658.

**Comment by randombit** [comment]
Both PRs merged now. Thank you for raising these issues.
