### ISSUE TITLE
Base32 decode issue

### ISSUE THREAD

**Issue by gaborgsomogyi** [randombit/botan#2656]
Seems like tor guys are not using the mainstream `base32` algo and onion addresses can't be decoded neither with online decoders nor with `botan`. I've attached the tor way of encoding/decoding which works. There are inputs which makes `botan` to throw exceptions like this: `Botan::Invalid_Argument at memory location 0x00000069CFAFDD40`

Inputs:
* pg6mmjiyjmcrsslvykfwnntlaru7p5svn6y2ymmju6nubxndf4pscryd
* sp3k262uwy4r2k3ycr5awluarykdpag6a7y33jxop4cs2lu5uz5sseqd
* xa4r2iadxm55fbnqgwwi5mymqdcofiu3w6rpbtqn7b2dyn7mgwj64jyd

Since online tools also fail I'm pretty sure tor has nasty tricks inside but unless not 100% required I wouldn't re-implement `base32`. If somebody could have a look I would appreciate it.

[Base32.zip](https://github.com/randombit/botan/files/6131423/Base32.zip)

**Comment by gaborgsomogyi** [comment]
A reference from the specification:
```
6. Encoding onion addresses [ONIONADDRESS]

   The onion address of a hidden service includes its identity public key, a
   version field and a basic checksum. All this information is then base32
   encoded as shown below:

     onion_address = base32(PUBKEY | CHECKSUM | VERSION) + ".onion"
     CHECKSUM = H(".onion checksum" | PUBKEY | VERSION)[:2]

     where:
       - PUBKEY is the 32 bytes ed25519 master pubkey of the hidden service.
       - VERSION is an one byte version field (default value '\x03')
       - ".onion checksum" is a constant string
       - CHECKSUM is truncated to two bytes before inserting it in onion_address

  Here are a few example addresses:

       pg6mmjiyjmcrsslvykfwnntlaru7p5svn6y2ymmju6nubxndf4pscryd.onion
       sp3k262uwy4r2k3ycr5awluarykdpag6a7y33jxop4cs2lu5uz5sseqd.onion
       xa4r2iadxm55fbnqgwwi5mymqdcofiu3w6rpbtqn7b2dyn7mgwj64jyd.onion

   For more information about this encoding, please see our discussion thread
   at [ONIONADDRESS-REFS].
```

**Comment by randombit** [comment]
I think it's possible Tor uses the standard (RFC 4648) base32 except that it lowercases everything. If I uppercase these they decode and do have the correct 03 version byte. This casing seems incorrect re the RFC spec "These characters, identified in Table 3, below, are selected from US-ASCII digits and **uppercase** letters." which is why we reject lowercase, but at least the translation is really easy.

**Comment by gaborgsomogyi** [comment]
Oh gosh, seems like I've picked the only wrongly implemented online tool because I've tried the uppercase stuff (of course not in `botan`). It works like charm in uppercase and thanks for answering such a junior question :)
