### ISSUE TITLE
Should I make session_manager global?

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2661]
As noted from previous issue, it appear the messages are being sent to already established connection.  I'm not sure what causing this but my guess is that this has to do with my Connection object. 

I use ` Botan::TLS::Session_Manager_In_Memory ` inside `Connection ` class and it's not Global. 

At every new connection, a new Session_Manager would be created unless we found an already existing connection we would use that Connection's Session_Manager. The connection is stored under IP:PORT in a unordered_map. I use IP:PORT because it's unique and persistent. The connection object get deleted from map when the client disconnect the socket. 

So, what should I do here? Should I make session_manager global? 

```
std::unordered_map<std::string, Connection> connections;

class Connection
{
public:
    TLS::callbacks tlsCallbacks{};

    Botan::AutoSeeded_RNG rng{};
    Botan::TLS::Session_Manager_In_Memory sessionMgr{rng};
    Botan::TLS::Policy policy{};


    Botan::TLS::Server server{tlsCallbacks, sessionMgr, creds, policy, rng};
};

void HTTPTransport::worker(const evpp::TCPConnPtr &socket, evpp::Buffer *event) {
    std::string request = event->NextAllString();

    // Create a new instance for Connection in case we didn't find a matching one
    Connection currentConnection;
    
    // socket->name() gives IPAdd:Port
    auto existingConnection = connections.find(socket->name());

    // Alias Connection (NEW | OLD) using a Context
    Connection *context = nullptr;

   
    if (existingConnection != connections.end())
    {
        // Set the context to existingConnection
        context = existingConnection->second;
    }
    else
    {
        // Set the context to currentConnection
        contextType = contexts::current;
        context = currentConnection;
    }

    context.server.received_data(reinterpret_cast<const uint8_t *>(request.c_str()), request.size());

    // Send ...
}
```

**Comment by randombit** [comment]
Yes having the session manager being shared at a high a level as possible increases the changes of a hit on the session cache. IIUC you are currently tying the session manager lifetime to that of a connection which means if the client disconnects and then reconnects you have already purged the session manager and so you would need a full handshake even if the client was able to resume.
