### ISSUE TITLE
Botan cli can't find shared library

### ISSUE THREAD

**Issue by bapi23** [randombit/botan#2662]
I've just build recent master branch (68fbeb9893bf6ce7235a4caf5de186c51d2a9ffb) and I think that there is one issue.
Why do I need to specify LD_LIBRARY_PATH with usr/local/lib to be able to run Botan cli?
```
$ botan
botan: error while loading shared libraries: libbotan-3.so.0: cannot open shared object file: No such file or directory
$ whereis libbotan-3.so.0
libbotan-3.so: /usr/local/lib/libbotan-3.so /usr/local/lib/libbotan-3.so.0
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
$ botan
Usage: botan <cmd> <cmd-options>
```

**Comment by randombit** [comment]
I think this is some issue with your local configuration - perhaps `/usr/local/lib` is not listed in `/etc/ld.so.conf`?

**Comment by bapi23** [comment]
I've checked it already. Here is the output from ldconfig -v:
$ ldconfig -v
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: Path /lib/x86_64-linux-gnu given more than once
/sbin/ldconfig.real: Path /usr/lib/x86_64-linux-gnu given more than once
/usr/lib/x86_64-linux-gnu/libfakeroot:
	libfakeroot-0.so -> libfakeroot-tcp.so
/usr/local/lib:
	libprotobuf-lite.so.22 -> libprotobuf-lite.so.22.0.1
	libbotan-3.so.0 -> libbotan-3.so.0.0.0
	libprotoc.so.22 -> libprotoc.so.22.0.1
	libprotobuf.so.22 -> libprotobuf.so.22.0.1

As you can see libbotan-3.so.0 is there.

**Comment by randombit** [comment]
Really not sure what to make of this. Like, I don't even know how to write a program that *could* have this behavior outside of maybe using a custom dynamic linker.

**Comment by bapi23** [comment]
Do you mean that it still looks like my environment? I will try to double-check it again. Thanks!

**Comment by randombit** [comment]
Closing as stale, if you are still having problems please open a new ticket.
