### ISSUE TITLE
TLS server failed to detect no TLS initial input

### ISSUE THREAD

**Issue by fxdupont** [randombit/botan#2668]
I am testing a basic HTTPS server using OpenSSL and Botan with a HTTP client sending a GET instead a TLS handshake record. Results are:
 - with recent OpenSSL I get "http request" error
 - with old OpenSSL I get "wrong version number" error
 - with Botan the server hangs

I looked at the different codes:
 - recent OpenSSL checks in the first record the upper 8 bits of the major version (second byte of the header), if it is not 3 as for all SSL and TLS versions it compares the beginning of the packet with common HTTP commands (GET, POST, etc)
 - old OpenSSL checks in the first record the upper 8 bits of the major version (second byte of the header), if it is not 3 as for all SSL and TLS versions it returns an error (SSL_R_WRONG_VERSION_NUMBER)
 - Botan sees an incomplete record in Channel::received_data (src/lib/tls/tls_channel.cpp) and asks for the remaining content of what it believes to be a record (comment ```// need more data to complete record```). Note that some lines later there is a similar check for the initial record so my concern is that Botan is a little naive.

I propose to either move the return needed down or the blocks with the initial_record definition and checks up.

**Comment by randombit** [comment]
Yeah certainly we can at least check the first record version byte here. I'm not huge on checking for HTTP verbs or anything else that's specific to the application protocol.

**Comment by fxdupont** [comment]
I fully agree: to me the recent OpenSSL behavior is just a (late) attempt to provide a more user friendly error message. What matters is to get an error.

I recommend to check if read_record decodes the whole header and in receive_data to perform all sanity checks using only the header as soon as possible: I can see only advantages to do that...

**Comment by randombit** [comment]
What do you think of #2669 ?

**Comment by randombit** [comment]
It turned out that for testing purposes it was simpler to just do the HTTP detection logic anyway, since an HTTP request is how the BoringSSL suite tests this and it wants to see a special error code when that happens. Without the detection logic I'd have to write a custom test instead of leveraging that one. And probably a more specific error will save someone a bit of debugging time someday.

**Comment by randombit** [comment]
Fixed now on `master` and `release-2` will be included in 2.18 which will be released within the next week or two I think.
