### ISSUE TITLE
How to load RSA public key in PKCS #1, ASN.1 DER form

### ISSUE THREAD

**Issue by adnan-kamili** [randombit/botan#2671]
We have a Golang app that generates an RSA key and sends the public key to the client in PKCS #1, ASN.1 DER form. 

https://golang.org/pkg/crypto/x509/#MarshalPKCS1PublicKey

When I try to load the same public key in the client using Botan 1.10.17:

    try
    {
        Botan::AutoSeeded_RNG rng;
        Botan::DataSource_Memory pubKeyMem(publicKey); // here public key is in PKCS #1, ASN.1 DER form
        Botan::RSA_PublicKey *rsaKey = dynamic_cast<Botan::RSA_PublicKey*>(Botan::X509::load_key(pubKeyMem));
        ...
    }
    catch (std::exception& e)
    {
        cout << e.what();
    }

I get an exception:

Decoding error: X.509 public key decoding failed

Here is the public key generated by the server:

-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA80s5aG/cuYU/xT3WsC5FkJmMdCg1SFFuc+qJT8aB1IgR3mnKGARf
tKpZ3Uk8Ehp1PSgS+tJE+NhE5fjU8S2K9EtGbep4DAK/TmeJ1TQvJXtCcrMH7MFV
Ck57X972MChnR5wJYrCnBYXt4Q9f76AT4PfFHCgN+eePYD175VIUN7rZlqZaqgX4
LAWQQpZsrj1DersOeH6YfMeuXplTljePGlKcutvWtr3LqGSAkPKAngW3gGTNcxXh
s8EW0CxXctvPLuWArlV2afU6XIpqWGVxB3NlRVuU64XvOE+aXyL2LyX2DXCWzzs8
mKjwp4SQW2xiJiQoRy3gmAR8oV8Jgffs2wIDAQAB
-----END RSA PUBLIC KEY-----

**Comment by randombit** [comment]
There is not a convenient API endpoint for this right now. You can use this constructor

`RSA_PublicKey::RSA_PublicKey(const AlgorithmIdentifier& alg_id, const std::vector<uint8_t>& key_bits)`

The algorithm identifier is basically ignored atm but that may change in the future so I'd suggest initializing with

`AlgorithmIdentifier alg_id(OID("RSA"), AlgorithmIdentifier::USE_NULL_PARAM))`

and then `key_bits` is the binary form of what the server is returning to you.

**Comment by adnan-kamili** [comment]
Thanks for the reply. I figured out that if we marshal the public key as MarshalPKIXPublicKey

https://golang.org/pkg/crypto/x509/#MarshalPKIXPublicKey

then it works directly in Botan.
