### ISSUE TITLE
Botan emit multiple Server Hellos 

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2681]
If you search for this Hex string, you can see it multiple times,

```
160303005f0200005b03036063858c650f4bb4c8f353bfb8636463b6940eacb
03de0e2c2fecc7422bbea34206063858c2dc4966785c3827b924810d000d3a3
0749d1c3c53f14fea77ffdc1b2c03000001300050000000b000201000017000
0ff01000100
```

This hex string is Server Hello. You can verify this by appending pseudo IP/Ethernet header so it becomes,

```
0000000000000000000000000800
4528008ce601400036063d6e03200345a29077df
b19d817aa1f2b148131867c3501801f58b240000

160303005f0200005b03036063858c650f4bb4c8f353bfb8636463b6940eacb
03de0e2c2fecc7422bbea34206063858c2dc4966785c3827b924810d000d3a3
0749d1c3c53f14fea77ffdc1b2c03000001300050000000b000201000017000
0ff01000100
```

Now, you can go here [https://hpd.gasmi.net](https://hpd.gasmi.net ) to decode this hex string as a packet and there you will see this as a Server Hello.

These are emitted by Botan received data's callbacks. 

This is a protocol violation as stated by you and I'm willing to bet there is serious bug in this library and you may have missed it because of ASIO. 

Parent Issue:   https://github.com/randombit/botan/issues/2666

FYI, You can apply this  pseudo IP/Ethernet header to rest HEX strings as-well to see what kind of TLS message is it

**Comment by randombit** [comment]
I don't see how asio could hide this bug nor have I ever seen this happen in the plain socket based code such as in the `tls_server` api or the BoringSSL test shim. I really don't see how this could happen and without a reproducible example I don't see a path for diagnosing.

**Comment by jeffRTC** [comment]
@randombit 

All your tests use one certificate and one private key. My application is different. It uses a self signed root CA and generates certificates for every website.

As for Asio, it uses Botan TLS stream, right?

This doesn't just emit duplicate Server Hellos, it also emit duplicate certificates.

I will try to create a reproducible example.

**Comment by jeffRTC** [comment]
@randombit 

Dang it.

```
auto encodedMessages = context.tlsCallbacks.encodedMessages;
// Do work
encodedMessages .clear();
```

I was making a copy and deleting Items on that copied vector so the context vector was not cleaned therefore resulting duplicate messages.....

Wow, it took a lot of months!!!!!!!
