### ISSUE TITLE
Does TLS::Channel::send supports zero length string? 

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2699]
I'm trying to implement HTTP Transfer encoding  and it requires a zero-length byte to indicate end of stream. 

I want to hear from you whether `Botan::TLS::Channel::send` supports this or not. If not, how it should be done.

`Botan::TLS::Channel::send('');
`

**Comment by randombit** [comment]
No - on sending we ignore a request to send no data. And I thought also the application data callback was suppressed when receiving an empty record but I can't find that now.

Can you link to the spec you are working from? I'm not familiar with this but based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding I would have thought termination was done by

```
0\r\n
\r\n
```

ie sending first 0 byte length field followed by \r\n, followed by a zero length field followed again by \r\n

**Comment by jeffRTC** [comment]
@randombit It's the same spec you linked. I was thinking \r\n as empty. So, Botan supports sending standalone "\r\n"?

**Comment by randombit** [comment]
Sure yes - from the perspective of TLS that's not empty at all, it's 2 bytes \r\n. The only thing we won't send is a completely empty record.

**Comment by jeffRTC** [comment]
Got it. Thanks!
