### ISSUE TITLE
configure.py incorrectly detects some linker flags as library names

### ISSUE THREAD

**Issue by thubble** [randombit/botan#2715]
The change in https://github.com/randombit/botan/pull/2623 seems to have an issue where it detects any linker flag containing `-l` as a library, even if it's in the middle of a string. This causes issues if certain linker flags contain this string.

E.g.: I have `-fdevirtualize-at-ltrans` and `-fuse-linker-plugin` in my flags, so I get `-ltrans -linker` appended to my linker flags, which obviously causes compile errors.

I'm using Gentoo which appends all CFLAGS to LDFLAGS, probably for supporting LTO and such, so this may not be a typical setup. However, it's valid to have some of these flags in LDFLAGS, particularly `-fuse-linker-plugin`.

The problem seems to be with the Regex match: `-l([a-z0-9]+)`. I believe changing it to require either whitespace, or the beginning of the string, at the start should fix the issue. Both my Regex and Python are a bit rusty though.

**Comment by randombit** [comment]
Thank you for reporting this, looking at a fix now

**Comment by thubble** [comment]
I applied the patch from https://github.com/randombit/botan/pull/2718 and the build now works!

**Comment by randombit** [comment]
Closing as this is now fixed in both master and release-2 branches. This will be fixed in upcoming  2.18.1 release but there isn't an immediate ETA of when that will happen. Thanks again for reporting, and also for checking the patch.
