### ISSUE TITLE
argon2_generate_pwhash with not rng salt

### ISSUE THREAD

**Issue by Antidote1911** [randombit/botan#2729]
Hello all.
In my [Argon2-Calculator](https://github.com/Antidote1911/Argon2_Calculator) i need to use personal salt. Not rng.
For now, i use:
```bash
auto default_pwhash{pwdhash_fam->from_params(memory, iteration, parallelism)};
default_pwhash->derive_key(key_buffer.data(),
                               key_buffer.size(),
                               pass_buffer.data(),
                               pass_buffer.size(),
                               salt_buffer.data(),
                               salt_buffer.size());
```
and i must manualy construct the Encoded hash string like $argon2i$v=19$m=65536,t=2,p=4$c29tZXNhbHQ$RdescudvJCsgt3ub+b+dWRWJTmaaJObG
I use the same code (copy/paste) used by Jack in  argon2_generate_pwhash to do that :)

It is possible to use argon2_generate_pwhash with no rng to eliminate the string construction ? 

Thanks !

**Comment by randombit** [comment]
I'd hestitate to include direct support for this as it's an easy foot gun. There is however an easy workaround, which works with current versions - pass an RNG which outputs exactly the bytes you want. You can probably adapt https://github.com/randombit/botan/blob/master/src/tests/test_rng.h#L24 for this.

**Comment by Antidote1911** [comment]
A litle modified Fixed_Output_RNG class work. But instead of reimplement the class, i will keep the manual formating for staying light.
```code
oss << "v=19$m=" << memory << ",t=" << iteration << ",p=" << parallelism << "$";
oss << strip_padding(base64_encode(salt_buffer)) << "$" << m_b69Hash;
```
Thank you for the workaround !
