### ISSUE TITLE
DNS name matching for name constraints is case-sensitive

### ISSUE THREAD

**Issue by robertsuska** [randombit/botan#2735]
Hi,

I've noticed that when Botan checks name constraints during validation of X509 certificates, it performs a case-sensitive matching on DNS names. I think this is a bug, since [RFC 5280](https://www.rfc-editor.org/rfc/rfc5280.txt) (article 7.2) says _"When evaluating name constraints, conforming implementations MUST perform a case-insensitive exact match on a label-by-label basis."_.

I've included a [test_example_chain.zip](https://github.com/randombit/botan/files/6416038/test_example_chain.zip) which highlights precisely this behavior, such that:

_test_root_ca.pem_ specifies a single name constraint:

```
X509v3 Name Constraints: critical
    Permitted:
      DNS:example.com
```

_test_server_ok.pem_ has an alternative name:

```
X509v3 Subject Alternative Name:
    DNS:test.example.com
```

_test_server_error.pem_ has an alternative name:

```
X509v3 Subject Alternative Name:
    DNS:test.EXAMPLE.COM
```

and validation of chain _test_root_ca.pem_ -> _test_server_ok.pem_ returns code 0 (VERIFIED)
while validation of chain _test_root_ca.pem_ -> _test_server_error.pem_ returns code 4004 (NAME_CONSTRAINT_ERROR)

I've also included a [real_world_example_chain.zip](https://github.com/randombit/botan/files/6416144/real_world_example_chain.zip) for reference, where the problem is that _real_world_intermediate_ca.pem_ specifies a name constraint (in a permitted subtree) for `DNS:gov.it`, while _real_world_server.pem_ has an alternative name which contains `DNS:INDICEPA-COLLAUDO.GOV.IT`.

---

I am using Botan in version 2.17.2 through its Python binding.

The (test) example chain above was validated as follows:

```
import botan2 as botan

server = botan.X509Cert(filename="test_server_ok.pem")
print(server.verify(trusted_path="trust_store/", reference_time=1620061260))
```

**Comment by randombit** [comment]
Thanks for reporting as well as the test case, looks like we just do `==` for comparing DNS
