### ISSUE TITLE
Using create_or_throw without allocations

### ISSUE THREAD

**Issue by Chaosvex** [randombit/botan#2741]
Since marking the algorithm-specific headers (e.g. sha160.h) as for internal use only, I haven't been able to find a clean way of using Botan's hashing algorithms without dynamic allocations that doesn't involve moving what ought to be compile-time checks to runtime.

Take the following code:
```cpp
auto hasher = Botan::HashFunction::create_or_throw("SHA-1");
BOOST_ASSERT_MSG(SHA1_LEN == hasher->output_length(), "Bad hash length");
std::array<std::uint8_t, SHA1_LEN> hash_out;
hasher->final(hash_out.data());
```

Ideally, I'd be able to size the output buffers using constants from Botan (e.g. `std::array<..., Botan::SHA_160::output_length()>`) and remove the asserts rather than having to maintain & carry around my own header with crypto-related constants and doing runtime checks each time I want to use the hashing algorithms.

This isn't a problem when including the algorithm headers directly but with Botan now expecting users to rely on this runtime interface, is there a better solution here that I'm missing? It's not a huge problem either way but it'd one less source of potential mistakes to not have to rely on runtime checks and defines that aren't part of Botan.

Thanks!

**Comment by randombit** [comment]
What you're asking for makes sense and is reasonable but unfortunately doesn't seem to be possible when balanced against a desire to minimize the API/ABI surface, which is the factor driving this change.

**Comment by Chaosvex** [comment]
I can't see any obvious way of doing this with the current direction either but I was hoping that I'd missed something. Thanks nonetheless.
