### ISSUE TITLE
HOTP generates incorrect code

### ISSUE THREAD

**Issue by binex-dsk** [randombit/botan#2745]
Using this as an example:
```cpp
#include <botan-2/botan/otp.h>
#include <iostream>

int main() {
    std::string key = "ORUGK==="
    std::cout << Botan::HOTP(Botan::secure_vector<uint8_t>(key.begin(), key.end()), "SHA-1", 6, 30).generate_hotp(54045442) << std::endl;
}
```

This outputs `78159` (why is it 5 digits?), while an equivalent from `oathtool` outputs `376083`.

**Comment by randombit** [comment]
You are using the base32-encoded key directly as the HOTP key - use `base32_decode` to decode it first.

Output of HOTP is just an integer < 10**n, `generate_hotp` just returns that integer. You then in typical usage have to format it as a 0-padded string. [There should probably be a helper in the library for doing that, but there is not at the moment]

Example of zero padding behavior

```
$ oathtool -b -d 6 -c 100 ORUGK===
025328
```

**Comment by binex-dsk** [comment]
oh, I see.  Feel like that should be clarified in the docs (and the code comments), since every library I've used takes the base32 (or hex) directly. And yeah, zero padding would be nice--but you might have to change the return type to an std::string iinm.
