### ISSUE TITLE
MSYS2 RNG Undefiend Reference to 'GOMP_parallel'

### ISSUE THREAD

**Issue by Ellie-42** [randombit/botan#2746]
System info:
Win 10 Pro x86_64
Mingw-w64 from MSYS2
Botan form MSYS2

Test code:

```
#include <iostream>
#include <botan/auto_rng.h>
#include <memory>

int main()
{
    std::unique_ptr<Botan::RandomNumberGenerator> rng;
    rng.reset(new Botan::AutoSeeded_RNG);
    return 0;
}
```

Compile instruction: 
`g++.exe -Wall -g -fopenmp -IC:\msys64\mingw64\include\botan-2 -IC:\msys64\mingw64\include -c P:\QCO\BotanTest\main.cpp -o obj\Debug\main.o`
`g++.exe -LC:\msys64\mingw64\lib -o bin\Debug\BotanTest.exe obj\Debug\main.o  -lbotan-2`

Many errors of the same style:

```
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\mingw64\lib/libbotan-2.a(block_camellia.o):(.text+0x362): undefined reference to `GOMP_parallel'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\mingw64\lib/libbotan-2.a(block_camellia.o):(.text+0x3d2): more undefined references to `GOMP_parallel' follow
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\mingw64\lib/libbotan-2.a(block_camellia.o):(.text+0x411): undefined reference to `omp_get_num_threads'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\mingw64\lib/libbotan-2.a(block_camellia.o):(.text+0x418): undefined reference to `omp_get_thread_num'
...
collect2.exe: error: ld returned 1 exit status
```

None of the RNG works

**Comment by randombit** [comment]
I think you must also link using `-fopenmp`?

But, do not bother with the OpenMP support. It is available in the build but outside of one macro it is not really used, also unclear if it provides any actual real-world speedup. It should probably be removed altogether.

**Comment by Ellie-42** [comment]
> I think you must also link using `-fopenmp`?

I am using `-fopenmp`
My OpenMP is also up to date, and I tried linking the library directly as well, but none of that worked. I'm not trying to use OpenMP at all. Its just what the MYS2 package already had built. Sounds like I need to build the library myself then to circumvent the issue?

**Comment by randombit** [comment]
> I am using -fopenmp

Not during the link:

g++.exe -LC:\msys64\mingw64\lib -o bin\Debug\BotanTest.exe obj\Debug\main.o -lbotan-2

> Its just what the MYS2 package already had built.

Yikes. It should not be doing that. That adds a lot of weirdness onto everyone trying to use the package.

**Comment by Ellie-42** [comment]
> Not during the link

Ugh, had to put it in the "Other linker options" which is really dumb way CodeBlocks does things. Thank you for pointing that out.

But hopefully this helps the removal of the usage altogether 😄 
The MSYS2 version is missing a few RNG files too, so I'll look into that.
