### ISSUE TITLE
Session resumption tied with SNI

### ISSUE THREAD

**Issue by GeryEmreis** [randombit/botan#2757]
Hi, is there any reason in TLS/DTLS standard, that client side session resumption (session tickets) is tied with SNI? Or is it just implementation detail? 
Session is not saved when `Botan::TLS::Server_Information` is not filled while creating `Botan::TLS::Client,` but filling it enables SNI. Therefore I see no way to enable session tickets while disabling SNI.

**Comment by randombit** [comment]
There is nothing in the specification that requires SNI for resumption. However without knowing the intended destination hostname we have no real way of looking up the session in the cache. But we do not necessarily need to send SNI; there is no reason we couldn't accept a hostname, use it looking up the session info in the cache, but not send SNI. It would just need some additional toggle in the `Callbacks` eg `bool tls_should_send_sni(const std::string& server_hostname)`

However I'd like to understand a bit more about why SNI is a problem here. Is there some server which is SNI intolerant??

**Comment by GeryEmreis** [comment]
Thanks for reply. We are using DTLS and have control of both server and clients (both using Botan). I just wanted to disable SNI to save few bytes in handshake and simplify things, because we won't be using virtual hosts.

**Comment by randombit** [comment]
You can remove the SNI extension by implementing `tls_modify_extensions` then using `Extensions::remove_extension(TLSEXT_SERVER_NAME_INDICATION)`

**Comment by randombit** [comment]
Closing this since there is a way of disabling SNI already
