### ISSUE TITLE
Question: rsa slow ?

### ISSUE THREAD

**Issue by pfeatherstone** [randombit/botan#2758]
RSA seems to be really slow when encrypting. Is there an equally secure asymmetric crypto that is faster ?

Thanks

**Comment by randombit** [comment]
Can you clarify what you mean by really slow? What compiler and platform? Are you sure you did not build without optimizations?

On a ten year old laptop, RSA with 2048 bit keys seems to take about 60 microseconds to encrypt, which seems ok? OpenSSL reports about the same.

**Comment by pfeatherstone** [comment]
I would need to run some benchmarks tomorrow to quantitatively describe slow. But reading more about RSA, it seems it is genuinely slow compared to AES. Some people use hybrid systems where RSA is used to securely encrypt a random AES key, and use that to encrypt messages

**Comment by pfeatherstone** [comment]
Is that 60us per 190 bytes ?

**Comment by pfeatherstone** [comment]
Then that would be about what I'm seeing.

**Comment by pfeatherstone** [comment]
Maybe a bit less than 60us. That seemed really slow at the time

**Comment by randombit** [comment]
Oh yes if you are encrypting more than just a symmetric key with RSA that is a bad move. For one RSA is orders of magnitude slower than a symmetric scheme like AES. Plus you have to worry about things like an attacker reordering your messages, or inserting new ones, or replaying previously seen ciphertexts.

**Comment by pfeatherstone** [comment]
OK cheers. I will use RSA + AES.
