### ISSUE TITLE
The master-cpp14 branch does not compile with enabled tls, asio, stream, boost modules.

### ISSUE THREAD

**Issue by paba-eb** [randombit/botan#2759]
The master-cpp14 branch does not compile with enabled tls, asio, stream, boost modules.
I have used following configuration: ./configure.py --enable-modules=tls,asio,stream,boost
This is the top of a master-cpp14 branch which I'm trying to compile:

commit 769e036c3582b9ea649f56e1d032c05ef645524f (HEAD -> master-cpp14, origin/master-cpp14)
Author: Jack Lloyd <jack@randombit.net>
Date:   Wed Jun 9 07:07:29 2021 -0400

Getting following errors compiling with gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0:

`In file included from src/tests/unit_asio_stream.cpp:13:
build/include/botan/asio_stream.h: At global scope:
build/include/botan/asio_stream.h:801:12: error: ‘void Botan::TLS::Stream<S, C>::try_with_error_code(Fun, boost::system::error_code&) [with Fun = Botan::TLS::Stream<S, C>::setup_native_handle(Botan::TLS::Connection_Side, boost::system::error_code&) [with StreamLayer = Botan_Tests::TestStream; ChannelT = Botan_Tests::MockChannel]::<lambda()>; StreamLayer = Botan_Tests::TestStream; ChannelT = Botan_Tests::MockChannel]’, declared using local type ‘Botan::TLS::Stream<S, C>::setup_native_handle(Botan::TLS::Connection_Side, boost::system::error_code&) [with StreamLayer = Botan_Tests::TestStream; ChannelT = Botan_Tests::MockChannel]::<lambda()>’, is used but never defined [-fpermissive]`

`In file included from src/tests/unit_asio_stream.cpp:13:
build/include/botan/asio_stream.h:723:35: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<Botan_Tests::ThrowingMockChannel, std::default_delete<Botan_Tests::ThrowingMockChannel> >’ and ‘std::unique_ptr<Botan::TLS::Server>’)`

`src/tests/unit_asio_stream.cpp:209:46:   required from here
build/include/botan/asio_stream.h:712:35: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<Botan_Tests::ThrowingMockChannel, std::default_delete<Botan_Tests::ThrowingMockChannel> >’ and ‘std::unique_ptr<Botan::TLS::Client>’)`

**Comment by randombit** [comment]
I think we need to revert the asio code to match with release-2 for the C++14 branch

**Comment by randombit** [comment]
The C++14 branch is no longer supported.
