### ISSUE TITLE
Question : how to generate an RSA public key?

### ISSUE THREAD

**Issue by pfeatherstone** [randombit/botan#2767]
Using code, i can generate an RSA private - public key pair using:
```
    Botan::AutoSeeded_RNG rng;
    Botan::RSA_PrivateKey keygen(rng, 4096);
    
   auto private_key = Botan::PKCS8::PEM_encode(keygen, rng, "hello there!");
   auto public_key  = Botan::X509::PEM_encode(keygen);
```

Using the command line tool, I can generate an RSA private key using:
```
botan keygen --algo=RSA --params=4096
```
But how do I generate the public key?

Using the command line tool, i can only generate certificates...

I might be blind and not read the docs right, but if so, can someone point me in the right direction?

**Comment by randombit** [comment]
Using the command line you mean? It's a bit obscure and may not be documented at all - `botan pkcs8 --pub-out filename`

**Comment by pfeatherstone** [comment]
OK, yes it was documented [here](https://botan.randombit.net/handbook/cli.html#public-key-cryptography), but it wasn't clear to me at least that --pub-out meant that it output the corresponding public key. 
Thank you
