### ISSUE TITLE
Kyber algorithm implementation - Post Quantum Crypto

### ISSUE THREAD

**Issue by omarama** [randombit/botan#2778]
Hello,

currently we implement the CRYSTALS-KYBER algorithm from NIST Submission Package Round III in Botan and would be happy to contribute this.
 - https://csrc.nist.gov/projects/post-quantum-cryptography/round-3-submissions
 - https://pq-crystals.org/kyber/resources.shtml 
Right now we are looking at the mathematic implemetation of the package: 

https://csrc.nist.gov/CSRC/media/Projects/post-quantum-cryptography/documents/round-3/submissions/Kyber-Round3.zip
Especially file: Kyber-Round3\NIST-PQ-Submission-Kyber-20201001\Reference_Implementation\crypto_kem\kyber512\indcpa.c - Functions: indcpa_enc, indcpa_dec and indcpa_keypair. 

We noticed that the mathemtic funtions currently are not available in the math part of botan.

Should we solve the problem like the newHope implementation and put the c style functions into the kyber classes 
or should we implement these functions in the botan math part?  

Thanks for your help

**Comment by randombit** [comment]
> currently we implement the CRYSTALS-KYBER algorithm from NIST Submission Package Round III in Botan and would be happy to contribute this.

Looking forward to it!

> Should we solve the problem like the newHope implementation and put the c style functions into the kyber classes
or should we implement these functions in the botan math part?

Until there is a clear common functionality that we can extract and use (eg between Kyber and Dilithium), leave any lattice mathematical logic within the kyber submodule.

**Comment by mouse07410** [comment]
At the risk of duplicating functionality, I suggest keeping all the lattice operations within the corresponding module - Kyber, Dilithium, etc.
