### ISSUE TITLE
Zeroise Memory without std::memset

### ISSUE THREAD

**Issue by steffenbuhle** [randombit/botan#2786]
Botan provides the method `secure_scrub_memory` for reliable zero-ing memory independently of the compiler or operating system. The method works fine is the go-to-solution for the deletion of our own secure data structures.

In the quality assurance step of our code we can detect "un-zeroed" content und we realized that botan itself is keeping memory which actually should be overwritten by zero. It turns out that botan uses the methods `zeroise`, `clear_mem` and `clear_bytes` quite often which eventually leads to a simple `std::memset` with zero. Even the comment for  `clear_bytes` is suggesting that `secure_scrub_memory` should be preferred since `std::memset` could be ignored by the compiler. I can confirm that this _is_ the case for my MSVC 2019 compiler.

Why are `zeroise`, `clear_mem` and `clear_bytes` not just be replaced by `secure_scrub_memory`? IMHO that's the only method that provides the expected behavior and any other solution leads to a security issue.

**Comment by steffenbuhle** [comment]
The hint with the stack-allocation may be the key to our issue, thank you very much! I'll check if that may apply to our code.

**Comment by steffenbuhle** [comment]
Well, after a lot of experimenting with with our test environment I am pretty sure it's our fault. The un-zeroed content derived from a needless log-message, not from the underlying botan library. I am sorry for wasting your time - the ticket is closed.
Thanks for your help!

**Comment by randombit** [comment]
No problem! I appreciate the time spent on validating behavior such as this. Glad it turned out not to be an issue of course, but please do report anything else that seems odd.
