### ISSUE TITLE
Coveralls integration broken

### ISSUE THREAD

**Issue by randombit** [randombit/botan#280]
Travis coverage jobs like `https://travis-ci.org/randombit/botan/jobs/80047917` seem to complete and upload the results ok, but the result on coveralls is obviously incomplete/corrupt: `https://coveralls.io/jobs/8258709`

It looks like things broke around Aug 21, though the commits around that time don't seem to be touching the build at all.

**Comment by webmaster128** [comment]
I reviewed the configuration and did not find anything strange.

I just contacted the coveralls support because of this.

**Comment by webmaster128** [comment]
Successfully integrated codecov.io, which is able to parse gcov data.
