### ISSUE TITLE
Is there thread-unsafe list?

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2813]
To be specific, I'm asking you if there are more thread unsafe stuff like the RNG one.

I am having troubles using Botan with Seastar. Seastar has their own threads.

**Comment by jeffRTC** [comment]
cc @randombit

**Comment by lieser** [comment]
The default for objects in Botan is that no thread safety is guaranteed. So unless an API explicitly states that concurrent access is thread safe you have to unsure yourself that no concurrent access happens.

**Comment by lieser** [comment]
As you haven't replied yet I'm assuming your questions are answered. If not please reopen the issue.
