### ISSUE TITLE
How to write TLS code with client certificate?

### ISSUE THREAD

**Issue by ryutei** [randombit/botan#282]
I'm writing socket base TLS client code. This requires client certificate authentication.

I understand that botan needs override Botan::Credentials_Manager::cert_chain and private_key_for, but in my test (with apache+mod_ssl), this methods never called because client dose not receive CertificateRequest on TLS protocol. This is because client certificate authentication generally needs renegotiation after first handshake and server sends HelloRequest to inform renegotiation. In this case, it seems botan dose not react to HelloRequest from server.
1. If I need handle renegotiation manually, please show me how to it; is there something callback which react to HelloRequest?
2. Otherwise tell me correct way to implement client certificate code.

**Comment by randombit** [comment]
The default TLS policy has `allow_server_initiated_renegotiation` as false, so the client may be ignoring the request. In that case the client should be sending a no renegotiation warning alert to indicate it was rejecting the request, but this might be logged by apache.

**Comment by ryutei** [comment]
Thank you for your comment.
I tested `allow_server_initiated_renegotiation` as true, there are something wrong yet. 
I confirmed that client send ClientHello to server, server debug log says sever receives EOF in handshake and shutdown connection. (is this server side problem?)

I will look into this a little more.

**Comment by ryutei** [comment]
I found a solution on server side setting. But I cannot judge this is correct and essential one or not, so I report the situation...

In my case, my original apache setting request client-certificate in Directory context, basically same as httpd.conf sample(http://httpd.apache.org/docs/2.0/ssl/ssl_howto.html). That is:
>&lt;Directory /path/to/protect&gt;
>SSLVerifyClient require
>...
>&lt;/Directory&gt;

Server log is here (Apache 2.4.16/OpenSSL 0.9.8zg/OS X 10.10):
>[Sat Sep 19 13:05:16.527227 2015] [ssl:info] [pid 7107] [client fe80::baf6:b1ff:fe19:1fd1:51264] AH01964: Connection to child 0 established (server PC-70.local:443)
>[Sat Sep 19 13:05:16.556759 2015] [ssl:debug] [pid 7107] ssl_engine_kernel.c(1919): [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02043: SSL virtual host for servername pc-70.local found
>[Sat Sep 19 13:05:16.603444 2015] [ssl:debug] [pid 7107] ssl_engine_kernel.c(1849): [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02041: Protocol: TLSv1, Cipher: DHE-RSA-AES256-SHA (256/256 bits)
>[Sat Sep 19 13:05:16.611032 2015] [ssl:debug] [pid 7107] ssl_engine_kernel.c(237): [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02034: Initial (No.1) HTTPS request received for child 0 (server PC-70.local:443)
>[Sat Sep 19 13:05:16.612452 2015] [ssl:debug] [pid 7107] ssl_engine_kernel.c(599): [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02255: Changed client verification type will force renegotiation
>[Sat Sep 19 13:05:16.612479 2015] [ssl:info] [pid 7107] [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02221: Requesting connection re-negotiation
>[Sat Sep 19 13:05:16.612531 2015] [ssl:debug] [pid 7107] ssl_engine_kernel.c(799): [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02260: Performing full renegotiation: complete handshake protocol (client does support secure renegotiation)
>[Sat Sep 19 13:05:16.612608 2015] [ssl:info] [pid 7107] [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02226: Awaiting re-negotiation handshake
>[Sat Sep 19 13:05:16.613250 2015] [ssl:debug] [pid 7107] ssl_engine_kernel.c(1919): [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02043: SSL virtual host for servername pc-70.local found
>[Sat Sep 19 13:05:16.615392 2015] [ssl:error] [pid 7107] [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02261: Re-negotiation handshake failed
>**[Sat Sep 19 13:05:16.616846 2015] [ssl:debug] [pid 7107] ssl_engine_io.c(1210): (70014)End of file found: [client fe80::baf6:b1ff:fe19:1fd1:51264] AH02007: SSL handshake interrupted by system [Hint: Stop button pressed in browser?!]**
>[Sat Sep 19 13:05:16.616867 2015] [ssl:info] [pid 7107] [client fe80::baf6:b1ff:fe19:1fd1:51264] AH01998: Connection closed to child 0 with abortive shutdown (server PC-70.local:443)`

I know botan client tried to send ClientHello to server, but it seems server cannot receive it.
To avoid the problem I moved client-certificate settings to VirtualHost. In this case, https request was success because server don't send re-negotiation handshake. But it is mysterious why browsers can connect the server but Botan client cannot.

If you know some information about it, please teach me.
Thank you.

**Comment by randombit** [comment]
I wish the reason `Re-negotiation handshake failed` mentioned in the log before your bolded line was more clear. Is this due to a timeout, an alert, or some renegotiation failure. Can you trace a connection with `tcpdump` (or just add logging to the I/O TLS callbacks in your client application) so we can see what messages are exchanged when the hello request is received?

**Comment by ryutei** [comment]
I'm sorry that I cannot response your request. I have lost my error reproducible environment but I encounter it again. See my tcpdump.
One supplement: If the client certificate is required by Apache in VirtualHost context, my code works fine. But in Directory context, same code becomes fail. I don't understand why these settings make such difference. 
[tls_dir_fail.dump.zip](https://github.com/randombit/botan/files/75565/tls_dir_fail.dump.zip)

**Comment by ryutei** [comment]
Sorry, I have upload wrong dump file. This is correct one.
[tls_dir_fail.dump.zip](https://github.com/randombit/botan/files/84144/tls_dir_fail.dump.zip)

**Comment by randombit** [comment]
Closing this because it's old, the TLS stack has changed dramatically since early 2016, and I still have no idea what the problem might be.
