### ISSUE TITLE
Add support for Ed25519

### ISSUE THREAD

**Issue by Jesse-V** [randombit/botan#283]
Ed25519 is very strong, extremely fast, and very safe ECC curve designed for digital signatures. It's generally recommended by most cryptographers over NIST and secp256k1 curves and is not encumbered by patents. Botan should include an implementation of Ed25519 to allow users to make strong digital signatures.

http://ed25519.cr.yp.to/
http://safecurves.cr.yp.to/
https://en.wikipedia.org/wiki/EdDSA

Ed25519 is used by a number of applications, including the Tor anonymity network. They adapt their implementation from https://github.com/floodyberry/ed25519-donna, which I have also used in my own projects. Would Botan accept a patch of this implementation wrapped in a standard Botan class?

**Comment by webmaster128** [comment]
Is that the same thing as [curve25519_donna](https://github.com/randombit/botan/tree/master/src/lib/pubkey/curve25519)?

**Comment by Jesse-V** [comment]
@webmaster128 no, Curve25519 is for ECDHE key exchange. Ed25519 is for digital signatures, they are mathematically similar but they are used for different purpose.

**Comment by randombit** [comment]
Ed25519 would be an excellent addition and floodyberry's impl is the best available implementation I know of to use as a base. I'd prefer removing most of the assembly versions, if possible - they may be faster but the maintenance costs it can impose on us is not worth it. The SSE2 version seems to be the fastest, anyway.

Ed25519's Schnorr-like signature requires H(R,A,M) with M the message. This doesn't map well to standard usage so to create the signing and verification objects you'll need to derive directly from PK_Ops::{Signature,Verification}, which will let you control the entire process.

The code for exposing a new key type is pretty simple, the impl of the curve25519 key types should provide a good outline.

**Comment by Jesse-V** [comment]
Thanks @randombit! So you would accept pull requests if someone contributed Ed25519 in this way?

**Comment by randombit** [comment]
@Jesse-V Yes I would accept a pull for an Ed25519 based on floodyberry's portable impl.

A typedef for`uint128_t`is set by `mul128.h`if available, otherwise `donna128` provides a minimal 128 bit integer sufficient for curve25519-donna and poly1305-donna, it may also be sufficient for ed25519

**Comment by webmaster128** [comment]
First of all: welcome @Jesse-V Great to hear that you are eager to contribute.

Are you planing to use Botan and Ed25519 in production software? I am just curious about your motivation. Feel free to ignore the question or reply in private (Kullo: simon#kullo.net).

In addition to Jack's help, I'd like to point out that new code should have an excellent test coverage. Every public interface should be tested with special care for edge cases like empty length or other extreme inputs. So it is advisable to start developing in a test driven manner. New test code should be written using the matcher syntax of the Catch unittesting framework. This produces the most readable test code the the style of (pseudo code):

```
CHECK_THAT(actual value, MATCHES(expected value))
```

Even though the matcher system of Catch is not very mature yet, it has a great and highly extensible base. I was able to quickly write additional matchers and one of them (the Not() matcher) has already been accepted in Catch upstream. You can find a lot of Catch test code in `src/tests/catchy/`. I think test_base64.cpp is one of the most beautiful examples and test_x509.cpp covers a lot of different stuff like boolean matchers, multiple matchers and sections. Please feel free to contact me if you have any questions related to that or need another matcher.

**Comment by Jesse-V** [comment]
Yes, I'm currently developing some supplementary software for the Tor network with full intentions of deploying the project once it is ready. I don't trust OpenSSL's codebase (the API is horrendous and the code is a general mess according to many sources) and I needed to find a maintained crypto library with a friendly API. One of the Tor developers suggested Botan, and after some research I agreed, so here I am. Ed25519 is gaining more and more ground as the ECC DSA of choice and I decided that it could fit one of my needs. I had to use floodberry's repo separately since it isn't in Botan, but then I had the idea to see if it could be merged with Botan in the first place.

I will keep your suggestions in mind. I don't know when I'll get around to doing this, but I've forked the repo and that's a good start, right? :)

**Comment by webmaster128** [comment]
I think all questions are answered here. If you come across problems, please open specific issues for that. Looking forward to your pull request.

**Comment by estan** [comment]
@randombit The readme.rst currently lists "Ed25519" under supported signature schemes. Does this mean support for this was added? I couldn't find anything about it in the user manual, can I use the PK_Verfier to do Ed25519 signature verification on an Ed25519 signature that was made with e.g. OpenSSL? Or must I work at a lower (undocumented) level?

**Comment by estan** [comment]
@randombit Bah nevermind, I'm blind. The user manual clearly lists Ed25519 as supported scheme in the docs for PK_Verifier.

**Comment by randombit** [comment]
@estan Yes Ed25519 works just like any other signature scheme. It was added in 2.2.0
