### ISSUE TITLE
os_utils: Test failure

### ISSUE THREAD

**Issue by kekePower** [randombit/botan#2830]
When trying to build on Mageia Cauldron x86_64.

```
os_utils:
OS::get_cpu_cycle_counter ran 1 tests all ok
OS::get_cpu_total/OS::get_cpu_available ran 1 tests 1 FAILED
Failure 1: OS::get_cpu_total/OS::get_cpu_available get_cpu_available not greater than total unexpected result 24 > 1
```

Build log can be found here: https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20211026173056.kekepower.duvel.14005/log/botan2-2.18.2-1.mga9/build.x86_64.0.20211026173205.log

**Comment by randombit** [comment]
This was resolved by #2837
