### ISSUE TITLE
Recovery phrase (bip-0039) based private key recovery, how?

### ISSUE THREAD

**Issue by DisableAsync** [randombit/botan#2855]
I did simple searches on the [bitcoin](https://github.com/bitcoin/bitcoin) repo. Only found some public key recovery related code, not for private key.
So how does recovery phrase private key recovery actually work, can we do it in botan?

**Comment by randombit** [comment]
Seems pretty easy you just need SHA-256 for the checksum and PBKDF2 with SHA-512 for the derivation. Plus a wordlist.

**Comment by DisableAsync** [comment]
> Seems pretty easy you just need SHA-256 for the checksum and PBKDF2 with SHA-512 for the derivation. Plus a wordlist.

Bitcoin's [wordlists](https://github.com/bitcoin/bips/tree/master/bip-0039)

But SHA-256 and PBKDF2 with SHA-512? Am I getting something wrong?

**Comment by randombit** [comment]
> But SHA-256 and PBKDF2 with SHA-512? Am I getting something wrong?

From BIP39 https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

> A checksum is generated by taking the first `ENT / 32` bits of its SHA256 hash.
> To create a binary seed from the mnemonic, we use the PBKDF2 function with a mnemonic sentence (in UTF-8 NFKD) used as the password and the string "mnemonic" + passphrase (again in UTF-8 NFKD) used as the salt. The iteration count is set to 2048 and HMAC-SHA512 is used as the pseudo-random function.

Why they used both, who knows.

> I looked into botan's code, it just generate a random BigInt!

Right. You would have to generate the key using BIP39 then load it as if it was externally generated.

**Comment by DisableAsync** [comment]
> From BIP39 https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
 
> You would have to generate the key using BIP39 then load it as if it was externally generated.

That looked surprisingly simple! I don't fully understand (lack of math knowledge), but I will try to read their implementations later.

Thanks for the help, I really appreciate it. <3
