### ISSUE TITLE
Support for Triple DES with CBC(Init Vector)

### ISSUE THREAD

**Issue by ra185148** [randombit/botan#2857]
Can you please share if any documentation is available for Botan with 3DES in CBC mode using Init Vector?

**Comment by randombit** [comment]
There is an example in the documentation of using AES-128 in CBC mode. Literally the only differences would be using the string "3DES/CBC/PKCS7" instead of "AES-128/CBC/PKCS7" and using the correct (168 bit) key size for 3DES.

**Comment by ra185148** [comment]
Hi,

Thank you for replying.
We have tested the sample code as provided in https://botan.randombit.net/handbook/api_ref/cipher_modes.html

With "AES-128/CBC/PKCS7" or "3DES/CBC/PKCS7", we are experiencing a bad_alloc issue.
"Unhandled exception at 0x76F1B5B2 in ABCD.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x00AFF53C."

We are using VS2017 with WinVer 10.0.17763.0

For Botan Version, 
#define BOTAN_VERSION_MAJOR 2
#define BOTAN_VERSION_MINOR 16
#define BOTAN_VERSION_PATCH 0
#define BOTAN_VERSION_DATESTAMP 20201006

Thank you

**Comment by reneme** [comment]
Thats curious. I can confirm that the example code works as expected for `3DES/CBC/PKCS7` on Botan 2.16.0. I tried it on macOS, but this shouldn't make a difference.

Could you run your code with a debugger attached to get a stack trace?

Maybe you accidentally linked against an binary-incompatible library build of Botan?

**Comment by ra185148** [comment]
Hi,

Thank you for the support, we were using in debug mode. Now it is working fine with "3DES/CBC/PKCS7".
Can you please help us with last question, for ECB mode can we use 3DES/ECB/PKCS7? 
We have tried this but Create is a success, but setKey is failed with an access violation.

Thanks,
Rohit Arora

**Comment by reneme** [comment]
`Botan::Cipher_Mode::create("3DES/ECB/PKCS7", Botan::ENCRYPTION)` returns a `nullptr`, because Botan does not support the ECB mode via this interface. Note that usage of ECB is generally discouraged as it is not secure for the general use case.

If you need to support ECB (e.g. for some legacy use case), you will need to use the bare metal 3DES block cipher and apply it to your cipher/plain-text blockwise. Please refer to this document for further details: https://botan.randombit.net/handbook/api_ref/block_cipher.html

**Comment by ra185148** [comment]
Thank you for the update. Seems the 3DES and ECB works well for us.
One small question again, DES supported with CBC?
Can we use Botan::Cipher_Mode::create("**DES/ECB/PKCS7**", Botan::ENCRYPTION)??

**Comment by reneme** [comment]
Yes, `DES/CBC/PKCS7` (note that the cipher mode of operation is "CBC" not "ECB") works with Botan. Just make sure to adjust your used key length to 64bit. Also be warned that DES is not considered secure these days anymore.

**Comment by ra185148** [comment]
Hi,
I am still finding a small issue with 3DES usage. 

"**Decryption is successful**" But it shows Unhandled exception : Microsoft C++ exception: Botan::Decoding_Error at memory location 0x00xxxxxx. After we execute "_enc->finish(data);_"

Key I am using - 698832F8778A7CFCBC79559DAB07B88A
IV - 6EED7B727B8A248E
Data to decrypt - 94B420079CC80BA3461F86FE26EFC4A3B8E4FA4C5F5341176EED7B727B8A248E

Note:
Data I am getting is in vector<uint8_t> from, which I am converting to secure_vector:
Botan::secure_vector<uint8_t> data;
data.assign(myData.begin(),myData.end());

**Comment by ra185148** [comment]
Hi,

When we tried to handle the exception using the Botan::Exception, Msg for that is "**Invalid CBC Padding**"
The above-mentioned data is working with some hardware encryption module. And we would not be able to change the data incoming.

**Comment by reneme** [comment]
Mhh, "invalid padding" either means, that you're using the wrong key and/or IV or the wrong padding scheme. Basically, it tells you that the data that came out of the encryption does not fit the expectation.

**Comment by ra185148** [comment]
Thank you for trying this out.
Seems the output he got is almost similar
00803F419E1CB7079442AA37474C2EFBF8B81C2965473CE 
but this is extra appended  "2A55B6F4C1D24DA70"

**Comment by ra185148** [comment]
But With PKCS7, output is 00803F419E1CB7079442AA37474C2EFBF8B81C2965473CE with the Invalid CBC Padding issue

**Comment by ra185148** [comment]
Or do we have any way to mention Optional Padding?

**Comment by reneme** [comment]
I reckon that `00803F419E1CB7079442AA37474C2EFBF8B81C2965473CE` is the string you would expect your application to generate? I.e. does this make sense to you, given your domain requirements?

Unfortunately, I'm now fishing in the dark entirely. Do you have any more information about your use case?

**Comment by CodeContribute** [comment]
Similar kind I am facing while working with decryption of TR31 blocks which I have followed from the following link - https://www.cryptomathic.com/news-events/blog/tr-34-key-blocks-for-the-tr-34-exchange-protocol-basic-principles

**Comment by CodeContribute** [comment]
The above mentioned keys matches the TR-31 keyblock and decryption out expected is also 00803F419E1CB7079442AA37474C2EFBF8B81C2965473CE
Tried with PKCS7 and NoPadding with same results as mentioned above.
PKCS7 gives correct results but says Invalid CBC Padding
And
NoPadding is adding extra buffer which is not expected

**Comment by ra185148** [comment]
Thank you all for all the help. Worked well with NoPadding.
