### ISSUE TITLE
Can I decrypt using only the "e d n" ?

### ISSUE THREAD

**Issue by wx1183618058** [randombit/botan#2863]
using "e d n" in OpenSSL as follows:
```
RSA *r = RSA_new();

r->e = BN_new();
r->d = BN_new();
r->n = BN_new();

BN_hex2bn(&(r->e), "XXXXXXXXXXXXXXXXXX");
BN_hex2bn(&(r->d), "XXXXXXXXXXXXXXXXXX");
BN_hex2bn(&(r->n), "XXXXXXXXXXXXXXXXXX");

RSA_private_decrypt(flen, from, to, r, padding);
```
```RSA_PrivateKey``` need "p q" , but i I didn't have. How to solve it in Botan?

Thanks very much.

**Comment by randombit** [comment]
It's possible/easy given `d` and `n` to recover the prime factors. There is no direct support for just using `e`/`d`/`n` though. For one because this prevents use of CRT optimization so signing/decryption would be quite slow.

Normally RSA keys are stored with all params available. Can you describe a bit what situation you are in where the primes are not available?

**Comment by wx1183618058** [comment]
This is a historical project using OpenSSL for PublicKey encryption and  RSA PrivateKey decryption. I checked the source code and didn't find the RSA keys. encryption using “e” "n" and decryption using “e” "d"  "n"  in code. Now I want to reimplement using botan.

**Comment by randombit** [comment]
Fair enough. I'll look up the algorithm over the upcoming holiday break. I'm not sure if we want to support it within the library, but really you would just have to run it once offline to recover the full key and then use it going forward.

**Comment by randombit** [comment]
Can you try this

```
std::pair<BigInt, BigInt>
factor_rsa_modulus(const BigInt& e, const BigInt& d, const BigInt& n, RandomNumberGenerator& rng)
   {
   const BigInt k = e*d - 1;

   BigInt g = BigInt::random_integer(rng, 2, n);
   BigInt t = k;

   for(;;)
      {
      if(t.is_even())
         {
         t >>= 1;
         const BigInt x = power_mod(g, t, n);

         if(x > 1)
            {
            const BigInt p = gcd(x - 1, n);

            if(p != 1)
               {
               const BigInt q = n / p;

               // sanity check:
               if(is_prime(p, rng) && is_prime(q, rng))
                  return std::make_pair(p, q);
               }
            }
         }
      else
         {
         g = BigInt::random_integer(rng, 2, n);
         t = k;
         }
      }
   }


RSA_PrivateKey from_edn(const BigInt& e, const BigInt& d, const BigInt& n, RandomNumberGenerator& rng)
   {
   auto pq = factor_rsa_modulus(e, d, n, rng);
   auto key = RSA_PrivateKey(pq.first, pq.second, e, d, n);

   if(!key.check_key(rng, true))
      throw std::runtime_error("Key check failed");

   return key;
   }
```

**Comment by wx1183618058** [comment]
Thank you @randombit .
I have recovered the full key by your code. Other helpful contents are as follows: 
[https://stackoverflow.com/questions/2921406/calculate-primes-p-and-q-from-private-exponent-d-public-exponent-e-and-the](url)
