### ISSUE TITLE
RSA encryption using OAEP with label

### ISSUE THREAD

**Issue by halvors** [randombit/botan#2874]
Hi!

I am having a hard time figuring out how to specify the label of OAEP that you can see here: https://github.com/randombit/botan/blob/master/src/lib/pk_pad/eme_oaep/oaep.h#L34

How would i set this to something other than empty string when obtaining a PK_Encryptor?

**Comment by randombit** [comment]
It's a little awkward but passing `"OAEP(SHA-512,MGF1,YourLabelHere)"` to `PK_Encryptor` should work

**Comment by halvors** [comment]
Thx :-)
