### ISSUE TITLE
botan/internal doesn't exist

### ISSUE THREAD

**Issue by oliviervibe** [randombit/botan#2875]
Hi,

I'm trying to use botan to wrap a PKCS11 library but when compiling the file botan/internal/dyn_load.h cannot be found.
If I don't include that file, the following line doesn't compile:
Botan::Dynamically_Loaded_Library pkcs_module("/usr/local/lib/softhsm/libsofthsm2.so");

Under /usr/local/include/botan-3/botan this directory doesn't't exist. 

However, I could find this file where I compiled the library. The directory is under build/include/botan/internal.
I could use this include folder in my project but it doesn't feel right! 

Did I miss something when I installed the library using 'make install'

Thanks!

**Comment by randombit** [comment]
Normally you would pass that path to the `PKCS11::Module` constructor, which internally uses `Dynamically_Loaded_Library`.

The `internal` headers represent things where we want to have a header for it so functionality can be used in different places within the library, but which we don't want to include in our API contract.

**Comment by oliviervibe** [comment]
I agree with that and I discovered what you're telling me.

I was just trying to verify an issue that I had when loading dynamically the sofhsm2 DLL and using the function pointer to call the PKCS functions.

It seems that the documentation of botan is not up to date as it describes both the high level (Module class) and low-level API (the one accessible through internal includes).

By the way, the doc of the high level is incorrect as it mentions the include p11_module.h that doesn't exist any longer!

If the low-level API is not accessible, it should not appear in the doc. I guess this is a recent change.

Thanks

**Comment by randombit** [comment]
Thanks for mentioning, I'll take a look. The docs are probably correct for 2.x branch and haven't been updated.

**Comment by oliviervibe** [comment]
You're welcome, the wrapping of Softhsm2 using PKCS11::Module is working fine,
