### ISSUE TITLE
Missing include <windows.h> in UWP build

### ISSUE THREAD

**Issue by oviano** [randombit/botan#2887]
It's necessary to add this include before including <bcrypt.h> as otherwise the build fails on UWP.

https://stackoverflow.com/questions/57472787/compile-errors-when-using-c-and-bcrypt-header

**Comment by oviano** [comment]
Also, even when including <windows.h>, there are errors relating to STATUS_SUCCESS not being defined.

It looks like the code should be using the macro

BCRYPT_SUCCESS()

Instead of trying to use the definition STATUS_SUCCESS which isn't defined even when including <windows.h> followed by <bcrypt.h>.

**Comment by oviano** [comment]
This is while building using the amalgamation, by the way.

**Comment by randombit** [comment]
Thanks for reporting. UWP build isn't tested by CI and I think was just tested once manually when support was first added.

**Comment by oviano** [comment]
Hello there, @randombit sorry for taking a while - yes I can confirm 2909 fixes this issue.

Also, using that branch, all the warnings have disappeared from all platforms I'm using, with the exception of warning C4250 which appears on both Windows and UWP, an example of which is:

C:\Users\Oliver\Git\source\ovlibs\ovnet\thirdparty\botan\uwp\x64\botan_all.h(7424,4): warning C4250: 'Botan::DL_Scheme_
PrivateKey': inherits 'Botan::DL_Scheme_PublicKey::Botan::DL_Scheme_PublicKey::estimated_strength' via dominance
