### ISSUE TITLE
String decryption only works for the first 16 bits - ECB 

### ISSUE THREAD

**Issue by nbianka99** [randombit/botan#2890]
Hello, i have the following function: 

```C++
public int ECB_decryption(uint8_t cipher[], uint8_t cipherSize, uint8_t key[], uint8_t keySize, std::string* plain, uint8_t* plainSize)
{
          botan_block_cipher_t ciph;
          Botan::secure_vector<uint8_t> cipher2(cipherSize);
	  Botan::secure_vector<uint8_t> result(cipherSize);

	  Botan::copy_mem(cipher2.data(), cipher, cipherSize);
	  double blockSize = ceil(double(cipherSize)/(double)16);

	  int retciph = botan_block_cipher_init(&ciph, "AES-128");
	  int retkey = botan_block_cipher_set_key(ciph, key, keySize);
	  int retdec = botan_block_cipher_decrypt_blocks(ciph, cipher2.data(), result.data(), blockSize);

          return 1;
}
```

with the function call and parameters:

```C++
uint8_t key[] = { 0x10, 0x0F, 0x0E, 0x0D, 0x0C, 0x0B, 0x0A, 0x09, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01 };
uint8_t cipher[1028];
uint8_t keySize = 16;
uint8_t cipherSize;
char* plainText = "Test Authenticated Encryption";
    
ECB_decryption(cipher, cipherSize, key, keySize, &decryptedOutput, &decryptedOutputSize);
```

The cipher and the cipherSize are outputs of the ECB_encryption function, which is written in the same manner as the decryption function and it works fine. 
The issue is that it decripts only the first 16 bits of my text input. Also I tried a numeric input such as "0000000000000000000000000043dcc8" which is decrypted nicely. But I also tried to encrypt and decrypt "0000000000000000000000000043dcc43dcc" and the last 4 bits won't be decrypted.

![1](https://user-images.githubusercontent.com/42147654/151519507-b4415002-c069-4f39-8ed8-9bbd1f8573a6.PNG)
![2](https://user-images.githubusercontent.com/42147654/151519509-7c168578-8481-4385-bbf7-7d40c112be9b.PNG)

Can you please tell me what did I do wrong? Or is it a bug?

**Comment by reneme** [comment]
I took the liberty to reformat your code listings a bit.

From a quick glance, my guess is that you should set the variable `cipherSize` at the call site. Right now, you just pass it into the `ECB_decryption` function uninitialized. Maybe to the byte length of the `plainText`?

**Comment by nbianka99** [comment]
> I took the liberty to reformat your code listings a bit.
> 
> From a quick glance, my guess is that you should set the variable `cipherSize` at the call site. Right now, you just pass it into the `ECB_decryption` function uninitialized. Maybe to the byte length of the `plainText`?

The cipherSize will be initialized after encryption. For the working example it's 32 and for the "Test Authenticated Encryption" in 29, which is correct

**Comment by reneme** [comment]
> The cipherSize will be initialized after encryption.

Alright. Makes sense.

> For the working example it's 32

So your code works as expected, if your plaintext data is exactly 32 bytes long?

> for the "Test Authenticated Encryption" in 29, which is correct

Could it be, that you encrypt/decrypt functions require inputs that are a multiple of the block cipher's block length (which is 128bit for AES)?

**Comment by nbianka99** [comment]
> > The cipherSize will be initialized after encryption.
> 
> Alright. Makes sense.
> 
> > For the working example it's 32
> 
> So your code works as expected, if your plaintext data is exactly 32 bytes long?
> 
> > for the "Test Authenticated Encryption" in 29, which is correct
> 
> Could it be, that you encrypt/decrypt functions require inputs that are a multiple of the block cipher's block length (which is 128bit for AES)?

Yes, I think that will be. I added 3 more letters after my plain text input, and it decrypts it.

**Comment by reneme** [comment]
AES in the ECB mode-of-operation can only work on full blocks of plaintext/ciphertext data. I don't know how your `botan_block_cipher_decrypt_blocks` is implemented in detail, though it should probably add a padding to the plaintext to account for that.

**Comment by nbianka99** [comment]
Okay, thank you!
