### ISSUE TITLE
How to include Botan in a project built with Cmake?

### ISSUE THREAD

**Issue by oliviervibe** [randombit/botan#2897]
Maybe I did something very wrong but the following doesn't seem to work:

... 
include(FetchContent)
FetchContent_Declare(botan GIT_REPOSITORY https://github.com/randombit/botan.git)
FetchContent_MakeAvailable(botan)

file(
	GLOB_RECURSE _srce_files
	LIST_SDIRECTORIES false
	"${CMAKE_CURRENT_LIST_DIR}/include/*.h"
	"${CMAKE_CURRENT_LIST_DIR}/src/*.cpp"
)

add_executable(test_botan ${_srce_files})

target_link_libraries(test_botan 
	PRIVATE dl
	PRIVATE botan
)

target_include_directories(test_botan 
	PRIVATE ${CMAKE_CURRENT_LIST_DIR}/include
)

The source of botan is downloaded, but it is not compiled. I'm using Visual Studio Code. I have created a test with a version of botan that I precompiled and installed. This works, but I would like to compile my final project including the git reference. It doesn't seem to work like with all the other libraries I have used before.

Any hint would be appreciated if this is possible to do.  

PS: I noticed that when I compiled the library separately its name is 'botan-3'.

**Comment by ncoder-1** [comment]
I used to have an external `.cmake` file that would use botan's `configure.py` to build itself, but I have since switch to using [conan](https://conan.io/) within my `CMakeLists.txt` file as it is so much more convenient and portable (you only need to have conan installed):

Here's an example of what that looks like:
```cmake
cmake_minimum_required(VERSION 3.15)
project(botan-app LANGUAGES CXX C)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})

if (NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
    file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/release/0.17/conan.cmake"
            "${CMAKE_BINARY_DIR}/conan.cmake"
            EXPECTED_HASH SHA256=3bef79da16c2e031dc429e1dac87a08b9226418b300ce004cc125a82687baeef
            TLS_VERIFY ON)
endif ()

include(${CMAKE_BINARY_DIR}/conan.cmake)
conan_cmake_configure(REQUIRES botan/2.19.1
        GENERATORS cmake_find_package)

conan_cmake_autodetect(settings)

conan_cmake_install(PATH_OR_REFERENCE .
        BUILD missing
        REMOTE conancenter
        OPTIONS botan:shared=False
        SETTINGS ${settings})

find_package(botan)

add_executable(botan-app src/main.cpp)
target_link_libraries(botan-app PRIVATE botan::botan)
```

If you'd still rather have my old way of building `botan` from `cmake`, let me know.

**Comment by randombit** [comment]
I don't have much experience with Cmake but this might be helpful: https://github.com/keepassxreboot/keepassxc/blob/develop/cmake/FindBotan2.cmake

**Comment by dsvi** [comment]
There are options
1. [Downloads botan sources and generates amalgamated build at compile time](https://github.com/Tectu/botan-cmake)
2. [Uses local archive and  generates amalgamated build at configure time](https://gitlab.com/44100Hz/cmake-for-botan)

**Comment by lieser** [comment]
The next Botan release will include a `botan-config.cmake` that should make CMake integration easier (https://github.com/randombit/botan/pull/3722). Some small documentation was added for it in https://github.com/randombit/botan/pull/3826.

I also updated the CMake information in https://github.com/randombit/botan/wiki/Adding-Botan-to-your-build.

Hopefully with this the question how to use Botan with CMake is answered.
If not please create a new issue with more concrete questions.
