### ISSUE TITLE
botan.randombit.net fails with IPv6

### ISSUE THREAD

**Issue by tiwoc** [randombit/botan#290]
My ISP offers dual-stack IPv4/IPv6. When requesting a botan release tarball, the DNS server returns both an IPv4 and IPv6 address for `botan.randombit.net`. `wget` now tries IPv6 first, but connecting to port 80 via IPv6 times out, which takes a minute or so.

According to [ipv6-test.com](http://ipv6-test.com/), my own connection works fine, but when using their [website test](http://ipv6-test.com/validate.php), `botan.randombit.net` doesn't respond to connection requests via IPv6.

To fix this, either remove the AAAA record from DNS, or (better) make the webserver also serve via IPv6.

**Comment by randombit** [comment]
Thanks. The webserver is running dual stack but there seems to be some problem with the machines IPv6 routing - I cannot reach it even from another IPv6 host in the same data center. I have removed the AAAA record for now.
