### ISSUE TITLE
Core dump during test execution on s390 with GCC 12

### ISSUE THREAD

**Issue by bkircher** [randombit/botan#2900]
Test execution aborts in std::vector<>::operator[] due to a failed assertion on IBM System z9 with a GCC 12. Complete build logs attached.

[gcc12-s390x-build.log](https://github.com/randombit/botan/files/8007800/gcc12-s390x-build.log)

```
SRP6 ran 1 tests all ok
srp6_kat:
SRP6a ran 192 tests in 785.47 msec all ok
system_rng:
System_RNG ran 3 tests all ok
testcode:
Test Framework ran 45 tests all ok
Testsuite_RNG ran 256 tests all ok
thread_pool:
Thread_Pool ran 100 tests all ok
tls:
/usr/include/c++/12/bits/stl_vector.h:1122: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = Botan::secure_allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
/var/tmp/rpm-tmp.j2Ftck: line 42: 73430 Aborted                 (core dumped) LD_LIBRARY_PATH=/builddir/build/BUILDROOT/botan2-2.19.1-2.fc36.s390x/usr/lib64 ./botan-test
```

**Comment by bkircher** [comment]
I have a build that looks good:
[s390x-openssl11-good-build.log](https://github.com/randombit/botan/files/8007965/s390x-openssl11-good-build.log)

Only difference: it uses OpenSSL 1.1 whereas the failing build above uses OpenSSL 3.

I think we can close this issue since OpenSSL 3 is not supported. I guess, we need to drop the openssl provider on platforms that don't ship OpenSSL 1.1 anymore.

**Comment by randombit** [comment]
Removed now in 2.x release branch also - #2902
