### ISSUE TITLE
HMAC verify_mac returns false despite having the right tag

### ISSUE THREAD

**Issue by ncoder-1** [randombit/botan#2906]
I'm trying an HMAC variation of the API reference's [MAC code example](https://botan.randombit.net/handbook/api_ref/message_auth_codes.html#code-examples) with the following code block:

```cpp
const std::vector<uint8_t> key = Botan::hex_decode("2B7E151628AED2A6ABF7158809CF4F3C");
std::string str_data{"test input"};

std::unique_ptr<Botan::MessageAuthenticationCode> mac(Botan::MessageAuthenticationCode::create("HMAC(SHA-256)"));
if (!mac) return 1;

mac->set_key(key);
mac->update(str_data);
auto tag = mac->final();
std::cout << "MAC Tag: " << Botan::hex_encode(tag) << '\n';
std::cout << "MAC Verification: " << (mac->verify_mac(tag) ? "success" : "failure") << '\n';

//Corrupting data
str_data.back()++;
//Verify with corrupted data
mac->update(str_data);

std::cout << "MAC Verification: " << (mac->verify_mac(tag) ? "success" : "failure") << '\n';
```

The expected tag is properly produced (in hex) as F7BBE02AEE26661740420E6986C3EED4BDD1D5F8A3EA7A68B91EC7D729696AE1

And is verified both by openssl:
```
$ echo -n "test input" | openssl dgst -sha256  -mac hmac -macopt hexkey:2B7E151628AED2A6ABF7158809CF4F3C                                                                                
(stdin)= f7bbe02aee26661740420e6986c3eed4bdd1d5f8a3ea7a68b91ec7d729696ae1
```

And GCHQ's [CyberChef](https://gchq.github.io/CyberChef/#recipe=HMAC(%7B'option':'Hex','string':'2B7E151628AED2A6ABF7158809CF4F3C'%7D,'SHA256')&input=dGVzdCBpbnB1dA).

Both this code sample and the API ref's AES-128 CMAC example returns `false` before the data corruption. 

So if the tag is correct prior to the "data corruption", why does `verify_mac()` return `false`?

**Comment by randombit** [comment]
After you call a function which computes the result of a MAC (like `verify_mac` or `final`) the message state of the MAC object resets. So the problem is you are missing a

```
mac->update(str_data);
```

between the call to `final` and the first call of `verify_mac`.

**Comment by ncoder-1** [comment]
Ah got it, thanks!
