### ISSUE TITLE
Documentation does not compile properly

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#291]
Here's the problem-reporting output of "sudo make install":

   sphinx-build -c ./src/build-data/sphinx -b html ./doc/manual build/docs/manual
   Running Sphinx v1.3.1
   WARNING: the config value 'latex_show_urls' has type `bool', defaults to `str.'
   loading pickled environment... not yet created
   building [mo]: targets for 0 po files that are out of date
   building [html]: targets for 26 source files that are out of date
   updating environment: 26 added, 0 changed, 0 removed
   reading sources... [100%] x509                                                                                
   /Users/ur20980/Src/botan/doc/manual/tls.rst:197: WARNING: Error when parsing function declaration:
   If no return type {
   Invalid definition: Expected identifier in nested name. [error at 353]
     TLS::Client( output_fn output, data_cb data, alert_cb alert, handshake_cb handshake_complete,    TLS::Session_Manager& session_manager, Credentials_Manager& credendials_manager, const    TLS::Policy& policy, RandomNumberGenerator& rng, const Server_Information& server_info, const    Protocol_Version offer_version, const std::vector<std::string>& app_protocols,
     ---------------------------------------------------------------------------------------------------------------------------------------   -------------------------------------------------------------------------------------------------------------------------------------------   -------------------------------------------------------------------------------^
   } else if return type {
   If declId, parameters, and qualifiers {
   Invalid definition: Expected identifier in nested name. [error at 11]
     TLS::Client( output_fn output, data_cb data, alert_cb alert, handshake_cb handshake_complete,    TLS::Session_Manager& session_manager, Credentials_Manager& credendials_manager, const   TLS::Policy& policy, RandomNumberGenerator& rng, const Server_Information& server_info, const    Protocol_Version offer_version, const std::vector<std::string>& app_protocols,
     -----------^
   } else If parenthesis in noptr-declarator {
   Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 23]
     TLS::Client( output_fn output, data_cb data, alert_cb alert, handshake_cb handshake_complete,    TLS::Session_Manager& session_manager, Credentials_Manager& credendials_manager, const    TLS::Policy& policy, RandomNumberGenerator& rng, const Server_Information& server_info, const    Protocol_Version offer_version, const std::vector<std::string>& app_protocols,
     -----------------------^
   }
   }
   /Users/ur20980/Src/botan/doc/manual/tls.rst:197: WARNING: Error when parsing function declaration:
   If no return type {
   Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 7]
  size_t reserved_io_buffer_size)
  -------^
   } else if return type {
   Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 30]
     size_t reserved_io_buffer_size)
     ------------------------------^
   } 
   /Users/ur20980/Src/botan/doc/manual/tls.rst:287: WARNING: Error when parsing function declaration:
   If no return type {
   Invalid definition: Expected identifier in nested name. [error at 362]
     TLS::Server( std::function<void, const byte*, size_t> output_fn, std::function<void, const byte*, size_t>    data_cb, std::function<TLS::Alert, const byte*, size_t> alert_cb, TLS::Session_Manager&    session_manager, Credentials_Manager& creds, const TLS::Policy& policy, RandomNumberGenerator&    rng, std::function<std::string, std::vector<std::string> > proto_chooser,
     ---------------------------------------------------------------------------------------------------------------------------------------    -------------------------------------------------------------------------------------------------------------------------------------------  ----------------------------------------------------------------------------------------^
   } else if return type {
   If declId, parameters, and qualifiers {
   Invalid definition: Expected identifier in nested name. [error at 11]
  TLS::Server( std::function<void, const byte*, size_t> output_fn, std::function<void, const byte*, size_t> data_cb, std::function<TLS::Alert, const byte*, size_t> alert_cb, TLS::Session_Manager& session_manager, Credentials_Manager& creds, const TLS::Policy& policy, RandomNumberGenerator& rng, std::function<std::string, std::vector<std::string> > proto_chooser,
  -----------^
} else If parenthesis in noptr-declarator {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 54]
  TLS::Server( std::function<void, const byte*, size_t> output_fn, std::function<void, const byte*, size_t> data_cb, std::function<TLS::Alert, const byte*, size_t> alert_cb, TLS::Session_Manager& session_manager, Credentials_Manager& creds, const TLS::Policy& policy, RandomNumberGenerator& rng, std::function<std::string, std::vector<std::string> > proto_chooser,
  ------------------------------------------------------^
}
}
/Users/ur20980/Src/botan/doc/manual/tls.rst:287: WARNING: Error when parsing function declaration:
If no return type {
Invalid definition: Expected identifier in nested name, got keyword: const [error at 5]
  const std::vector<std::string>& protocols, bool is_datagram = false, bool reserved_io_buffer_size)
  -----^
} else if return type {
Invalid definition: Expecting "(" in parameters_and_qualifiers. [error at 41]
  const std::vector<std::string>& protocols, bool is_datagram = false, bool reserved_io_buffer_size)
  -----------------------------------------^
}
/Users/ur20980/Src/botan/doc/manual/tls.rst:3: SEVERE: Duplicate ID: "TLS::Session".
/Users/ur20980/Src/botan/doc/manual/tls.rst:745: WARNING: Type must be either just a name or a typedef-like declaration.
Just a name error: Invalid definition: Expected identifier in nested name, got keyword: enum [error at 4]
  enum Version_Code
  ----^
Typedef-like expression error: Invalid definition: Expected identifier in nested name, got keyword: enum [error at 4]
  enum Version_Code
  ----^
/Users/ur20980/Src/botan/doc/manual/tls.rst:3: SEVERE: Duplicate ID: "TLS::Protocol_Version::latest_tls_version".
/Users/ur20980/Src/botan/doc/manual/tls.rst:3: SEVERE: Duplicate ID: "TLS::Protocol_Version::latest_dtls_version".
/Users/ur20980/Src/botan/doc/manual/x509.rst:5: SEVERE: Duplicate ID: "X509_Certificate::subject_dnC".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] x509                                                                                 
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 10 warnings.
./src/scripts/install.py --destdir=/opt/local --build-dir="build" --bindir=bin --libdir=lib --docdir=doc --includedir=include
   INFO: Botan 1.11.21 installation complete
```

**Comment by webmaster128** [comment]
Thanks. Looks like that is a sphinx bug: https://github.com/sphinx-doc/sphinx/issues/2069

**Comment by webmaster128** [comment]
The bug I linked is not related to your warnings. I created the bugreport based on my sphinx version 1.2.3 on Ubuntu because I did not carefully read your output. The current version 1.3.1 does not have the linked issue anymore.

I was able to get rid of most errors and warnings in #306.
