### ISSUE TITLE
argon2 not available in BSI mode

### ISSUE THREAD

**Issue by Kretikus** [randombit/botan#2915]
BSI is reccommending argon2 for password hashing, but is blocked in BSI mode because of the blake2 dependency.

See
https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102.pdf?__blob=publicationFile

Chapter B.1.2. Page 75

**Comment by randombit** [comment]
@securitykernel what do you think? Should we allow `blake2` as well in order to enable Argon2?

**Comment by mouse07410** [comment]
I'm not asked, but I think - yes wet should. 😉

**Comment by securitykernel** [comment]
We noticed this contradiction, too, recently. We will discuss it with BSI next week and come back to you here.

**Comment by securitykernel** [comment]
So argon can be enabled as it is indeed recommended. blake2 can be removed from the prohibited list, but note that it should only be used in conjunction with argon as it is not recommended as a standalone hash function. The same holds for kyber and its shake dependency.

* argon -> required
* blake2 -> not prohibited, but not required
* kyber, kyber_90s -> required
* shake, shake_cipher -> not prohibited, but not required
