### ISSUE TITLE
Substantial performance hit encoding ASN1 Sequence between 2.9 and 2.18

### ISSUE THREAD

**Issue by CardContact** [randombit/botan#2920]
We are working on an application, where we need to create a large ASN1 SEQUENCE with 100K OCTET-STRING entries.

So far we used libbotan-2-dev that comes with Debian Buster in version 2.9. There was no notable time required to encode the structure.

This is completely different with 2.18, where encoding the list takes a dramatic 90 seconds.

Looking at the git revision history I can not really see what may cause this decrease in performance. 

Any idea ?

**Comment by CardContact** [comment]
Apparently the issue is introduced between 2.16 and 2.17.

2.16 is still fast, while 2.17 requires 90 seconds.

**Comment by CardContact** [comment]
Tracing it further down: #f9f2cb0 is causing the issue. #

**Comment by randombit** [comment]
Thanks for bisecting this. I can reproduce the problem with a small testcase and confirmed that partially reverting f9f2cb0 improves performance by ~100x. It is interesting that performance of `reserve`+`insert` is so poor.

**Comment by reneme** [comment]
@hrantzsch and I looked into that and found that `reserve` always allocates exactly as much memory as requested, while `resize` allocates in 'exponential' steps.

When adding many small-ish buffers incrementally, such as "100K octet-string entries" into the ASN.1 container, this will result in `reserve` copying _a lot_ (read: exponentially) more data than `resize` + `memcpy`.

We suggest to refrain from using `reserve` for the ASN.1 interface and let `insert` deal with the memory allocations. This will make the `std::vector` fall back to "exponential capacity increase", which is likely what we want for append-heavy interfaces like the ASN.1 container.

That's an interesting gotcha indeed!


For completeness, here are our measurements:

```C++
#include <iostream>
#include <cstdint>
#include <vector>

int main() {
  // a single 1 MiB buffer to be repeatedly appended
  const std::vector<uint8_t> in(1024 * 1024, 42);

  // data sink
  std::vector<uint8_t> out;

  const size_t iterations = 100;

  // repeatedly append `in` to out with different strategies
  for (int i = 0; i < iterations; ++i) {
    std::cout << out.capacity() << std::endl;

#ifdef RESERVE
    // `reserve` allocates exactly as much as asked in every iteration, hence
    // will re-allocate in O(n) iterations and perform increasingly larger memory copies.
    out.reserve(out.size() + in.size());
#endif

    out.insert(out.end(), in.begin(), in.end());
  }

  return 0;
}
```

As a result, the runtime of the `reserve` branch runs away exponentially for increasing iterations while without it the program scales (almost) linearly with the iterations.

![Screenshot 2022-02-28 at 14 15 23](https://user-images.githubusercontent.com/1562139/155989747-cdefe8ad-0d14-469d-8d90-dbc00129cb17.png)

**Comment by CardContact** [comment]
I can confirm, that the bug disappears, if DER_Encoder is created with a pre-allocated buffer of the required size.

However, that does not work if the sequence in question is not at the top-most level.

Will there be a patch for this issue ?
