### ISSUE TITLE
Uninstalling Botan from tar.xz file

### ISSUE THREAD

**Issue by Marko-Sanchez** [randombit/botan#2921]
While running into many issues trying to get Botan to work with Cmake. I have decided to uninstall Botan, of which I installed via tar.xz . Although, there seems to be no apparent way of uninstalling, I've tried `make uninstall` in the Botan folder but that seems not to work. Any tips on uninstalling or does such a method exist ? 

OS: Ubuntu 18.04.6 LTS x86_64

**Comment by randombit** [comment]
No uninstall method at the moment. I expect most people get the library via a package manager which can handle this. It would be a nice to have something for this, though.
