### ISSUE TITLE
Is it possible to provide a build option to set c++ version ?

### ISSUE THREAD

**Issue by netplus** [randombit/botan#2925]
Hello,
I've been using Botan several years, I have to switch to c++14, and c++20 in the coming two years, I checked the document of building section, I did not found any option to set the c++ verstion, Is it possible to set a give c++ version to build botan ?

**Comment by reneme** [comment]
The current stable version of Botan uses C++11, hence the hardcoding you pointed out. The upcoming Botan 3 major release will be based on C++17. Nevertheless, it should be perfectly fine to use Botan2 (being compiled in C++11 mode) with your code that compiles in C++14 or higher.

You might have some luck with `./configure.py --extra-cxxflags='-std=c++14`, to force the compiler to use a C++ standard above C++11 for Botan2.

**Comment by netplus** [comment]
Thanks for your advice , I prefer to take a try by modifying the hardcode from c++11 to c++14.
