### ISSUE TITLE
Latest verstion that supports visual studio 2005

### ISSUE THREAD

**Issue by LinArcX** [randombit/botan#2934]
Hello. We have a legacy codebase that uses c++98 and visual studio 2005.

My manager decided to use TLS in this codebase. I wanted to know what is the latest version of botan that supports vistual studio 2005?

EDIT: I know it's insane to use an outdated TLS library. Also outdated c++ version and visual studio. But please let me know what's the latest version of botan that meet my requirements.

**Comment by randombit** [comment]
VC **2005**? Not 2015??

Yikes

I have no idea when exactly VC2005 support was dropped. You might try 1.10 but keep in mind that these releases aren't supported at all in any way, implement only now obsolete versions of TLS, and have a completely different TLS API which doesn't support async communication well.

Just in case that was a typo (which for your sake I hope it was), VC 2015 is still supported in the latest stable releases, up to and including 2.19.1

If you really need VC2005 support you are probably better off using another library, likely one written in C
