### ISSUE TITLE
Question: How to switch between CRT linkage type for MSVC

### ISSUE THREAD

**Issue by diorahman** [randombit/botan#294]
Hi,

How to configure the CRT linkage type in MSVC when building Botan from source?

Thanks!

**Comment by cdesjardins** [comment]
Currently there is no built in way to do this, I just use find/replace on the Makefile, sed works fine. It is an open issue:
https://github.com/randombit/botan/issues/210

There is also a branch where they are starting to use cmake as the build system, which should support this, but it is not a very mature build system yet.

**Comment by randombit** [comment]
Closing as dup of #210
