### ISSUE TITLE
wiki/Users: Outdated URL for BSI’s page about the 2015 project

### ISSUE THREAD

**Issue by paulmenzel** [randombit/botan#2950]
The [*Users page*](https://github.com/randombit/botan/wiki/Users) page links *BSI's page about the project* to the URL below, currently giving a 404 error.

https://www.bsi.bund.de/DE/Themen/Kryptografie_Kryptotechnologie/Kryptografie/Kryptobibliothek/kryptobibliothek_node.html

Maybe use the one from the Internet Archive’s [Wayback Machine](https://web.archive.org/) instead?

https://web.archive.org/web/20200601061507/https://www.bsi.bund.de/DE/Themen/Kryptografie_Kryptotechnologie/Kryptografie/Kryptobibliothek/kryptobibliothek_node.html

**Comment by reneme** [comment]
Thanks! Apparently they restructured their website. Here's the new link: https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Kryptografie/Kryptobibliothek-Botan/kryptobibliothek-botan_node.html

**Comment by paulmenzel** [comment]
Thank you for fixing it so quickly. Too bad, organizations still have not understood how the Web works, and that URLs should not be broken, and, if, for whatever reason, the site is restructured, you at least set up redirects.
