### ISSUE TITLE
Docstring for inverse_mod() seems to be outdated

### ISSUE THREAD

**Issue by lieser** [randombit/botan#2961]
#2634  Added a fastpath for inversion modulo 2*o.

But the docstring still only list leaking the 3 categories:
- odd integer
- a power of 2
- some other even number

The new 2*o case seems to be missing.

It also mentions that if the modulus is even that it leaks the power of 2 which divides the modulus.
Is this still true for the new fastpath? From my understanding this change was not just for performance, but also to not leak any information about the structure of the prime (for the new 2*o case, and besides of course that it has this structure).

**Comment by randombit** [comment]
I think that there is a special case for `2*o` doesn't affect the docstring categories, because we also mention that for `2^k*o` case, we do leak `k`, and the existence of a special case for `2*o` that differs from the general `2^k*o` path is just "how" we leak that `k=1`.

**Comment by lieser** [comment]
Thanks for explaining, I agree now that the change does not affect the docstring.
