### ISSUE TITLE
Special case in ressol() for p == 2 is never reached

### ISSUE THREAD

**Issue by lieser** [randombit/botan#2962]
The `ressol()` function contains a special case for `p == 2`, so I assume this is a valid input.

But in 55fa3685c5053d66533a7a9e0f08403ffa95b323 the input checks there rearranged so that the `p.is_even()` check is now done at the beginning, which results in an exception being thrown before the special case for `p == 2` is reached.

**Comment by randombit** [comment]
I am not sure that Shanks-Tonelli applies for p == 2 but certainly we can trivially compute the square roots in that case, so it should be supported. Probably we have no test cases for this situation which is what allowed the regression.
