### ISSUE TITLE
Bad header placement in /usr/local/include/

### ISSUE THREAD

**Issue by IlannM** [randombit/botan#2986]
When installing on Linux, a `botan-2` folder will be put inside `/usr/local/include`, as a wrapper to the actuall `botan` folder that actually has the headers. And since the botan headers themselves have the path to other headers as if simply `botan` was inside the include folder, it gives a compile error. Of course this can be easily fixed by cd'ing into /usr/local/include and `mv botan-2/botan && rmdir botan-2`

**Comment by randombit** [comment]
That's not the intended usage. You should use `-I/usr/local/include/botan-2` then in your source include as `<botan/header.h`>. This scheme allows parallel installs of multiple versions.
