### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by briteming** [randombit/botan#2991]
hi.

on my mac.
git clone https://github.com/randombit/botan --depth 1
cd botan
./configure.py
make
it shows:
...
In file included from src/lib/pbkdf/argon2/argon2.cpp:15:
build/include/botan/internal/thread_pool.h:69:68: error: no type named
      'invoke_result' in namespace 'std'
  ...f, Args&&... args) -> std::future<typename std::invoke_result<F, Args......
                                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~
build/include/botan/internal/thread_pool.h:69:95: error: expected ';' at end of
      declaration list
  ...args) -> std::future<typename std::invoke_result<F, Args...>::type>
                                                                   ^
                                                                   ;
src/lib/pbkdf/argon2/argon2.cpp:348:50: error: no matching member function for
      call to 'run'
               fut_results.push_back(thread_pool.run(
                                     ~~~~~~~~~~~~^~~
3 errors generated.
make: *** [build/obj/lib/pbkdf_argon2.o] Error 1

how to fix the errors?

**Comment by randombit** [comment]
What compiler/compiler version are you using? Keep in mind that master requires C++17 support, your compiler seems to be missing `std::invoke_result` and may be too old.

**Comment by randombit** [comment]
`make` is just the program that invokes the compiler.

Your compiler will be either `gcc` or more likely `clang`

But if your `make` program is really 16 years old then probably your compiler is also quite old and is not going to have C++17 support.

Anyway, `master` is a work in progress and is not supported in any way right now. Please use the latest release which is available in package managers like [Homebrew](https://formulae.brew.sh/formula/botan) and which requires only C++11.
