### ISSUE TITLE
"Assertion '__n < this->size()' failed" in TLS test on Fedora

### ISSUE THREAD

**Issue by DaanDeMeyer** [randombit/botan#3002]
Build/Test logs: https://gist.githubusercontent.com/DaanDeMeyer/ea1187d30f7ca12ef44d337400a9b204/raw/457d0a3ca456059da6d6c0416e8d0eff86b3d434/gistfile1.txt (see bottom of gist for the assertion failure)

Let me know if you need any more information. All package versions and such should be available in the build logs.

**Comment by randombit** [comment]
Closing this since we cannot replicate and have no ability to diagnose the problem.
