### ISSUE TITLE
get_emsa() is declared but not defined

### ISSUE THREAD

**Issue by lieser** [randombit/botan#3022]
I see a declaration of `BOTAN_TEST_API EMSA* get_emsa(const std::string& algo_spec)` in `src/lib/pk_pad/emsa.h`, but don't see any definition of it.

This is caused by the raw pointer removal #2697.

Either:
1. The declaration should be removed
2. Similar to other removals, a small definition using the new `EMSA::create()` should be added again.
    - Maybe declare it as deprecated. But in most similar cases (e.g. `BlockCipher::clone()`) the old API using raw pointer is not yet marked deprecated.

**Comment by randombit** [comment]
Thanks for reporting. This decl can be removed entirely, since access to the `EMSA` objects for encoding is made entirely private starting in 3.0
