### ISSUE TITLE
Compatibility with .net core 6 in PKCS1 mode

### ISSUE THREAD

**Issue by oliviervibe** [randombit/botan#3037]
Hi,

I'm facing an issue when decrypting a digest (32 bytes) encrypted using RSA in EME_PKCS1 mode using .net Core 6 also in PKCS1. I'm facing the same issue with Bouncy Castle as well.
The digest once padded is 235 bytes length.

The encryption/decryption perfectly works when using Botan for both operations. I did the test using the exact same Private Key with Botan or .Net Core. I tried to export the key either encrypted or not, but I get the same problem.

This is the code of the encryption with Botan:
``` 
std::unique_ptr<RSA_PublicKey> rsaEncrPublicKey = loadRSAPubKeyFromToken(ckEncrPubKeyRef);
PK_Encryptor_EME emeEncryptor(*rsaEncrPublicKey, p11Rng, "EME-PKCS1-v1_5");
auto encrChallenge = emeEncryptor.encrypt(challenge, p11Rng);
std::string b64EncrChall = utility::Base64Helper::toBase64String(encrChallenge);
```

The code of the decryption with .Net Core 6:
```
var rsaPem = File.ReadAllText(PKEY_PEM);

RSACryptoServiceProvider rsa = new RSACryptoServiceProvider();
rsa.ImportFromEncryptedPem(rsaPem, PWD);

string encrDigest = File.ReadAllText(ENCR_DATA);
byte[] digestData = Convert.FromBase64String(encrDigest);

byte[] digest = rsa.Decrypt(digestData, RSAEncryptionPadding.Pkcs1);
```

This is the exception thrown by the Decrypt function: 
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'The parameter is incorrect.'
Bouncy Castle throws a similar exception.

Is there another PKCS1 Padding with Botan that would be compatible with the one I use with .Net Core?

Thanks for your help.
O. Rouit

**Comment by randombit** [comment]
As far as I understand things "EME-PKCS1-v1_5" in Botan and `Pkcs1` in .NET should be compatible, so I'm not sure what to suggest beyond some basic debugging steps:

* Make sure that the binary values (eg `digestData` and `encrChallenge`) are exactly identical (eg by hashing each with SHA-256 and comparing the hashes). Maybe you have two slightly different versions of base64 and that is causing an issue.

* Try the reverse (encrypting in .NET and decrypting in Botan) - does it work?

**Comment by oliviervibe** [comment]
PLEASE IGNORE THIS ISSUE: I have resolved it and it was not related to a compatibility issue between the 2 libraries.
