### ISSUE TITLE
Linux, OSX: linker error Undefined symbols Botan::Decompression_Filter::Decompression_Filter

### ISSUE THREAD

**Issue by matejk** [randombit/botan#304]
botan 1.11.21

Stripped down code that doesn't link:
```
Botan::Pipe pipe;
pipe.append(new Botan::Decompression_Filter("lzma", m_bufferSize));
pipe.append(new Botan::DataSink_Stream(output));
```

Compression links and works:
```
Botan::Pipe pipe;
pipe.append(new Botan::Compression_Filter("lzma", m_compressionLevel, m_bufferSize));
pipe.append(new Botan::DataSink_Stream(output));
```

When creating a pipe to decompress data, linker reports error that ctor of Decompression_Filter is undefined. The same problem happens on Ubuntu 15.04 (64-bit) and OSX 10.11 (Xcode 7):
```
Undefined symbols for architecture x86_64:
  "Botan::Decompression_Filter::Decompression_Filter(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)", referenced from:
```
Linux:
```
../libclavispacker.so: undefined reference to `Botan::Decompression_Filter::Decompression_Filter(std::string const&, unsigned long)'
```
Compression_Filter is used in the same source code and it links and runs fine.

I inspected object files and the library with objdump.

Decompression_Filter symbols are present in the object file build/obj/lib/filters_comp_filter.o. They are definitely missing in the shared library.

**Comment by randombit** [comment]
The Decompression_Filter was missing the BOTAN_DLL macro so was not being exported by the shared library. Can you try e607a5d and see if your code works?

**Comment by matejk** [comment]
Thank you very much. I'll try it ASAP.

I was looking at that part of the code and didn't see that missing export (I guess it was too late :) ).

**Comment by matejk** [comment]
Fix confirmed: compression/decompression with filters works properly.

**Comment by randombit** [comment]
Great. Thanks for the report and followup.
