### ISSUE TITLE
How to quickly customize AES/ECB/pkcs7padding encryption/decryption based on this library?

### ISSUE THREAD

**Issue by cnkjw** [randombit/botan#3042]
Thanks to the developers for this beautiful library, which I think is the best cryptography library implemented in C++. Unfortunately, the latest version of botan removes support for ECB mode. 

I know very little about cryptography and just want to use the ECB mode to generate usable tokens for my spider (so I don't need to consider the security of the ECB mode). 

I would like to ask how to implement ECB mode encryption/decryption by myself based on this library. 

Also, I tried to use a lower version of botan, but it did not compile successfully on windows using GCC. 

Thanks!

**Comment by randombit** [comment]
You can access ECB mode in a different way, by using the `BlockCipher` API directly. In particular `encrypt_n` and `decrypt_n` are (basically) ECB mode, and are the functions used to implement higher level operations like CBC, GCM, etc. You will have to implement any padding/unpadding yourself though.
