### ISSUE TITLE
TLS intermediate certificate - where to load?

### ISSUE THREAD

**Issue by tzimmer63** [randombit/botan#3044]
Hi,
I've built a working https server with Botan, but I'm only getting a B rating on ssllabs tests because the intermediate certificate is missing in the chain. Can someone give me an advice how and where to load it? The server cert and key is loaded and all is working well, except the missing intermediate cert.
Thanks in advance,
Thomas

**Comment by reneme** [comment]
You probably want to override the method [`Credentials_Manager::find_cert_chain()`](https://botan.randombit.net/doxygen/classBotan_1_1Credentials__Manager.html#aa01ef27a0e5927cdde6602a8806fc5f4). That method returns a `std::vector<X509_Certificate>` which should contain the certificate chain ordered from leaf to root. (Usually, root can be left out.)
