### ISSUE TITLE
build 2.19.1 with old gcc

### ISSUE THREAD

**Issue by BrooklynBoy21** [randombit/botan#3055]
Hi, I faced a problem building amalgamation 2.19.1 with gcc 4.7.3.
Could you say what is the oldest version of botan to be able to build with gcc 4.7.3?

thanks

**Comment by lieser** [comment]
You could try the 1.11.34 or 1.10.17 version. For all 2.x versions the minimum GCC version is 4.8.

Note that usage of this versions is not recommended. They did not get any security fixes for multiple years now.

**Comment by lieser** [comment]
As you haven't replied yet I'm assuming your questions are answered. If not please reopen the issue.
