### ISSUE TITLE
Handle LGTM shutdown

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3068]
Just learned LGTM is shutting down December 16th, replaced by some Github integration https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

**Comment by lieser** [comment]
Do we intend to track here also the adding of an alternative (e.g. GitHub code scanning), or can this be closed?

**Comment by randombit** [comment]
#3663

**Comment by randombit** [comment]
Closing since lgtm support is removed and we do use codeql though I suspect wecould benefit from some configuation changes
