### ISSUE TITLE
Handle GitHub Actions deprecations

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3074]
GitHub Actions will remove support for the 'save-state' and 'set-output' commands in May 2023: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

[`ubuntu-latest` will soon be Ubuntu 22.04](https://github.com/actions/runner-images/issues/6399) same as [`macos-latest` becoming macOS 12](https://github.com/actions/runner-images/issues/6384).

Actions based on Node.js 12 are being phased out until summer 2023: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
For us this seems to affect the `actions/cache@v2` action.

Support for the Ubuntu 18.04 image will end in April 2023: https://github.com/actions/runner-images/issues/6002

**Comment by randombit** [comment]
I believe all issues raised in this ticket are now addressed on master

**Comment by randombit** [comment]
Closing as completed
