### ISSUE TITLE
Discussion: Should 3.0 be C++20 instead of C++17?

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3080]
The choice of C++17 was made when `master` "forked" from the 2.x codebase. The expectation at the time was that 3.0 was going to come out towards the end of 2020 (sigh), at which point using a minimum compiler version of GCC 9, Clang 7, or MSVC 2019 seemed reasonable. At this point however, we may want to consider fixing 3.0 at C++20 instead.

Per the compiler support table on https://en.cppreference.com/w/cpp/compiler_support this would seem to call for GCC 11, Clang 13 (or so) and MSVC 19.25 (I'm not sure what Visual C++ version that corresponds to, though). All are available in Ubuntu 22 which is an option for CI builds.

3.0 shouldn't require an experimental compiler, or a version that was *just* released, because that makes things complicated. But I don't think we need to support ~3 year old compilers at the outset. Anyone using an older compiler can continue using 2.x since that will continue to be supported wrt bug/security fixes for some time.

cc @reneme @securitykernel

**Comment by reneme** [comment]
Some features in C++20 would certainly bring advantages for the library.
First and foremost (for me), would be `std::span` to get rid of (or at least complement) all those C-Style buffer handling APIs (i.e. `::update(const uint8_t* data, const size_t length)`).
Both internally (I would have loved to have it for the TLS implementation) and externally.

+1 from me for that idea.

**Comment by randombit** [comment]
Yes `std::span` would particularly be nice. I'm not sure we could adopt it everywhere in the public APIs simply because that would be a huge breaking change for callers, but we could certainly use it internally, and offer `span`-based API alternatives where reasonable.

Also there are several C++20 `std` library offerings that could potentially replace code that is currently handwritten for the library (barriers, latches, calendar calculations, UTF-8 handling, ...) - anything that removes utility code that's not a core competency of the library is worthwhile.

**Comment by randombit** [comment]
GH #3086

**Comment by randombit** [comment]
In #3086 I set our minimum Clang to 14 since that's whats in Ubuntu 22.04 and realistically we will inevitably break on a older version of Clang that we're not testing with.

**Comment by randombit** [comment]
Switched to C++20 :rocket:
