### ISSUE TITLE
Compile cpp failed if static-linking

### ISSUE THREAD

**Issue by cnbatch** [randombit/botan#3085]
Botan version 2.17.3, installed by Debian 11's apt.
(I've also tried to manually build 2.9.0 and 2.19.3, results are the same — failed)

C++ source code file `aes.cpp`:
```
#include <botan/botan.h>
#include <botan/gcm.h>
#include <botan/hex.h>

#include <iostream>

int main() {
  std::vector<uint8_t> key =
      Botan::hex_decode("000102030405060708090A0B0C0D0E0F101112131415161718191A1B1C1D1E1F");
  std::vector<uint8_t> block = Botan::hex_decode("00112233445566778899AABBCCDDEEFF");
  std::unique_ptr<Botan::BlockCipher> cipher(Botan::BlockCipher::create("AES-256"));
  cipher->set_key(key);
  cipher->encrypt(block);
  std::cout << std::endl << cipher->name() << "single block encrypt: " << Botan::hex_encode(block);

  // clear cipher for 2nd encryption with other key
  cipher->clear();
  key = Botan::hex_decode("1337133713371337133713371337133713371337133713371337133713371337");
  cipher->set_key(key);
  cipher->encrypt(block);

  std::cout << std::endl << cipher->name() << "single block encrypt: " << Botan::hex_encode(block);
  return 0;
}
```

compile option 1: `c++ -I/usr/include/botan-2 -lstdc++ -lbotan-2 -lpthread aes.cpp`
or  `c++ -I/usr/include/botan-2 -lstdc++ -lbotan-2 -lpthread -D_GLIBCXX_USE_CXX11_ABI=1 aes.cpp `
Output:
> In file included from /usr/include/botan-2/botan/botan.h:19,
>                  from aes.cpp:1:
> /usr/include/botan-2/botan/lookup.h:35:13: warning: this header is deprecated
>    35 | BOTAN_DEPRECATED_HEADER(lookup.h)
>       |             ^~~~~~~~~~~~~~~~~~~~~      
> In file included from /usr/include/botan-2/botan/botan.h:21,
>                  from aes.cpp:1:
> /usr/include/botan-2/botan/parsing.h:20:13: warning: this header will be made internal in the future
>    20 | BOTAN_FUTURE_INTERNAL_HEADER(parsing.h)
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~                      
> In file included from /usr/include/botan-2/botan/botan.h:22,
>                  from aes.cpp:1:
> /usr/include/botan-2/botan/init.h:16:13: warning: this header is deprecated
>    16 | BOTAN_DEPRECATED_HEADER(init.h)
>       |             ^~~~~~~~~~~~~~~~~~~        
> In file included from aes.cpp:1:
> /usr/include/botan-2/botan/botan.h:39:13: warning: this header is deprecated
>    39 | BOTAN_DEPRECATED_HEADER(botan.h)
>       |             ^~~~~~~~~~~~~~~~~~~~       
> In file included from aes.cpp:2:
> /usr/include/botan-2/botan/gcm.h:15:13: warning: this header will be made internal in the future
>    15 | BOTAN_FUTURE_INTERNAL_HEADER(gcm.h)
>       |             ^~~~~~~~~~~~~~~~~~~~~~~                          
> /usr/bin/ld: /tmp/ccPIRDaZ.o: in function 'main':
> aes.cpp:(.text+0x52): undefined reference to 'Botan::hex_decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
> /usr/bin/ld: aes.cpp:(.text+0xba): undefined reference to 'Botan::hex_decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
> /usr/bin/ld: aes.cpp:(.text+0x150): undefined reference to 'Botan::BlockCipher::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /usr/bin/ld: aes.cpp:(.text+0x2e3): undefined reference to 'Botan::hex_decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
> /usr/bin/ld: /tmp/ccPIRDaZ.o: in function 'void Botan::SymmetricAlgorithm::set_key<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&)':
> aes.cpp:(.text._ZN5Botan18SymmetricAlgorithm7set_keyISaIhEEEvRKSt6vectorIhT_E[_ZN5Botan18SymmetricAlgorithm7set_keyISaIhEEEvRKSt6vectorIhT_E]+0x3d): undefined reference to 'Botan::SymmetricAlgorithm::set_key(unsigned char const*, unsigned long)'
> /usr/bin/ld: /tmp/ccPIRDaZ.o: in function 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Botan::hex_encode<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool)':
> aes.cpp:(.text._ZN5Botan10hex_encodeISaIhEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIhT_Eb[_ZN5Botan10hex_encodeISaIhEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIhT_Eb]+0x47): undefined reference to 'Botan::hex_encode[abi:cxx11](unsigned char const*, unsigned long, bool)'
> collect2: error: ld returned 1 exit status

compile option 2: `c++ -I/usr/include/botan-2 -lstdc++ -lbotan-2 -lpthread -D_GLIBCXX_USE_CXX11_ABI=0 aes.cpp`
Output:

> In file included from /usr/include/botan-2/botan/botan.h:19,
>                  from aes.cpp:1:
> /usr/include/botan-2/botan/lookup.h:35:13: warning: this header is deprecated
>    35 | BOTAN_DEPRECATED_HEADER(lookup.h)
>       |             ^~~~~~~~~~~~~~~~~~~~~      
> In file included from /usr/include/botan-2/botan/botan.h:21,
>                  from aes.cpp:1:
> /usr/include/botan-2/botan/parsing.h:20:13: warning: this header will be made internal in the future
>    20 | BOTAN_FUTURE_INTERNAL_HEADER(parsing.h)
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~                      
> In file included from /usr/include/botan-2/botan/botan.h:22,
>                  from aes.cpp:1:
> /usr/include/botan-2/botan/init.h:16:13: warning: this header is deprecated
>    16 | BOTAN_DEPRECATED_HEADER(init.h)
>       |             ^~~~~~~~~~~~~~~~~~~        
> In file included from aes.cpp:1:
> /usr/include/botan-2/botan/botan.h:39:13: warning: this header is deprecated
>    39 | BOTAN_DEPRECATED_HEADER(botan.h)
>       |             ^~~~~~~~~~~~~~~~~~~~       
> In file included from aes.cpp:2:
> /usr/include/botan-2/botan/gcm.h:15:13: warning: this header will be made internal in the future
>    15 | BOTAN_FUTURE_INTERNAL_HEADER(gcm.h)
>       |             ^~~~~~~~~~~~~~~~~~~~~~~                          
> /usr/bin/ld: /tmp/ccUe34op.o: in function 'main':
> aes.cpp:(.text+0x52): undefined reference to 'Botan::hex_decode(std::string const&, bool)'
> /usr/bin/ld: aes.cpp:(.text+0xba): undefined reference to 'Botan::hex_decode(std::string const&, bool)'
> /usr/bin/ld: aes.cpp:(.text+0x138): undefined reference to 'Botan::BlockCipher::create(std::string const&, std::string const&)'
> /usr/bin/ld: aes.cpp:(.text+0x2aa): undefined reference to 'Botan::hex_decode(std::string const&, bool)'
> /usr/bin/ld: /tmp/ccUe34op.o: in function 'void Botan::SymmetricAlgorithm::set_key<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&)':
> aes.cpp:(.text._ZN5Botan18SymmetricAlgorithm7set_keyISaIhEEEvRKSt6vectorIhT_E[_ZN5Botan18SymmetricAlgorithm7set_keyISaIhEEEvRKSt6vectorIhT_E]+0x3d): undefined reference to 'Botan::SymmetricAlgorithm::set_key(unsigned char const*, unsigned long)'
> /usr/bin/ld: /tmp/ccUe34op.o: in function 'std::string Botan::hex_encode<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&, bool)':
> aes.cpp:(.text._ZN5Botan10hex_encodeISaIhEEESsRKSt6vectorIhT_Eb[_ZN5Botan10hex_encodeISaIhEEESsRKSt6vectorIhT_Eb]+0x47): undefined reference to 'Botan::hex_encode(unsigned char const*, unsigned long, bool)'
> collect2: error: ld returned 1 exit status

How to solve those 'undefined reference' issue?

**Comment by randombit** [comment]
The GNU linker is single pass, so it only adds symbols that are missing if a previously seen object referenced that symbol. Change this:

` c++ -I/usr/include/botan-2 -lstdc++ -lbotan-2 -lpthread -D_GLIBCXX_USE_CXX11_ABI=1 aes.cpp `

to this

` c++ -I/usr/include/botan-2 -lstdc++ -lpthread -D_GLIBCXX_USE_CXX11_ABI=1 aes.cpp -lbotan-2`

This works with dynamic linking because then the linker always adds the reference to the shared object and it is able to be found at runtime.

**Comment by cnbatch** [comment]
Thanks for your answer. I've created multiple binaries with multiple versions of Botan and distribute them to multiple version's Linux user.
It's a troublesome experience.

Botan can be statically linked on FreeBSD (with clang) and Windows (with MSVC), how to make static linking works on Linux?

**Comment by randombit** [comment]
Did the above invocation not resolve the issue?

**Comment by cnbatch** [comment]
No.

I solved the issue by using botan_all.h and botan_all.cpp, if the target platform uses GNU Toolchains.
