### ISSUE TITLE
Implement SPHINCS+

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3099]
Hash based signatures are great but the stateful nature of XMSS is a real footgun and difficult operationally.

**Comment by securitykernel** [comment]
An implementation is planned during [BSI](https://www.bsi.bund.de/EN) project 481.
 Preliminary schedule for the implementation is Mar '23 - May '23.

**Comment by securitykernel** [comment]
Updated schedule for the implementation is May '23 - July '23.
