### ISSUE TITLE
Cipher_Mode class (cipher_mode.h) is used polymorphically but does not have virtual destructor.

### ISSUE THREAD

**Issue by gokhangg** [randombit/botan#3104]
Cipher_Mode class (cipher_mode.h) is used polymorphically but does not have virtual destructor. I have checked the implementation classes and they have several members. So as instantiated objects are allocated dynamically this may cause leakage. I have  not checked other interface classes but this may be true for others too.

**Comment by randombit** [comment]
`Cipher_Mode` derives from `SymmetricAlgorithm` which does have a virtual destructor

**Comment by gokhangg** [comment]
Ah yeah I see thanks for the quick reply.
