### ISSUE TITLE
Implement LMS

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3105]
We will implement LMS from [NIST SP 800-208](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-208.pdf) during the [BSI](https://www.bsi.bund.de/EN) Project 481.

~~Preliminary schedule for the implementation is Jun '23 - Aug '23.~~

Updated schedule below due to slight project plan rescheduling.

**Comment by securitykernel** [comment]
Updated schedule for the implementation is Aug '23 - Oct '23.

**Comment by randombit** [comment]
Merged for 3.5.0 :tada:
