### ISSUE TITLE
Implement Classic McEliece

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3107]
We will implement [NIST PQC contest round 4](https://csrc.nist.gov/News/2022/pqc-candidates-to-be-standardized-and-round-4) KEM submission [Classic McEliece](https://classic.mceliece.org/) during the [BSI](https://www.bsi.bund.de/EN) Project 481.

~Preliminary schedule for the implementation is Nov '23 - Jan '24.~

Updated schedule below due to slight project plan rescheduling.

**Comment by securitykernel** [comment]
Updated schedule for the implementation is Dec '23 - Mar '24.

**Comment by reneme** [comment]
Done: #3883
