### ISSUE TITLE
New to Botan ECDSA

### ISSUE THREAD

**Issue by jhfigueiredo** [randombit/botan#3137]
I'm relatively new to Botan and I'm having some difficulty understanding how to use the ECDSA features specifically for my use case, with the following settings:

"PrivKey": "418073C239FA6125011DE4D6CD2E645780289F761BB21BFB0835CB5585E8B373",
"PubKey": "BAAFFDE06A8CB1C9DAE8D94023C601DBBB249254BA22EDD827E820BCA2BCC64362FBB83D86A82B87BB8B7161D2AAB5521911A946B97A284A90F7785CD9047D25"

ASN1 OID: prime256v1 
NIST CURVE: P-256 

Should I use:
**Botan::ECDSA_PrivateKey::ECDSA_PrivateKey(const AlgorithmIdentifier &  alg_id, const secure_vector< uint8_t > & key_bits)**
with the supplied private key? How? I've tried supplying the key to the key_bits attribute in diferent formats unsuccessfully.

Any help will be apreciated.

**Comment by reneme** [comment]
Your private key is simply the private value but the constructor you're referring to expects the key in DER format. Using the respective [constructor from the base class](https://github.com/randombit/botan/blob/master/src/lib/pubkey/ecc_key/ecc_key.h#L140-L151) should work:

```c++
  Botan::AutoSeeded_RNG rng;
  Botan::ECDSA_PrivateKey key(
   rng,
   Botan::EC_Group("secp256r1"),
   Botan::BigInt(Botan::hex_decode_locked("418073C239FA6125011DE4D6CD2E645780289F761BB21BFB0835CB5585E8B373")));
```

**Comment by jhfigueiredo** [comment]
Thanks René.
How do I set up the public key for verification when I have the public key in this format:
"PubKey": "BAAFFDE06A8CB1C9DAE8D94023C601DBBB249254BA22EDD827E820BCA2BCC64362FBB83D86A82B87BB8B7161D2AAB5521911A946B97A284A90F7785CD9047D25"

The ECDSA_PublicKey doesn't have a similar constructor.

**Comment by reneme** [comment]
The encoding of your public key is somewhat non-standard. It seems to me, that it is simply the concatenated EC point coordinates. Here's an example that reads your private and public key with (low-level) library functionality and signs/verifies a test message. I hope this is helpful.

```C++
#include <botan/auto_rng.h>
#include <botan/ec_group.h>
#include <botan/ecdsa.h>
#include <botan/hex.h>
#include <botan/pubkey.h>

#include <iostream>

int main() {
   Botan::AutoSeeded_RNG rng;

   const Botan::EC_Group group("secp256r1");

   Botan::ECDSA_PrivateKey privkey(
      rng,
      group,
      Botan::BigInt(Botan::hex_decode_locked("418073C239FA6125011DE4D6CD2E645780289F761BB21BFB0835CB5585E8B373")));

   const auto pubkey_encoded = Botan::hex_decode("BAAFFDE06A8CB1C9DAE8D94023C601DBBB249254BA22EDD827E820BCA2BCC64362FBB83D86A82B87BB8B7161D2AAB5521911A946B97A284A90F7785CD9047D25");

   BOTAN_ASSERT_NOMSG(pubkey_encoded.size() % 2 == 0);
   const auto point_length = pubkey_encoded.size() / 2;
   const auto x = Botan::BigInt::decode(pubkey_encoded.data(), point_length);
   const auto y = Botan::BigInt::decode(pubkey_encoded.data() + point_length, point_length);

   Botan::ECDSA_PublicKey pubkey(group, group.point(x, y));

   std::string text("This is a tasty burger!");
   std::vector<uint8_t> data(text.data(), text.data() + text.length());

   // sign data
   Botan::PK_Signer signer(privkey, rng, "EMSA1(SHA-256)");
   signer.update(data);
   std::vector<uint8_t> signature = signer.signature(rng);
   std::cout << "Signature:" << std::endl << Botan::hex_encode(signature);

   // verify signature
   Botan::PK_Verifier verifier(pubkey, "EMSA1(SHA-256)");
   verifier.update(data);
   std::cout << std::endl << "is " << (verifier.check_signature(signature) ? "valid" : "invalid") << std::endl;

   return 0;
}
```

To fix your encoding, you might add a single byte '0x04' at the beginning of the public key to obtain the so-called "uncompressed" EC point encoding that is widely used. Then the parsing code becomes somewhat simpler as:

```C++
const auto pubkey_encoded = Botan::hex_decode("04BAAFFDE06A8CB1C9DAE8D94023C601DBBB249254BA22EDD827E820BCA2BCC64362FBB83D86A82B87BB8B7161D2AAB5521911A946B97A284A90F7785CD9047D25");
   Botan::ECDSA_PublicKey pubkey(group, group.OS2ECP(pubkey_encoded));
```

@randombit Am I missing a more user-friendly API for this? And if not: should we add one?

**Comment by randombit** [comment]
I don't think there is anything friendlier than what you posted, but that's partially because this key does seem very unusual. I've never seen any system that encodes ECC points without a compressed/uncompressed marker byte, that's been standard for ECC since at least SEC1 which came out in 2000.

@jhfigueiredo can you explain a bit was to how you generated the key you are trying to parse here?

**Comment by jhfigueiredo** [comment]
Thank you @reneme so much for your precious help. 
@randombit, I didn't generate these keys. They are supplied as is by the client for this specific implementation. But I can follow @reneme suggestion and add the extra byte at the beginning.

Once again thank you both for the help.
