### ISSUE TITLE
openssl failed to verify RSA signature

### ISSUE THREAD

**Issue by BrooklynBoy21** [randombit/botan#3153]
The problem I faced is that openssl couldn't verify the signature generated with botan. I have generated RSA key pair and used it this way:
```
Botan::PK_Signer signer(*rsa, rng, "EMSA4(SHA-256)", Botan::IEEE_1363);
signer.update(data);
std::vector<uint8_t> signature = signer.signature(rng);
```

In order to verify I used the next command:
`openssl dgst -sha256 -verify pub_key.pem -signature signature.txt data.txt`

Is botan signature algorithm compatible with openssl?

**Comment by randombit** [comment]
I think `openssl dgst` assumes PKCSv1.5 which you can producing using `"PKCS1v15(SHA-256)"`. Alternately you can tell openssl to use PSS padding using [some PSS specific options](https://stackoverflow.com/questions/44428095/how-to-verify-signature-with-pss-padding)

**Comment by BrooklynBoy21** [comment]
@randombit Indeed, "PKCS1v15(SHA-256)" did its job and I was able to verify the signature with `openssl dgst` command. 
Thank you!

Unfortunately, it still doesn't work with cms document.
