### ISSUE TITLE
Always scaling GCM update granularity causes issues with non-ffi use

### ISSUE THREAD

**Issue by novasharper** [randombit/botan#3163]
Since the block size is 16 bytes, the size of the (un)encrypted data is not guaranteed to be a multiple of 64 bytes. For example, the size of the encrypted data in a password-protected ssh private key is only guaranteed to be a multiple of 16 bytes.

**Comment by novasharper** [comment]
Looking at how `botan_cipher_update` does
```c++
const size_t ud = cipher.update_granularity();
BOTAN_ASSERT(cipher.update_granularity() > cipher.minimum_final_size(), "logic error");
mbuf.resize(ud);
```
would it make sense to instead do
```c++
const size_t ud = cipher.update_granularity();
size_t buf_size = std::max<size_T>(cipher.update_granularity(), cipher.minimum_final_size());
mbuf.resize(buf_size);
```

**Comment by randombit** [comment]
@novasharper Do you think #3168 resolves this for you?

Another question is, assuming #3168 resolves things, are you in desperate need of this to be backported to the 2.x release branches or are you willing/able to wait a few months for 3.0 to be released?

**Comment by novasharper** [comment]
I need to try building against 3.0, but #3168  should resolve this. My need for this is not urgent. I can just use an alternate cipher until 3.0 is released. I had just noticed the issue and figured that I would bring it up and try to create a fix for it.
