### ISSUE TITLE
Using Dilithium as PKI Signer Algo.

### ISSUE THREAD

**Issue by obalak** [randombit/botan#3208]
To generate a self signed root CA for PSQ PKI, I tried the following:

`botan keygen --algo=Dilithium --params=Dilithium-AES-r3/6x5 --passphrase=xxxx --pbe= --pbe-millis=300 --provider= > ~/tmp/rootca_key.pem`

Which generates correctly the key. Then I generate the root CA certificate with the following:

`botan gen_self_signed ~/tmp/rootca_key.pem "My Root CA" --country=CH --dns=cloud.xxxx.ch --organization=xxxx --email=info@xxxx.ch --path-limit=1 --days=7300  --key-pass=xxxx --ca  --hash=SHA-512 --emsa= > ~/tmp/rootca_crt.pem`

The certificate is not generated and an error is issued:
`Error: Unknown X.509 signing key type: Dilithium-AES-r3/6x5`

I checked the source code and find out that the algorithm is not yet supported.
When do you think this will be supported? Or do you recommend other approaches?

**Comment by randombit** [comment]
We should support this if we can and I believe we already have everything needed to make it work (SPKI encodings, etc) it probably just requires a bit of glue so the X.509 handling code knows what to do.

**Comment by obalak** [comment]
Thanks. Waiting for the alpha1 to test.

**Comment by reneme** [comment]
This should now work as expected. Be aware that the algorithm name changed from "Dilithium-AES-r3/6x5" to "Dilithium-6x5-AES-r3". The slash in the old name had an internal semantic in the X.509 code that made this change necessary.

Feel free to test it with the latest master commit and re-open if you still run into issues.

**Comment by obalak** [comment]
It is working fine now with the fixed scheme name for all botan main PKI operations except for certificate verification.

`/usr/local/bin/botan cert_verify ~/build/pkigen/certs/entity_crt.pem ~/build/pkigen/certs/subca_crt.pem ~/build/pkigen/certs/rootca_crt.pem
Error: Internal error: Invalid name format found for 1.3.6.1.4.1.25258.1.10.2
`
It should be related to the name of the signature algorithm ASN.1.

result of : `botan cert_info --fingerprint certs/entity_crt.pem ` is 
`
Signature algorithm: Dilithium-6x5-AES-r3
...
Public Key [Dilithium-6x5-AES-r3-1952]
`
Let me know if you need help to have a makefile to generate all the test material.
I'm testing on RockyLinux 9.1 in docker.

**Comment by obalak** [comment]
I don't know if it is helpful or not, I added a specific test for sig_info first element content if it start or not with "Dilithium-" as follows in 

````
/*
* Return the hash used in generating the signature
*/
std::string X509_Object::hash_used_for_signature() const
   {
   const OID& oid = m_sig_algo.get_oid();
   const std::vector<std::string> sig_info = split_on(oid.to_formatted_string(), '/');

   if(sig_info.size() == 1 && sig_info[0] == "Ed25519")
      return "SHA-512";
   
    if(sig_info.size() == 1 && **sig_info[0].starts_with("Dilithium-")**)
      return "SHA-512";`

```
The certificate signature check passes.

```
botan cert_verify ~/build/pkigen/certs/entity_crt.pem ~/build/pkigen/certs/subca_crt.pem ~/build/pkigen/certs/rootca_crt.pem
Certificate passes validation checks
```

**Comment by reneme** [comment]
That's pretty much what I did in https://github.com/randombit/botan/pull/3223 😁 Just reporting `SHAKE-256(512)`, as that's whats used in Dilithium. By default `SHAKE-256(512)` isn't trusted though, so I needed to add this as well.

I'm somewhat on the fence whether that's a sustainable solution, though. Let's have the discussion in the Pull Request, I'll write something up.

**Comment by reneme** [comment]
Next try! 😄

Thanks a lot for testing this and bringing the issues to our attention. That helped a lot!

**Comment by obalak** [comment]
Thanks to all the team. You are doing a great job. :-)
I tested now from the master and it is working as expected.
