### ISSUE TITLE
verify_certificate_chain should throw on any error

### ISSUE THREAD

**Issue by louiz** [randombit/botan#323]
I believe Credential_Manager::verify_certificate_chain() should throw if an error is reported by x509_path_validate, right?

For example if `Credentials_Manager::verify_certificate_chain(…, "WRONG-HOSTNAME-for-test-purpose", …);` is called, it doesn’t throw anything (although the error (CERT_NAME_NOMATCH) is detected and set in the Path_Validation_Result object returned by x509_path_validate), and thus the user thinks the certificate is valid.

Maybe I’m wrong and this error should be signaled an other way to the user (but I’m not aware of it, and maybe this should be better documented). But if I’m not wrong, then a handful of errors are currently ignored.

**Comment by louiz** [comment]
I made a pull request #324 with a simple fix to explain more clearly the issue.

**Comment by randombit** [comment]
You're right, it looks like the relevant lines were accidentally removed in 1.11.22 in the patch fixing other certificate validation bypass issues.

**Comment by randombit** [comment]
Fixed in the 1.11.24 release (today). Thank you for the report.
