### ISSUE TITLE
botan website appears to be down?

### ISSUE THREAD

**Issue by alex** [randombit/botan#3249]
Accessing https://botan.randombit.net/ produces "ERR_SSL_VERSION_OR_CIPHER_MISMATCH". Accessing via HTTP shows a redirect to HTTPS (as expected).

**Comment by randombit** [comment]
It appears the most recent certbot renewal switched us from an RSA cert to an ECDSA cert. There was an explicitly approved list of TLS ciphersuites that included only RSA signatures, so nginx couldn't figure out what suite to use.

I'm not sure why certbot did this. The [announcement of ECDSA cert support](https://community.letsencrypt.org/t/ecdsa-certificates-by-default-and-other-upcoming-changes-in-certbot-2-0/177013/9) says that existing RSA keys are kept as is, and I don't find any followup post indicating that existing RSA keys were going to be replaced with ECDSA.

Anyway thanks for reporting, removing the ciphersuite preferences and restarting nginx seems to have resolved it.

**Comment by alex** [comment]
Thanks!
