### ISSUE TITLE
Server_Hello_13 invokes virtual function during construction

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3285]
Flagged by clang-tidy

```
src/lib/tls/msg_server_hello.cpp:607:7: warning: Call to virtual method 'Server_Hello_13::selected_version' during construction bypasses virtual d\
ispatch [clang-analyzer-optin.cplusplus.VirtualCall]
   if(selected_version() != Protocol_Version::TLS_V13)
      ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:543:7: note: Assuming the condition is false
   if(version.is_pre_tls_13())
      ^~~~~~~~~~~~~~~~~~~~~~~
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:543:4: note: Taking false branch
   if(version.is_pre_tls_13())
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:547:4: note: Taking true branch
   if(version == Protocol_Version::TLS_V13)
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:549:10: note: Assuming field 'is_hello_retry_request' is false
      if(data->is_hello_retry_request)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:549:7: note: Taking false branch
      if(data->is_hello_retry_request)
      ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:552:14: note: Calling constructor for 'Server_Hello_13'
      return Server_Hello_13(std::move(data));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:617:32: note: Field 'is_hello_retry_request' is false
   BOTAN_ASSERT_NOMSG(!m_data->is_hello_retry_request);
                               ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:617:4: note: Taking false branch
   BOTAN_ASSERT_NOMSG(!m_data->is_hello_retry_request);
   ^
build/include/botan/assert.h:69:7: note: expanded from macro 'BOTAN_ASSERT_NOMSG'
      if(!(expr))                                         \
      ^
   BOTAN_ASSERT_NOMSG(!m_data->is_hello_retry_request);
   ^
build/include/botan/assert.h:68:4: note: expanded from macro 'BOTAN_ASSERT_NOMSG'
   do {                                                   \
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:618:4: note: Calling 'Server_Hello_13::basic_validation'
   basic_validation();
   ^~~~~~~~~~~~~~~~~~
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:564:4: note: Taking false branch
   BOTAN_ASSERT_NOMSG(m_data->version() == Protocol_Version::TLS_V13);
   ^
build/include/botan/assert.h:69:7: note: expanded from macro 'BOTAN_ASSERT_NOMSG'
      if(!(expr))                                         \
      ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:564:4: note: Loop condition is false.  Exiting loop
   BOTAN_ASSERT_NOMSG(m_data->version() == Protocol_Version::TLS_V13);
   ^
build/include/botan/assert.h:68:4: note: expanded from macro 'BOTAN_ASSERT_NOMSG'
   do {                                                   \
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:582:4: note: Taking false branch
   if(legacy_version() != Protocol_Version::TLS_V12)
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:590:7: note: Assuming the condition is false
   if(compression_method() != 0x00)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:590:4: note: Taking false branch
   if(compression_method() != 0x00)
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:597:4: note: Taking false branch
   if(!extensions().has<Supported_Versions>())
   ^
/home/jack/work/botan/src/lib/tls/msg_server_hello.cpp:607:7: note: Call to virtual method 'Server_Hello_13::selected_version' during construction\
 bypasses virtual dispatch
   if(selected_version() != Protocol_Version::TLS_V13)
      ^~~~~~~~~~~~~~~~~~
```

cc @reneme not sure if this is a problem or not

**Comment by reneme** [comment]
No, not a problem. It's virtual because the version negotiation changed from TLS 1.2 to 1.3 (introduction of the "support_versions" extension). At this point we're sure that we deal with a TLS 1.3 server hello (otherwise `Server_Hello_12` would have been instantiated). This check just makes sure that the "selected version" extension actually _selected_ TLS 1.3.

Anyway, I could look into avoiding this. Or would we opt to ignore such a thing with an annotation? Personally, I'm not a big fan of changing a valid program structure that follows the "least surprise" principle to please the tool.

**Comment by randombit** [comment]
You can use [annotations](https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html#suppressing-undesired-diagnostics) to disable warnings on specific lines but I would prefer doing so only if really necessary.

Actually, IIUC we can avoid this warning by just making `Server_Hello_13` `final`, which it probably should be *anyway*.

**Comment by randombit** [comment]
BTW I will go ahead and quote the [project goals](https://github.com/randombit/botan/blob/master/doc/goals.rst) which still captures my overall feeling on the issue

> Within reason, all warnings from compilers and static analyzers should be addressed, even if they seem like false positives, because that maximizes the signal value of new warnings from the tool.

In this specific case we have multiple possible paths. Ordered basically by order of preference:

1) Fix the warning with a simple change (eg `final`, if that works)
2) Ignore the warning for this specific case, adding a comment why it is being disabled here
3) Perform some contorted change that makes the logic difficult to understand
4) Disable the warning globally in our clang-tidy config

**Comment by randombit** [comment]
Turns out `Server_Hello_13` is further derived from, but we can make `selected_version` function `final` which suffices for Clang to know that there is not a problem.

**Comment by randombit** [comment]
Fixed now

**Comment by reneme** [comment]
Nice! Making this method `final` sounds like a very valid fix for the warning. Thanks for looking into it.

(I agree with your view on handling such warnings, by the way. Particularly that the *concious* decision to spot-ignore warnings comes before making contrived changes to work around them. Thanks for making your views clear on that.)
