### ISSUE TITLE
botan/rsa.h cannot be used with -Wpedantic

### ISSUE THREAD

**Issue by cordney** [randombit/botan#330]
We compile our code with `-Wpedantic -Werror`, but currently cannot, because when including `<botan/rsa.h>`, we get a compiler warning with gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2). Tested against current master.

The following test program reproduces the error:

```
#include <botan/rsa.h>

int main()
{
    return 0;
}
```

```
$ g++ mul.cxx -o mul -I/usr/local/include/botan-1.11 -std=c++11 -Wpedantic -Werror
In file included from /usr/local/include/botan-1.11/botan/mp_types.h:12:0,
                 from /usr/local/include/botan-1.11/botan/bigint.h:14,
                 from /usr/local/include/botan-1.11/botan/if_algo.h:11,
                 from /usr/local/include/botan-1.11/botan/rsa.h:11,
                 from mul.cxx:1:
/usr/local/include/botan-1.11/botan/mul128.h:17:30: error: ISO C++ does not support ‘__int128’ for ‘uint128_t’ [-Werror=pedantic]
    typedef unsigned __int128 uint128_t;
                              ^
cc1plus: all warnings being treated as errors
```

**Comment by webmaster128** [comment]
Adding ` -U__SIZEOF_INT128__` causes the code to compile. But I cannot tell what consequences this has for your performance. Could you provide data here?

**Comment by randombit** [comment]
It looks like GCC 5.2 at least rejects __int128 but still accepts the TI attribute variant  in pedanatic mode. That mode is what is used when __SIZEOF_INT128__ is not defined, at least for 64 bit (but I think 32-bit systems don't have __int128 either). Unfortunately even setting `-pedantic` leaves the sizeof macro defined. Swapping the two clauses so TI is preferred looks to resolve the issue as it looks like Clang is fine with both _int128 and TI even in pedantic mode (tested clang 3.7).

**Comment by randombit** [comment]
@cordney Can you check with latest master? Thanks.

**Comment by cordney** [comment]
I can confirm that the current master works. Thanks a lot!
