### ISSUE TITLE
credits.rst and attributions in license.txt

### ISSUE THREAD

**Issue by tiwoc** [randombit/botan#331]
How are the files [doc/credits.rst](https://github.com/randombit/botan/blob/master/doc/credits.rst) and [doc/license.txt](https://github.com/randombit/botan/blob/master/doc/license.txt) maintained? What is the process to update them? Should every pull request contain a change to these files if applicable?

In any case, the intended process should be documented, probably in `hacking.rst`.

**Comment by randombit** [comment]
Yes they should be updated in the pull request if it is a new year or if the copyright holder changed. The credits file is optional, the license text is not. I'll update hacking to mention this.

**Comment by tiwoc** [comment]
Thanks! I didn't know about these files before, so I never modified them. I submitted a PR just now to add credits: https://github.com/randombit/botan/pull/332
