### ISSUE TITLE
Question: X509_DN rdns ordering

### ISSUE THREAD

**Issue by andreaceccanti** [randombit/botan#336]
Hi,

why the X509_DN class, and in particular the dn_info internal map, does not preserve the order
of the parsed structure  and imposes instead some "arbitrary ordering" on the DN?

Probably this is a dumb question, but how is one supposed to implement the [rfc2253 X509 DN string rendering](https://www.ietf.org/rfc/rfc2253.txt), for instance,  relying only on the X509_DN exposed interface?

Thanks in advance for your help,
A.

**Comment by randombit** [comment]
Yes looking at the code probably having a vector to maintain the ordering would be superior. From my read of the RFC, it sounds like this string rendering is supposed to match the ordering in the DN. If that is the case then for now what you'd have to do is use the escape hatch which is X509_DN::get_bits which returns the bare RDN bits. Then just decode it (effectively copying the ~10 line loop in X509_DN::decode_from), and build up your string repr as you go.

Totally lame on the DN design and I would take a patch to fix it to use a vector instead to maintain the ordering. As the DN is no more than a dozen items anyway using a linear search on lookups is fine, there is no need for the map. But anyway I think the above while ugly will solve your particular problem (assuming I'm understanding it correctly) with only minor annoyance.

**Comment by andreaceccanti** [comment]
> From my read of the RFC, it sounds like this string rendering is supposed to match the ordering in the
> DN.

Exactly, that's the problem. I will try to patch the code to use a vector and see what comes out of it.
Thanks,
A.

**Comment by randombit** [comment]
It took a while but this has been fixed by #1504 now the order of DN entries is exposed to applications.
