### ISSUE TITLE
Use Breathe for API Reference documentation

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3377]
Currently, the documentation in `docs/api_ref` duplicates quite a bit of the API details already documented in Doxygen. This adds a maintenance burden and leads to outdated documentation.

Instead, I propose to use [Breathe](https://breathe.readthedocs.io/en/latest/index.html) for our Sphinx documentation. This allows pulling API documentation from Doxygen into Sphinx documentation.

### Example

Say, I want to describe the mandatory callbacks to be implemented by an application using TLS.

First I would use a [doxygen member group](https://www.doxygen.nl/manual/grouping.html#memgroup) to define the mandatory members in the code.

```C++
namespace Botan::TLS {
class Callbacks {
public:
  /**
   * @name Mandatory
   * Those callbacks must be overridden by all applications wishing to use TLS.
   */
  ///@{
  void tls_emit_data();
  void tls_record_received();
  // ...
  /// @}
};
}
```

Then, [instead of recreating all the information about the callback methods](https://github.com/randombit/botan/blob/b67c32643c1bc2e84896cd43967e087b44149346/doc/api_ref/tls.rst), one would simply add the following in the reStructuredText documentation for Sphinx:

```rST
.. doxygenclass:: Botan::TLS::Callbacks
    :members:
    :membergroups: Mandatory
```

And the result would look like that. Further tuning is possible, of course:

![image](https://user-images.githubusercontent.com/1562139/225262078-128683a5-5e65-4c1c-8341-196f7043954c.png)

**Comment by randombit** [comment]
Sounds good to me

**Comment by randombit** [comment]
It does seem breathe is available in most distros

https://repology.org/project/python:breathe/versions
and
https://repology.org/project/breathe/versions

But the question arises what can/should we do if breathe is not available. Can we proceed with building the docs at that point, in some degraded fashion? Or is there no chance of proceeding?

**Comment by reneme** [comment]
We can detect that breathe is not installed in the system (via `except ImportError` in Sphinx's `conf.py`) and simply not register it as an extension in Sphinx. This will result in warnings during build:

```
doc/api_ref/tls.rst:39: WARNING: Unknown directive type "doxygenclass".

.. doxygenclass:: Botan::TLS::Callbacks
    :members:
    :membergroups: Mandatory
```

and simply leave out the Doxygen information.

Probably, we could even mock breathe's directives in this case and render some "API documentation not available"-warning into the documentation in lieu of the actual breathe output.

Is building the documentation on some restricted platform an actual use case though?

**Comment by reneme** [comment]
By the way, breathe works well with PDF output as well:

![image](https://user-images.githubusercontent.com/1562139/225575878-70462779-8f57-4c9d-aefd-2d23579ce029.png)

**Comment by randombit** [comment]
> Is building the documentation on some restricted platform an actual use case though?

Not really, but it would be nice if the user got basically working documentation even if they don't/can't have this extension installed for whatever reason.

**Comment by reneme** [comment]
## Status Update

I think there's enough progress in converting the API reference to Breathe for today. I split the changes into small PRs (#3470, #3472, #3473, #3474, #3475, #3476, #3477, #3478) to ease the review a bit.

A note on method: I went through the documentation in rST, moved extra detail over to the Doxygen comments where appropriatie and then replaced `.. cpp:function::` with `.. doxygenfunction::` (and friends). In places where the actual API documentation was not front-and-center for the topic, I wrapped it into `.. container:: toggle` to collapse it by default. I feel that makes the documentation much less cluttered for the occasional reader.

At some places  I did find and fix minor documentation errors. Though, generally, these should happen in a separate pass.

## Chapters that still need attention

* Hardware Wrappers
  * [ ] pkcs11.rst
  * [ ] tpm.rst

* Transport Layer Security
  * [ ] credentials_manager.rst
  * [ ] tls.rst
  * [ ] psk_db.rst

* Public Key Infrastructure
  * [ ] pubkey.rst
  * [ ] x509.rst

* Core Functionality
  * [ ] rng.rst
  * [ ] secmem.rst
  
* Misc
  * [ ] fpe.rst
  * [ ] keywrap.rst
  * [ ] otp.rst
  * [ ] roughtime.rst
  * [ ] srp.rst
  * [ ] tss.rst
  * [ ] zfec.rst

* Integrations
  * [ ] ffi.rst
  * [ ] python.rst
  
* Legacy
  * [ ] filters.rst

**Comment by reneme** [comment]
Regardless of using Breathe or not: The current state of the documentation needs some TLC. The currently open (Breathe-related) PRs contain a number of cleanups and fixes to the documentation. If we decide to abandon Breathe, I could pull those out.

Re:togglebutton: I'm sure we'd find a way to make this without the dependency.

Re:Breathe: I must say, I'm quite sad with this situation. I actually do enjoy the way Breathe bridges the gap between rST and Doxygen. Despite the lacking functionality and speed its a great tool, IMO.
What's your general feeling of Breathe's output/functionality @randombit? Do you think its worth investing more time into this?

**Comment by reneme** [comment]
A note on performance: disabling source code listing in the XML output (`XML_PROGRAMLISTING = NO` in `botan.doxy.in`) cuts the size of the generated XML roughly in half. As Breathe's performance issues seem to stem from inefficient parsing, this also drastically speeds up the documentation generation in general. Proper measurements pending.

**Comment by reneme** [comment]
With `XML_PROGRAMLISTING = NO` the performance of Breathe is still not great, but I'd argue its "good enough". In [this little test balloon](https://github.com/randombit/botan/pull/3554) the `docs` CI job ran for about _2 minutes_ (in total with setup) and slightly more than _1 minute_ for the build step alone.

I find that bearable for the convenience it brings. Also, I removed the `sphinx-togglebutton` dependency (by inlining the extension in our repo).

@randombit If we decide to take this further, I'd be glad if we could start reviewing/merging the open PRs to reduce clutter. Otherwise, I'd like to rescue the API documentation fixes in them and then close them.

Unfortunately, there doesn't seem to be a notable alternative to Breathe for our usecase. Except manual sync with the documentation as before or replacing the API docs in Sphinx with links to Doxygen.

**Comment by reneme** [comment]
For the record: @lieser pointed out that people work on a speed improvement for Breathe. https://github.com/breathe-doc/breathe/discussions/962

**Comment by reneme** [comment]
We decided to drop the idea of integrating Breathe. Closing.
