### ISSUE TITLE
MSVC warning C4275

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#340]
Hi,

Building my application generates a lot of [C4275](https://msdn.microsoft.com/de-de/library/3tdb471s.aspx) warnings when using Botan. The warnings are generated in the places i have looked up because a child class is exported whose base clase is not exported. For example the exception classes that are derived from `std::runtime_error`

I've seen that in the Botan build C4275 is entirely disabled. Can i safely ignore this warning?

From the MSDN documentation 

> C4275 can be ignored in Visual C++ if you are deriving from a type in the Standard C++ Library,  compiling a debug release (/MTd) and where the compiler error message refers to _Container_base.

If i understand this correctly C4275 can only be ignored when deriving from a type in the Standard C++ Library and building in debug mode?! Because i receive this warning also in release builds.

**Comment by randombit** [comment]
The MSDN quote seems to describe a very specific scenario and if it is triggering outside that case that may be bad but I for one have no clue what the implications might be, I disabled the warning a long time ago but I'm pretty sure the docs at the time made the warning sound like useless noise since apparenently? everything works.

Where are you seeing this outside of the exception hierarchy? I have been thinking my decision in 1.11 to remove the Botan::Exception base exception class was a mistake so if we can avoid this miss simply be adding  back (deriving from std::exception which hopefully is exported...) and sed'ing all the throw calls that seems the simplest approach. I don't see any other cases where the library derives from a std:: object, and if a BOTAN_DLL object is derived from an Botan object that is not marked BOTAN_DLL that's definitely a bug.

**Comment by neusdan** [comment]
I think i have only seen this for classes that are derived from std types in Botan. [Here](http://asked.online/could-we-ignore-the-mysql---c4275-warning/2139756/) someone has described that this is not an issue if application and DLL get compiled with the same compiler and by specifing   `/MD` to the compiler so that application and DLL share the same runtime.

Wouldn't be one solution to export only the public member functions instead of whole classes?

**Comment by randombit** [comment]
I noticed the other day that Boost also explicitly disables this warning when deriving eg from std::logic_error. Not that this means it's harmless, necessarily (and I wish the MS docs were more clear exactly what the consequences of the warning are)

**Comment by neusdan** [comment]
I've found a StackOverflow [post](https://stackoverflow.com/questions/24511376/how-to-dllexport-a-class-derived-from-stdruntime-error) where someone quoted Stephan T. Lavavej (one of the maintainer's of Micrsoft's C++ library). He said:

> ... putting STL types in your DLL's interface forces you to play by the STL's rules (specifically, you can't mix different major versions of VC, and your IDL settings must match). However, there is a workaround. C4251 is essentially noise and can be silenced...

Deriving from `std::exception` unfortunately doesn't seem to help because i've read it is not exported  in VS2015. 

I am feeling pretty safe now that this is not an issue for us because we are compiling Botan and our application with the same compiler and settings. But i don't know what others are doing.

**Comment by RavilN** [comment]
Consequence of ignoring  warning 4275 can be crash of the application when EXE and DLL are as you said built with different versions of VC or one is release build and another is debug build. On these cases EXE and DLL are linked against different versions of C++ runtime. So if your DLL let say returns pointer to some object which was created by using new operator, it's memory is allocated by the heap which is owned by C++ runtime  version A. Meanwhile EXE side uses heap with version B of C++ runtime, so when that object returned by pointer is deleted in EXE side, it is being deleted from different heap than it was created at, which causes crash.
Another problem happen when you mix EXE which was linked against botan lib file (which is created for DLL type project too) of version X, with DLL of version Y. If a class was changed between versions X and Y, they will have different layout for function pointers and members variables. So when instance of that class crosses DLL boundaries, then you will have mismatch on virtual tables, which causes all sorts of hard to figure out problems (memory corruption etc).
These issues will happen not only on Windows, the same for Linux.

So EXE and DLL must have always built with the same VC and same compiler/linker settings, built with the same version of botan, and both be either release or debug.

Actually it is possible to overcome some of these problems and make DLL interface de-coupled using pure virtual functions, and putting some rules to provide version compatibility, but then all data types (not only base classes, but all member variables) must follow these patterns, which is not possible for botan as it uses a lot of STL.

**Comment by randombit** [comment]
Closing. I think given Botan's API it's not really possible to avoid STL. Applications that need to use mixed runtime DLL should stick to the FFI API which avoids these issues.
