### ISSUE TITLE
TLS 1.3: hitting assert in close notify alert

### ISSUE THREAD

**Issue by oviano** [randombit/botan#3434]
Perhaps I am doing something wrong, but having updated to latest RC1 Botan to try and give TLS 1.3 a test, I found my client hitting the line as shown in the attached screenshot.

This is after the server has rejected the connection attempt with the message "Failed to agree on a signature algorithm" and as a result of this my server has closed the connection (I'm debugging why it has failed to agree an algo, but I'm sure that's just something I need to update for 1.3).

The client is then responding to the closed socket (the receive has failed) and as part of cleaning up it is calling close() on the tls channel.

Is this something I need to address in my code somehow?

<img width="1728" alt="Screenshot 2023-03-26 at 17 48 06" src="https://user-images.githubusercontent.com/621629/227791847-dcb164cf-01ea-4239-a7b3-6b4a22b99ad6.png">

**Comment by randombit** [comment]
@reneme any ideas?

**Comment by reneme** [comment]
> At a guess, m_cipher_state hasn't been set yet because we are too early in the process/we've failed at the first hurdle?
> 
> So maybe it just doesn't need to be an assert, and we just need to check if it's valid before calling clear_write_keys.

Without looking deeper into it, yet: I think you assessment is very likely right. I'll see if I can build a regression test for this. Thanks a lot for trying out the pre-release version. That's helping us a lot.

**Comment by oviano** [comment]
> > At a guess, m_cipher_state hasn't been set yet because we are too early in the process/we've failed at the first hurdle?
> > So maybe it just doesn't need to be an assert, and we just need to check if it's valid before calling clear_write_keys.
> 
> Without looking deeper into it, yet: I think you assessment is very likely right. I'll see if I can build a regression test for this. Thanks a lot for trying out the pre-release version. That's helping us a lot.

It should be easy to reproduce - it happens 100% of the time for me, but let me know if you need any more information. Once I fixed up the signature scheme discrepancy in my code, it was able to connect over 1.3 just fine.

**Comment by reneme** [comment]
I believe I understood the mechanism that leads to this state. It took me a while to grasp how `m_can_write` can still be `true` after the server has terminated the handshake with an alert.

Though, reading your initial description carefully, you never received a TLS alert from the server. The server just closed the socket immediately:

> The client is then responding to the closed socket (the receive has failed) and as part of cleaning up it is calling close() on the tls channel.

Then, as a reaction to the closed socket connection, your application calls `close()` on the `Botan::TLS::Client` object. And this causes the assertion.

Is that correct?

**Comment by oviano** [comment]
Yes.

On the server I am responding to the exception thrown by tls_channel->received_data due to not being able to find a signature scheme to agree on. At that point, I have closed the connection on the server.

The client then fails when trying to receive (as the socket was closed by the server) and as part of the clean-up process of the connection, I am calling close() and this triggers the assert.

**Comment by reneme** [comment]
That explains. Your PR is correct, I just wanted to get to the bottom of this. To reproduce, one can simply instantiate a `Botan::TLS::Client` object and immediately call `close()` on it. That shouldn't end up in an assertion. Good catch! Thanks.
