### ISSUE TITLE
Add GCM tests for different AES key lengths

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#344]
There are 18 nice test cases I found here which I want to integrate:
http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-spec.pdf

Background: I am developing a `botan encrypt` utility that works like `openssl enc` but does also work with GCM, which openssl does not support in enc. The test data should be used for unittests as well as integration tests (calling the command line app, mybe from python).

**Comment by randombit** [comment]
Some of those vectors (1 and 2, at least) are already in gcm.vec but having all 18 would be great.
