### ISSUE TITLE
TLS 1.3 - a way of viewing/outputting the session ticket

### ISSUE THREAD

**Issue by oviano** [randombit/botan#3441]
Inside the tls_session_established callback on server and client, I am dumping the Session_Summary information like this:

```
        LOG_DEBUG("ASIO_CONNECTION_IOCP_SYS: Started TLS session (version " << session.version().to_string() << ", ciphersuite " << session.ciphersuite().to_string() << ", session id " << Botan::hex_encode(session.session_id()) << ", session ticket " << (session.session_ticket().has_value() ? Botan::hex_encode(session.session_ticket().value()) : "NA") << ")");
```

I have noticed that even when using stateless tickets in 1.3 it doesn't show any ticket value, which would be useful to verify that tickets are actually being used. The ID does contain a value, however, even when I'm using a Session_Manager_Stateless on the server.

Further investigation revealse that Session_manager does indeed issue a ticket, so I *think* it's working.

I can see this comment in Session_Summary:

```
      /**
       * The session ticket a TLS 1.2 server issued for this session.
       * Note that this may be set in TLS 1.2 clients only. It is _not_ the
       * ticket used to establish this session.
       */
      const std::optional<Session_Ticket>& session_ticket() const { return m_session_ticket; }
```

...and a quick check of the code shows that...

```
      void set_session_ticket(Session_Ticket ticket) { m_session_ticket = std::move(ticket); }
```

... is only called in the 1.2 client/server implementations.

Is there a reason this information can't also be propagated in a 1.3 connection so that it is available inside tls_session_established?

**Comment by reneme** [comment]
There might be one caveat with `tls_should_persist_resumption_information()`, though: It does not provide access to the *actual ticket bytes* received.

One way to grab these, would be to derive your own `SessionManager` and override the `store()` method. TLS clients will pass the `Session_Handle` into this method, which might either be a ticket or a session ID depending on what the server provided.

**Comment by reneme** [comment]
There might be one caveat with `tls_should_persist_resumption_information()`, though: It does not provide access to the *actual ticket bytes* received.

One way to grab these, would be to derive your own `SessionManager` and override the `store()` method. TLS clients will pass the `Session_Handle` into this method, which might either be a ticket or a session ID depending on what the server provided.

**Comment by oviano** [comment]
> There might be one caveat with `tls_should_persist_resumption_information()`, though: It does not provide access to the _actual ticket bytes_ received.
> 
> One way to grab these, would be to derive your own `SessionManager` and override the `store()` method. TLS clients will pass the `Session_Handle` into this method, which might either be a ticket or a session ID depending on what the server provided.

Ok, this is helpful and sounds like a good plan.

Out of curiosity, in the case of a stateless server session manager, what is the meaning of the session_id that appears in the Server_Summary on both client and server? Is it just generated in case a session ID was needed, but not actually used?

**Comment by reneme** [comment]
This is merely for backward compatibility. TLS 1.3 doesn't even have a Session-ID based resumption anymore. All resumptions happen via tickets that may or may not be stateful on the server side. 

To keep incompatible network middleboxes from interfering with the connection, TLS 1.3 can make its initial handshake look like a TLS 1.2 session resumption by 'faking' a random session ID. Let me quote the RFC: https://www.rfc-editor.org/rfc/rfc8446#appendix-D.4

If you don't want that for some reason, you can disable it in the client's `TLS::Policy` by making `tls_13_middlebox_compatibility_mode()` return false.

**Comment by reneme** [comment]
> Ok, this is helpful and sounds like a good plan.

Do you have a use case for accessing the session ticket bytes that might justify an easier way to access it?

**Comment by oviano** [comment]
> > Ok, this is helpful and sounds like a good plan.
> 
> Do you have a use case for accessing the session ticket bytes that might justify an easier way to access it?

Not beyond just debugging and verifying it works, no.

I've been using session IDs with 1.2 until now, and I found it useful to be able to view the log on both client and server via what is passed to tls_session_established() to make sure everything was working as expected.

I guess it feels a bit "blind" with 1.3 session tickets as I can't easily verify whether it's working or not without adding some temporary stdout logging to Botan.

As a debugging aid some callbacks that were called at different stages would have been helpful, eg:

- server has generated a session ticket and is going to send it to the client
- client has received a session ticket from the server

then

- client has a session ticket and wants is going to send it to the server for resumption
- server has received a session ticket from the client

As I say though, I can verify it by just hacking in some trace for now, if it's not worth adding such callbacks.

**Comment by reneme** [comment]
> As a debugging aid some callbacks that were called at different stages would have been helpful, eg:
> 
> * server has generated a session ticket and is going to send it to the client
> * client has received a session ticket from the server

That's exactly what `Callbacks::tls_should_persist_resumption_information()` is doing. Servers call this, before issuing a ticket to the client. And clients call it when they received a ticket from the server.

We changed that from the old `tls_session_established()`, because TLS 1.3 allows issuing arbitrarily many tickets per connection -- and also at any time after a successful handshake. I.e. a more generic callback was needed.

> then
> 
> * client has a session ticket and is going to send it to the server for resumption
> * server has received a session ticket from the client

The `Session_Summary` that is passed in `tls_session_established()` now has a `Session_Summary::was_resumption()` that is true if the session is the result of a redeemed ticket. Maybe that's enough?
