### ISSUE TITLE
Add TLS-Anvil to testing setup

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3444]
https://tls-anvil.com/ seems to be derived from/ from the same team as TLS-Attacker, but :sparkles:  fully automated :sparkles: :heart:

**Comment by FAlbertDev** [comment]
Yeah, I've worked with/for TLS-Anvil in my master thesis. It uses so called "combinatorial testing" to systematically test various combinations of TLS handshake parameters (e.g. cipher suites, enabled extensions, etc.). Its test suite tries to cover all RFC statements, so yeah: Its a nice tool :D  
If we want to use TLS-Anvil for Botan, we should make some considerations:

1. When using TLS-Anvil we can define a combinatorial testing strength defining how many combinations of handshake parameters are tested (e.g. `strength=2` requires that all possible combinations of two parameters are covered by the test vector). These combinations are tested in TLS-Anvil's test suite. Consequently, we can choose freely, if want a more extensive testing using a high strength (e.g. `strength=3`), which is much slower than testing with low strenghts. Maybe we should run a one-time manual analysis with high strength and  integrate a CI task with low strength.

2. If we want to consider a CI/CD integration, we need to discuss how to automatically interpret the results. As far as I remember, TLS-Anvil outputs multiple .json files which can be processed by an analyser for manual analysis in the browser. To process them automatically, extra work will be required.

Maybe I can invest some time in the following weeks to setup and run TLS-Anvil with Botan (manually first). I will then share the results. However, as far as I know, the authors of TLS-Anvil already ran TLS-Anvil with various TLS Libraries including Botan. I guess, if there were any findings at this point, they would have reported them. However, a CI task for TLS-Anvil is a good addition in my opinion...

**Comment by securitykernel** [comment]
We're running this in nightly CI now! 🚀
