### ISSUE TITLE
Upstream a CMake Find Module

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3490]
CMake provides so-called ["find modules"](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) in order to make it easier for downstream users of software packages to find header files, libraries to link against, etc. CMake ships find modules for [many standard software packages](https://gitlab.kitware.com/cmake/cmake/-/tree/master/Modules), e.g., Boost, OpenSSL, curl and many more. We have been writing our own find module for Botan 2.x and would now have to write our own find module for Botan 3.x when switching. Others are doing the same, e.g., [KeePassXC](https://github.com/keepassxreboot/keepassxc/tree/develop/cmake), [rnp](https://github.com/rnpgp/rnp/blob/master/cmake/Modules/FindBotan2.cmake) and more. We even link to rnp's FindBotan2.cmake from our [wiki](https://github.com/randombit/botan/wiki/Adding-Botan-to-your-build).

Can we just upstream one of these to the CMake project to be included with the CMake distribution? That would make it really easy for Botan users on CMake to integrate Botan into their builds and we get rid of all these CMake script duplicates.

**Comment by randombit** [comment]
Yeah this makes sense to include. Ideally we'd have some way of testing it.

**Comment by securitykernel** [comment]
Asked the rnp people if we can upstream theirs https://github.com/rnpgp/rnp/issues/2121.
