### ISSUE TITLE
Use a Actions nightly job to run clang-tidy

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3493]
`clang-tidy` is just too slow to run in the normal CI pipeline but apparently GH Actions supports nightly jobs, which would be ideal

**Comment by lieser** [comment]
Running `clang-tidy` at least in a nightly job sounds good.

A few other ideas:

- Use `clang-tidy-diff.py` https://clang.llvm.org/extra/doxygen/clang-tidy-diff_8py_source.html.
- Similar to the above `clang-tidy-diff.py`, get the changed files in a PR and only run `clang-tidy` on changed files.
- Try to use a cache for clang-tidy https://github.com/matus-chochlik/ctcache.

**Comment by randombit** [comment]
Closing as completed as the full nightly run is now going. Above ideas may be useful for CI checks - #3569
