### ISSUE TITLE
Make .vec data valid ini format

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#352]
When I was working with the .vec data in the Botan tests, I found that those have two issues: no syntax highlighting and not parsable by default software, like Python.

Syntax highlighting is always good for orientation, especially when comparing tests with given test vectors from other sources. Parsing I need right now to use the .vec files to perform integration tests for a cli application.

I considered using JSON or YAML for this but I guess I don't make friends here when pulling in a JsonCpp dependency …

However I was able to convert the .vec data relatively easy to the [.ini file format](https://en.wikipedia.org/wiki/INI_file). This lets me syntax highlighting it using gedit and parsing it using Python's [configparser](https://docs.python.org/3/library/configparser.html).

The only thing that needs to be adapted is that one section can contain each key only once. That means every section needs to be one test case. This is a very helpful thing because it allows me to give the test cases a proper name referring it's source.

Having a custom name for each test case means we need to add the algorithm to each test case, which is a good thing to do in my opinion.

My current gcm.vec looks like this: https://gist.github.com/webmaster128/45186a1b9cca0ffe4474 (thanks github for syntax highlighting this for me)

Would it be okay to convert more .vec files (starting with test_aead.cpp) to correct .ini format?

**Comment by randombit** [comment]
Totally unconvinced. It's plausible enough in this context but look at des.vec (which would need 389 additional

Algo=DES

plus 389 additional
[Unknown DES Test #xyz]
headers, adding tedium and noise with precisely zero increase in actual content. Or ecdsa.vec which I think would be 2-3x longer in this scheme, when the same keys are tested with 10 distinct inputs.

The .vec files are not configuration files, not even slightly. They configure nothing, are typically append-only, and are never edited by a user. They represent streams of key value pairs that the tests iterate over; any syntactical resemblance to an .ini file is coincidental. Every bit of smarts in configparser will be bent against us as it helps us manage our config files which are not config files at all.

And I don't find github adding syntax hightlighting to be a particularly compelling advantage; its a sequence key value pairs and yup! the split is at the equals.

**Comment by webmaster128** [comment]
Thanks Jack for your thoughts. I see that this is not ideal for lager datasets. ini was just an idea because it is very similar to the current file structure and it can be parsed without other dependencies.

Still, I think that we should have structured test data using an industry standard file format, which allows us to automatically read and write test data vectors. This allows everyone to inspect and verify our test vectors against other implementations and easily add new ones.

The readability and auditability of the tests is as crucial is the implementation of the code under test. This is not just about testing a bit of something but having an idea of what combinations and which edge cases need to be tested. Structured test names/descriptions help a lot here.

There is no need to implement even the simplest parser ourself, which we need to do multiple times in different languages, if we for example add proper tests for the cli and the Python module.

If I had to choose, I'd go for json because it is widely spread, human readable and easy to parse. It can model the existing data better than ini because it can nest more than one layer.

This is really a matter of sharing resources. I have my tests prepared for `./botan encryption` and could contribute those to the main botan tests, if we can agree on a common file format.

**Comment by randombit** [comment]
What would be 'standard' about a crypto library using an INI file (or god forbid JSON for that matter) to represent test vectors? No other implementation uses such a format. No RFC, standards doc, or academic paper uses such a format or even close to it.

Also, parsing a fucking text file in Python is  just not hard compared to the actual, real, serious problems this code is meant to solve.
