### ISSUE TITLE
cli: regression error (demanding wrong number of arguments)

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#354]
`src/cli/x509print.cpp` has the following code:
```
int x509print(const std::vector<std::string> &args)
   {
   if(args.size() != 1)
      {
      std::cout << "Usage: " << args[0] << " cert.pem" << std::endl;
      return 1;
      }
```
The comparison should be `args.size() <= 1`, or `args.size() != 2`.

`src/cli/cert_verify.cpp` has a similar problem:
```
int cert_verify(const std::vector<std::string> &args)
   {
   using namespace Botan;

   if(args.size() <= 2)
      {
      std::cout << "Usage: " << args[0] << " subject.pem [CA certificates...]" << std::endl;
      return 1;
      }
```

Comparison should be `args.size() < 2`.

Haven't checked all of them, so may be other lurkers.

**Comment by webmaster128** [comment]
You are right, that those are might bugs. But both of them are not really regressions in the sense that they have been introduced recently. Those bugs are years old.

The first must be != 2 (as you mentioned) because exactly one argument is documents. The second one might be okay as it is, if at least one CA certificate must be set. I don't know how the semantics are here. But even than < 3 is a better notation given that 3+ is valid.

**Comment by mouse07410** [comment]
As far as I recall, it should function without explicit CA cert passed as parameter. That would mean `args.size() < 3`.

**Comment by webmaster128** [comment]
Okay but if CA certs are optional, 2 and more arguments are valid. So it would be `args.size() < 2`.

**Comment by mouse07410** [comment]
Oops, you're right. Anyway, I see you have fixed this. Thanks!

**Comment by webmaster128** [comment]
Did I? I don't think this is fixed.

**Comment by webmaster128** [comment]
I think we should use the argparse notation for optional positional arguments:

exactly one: `cmdname unittest_args`
one or more: `cmdname unittest_args [unittest_args ...]`
arbitrary count: `cmdname [unittest_args [unittest_args ...]]`

I don't see how cert_verify could produce anything useful without at least one CA file.

**Comment by mouse07410** [comment]
Certificate verification does not have to go all the way to the CA - perhaps the user just wants to make sure all the fields are consistent, or perhaps it is a self-signed certificate.

In any case, having no CA in the arguments **is OK**.

**Comment by webmaster128** [comment]
Thanks @mouse07410 for reviewing my change. As I said, I am not an expert of the semantics of cert_verify, thus I did not yet change it. Please feel free to open a PR changing `< 3` to `< 2` and the usage message accordingly. The rest of the code should work just fine.

**Comment by mouse07410** [comment]
Turns out the problem is deeper. `cert_verify()` calls `x509_path_validation()` that requires CA cert(s). I will look into how it affects self-signed certificates. In the meanwhile, since changing the allowed number of arguments to 2 would not improve the situation, I'm holding back on that PR until I learn more. Thanks!

**Comment by mouse07410** [comment]
I'm closing this issue for now. If there is new development, will either reopen this one or create a new one.
