### ISSUE TITLE
Add a quick check mode for clang-tidy

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3569]
`clang-tidy` gets slower as more checks are enabled. We may be able to get away with a very limited check of `clang-tidy` in CI that hits just the issues that most commonly escape review. That will reduce the rate that the nightly job fails after code is committed.

With *just* the checks `modernize-use-nullptr` and `readability-braces-around-statements` enabled, `clang-tidy` already took 171 seconds to check the codebase on a 4 core machine, so we probably can't get away with more than ~~ 3 to 10 checks enabled, before the runtime becomes intolerable. That's probably enough to cover the ones that people regularly commit by accident, though.

**Comment by reneme** [comment]
Perhaps we should add those smoke checks (or potentially the full check harness) to the editor integrations and encourage contributors to use those supported editors. That way things won't even be committed in  the first place.

**Comment by randombit** [comment]
@lieser posted links to some tools that may help in [this comment](https://github.com/randombit/botan/issues/3493#issuecomment-1531340219)

**Comment by randombit** [comment]
> potentially the full check harness

If you want to wait 20+ minutes per commit, go for it, but I'll pass :sweat_smile: 

I think in terms of editor integrations or pre-commit hooks that will reduce CI turnaround times, checking formatting is a lot more viable.

**Comment by randombit** [comment]
The fast job added in #3571 didn't actually work because in GH actions we didn't have master to compare to to find the list of changed files and for the life of me I couldn't make it work without pulling the entire commit history, which takes at least 10 minutes on github actions (a whole WTF on its own, seeing consistent 200 KB/s for fetch), killing the point of a fast check.

**Comment by reneme** [comment]
> I think in terms of editor integrations or pre-commit hooks that will reduce CI turnaround times, checking formatting is a lot more viable.
>
> (But feel free to explore this! Maybe with good caching, etc it will actually be viable)

Here's a suggestion of how an editor integration might work: #3592. Time from saving/opening the file to being notified: ~5 seconds.

**Comment by randombit** [comment]
OK I got it working in #3620 by writing a script that queries github's API which is apparently the easiest way to get the list of changed files from within github actions (?!?)

It's not perfect because we don't have dependency information - a change to a header that introduces a clang-tidy warning will be missed unless the same PR also changes a file that includes that header - but it will catch most issues and the nightly run will do the rest.
