### ISSUE TITLE
Something is wrong with `run_clang_tidy.py`s `--only-changed-files` option

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3576]
https://github.com/randombit/botan/actions/runs/5169538129/jobs/9311857163?pr=3575 reports "No C++ files were modified vs master, skipping clang-tidy checks". But two C++ files were modified. If I run locally, it correctly checks those two files.

**Comment by randombit** [comment]
Ah master is not available to compare in the default checkout

```
+ git diff --name-only -r master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
```

**Comment by randombit** [comment]
Couldn't figure out how to make it work, fuck github, disabled the job

**Comment by lieser** [comment]
We could try one of the GitHub actions that list changed files, e.g. https://github.com/tj-actions/changed-files.
