### ISSUE TITLE
XMSS private key does not update when signing X.509 things from the CLI tool

### ISSUE THREAD

**Issue by thewalker77** [randombit/botan#3578]
I am not 100% sure I am doing things correctly, but assuming I am. XMSS keys are stateful and they should keep track of how many times they have been used, but the cli tool does not do that:

```
$ botan -V
2.19.1
$ botan keygen --algo=XMSS  > key.priv
$ shasum key.priv
e938f6.............ef key.priv
$ botan gen_self_signed key.priv --emsa=pssr random_file > cert
$ shasum key.priv
e938f6.............ef key.priv # does not change
```

I expected key.priv to update on every usage,otherwise it is security risk ?

**Comment by reneme** [comment]
At first sight that sounds surprising as we test that [with a CLI test](https://github.com/randombit/botan/blob/f896922083ec913a2fe9a875c49158aa772b751b/src/scripts/test_cli.py#L409). Though, this does sign directly and not via an X.509 certificate. I'll keep you posted.

**Comment by reneme** [comment]
Yes, this is reproducible. Thanks for reporting, I'll look into it.

**Comment by reneme** [comment]
With #3579 merged this is fixed. Thanks again for reporting.
