### ISSUE TITLE
how to ignore certificate?

### ISSUE THREAD

**Issue by magicjva** [randombit/botan#3580]
how to ignore certificate? botan3

**Comment by reneme** [comment]
I'm assuming you want to establish a TLS connection as a client and ignore the server certificate chain.

To do that, add an overload of `tls_verify_cert_chain()` to your `Botan::TLS::Callbacks` subclass and simply ignore all the inputs. As long as your overload does not throw an exception the TLS implementation will assume you're happy with the certificate chain.

**Comment by reneme** [comment]
Closing. Please feel free to re-open if your question wasn't answered.
