### ISSUE TITLE
Unused function: word8_muladd

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#363]
The mp_x86_32_msvc version of mp_asmi.h defines a method that does not exist in mp_generic or any other mp_asmi.h: 

```
/*
* Eight Word Block Linear Multiplication
*/
inline word word8_muladd(word z[8], const word x[8],
                         word y, word carry)
```

It looks like this method is used nowhere in the entire code. Can it die or did I miss something here?

**Comment by randombit** [comment]
Yes it can go, I believe this was a function used by BigInt long ago which was likely removed from the other versions but missed here.

**Comment by randombit** [comment]
Removed, closing
