### ISSUE TITLE
Installs library with wrong numeric suffix

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#3636]
```sh
$ pwd
/Users/ur20980/src/botan
$ ./botan3 version
3.2.0
$ ll *.dylib
lrwxr-xr-x  1 ur20980  MITLL\Domain Users       18 Jul 20 09:34 libbotan-3.0.2.0.dylib@ -> libbotan-3.0.dylib
-rwxr-xr-x  1 ur20980  MITLL\Domain Users  7064344 Jul 20 09:34 libbotan-3.0.dylib*
lrwxr-xr-x  1 ur20980  MITLL\Domain Users       18 Jul 20 09:34 libbotan-3.dylib@ -> libbotan-3.0.dylib
$ 
```

Shouldn't it be `libbotan-3.2.0.dylib` instead of `libbotan-3.0.2.0.dylib`?

**Comment by randombit** [comment]
We were failing to bump the ABI revision along with the minor version

On Mac we use a unconventional (?) naming scheme

```
soname_pattern_base  "lib{libname}.dylib"
soname_pattern_abi   "lib{libname}.{abi_rev}.dylib"
soname_pattern_patch "lib{libname}.{abi_rev}.{version_minor}.{version_patch}.dylib"
```

So the name "should be" `libbotan-3.2.2.0.dylib` where the first 2 is the ABI revision and the second is the minor version.

I don't know if any of this is really correct but looking at the history it's how things have been set up for many years.

**Comment by mouse07410** [comment]
> On Mac we use a unconventional (?) naming scheme

I think what you described is perfectly conventional, on both Mac and Linux.

Regardless, the current master assigns correct values:
```sh
$ ll ~/src/botan/*.dylib
lrwxr-xr-x  1 ur20980  staff       18 Jul 23 16:06 /Users/ur20980/src/botan/libbotan-3.2.2.0.dylib@ -> libbotan-3.2.dylib
-rwxr-xr-x  1 ur20980  staff  7449440 Jul 23 16:06 /Users/ur20980/src/botan/libbotan-3.2.dylib*
lrwxr-xr-x  1 ur20980  staff       18 Jul 23 16:06 /Users/ur20980/src/botan/libbotan-3.dylib@ -> libbotan-3.2.dylib
$ 
```

Thanks!
