### ISSUE TITLE
ECDSA private key check

### ISSUE THREAD

**Issue by Takarth** [randombit/botan#3648]
bool ECDSA_PrivateKey::check_key(RandomNumberGenerator& rng, bool strong) const

Does not verify that private value is in the range of 1 <= k < curve order.

Suggested fix:
bool ECDSA_PrivateKey::check_key(RandomNumberGenerator& rng, bool strong) const {
     if(m_private_key < 1 || m_private_key >= m_domain_params.get_order()) {
      return false;
   }

   if(!public_point().on_the_curve()) {
      return false;
   }
....

**Comment by randombit** [comment]
Thanks for pointing this out
