### ISSUE TITLE
Rewrite ./botan tls_http_server using the ASIO stream

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3659]
It seems the implementation for said toy HTTP server is quite dated and bug prone. I envision to use Boost Beast to replace the minimal HTTP responder that is currently used on top of the ASIO stream. To be clear: this does not aim to implement a fully functional HTTP server. Instead, it should serve as a nice showcase for how to combine ASIO, Botan's TLS and Beast to build an HTTPS server.

Perhaps, @hrantzsch's [example code](https://github.com/hrantzsch/botan-tls-stream-server-example/blob/master/server.cpp) could be a good starting point for this. This example was initially adapted from [Boost Beast's server example](https://www.boost.org/doc/libs/master/libs/beast/example/advanced/server/advanced_server.cpp) in early 2020 and may or may not need some refreshing with the latest Boost code.

**Comment by randombit** [comment]
Yeah, the current version was *just* sufficient to run some tests with (IIRC) https://github.com/tlsfuzzer/tlsfuzzer which requires that the TLS stack it is talking to also be an HTTP server.
