### ISSUE TITLE
Mark functions in lookup.h as deprecated

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#366]
If i understand this correctly the functions in `lookup.h` should no longer be used. Instead the new  `T::create` API should be used. 

So what about marking the functions in lookup.h as `BOTAN_DEPRECATED` ?

**Comment by randombit** [comment]
I wanted to give a little time to see how the new API settled out before I marked the lookup.h versions deprecated and caused people to rewrite existing code. But after a couple of months, it's probably time.

**Comment by neusdan** [comment]
Okay thats fine, but maybe it should be somehow documented to let people know that they should use the new API.

**Comment by neusdan** [comment]
:+1: 

I suppose this can be closed then?!
