### ISSUE TITLE
Output of testframework too verbose

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#367]
I think there is a lot of overhead in the output of the testframework. For example i get a lot of this  messages:

```
Comb4P(MD4,MD5) ran ZERO tests in 0.03 msec all ok
Note 1: Comb4P(MD4,MD5) Skipping tests due to missing Comb4P(MD4,MD5) from base
```

So for all tests that cannot run because a dependency is missing i get this kind of messages.

I would suggest to output this only if `--verbose` or something like that is specified.

**Comment by randombit** [comment]
I'm working on some CLI changes (in cli-improvements branch) specifically to address some of these issues. It among other things will add a --verbose flag (to every command). Deciding exactly how noisy the non --verbose test output will be is an open question but I agree with you in principle. The lack of any toggles on the current test output results in it being pretty noisy by default for lack of any alternative.

Right now the test framework isn't using the new CLI framework but that's the next step once I finish rewriting the benchmark code (last thing not already rewritten in that branch). I expect this all to land before 1.11.26.

**Comment by neusdan** [comment]
Thanks for a24c4cd. In my opinion this can be closed now.

**Comment by cordney** [comment]
@randombit Any reason to still keep this open?

**Comment by randombit** [comment]
Nope thanks
