### ISSUE TITLE
Dilithium Standardization Updates

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3691]
NIST has published a [first public draft standard](https://csrc.nist.gov/pubs/fips/204/ipd) for Dilithium, now called "Module-Lattice-Based Digital Signature Standard".

**Comment by falko-strenzke** [comment]
I would like to point at https://github.com/randombit/botan/issues/3697 in this context. I think it is really important to have clarity what algorithm generation is actually invoked.

**Comment by reneme** [comment]
#4270 is merged.
