### ISSUE TITLE
Sphincs+ Standardization Updates

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3692]
NIST has published a [first public draft standard](https://csrc.nist.gov/pubs/fips/205/ipd) for Sphincs+, called "Stateless Hash-Based Digital Signature Standard".

**Comment by falko-strenzke** [comment]
I would like to point at https://github.com/randombit/botan/issues/3697 in this context. I think it is really important to have clarity what algorithm generation is actually invoked.

**Comment by reneme** [comment]
#4291 is merged.
