### ISSUE TITLE
base64_encode does not work with zero-length input

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#37]
[base64_encode](http://botan.randombit.net/doxygen/namespaceBotan.html#a0dd24063a031ed438e778f160ec3fba7) does allocate an output string using the following length calculation

```C++
(round_up<size_t>(input_length, 3) / 3) * 4
```
It turns out that `round_up<size_t>(0, 3)` is 3. From reading the comment, that is not the expected bahavior:

```
* Round up
* @param n an integer
* @param align_to the alignment boundary
* @return n rounded up to a multiple of align_to
```

If `n = 0` and `align-to = 3`, than it must return `0` because [0 is a multiple of everything](http://en.wikipedia.org/wiki/Multiple_%28mathematics%29#Properties)

If the function cannot be changed, `base64_encode` needs to treat the case `input_length = 0` separately. I was able to fix the problem by calculating the output length before allocating the string:

```C++
size_t output_length = input_length != 0 ? (round_up<size_t>(input_length, 3) / 3) * 4 : 0;
std::string output(output_length, 0);
```
I could provide a pull request for the 2 possible fixes:
* Change `round_up`
* Add case distiction in `base64_encode`

**Comment by randombit** [comment]
Changing `round_up` unfortunately conflicts with some uses where we rely on `n = 0` returning the maximum alignment. Instead I've special cased base64_encode (and base64_decode) for zero length inputs. Can you test latest trunk?

**Comment by webmaster128** [comment]
On which branch? I can't find the commit. Could you post a link here?

**Comment by randombit** [comment]
Sorry, it took a little while for the monotone->github sync to run it appears, the specific commit is https://github.com/randombit/botan/commit/a205bc8691df95b58e651fdb932d886f4f937cb9

**Comment by webmaster128** [comment]
Nice! I added an optional PR: https://github.com/randombit/botan/pull/40. Unfortunately I was not able to easily  add unit tests to Botan because I could not understand the structure from existing tests. Maybe it would be a good idea to implement a widely used testing framework.
