### ISSUE TITLE
`Vector too long` error in runtime when creating a TLS client but not in amalgam

### ISSUE THREAD

**Issue by Max9403** [randombit/botan#3704]
Hi,

While setting up a c++23 project using modules (but not using the std module) in cmake, on windows using MSVC 19.37.32824.0, I ran into the runtime error `Vector too long` when I instantiate a TLS client (using near 1-to-1 to the example code in the documentation/tests) however it doesn't happen when I use the amalgam build. This happened with the 3.1.1 and git release, I have however not checked if the amalgam fixes the git version. (I do move the files out of the `c:\botan` folder)

Please let me know if you need any extra info.

**Comment by randombit** [comment]
Do you mean, you built botan not as a typical library but instead as a C++20 module? That isn't something we've tested and I would not be surprised if there was some miscompilation as a result. In any case we'd need more details, at the very least a backtrace to indicate where the runtime error occurs. Did you run the test suite?

**Comment by Max9403** [comment]
No compiling it using the standard `./configure.py / nmake / nmake check / nmake install` then copying the result into a project that use modules. Then I add it in cmake as an imported shared library. Then the constructor balks with `Vector too long`.
If instead run configure with amalgam, then create a shared library containing `botan_all.h`, `botan_all.cpp`, and `external/*` (with `BOTAN_DLL` defined and `/bigobj` flag) it runs fine.
It happens in `std::make_shared<Botan::TLS::Client>(...)`, I have tried a standard `Botan::TLS::Client(...)`

**Comment by Max9403** [comment]
Turns out this was because I was using the release build on the debug cmake project without realizing it
