### ISSUE TITLE
How can I access Blake2b192 from the Botan::Hash class?

### ISSUE THREAD

**Issue by Trafo** [randombit/botan#3728]
I am using at the moment Botan2 and when I use Blake2b hash class directly I get the warning that those headers will be not accessible anymore in the future (I assume with Botan 3, where I want to migrate soon.)

Because I don't like any warnings, I wanted to use the more general Hash class. But for me, it seems like, it only provides me Blake2b256 and Blake2b512 and I cannot set any number of the output bits. Truncating is not possible, because results are completely different, in case output bits differ.

I need this function to support old legacy crypto, based on libsodium, because libsodium is using Blake2b192 in one of his algorithms (sealed boxes: https://doc.libsodium.org/public-key_cryptography/sealed_boxes) Did I oversee something, or did I loose with Botan3 functionality?

**Comment by randombit** [comment]
This should still be available by requesting via name "BLAKE2b(192)". While we did remove some functionality in 2->3, none of it related to BLAKE2b so if something here used to work and doesn't anymore, that was certainly unintentional and should be fixed.

**Comment by randombit** [comment]
BTW in case you were unaware, there is a libsodium compatability later in `botan/sodium.h`. It implements the libsodium API circa 2019 and hasn't been updated since, so new APIs are not there, but it might be helpful for porting and/or understanding how to implement the same functionality using the C++ interface.

**Comment by Trafo** [comment]
Thx very much, that is good news for me, by the way, is there somewhere a list of all supported string inputs of algorithms for each function? Because I could not find any document describing it and in the code, I did not find many central clues as well, I mainly found them out while reviewing other code or guessing them based on the documentation.

Besides that, I am aware of `botan/sodium.h` and I am very thankful that it exists. But this function was not implemented there, which is not a big problem, because it is only some extra logic + crypto_box which is available in botan.

**Comment by Trafo** [comment]
Thx it worked. But I thought actually I tried this already and then I got an exception. But maybe another typo was the reason.

**Comment by Trafo** [comment]
@randombit I can offer to add the sealed box implementation of libsodium to `botan/sodium.h`. But will only do it, if those changes are welcomed.

**Comment by randombit** [comment]
@Trafo ideally `botan/sodium.h` would be a 100% complete/compatible clone of the libsodium API, so anything that gets us even a tiny bit closer to that is certainly welcome.
