### ISSUE TITLE
CI: Look into iterator debugging

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3737]
As discussed in #3734.

**Comment by thesamesam** [comment]
See https://github.com/randombit/botan/pull/3736#issuecomment-1751913027.

I don't see why the lightweight options (which don't break ABI) couldn't be added at the very least.

**Comment by randombit** [comment]
GCC and MSVC already have configurations set up for iterator debugging - we just aren't using them in CI for whatever reason

**Comment by randombit** [comment]
#4413
