### ISSUE TITLE
Fixing Wshadow issues

### ISSUE THREAD

**Issue by cordney** [randombit/botan#374]
When enabling `-Wshadow` on GCC 5.2.0, I get a lot of `declaration of x shadows a member of` warnings, on linux x86_64 in the default configuration there are about 260 currently. An example:

```
In file included from ./src/tests/unit_ecdsa.cpp:23:0:
build/include/botan/rsa.h: In constructor ‘Botan::RSA_PrivateKey::RSA_PrivateKey(Botan::RandomNumberGenerator&, const Botan::BigInt&, const Botan::BigInt&, const Botan::BigInt&, const Botan::BigInt&, const Botan::BigInt&)’:
build/include/botan/rsa.h:71:43: warning: declaration of ‘n’ shadows a member of ‘Botan::RSA_PrivateKey’ [-Wshadow]
                      const BigInt& n = 0) :
                                           ^
In file included from build/include/botan/rsa.h:11:0,
                 from ./src/tests/unit_ecdsa.cpp:23:
build/include/botan/if_algo.h:52:14: note: shadowed declaration is here
       BigInt n, e;
```

Cpp best practices say you should enable `-Wshadow` these days, for example:

* https://github.com/lefticus/cppbestpractices/blob/613895ce9eb61cd384eca4308b2a63b3382f20b2/02-Use_the_Tools_Available.md#gcc--clang
* https://www.securecoding.cert.org/confluence/display/cplusplus/DCL01-CPP.+Do+not+reuse+variable+names+in+subscopes

One way would to fix these would be to use a prefix in member variables, e,g., the `m_` prefix as in `BigInt m_n, m_e;`. I would work out a patch for fixing these, but I wonder if you think its worth fixing them.

**Comment by webmaster128** [comment]
Thanks for the `-Wshadow` hint. I personally see this as a valuable thing to do because shadow variables already caused bugs in my code in the past (not Botan).

Having the `m_` prefix for members is already a [style-convention](https://github.com/randombit/botan/blob/master/doc/hacking.rst#style-conventions) in Botan. So it should be possible to get rid of the warnings without doing undesired code changes.

But regarding your question, this is up to Jack.

**Comment by randombit** [comment]
In general being as warning clean as possible is good, and especially warnings in public headers are worth fixing since otherwise this adds noise for downstream projects. I would be fine with a PR with a mass addition of m_ prefixes on member variables.

**Comment by cordney** [comment]
Ok, I'll prepare a PR.

**Comment by cordney** [comment]
Does the `m_` prefix rule also apply on public members, e.g., as in https://github.com/randombit/botan/blob/master/src/lib/asn1/asn1_obj.h#L87?

**Comment by randombit** [comment]
For now public members should stay as is but if you notice them please add

// public member variable:

before each, both so it is obvious to a reader that this variable is intentionally public, and to make it easier to find them since likely most uses are code smells.
