### ISSUE TITLE
configure.py fails if parent directory has info.txt

### ISSUE THREAD

**Issue by gix** [randombit/botan#3746]
The `InfoObject` constructor does not stop after reaching the repository root. If the parent directory by chance has an info.txt file configure will fail complaining with a confusing message about an unknown module.

The loop should probably check against the dirname of `__file__` and stop when reached.

**Comment by randombit** [comment]
Wow, WTF :joy: thank you for reporting this

**Comment by randombit** [comment]
Fixed by #3748 thanks again for the report
