### ISSUE TITLE
Problem building using compiler 19.37 on Windows 11 VisualStudio 2022 Community

### ISSUE THREAD

**Issue by FlorisBeentjes** [randombit/botan#3761]
When building the library in Visual Studio using the developer powershell I get:
 ERROR: Configured target is x86_64 but compiler probe indicates x86_32
 
The only compiler I have installed is 19.37 and in the configuration manager I have configured that I build for x86_64. (I know this is for the project but I can't find any other option that changes the compiler or its behavior).

To prevent this error I started a x64 command prompt from my windows start menu and built the library using this prompt. This started the build with the following parameters:
   INFO: Canonicalized CPU target AMD64 to x86_64
   INFO: Auto-detected compiler version msvc 19.37
   INFO: Auto-detected compiler arch x86_64
   INFO: Target is msvc:19.37-windows-x86_64
   
When using nmake check all test except the one for certstor_system are ok.
 Tests complete ran 2956107 tests in 32.75 sec 1 tests failed (in certstor_system)

When I enter the lib path and headers path to my project (I do not plan on using the certificate functions) and try to run the ChaCha20 streamcipher demo from the website I get the following error messages in Visual Studio:
![image](https://github.com/randombit/botan/assets/70689801/ed579b81-7d8c-4afb-bd7d-0baef907bf6d)

With the following build output:
![image](https://github.com/randombit/botan/assets/70689801/45d089a7-8868-41d8-ab30-96040be6012b)

I think that this means that somewhere I made a mistake when building the library, and the mistake is probably in my VisualStudio settings but I checked everything and can not find it, so maybe it could be an error?

I used the latest v3 release from the GitHub page to build the library.

**Comment by securitykernel** [comment]
> To prevent this error I started a x64 command prompt from my windows start menu and built the library using this prompt. 

Yeah, the command prompt when opened from within Visual Studio defaults to `x86` and there seems to be no way to change it after that, even with running `vcvarsall.bat` and the like, so opening it from Windows start menu is the right thing to do here.

> I think that this means that somewhere I made a mistake when building the library, and the mistake is probably in my VisualStudio settings but I checked everything and can not find it, so maybe it could be an error?

It is likely an issue in your VS project. Make sure to have the following set in the project properties (All Configurations, x64):

* VC++ Directories -> Include Directories: Add path to Botan headers, e.g., `C:\Botan\build\include`
* VC++ Directories -> Library Directories: Add path to botan-3.lib, e.g., `C:\Botan`
* Linker -> Input -> Additional Dependencies: Add `botan-3.lib`

When not setting Additional Dependencies, I get the same linker errors as you get.

**Comment by FlorisBeentjes** [comment]
Started a new VS project and that ended up working. (I copied the link properties so I don't know why

**Comment by securitykernel** [comment]
Glad to see you have a working setup! FWIW I added the instructions to https://github.com/randombit/botan/wiki/Adding-Botan-to-your-build.

**Comment by lieser** [comment]
> Started a new VS project and that ended up working. (I copied the link properties so I don't know why it works but hey.

I sometimes had the problem that VS fails to detect that it needs to do a recompilation if the configured external libraries change. The result there some strange linker errors like you observed too.
In the past an explicit rebuild (or a clean before the build) helped to resolve it.
