### ISSUE TITLE
String comparision

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#377]
I've ran the static analyzer PVS-Studio on the Botan code base. It's shows a lot of performance warnings for places where strings are compared like this `if (s == "")` instead of `if (s.empty())`

The explanation from PVS-Studio:

> The object of the 'std::string' class knows the length of the string it is storing, but it is unknown which string it is intended to be compared to. That's why a loop is called for string comparing

It's clear that it won't make much difference but i would send a PR if you are willing to accept this change.

**Comment by randombit** [comment]
I would have guessed the compiler would inline the construction of the std::string and convert s == "" to the equivalent of s.empty() in any case. But perhaps not?

No harm in it though, and there is value in keeping static analyzers quiet and happy, so I would take a PR with a mass `s == ""` -> `s.empty()` conversion.

Does it also warn about `s != ""` as equivalent to `s.size() > 0` or `!s.empty()`?

**Comment by neusdan** [comment]
PVS-Studio also warns about `s != ""`

**Comment by randombit** [comment]
Is there any way to teach PVS-Studio about new types? BigInt != 0 or == 0 would be valuably replaced by BigInt::is_zero

(Just a review would find most of these, though they are out of most common paths now)

**Comment by neusdan** [comment]
Unfortunately PVS-Studio doesn't have a mechanism to enable users to write their own rules.
