### ISSUE TITLE
Nightly TLS-Anvil CI failure with new HTTP server

### ISSUE THREAD

**Issue by FAlbertDev** [randombit/botan#3778]
It seems that TLS-Anvil is not (yet) happy with the new TLS HTTP server (see [failing CI](https://github.com/randombit/botan/actions/runs/6662530573/job/18107006051) ). At first glance, it is a problem with a clean TLS session shutdown. Either some wrong handling of the close notify TLS alert (which looks OK in Wireshark) or some issue with closing the socket. I'll look into it.

**Comment by reneme** [comment]
After a first investigation we believe that the ASIO stream fails to send TLS alerts while handling the handshake. For instance, if the TLS implementation generates a `TLS_Exception(Alert::HandshakeFailure)`, it would close the socket immediately but not report the alert to the peer first.

This seems to be a long-standing bug in the ASIO stream.

**Comment by reneme** [comment]
Another issue seems to be that we didn't close the connection gracefully in `./botan tls_http_server` after a protocol error had occured. Details [here](https://github.com/randombit/botan/pull/3795#issuecomment-1792589832). @FAlbertDev has run [another round of TLS-Anvil](https://github.com/FAlbertDev/botan/actions/runs/6746976008/job/18342090752) with now just one failing test. More next week!
