### ISSUE TITLE
Update draft-irtf-cfrg-hash-to-curve to RFC 9380

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3806]
[draft-irtf-cfrg-hash-to-curve](https://datatracker.ietf.org/doc/rfc9380/) was added in 3.0.0 and was now finalized as RFC 9380. We should review the differences and update the implementation accordingly. Guessing from 8bf306dbff69188f23ae1b6932ba392e4e04e814 it was likely implemented against draft-irtf-cfrg-hash-to-curve-09 or draft-irtf-cfrg-hash-to-curve-10, which is 8 or 7 revisions behind RFC. Luckily, IETF's data tracker provides a good diff viewer.

**Comment by randombit** [comment]
I think for SSWU suites nothing actually changed in all that time. At least the test vectors are still the same.

**Comment by securitykernel** [comment]
So should we just update the [docstring](https://github.com/randombit/botan/blob/master/src/lib/pubkey/ec_h2c/ec_h2c.h#L31C15-L31C45) to reflect that it conforms to RFC 9380?
