### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Ricky-Tigg** [randombit/botan#3816]
Hello. This platform has a built-in section named _Releases_ for a reason. What was the goal of this project to disable it? A way of your own to reveal their existence would be unusual and is never wise.

**Comment by randombit** [comment]
Github's "releases" just points to the tag which is not the final release artifact. AFAIK there is no way to change this.

**Comment by lieser** [comment]
> Github's "releases" just points to the tag which is not the final release artifact. AFAIK there is no way to change this.

Although it is true that the assets of a release always contain the source code of the tag, it is possible to also upload additional assets.
See step 9 of https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release.
