### ISSUE TITLE
Be able to provide passwords as secure_vector<byte>

### ISSUE THREAD

**Issue by jjl** [randombit/botan#384]
It seems undesirable  to have to pass in a string for the passphrase in various places when we could provide it as a secure vector. If we've already gone to the trouble of making sure the data is in a secure vector, it seems a waste of time (and a potential security problem) turning it into a string just to pass it to a function.

e.g.

```
OctetString PBKDF::derive_key(size_t output_len, const std::string &passphrase, const byte *salt, size_t salt_len, size_t iterations) const
```

**Comment by randombit** [comment]
To some extent I view this as a lost cause: likely any password that came from a user passed through tens of different IO buffers along the way (kernel, terminal handling or GUI libraries, etc), none of which are going to be zeroed. But there is no reason to make it worse than it already is, and in specialized applications there may be more reason to believe the password has be securely handled up to the point of the library call (eg, it was retrieved via some trusted system-provided password entry GUI)

I think maybe the best option is to allow the user to provide a byte* pointer and length as an alternative input to such functions, and then provide `std::string` override that passes s.data()/s.length() for compatibility and users who don't want to worry about it.

It would be great to use `string_view` for this which is actually exactly what's needed and avoids any copies. But I think the library fundamentals TS is not quite baked.

PBKDF would be easy to update as it would just be adding a few new signatures. The ripple effects of updating PBES2 and private key encoding might require some work though.
