### ISSUE TITLE
CI hangs for Botan 2.x branch

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3873]
The build of the Botan `release-2` branch depends on Ubuntu 18.04 (to test on GCC 4.8). Apparently, GitHub Actions has removed this runner [a while ago](https://github.com/actions/runner-images/commit/e72606ffb643bcabdd712fb09ef10c3181959f27). Hence, pull requests pointing at `release-2` (such as #3871) now hang in CI.

**Comment by randombit** [comment]
:disappointed:

It looks like this was *only* used for GCC 4.8 testing. On quick search I don't see an easy way of getting GCC 4.8 installed onto Ubuntu 20.04 or higher, short of actually compiling all of GCC as part of CI which is not ideal [*]

[*] We probably could get away with this given the very low commit rate to `release-2` but still ...

IMO let's just disable it from CI. I don't expect 2.x will see much further changes anyway and we/I can just spot-check with GCC 4.8 compiling locally as required.
