### ISSUE TITLE
Confirm restrictions of install_name_tool/Set -headerpad_max_install_names

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#388]
We are expanding the library install names via install_name_tool, which is not necessarily a valid thing.

Let's check what happens if we are exceeding the max. length of the library names by setting a very long value. Is install_name_tool returning an error or just overriding bytes in the binary?

Set `-headerpad_max_install_names` if appropriate.

This is a memo to not spam the mailing list. I can do it when I have access to a mac again next week.

**Comment by randombit** [comment]
Going to assume whatever we are doing is not causing problems, or someone would have mentioned it by now. Closing.
