### ISSUE TITLE
Failing to run program on Windows

### ISSUE THREAD

**Issue by PL-Aurora** [randombit/botan#3886]
Hi, while trying to run simple program:

```
#include <botan/hash.h>
#include <botan/hex.h>
#include <vector>
#include <iostream>

int main()
{
    std::vector<uint8_t> key{ 1,2,3,4,5,6,7,8 };
    auto hash1 = Botan::HashFunction::create("SHA-256");
    hash1->update(key);
    std::cout << "SHA-256: " << Botan::hex_encode(hash1->final()) << std::endl;
    return 0;
}
```
on windows Im getting error:
![error](https://github.com/randombit/botan/assets/64229593/21c5ede9-77f7-48a3-950a-becfab8a7ce3)

somehow weird is that i have on debugger this info, suggesting that maybe botan is not properly included?:
![debugger](https://github.com/randombit/botan/assets/64229593/501707d8-0681-43c1-9c41-66ce0a06a7b9)

That's my setup in Visual Studio:
![dir_vssetup](https://github.com/randombit/botan/assets/64229593/58231d43-40e2-4f08-ab91-887a1378eeea)
![lib_included](https://github.com/randombit/botan/assets/64229593/5ea68ccf-eecf-47b3-b190-be8f27ee7b65)

It's worth mentioning that building the same sample on Ubuntu went without any errors, and SHA was calculated as expexted

I'm using:
Microsoft Visual Studio Community 2022 (64-bit) - 17.8.3
Microsoft Visual C++ 2022
Windows 10

Thank you in advance for any suggestions!

**Comment by reneme** [comment]
> weird is that i have on debugger this info, suggesting that maybe botan is not properly included?

Are you referring to: "no symbols loaded for Botan-3.dll"? That doesn't mean that the library was not found. Just that the debugger didn't find any debugging information. Hence, it cannot properly resolve symbols in your call stack. The library itself seems to be found just fine.

Anyway: You're most likely seeing the `nullptr` exception because `HashFunction::create()` wasn't able to construct a SHA-256 object (which is surprising). Could you please try again with `HashFunction::create_or_throw()`?

**Comment by PL-Aurora** [comment]
I have rebuilt Botan with `--cc=msvc --os=windows --with-debug-info` flags so now symbols are loaded, but initial problem still happens.

I have tried with `HashFunction::create_or_throw()` but result is literally the same.

What's more, I tried another functionality to apply:

`Botan::AutoSeeded_RNG rng;`
`auto group = std::make_unique<Botan::DL_Group>(rng, Botan::DL_Group::Strong, 2048);`

and it ended that the application "stucks":

![stuck](https://github.com/randombit/botan/assets/64229593/2f1b8682-823b-43e2-a21b-136d677b2c69)

results of rebuild:

![build_warnings](https://github.com/randombit/botan/assets/64229593/8277fb81-a088-449e-b300-98d4c255b662)

Maybe there is something specific in Botan options while building or using in projects which I missed? I'm also running pretty much the same code on Linux, and everything works just fine.

**Comment by PL-Aurora** [comment]
No, I'm sure that there is exact version of DLL that i built as a result of those manuals:
[https://botan.randombit.net/handbook/building.html](url)
[https://github.com/randombit/botan/wiki/Adding-Botan-to-your-build](url)

**Comment by reneme** [comment]
Mhh, strange. I'm trying to reproduce... Any chance you could share your Visual Studio Solution or a small reproducer of it?

**Comment by reneme** [comment]
I think I found the problem!

I configured a fresh Visual Studio project along the lines of your screenshots. Also, I regenerated my botan installation (in `C:\Botan`) with `python3 configure.py --cc=msvc --os=windows`. This results in a Release-build of the library.

However, a fresh Visual Studio project builds a Debug-build by default. Linking the botan build (in Release mode) with the Visual Studio project (in Debug mode), produces exactly the same error you initially pointed out.

You have two options:

1. Build your Visual Studio project in Release-mode (you'll need to re-configure the search paths and library dependencies)
2. Build botan in Debug-mode (by configuring with `configure.py ... --debug-mode`) and re-install to `C:\Botan` or a different location using `configure.py .. --prefix=C:\Botan-debug`

**Comment by PL-Aurora** [comment]
Yes! I have finally managed to accomplish this on windows, great!:
![saviour](https://github.com/randombit/botan/assets/64229593/c02e901b-6a6c-4e3d-ab98-7bca5ccfc1cb)
you were right! that's solves the problem, thank you so much!

I had no clue that this would be the problem, but you helped me, Thanks again! :)

**Comment by reneme** [comment]
You're welcome. Good luck with your project using Botan.

**Comment by securitykernel** [comment]
@reneme Not sure mixing debug and release artifacts is not supported? But maybe we should add a hint to https://github.com/randombit/botan/wiki/Adding-Botan-to-your-build#visual-studio.
