### ISSUE TITLE
Support for Ed448 and X448

### ISSUE THREAD

**Issue by falko-strenzke** [randombit/botan#3895]
Neither Ed448 nor X448 is currently implemented in Botan. These algorithms are used in the multi-algorithm combinations in the current version of the [draft for PQC in OpenPGP](https://datatracker.ietf.org/doc/draft-wussler-openpgp-pqc/). RNP already implements this draft using Botan as its crypto backend. It would be great if Botan also supported the Curve448 algorithms in order to enable the full spectrum also in RNP and Thunderbird.

**Comment by randombit** [comment]
I personally find X448 kind of pointless, in that the only way X25519 or P-256 are being broken is with a quantum computer, and if a QC that can break X25519 can be constructed, then X448 is likely to fall shortly after.

That said it is used (somewhat) and I wouldn't be opposed to patches adding it, given the explicit project goal of supporting protocols that are used in practice. (No plans to work on this personally, however.)
