### ISSUE TITLE
Add BLAKE2b support

### ISSUE THREAD

**Issue by cynecx** [randombit/botan#390]
It would be nice to have BLAKE2 as a addition to SKEIN since both are SHA-3 candidates.
If it is okay I would be happy to provide needed patches.

**Comment by randombit** [comment]
Technically BLAKE2 was not a SHA-3 candidate (BLAKE was) but BLAKE2b in particular does seem somewhat popular in new applications and is already listed into the todo file.

I am not sure if we want all the complexities of the tree hashing modes etc (and even if we do, supporting this would require some non trivial design/API work to expose it to callers) but a plain iterative BLAKE2b hash should be easy to slot in to the existing design and could be the base for adding support for the rest later on.

**Comment by randombit** [comment]
For a plain init-update-final mode the existing hash functions (esp Skein) should provide a good example. It looks like BLAKE2b has a simple keying mode, feel free to include support for that if you like (totally optional, I would accept it with or without keying).

Pass at least the one test vector from RFC 7963 Appendix A H("abc"), and hopefully more vectors taken from another implementation. Having the long test in RFC 7963 Appendix E would be great also.

**Comment by cynecx** [comment]
I will try to get a pull request ready at the weekend for BLAKE2b.

**Comment by cynecx** [comment]
https://github.com/randombit/botan/pull/413
