### ISSUE TITLE
add --cc-standard to force a cpp compiler version

### ISSUE THREAD

**Issue by netplus** [randombit/botan#3903]
Hi, 
I have a project that be compiled using c++14, I'd like to compile botan with c++14 also, so I set the a cc-abi-flags by 
configure.py --cc-abi-flags='-std=c++14', the final compile parameter result in -std=c++14 -std=c++11. I checked the Makefile , And I found that cc-abi-flags is followed by LANG_FLAGS which has -std=c++11 there. 

Is it ok to add a option in configure.py to specify a cpp standard to meet this kind of request ?

if it is ok to add the feature, I'd like add it in my projects, and I'd be happy to provide the patch once tested.

**Comment by reneme** [comment]
Hi! Perhaps you could try `./configure.py --extra-cxxflags=-std=c++14`. This places your custom flag behind botan's default, and should override it.

**Comment by netplus** [comment]
It's very nice of you to providing such a helpful option, it match my requirement exactly .

**Comment by reneme** [comment]
Happy to help!
