### ISSUE TITLE
Missing Implementation of `botan_cipher_is_authenticated()` in ffi.h.

### ISSUE THREAD

**Issue by aahajj** [randombit/botan#3904]
Hello everyone, 
I've encountered an issue regarding the [int botan_cipher_is_authenticated(botan_cipher_t cipher)](https://botan.randombit.net/handbook/api_ref/ffi.html#_CPPv429botan_cipher_is_authenticated14botan_cipher_t) function within Botan's Symmetric Ciphers documentation for ffi.h (C Bindings). Despite referencing the documentation, I cannot find an implementation of this function. 

Just for the record, I'm using the latest stable release:

```bash
./botan version
3.2.0
```

Could someone please clarify whether this function is indeed missing or if there's an alternative method to achieve the same functionality? Thank you.

**Comment by reneme** [comment]
Yes, I can confirm that. Must be an oversight. Will look into that, thanks for reporting.

**Comment by reneme** [comment]
As a workaround for the time being, please use `botan_cipher_get_tag_length()`. If that's greater than 0, your cipher is an AEAD and, thus, authenticated. The missing predicate function would just be a convenience wrapper for the same check, anyway.

**Comment by aahajj** [comment]
Alright, thank you! :)
