### ISSUE TITLE
Getting "bignum is negative" from ssh_agent using Botan generated RSA keys

### ISSUE THREAD

**Issue by droidmonkey** [randombit/botan#3928]
Hello, this is a bit of a shot in the dark, but our users (and our own CI) are starting to report anomalies when adding generated RSA keys to ssh_agent. The ssh_agent outputs an error message stating the "bignum is negative" and refuses the key. This just started happening recently with no code changes to the relevant bits on our side. We suspect this may be related to a library change, Botan is the obvious one in this case.

Background issue: https://github.com/keepassxreboot/keepassxc/issues/10320

Relevant KeePassXC code:

https://github.com/keepassxreboot/keepassxc/blob/dff2f186ce0e063df5842731631c0f8e8c2af0e6/src/sshagent/OpenSSHKeyGen.cpp#L51-L82

``` C++
bool generateRSA(OpenSSHKey& key, int bits)
    {
        auto rng = randomGen()->getRng();

        try {
            Botan::RSA_PrivateKey rsaKey(*rng, bits);

            QByteArray publicData;
            BinaryStream publicStream(&publicData);
            // intentionally flipped n e -> e n
            bigIntToStream(rsaKey.get_e(), publicStream);
            bigIntToStream(rsaKey.get_n(), publicStream, 1);

            QByteArray privateData;
            BinaryStream privateStream(&privateData);
            bigIntToStream(rsaKey.get_n(), privateStream, 1);
            bigIntToStream(rsaKey.get_e(), privateStream);
            bigIntToStream(rsaKey.get_d(), privateStream);
            bigIntToStream(rsaKey.get_c(), privateStream, 1);
            bigIntToStream(rsaKey.get_p(), privateStream, 1);
            bigIntToStream(rsaKey.get_q(), privateStream, 1);

            key.setType("ssh-rsa");
            key.setCheck(randomGen()->randomUInt(std::numeric_limits<quint32>::max() - 1) + 1);
            key.setPublicData(publicData);
            key.setPrivateData(privateData);
            key.setComment("id_rsa");
            return true;
        } catch (std::exception& e) {
            return false;
        }
    }
```

Was the RSA code recently changed in Botan?

Is there something we can do to prevent negative big numbers?

**Comment by reneme** [comment]
There was indeed a change that may be relevant. Did you update to 2.19.4?

**Comment by reneme** [comment]
Interesting. The change I had in mind (#3909) was released more recently (2.19.4 and 3.3.0). Thanks for reporting, I will look into it.

**Comment by droidmonkey** [comment]
I'll attempt to roll back botan to see if that resolves it. I wouldn't necessarily rule out an ssh-agent change as well. Although Google turned up nothing.

**Comment by droidmonkey** [comment]
Come to find out, thank you @reneme, this is probably on us. Not sure if botan wants to include a flag to zero pad bignums to prevent the MSB from possibly causing a "negative" number. I'll leave it up to you guys to close this if you don't want to implement something like that.

**Comment by reneme** [comment]
> Not sure if botan wants to include a flag to zero pad bignums to prevent the MSB from possibly causing a "negative" number.

Technically, we have this already. Quoting the docstring of `BigInt::binary_encode()`:

https://github.com/randombit/botan/blob/b84acd926d1ccc78524c69aee5d53279b9a5e361/src/lib/math/bigint/bigint.h#L654-L664

... i.e. if you pass in a buffer that is longer than `BigInt::bytes()`, the buffer is zero-padded. Though, looking at the code, this might be flawed. I'll look into that and potentially submit a fix and extend the documentation as to why such a zero-padding may be desirable.

**Comment by reneme** [comment]
> Though, looking at the code, this might be flawed.

False alarm, it works as expected. @droidmonkey Your `bigIntToStream` might as well be implemented like that:

```C++
void bigIntToStream(const Botan::BigInt& i, BinaryStream& stream, int padding = 0)
{
    QByteArray ba(i.bytes() + padding, 0);
    i.binary_encode(reinterpret_cast<uint8_t*>(ba.data()), ba.size());
    stream.writeString(ba);
}
```

... letting Botan take care of the zero-padding. That said, your implementation is perfectly valid as is.

**Comment by droidmonkey** [comment]
Oh neat, thank you!
