### ISSUE TITLE
OS X bzip compression problem

### ISSUE THREAD

**Issue by randombit** [randombit/botan#394]
The entropy tests are occasionally failing on OS X, for example:

https://travis-ci.org/randombit/botan/jobs/100203704

The problem is always due to an exception while compressing the entropy outputs with bzip2 (calling BZ2_bzCompress) The error is -1, `BZ_SEQUENCE_ERROR`, which bzip2 uses to indicate an out of order operation of flags. But it only fails periodically, and only on OS X - I've never seen this elsewhere (either on Linux CI or any Linux/BSD system I have tried).

I have no idea if this a bug in the library, in the OS X bzip library, or what.

**Comment by webmaster128** [comment]
Does the problem occur for other entropy sources than darwin_secrandom as well?

**Comment by randombit** [comment]
I've also seen fail compressing the timestamp values

**Comment by webmaster128** [comment]
New fail with darwin_secrandom: https://travis-ci.org/randombit/botan/jobs/100555080

**Comment by randombit** [comment]
Pure speculation: it may also be somehow input specific (which is why it only sometimes occurs given the entropy values change between runs) and something about compressing the concatenation of these values is triggering a bug in bzlib on OS X.

**Comment by webmaster128** [comment]
New fail with darwin_secrandom: https://travis-ci.org/randombit/botan/jobs/101584198

Still speculating: I don't really think it is triggered by random data only. If it was triggered by `darwin_secrandom`, it would explain the OS X only fact too.

**Comment by randombit** [comment]
Closing. This will remain one of lifes little mysteries.
