### ISSUE TITLE
aes_neon module is not presesnt

### ISSUE THREAD

**Issue by YogitaChandrawanshi** [randombit/botan#3943]
as per documentatiom of botan https://botan.randombit.net/handbook/hardware_acceleration.html
aes_neon need to be enabled for hardware accelaration of botan for arm architecure.
But i can not see any moduled named aes_neon in botan 2.12.1 & 2.19.3

**Comment by reneme** [comment]
True, that's a typo in the documentation! The module is called `aes_armv8` (like all the other hardware accelerations for NEON).
Thanks for reporting.
