### ISSUE TITLE
Doxygen output includes full file paths

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3986]
Noticed this when diffing the output of the website changes for the 3.4 release

```
-  <div class="headertitle"><div class="title">/home/jack/var/tmp/botan_website_0a3uuq24/build/module_info/aes.dox File Reference</div></div>
+  <div class="headertitle"><div class="title">/home/jack/var/tmp/botan_website_7896_t1q/build/module_info/aes.dox File Reference</div></div>
```

Not critical but I'd like to fix this for the future.

**Comment by KaganCanSit** [comment]
I rarely use Doxygen. But I want to help with this. Can you direct me?

Currently, I configured the project with configure.py and created doxygen files with botan.doxygen.

When I searched under the "botan/build/docs/doxygen" directory (grep -r "/home/jack" .) I could not find any content.

But when I searched the whole project from the main folder, I found it at another point. Just wanted to let you know.

`../../../src/scripts/rewrite_lcov.py: # SF:/home/jack/work/botan/build/include/botan/pkix_types.h`

**Comment by reneme** [comment]
Thanks for looking into this! If you build the doxygen documents on your system it will likely prefix paths with the directory structure of your system. 

Depending on where you might have checked out the repository, you should grep for this base path. 😊

**Comment by KaganCanSit** [comment]
When I created the files in the "botan/build/docs/doxygen" location without changing the "botan.doxygen" file, I could not find any path for my own user in this folder. I forgot to write. 😊

![image](https://github.com/randombit/botan/assets/59123356/66c3e2bf-2698-40f6-96d0-b928d057342e)

**Comment by reneme** [comment]
Mmh, another shot in the dark: perhaps that shows up only when the build script is called as an absolute path.

**Comment by KaganCanSit** [comment]
Without changing the configuration file, I basically made my calls as follows;
`sudo doxygen build/botan.doxy`

However, when I try from a few other directories, I get an error regarding the doxygen directory and the process does not take place. A few sample attempts;
(in the build directory) `sudo doxygen botan.doxy`
(in the build/docs directory) `sudo doxygen ../botan.doxy`
(from a parent directory of the botan folder) `sudo doxygen botan/build/botan.doxy` 

The result is the same for now;
warning: tag INPUT: input source './src/lib' does not exist
warning: tag INPUT: input source 'build/build.h' does not exist
warning: tag INPUT: input source 'None' does not exist
error: tag OUTPUT_DIRECTORY: Output directory 'build/docs/doxygen' does not exist and cannot be created

**Comment by randombit** [comment]
Possible factor here is that for the website, doxygen is invoked via `src/scripts/website.py` which is the script that generates the website, PDF docs, etc.

**Comment by KaganCanSit** [comment]
Hello again @randombit, @reneme;
I made a change to the issue here. If you guide by checking. I would love to help and improve myself.
Best regards.
