### ISSUE TITLE
build failure on armv7 with latest 3.4.0 release

### ISSUE THREAD

**Issue by david-geiger** [randombit/botan#4001]
Hi,

On Mageia Cauldron latest 3.4.0 release now fails to build on armv7 with the following issue:

`In file included from build/include/public/botan/curve25519.h:11,
                 from src/lib/compat/sodium/sodium_25519.cpp:9:
build/include/public/botan/pk_keys.h: In destructor 'virtual constexpr Botan::Public_Key::~Public_Key()':
build/include/public/botan/pk_keys.h:119:30:   in 'constexpr' expansion of 'Botan::Public_Key::~Public_Key()'
build/include/public/botan/pk_keys.h:119:30: internal compiler error: in cxx_eval_call_expression, at cp/constexpr.cc:3242
  119 | class BOTAN_PUBLIC_API(2, 0) Public_Key : public virtual Asymmetric_Key {`

Attached full build log:
[build.armv7hl.0.20240410234110.log](https://github.com/randombit/botan/files/14938973/build.armv7hl.0.20240410234110.log)

**Comment by randombit** [comment]
An internal compiler error should be reported upstream to GCC; we're not in much of a position to fix a GCC issue.

**Comment by randombit** [comment]
Known GCC 14 regression on arm https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114426
