### ISSUE TITLE
Dead assignment in test_gf2m.cpp

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#401]
In https://github.com/randombit/botan/blob/master/src/tests/test_gf2m.cpp#L57

The variable `xl_j_tt_5` is never read. It's really hard to understand whats going on here because of the cryptic variable and function names but i assume the input to `field.gf_mul_nrr()` in line 58 should be `xl_j_tt_5` instead of `xl_gray_tt_3` otherwise the whole line can be removed?!

**Comment by randombit** [comment]
The `xl_j_tt_5` variable is later used in `gf2m_decomp_rootfind_state::calc_Fxj_j_neq_0` which is where this code sequence comes from. Here in the test it is probably an actual dead store but I'd have to walk through the math again to be sure.
