### ISSUE TITLE
Amalgamation SHA3 missing

### ISSUE THREAD

**Issue by Tectu** [randombit/botan#4031]
Not sure what I'm doing wrong but after upgrading from Botan 2.8 to 3.4.0, SHA3 does not seem to be part of the amalgamation output.

Excerpt from `build_all.h`:
```
/**
* @file  build.h
* @brief Build configuration for Botan 3.4.0
*
* Automatically generated from
* 'configure.py --quiet --cc-bin=/usr/bin/clang++ --cc=clang --disable-shared --amalgamation --minimized-build --enable-modules=sha3'
*
* Target
*  - Compiler: /usr/bin/clang++ -fstack-protector -m64 -pthread -std=c++20 -D_REENTRANT -O3
*  - Arch: x86_64
*  - OS: freebsd
*/
```

However, the `SHA_3` types/classes do not appear to be part of the generated output file.
Other modules such as `system_rng` or `argon2` seem to work fine just as before.

Running `configure.py --list-modules` does show `sha3` as an option.

Any ideas?

**Comment by reneme** [comment]
As mentioned in the [migration guide](https://github.com/randombit/botan/blob/master/doc/migration_guide.rst) we removed direct access to the algorithm implementation classes for applications. Please use `HashFunction::create_or_throw("SHA-3")` to get an instance of the SHA-3 hash.

**Comment by Tectu** [comment]
Thanks - That was helpful!

Running the risk of embarrassing myself a 2nd time: I have grepped that `migration_guide.rst` for a third time now and I still couldn't find an obvious reference that the new way is to use `HashFunction::create_or_throw()`.
