### ISSUE TITLE
Cipher Mode : Process and Finish are Confusing

### ISSUE THREAD

**Issue by TxMat** [randombit/botan#4060]
Hi,

I'm pretty new to Botan and i don't understand fully the difference between process and finish when encrypting or decrypting a message.

For instance here is a part of my code for decrypting a ChaCha20Poly1305 encoded message using `process` and everything works

```c++
// Decrypt the challenge using ChaCha20
  Botan::SymmetricKey skey(key.data(), key.size());

  const auto decrypt_cipher = Botan::AEAD_Mode::create_or_throw("ChaCha20Poly1305", Botan::Cipher_Dir::Decryption);

  std::vector<uint8_t> nonce(encrypted_msg.begin(), encrypted_msg.begin() + 12);

  std::vector<uint8_t> ciphertext(encrypted_msg.begin() + 12, encrypted_msg.end());

  decrypt_cipher->set_key(skey);
  decrypt_cipher->start(nonce);
  decrypt_cipher->process(ciphertext); // use of process, everything works

  std::cout << decrypt_cipher->name() << " with nonce " << Botan::hex_encode(nonce) << ": " << Botan::hex_encode(ciphertext.data(), ciphertext.size(), false) << '\n';
  std::cout << "Decrypted challenge Raw: ";
  for (uint8_t byte : ciphertext) {
    std::cout << static_cast<int>(byte) << " ";
  }
  std::cout << std::endl;
```

However, when encrypting, i have to use `finish` as the poly1305 tag is not appended to the message when using process

```c++
  Botan::SymmetricKey skey(key.data(), key.size());

  const auto encrypt_cipher = Botan::AEAD_Mode::create_or_throw("ChaCha20Poly1305", Botan::Cipher_Dir::Encryption);

  std::vector<uint8_t> nonce = generate_random_nonce();
//  std::vector<uint8_t> nonce {12,12,12,12,12,12,12,12,12,12,12,12}; // debug

  encrypt_cipher->set_key(skey);
  encrypt_cipher->start(nonce);
  encrypt_cipher->finish(plaintext); // process does not work

  std::cout << "Processed msg : ";
  for (uint8_t byte : plaintext) {
    std::cout << static_cast<int>(byte) << " ";
  }
  std::cout << std::endl;
```

Should I always use finish ? Should i first call to process then finish ? what is the correct way of using it ?

I did not find anything in the doc saying which one should be used when :

![image](https://github.com/randombit/botan/assets/46858765/e9686336-cc6c-4dec-9356-1ee2ed7923ea)

![image](https://github.com/randombit/botan/assets/46858765/33826ce2-bf53-444e-975e-f20a614c0332)

Thanks for your time.

**Comment by randombit** [comment]
Sorry, I know this is confusing. The cipher API is kind of weirdly designed. I didn't realize our documentation was that non-specific though, thanks for pointing this out.

You should *always* call `finish`, either when encrypting or decrypting.

In fact you can get away with never calling `process`, it exists just for efficiency when dealing with larger messages. It's perfectly fine/correct/easy to just call `start` with the nonce then immediately `finish` with a buffer containing the entire message.

For your decryption example, things maybe "work" but probably not quite as you're thinking. What's happening is the Poly1305 authentication tag (final 16 bytes) is being decrypted and emitted as if it was part of the message, and so you're both not checking the tag (which allows arbitrary forgeries) but also ending up with 16 bytes of extra junk at the end. Maybe if you're only looking at the first <X> bytes of the plaintext this was not obvious.
