### ISSUE TITLE
Somehow load_{be,le} of integer without offset doesn't work

### ISSUE THREAD

**Issue by randombit** [randombit/botan#4080]
In most cases it doesn't matter much but when there is a lone `load_be(array, 0)` it would be nicer if we could omit the index.

https://github.com/randombit/botan/pull/4056#discussion_r1618336576

@reneme can you take a look?

**Comment by reneme** [comment]
The index may be omitted when actually passing an array. In the case at hand we did try to pass a raw pointer, though. This overload does not exist. #4085 switches to using a range-based overload.
