### ISSUE TITLE
How to implement TLS 1.3 session resumption?

### ISSUE THREAD

**Issue by cmazakas** [randombit/botan#4091]
I'm writing a unit test to check that with my localhost server setup, I can successfully reuse all the handshake data for subsequent clients.

I have a test right now that spawns 10 TCP clients and connects to a localhost server. Everything works great, the server presents a valid certificate, the client checks it against the registered CA, I can send messages back and forth, it's awesome.

However, I've added this to my `TLS::Callbacks` implementation:
```cpp
void
tls_session_established( Botan::TLS::Session_Summary const& session ) override
{
  std::cout << "was this session a resumption? => " << std::boolalpha
            << session.was_resumption() << std::endl;
}
```
and I notice that only _one_ TLS session is ever resumed here!

For all the other client connections, all I see is `false`. I have my code setup so that the very first client completes its entire exchange with the peer before disconnecting.

I'm using the `Session_Manager_In_Memory`. Am I supposed to be manually storing the session stuff? If so, I'm not sure why I see `true` for the most immediate client connection and then false for the rest.

I've looked into how manually `store()` session info and it seems a little confusing to me.

I'm assuming that I'll need to use both of these callbacks in tandem and this is what's currently in my project:
```cpp
bool
tls_should_persist_resumption_information(
    Botan::TLS::Session const& session ) override
{
  return true;
}

void
tls_session_established( Botan::TLS::Session_Summary const& session ) override
{
  std::cout << "was this session a resumption? => " << std::boolalpha
            << session.was_resumption() << std::endl;
}
```

**Comment by cmazakas** [comment]
I figured it out!
Turns out, you need to update the `Botan::TLS::Policy` class to enable this feature!

```cpp
struct tls_policy final : public Botan::TLS::Policy
{
  bool
  reuse_session_tickets() const override
  {
    return true;
  }

  ~tls_policy() override;
};

tls_policy::~tls_policy() = default;
```
this is all a user has to do and then et voila, I now see that all my TLS resumptions are happening as I'd expect.

**Comment by cmazakas** [comment]
Interesting. Why increase the amount of usable session tickets vs just enable their reuse?

**Comment by cmazakas** [comment]
Alright, sounds good to me then!
I'll think about how to add this to a public API in a way that won't immediately make users groan.

**Comment by reneme** [comment]
Note that TLS 1.3 allows sending session tickets at any time after the handshake is complete. See the API in `TLS::Server`: https://github.com/randombit/botan/blob/5649a10ec3399d28c8b84ae18fd65fce57bd7bca/src/lib/tls/tls_server.h#L86-L87

You could simply provide a wrapper for this, instead of (or additionally to) some more complicated configuration construction.

**Comment by cmazakas** [comment]
btw, as always, thanks for the help, @reneme 
I really appreciate.
This library is fantastic, and I appreciate the guidance in learning how to use it effectively.
