### ISSUE TITLE
MSVC 19.40 miscompilation/crash

### ISSUE THREAD

**Issue by randombit** [randombit/botan#4103]
GH actions builds started failing recently. I've been seeing occasional crashes in CI, which retries fixed. Now they seem to be becoming more extensive

> INFO: Auto-detected compiler version msvc 19.39

Works fine

> INFO: Auto-detected compiler version msvc 19.40

  Command '.\botan-test --data-dir=.\src\tests\data --run-memory-intensive-tests --test-results-dir=junit_results --report-properties=ci_target:static,os:windows' failed with error code 3221225477

**Comment by randombit** [comment]
Possibly related: https://github.com/actions/runner-images/issues/10004

**Comment by randombit** [comment]
Combo Visual C++ and Github fuckup #4105

**Comment by reneme** [comment]
Yikes! I saw the occasional MSVC fails as well. Probably we should start trusting our CI setup more and investigate earlier... 😇

Hopefully this CI issue doesn't become a long-standing feature as the previous clang problem. 😨
