### ISSUE TITLE
Namespace Botan has no member

### ISSUE THREAD

**Issue by shreyas-shivapuji** [randombit/botan#4139]
I'm continuously getting an error while working with Botan in vscode. I updated the includePaths and did not get any error while including a header file (for instance say auto_rng.h). But when I try accessing a member (say Botan::AutoSeeded_RNG), I get an error saying the Botan namespace has no such member. 

OS: MacOS (Installed botan through homebrew)

**Comment by randombit** [comment]
Is this error coming from the compiler, or an autocomplete error? If a compiler error please provide the full compiler invocation and output

**Comment by shreyas-shivapuji** [comment]
The error is from the compiler : namespace "Botan" has no member "DL_Group" C/C++(135)

![image](https://github.com/randombit/botan/assets/121794313/a7e4819f-7daa-428b-be58-81b10ca16a23)

**Comment by shreyas-shivapuji** [comment]
The issue is resolved @randombit. The cpp-standard had to be upgraded to C++20 (was C++17 initially), as many of the header files used functions exclusively available from C++20.
