### ISSUE TITLE
GetTickCount64 in es_win32.cpp

### ISSUE THREAD

**Issue by nazar554** [randombit/botan#416]
Is it safe to remove `GetTickCount64` call in `es_win32.cpp`?. I am creating a package for MSYS2 and this function is not compatible with Windows versions before Vista (because `_WIN32_WINNT` is defined). https://github.com/Alexpux/MINGW-packages/pull/1040 this is my current patch.

It looks like entropy provided by it is not too important. Am I right?

**Comment by randombit** [comment]
Yes the entropy this function is providing is quite minimal (and is counted as producing nothing at all, in terms of the entropy estimate) and could be removed without harm. On modern systems the system RNG (CryptGenRandom here) is the primary source of seed material, and the rest more or less acts as a supplement or nonce to guard against catastrophic failures. So even disabling es_win32 entirely from the build is probably not a problem (though better to just remove the offending call and leave the rest, IMO).

Am I understanding correctly from the maintainer's comment in the issue you posted that MinGW maintains ongoing support for XP even though it is EOLed and does not receive any security updates? Do you happen to know if there is an official policy on this; it kind of sounds like for MinGW we are stuck with XP-only APIs for the forseeable future?

**Comment by nazar554** [comment]
New MinGW versions provide access to lots of Windows 7+ functions but it seems that MSYS2 project itself intends to support old Windows versions. So I think its more like they want MSYS2 and packages to work on Windows XP.
I am going to remove `GetTickCount64` call.

**Comment by randombit** [comment]
Good to know, thanks
