### ISSUE TITLE
current master fails to build docs

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#4184]
MacOS Sonoma 14.5, Xcode-15.4, Python-3.12.

```text
$ make docs
"/opt/local/bin/python3" "src/scripts/build_docs.py" --build-dir="build"
   INFO: Starting sphinx-build -q -c ./src/configs/sphinx -j auto -W --keep-going -b html ./doc build/docs/handbook
   INFO: Starting sphinx-build -q -c ./src/configs/sphinx -j auto -W --keep-going -b latex ./doc /var/folders/gn/nbv4dk8j2m94ly04yqdhy8kh0000gn/T/botan_latex_f7z7t343
/Users/ur20980/src/botan/doc/dev_ref/next_major.rst: WARNING: document isn't included in any toctree
  ERROR: Error running sphinx-build -q -c ./src/configs/sphinx -j auto -W --keep-going -b latex ./doc /var/folders/gn/nbv4dk8j2m94ly04yqdhy8kh0000gn/T/botan_latex_f7z7t343
make: *** [build/doc.stamp] Error 1
$ 
```

Please let me know what info would help fixing this problem, and I'll be happy to provide. Configuration results attached: [conf-out.txt](https://github.com/user-attachments/files/16119641/conf-out.txt)

### Update
Interestingly, when after receiving the above error I `cd /var/folders/gn/nbv4dk8j2m94ly04yqdhy8kh0000gn/T/botan_latex_f7z7t343` and manually run `make` there, it builds `botan.pdf` successfully. ???

But this still does not help installation, because `make install` depends on the failing make `docs` target.

**Comment by randombit** [comment]
Hm, interesting, I thought we had a docs CI target that would have noticed this. Maybe this got lost at some point.

**Comment by randombit** [comment]
Oh this was `[ci skip]` I guess that would do it! Should be fixed now
