### ISSUE TITLE
Botan Thread == 1 handling and Emscripten side effects

### ISSUE THREAD

**Issue by Trafo** [randombit/botan#4195]
Hi,

my team and I had some troubles with the current Botan Threadpool implementation. For us, it was surprising that those Thread pools exist. We integrated Botan inside of Emscripten, but not using unbounded web workers, because they are not supported everywhere yet. Because of that, we need to do thread management on our own. But this conflicts with the Botan thread pool, which is not in our hands. For us, the solution is to deactivate Botan's thread pool.
I would suggest making this a default setting for Emscripten ([here](https://github.com/randombit/botan/blob/bb9c069a2688065bf354356190156a34cbce98d2/src/lib/utils/thread_utils/thread_pool.cpp#L17)) because other botan users can encounter the same problems. It can be very tricky to find the issue because it only becomes an issue in case Argon2 for example was used. I would prefer that the Botan user opt-in to the Multithreading option in the case of Emscripten, like already been done in the case of MinGW.

In the case of the Argon2 implementation, an edge case exists, where the ThreadPool will be created but not used. This will be the case if only one thread is configured for the Argon2 algorithm. ([here](https://github.com/randombit/botan/blob/bb9c069a2688065bf354356190156a34cbce98d2/src/lib/pbkdf/argon2/argon2.cpp#L344))

In general, I am not a big fan of Botan organizing a thread pool in the background which is hidden from Botan users. I am not sure if it is feasible, but I would prefer that the caller of an API, where multi-threading is beneficial and supported, can configure it on demand. I still do not get the use case of a Thread Pool inside Botan. Because most systems don't care about the number of threads and in the case of systems which care it is troublesome, because Botan can unintentionally conflict with other ThreadPools.
A solution for the last described problem could be, that Botan can use external ThreadPools, which can be connected to Botan via an API as suggested [here](https://github.com/randombit/botan/issues/4194).

Thanks for this amazing library! And thx to all the contributors. I enjoy working with botan, whenever I work with it, and I like the latest changes for example regarding including std::span into the API. I look forward to seeing coroutine support :)

[EDIT] I tried to clarify the text more.

**Comment by reneme** [comment]
Trying to unpack a few concrete suggestions and/or potential TODOs here:

* [ ] **Disable the `Thread_Pool` on web platforms by default** (see [`global_thread_pool_size()`](https://github.com/randombit/botan/blob/bb9c069a2688065bf354356190156a34cbce98d2/src/lib/utils/thread_utils/thread_pool.cpp#L17-L40))
   _Note: when this function returns `std::nullopt`, the `Thread_Pool` object will be instantiated, but it won't spawn any worker threads and all scheduled work is simply run synchronously -- see [the `m_workers.empty()` case](https://github.com/randombit/botan/blob/bb9c069a2688065bf354356190156a34cbce98d2/src/lib/utils/thread_utils/thread_pool.cpp#L105-L118)_

* [ ] **Don't even instantiate a `Thread_Pool` when the algorithm won't have anything to parallelize** (e.g. Argon2 w/ `threads=1`)
   _I actually consider the current behaviour **a bug**. In [`argon2.cpp, process_blocks()`](https://github.com/randombit/botan/blob/bb9c069a2688065bf354356190156a34cbce98d2/src/lib/pbkdf/argon2/argon2.cpp#L328-L361) we **always** spawn a `Thread_Pool`, and then just not use it when `threads = 1`_

* [ ] **Allow users to customize how async work is offloaded**
      _Essentially #4194_

Did I miss something, @Trafo?

**Comment by reneme** [comment]
> I look forward to seeing coroutine support :)

For what its worth: You can use Botan's TLS via boost ASIO with full support for coroutines, today! [Here is an example of a minimal HTTPS client](https://github.com/randombit/botan/blob/master/src/examples/tls_stream_coroutine_client.cpp) using ASIO and Beast where Botan provides the TLS implementation. As a counter-part, Botan's CLI features a [simple HTTPS test server](https://github.com/randombit/botan/blob/master/src/cli/tls_http_server.cpp) using the same tech stack.

Do you have other use cases in mind that could benefit from coroutines in the public API?

**Comment by Trafo** [comment]
@reneme No you perfectly summarized my gibberish.

Our application is not using the ThreadPool at all, because we are using Argon2 with the thread=1 configuration, but it still will be created, which already causes problems for us.

As a little add-on, I would like to question in general the usage of a thread pool inside of Botan, because I see only problems and not so much benefits. And in case it is useful, we definitely should have an option of customizing the botan thread pool from the outside.

**Comment by randombit** [comment]
> I would like to question in general the usage of a thread pool inside of Botan, because I see only problems and not so much benefits

For relevant algorithms it often is a 2-4x improvement in performance. KeepassXC recently adopted Botan for all of their crypto *except* continuing to use `libargon2` for Argon2, solely because the version of Botan included in Debian stable did not support multithreading Argon2, and this caused visible performance regressions for users.

**Comment by randombit** [comment]
> but it still will be created, which already causes problems for us.

Also worth noting that if the thread pool is generally problematic/unhelpful on this platform you can easily disable it completely at build time with `--disable-modules=thread_utils`

**Comment by randombit** [comment]
#4199 addresses the first two issues. The ability to offload to an application provided executor will come in a different PR

**Comment by Trafo** [comment]
@randombit Thx for the changes.

I can see the benefits. Especially in the case of dicing a new RSA key things can become faster. And I find the option to support multi-thread support in nowadays world very important. I am just not sure if an internal ThreadPool is the right approach. But of course, it is just my opinion and I might not have the overview of all use cases and just judge out of my own problem bubble.

**Comment by Trafo** [comment]
Thx for the fast problem-solving!
