### ISSUE TITLE
[OS X] Amalgamation breaks memset_s

### ISSUE THREAD

**Issue by tiwoc** [randombit/botan#42]
To use memset_s, one must first `#define __STDC_WANT_LIB_EXT1__ 1` before including `string.h`. This is done in `src/lib/utils/zero_mem.cpp`, so its use of `memset_s` should work just fine if the file is compiled by itself.

However, there are other locations in Botan where string.h is included. When generating the amalgamation, these files might occur before the contents of `zero_mem.cpp`. For me, this is the case with `src/lib/entropy/dev_random/dev_random.cpp`, where `string.h` is included without first defining `__STDC_WANT_LIB_EXT1__`.

There are currently three places where <string.h> is included without first defining the flag:

* src/lib/entropy/dev_random/dev_random.cpp
* src/lib/pubkey/curve25519/donna.cpp
* src/lib/rng/system_rng/system_rng.cpp

## Proposed solutions

Some possible solutions I could come up with:

1. Include the following code near the bottom of `src/build-data/buildh.in`:

  ```
  #if defined(BOTAN_TARGET_OS_HAS_MEMSET_S)
    #define __STDC_WANT_LIB_EXT1__ 1
  #endif
  ```
2. Copy the code from 1. to every place where `string.h` is included.

3. Define some header (for example `botan_string.h`) that contains the above code and `#include <string.h>`, in this order. Replace all other inclusions of `string.h` with `botan_string.h`.

## Discussion of the solutions

1. This is not great for users of Botan because it defines the flag in `botan_all.h`, so that it might interact with unrelated client code.

2. This would only change `botan_all.cpp`, but introduce some repetion, which is bad for maintenance.

3. Probably the cleanest solution.

Any opinions on this issue? I'm willing to send in a pull request.

**Comment by webmaster128** [comment]
Same problem without amalgamation. In a [regular OSX build](https://gist.github.com/webmaster128/24224e1becd423d47afe) the same error occurs, because `src/lib/utils/zero_mem.cpp` first includes `botan/mem_ops.h`, which includes `<cstring>`, which (I guess) includes `string.h`.

Btw.: Wouldn't it be a good idea to standardize the include file for c-strings? See also [Difference between string.h and cstring?](https://stackoverflow.com/questions/8380805/difference-between-string-h-and-cstring)

**Comment by webmaster128** [comment]
https://github.com/randombit/botan/commit/9a0da0565c042c0f0a09caed036621c47e3f494e seems to fix the issue.

**Comment by randombit** [comment]
848314e1 creates a single location including string.h/cstring in mem_ops.h. I'd take a patch adding back memset_s using approach 3 but am not going to do it myself as I can't test it.

**Comment by webmaster128** [comment]
I think this is out of scope as stated in #48.
