### ISSUE TITLE
Building botan fails with vs2022 preview 4.0

### ISSUE THREAD

**Issue by learn-more** [randombit/botan#4250]
MSVC version: `Version 17.11.0 Preview 4.0`
CL version: `Version 19.41.34021`

```
D:\src\cert-view\vendor\botan\build\build\include\internal\botan/internal/pcurves_id.h(59): error C2039: 'string': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.41.34021\include\__msvc_string_view.hpp(22): note: see declaration of 'std'
D:\src\cert-view\vendor\botan\build\build\include\internal\botan/internal/pcurves_id.h(59): error C3646: 'to_string': unknown override specifier
D:\src\cert-view\vendor\botan\build\build\include\internal\botan/internal/pcurves_id.h(59): error C2059: syntax error: '('
D:\src\cert-view\vendor\botan\build\build\include\internal\botan/internal/pcurves_id.h(59): error C2238: unexpected token(s) preceding ';'
../src/lib/math/pcurves/pcurves.cpp(128): error C2039: 'to_string': is not a member of 'Botan::PCurve::PrimeOrderCurveId'
```

This seems to be caused by `pcurves_id.h` including `string_view`, but using `std::string`.
If I change the include from `#include <string_view>` to `#include <string>` then it builds fine.

Note: on the non-preview version of vs2022 it builds without issue, so this seems to be something that changed in the preview version.

Build config used:
```batch
mkdir botan\build
pushd botan\build
python3 ../configure.py --cc=msvc --os=windows --build-tool=ninja --prefix=install --disable-shared-library --debug-mode
ninja install
popd
```

**Comment by randombit** [comment]
Thanks! Interesting that all of the builds missed this until now. Fixed on master

**Comment by learn-more** [comment]
Somewhere between these 2 versions the `string_view` header was changes:
![string_view](https://github.com/user-attachments/assets/2d58929a-83b9-45aa-912e-96fcc71735a2)
