### ISSUE TITLE
[C++] Botan build failed with error C2039

### ISSUE THREAD

**Issue by JonLiu1993** [randombit/botan#4278]
Hello, I'm a member of Microsoft VCPKG, when I built botan:x64-windows in an internal version of Visual Studio, it failed with following errors:
````
build\include\internal\botan/internal/pcurves_id.h(57): error C2039: 'string': is not a member of 'std'
````
This issue caused by the STL PR: https://github.com/microsoft/STL/pull/4633, and according to the recommendations of the STL developers, the affected files need to include the Standard <string> header.

I have applied this change in vcpkg by https://github.com/microsoft/vcpkg/pull/40192. Since this VS internal version has not been released yet, I am submitting this issue just to inform you.

**Comment by randombit** [comment]
Thank you for the report. On master this has already been resolved #4250 so I’m closing this as completed.
