### ISSUE TITLE
#include <botan/x25519.h> causes error when compiling with clang (version 3.5.0)

### ISSUE THREAD

**Issue by gjvanderheiden** [randombit/botan#4292]
version: 3.5.0
clang: 18.1.8
OS: Arch Linux

When I include <botan/x25519.h> I get an error:
`/usr/include/botan-3/botan/x25519.h:116:1: error: an attribute list cannot appear here
  116 | BOTAN_DEPRECATED_API("Use X25519_PrivateKey or Sodium::crypto_scalarmult_curve25519_base")
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/botan-3/botan/compiler.h:37:45: note: expanded from macro 'BOTAN_DEPRECATED_API'
   37 | #define BOTAN_DEPRECATED_API(msg) BOTAN_DLL BOTAN_DEPRECATED(msg)
      |                                             ^~~~~~~~~~~~~~~~~~~~~
/usr/include/botan-3/botan/compiler.h:125:34: note: expanded from macro 'BOTAN_DEPRECATED'
  125 |    #define BOTAN_DEPRECATED(msg) [[deprecated(msg)]]
      |                                  ^~~~~~~~~~~~~~~~~~~`

If I alter line 37 in botan/compiler.h (sourcecode: src/lib/utils/compiler.h) as it is in the master branch it works fine.
master:
`
#define BOTAN_DEPRECATED_API(msg) BOTAN_DEPRECATED(msg) BOTAN_DLL
`
3.5.0:
`
#define BOTAN_DEPRECATED_API(msg) BOTAN_DLL BOTAN_DEPRECATED(msg)
`

**Comment by randombit** [comment]
Sorry about that. You can work around this by defining `BOTAN_NO_DEPRECATED_WARNINGS` in the file that includes `x25519.h` (just has to be before any other botan header is included)

**Comment by gjvanderheiden** [comment]
Don't be sorry, just wanted to report it. Thanks for the workaround.
