### ISSUE TITLE
Try to build on Windows 

### ISSUE THREAD

**Issue by Fxztam** [randombit/botan#4304]
I try to build Botan on Windows 10 and after  `python configure.py --cc=msvc --os=windows` 👍 

 I get on `nmake`

`build/include/public\botan/types.h(16): fatal error C1083: File (Include) cannot open: "cstddef": No such file or directory`

What is wrong, please?

Fried

**Comment by randombit** [comment]
> cannot open: "cstddef": No such file or directory

This seems to indicate a problem with how your compiler is installed. Are you able to build code normally with the command line? You may need to run a batch like `vcvarsall.bat` - see https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170

**Comment by randombit** [comment]
Closing this, if you are still having problems feel free to reopen
