### ISSUE TITLE
NIST PQC Final Standards

### ISSUE THREAD

**Issue by p-barabas** [randombit/botan#4308]
Hi, 

on 13.Aug. 2024 NIST has published final PQC standard ( FIPS 203-205): 
https://csrc.nist.gov/publications/fips 

Is it planned to update Botan library with differences and to be able to use algorithms by defined standards?

Thanks in advance for your response.

**Comment by reneme** [comment]
Yes! We're on it in context of [the BSI Project 481](https://github.com/randombit/botan/issues/3108):

* https://github.com/randombit/botan/pull/3893
* https://github.com/randombit/botan/pull/4270
* https://github.com/randombit/botan/pull/4291

Currently these open pull requests contain implementations of the IPD-versions but they'll be updated (and hopefully merged) before the next planned release in October.

**Comment by reneme** [comment]
The mentioned algorithm implementations are now merged and slated for release in Botan 3.6.0 next week. The signature algorithms ML-DSA and SLH-DSA won't support the pre-hash mode and will lack support for the application-defined "context" string. Those features will be implemented in a later release. See: https://github.com/randombit/botan/issues/4376
