### ISSUE TITLE
visual studio botan lib pdb is missing  after compilation.

### ISSUE THREAD

**Issue by agrandville** [randombit/botan#432]
The makefile generate it but it's immediatly replaced when compiling the botan.exe. 
I've found a workaround changing the app output file from botan.exe to botan-cli.exe in the Makefile (CLI = .\botan-cli.exe).

**Comment by randombit** [comment]
Oh, unfortunate.

I wonder if there is some command line flag to tell MSVC to output the PDB for the CLI file to some other location to avoid the overwrite, or to skip it entirely. The PDB for the command line is probably not particularly useful for most people.

**Comment by neusdan** [comment]
There is a compiler option `/Fd` 

https://msdn.microsoft.com/en-us/library/9wst99a9.aspx

and a linker option `/PDB`

https://msdn.microsoft.com/en-us/library/kwx19e36.aspx

not sure which is the right one.

**Comment by agrandville** [comment]
I think /Fd flag is used to specify the output folder during compilation, the /PDB file locate the final pdb file.  
I do some test and obtain the best result with this change in my Makefile  
LIB_LINK_CMD   = $(LINKER) /DLL /DEBUG /PDB:botanlib.pdb

**Comment by neusdan** [comment]
Can be closed now.

**Comment by randombit** [comment]
Thanks
