### ISSUE TITLE
Failing to build on Windows MinGW-w64 64-bit system

### ISSUE THREAD

**Issue by ForceBru** [randombit/botan#434]
I downloaded the latest version of Botan, installed gcc version 5.3.0 and python 3.4.3. Then I ran `python configure.py --os=mingw`. The script complained that I should add the `--disable-shared` option. I've done it and everything configured OK.

So, I typed `make`. Everything went good until the file called `src/lib/entropy/win32_stats/es_win32.cpp`. 

Here's the error message:

```sh
src/lib/entropy/win32_stats/es_win32.cpp: In member function 'virtual void Botan::Win32_EntropySource::poll(Botan::Entropy_Accumulator&)':
src/lib/entropy/win32_stats/es_win32.cpp:23:29: error: 'GetTickCount64' was not declared in this scope
    accum.add(GetTickCount64(), BOTAN_ENTROPY_ESTIMATE_SYSTEM_DATA);
```

**Edit:** the same happens if I set `--os` to `windows`.

Botan 1.10.12 compiled successfully, but seems to lack `secure_vector`, which I'm using in my [project](https://brute.tk). Under Linux and Mac OS everything builds very well.

Could you please help me to fix this error?

**Comment by ForceBru** [comment]
Finally I managed to solve this: I had to do `make CXXFLAGS="-D_WIN32_WINNT=0x0600 -std=c++11 -O3"`. MinGW seems to override `_WIN32_WINNT` for some reason.

**Comment by neusdan** [comment]
The call to GetTickCount64 was removed in ee7f93a but this is not yet released.
