### ISSUE TITLE
Referred Z-Botan package seems abandoned

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#4345]
https://botan.randombit.net/ site lists several available packages in various languages supporting access to Botan via FFI (https://github.com/randombit/botan/wiki/Language-Bindings).

For Haskell it lists Z-Botan package https://hackage.haskell.org/package/Z-Botan, which appears to have been abandoned. It definitely does not track the current Botan-3, and does not support any of the PQ algorithms.

Perhaps, you want to replace that pointer with another package, maybe something like https://github.com/haskell-cryptography/botan?

**Comment by randombit** [comment]
Bumped Z-Botan to the abandoned group and added a link to the other package
