### ISSUE TITLE
How to access ML-KEM?

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#4346]
Please forgive my ignorance. I thought that the current master included the updates of Kyber Round 3 to ML-KEM, but all I can find via API seems to be "Kyber-<XXX>-r3", not "ML-KEM-<XXX>".

Am I not looking in the right place, or is ML-KEM support just not there yet? If not there - could you share your plans for merging it in? Thanks!

**Comment by reneme** [comment]
It's currently implemented in a pull request: #3893. We're hoping to merge it soon and integrate it into the upcoming release 3.6.0 in October.
