### ISSUE TITLE
Diffie-Hellman group generator

### ISSUE THREAD

**Issue by agrandville** [randombit/botan#436]
I would like to generate my own DH generator, but my code doesn't work, the call to the Botan::DL_Group never ends.

my code
```cpp
Botan::RandomNumberGenerator* rng = Botan::RandomNumberGenerator::make_rng();
//Botan::DL_Group group("modp/ietf/1024");
//std::unique_ptr<Botan::Private_Key> key(new Botan::DH_PrivateKey(*rng, group)); 

size_t pbits = 1024;
Botan::DL_Group* genGrp = new Botan::DL_Group(*rng, Botan::DL_Group::Strong, pbits); //never returns ?!?!
```

any idea ?

**Comment by randombit** [comment]
It should terminate eventually but may be quite slow. I just tried it via the command line (botan gen_dl_group --type=strong), it took 522 seconds to return on my laptop (Linux, x86-64).

The algorithm used is pretty simplistic (generate random prime, check if 2*p+1 is also prime), maybe there is a faster method.

**Comment by agrandville** [comment]
sorry, I was too impatient.
