### ISSUE TITLE
MSVC Compiler Flags Incorrectly Passed to Linker (Regression)

### ISSUE THREAD

**Issue by TriceHelix** [randombit/botan#4424]
This is a regression of https://github.com/randombit/botan/issues/2209.

Configure using these flags:
`--os=windows --cc=msvc --disable-shared-library --msvc-runtime=MT`
...and build. This produces the following linker error:
`LINK : fatal error LNK1146: no argument specified with option '/MT'`

It seems identical to the issue from 5 years ago and occurs on version 3.6.1 (lastest release).

**Comment by reneme** [comment]
Confirmed. This is being addressed as a side-fix in #4255. Perhaps we should extract that and merge it independently, @randombit?

**Comment by randombit** [comment]
Fixed in #4452
