### ISSUE TITLE
Heap Corruption at Destructor Kyber_PrivateKey (Botan 3.6.1)

### ISSUE THREAD

**Issue by kre-medisoftware** [randombit/botan#4428]
I get a Heap Corruption at the Destructor of Kyber_PrivateKey.
```

Botan::AutoSeeded_RNG random;
Botan::Kyber_PrivateKey* m_kyberPrivateKey = new Botan::Kyber_PrivateKey(random, Botan::KyberMode::Kyber768_R3);
delete (m_kyberPrivateKey);
```
![grafik](https://github.com/user-attachments/assets/d3966bc4-af88-45cd-8c4f-540fdf6c2917)

the build-paramaters of Botan 3.6.1 are (amalgamation-mode)
`python3 configure.py --cc=msvc --os=windows --prefix=%cd% --cpu=x86 --msvc-runtime=MT --amalgamation --disable-shared-library`

Is this a known problem?

**Comment by randombit** [comment]
Certainly not a known issue

After building did you run the test suite?

**Comment by kre-medisoftware** [comment]
no i did not. 
how can i easily build the test suite. i'm use the amalgamation-mode.

**Comment by randombit** [comment]
Amalgamation should not matter one way or another.

From the working directory where you built the library

`nmake tests`

then

`./botan-test`

**Comment by kre-medisoftware** [comment]
i am sorry. 
Building the tests, first had some build errors. So i had to rebuild botal_all.cpp.
Finally the tests runs without any errors. 
With this amalgamation-Build my own application even has no more exceptions.

The issue can be closed. thanks a lot
