### ISSUE TITLE
Typo on http://botan.randombit.net/ - "may also prove useful resources."

### ISSUE THREAD

**Issue by shlomif** [randombit/botan#443]
Hi,

I was not able to find the source repository of the site anywhere or I would have sent a pull req.
Anyway, on http://botan.randombit.net/ "may also prove useful resources" should be "may also prove as useful resources". Please correct it.

Regards,

-- @shlomif .

**Comment by cordney** [comment]
You'll find the source of the website in [readme.rst](https://github.com/randombit/botan/blob/master/readme.rst) (start page) and in [doc/](https://github.com/randombit/botan/tree/master/doc).

**Comment by shlomif** [comment]
Thanks @cordney!

**Comment by randombit** [comment]
Fixed by merging #448 thanks

**Comment by shlomif** [comment]
Thanks @randombit ! And you're welcome.
