### ISSUE TITLE
Build of Botan 3.6.1/3.7.0 still failing with LNK1146 error

### ISSUE THREAD

**Issue by ronchristie52** [randombit/botan#4451]
Hi all,

Just cloned the latest version of Botan and tried to build an x86 static library using the following configure line:

python3 configure.py --cpu=x86_32 --build-tool=ninja --cc=msvc --disable-shared-library --msvc-runtime=MT --libdir=c:\botan\Botan-3.6.1.1\Release
ninja
ninja check
ninja install

The build fails with:

LINK : fatal error LNK1146: no argument specified with option '/MT'

when attempting to build botan-cli.exe and botan-test.exe.

When these builds fail, then ninja stops the process and it never gets to the install step.

**Comment by randombit** [comment]
@ronchristie52 Can you try the patch in #4452?

**Comment by randombit** [comment]
Fixed by #4452
