### ISSUE TITLE
RSA signature verification with 1017 bit key crashes

### ISSUE THREAD

**Issue by mneffgen** [randombit/botan#4465]
The Reason is an insufficient buffer size created at `pk_ops.cpp`:

```
std::vector<uint8_t> PK_Ops::Encryption_with_EME::encrypt(std::span<const uint8_t> msg, RandomNumberGenerator& rng) {
   const size_t max_raw = max_ptext_input_bits();
   secure_vector<uint8_t> eme_output((max_raw + 7) / 8);  // insufficient size
   size_t written = m_eme->pad(eme_output, msg, max_raw, rng);
   return raw_encrypt(std::span{eme_output}.first(written), rng);
}
```

The check `BOTAN_ASSERT_NOMSG(output.size() >= input.size());` in `EME_Raw::pad()` fails.

Changing the buffer size to `(max_raw + 7) / 8 + 1` fixes the problem.

Probably the error occurs for all keys with `size % 8 = 1`. 
We use various and exotic key sizes for testing purposes.

**Comment by randombit** [comment]
Can you post a complete test case? Checking a set of vectors generated by OpenSSL with keys in range 1024..1056 I cannot replicate this.

**Comment by randombit** [comment]
Use `PK_Verifier` to verify signatures, the encryption == verification thing is true for (unpadded) RSA on a mathematical level but it is not treated the same in practice.

Also do note that we already support ISO 9796 signature verification: either of these work already

```
   Botan::PK_Verifier ver(botanKey, "Raw");
   printf("accept = %d\n", ver.verify_message(dsi, signature));

   Botan::PK_Verifier iso_ver(botanKey, "ISO_9796_DS2(SHA-256,imp,32)");
   printf("accept = %d\n", iso_ver.verify_message({}, signature));
```

**Comment by mneffgen** [comment]
We need it for testing purposes. That is why we use the low level algorithm and unusual key sizes.
