### ISSUE TITLE
ML-DSA fails the FIPS 204 ACVP signature verification test vectors

### ISSUE THREAD

**Issue by strongX509** [randombit/botan#4496]
We are currently adding ML-DSA support to the existing strongSwan **`botan`**  plugin (see our [ml-dsa](https://github.com/strongswan/strongswan/tree/ml-dsa) branch on github). Unfortunately the [FIPS 204 ACVP signature verification test cases](https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json) (tcId: 1, 20, 31) fail. Thus we are wondering whether the **botan-3.6.1** library correctly implements the final FIPS 204 standard.

The same ACVP test vectors work fine with the strongSwan **`wolfssl`** plugin using the **wolfssl-5.7.4-stable** library, so that we are quite sure that the generic strongSwan  ML-DSA wrappers are correct. We are using the **` ffi.h`** C-language interface to integrate the botan code into our strongSwan code.

We are not sure what constant string to use for the **`hash_and_padding`** argument of the **`botan_pk_op_verify_create()`** function for the ML-DSA case without pre-hashing. We have a similiar question for the **`botan_pk_op_sign_create()`** function where we want to use Randomized signatures. For the existing Ed25519 case we used **`Pure`** both for signature generation and verification, so for the time being we use the same string for the ML-DSA case.
```
int botan_pk_op_verify_create(botan_pk_op_verify_t* op,
                              botan_pubkey_t key,
                              const char* hash_and_padding,
                              uint32_t flags);

int botan_pk_op_sign_create(botan_pk_op_sign_t* op,
                             botan_privkey_t key, 
                            const char* hash_and_padding,
                             uint32_t flags);
```
On the positive side the [FIPS 204 ACVP key generation test cases](https://github.com/usnistgov/ACVP-Server/blob/master/gen-val/json-files/ML-DSA-keyGen-FIPS204/internalProjection.json) (tcID: 1, 26, 51) are correct and our own roundtrip tests (private/public key generation / signature generation / signature verfication) using the **botan-3.6.1** library work.

**Comment by strongX509** [comment]
The **`hash_and_padding`** settings have been resolved.  **`Randomized`** and **`Pure`** work fine for signature generation and signature verification, respectively.

The failure of the FIPS 204 ACVP signature verification test cases is still persistent.

**Comment by randombit** [comment]
On the contrary, it seems that neither ACVP nor WolfSSL correctly implement the full ML-DSA

Specifically, ML-DSA introduces a context string, which is by default empty. However even if empty, the message representative `mu` must include the empty length field associated with the context (see Algorithm 2 of FIPS 204).

If I modify our ML-DSA implementation to skip including the context string header then the verification succeeds.

It seems this is already a known issue with the ACVP test data https://github.com/usnistgov/ACVP-Server/issues/375 which is (for some absolutely unfathomable reason) testing "the internal interfaces" ie not the full signature scheme....

**Comment by randombit** [comment]
You can find BoringSSL's test vectors for ML-DSA at

https://github.com/google/boringssl/blob/master/third_party/wycheproof_testvectors/mldsa_65_standard_verify_test.json
https://github.com/google/boringssl/blob/master/third_party/wycheproof_testvectors/mldsa_87_standard_verify_test.json

BoringSSL correctly implements the ML-DSA context string encoding, and we correctly process (accept/reject) all of their test cases.

**Comment by strongX509** [comment]
Thanks for the quick feedback. So the ACVP test suite misses  the ctx Header

10: 𝑀′ ← BytesToBits(IntegerToBytes(0, 1) ∥ IntegerToBytes(|𝑐𝑡𝑥|, 1) ∥ 𝑐𝑡𝑥) ∥ M

of  the external ML-DSA.Sign(𝑠𝑘, 𝑀, 𝑐𝑡𝑥) (Algorithm 2) interface. Good to know since I'm currently coding our own ML-DSA implementation. I see that the PQ-Crystals source code correctly implements the ctx header:
```
  /* Prepare pre = (0, ctxlen, ctx) */
  pre[0] = 0;
  pre[1] = ctxlen;
  for(i = 0; i < ctxlen; i++)
    pre[2 + i] = ctx[i];```
```
