### ISSUE TITLE
Unable to build for windows c++

### ISSUE THREAD

**Issue by naushadck** [randombit/botan#4498]
Followed the steps https://botan.randombit.net/handbook/building.html#on-windows

Produced the following error. (nmake)

      cl /DBOTAN_DLL=__declspec(dllexport)  /Zc:preprocessor /std:c++20 /EHs /GR /D_WIN32_WINNT=0x0600 /MD /bigobj /O2 /Oi /Zc:throwingNew /W4 /wd4251 /wd4275 /wd5072 -DBOTAN_IS_BEING_BUILT  /I build/include/public /I build/include/internal  /external:W0 /external:I build/include/external /nologo /c src/lib/asn1/alg_id.cpp /Fobuild/obj/lib/asn1_alg_id.obj
alg_id.cpp
build/include/public\botan/build.h(506): fatal error C1189: #error:  "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
NMAKE : fatal error U1077: 'cl /DBOTAN_DLL=__declspec(dllexport)  /Zc:preprocessor /std:c++20 /EHs /GR /D_WIN32_WINNT=0x0600 /MD /bigobj /O2 /Oi /Zc:throwingNew /W4 /wd4251 /wd4275 /wd5072 -DBOTAN_IS_BEING_BUILT  /I build/include/public /I build/include/internal  /external:W0 /external:I build/include/external /nologo /c src/lib/asn1/alg_id.cpp /Fobuild/obj/lib/asn1_alg_id.obj' : return code '0x2'
Stop.

Help is highly appreciated....

**Comment by reneme** [comment]
> Trying to compile Botan configured as x86_64 with non-x86_64 compiler.

This is a shot in the dark: perhaps you tried to build for x86-64 using an x86 MSVC? Typically that happens if you accidentally open the Microsoft development console with the wrong environment.

**Comment by naushadck** [comment]
i added  --cpu=-x86_32 as follows. It worked. 

py configure.py --cc=msvc --os=windows --cpu=-x86_32

The error shown as follows -
ERROR: Configured target is x86_64 but compiler probe indicates x86_32

Once added --cpu=-x86_32,  it worked. 

Thank you.
