### ISSUE TITLE
How to create private key using cli

### ISSUE THREAD

**Issue by naushadck** [randombit/botan#4499]
1. Can i know, if it is possible to generate the private key with EC secp256k1  using cli. 

2. I could not find the tls_server parameter with cli. I could see the tls_server.cpp and tls_clinet.cpp under cli folder.

**Comment by randombit** [comment]
1. `botan keygen --algo=ECDSA --params=secp256k1`
2. Details please. What did you try to do? What happened?

**Comment by naushadck** [comment]
1. botan keygen --algo=ECDSA --params=secp256k1

      Worked  Super.    Thanks. 

2. The following commands from cli did not work. 
             botan-cli tls_server
             botan-cli tls_client

**Comment by randombit** [comment]
> did not work

In what way?

**Comment by naushadck** [comment]
Nope. Did not work. Error messages as follows. 

Unknown command tls_server (try --help)

Unknown command tls_client (try --help)

**Comment by randombit** [comment]
How did you build the library? The exact invocation to configure.py is reflected in build.h

**Comment by naushadck** [comment]
1. Cloned the repository 
2. Opened the VS Dev prompt.
3. py configure.py --cc=msvc --os=windows --cpu=-x86_32
4. nmake

This was generated static and dynamic library. Then the botan-cli.exe.

**Comment by randombit** [comment]
Ah I forgot, those currently only support BSD sockets and not Winsock2, so they are not available on Windows. If you add Boost support there are a couple other TLS utils based on asio.
