### ISSUE TITLE
OSX can not compile amalgamation using clang

### ISSUE THREAD

**Issue by FengLinqing** [randombit/botan#45]
The version I use is commit 7e6ac35931ed073d01c96d212bba5c7674cba505 and
botan_all files are generated by "./configure.py --gen-amalgamation --cc=clang"

I got the following errors while compling with clang:
./xx/botan_all.h:13260:40: error: unknown type name 'McEliece_PrivateKey'
      McEliece_Private_Operation(const McEliece_PrivateKey& mce_key);
                                       ^
../xx/botan_all.h:13270:3: error: unknown type name 'McEliece_PrivateKey'
  McEliece_PrivateKey const& get_key() const { return m_priv_key; };
  ^
../xx/botan_all.h:13270:23: error: expected member name or ';' after declaration specifiers
  McEliece_PrivateKey const& get_key() const { return m_priv_key; };

../xx/botan_all.h:13273:13: error: unknown type name 'McEliece_PrivateKey'
      const McEliece_PrivateKey m_priv_key;
            ^
../xx/botan_all.h:13279:35: error: unknown type name 'McEliece_PublicKey'
  McEliece_Public_Operation(const McEliece_PublicKey& public_key, u32bit code_length);
                                  ^
../xx/botan_all.h:13284:3: error: unknown type name 'McEliece_PublicKey'
  McEliece_PublicKey const& get_key() const { return m_pub_key; };
  ^
../xx/botan_all.h:13284:22: error: expected member name or ';' after declaration specifiers
  McEliece_PublicKey const& get_key() const { return m_pub_key; };
  ~~~~~~~~~~~~~~~~~~ ^
../xx/botan_all.h:13287:3: error: unknown type name 'McEliece_PublicKey'
  McEliece_PublicKey m_pub_key;
  ^
../xx/botan_all.h:20354:2: error: #endif without #if
#endif
 ^
../xx/botan_all.cpp:17170:30: error: unknown type name '__m256i'
inline void interleave_epi64(__m256i& X0, __m256i& X1)
                             ^
../xx/botan_all.cpp:17170:43: error: unknown type name '__m256i'
inline void interleave_epi64(__m256i& X0, __m256i& X1)
                                          ^
../xx/botan_all.cpp:17175:10: error: unknown type name '__m256i'
   const __m256i T0 = _mm256_unpacklo_epi64(X0, X1);
         ^
../xx/botan_all.cpp:17176:10: error: unknown type name '__m256i'
   const __m256i T1 = _mm256_unpackhi_epi64(X0, X1);
         ^
../xx/botan_all.cpp:17182:32: error: unknown type name '__m256i'
inline void deinterleave_epi64(__m256i& X0, __m256i& X1)
                               ^
../xx/botan_all.cpp:17182:45: error: unknown type name '__m256i'
inline void deinterleave_epi64(__m256i& X0, __m256i& X1)
                                            ^
../xx/botan_all.cpp:17184:10: error: unknown type name '__m256i'
   const __m256i T0 = _mm256_permute4x64_epi64(X0, _MM_SHUFFLE(3,1,2,0));
         ^
../xx/botan_all.cpp:17185:10: error: unknown type name '__m256i'
   const __m256i T1 = _mm256_permute4x64_epi64(X1, _MM_SHUFFLE(3,1,2,0));
         ^
../xx/botan_all.cpp:17198:10: error: unknown type name '__m256i'
   const __m256i ROTATE_1 = _mm256_set_epi64x(37,19,36,46);
         ^
../xx/botan_all.cpp:17198:29: error: use of undeclared identifier '_mm256_set_epi64x'
   const __m256i ROTATE_1 = _mm256_set_epi64x(37,19,36,46);
                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

It appears that the location of class McEliece_PrivateKey is wrong and AVX is accidentally enabled.

**Comment by randombit** [comment]
There is a small bug in the McEliece code that confuses the amalgamation builder. You can work around this now with --disable-modules=mce, or wait for the next release.

Currently when building via the amalgamation all CPU flags required by all enabled modules are set on the build line, so you must explicitly disable use of any extensions you do not want to require (AVX2 here, but also rdrand or AESNI).  This could easily be better, for instance splitting the objects into botan_all_avx2.o, botan_all_ssse3.o, etc, but that's how it works right now.

**Comment by FengLinqing** [comment]
Thanks
