### ISSUE TITLE
Add Argon2 password hashing algo (successor to bcrypt/scrypt)

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [randombit/botan#459]
[Password Hashing Competition](https://password-hashing.net/) just finished and they are selected Argon2 as successor to bcrypt/scrypt algos. It's preferable algorithm for new projects and it may be cosidered as standard (although not as famous as AES and SHA). The [Argon2 implementation](https://github.com/p-h-c/phc-winner-argon2) is pure C99, CC-licensed code. Once it will be stabilised it will be great to make it a part of Botan.

**Comment by randombit** [comment]
Yes this would be great to see, both as a PBKDF for symmetric key derivation and for server password hashing. An internet draft for Argon2 (draft-irtf-cfrg-argon2) is working its way through the CFRG now.  I don't know if there has been yet defined a format for Argon2 passwords in the style of a $2a$ bcrypt hash which encapsulates all of the parameters into a string for db storage, but that would be straightforward to define from the PBKDF.

**Comment by randombit** [comment]
I pushed about ~half of an implementation of Argon2 in https://github.com/randombit/botan/tree/argon2 if someone wants to pick it up.

**Comment by randombit** [comment]
Initial support for Argon2 is available in master now.
