### ISSUE TITLE
Shared libraries are broken on Darwin/OS X

### ISSUE THREAD

**Issue by al45tair** [randombit/botan#467]
Shared libraries are currently broken on Darwin, in a couple of respects.

For those not familiar with the way dylibs work on Darwin, the latter doesn’t rely on `LD_LIBRARY_PATH` or similar, but instead labels each dylib with an _install name_, which is either the full path to the library as installed, or a path including some special symbols. When you later link against a dylib, that install name is copied into your executable, and when the dynamic linker loads the executable it uses the install name to locate the library.

Anyway, in f12d2fbf, @randombit added the commands for building shared libraries on Darwin, specifying `$(LIBDIR)/$(SONAME)` as the install name. Unfortunately, `LIBDIR` isn’t actually set anywhere, so the install name was set as just `/$(SONAME)`, which is always going to be wrong.

Then in 61fe5f70, @webmaster128 changed things so that after linking the `botan` and `botan-test` commands, the `install_name_tool` program got used to change the install name _in those binaries_ to `@executable_path/$(SONAME)`. This makes the `botan` and `botan-test` executables work in their _built_ locations, which is certainly desirable, but not when they’re installed. It also doesn’t fix the problem of linking against the dylib from your own code, where you’ll end up with the (incorrect) install name `/$(SONAME)`.

An additional issue is that dyld, Darwin’s dynamic linker, stores versioning information in the dylib and also in executables linked against it, to prevent executables from running against incompatible dynamic libraries. Botan, right now, isn’t setting that information.

So, I’m proposing that we:

 1. Add a Makefile variable `INSTALLED_LIB_DIR` that points at the install location for library files. I don’t think we should call it `LIBDIR` because there is already a variable of that name in use in the configure script and it doesn’t point at that location. Having two variables of the same (or similar) names that contain different paths is confusing.
 2. Change the install name in the dylib to `$(INSTALLED_LIB_DIR)/$(SONAME_ABI)`.
 3. While keeping the change in 61fe5f70, alter the install script so that it changes the install name on the `botan` executable back again. This means that `botan` can be invoked immediately after building, but it will also work when installed (right now, the copy installed by `make install` does not work because it can’t find the dylib).
 4. Set the current and compatibility versions in the dylib appropriately.

The dylib versions are a slight complication. Darwin defines those versions as being of the form [_x_[._y_[._z_]], where _x_ is a 16-bit number, _y_ is an 8-bit number and _z_ is an 8-bit number, but Botan uses _major_._minor_._abi-ver_._patch_, which won’t fit. It seems to me that the right thing here is to combine _major_ and _minor_ into a single number; I propose:

_x_ = _major_ × 4096 + _minor_
_y_ = _abi-ver_
_z_ = _patch_

thus e.g. 1.11.29.29 becomes 4107.29.29, and then we set the compatibility version to _x_._y_.0 and the current version to _x_._y_._z_, which will allow linking against a dylib of any patch level, but prohibit linking against a different ABI version. _Note that I have assumed that ABI versions are per major/minor version_, which appears to be how the build system assumes things work right now. I’m not certain that’s the right way forward in the longer term, but that’s another issue entirely.

**Comment by webmaster128** [comment]
Is there any specific reason to use the 4096 factor? I think 1000 would be much more human readable, giving us 1011 for 1.11. This gives us 65 mayor and 999 minor versions, assuming 2^16-1 is the maximum for x.

**Comment by webmaster128** [comment]
Do we agree that

> This makes the botan and botan-test executables work in their built locations

means *whenever the library and the executable are in the same directory*? Because this was the initial intent assuming that the user can override the value in his deployment.

I like the idea of overriding the install name in the installation step but I don't see why we need `INSTALLED_LIB_DIR` which acts as a dummy value that is first changed to `@executable_path` at build time and then to the installation path. Given that we can rename `INSTALLED_LIB_DIR` to `INSTALL_NAME_DUMMY` of value `iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi`, right?

**Comment by al45tair** [comment]
> Is there any specific reason to use the 4096 factor? I think 1000 would be much more human readable

I picked that because it's the largest power of two that results in a reasonable range for the major number without unduly limiting the minor number. I can well imagine that Botan might undergo a very large number of minor revisions during its lifetime, but probably very few major ones.

As for changing to using 1000 instead, I have no particular problem with that, though I don't think human readability is actually a particularly big issue for the embedded version numbers — they’re only visible to developers (via `otool -L`) and the version number is already encoded in the filename (as indeed it should be).

> Do we agree that

> > This makes the botan and botan-test executables work in their built locations

> means whenever the library and the executable are in the same directory?

Yes, we do, and I agree that it’s entirely appropriate to set the OS X build up this way.

> I like the idea of overriding the install name in the installation step but I don't see why we need `INSTALLED_LIB_DIR` which acts as a dummy value that is first changed to `@executable_path` at build time and then to the installation path. Given that we can rename `INSTALLED_LIB_DIR` to `INSTALL_NAME_DUMMY` of value `iIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIi`, right?

No. The reason we need to do that is that during the build, we’re setting the install name *of the library*, which *should* default to the final install location. It isn’t acting as a dummy value — we don’t change the install name of the library during installation; what we’re changing at that point is the name that has been encoded into the `botan` binary.

If we don’t do this, then any program that links against the library in (say) `/usr/local/lib/libbotan-1.11.29.dylib` is going to end up with the path set to your `INSTALL_NAME_DUMMY` value — that is, straightforwardly linking against the library will fail, and users would have to explicitly run `install_name_tool` on their linked product to fix that.

Now, I grant you that on OS X there are two separate use cases. The first is treating OS X as a UNIX system and building traditional UNIX-like software; in that case, it’s going to want to use Botan from `/usr/local/lib` or wherever it’s been installed. The *second* use case is where an application developer wants to embed the library, and in that case the developer is going to want to put the dylib in their application bundle, but in *that* case they’ll want to set the install name themselves anyway.
