### ISSUE TITLE
Certificate_Store doesn't match documentation

### ISSUE THREAD

**Issue by al45tair** [randombit/botan#470]
The [documentation](https://github.com/randombit/botan/blob/master/doc/manual/x509.rst) indicates that `Certificate_Store` has `by_SKID`, `by_name` and `by_email` methods, but the code doesn’t have any of these. Additionally it talks about an `X509_Store` class that doesn’t appear to exist.

**Comment by randombit** [comment]
These were removed some time ago, the documentation in this area is pretty badly out of date :(

**Comment by randombit** [comment]
Fixed in 348c9728538e
