### ISSUE TITLE
Bug: mismatch type, TLS_Data_Reader get_u32bit()

### ISSUE THREAD

**Issue by dreamnemo** [randombit/botan#478]
I'm beginner in English.
I think to modify the type... u16bit ==> u32bit

      **u16bit** get_u32bit()
         {
         assert_at_least(4);
         **u16bit** result = make_u32bit(m_buf[m_offset  ], m_buf[m_offset+1],
                                     m_buf[m_offset+2], m_buf[m_offset+3]);
         m_offset += 4;
         return result;
         }

**Comment by randombit** [comment]
Confirmed, thank you. Looks like only usage of `get_u32bit` is for handling TLS session ticket lifetimes (the value of which is not even exposed to applications currently) so impact seems minimal.

**Comment by randombit** [comment]
Fixed, thanks
