### ISSUE TITLE
X942_DH_PARAMETERS in dl_group.h conflicts with macro in wincrypt.h

### ISSUE THREAD

**Issue by lanurmi** [randombit/botan#482]
The enum symbol `DL_Group::Format::X942_DH_PARAMETERS` has the same name as a macro in `c:\Program Files (x86)\Windows Kits\8.1\Include\um\wincrypt.h`. This leads to a compilation error.

Both files get `#include`d through `tls_server.h`, so the problem can be reproduced with one line:
`#include <botan/tls_server.h>`

Renaming `X942_DH_PARAMETERS` to something else in `dl_group.h` fixes the error, but may not be the correct solution.

Environment: VS2015

**Comment by randombit** [comment]
How does wincrypt.h become included as part of tls_server.h? The only includes I can for wincrypt.h or windows.h are in source files, so just that single include should be fine. Though including both CryptoAPI and botan headers in an application is a somewhat reasonable thing, so probably renaming the enum value is the way to go here.

**Comment by lanurmi** [comment]
Ah, my bad, tls_server.h alone doesn't cause the problem. However, if windows.h has been included prior to tls_server.h (as it was through some other library's header in my test case), then there will be an error.

So no bug in Botan per se, but given how widely `<windows.h>` is included in Windows applications, it is a bit unfortunate to have such a naming conflict.

**Comment by Kijewski** [comment]
@lanurmi, I fixed it with
```diff
diff -ru Botan-1.11.30/src/lib/pubkey/dl_group/dl_group.h Botan-1.11.30/src/lib/pubkey/dl_group/dl_group.h
--- ./src/lib/pubkey/dl_group/dl_group.h
+++ ./src/lib/pubkey/dl_group/dl_group.h
@@ -11,6 +11,10 @@
 #include <botan/bigint.h>
 #include <botan/data_src.h>
 
+#ifdef X942_DH_PARAMETERS
+#   undef X942_DH_PARAMETERS
+#endif
+
 namespace Botan {
 
 /**
```
but `-DNOCRYPT` would work for you, too.

**Comment by lanurmi** [comment]
Sure, it is not hard to fix or work around locally, but nevertheless unfortunate that one single line prevents including botan and `<windows.h>` together easily.

**Comment by randombit** [comment]
Took a while, but as part of the final pre-stabilization cleanup I renamed the enum. So this should be fixed now.
