### ISSUE TITLE
TLS1.2 cipher suites accepted in TLS 1.0 / 1.1 connections

### ISSUE THREAD

**Issue by jurajsomorovsky** [randombit/botan#496]
It is possible to establish TLS 1.0 / 1.1 connections with cipher suites that are only standardized for TLS 1.2. Examples give the following ones:

 TLS_RSA_WITH_AES_256_CBC_SHA256
 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
 TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
 TLS_RSA_WITH_AES_128_CBC_SHA256

This is not a direct security critical issue. However, using these secure cipher suites in older protocols could possibly undermine their security. There should be a clear separation of which protocols support which cipher suites.

Found with TLS-Attacker: https://github.com/RUB-NDS/TLS-Attacker
Verification possible e.g. with:
`java -jar TLS-Attacker-1.0.jar client -cipher TLS_RSA_WITH_AES_128_CBC_SHA256 -version TLS10`

**Comment by randombit** [comment]
Thanks. AEAD suites are already excluded from 1.0/1.1 connections so I think all that is required is adding a similar check for HMAC with a hash other than SHA-1

**Comment by randombit** [comment]
Should be fixed with 0048292
