### ISSUE TITLE
FE1 implementation does not provide enough rounds for security

### ISSUE THREAD

**Issue by jamespic** [randombit/botan#500]
A comment in `fpe_fe1.c` notes that the Rogaway, Bellare et al. paper shows that `2+log_a(b)` rounds are sufficient for security, and then notes that the implementation ensures `a >= b`, so 3 should always be sufficient. However, the paper by Rogaway, Bellare et al. assumes that `a <= b`.

**Comment by randombit** [comment]
Thanks for pointing this out.

Picking a >= b is certainly a mistake. Looking over the paper again it's not clear what the effect of this error would be. I have added a parameter to control this so users can adopt the correct version as long as compat is not a problem for them.

With regards to the round count, fortunately for the common scenario of `n` a power of 10, the `a` and `b` will be chosen of the form 200... and 500... in which case `1 + ceil(log_a(n))` is 3. So I think this will not be a big problem in practice. The number of rounds is now configurable and defaults to 5 to provide a good safety margin.

**Comment by jamespic** [comment]
Thanks for looking at this.

Just to answer your question, the impact of the effect is that related plaintexts have related ciphertexts - I became aware of the issue when testing with n a power of 26, and found that ciphertexts looked a bit too similar.
