### ISSUE TITLE
building Botan-1.11.29 on win10 with VS2015 occur error!

### ISSUE THREAD

**Issue by ranqiyu** [randombit/botan#508]
when I run configure.py, it generate a "build" dir,but when input nmake, it occur error,like this:

makefile(1408) : fatal error U1001: syntax error : illegal character '.' in macro
Stop.

so have test on win10 with vs2015?

**Comment by randombit** [comment]
I'm not sure why this would happen. VS 2015 is tested by CI and seems to be working fine. Can you provide the arguments you used to `configure.py` as well as the complete output?

**Comment by greenbioman** [comment]
I got this problem and it was due to g++ not being able to handle the makefile. I added --cc=msvc in the configure.py options and it worked.

**Comment by randombit** [comment]
Should be fixed now as we used a combined makefile for all platforms.
