### ISSUE TITLE
D version of Botan

### ISSUE THREAD

**Issue by etcimon** [randombit/botan#51]
Just wanted to let you know that the [D version of Botan v1.11.10](https://github.com/etcimon/botan) is finished now! I've had a lot of fun translating the architecture which I believe is the most modern and convenient of all, and the D community will benefit from such.

Pros:
- Faster compilation times: 7 seconds vs 70 seconds from a clean make
- No separate header files
- Speeds approx. equal: Powermod unit test at debug times shows this (release is 2x slower with DMD)
- Benefits from a community package manager similar to npm
- No pre-processor (all CTFE) and no python scripts (also CTFE but with the help of dub package manager)
- Backed by a garbage collector

Cons:
- Not GCC/LLVM ready (work in progress in GDC/LDC)
- Only available for x86 / x64
- Moving all new commits manually

I will maintain it myself as well, commit to commit, probably keep a 6 month delay but if anything urgent needs to be mirrored you can always ping me.

This was purely informational, no need to keep this open in the issue tracker.

**Comment by webmaster128** [comment]
Hey  @etcimon, I just came across this ticket and checked you work, seeing that your D version of Botan is still actively maintained.

I am wondering how you can pull changes into your implementation ... Did you re-write the entire codebase? Or is there some kind of automatic translator?

**Comment by etcimon** [comment]
It was entirely hand-written and ported line by line, it required thousands of custom regexes with search & replace on a case by case basis. You can see the commit history here: https://github.com/etcimon/botan-historical/commits/master?page=5

**Comment by etcimon** [comment]
> I am wondering how you can pull changes into your implementation

Changes will be added selectively, I will focus on feature additions and skip any breaking/experimental changes e.g the new algorithm factory. It was mostly a tool for statically compiling my all-D TLS/HTTP2 web server here: https://github.com/etcimon/vibe.d

**Comment by webmaster128** [comment]
First of all: respect. I never used D so I cannot really estimate the value of this.

Still I am a little bit concerned how maintainable this is. I mean we're constantly fixing bugs that might only occur in edge cases so you might have copied them without noticing it. Some of those bugs might affect security. What do you think of those problems?

**Comment by etcimon** [comment]
> Some of those bugs might affect security. What do you think of those problems?

I'm looking through each commit to make sure I find important security threats in the D version as well. In many cases, security was reinforced by the nature of D language being safer, e.g. bounds checking is always on. I think it's an advantage that the D Botan library is a port of C++ Botan and not an entirely new library, because there was going to be a security library in D after I was through with my endeavors.
