### ISSUE TITLE
botan manual  for latest version

### ISSUE THREAD

**Issue by mkawserm** [randombit/botan#511]
Problem Solved: Current manual is not outdated.
Is the current manual outdated? While i am trying to follow this one "https://github.com/randombit/botan/blob/master/doc/manual/filters.rs " for hashing but failed. I don't see anything named Pipe or Hash_Filter in the latest botan source code.

**Comment by randombit** [comment]
The manual is definitely outdated with regards to the devel tree, but these particular types are still available. You can find `Pipe` in `filters/pipe.h` and `Hash_Filter` in `filters/filters.h`

**Comment by mkawserm** [comment]
Got it
