### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [randombit/botan#512]
I would like to point out that an identifier like "[`BOTAN_STREAM_CIPHER_H__`](https://github.com/randombit/botan/blob/00337c4ea2af6b1727be0bdf9b719c98760a14fd/src/lib/stream/stream_cipher.h#L8)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by randombit** [comment]
Thanks. I knew most of these rules but not (to my memory) about any identifier with two consecutive underscores anywhere in it being reserved. Besides the header guards there are a couple of regular variables which also contain `__`. Should be a simple sed to fix. There are a lot of active PRs so can't make this change right now without causing needless conflicts.

**Comment by randombit** [comment]
Fixed now, thanks

**Comment by elfring** [comment]
Thanks for [your improvement of affected included guards](https://github.com/randombit/botan/commit/8731d4920fa8b17374a442d62c2d8c1c6d34967a "Change header guard format to BOTAN_FOO_H_").

How will the software situation evolve further around variables which you mentioned before?

**Comment by randombit** [comment]
Thanks for the followup on that, I had forgotten about that part. Now fixed. Remaining uses of `__` are all for invoking compiler specific code (`__builtin_foo`, `__m128i`, and the like). And I don't believe we violate any of the other reserved identifier rules.
