### ISSUE TITLE
SonarQube integration

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#524]
SonarQube is a tool/service to measure code quality and find technical debt. Their service is free for open source projects. Could you try to set this up Jack?

Here is the link:

https://sonarqube.com

**Comment by randombit** [comment]
Emailed to get an invite

**Comment by cordney** [comment]
There's even quite a nice Travis CI integration for SonarQube: https://docs.travis-ci.com/user/sonarqube/

**Comment by randombit** [comment]
I have an account on their system and can create an API key if someone wants to try the Travis integration (email me). Some setup is required http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner which I have not dug into - this is not a high priority for me.

**Comment by neusdan** [comment]
Thx Jack. I would like to try it. Can you send me the key?
