### ISSUE TITLE
Multiple problems with PKCS#11 addition

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#527]
It builds fine.

However, it appears hardly usable. 

First, there is no documentation whatsoever. It is unclear whether `botan` executable now supports PKCS#11 tokens, and if so - how to use those tokens with commands such as `botan sign ...`

Second, most of the PKCS#11-related tests in `botan-test` fail consistently. It looks like they were designed to *initialize* a token (i.e., cannot test/work with a token that's been already provisioned, like all the tokens that I have)?!

Third - there doesn't seem to be a (documented) way to specify the default location/path of the PKCS11 module (in OpenSC case on Mac OS X `/Library/OpenSC/lib/opensc-pkcs11.so`)? Why does one have to always specify `--pkcs11-lib=...`??

Fourth, tokens tend to have PINs that often are not `123456`. The ability to tell `botan` the PIN seems missing.

Anyway, here's the test output:
```
$ ./botan-test pkcs11-module --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E3CF7EFDBDBA'
Module copy ran 1 tests all ok
Module ctor ran 2 tests all ok
Module info ran 1 tests all ok
Module reload ran 2 tests all ok
Tests complete ran 6 tests all tests ok
$ ./botan-test pkcs11-manage --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E414DAC3BACF'
PKCS11 change pin ran 2 tests all ok
PKCS11 token management test 0 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 5
PKCS11 token management test 1 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 token management test 3 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 5
Tests complete ran 5 tests 3 tests failed
Error: Test error Test suite failure
$ ./botan-test pkcs11-rng --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E3D546189171'
PKCS11 RNG test 0 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 160
PKCS11 RNG test 1 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 160
PKCS11 RNG test 2 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 160
Tests complete ran 3 tests 3 tests failed
Error: Test error Test suite failure
$ ./botan-test pkcs11-rsa --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E3D8DD9759B6'
PKCS11 RSA test 0 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 160
PKCS11 RSA test 1 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 164
PKCS11 RSA test 2 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 164
PKCS11 RSA test 3 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 164
PKCS11 RSA test 4 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 164
PKCS11 RSA test 5 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 164
PKCS11 RSA test 6 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 164
Tests complete ran 7 tests 7 tests failed
Error: Test error Test suite failure
$ ./botan-test pkcs11-slot --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E429BB4B72FC'
Slot ctor ran 2 tests all ok
Slot get_available_slots ran 1 tests all ok
Slot get_mechanism_list ran 1 tests all ok
Slot get_slot_info ran 1 tests all ok
Slot get_token_info ran 1 tests all ok
Slot test 5 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 112
Tests complete ran 7 tests 1 tests failed
Error: Test error Test suite failure
$ ./botan-test pkcs11-session --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E433AFEEAF2C'
Session ctor ran 4 tests all ok
Session release/take ownership ran 1 tests all ok
Session test 2 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 5
Session test 3 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 5
Tests complete ran 7 tests 2 tests failed
Error: Test error Test suite failure
$ ./botan-test pkcs11-x509 --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E43DC7DEAAED'
PKCS11 X509 test 0 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
Tests complete ran 1 tests 1 tests failed
Error: Test error Test suite failure
$ ./botan-test pkcs11-lowlevel --pkcs11-lib=/Library/OpenSC/lib/opensc-pkcs11.dylib
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/Library/OpenSC/lib/opensc-pkcs11.dylib rng:HMAC_DRBG with seed '0000E4464E47EDBC'
PKCS 11 low level - C_CloseAllSessions ran 4 tests all ok
PKCS 11 low level - C_GetFunctionList ran 4 tests all ok
PKCS 11 low level - C_GetInfo ran 5 tests all ok
PKCS 11 low level - C_GetMechanismInfo ran 4 tests all ok
PKCS 11 low level - C_GetMechanismList ran 5 tests all ok
PKCS 11 low level - C_GetSessionInfo ran 7 tests all ok
PKCS 11 low level - C_GetSlotInfo ran 5 tests all ok
PKCS 11 low level - C_GetSlotList ran 10 tests all ok
PKCS 11 low level - C_GetTokenInfo ran 5 tests all ok
PKCS 11 low level - C_Initialize/C_Finalize ran 8 tests all ok
PKCS 11 low level - C_Login/C_Logout ran 16 tests all ok
PKCS 11 low level - C_OpenSession/C_CloseSession ran 16 tests all ok
PKCS 11 low level - C_WaitForSlotEvent ran 4 tests 1 FAILED
Failure 1: C_WaitForSlotEvent fails as expected failed to throw expected exception
PKCS 11 low level - LowLevel ctor ran 2 tests all ok
PKCS11 low level test 13 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 low level test 14 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 5
PKCS11 low level test 15 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 5
PKCS11 low level test 17 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 low level test 18 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 low level test 19 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 low level test 20 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 low level test 21 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
PKCS11 low level test 22 ran 1 tests 1 FAILED
Failure 1: PKCS11 error 84
Tests complete ran 104 tests 10 tests failed
Error: Test error Test suite failure
$
```

**Comment by randombit** [comment]
> It is unclear whether botan executable now supports PKCS#11 tokens, and if so - how to use those tokens with commands such as botan sign ...

No, there is no CLI integration so far. That would be a great addition but nothing in the botan tool knows about tokens yet.

> cannot test/work with a token that's been already provisioned, like all the tokens that I have

I think running the tests against a production token would be a very bad idea, because the tests may do destructive things to the objects on the token. And forcing the the tests start from some (arbitrary and unknown) initial starting point also greatly complicates their lives. Expecting the token to be in an uninitialized state (many hardware tokens use 123456 as their default/uninitialized PIN) prevents the user from doing a Bad Thing to their precious dongles.

In comparison it would be very reasonable for a (hypothetical) `botan pkcs11` command to be able to accept a PIN from the user and work with any already provisioned device.

As to the test failures, error 84 seems to be CKR_FUNCTION_NOT_SUPPORTED (it would be great if the PKCS11_Exception converted the error code to a readable string here...) - perhaps the test is trying to do something which your device does not support?

**Comment by neusdan** [comment]
> I think running the tests against a production token would be a very bad idea, because the tests may do destructive things to the objects on the token. And forcing the the tests start from some (arbitrary and unknown) initial starting point also greatly complicates their lives. Expecting the token to be in an uninitialized state (many hardware tokens use 123456 as their default/uninitialized PIN) prevents the user from doing a Bad Thing to their precious dongles.

+1 

There is also some protecting that prevents the token to get locked if the PIN is not 123456:
https://github.com/randombit/botan/blob/master/src/tests/test_pkcs11.cpp#L31

> First, there is no documentation whatsoever.

Yeah that's true. And we will contribute documentation in the near future. 

> Second, most of the PKCS#11-related tests in botan-test fail consistently.

Wrong PIN or PUK can be one reason for this. But it's also possible that the token or middleware has bugs or unsupported features. You can't blame the PKCS#11 module for this. We've tested with SoftHSMv2, a CardOS token and a Gemalto token where all tests pass. I wouldn't wonder if there are a lot of tests that fail with OpenSC. We've made a lot of tests in our company with OpenSC in the past and had continuously bad experience with it.

> Third - there doesn't seem to be a (documented) way to specify the default location/path of the PKCS11 module (in OpenSC case on Mac OS X /Library/OpenSC/lib/opensc-pkcs11.so)? Why does one have to always specify --pkcs11-lib=...

You just have to specifiy the location to run the PKCS#11 tests. That's a problem? Botan has to know with PKCS#11 middleware to use to run the tests and has nothing to do with the "real use" later on. Then you will pass the path to the middleware module like i've already described:

```Module module( R"(C:\Windows\SysWOW64\myPkcs11Middleware.dll)" );```

> Fourth, tokens tend to have PINs that often are not 123456. The ability to tell botan the PIN seems missing.

Again, that's just to run the tests. If you need to log in to a session with you PIN you can do it with the following method:
https://github.com/randombit/botan/blob/master/src/lib/prov/pkcs11/p11_session.h#L82

**Comment by mouse07410** [comment]
> I think running the tests against a production token would be a very bad idea, because the tests may do destructive things to the objects on the token.

Respectfully disagree. Some people build Botan to work with their existing (apps and) tokens. They would want to know that the code they just built works correctly - they don't necessarily need or want the PKCS#11 part of it to be able to reformat the token, or stand it on its head. 

> And forcing the the tests start from some (arbitrary and unknown) initial starting point also greatly complicates their lives.

As I said, respectfully disagree. If I want this new software to work with my existing precious tokens (rather than buy new tokens to work with this precious software), I better be able to test this software with my existing token - and in a non-destructive way.

To address this, I suggest splitting the tests into two groups: 
- non-destructive tests that I can use to make sure Botan can "work" with my institution-issued token (which neither I not Botan can or should modify), and
- destructive tests that assume complete control over a blank token, and would be used to make sure PKCS#11 module can do *everything*.

> There is also some protecting that prevents the token to get locked if the PIN is not 123456:
https://github.com/randombit/botan/blob/master/src/tests/test_pkcs11.cpp#L31

For whatever reason, it did not work. Since the token I tested it with, was of my own issuance, I could reset the PIN. ;)

> And we will contribute documentation in the near future.

Excellent! Thanks! Looking forward to it.

> Wrong PIN or PUK can be one reason for this. 

I doubt it, since for some invocations I reset the PIN to "123456". Still, no RSA test passed. While applications that sign/verify and encrypt/decrypt using RSA and token, work fine (that includes OpenSSL and native Apple apps such as Safari and Apple Mail).

> But it's also possible that the token or middleware has bugs or unsupported features.

I'm testing it on a PIV token. Not CardOS, not Gemalto-proprietary.

> You can't blame the PKCS#11 module for this. We've tested with SoftHSMv2, a CardOS token and a Gemalto token where all tests pass. I wouldn't wonder if there are a lot of tests that fail with OpenSC. We've made a lot of tests in our company with OpenSC in the past and had continuously bad experience with it.

And for me OpenSC is the only Open Source PKCS#11 middleware that consistently works with PIV tokens, and allows applications on Mac OS X to use certificates on smart cards. I guess our experiences differ. But then, I don't touch Windows - while your development seems to be centered on it.

> You just have to specifiy the location [of PKCS11 module] to run the PKCS#11 tests. That's a problem?

Yes it is a problem when I need to specify location of something that never changes on the platform the code is built, and when this location is known at the compilation time.

> Then you will pass the path to the middleware module like i've already described:...

I think I can guess what that Windows code should look like on Mac or Unix. But why cannot it be compiled it, with user's ability to *override* if necessary, and leave alone if defaults are OK?

**Comment by mouse07410** [comment]
**Update** Succeeded setting *non-privileged* configuration for SoftHSMv2 and running the tests like this:
```
$ ./botan-test pkcs11 --pkcs11-lib=/opt/local/lib/softhsm/libsofthsm2.so
Testing Botan 1.11.31 (unreleased, revision git:d3c331cfd0d4aae0e9cac50cafa82dddf7335222, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/opt/local/lib/softhsm/libsofthsm2.so rng:HMAC_DRBG with seed '00001D902C69265A'
PKCS11 change pin ran 2 tests all ok
PKCS11 change so_pin ran 2 tests all ok
PKCS11 initialize token ran 1 tests all ok
PKCS11 set pin ran 2 tests all ok
Module copy ran 1 tests all ok
Module ctor ran 2 tests all ok
Module info ran 1 tests all ok
Module reload ran 2 tests all ok
Slot ctor ran 2 tests all ok
Slot get_available_slots ran 1 tests all ok
Slot get_mechanism_info ran 1 tests all ok
Slot get_mechanism_list ran 1 tests all ok
Slot get_slot_info ran 1 tests all ok
Slot get_token_info ran 1 tests all ok
Session ctor ran 4 tests all ok
Session login/logout ran 2 tests all ok
Session release/take ownership ran 1 tests all ok
Session session info ran 5 tests all ok
AttributeContainer ran 1 tests all ok
Object copy ran 1 tests all ok
Object create/delete data object ran 2 tests all ok
Object get/set attributes ran 2 tests all ok
ObjectFinder ran 3 tests all ok
PKCS11 RSA encrypt decrypt ran 3 tests all ok
PKCS11 RSA sign and verify ran 5 tests all ok
PKCS11 export RSA private key ran 2 tests all ok
PKCS11 generate RSA key pair ran 1 tests all ok
PKCS11 generate RSA private key ran 1 tests all ok
PKCS11 import RSA private key ran 1 tests all ok
PKCS11 import RSA public key ran 1 tests all ok
PKCS11 ECDSA sign and verify ran 2 tests all ok
PKCS11 export ECDSA private key ran 1 tests all ok
PKCS11 export ECDSA public key ran 1 tests all ok
PKCS11 generate ECDSA key pair ran 1 tests all ok
PKCS11 generate ECDSA private key ran 1 tests all ok
PKCS11 import ECDSA private key ran 1 tests all ok
PKCS11 import ECDSA public key ran 1 tests all ok
PKCS11 ECDH derive ran 1 tests all ok
PKCS11 export ECDH private key ran 1 tests all ok
PKCS11 export ECDH public key ran 1 tests all ok
PKCS11 generate ECDH key pair ran 1 tests all ok
PKCS11 generate ECDH private key ran 1 tests all ok
PKCS11 import ECDH private key ran 1 tests all ok
PKCS11 import ECDH public key ran 1 tests all ok
PKCS11 HMAC_DRBG using PKCS11_RNG ran 4 tests all ok
PKCS11 RNG add entropy random ran 1 tests all ok
PKCS11 RNG generate random ran 1 tests all ok
PKCS11 X509 cert import ran 2 tests all ok
Tests complete ran 78 tests all tests ok
$
```

Does not negate my criticism, but the code works.

**Comment by neusdan** [comment]
> Respectfully disagree. Some people build Botan to work with their existing (apps and) tokens. They would want to know that the code they just built works correctly - they don't necessarily need or want the PKCS#11 part of it to be able to reformat the token, or stand it on its head.

I would assume that a app developer that is writing an app using tokens has at least one token that can be used for developing purposes and that can be reformatted as often as needed.

> As I said, respectfully disagree. If I want this new software to work with my existing precious tokens (rather than buy new tokens to work with this precious software), I better be able to test this software with my existing token - and in a non-destructive way.

There is only little you can test in a noninvasive way (without modifying the token). You can't create keys, certificates, data. You can't change the PIN or SO_PIN. So you furthermore can't encrypt, decrypt and so on... and i'm sure that there are more things i'm just now not remembering right now.

> To address this, I suggest splitting the tests into two groups:
> non-destructive tests that I can use to make sure Botan can "work" with my institution-issued token (which neither I not Botan can or should modify), and
destructive tests that assume complete control over a blank token, and would be used to make sure PKCS#11 module can do everything.

As already said. Without knowing the initial state and without modifying the token you can't be sure that Botan can "can work with your institution-issued token". It's possible to split the tests but in my opinion it's doesn't make that much sense.

>> Wrong PIN or PUK can be one reason for this.

> I doubt it, since for some invocations I reset the PIN to "123456". Still, no RSA test passed. While applications that sign/verify and encrypt/decrypt using RSA and token, work fine (that includes OpenSSL and native Apple apps such as Safari and Apple Mail).

This is probably because of bugs in OpenSC. What we have tested (SoftHSM, CardOS and Gemalto works as expected). Someone has to investigate this. 

> But then, I don't touch Windows - while your development seems to be centered on it.

Yes, i'm mainly developing on Windows. But this code is tested cross platform with Visual C++ 2013 + 2015, gcc and clang on Windows, Linux, macOS and iOS.

> Yes it is a problem when every time I need to specify location of something that never changes on the platform the code is built, and when this location is known at the compilation time.

For the CLI tool i can image that a default location is useful. But in the first step our focus was on the library itself.

> I think I can guess what that Windows code should look like on Mac or Unix. But why cannot it be compiled in, with user's ability to override if necessary, and leave alone if defaults are OK?

That's Windows code just because a Windows path is used? Whatever :) My opinion is still that the library (Botan) should not handle or save the location of the PKCS#11 middleware. That's the job of the application using Botan to access tokens. Applications can use multiple middlewares and multiple tokens. How should Botan handle this?

**Comment by mouse07410** [comment]
> I would assume that a app developer that is writing an app using tokens has at least one token that can be used for developing purposes and that can be reformatted as often as needed.

Maybe so, I see your point. However, people may install and use Botan not only to *develop* but also to *use* applications developed by others.

> There is only little you can test in a noninvasive way (without modifying the token).

Respectfully disagree. Most of the user-level functionality can be tested (see below).

> You can't create keys, certificates, data. 

This is correct - and for user-level access and applications unnecessary to test.

> You can't change the PIN or SO_PIN.

Technically incorrect wrt. PIN, correct wrt. SO_PIN. I still wouldn't want the test to change the PIN. ;)

> So you furthermore can't encrypt, decrypt and so on... 

Huh...?! I don't think I understand you. This is *exactly* what I think this set of non-destructive tests should do and report:

- If key is slot 9A is present - sign and verify using it.
- If key in slot 9C is present - sign and verify using it.
- If key in slot 9D is present - encrypt and decrypt using it.
- If key in slot 9E is present -  sign and verify using it.

The report of the above would be one of:

- Operation X with key Y succeeded, or
- Operation X with key Y failed, or
- Key Y was not provisioned.

These tests would be useful for me. It is nice to ensure that Botan PKCS#11 can do everything - on a spare blank token, or on SoftHSMv2. It is also nice to ensure that Botan PKCS#11 can do the above subset with my already-provisioned "real" hardware token (without me having to reset it afterwards).

>  Without knowing the initial state and without modifying the token 

I'd expect the test-code to check for the presence of keys in the above slots, and act accordingly.  If no keys are found - just report. That would mean either an improperly provisioned (or unprovisioned) token, **or** that Botan fails to work with it properly.

In the end, a Botan application in 99% of all cases would have to work with real hardware tokens provisioned by something/somebody else. So might as well provide the way to test it in an easy way.

> you can't be sure that Botan can "can work with your institution-issued token".

I'd say that if Botan subset of non-destructive tests succeeds working with the token (strictly speaking, signing using 9A, 9C and 9E, and decrypting using 9D), that's enough evidence for a "normal user" that "Botan can work with that institution-issued token". And if it fails - it means a deeper look is necessary.

>  It's possible to split the tests but in my opinion it's doesn't make that much sense.

Please see above, and decide if it convinces you to reconsider.

> My opinion is still that the library (Botan) should not handle or save the location of the PKCS#11 middleware. That's the job of the application using Botan to access tokens. Applications can use multiple middlewares and multiple tokens. How should Botan handle this?

You made a good point. However... Many (most?) of the installations would not have a bunch of middleware packages, jumping back and forth between them. Usually it would be just one. And even if more than one is installed, it seems to make sense to have the **default** middleware location compiled in - it does not restrict an application from providing whatever location of whatever middleware it sees fit.

Also, please keep in mind that eventually (hopefully soon, partially up to you :) Botan CLI would add the capability to use keys on PKCS#11 tokens. It would be very nice if the **default** location of the *preferred* middleware could be compiled in (and your out-of-the-box default can well be NULL if you insist :), saving keystrokes and potential typos on something really unnecessary.

Regarding your example: it would have been far easier for me if you were to provide a reasonably complete example of *doing* something like signing or decrypting with a key on a token.

Also, with OpenSSL I can *verify* or *encrypt* using the pubkey/cert on the token (even though the token itself does not perform those operations), because OpenSSL is smart enough to just pull/extract the key in such a case. Would it be possible with your PKCS#11 module and Botan? If so, how?

Thanks!

**Comment by cordney** [comment]
> Huh...?! I don't think I understand you. This is exactly what I think this set of non-destructive tests
> should do and report:
>
> * If key is slot 9A is present - sign and verify using it.
> * If key in slot 9C is present - sign and verify using it.
> * If key in slot 9D is present - encrypt and decrypt using it.
> * If key in slot 9E is present - sign and verify using it.
>
> The report of the above would be one of:

> * Operation X with key Y succeeded, or
> * Operation X with key Y failed, or
> * Key Y was not provisioned.
> 
> These tests would be useful for me. It is nice to ensure that Botan PKCS#11 can do everything - 
> on a spare blank token, or on SoftHSMv2. It is also nice to ensure that Botan PKCS#11 can do the 
> above subset with my already-provisioned "real" hardware token (without me having to reset it 
> afterwards).

These tests are non-deterministic and therefore not suitable for the library test suite. What you describe is something like a compatibility test suite. That's not what the PKCS#11 tests in Botan are meant for. They are meant to test that Botan's PKCS#11 implementation works correctly. What you want to know is if your token works with Botan, so is compatible with Botan's implementation of PKCS#11. While I see such a compatibility test suite would be useful, this would better be implemented in the CLI, not in the library itself.

**Comment by mouse07410** [comment]
> These tests are non-deterministic ...

I can see how that can be true for ECC keys. But for RSA I don't think I agree (considering that all the randomization is performed by the invoking software, and the token only plain RSA operations). 

That means the test code can have test-vectors of predefined sizes (say, 2048 and 3072 bits) for RSA encryption (aka "signature") and decryption. Having the results match would prove that
(a) a tested subset of Botan worked correctly, and (b) the token performed correctly under control of Botan, and (c) this token and this version of Botan library are compatible.  This (as far as I can see) is fully/totally deterministic.

Testing round-trip results would also instill a certain level of confidence that the tested subset is not only compatible with the token, but also works correctly. Here's how:

- For RSA - encrypting some data with the token public key, decrypting on the token, and comparing results to the original plaintext; signing some random data by the token, validating signature by the token public key, making sure that modified signature fails validation.
- For ECC - same regarding signature; generate random EC key pair, derive shared secret on the token, derive shared secret with token public key, compare if they match.

I'd dare to call the above deterministic *from practical point of view* (it may not matter that the intermediate values differ - we want to see that the process is followed and that it produced the correct/matching results in the end).

Do you agree with the above?

> What you want to know is if your token works with Botan...

Yes but not quite...

What I want to know is if my token works **correctly** with Botan - which is more than just getting the two communicate/exchange data.

> ...this would better be implemented in the CLI, not in the library itself.

I think that this would be a natural evolution of the current set of PKCS#11 tests, easier to implement as such (rather than as a separate set that's a part of a different application). It would also fit my desire to see the tests split into destructive and non-destructive.

**Comment by cordney** [comment]
> Do you agree with the above?

I think you did not get my point. The tests you described above check if a key is available in some arbitrary slot, possibly by iterating over all slots (?), if yes, they do something with it and so on. The results will differ with different tokens, because they will certainly contains different keys in different slots, probably with different constraints. That make the tests non-deterministic.

> I think that this would be a natural evolution of the current set of PKCS#11 tests, easier to
> implement as such (rather than as a separate set that's a part of a different application). It would
> also fit my desire to see the tests split into destructive and non-destructive.

I still don't see this, but maybe practice proves me wrong. If @neusdan and @randombit do not object, you can give an implementation a try and open a PR, so we can discuss actual code.

> Also, please keep in mind that eventually (hopefully soon, partially up to you :) Botan CLI would
> add the capability to use keys on PKCS#11 tokens. It would be very nice if the default location of
> preferred middleware could be compiled in (and your out-of-the-box default can well be NULL if 
> you insist :), saving keystrokes and potential typos on something really unnecessary.

Imagine botan being distributed in a package manager, e.g., apt, with a default location set. Other libraries use a different approach, e.g., gnutls allows putting locations of middleware libraries into a config file, see https://www.gnutls.org/manual/html_node/p11tool-Invocation.html.

**Comment by mouse07410** [comment]
> I think you did not get my point.

I think I get it now. But please bear with me for a little more.

> The tests you described above check if a key is available in some arbitrary slot, possibly by iterating over all slots (?), if yes, they do something with it and so on.

But the slots are *not* arbitrary! There are *exactly four* allowed standard-defined slots, with well-defined key usage for each. I admit that my vision here is colored by the PIV standard. 

> The results will differ with different tokens,

Yes, you are correct. But the "round-trip results" would not differ across different tokens and keys, modulo type (RSA vs ECC) and key size. 

> Imagine botan being distributed in a package manager, e.g., apt, with a default location set. Other libraries use a different approach, e.g., gnutls allows putting locations of middleware libraries into a config file...

I don't see how having a compile-able default (say, initially set to NULL) hurts anything or anybody. In that case, when you compile the library for a platform where having a compiled-in default makes sense, you have the ability to set it so. And when you don't have a default - just don't set that value.

**Comment by mouse07410** [comment]
Probably no point keeping this issue open any longer.
