### ISSUE TITLE
HMAC_DRBG commit broke PKCS#11

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#539]
Current GitHub master, Xcode-7.3.1, Mac OS X 10.11.6. Yesterday everything compiled fine.

```
clang++  -m64 -pthread -maes -mpclmul -mssse3 -msse4.2 -mrdrnd -I/opt/local/include -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -I/Users/uri/src/pkcs11-base/ -c ./src/tests/test_pkcs11_high_level.cpp -o build/obj/test/test_pkcs11_high_level.o
./src/tests/test_pkcs11_high_level.cpp:1345:14: error: no matching constructor for
      initialization of 'Botan::HMAC_DRBG'
  ...drbg(MessageAuthenticationCode::create("HMAC(SHA-512)").release(), new PKCS11_RNG(test_session.session()));
     ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/include/botan/hmac_drbg.h:28:7: note: candidate constructor not viable: no
      known conversion from 'Botan::PKCS11::PKCS11_RNG *' to 'size_t'
      (aka 'unsigned long') for 2nd argument
      HMAC_DRBG(MessageAuthenticationCode* hmac,
      ^
build/include/botan/hmac_drbg.h:25:7: note: candidate constructor not viable: no
      known conversion from 'pointer' (aka 'Botan::MessageAuthenticationCode *') to
      'const std::string' (aka 'const basic_string<char, char_traits<char>,
      allocator<char> >') for 1st argument
      HMAC_DRBG(const std::string& hmac_hash,
      ^
build/include/botan/hmac_drbg.h:19:17: note: candidate constructor (the implicit
      copy constructor) not viable: requires 1 argument, but 2 were provided
class BOTAN_DLL HMAC_DRBG final : public Stateful_RNG
                ^
1 error generated.
make: *** [build/obj/test/test_pkcs11_high_level.o] Error 1
$
```

Applying this patch
```
diff --git a/src/tests/test_pkcs11_high_level.cpp b/src/tests/test_pkcs11_high_level.cpp
index 6770415..877c44f 100644
--- a/src/tests/test_pkcs11_high_level.cpp
+++ b/src/tests/test_pkcs11_high_level.cpp
@@ -1342,14 +1342,14 @@ Test::Result test_pkcs11_hmac_drbg()
    Test::Result result("PKCS11 HMAC_DRBG using PKCS11_RNG");
    TestSession test_session(true);

-   HMAC_DRBG drbg(MessageAuthenticationCode::create("HMAC(SHA-512)").release(), new PKCS11_RNG(test_session.session()));
+   HMAC_DRBG drbg("SHA-512", 0);
    result.test_success("HMAC_DRBG(HMAC(SHA512)) instantiated with PKCS11_RNG");

    result.test_eq("HMAC_DRBG is not seeded yet.", drbg.is_seeded(), false);

    std::string personalization_string = "Botan PKCS#11 Tests";
    std::vector<byte> personalization_data(personalization_string.begin(), personalization_string.end());
-   drbg.add_entropy(personalization_data.data(), personalization_data.size());
+   drbg.initialize_with(personalization_data.data(), personalization_data.size());

    result.test_eq("HMAC_DRBG is seeded now", drbg.is_seeded(), true);

```
makes the code compile and fixes the test:
```
$ ./botan-test
Testing Botan 1.11.31 (unreleased, revision git:99f82cd1b53ff16ac96793d3fc034fb16c2edd64, distribution unspecified)
Starting tests soak level:5 rng:HMAC_DRBG with seed '00000525F6A3939C'
AES-128 ran 9240 tests in 8.93 msec all ok
AES-192 ran 10776 tests in 7.48 msec all ok
. . . . .
X509v3 Name Constraints: Valid_IP_Name_Constraint.crt ran 1 tests all ok
NIST path validation ran 71 tests all ok
X509test path validation ran 37 tests all ok
Tests complete ran 493362 tests all tests ok
$ ./botan-test pkcs11 --pkcs11-lib=/opt/local/lib/softhsm/libsofthsm2.so
Testing Botan 1.11.31 (unreleased, revision git:99f82cd1b53ff16ac96793d3fc034fb16c2edd64, distribution unspecified)
Starting tests soak level:5 pkcs11 library:/opt/local/lib/softhsm/libsofthsm2.so rng:HMAC_DRBG with seed '0000051865F56D2B'
PKCS11 change pin ran 2 tests all ok
PKCS11 change so_pin ran 2 tests all ok
PKCS11 initialize token ran 1 tests all ok
. . . . .
PKCS11 HMAC_DRBG using PKCS11_RNG ran 4 tests all ok
PKCS11 RNG add entropy random ran 1 tests all ok
PKCS11 RNG generate random ran 1 tests all ok
PKCS11 X509 cert import ran 2 tests all ok
Tests complete ran 78 tests all tests ok
```

@randombit, for the fix see PR https://github.com/randombit/botan/pull/540

**Comment by mouse07410** [comment]
I don't understand. I did a pull at home three hours ago from the master, and HMAC_DRBG showed as a subclass of RandomNumberGenerator, with optional RNG in constructors. So the unmodified PKCS#11 tests worked.

Right now I'm looking at the master on Github - and HMAC_DRBG is what it was yesterday, aka no constructors with RNG, so PKCS#11 tests keep failing. 

Probably I should re-open #540? Or @randombit could speed up his partial revert of HMAC_DRBG changes (I guess something similar should be done to other RNGs as well?)?

**Comment by randombit** [comment]
> I don't understand. I did a pull at home three hours ago from the master, and HMAC_DRBG showed as a subclass of RandomNumberGenerator, with optional RNG in constructors. So the unmodified PKCS#11 tests worked.

Do you have commit IDs that made these changes? Are the commits signed (`git log --show-signature`)? I have started working on this but have not even commited anything to a public branch much less merged it to master. Nor have I done a force push to the repo, which would be required to erase history (master is protected from force pushes through the github interface).

I suppose it's concievable that due to some github error when you pulled, you received a truncated history only up to some commit prior to e33c9894 and were thus looking at the state of master before #520 was merged?

**Comment by mouse07410** [comment]
> I suppose it's concievable that due to some github error when you pulled, you received a truncated history only up to some commit prior to e33c989 and were thus looking at the state of master before #520 was merged?

Entirely possible. :-(

> Do you have commit IDs that made these changes? Are the commits signed (`git log --show-signature`)? 

If it is not the case above (GitHub error where something old got pulled in) I will report the details as soon as I get home.

**Comment by mouse07410** [comment]
I checked the code - and everything is as you said. No problem - I just did not realize that the PKCS11 test in my tree was my modified version. Sorry for the false alarm.

**Comment by mouse07410** [comment]
Since PKCS#11 is no longer broken, I'm closing this issue. But it would be nice to hear from @randombit what his plans and timeframe are for the HMAC_DRBG modification to restore the RNG-taking constructors (and automatic pull from that RNG).
