### ISSUE TITLE
Transformation_Filter error

### ISSUE THREAD

**Issue by FuckingCoder** [randombit/botan#564]
Hi! When using Transformation_Filter I get an error: "error: expected type-specifier". What to do?

**Comment by randombit** [comment]
Can you post the relevant code?

**Comment by FuckingCoder** [comment]
`    Algorithm_Factory &af = global_state().algorithm_factory();
    cipher = af.prototype_block_cipher(algo);
	
    Keyed_Filter *filter = new Botan::Transformation_Filter(new Botan::CBC_Encryption(cipher->clone(), new Botan::Null_Padding));`


I read that Transformation_Filter has been removed from the new version of the library. It's true? If yes, what there is a change?

**Comment by FuckingCoder** [comment]
As I understand it, this feature added in botan 1.11. How to reset nonce (IV) in version 1.10, if I create a decryptor follows?

`_decrypt.reset(new Pipe(new CBC_Decryption(cipher->clone(), new Null_Padding, s2c_key, s2c_iv)));`

**Comment by randombit** [comment]
To reset the IV using the filters interface save a pointer to the filter:

```
Keyed_Filter* cbc = nullptr;
_decrypt.reset(new Pipe(cbc = new CBC_Decryption(...));
cbc->set_iv(..);
```

**Comment by FuckingCoder** [comment]
Perhaps you can help me. I'm trying to implement a secondary school with the help of your way to the library, pokazynnym above. The first message is decrypted properly, but there is no follow-up. What can be wrong?
