### ISSUE TITLE
get_files_recursive doesn't return symlinks to files

### ISSUE THREAD

**Issue by ChrisBFX** [randombit/botan#565]
get_files_recursive doesn't return symlinks if it uses the readdir implementation. I noticed this when I wanted to read all ca in /etc/ssl/certs using the Certificate_Store_In_Memory. Under debian /etc/ssl/certs is full of symlinks to the actual certificates.
My guess is that lstat returns the symlinks themselves which are not regular files so S_ISREG returns false. I didn't test it but i think stat instead of lstat would solve this.
To be future ready it would be cool if there was an implementation using c++17 std::filesystem and std::experimental::filesystem. (Even though i would have to wait decades until i can use it under debian....)

**Comment by randombit** [comment]
Thanks for the report, using `stat` instead of `lstat` here looks right.

It will probably be another year or two before C++17 features can be adopted, want to make sure the compilers have some chance to catch up first.

**Comment by randombit** [comment]
@ChrisBFX can you check bca8bef?

**Comment by ChrisBFX** [comment]
Works great. Thanks alot for the quick fix :+1:
