### ISSUE TITLE
Unknown PBE type "1.2.840.113549.1.5.3"

### ISSUE THREAD

**Issue by AlexNk** [randombit/botan#571]
1. Generate self-signed certificate with encrypted private key using OpenSSL:
```
openssl genrsa -out ./tmp.key 1024 -des3 -passout pass:123456
openssl req -x509 -new -key ./tmp.key -days 720 -subj "/C=US/ST=AL/L=/O=Tedy Inc./emailAddress=test@test.com/CN=Test app" -out ./tmp.cer -passin pass:123456 -sha256
openssl pkcs8 -topk8 -in ./tmp.key -out ./tmp.key.pem -outform PEM -passin pass:123456 -passout pass:123456
```
2. Load private key:
```
Bo::DataSource_Stream in( pem_file );
Bo::DataSource_Memory ds( Bo::PEM_Code::encode( data, label ) );
...
Bo::PKCS8::load_key( ds, *rng, "123456" );

```
3. Exception is being generated with mentioned error

**Comment by randombit** [comment]
1.2.840.113549.1.5.3 is insecure `pbeWithMD5AndDES-CBC` which was removed two years ago in 1.11.8. It supports only 56 bit keys.

You need to use the `-v2` flag for `openssl pkcs8`. From the openssl man page:

"Normally PKCS#8 private keys are encrypted with the password based encryption algorithm called pbeWithMD5AndDES-CBC this uses 56 bit DES encryption but it was the strongest encryption algorithm supported in PKCS#5 v1.5. Using the -v2 option PKCS#5 v2.0 algorithms are used which can use any encryption algorithm such as 168 bit triple DES ..."

**Comment by AlexNk** [comment]
Thanks for clarification.
I'll close the issue.
