### ISSUE TITLE
 32-bit build with x86-64 CPUs

### ISSUE THREAD

**Issue by Bi11** [randombit/botan#579]
I'd like to build a 32-bit Botan for Core2 and later CPUs.
But current Botan configuration tool will set CPU to `x86_64/core2` if I set `--cpu=core2`.

On Mac OS with clang, I tried `--cc-abi-flags='-arch i386'`, but the compile failed because of incorrect `BOTAN_TARGET_ARCH_IS_X86_64` flag. (e.g., in src/lib/utils/mul128.h)

I prefer to consider it as a cross compile, update `doc/manaul/buidling`, and try to fix Fat Binary build with `--cc-abi-flags='-arch i386 -arch x86_64'`.

What do you think?

**Comment by webmaster128** [comment]
Try `--cpu=x86_32`.

If you need multiple builds, do

* configure for 32 bit
* build
* copy library
* configure for 64 bit
* build
* copy library

**Comment by Bi11** [comment]
This issue majorly affects the module that written in vanilla C++ codes.
If my target CPU is core2 and later ones, I want all C++ codes are compiled with SSSE3 feature, both in 32-bit mode and 64-bit mode.

With `--cpu=x86_32`, the C++ codes are compiled without any SSE instructions, it is a generic i386 build.

The universal build is just a side effect.

So I hope the c++ flags in Makefile can be configured as `-m32 -march=core2` or `-arch i386 -march=core2`.  Current configuration can not be specified with `--cpu=x86_32/core2`. 

Since core2 is indeed an x86_64 CPU, so I prefer to set `--cpu=x86_64/core2`, and set `--cc-abi-flags='-arch i386'` for a 32-bit build.

**Comment by webmaster128** [comment]
So `--cpu=x86_32 --cc-abi-flags='-march=core2'` and `--cpu=x86_64 --cc-abi-flags='-march=core2'` is your friend, isn't it?

**Comment by Bi11** [comment]
YES, it works.
I did not notice that `--cpu=x86_32` won't produce `-march` in `CXXFLAGS`.

But universal build for macOS in `doc/manaul/buidling` is outdated. Since c++11 requires macOS 10.7, and macOS 10.7 requires 64bit CPU, I think the universal build part may be simply removed.

**Comment by webmaster128** [comment]
> Since c++11 requires macOS 10.7, and macOS 10.7 requires 64bit CPU, I think the universal build part may be simply removed.

But you can build for target OS X < 10.7 using a modern OS X with a c++11 toolchain, can't you?
