### ISSUE TITLE
SonarQube CI fails with error

### ISSUE THREAD

**Issue by randombit** [randombit/botan#601]
Errors out with

```
ERROR: Error during SonarQube Scanner execution
ERROR: You're only authorized to execute a local (preview) SonarQube analysis without pushing the results to the SonarQube server. Please contact your SonarQube administrator.
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Scanner with the -e switch.
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
```

https://travis-ci.org/randombit/botan/jobs/154516481

**Comment by neusdan** [comment]
I assume you changed nothing at Project -> Administration -> Permissions? Especially the "Execute Analysis" Option?

**Comment by randombit** [comment]
Nope, have not touched any configs on the site

**Comment by neusdan** [comment]
I've sent them an email.

**Comment by neusdan** [comment]
Got an answer.

There is a way you can add me as a user to the SonarQube project. I'll try to handle all SonarQube related configuration then.
 
> Jack should be able to add you as an administrator of the project in "Administration -> Permissions", searching for your name in the search box.

Regarding the analysis error:

> Regarding the analysis, it seems that Jack has simply removed his rights on the project. I fixed it and it should be back to normal now.

**Comment by randombit** [comment]
Hm, I don't remember doing that? In any case, you should have all rights on sonarqube now.

**Comment by randombit** [comment]
Works now
