### ISSUE TITLE
Code coverage report broken

### ISSUE THREAD

**Issue by randombit** [randombit/botan#609]
Code coverage is stuck at fedaf80bad502a2f0c85b7acd0e2ead37c6c8ced: https://codecov.io/gh/randombit/botan

The next commit on master merged #592 which switched to a new distro and upgraded lcov. It seems something broke here. CI ends with

lcov: ERROR: cannot write to coverage.info!

**Comment by neusdan** [comment]
fixed in #610

**Comment by randombit** [comment]
Thanks
