### ISSUE TITLE
What happened to module hres_timer?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#614]
After upgrading from 1.11.30 to 1.11.31, I get the configure error:

>   ERROR: Module not found: hres_timer

Log:

>    INFO: /tmp/update-botan/1.11.31/Botan-1.11.31/configure.py invoked with options "--via-amalgamation --no-autoload --disable-shared --enable-modules=aes,auto_rng,cmac,codec_filt,eme_oaep,emsa_pssr,gcm,hres_timer,rsa,sha1,sha2_32,sha2_64,srp6,system_rng,xts,dev_random,proc_walk,aes_ni,clmul --os=android --cpu=x86_32 --cc=clang"
>    INFO: Platform: OS="Linux" machine="x86_64" proc="x86_64"
>    INFO: Canonicalizized CPU target x86_32 to x86_32/x86_32
>    INFO: Target is clang-android-x86_32-x86_32
>    INFO: Found sphinx-build (use --without-sphinx to disable)
>   ERROR: Module not found: hres_timer

I did not find anything about this module in the changelog. `hres_timer` is still listed in `src/build-data/policy/bsi.txt` and `src/build-data/policy/modern.txt`.

**Comment by randombit** [comment]
It was removed in #520/#593 but was missed in the release notes. Timestamps are incorporated into each output by AutoSeeded_RNG via the additional_input field, or by applications explicitly calling (new function) `randomize_with_ts_input` to generate outputs.

**Comment by randombit** [comment]
Release notes were updated to reflect the change
