### ISSUE TITLE
Disable Locking Allocator for ASAN builds

### ISSUE THREAD

**Issue by flanfly** [randombit/botan#626]
The `locking_allocator` module prevents ASAN from catching overflows involving `secure_vector` backed buffers.

I had a look at the inner workings of `secure_vector` and saw that all instances are allocated from a single continuous memory pool that is managed by Botan. ASAN does not know about this custom allocator so overflowing a `secure_vector` backed buffer won't be detected as the access will still be inside the memory pool. I believe it makes sense to disable the `locking_allocator` for the ASAN builds and let `secure_vector` use the default new/delete interface.

**Comment by randombit** [comment]
The pool also hides misbehavior from `valgrind`. I believe for both `valgrind` and ASan it is possible to add annotations that would help.

**Comment by flanfly** [comment]
I checked the ASan [documentation](https://github.com/google/sanitizers/wiki/AddressSanitizerManualPoisoning) and they discourage manual poisoning. Also, disabling the `locking_allocator` has the advantage that we don't have to add metadata for each dynamic instrumentation tool we want to use.

While I'm not a fan of special test modes, disabling the `locking_allocator` gives us a lot in terms of security with for a comparable small change.

**Comment by randombit** [comment]
Worth mentioning that on Unix you can disable the mlock pool at runtime either by setting the locked memory ulimit (`ulimit -H -l 0`) or setting the env variable `BOTAN_MLOCK_POOL_SIZE` to 0. Neither of these methods work on Windows.

As I read that ASan doc it is not discouraging manual poisoning, just saying that manual poisoning+allocator is not likely to find *more bugs* than ASan instrumented malloc+free

**Comment by randombit** [comment]
For now I disabled the locking_allocator module on valgrind+ASan builds with 272fcf0. I will probably add poison handling at least for valgrind later on.
