### ISSUE TITLE
No tests for TLS 1.2 PRF

### ISSUE THREAD

**Issue by cordney** [randombit/botan#627]
It seems there are no tests for the TLS 1.2 PRF, https://github.com/randombit/botan/blob/master/src/tests/data/kdf/tls_prf.vec only contains test vectors for the TLS1.0/1.1 PRF. I could not find any official test vectors for both the TLS 1.0/1.1 as well as the 1.2 PRF, apart from these: https://www.ietf.org/mail-archive/web/tls/current/msg03416.html. We could add these at least, but I wonder where the existing 1.0/1.1 test vectors in Botan came from. Were they self-generated?

**Comment by randombit** [comment]
Re the 1.0/1.1 vectors I would guess self-generated, though it is possible I instrumented a version of OpenSSL - this was a long time ago.
