### ISSUE TITLE
Build botan on Windows with mingw-w64 and gnuwin32

### ISSUE THREAD

**Issue by alexeyvoronin777** [randombit/botan#629]
Platform: Windows 10 AMD64
toolchain:  mingw-w64(32-bit)
cp --version
cp (GNU coreutils) 5.3.0
...

python configure.py --cc=gcc --cpu=x86 --os=mingw --disable-shared

Build is success but install:
D:\projects\work\source\Botan-1.11.31>make install
cp D:\projects\work\source\Botan-1.11.31\doc\manual*.rst build\docs\manualcp: cannot stat `D:\projects\work\source\Botan-1.11.31\doc\manual_.rst': Invalid argumentmake: *_\* [docs] Error 1

Problem string in Makefile:
....
docs:
    $(COPY) D:\projects\work\source\Botan-1.11.31\doc\manual*.rst build\docs\manual
...

Solution: add quotation marks in the path to the file.
....
docs:
    $(COPY) "D:\projects\work\source\Botan-1.11.31\doc\manual*.rst" "build\docs\manual"
...

**Comment by webmaster128** [comment]
I don't think this kind of quoting is the proper solution, since usually this would prevent globing (at least in Linux shells).

See https://www.gnu.org/software/make/manual/html_node/Wildcard-Pitfall.html#Wildcard-Pitfall:

> This is equivalent to the Unix-style c:/foo/bar/baz.c (the c: part is the so-called drive letter). When make runs on these systems, it supports backslashes as well as the Unix-style forward slashes in pathnames. However, this support does not include the wildcard expansion, where backslash is a quote character. Therefore, you must use Unix-style slashes in these cases.

So the problem might be that the Python version of this MinGW environment returns `\` for `os.sep` instead of `/`.

**Comment by michabuehlmann** [comment]
I'm trying to install Botan 2.1 on my Windows 10 Computer. I downloaded the tgz-file and extracted it. I went into the folder (botan 2.1). Then I tried to build the makefile with the following command:

python configure.py --cc=gcc --cpu=i386 --os=mingw

The cpu-option is here, because I use mingw in the 32bit version.
I receive the following error message:

ERROR: Error linking src\lib\asn1\alg_id.h into build\include\botan: symbolic link privilege not held

When I use --os=windows I can produce the makefile but I can't build the library.
Can anybody help me?

**Comment by neusdan** [comment]
Quick fix is to use --link-method hardlink

**Comment by michabuehlmann** [comment]
Thanks for the help. I could build the makefile now. But then I wanted to produce the library with:
C:\MinGW\bin\mingw32-make.exe
Unfortunately the procedure fails with the message:

process_begin: CreateProcess(NULL, rm -f ./libbotan-2.a, ...) failed.
make (e=2): Das System kann die angegebene Datei nicht finden.
Makefile:1628: recipe for target 'libbotan-2.a' failed
mingw32-make: *** [libbotan-2.a] Error 2

I have no make file. Just the mingw32-make.
How can I succeed?

**Comment by webmaster128** [comment]
The idea of `RM = @rm -f` is that `rm -f ./libbotan-2.a` succeeds even if libbotan-2.a does not exist. Now it looks like the command returns a non-0 return code, which causes the Make error.

Could you paste the result of `rm -f file_that_does_not_exist; echo $? `? This should be 0.

**Comment by michabuehlmann** [comment]
It seems that the rm command doesn't work on my windows machine. Why is this command in the windows makefile?

**Comment by webmaster128** [comment]
It should work in your MinGW shell, not in the Windows command prompt. It is in the Makefile because an old libbotan-2.a should be removed if existing before creating a new one.

**Comment by michabuehlmann** [comment]
I have no MinGW shell.

**Comment by webmaster128** [comment]
A quick search revealed that only MYSYS contains a bash, not MinGW. It is possible that Botan's MinGW build systems depends on MYSYS just because the few users of Botan on MinGW have MYSYS tools available. I have no clue how MinGW works in detail, so I cannot help any further here.

**Comment by michabuehlmann** [comment]
Hello webmaster128. I found the msys system. With shell, make-command etc. I could build the makefile with:
python configure.py --cc=gcc --cpu=i386 --os=mingw
Then the msys command make was succesful. I tested  "botan-test.exe". I received the message:

Tests complete ran 304247 tests in 105.93 sec 16 tests failed
Error: Test error Test suite failure

Then I wanted invoke "make install" The result is:

cp doc\manual\*.rst build\docs\manual
cp: cannot stat `doc\\manual*.rst': No such file or directory
make: *** [docs] Error 1

What is wrong?

**Comment by webmaster128** [comment]
Please open a new dedicated Github issue for the test problem including the full output.

The error in make install is the same as in the original post in this issue. Looks like still the same issue I described in https://github.com/randombit/botan/issues/629#issuecomment-255846838: The wildcard * may not work so the build system must be rewritten to put all the `doc\manual*.rst` paths into the Makefile. But this is just a guess and I don't use MinGW. I think if you want that to be fixed, you need to put a lot of research and testing into this.

**Comment by michabuehlmann** [comment]
Dear webmaster128, just one question. I adapted the makefile and could execute the "make install". Now I have a file called "libbotan-2.a". Is this the right library file? Can I use that in Qt? Or do I need a .dll file?

**Comment by randombit** [comment]
This should be fixed with the recent rewrites of the install targets into Python, closing. @michabuehlmann if you have any remaining issues here please open a new ticket. Thanks.

**Comment by Crafsman** [comment]
@neusdan @michabuehlmann hi buddy, I encountered the some error:
**ERROR: Error linking src\lib\asn1\alg_id.h into build\include\botan: symbolic link privilege not held**
you said use the --link-method hardlink,
but I don't know how to use the link, could you give me constructive details, for example, what is the detailed link command.
thanks
