### ISSUE TITLE
Coverage report lists test files

### ISSUE THREAD

**Issue by cordney** [randombit/botan#635]
The current codecov coverage report also lists coverage for the tests and for `cli.h`, resulting in wrong overall coverage. We currently remove all coverage results of the `tests/` files using lcov, but from the Travis output of the codecov uploader it seems it parses the raw *.gcov files which are generated by running botan-test. I think for codecov it would be sufficient to exclude these files from the codecov report, it seems there is a custom `codecov.yml` [option](http://docs.codecov.io/docs/ignoring-paths) to just do that.

**Comment by randombit** [comment]
Inclusion of `cli.h` is needless but I actually rather like the coverage report being over both the library and the tests, as it shows where test code is written but is not running, like in https://codecov.io/gh/randombit/botan/src/7df9d0dcd968a4c0462b6e95dae4ec847b04199e/src/tests/unit_tls.cpp

**Comment by cordney** [comment]
OK
