### ISSUE TITLE
Botan attempts to open /dev/urandom for writing

### ISSUE THREAD

**Issue by nathanhourt** [randombit/botan#647]
See: https://github.com/randombit/botan/blob/master/src/lib/rng/system_rng/system_rng.cpp#L77

Botan is attempting to open /dev/urandom as read-write, which (correct me if I'm wrong) is not correct -- I know of no reason to write to /dev/urandom (what would that even do?).

I note that Ubuntu's new package format, Snappy, sandboxes apps by default, and the AppArmor profile it uses forbids opening /dev/{,u}random in write mode. This prevents apps which use Botan from being packaged with Snappy.

**Comment by nathanhourt** [comment]
So I was going to submit a pullreq to fix this, but one of the unit tests failed, namely, the one that reseeds the RNG. So writing to urandom is a way to add entropy to the pool? I've never heard of this.

Perhaps Snappy's AppArmor profile is wrong, then?...

**Comment by nathanhourt** [comment]
So probably botan's behavior should be "try to open RDWR; if that fails, try to open RDONLY; if that fails, give up" rather than "try to open RDWR; if that fails, give up". I suspect attempting to reseed the kernel's RNG is a rare use case...

**Comment by randombit** [comment]
> I know of no reason to write to /dev/urandom (what would that even do?)

Writes to `/dev/urandom` are documented as reseeding it with the material provided (see eg the man page for `random(4)`) which is useful if an application both wants to use and attempt to provide seed material for the system PRNG.

> AppArmor profile it uses forbids opening /dev/{,u}random in write mode.

Huh, well we can argue about the sense of adding that restriction but in any case they did it, so probably the backdown strategy you suggest is appropriate.

**Comment by nathanhourt** [comment]
Yeah, I was talking with some of the snappy folks about it, and they suggested the backdown strategy. I've also filed a bug with snapd to allow opening random devices in write mode, so theoretically they'll do something about it too, but in the meantime I'm going to implement the backdown strategy and do a custom build of botan with it until one or the other upstreams changes their behavior. :)

Technically, this isn't a bug in botan, but I'll be happy to send a pull req over all the same.

**Comment by alonbl** [comment]
Hello,

I was just bump into this one.

I had also change the src/tests/test_ffi.cpp to comment out the:
```
if(TEST_FFI_OK(botan_rng_init, (&rng, "system")))
  {
    TEST_FFI_OK(botan_rng_reseed, (rng, 256));
  }
```[1]

Shouldn't this be included as well? or workaround or any other mechanism so tests will succeed with system rng in all cases?

Thanks!

[1] https://github.com/gentoo/gentoo/blob/master/dev-libs/botan/files/botan-1.11.32-urandom.patch
