### ISSUE TITLE
Serialized_RNG deprecated, no release note

### ISSUE THREAD

**Issue by bazineta** [randombit/botan#651]
At some point between 1.11.29 and 1.11.32, Serialized_RNG was deprecated, but there's no release note as to what previous consumers of this function should do. There's a somewhat cryptic string on the deprecation, but that's it.

```
BOTAN_DEPRECATED("Create an AutoSeeded_RNG for other constructor") Serialized_RNG();
```

I'm not sure what the deprecation message is trying to tell me here, frankly.

**Comment by randombit** [comment]
Sorry. I'm sure that made more sense when I wrote it. What it means is instead of

`new Serialized_RNG`

write

`new Serialized_RNG(new AutoSeeded_RNG)`

**Comment by bazineta** [comment]
Ah, got it, makes sense now that I see it. Thanks.

**Comment by randombit** [comment]
Closing - question answered and I improved the deprecated message
