### ISSUE TITLE
Improving the Doxygen API doc

### ISSUE THREAD

**Issue by cordney** [randombit/botan#652]
We want to improve on the coverage of the Doxygen API throughout the library going through the it and adding Doxygen API doc for all public functions. However, quite often in derived classes we currently declare functions from the base class interface as `override`, but with no documentation. This sometimes leads to headers having no Doxygen API doc, except for a class description, e.g., https://github.com/randombit/botan/blob/master/src/lib/pubkey/dsa/dsa.h. Our proposal for derived class overridden member functions would be to add a one-line description of the function, presumable taken from the base class function, together with a reference to the base class function:

```cpp
/**
* DSA Public Key
*/
class BOTAN_DLL DSA_PublicKey : public virtual DL_Scheme_PublicKey
   {
   public:
      /**
      * Get the name of the underlying public key scheme.
      * See @ref Public_Key::algo_name()
      */
      std::string algo_name() const override { return "DSA"; }
```

What do you think? Any other ideas for improving the API doc coverage?

**Comment by randombit** [comment]
Sounds great to me.

WRT other Doxygen improvements, there are many warnings right now when Doxygen runs due to undocumented parameters - sometimes due to additional params being added to functions, other times due to renaming of variables.

**Comment by cordney** [comment]
OK, we'll check that, too.

**Comment by cordney** [comment]
Looking at the html generated by doxygen, I see that it (1) automatically takes the description from the base member function for the derived member function and (2) automatically links to the base member function, so the apidoc for `DSA_PublicKey::algo_name()` already looks like this (https://botan.randombit.net/doxygen/classBotan_1_1DSA__PublicKey.html#ae888d86bda27e83e2e2282174ac10405):

```
std::string Botan::DSA_PublicKey::algo_name() const

Get the name of the underlying public key scheme.

Returns
   name of the public key scheme

Implements Botan::Public_Key.
```

Of course you only get that if you look at the doxygen generated output, not by simply browsing the header files in your IDE. Do we still want to duplicate apidoc in derived classes now? My take now would be to keep the status quo and only annotate derived member functions when it adds more (derived-specific) information. Though I must admit that I dislike that an IDE like Eclipse is not able to show me the same information doxygen does (or I simply can not find the right setting).

**Comment by randombit** [comment]
I agree, no reason to duplicate this information in each subclass if Doxygen handles it correctly and there is nothing additional to mention about the derived version.

**Comment by randombit** [comment]
BTW I have rebuilt the website so your additions are now live https://botan.randombit.net/doxygen/

Thanks again, this is one of those things that falls by the wayside too easily...

**Comment by cordney** [comment]
Great, thanks for updating the website!
