### ISSUE TITLE
Support recovering ECDSA public key from msg/signature pair

### ISSUE THREAD

**Issue by nathanhourt** [randombit/botan#664]
Can Botan be used for Bitcoin cryptography? Particularly for signing messages, verifying signatures, and deriving a public key from a message hash and signature?

**Comment by nathanhourt** [comment]
For the record, Bitcoin uses ECDSA on secp256k1

**Comment by neusdan** [comment]
All those questions are answered in the README.

**Comment by randombit** [comment]
Yes, ECDSA with secp256k1 curve is supported. But, Botan does not take advantage of the endomorphisms that allow fast scalar multiplies on the Koblitz curves or any other special curve-specific logic, it just uses the generic Weierstrass form, so it will be rather slower (guessing maybe 2-10x?) than special purpose code like libsecp256k1

**Comment by nathanhourt** [comment]
OK, and how do I recover a public key from a signature and message hash?

**Comment by randombit** [comment]
There is nothing in the library for this. There is an algorithm for it in SEC 1 Section 4.1.6 'Public Key Recovery Operation' http://www.secg.org/sec1-v2.pdf which seems like it would be easy to implement given the existing ECC code. Is this key recovery a common operation in Bitcoin?

**Comment by nathanhourt** [comment]
@randombit Yes, it's fundamental to the protocol, due to the use of addresses rather than public keys.

If you care why: all spendable bitcoins exist in Unspent Transaction Outputs (UTXOs) which are essentially records containing
```
{id: <unique id>,
 ownerAddress: <hash of public key>,
 amount: <some amount of BTC>}
```
(simplified, but it gets the idea across). In order to spend the BTC, I publish a transaction saying essentially, "Claim UTXO with ID <id>; send <amount> BTC to <address>, and <amount> to <address>, and ..." and this transaction is signed with the private key corresponding to the claimed UTXO's ownerAddress. To verify the transaction, the signature and transaction hash are combined to get ownerPublicKey, which is then hashed and compared to ownerAddress. Iff they match, the transaction is authorized.

**Comment by randombit** [comment]
I think your comment got mangled in one part but that does get the basic idea across, thanks. This seems worthwhile given how common Bitcoin is, and I could see this ability to precommit to an unrevealed key being useful in other applications.

I would take a PR implementing the recovery algo from SEC, I might do it myself if I felt suddenly motivated but I have a lot going on so this is not hugely likely in the near term.

**Comment by nathanhourt** [comment]
OK, good to know, thanks. :) I might try and implement it myself, but I usually prefer to avoid implementing low-level crypto algorithms when I can avoid it... :]

I think my previous comment should be demangled. Apparently github filters out &lt; and &gt; rather than escaping them.
