### ISSUE TITLE
VS2013::Botan app hangs forever, maybe related to AutoSeeded_RNG 

### ISSUE THREAD

**Issue by sebastiandev** [randombit/botan#67]
I've tried the latest src from github, compiled fine on VS2013 with cpu=x64. But when trying to run  a simple program that creates an RSA key, program hangs forever. Same thing happens trying to run botan.exe and botan_test.exe. Not sure if its an issue with AutoSeeded_RNG or what.

Code is pretty simple:

For 1.11.16
```
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include <cstring>
#include <memory>

#include <botan/botan.h>
#include <botan/rsa.h>
#include <botan/x509cert.h>
#include <botan/x509self.h>
#include <botan/pem.h>
#include <botan/oids.h>

using namespace std;

int main()
{
    try
    {
        cout << "Hello Botan!" << endl;
	cout << "Generate key.." << endl;
	AutoSeeded_RNG rng;
        RSA_PrivateKey rsaPrivate(rng, 1024);

        // just testing some stuff
        vector<Botan::byte> publicBytes  = X509::BER_encode(rsaPrivate);
	vector<Botan::byte> privateBytes = PKCS8::BER_encode(rsaPrivate, rng, "passphrase");

	ofstream pub("public.pem");
	pub << X509::PEM_encode(rsaPrivate);

	getchar();

     }
     catch(std::exception& e)
     {
        cerr << "Error: " << e.what() << "\n";
     }

	 return 0;
}
```

**Comment by randombit** [comment]
It is likely some bug in the Windows entropy sources that is causing an infinite loop. As I do not develop much on Windows I have made several blind changes recently, and right now the Windows CI system is building the library but not running the tests. I'll fire up a VM and try to replicate.

**Comment by sebastiandev** [comment]
Yes i guess so  too. I'll see if i can find something as well.

**Comment by webmaster128** [comment]
How long is "forever" @sebastiandev? RSA generation is damn slow on Windows. The Botan keygen test took 12 minutes in Windows today.

**Comment by sebastiandev** [comment]
Oh ok i surely didnt wait for 12minutes. I'll see if i can leave it running
and let u know what happens.
Thanks!

**Comment by sebastiandev** [comment]
well, I have launched botan-test and its been an hour so far and still running... 
Has anyone tried this on an Windows 7 64bits with Visual Studio 2013?

**Comment by webmaster128** [comment]
What is the last test output you got?

We're using Windows 7 32 bit with Visual Studio 2013 but there are implementation differences between 32 bit and 64 bit MSVC.

**Comment by sebastiandev** [comment]
I've got no output at all, and windows has probably sent it to very low
priority by now.

**Comment by webmaster128** [comment]
Are you running the entire tests `botan-test.exe` or did you add a parameter for some test suite?

**Comment by sebastiandev** [comment]
The entire test. Also running a simple app that creates a key and encodes
it, shows the same problem, it hangs for ever and nothing is written to
output.

```c++
int main()
{
    try
    {
        std::cout << "Hello Botan!" << std::endl;
std::cout << "Generate key.." << std::endl;
Botan::AutoSeeded_RNG rng;
std::cout << rng.name() << std::endl;
        rng.reseed(10096);
        Botan::RSA_PrivateKey rsaPrivate(rng, 1024);

vector<Botan::byte> publicBytes = Botan::X509::BER_encode(rsaPrivate);
vector<Botan::byte> privateBytes = Botan::PKCS8::BER_encode(rsaPrivate,
rng, "passphrase");

std::ofstream pub("public.pem");
pub << X509::PEM_encode(rsaPrivate);
getchar();
     }
     catch(std::exception& e)
     {
        std::cerr << "Error: " << e.what() << std::endl;
     }

  return 0;
}
```

**Comment by webmaster128** [comment]
Could you add the configure command you used?

**Comment by sebastiandev** [comment]
```
configure.py --debug-mode --with-boost
```

I have boost 1.57, linking in makefile looks like:

``` 
LIB_LINKS_TO   = advapi32.lib boost_filesystem-vc120-mt-gd-1_57.lib boost_system-vc120-mt-gd-1_57.lib user32.lib
```

I had to manually edit the boost dependencies because they where like boost_filesystem and boost_system

**Comment by webmaster128** [comment]
Are you sure you are not waiting for `getc()`. The following modified code runs for me in less than 3 seconds

```
#include <iostream>
#include <fstream>
#include <chrono>

#include <botan_all.h>

int main()
{
    auto start = std::chrono::steady_clock::now();

    try
    {
        std::cout << "Hello Botan!" << std::endl;
        std::cout << "Generate key.." << std::endl;
        Botan::AutoSeeded_RNG rng;

        std::cout << rng.name() << std::endl;
        //rng.reseed(10096);
        Botan::RSA_PrivateKey rsaPrivate(rng, 1024);

        std::vector<Botan::byte> publicBytes = Botan::X509::BER_encode(rsaPrivate);
        std::vector<Botan::byte> privateBytes = Botan::PKCS8::BER_encode(rsaPrivate, rng, "passphrase");

        std::ofstream pub("public.pem");
        pub << Botan::X509::PEM_encode(rsaPrivate);
     }
     catch(std::exception& e)
     {
        std::cerr << "Error: " << e.what() << std::endl;
     }

     auto end = std::chrono::steady_clock::now();
     auto diff = end - start;
     std::cout << std::chrono::duration <double, std::milli> (diff).count() << " ms" << std::endl;

     return 0;
}
```

Also getting 1.2 KB of seed data is very much overkill.

**Comment by sebastiandev** [comment]
yes im positive, but i will run this code today and see what happens.

Any particular configuration when building?

**Comment by webmaster128** [comment]
Note that

```
std::ofstream pub("public.pem");
pub << Botan::X509::PEM_encode(rsaPrivate);
```

does not necessarily write to disk before you either destruct `pub` (after `getc()` in your code) or call `pub.flush()` explicitly.

Note also that it took me 13 minutes to read 10096 bits of real entropy from `/den/random` on Linux. Windows might be (much) slower because the entropy source works entirely different there.

I successfully ran the code using all of those configurations

```
./configure.py --cpu=x86_32 --build-mode=debug
./configure.py --cpu=x86_32 --via-amalgamation --build-mode=debug
./configure.py --cpu=x86_32 --disable-shared --via-amalgamation --build-mode=debug
./configure.py --cpu=x86_32
```

where I used current master, which is especially necessary for the debug versions. Configuration no. 4 should work as well with the 1.11.18 release.

**Comment by webmaster128** [comment]
@sebastiandev Could you please check my last post? Otherwise I'll close this one.

**Comment by sebastiandev** [comment]
Simon, i'm sorry i wasn't at home.

I've been doing some testing and found this:

**Always using Visual Studio 2013**
```
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.50938
```

####  Scenario 1
Setting dev env as
```
> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\vcvars64.bat"

> configure.py --cpu=x86_64.
```

With this setup:
- botan builds **fine**
- tests **never end**, i don't get a single output
- When trying to compile my project, i get
 > Error	13	error C3861: '_umul128': identifier not found	c:\botan\include\botan-1.11\botan\mul128.h	84

The problem happens in *botan\mul128.h*:
```c++
inline void mul64x64_128(u64bit a, u64bit b, u64bit* lo, u64bit* hi)
   {
#if defined(BOTAN_FAST_64X64_MUL)
   BOTAN_FAST_64X64_MUL(a, b, lo, hi);
#else
```

####  Scenario 2
Setting dev env as
```
> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64_x86\vcvarsamd64_x86.bat""

> configure.py --cpu=x86_32
```

With this setup:
- botan builds **fine**
- tests **never end**
- sample app from above, **never ends**

####  Scenario 3
By looking at the CI server for windows, I used the same configs, thus:

```
> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat""

> configure.py --disable-shared --via-amalgamation --cpu=x86_32 --cc=msvc
```

I had to modify the Makefile to add the big object flag, otherwise it wouldn't compile.
```
CXX            = cl /MD /bigobj
```

With this setup:
- botan builds **fine**
- tests **run ok**
- sample app from above, **run ok**

----------------------------------------------------------------------------------------------------------------------------
So it looks that **x86_32 is the only one working**, and one needs to be **careful** about the **VS dev env selected**.

----------------------------------------------------------------------------------------------------------------------------

Also there are some issues in the install.py script, I had to comment out the lines 
```python
[22]
import combine_relnotes

[205]
with combine_relnotes.open_for_utf8(os.path.join(target_doc_dir, 'news.txt'), 'w+') as news:
    news.write(combine_relnotes.combine_relnotes('doc/relnotes', False))
``

**Comment by webmaster128** [comment]
1. `/bigobj` and combine_relnotes are fixed in 1.11.19.
2. Scenario 2: Is that a typo or a different installation? I have `bin\x86_amd64\vcvarsx86_amd64.bat` instead of `bin\amd64_x86\vcvarsamd64_x86.bat`. Looks like you start a 64bit compiler and try to configure 32bit Botan. With my path, Scenario 2 works for me.
3. Scenario 1: I neither have the directory "\VC\bin\amd64" nor the file "vcvars64.bat"

I am using Update 5 of MSVC 2013 Express

**Comment by sebastiandev** [comment]
2) is not a typo

So for 64bits the steps would be:

> This will use VC\bin\amd64
```
 "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat x64"
```

Then  ``` python configure.py --disable-shared --via-amalgamation --cpu=x64 --cc=msvc ```

Making sure /bigobj is added if you dont have 1.11.19

But when trying to compile the above simple app with x64 platform (in target machine and the corresponding x64 source directories), error is:
> 1>s:\fuentes\workspace\c++\botantest\botantest\botan_all.h(3846): warning C4163: '_umul128' : not available as an intrinsic function
1>s:\fuentes\workspace\c++\botantest\botantest\botan_all.h(3892): error C3861: '_umul128': identifier not found

I see there is no CI for 64bit architecture i guess that will prevent or at least warn about this issues. Has anyone tried successfully in x64?

**Comment by webmaster128** [comment]
How do your build your sample app? Are your sure you are still using a 64bit compiler? Since you include the header (`botan_all.h`) into your cpp file, the entire header is compiled again.

-------------------------

Btw. you must be using some kind of legacy names there. Looks like MS got more precise over the time since supporting Arm as well. For me

> "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64

is not available at all. I get 32bit vs. 64 bit the following way (check `cl` output for architecture):

```
C:\Users\me>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
C:\Users\me>cl
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Users\me>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
C:\Users\me>cl
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

**Comment by sebastiandev** [comment]
Yes there is a hell of a mess with architectures... i edited the comment because i was able to make it work. Some how deep in the config manager in visual studio x64 was still doing 32bits... meh...

i've checked my vcvarsall.bat and there you can see the supported flags and x64 is one of them, at least for me. Any way, it looks like is working now, but one has to be super careful about those setups. I can happily work on some guidelines for windows x64 compilation guide if you think is helpful.

**Comment by webmaster128** [comment]
Feed free to send pull request for the documentation at https://github.com/randombit/botan/blob/master/doc/manual/building.rst.

Closing this now.

**Comment by webmaster128** [comment]
I just added 64 bit to the AppVeyor CI
