### ISSUE TITLE
HMAC_DRBG: configuration of max_number_of_bytes_per_request

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#672]
Default the Botan `HMAC_DRBG` uses 64KB for `max_number_of_bytes_per_request`. I need to use a custom value here. 

So it would be nice if we can make this configurable by adding a new constructor parameter or a new value in `build.h`. Not sure which is the best. 

For a test run i already changed the hardcoded value to 64 Bytes and got a lot of test errors. Which i think is no surprise because this low value enforces a lot of reseeds which the test vectors are not expecting.

**Comment by randombit** [comment]
I'm OK with this. I think constructor arg is better here, otherwise changing the build-time constant breaks use of HMAC_DRBG as a deterministic generator (eg when generating a RSA key from a passphrase)
