### ISSUE TITLE
Wrong behavior of RSA_PublicKey::x509_subject_public_key

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#685]
The caller of this function would expect that it returns a X.509 subject public key as described in RFC5280:

```
SubjectPublicKeyInfo  ::=  SEQUENCE  {
        algorithm            AlgorithmIdentifier,
        subjectPublicKey     BIT STRING  }

```

But what it actually returns is a PKCS#1 RSAPublicKey:

```
RSAPublicKey ::= SEQUENCE {
          modulus           INTEGER,  -- n
          publicExponent    INTEGER   -- e
      }

```

**Comment by randombit** [comment]
The first structure is returned by `X509::BER_encode(Public_Key&)` by calling the (basically internal, but public on `Public_Key`) `algorithm_identifier` and `x509_subject_public_key`. We can do better - briefly:

`X509::BER_encode` is just `return pub_key.subject_public_key()`

The new function `Public_Key::subject_public_key` is a non-virtual identical to current `X509::BER_encode`

The (mostly/primarily for internal use) `x509_subject_public_key` is renamed in a way that is less confusing about what it returns (`public_key_bits`?).

The same issue applies on the private key side also with `PKCS8::BER_encode` vs `Private_Key::pkcs8_private_key`.

**Comment by neusdan** [comment]
Thanks for the clarification.  The proposed changes look good to me.
