### ISSUE TITLE
VS2013::Unresolved reference when using Win32_EntropySource version 1.10.9

### ISSUE THREAD

**Issue by sebastiandev** [randombit/botan#69]
Im on windows 7, VS2013. Everything seems to work fine, except when i try to use the Entropy source, Win32_EntropySource. I get an unresolved reference in the poll method. Not sure why, unless some particular library needs to be added to the linker.

***************************************************************************************************************
Error 15 error LNK2001: unresolved external symbol "public: virtual void __cdecl Botan::Win32_EntropySource::poll(class Botan::Entropy_Accumulator &)" (?poll@Win32_EntropySource@Botan@@UEAAXAEAVEntropy_Accumulator@2@@Z) C:\Fuentes\workspace\BotanTest\BotanTest\main.obj BotanTest
***************************************************************************************************************
```
#include <botan/botan.h>
#include <botan/rsa.h>
#include <botan/x509cert.h>
#include <botan/x509self.h>
#include <botan/pem.h>
#include <botan/internal/es_win32.h>
#include <botan/oids.h>

using namespace std;
using namespace Botan;


int main()
{
    try
    {
	Botan::LibraryInitializer init;
        cout << "Hello Botan!" << endl;

	cout << "Generate key.." << endl;
	Botan::AutoSeeded_RNG rng;
        Botan::Win32_EntropySource entropySource; ==> unresolved external reference
        rng.add_entropy_source(&entropySource);
        		
        Botan::RSA_PrivateKey rsaPrivate(rng, 1024);

        MemoryVector<Botan::byte> publicBytes  = Botan::X509::BER_encode(rsaPrivate);
	MemoryVector<Botan::byte> privateBytes = Botan::PKCS8::BER_encode(rsaPrivate, rng, "passphrase");

	ofstream pub("public.pem");
	pub << X509::PEM_encode(rsaPrivate);

	getchar();

     }
     catch(std::exception& e)
     {
        cerr << "Error: " << e.what() << "\n";
     }

	 return 0;
}
```

Im compiling everything in x64, but the same errors occurs in 32bits . Here's the linking line:

*******************************************************************************************************
/OUT:"S:\Fuentes\workspace\BotanTest\BotanTest\x64\Release\BotanTest.exe" /MANIFEST /LTCG /NXCOMPAT /PDB:"S:\Fuentes\workspace\BotanTest\BotanTest\x64\Release\BotanTest.pdb" /DYNAMICBASE "botan.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEBUG /MACHINE:X64 /OPT:REF /PGD:"S:\Fuentes\workspace\BotanTest\BotanTest\x64\Release\BotanTest.pgd" /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Release\BotanTest.exe.intermediate.manifest" /OPT:ICF /ERRORREPORT:PROMPT /NOLOGO /TLBID:1
*******************************************************************************************************

**Comment by randombit** [comment]
This class is not marked with BOTAN_DLL so is not in the list of visible symbols when used from the DLL.

That's because this class is not really meant for external use, in fact the declaration is entirely hidden in 1.11
