### ISSUE TITLE
Threaded_Fork does not behave correctly

### ISSUE THREAD

**Issue by randombit** [randombit/botan#695]
Threaded_Fork starts a pool of work threads (one per filter) which have the following main loop:

```
   while(true)
      {
      /*
      * This is plain wrong: a single thread can get the semaphore
      * more than one time, meaning it will process the input twice
      * and some other thread/filter will not see this input.
      */
      m_thread_data->m_input_ready_semaphore.acquire();

      if(!m_thread_data->m_input)
         break;

      filter->write(m_thread_data->m_input, m_thread_data->m_input_length);
      m_thread_data->m_input_complete_semaphore.release();
      }
```

A semaphore does not guarantee that each of N thread will acquire it exactly once, so for example if you had a `Threaded_Fork` that had two hash functions, and you sent the string 'A' to the pipe, it's possible one filter would see 'AA' and other other nothing at all, causing incorrect computations in both. Of course sometimes the semaphore acquisition happens to behave as the code expects and everything is fine - the odds decrease as the number of filters (and thus competing threads) increases.

There is a disabled test in `test_filters.cpp` that fails with some regularity on a multicore machine.

Opening an issue for this in the hopes someone else wants to take this on. If not I'll probably disable or remove Threaded_Fork before 2.0 so as not to ship something silently broken. I think the fix is just to replace the semaphore with a barrier? (http://stackoverflow.com/questions/24465533/implementing-boostbarrier-in-c11)

**Comment by lowjoel** [comment]
I've got a fix for this, I'm gunna submit a PR for this once I've checked that the build scripts are fine.
