### ISSUE TITLE
Compiling unicode version failed

### ISSUE THREAD

**Issue by icelemon1314** [randombit/botan#707]
System Info:
Windows 8.1 x64 Simplified Chinese
VS2015 x64 Native tool command prompt

When I use this compiler parameters, will be incorrect report：

 "D:\Program Files (x86)\Python27\python.exe" configure.py --cc=msvc --cpu=X64  --enable-modules=rsa,aes
nmake

        cl  /MD /bigobj /EHs /GR /O2 /W4 /wd4250 /wd4251 /wd4275 /Ibuild\include
 /nologo /c src\tests\test_compression.cpp /Fobuild\obj\test\test_compression.ob
j
test_compression.cpp
src\tests\test_compression.cpp: warning C4819: The file contained can not be found in the current code page (936)
Character representation。Save the file in Unicode format to prevent data loss
src\tests\test_compression.cpp(29): error C2001: There are line breaks in constants
NMAKE : fatal error U1077: “"D:\Program Files (x86)\vs2015\VC\BIN\amd64\cl.EXE"
”: return code“0x2”
Stop.

In the src\tests\test_compression.cpp(29) line 29,
   "Long time the manxome foe he sought—"
when I remove the — symbol, it's fine.

Hope that these can help to you,If you need additional information, contact me.

**Comment by randombit** [comment]
Fixed now, thank you for the report.
