### ISSUE TITLE
Unused values in build.h

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#708]
Looks like the following values are unused currently:

```
#define BOTAN_ENTROPY_EGD_PATHS { "/var/run/egd-pool", "/dev/egd-pool" }
#define BOTAN_ENTROPY_PROC_FS_PATH "/proc"
#define BOTAN_ENTROPY_SAFE_PATHS { "/bin", "/sbin", "/usr/bin", "/usr/sbin" }
```

**Comment by randombit** [comment]
Thanks. EGD paths and 'entropy safe path' are for removed entropy sources and can go. PROC_FS_PATH maybe should be used, currently global `ProcWalking_EntropySource` is initialized with fixed string "/proc" instead.

**Comment by randombit** [comment]
Fixed, thanks
