### ISSUE TITLE
Stream_Cipher_Mode untested

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#713]
I think this interface is completely untested. Unfortunately the Codecov report does not show the coverage of header files.

**Comment by randombit** [comment]
I think the problem with codecov it is looking for files in git under 'build/include' which are not found and so omitted entirely from the report. The `gcda` output files seem to be some binary format, I had hoped some simple seds to post-process the filenames could fix this, but no luck.

The coverage output on Travis shows all files including the headers  https://travis-ci.org/randombit/botan/jobs/172835158 in the `after_success.sh` output. Almost all headers have a high hit rate and low line counts so I am not too concerned about codecov missing the headers, though it would be nice to fix.

Btw here is my list (based on codecov output) of other things that have effectively no tests, ordered roughly how hair-on-fire bad it is that we have no tests for them

- OCSP
- http_util
- DL_Group generation and encode/decode
- Various special cases in prime generation (bits=3, etc), also some statistical tests of this code would be nice to have.
- X.509 alt name IP address and othername handling
- GOST 34.10 signature generation (no signature gen KATs)
- PKCS9 email address + challenge password fields
- Package transform
- SRP6 file handling
- TLS blocking interface

Especially OCSP parsing tests on a corpus of request/responds would be nice to have :(

**Comment by cordney** [comment]
Re codecov and header files, since v4 a `codecov.yml` file can be placed in the root directory of the repo that is able to customize a lot of things. There is also quite a lot of docs now on http://docs.codecov.io.

You may find something regarding the header files on http://docs.codecov.io/docs/fixing-paths or http://docs.codecov.io/docs/path-regexp.

**Comment by randombit** [comment]
The example for fixing paths is intriguing but not (I think) quite enough for what we need. Since that page says to mail support with questions, I emailed codecov support detailing the problem - hopefully the path fixup syntax is (or can be made) general enough to handle this case.

**Comment by randombit** [comment]
I think with b3d598a it is tested now, though I haven't checked how much of the class is actually used when run via the cipher mode tests.
