### ISSUE TITLE
--with-gnump not accepted?

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#719]
According to `doc/manual/building.rst` line 303, `configure.py` is supposed to accept parameter `--with-gnump` that instructs Botan build to use GMP library.

However this parameter is not recognized - `./configure.py --with-gnump . . .` complains that `--with-gnump` is unknown.

If Botan can no longer use GnuMP,  the documentation needs to be adjusted (remove the reference).

If Botan still can utilize GnuMP - `configure.py` needs to be fixed to accept that parameter again.

**Comment by randombit** [comment]
GNU MP removed in 1.11.10, must have missed this. Thanks
