### ISSUE TITLE
OSS-Fuzz

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#750]
A cool new project which fuzzes open source projects. We should try to get Botan integrated there.

https://github.com/google/oss-fuzz
https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html?m=1

**Comment by randombit** [comment]
I saw this, looks like a great program but per the blog post "In order for a project to be accepted to OSS-Fuzz, it needs to have a large user base and/or be critical to Global IT infrastructure" so not clear they would take us.

**Comment by mgierlings** [comment]
I guess there is only one way to find out =)

**Comment by neusdan** [comment]
@randombit Nothing to loose ;) We should just try it. 

Could you create a PR at the OSS-Fuzz repository adding the file `projects/botan/project.yaml` with the following contents:

```
homepage: "https://botan.randombit.net"
primary_contact: "jack@randombit.net"
```

And if you like you can add @cordney and me with the `auto_ccs:` block like [here](https://raw.githubusercontent.com/Rohde-Schwarz-Cybersecurity/oss-fuzz/master/projects/libarchive/project.yaml)

Thanks a lot!

**Comment by randombit** [comment]
Posted https://github.com/google/oss-fuzz/pull/121

**Comment by mgierlings** [comment]
@randombit: I did some quick research on botan usage and found another interesting reference. [Bosch Security Systems](http://resource.boschsecurity.com/documents/Bosch_VMS_Open_Sourc_Application_note_enUS_20710840843.pdf) seems to be using Botan (or parts of it) in [their products](http://www.boschsecurity.com/oss/).

**Comment by randombit** [comment]
Another interesting user I found is shadowsocks https://github.com/shadowsocks/libQtShadowsocks https://github.com/shadowsocks/shadowsocks-qt5

it appears to be a popular mechanism for bypassing Internet censorship in China, and the project website offers downloads of shadowsocks-qt5 for both Linux and Windows users https://shadowsocks.org/en/download/clients.html

Also ... OSS-Fuzz agreed to fuzz for us! I'm working on the docker integration bits now so the fuzzers can start up in Google's Clusterfuzz env.

**Comment by cordney** [comment]
Botan was accepted, this is great! Thanks @neusdan for insisting and @randombit for doing the PR.

**Comment by randombit** [comment]
Opened a PR to add the fuzzer integration in https://github.com/google/oss-fuzz/pull/150 once merged Clusterfuzz should start running in short order.

**Comment by randombit** [comment]
PR has been merged to oss-fuzz master! Closing. @neusdan  @mgierlings thanks again for the encouragement to submit Botan.
