### ISSUE TITLE
Guideline Support Library

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#752]
What do you think about using the [Guideline Support Library](https://github.com/Microsoft/GSL)?
It's small, header only and seems to have a good platform support. Would probably the best to ship it with Botan. I especially like the idea to replace all pointer arithmetic with `span`.

**Comment by randombit** [comment]
I hadn't seen this library before. `span` concept does seem very useful, I'm not so sure about the rest. I will try it out soon and think it over.

**Comment by webmaster128** [comment]
If you're a video guy you might be interested in the GSL introduction on CppCon 2015 for the overall idea and the motivation

https://www.youtube.com/watch?v=1OEu9C51K2A&list=PLHTh1InhhwT75gykhs7pqcR_uSiG601oh&index=1
https://www.youtube.com/watch?v=hEx5DNLWGgA&index=2&list=PLHTh1InhhwT75gykhs7pqcR_uSiG601oh

**Comment by randombit** [comment]
Closing this - now with C++20 on master we can use `std::span` which seems like the main attractor for GSL
