### ISSUE TITLE
Can support for external headers be removed from build system?

### ISSUE THREAD

**Issue by randombit** [randombit/botan#767]
This was added for PKCS11 support in 7944a67bd083, but we ended up deciding it was easier to just ship the PKCS11 headers in the library source, rather than tangle with the N different ways the PKCS11 headers can/can not be installed on different OSes. So the external header support is completely unused.

I'm doing some cleanups in the build system, and am wondering if this code can be removed entirely. Or perhaps there is some similar situation that will arise in the future, and we should keep the code? Seems like other libraries whose headers we use (zlib, openssl etc) there is always an associated link library and we are never just importing a fixed header from some external source.

**Comment by neusdan** [comment]
AFAIK for Windows there is still not way to use Botan with OpenSSL or Boost for example. Because these libs are not header-only the `--with-external-includedir` option alone does not help here. But if we add, for example a `--with-external-libdir` we could use on Windows external libs and #19 would be resolved.

**Comment by randombit** [comment]
@neusdan I forget about Windows most of the time ;) yes probably useful there if we had libdir support also.

**Comment by MeerMusik** [comment]
Hello.

Yes please make it possible to allow us to use OpenSSL on Windows. I wasted a whole weekend trying to get Botan compiled with the following Batch File Commands:
```
:START
set PATH=%PATH%;C:\nasmx64\;C:\Perlx64\perl\bin\;C:\Pythonx64\;C:\opensslx64\bin\;c:\opensslx64\include\;C:\opensslx64\lib\
if not exist C:\Botansrcx64\ ( 
mkdir C:\Botansrcx64\ 
goto :BUILD 
)

if exist C:\Botansrcx64\ ( 
cd C:\Botansrcx64\
goto :BUILD 
)

:BUILD
cd C:\Botansrcx64\ && xcopy /v /f /y /s "C:\Botansrc\*.*" "C:\Botansrcx64\*.*" && set OPENSSL_CONF=C:\opensslx64\ssl\openssl.cnf && set CL=-d2SSAOptimizer- -MP && configure.py --prefix=c:\botanx64\ --cc=msvc --with-openssl --with-external-includedir=c:\opensslx64\include\

PAUSE;
jom -j3 && botan-test.exe && jom -j1 install
PAUSE;
```
And I always got a Linker Error at the End about 'crypto.obj not found'.
Worst thing: I followed the official Build Instructions and I found not a single Statement that OpenSSL usage is broken on Windows.
Dev Environment:
* Windows 10, x64, latest Anniversary Update
* Windows 10 SDK 10586 (a 3rd Party Lib dont support 14393 yet)
* Visual Studio 2015, Update 3.1, Community Edition, SSA Optimizer disabled

Thanks from a total Botan Newbie, who would love to replace OpenSSL with Botan in the Qt Framework some day :)

**Comment by neusdan** [comment]
i'll look into this in the next days.

**Comment by MeerMusik** [comment]
Thanks. But just to let you know: In my case: Botan is something I would love to start using around the end of 2017 - my Pet Project is still in Pre-Alpha yet. So definitely no need to rush it from my Side :)

**Comment by MeerMusik** [comment]
Wow, I totally forgot to say: Thank You :)
