### ISSUE TITLE
segfault during Botan 1.11.34 build : /usr/include/c++/6/bits/stl_iterator_base_funcs.h:79:5: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by pgnd** [randombit/botan#772]
building latest Botan release. 1.11.34
    
    wget http://botan.randombit.net/releases/Botan-1.11.34.tgz
    tar zxvf Botan-1.11.34.tgz
    cd Botan-1.11.34

on linux64, build fails,

    ./configure.py \
    --prefix=/usr/local/botan \
    --libdir=lib64 \
     --with-bzip2 \
     --with-zlib \
     --with-openmp \
     --with-boost \
     --with-sqlite3 \
     --without-openssl \
     --makefile-style=gmake
    make V=1

        ...
        g++  -fopenmp -m64 -pthread -fstack-protector -msse2 -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/block/noekeon/noekeon_simd/noekeon_simd.cpp -o build/obj/lib/block_noekeon_simd.o
        g++  -fopenmp -m64 -pthread -fstack-protector -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/block/seed/seed.cpp -o build/obj/lib/block_seed.o
        In file included from /usr/include/c++/6/bits/stl_algobase.h:66:0,
                         from /usr/include/c++/6/memory:62,
                         from build/include/botan/types.h:16,
                         from build/include/botan/key_spec.h:11,
                         from build/include/botan/sym_algo.h:11,
                         from build/include/botan/block_cipher.h:11,
                         from build/include/botan/seed.h:11,
                         from ./src/lib/block/seed/seed.cpp:8:
        /usr/include/c++/6/bits/stl_iterator_base_funcs.h: In substitution of ‘template<class _InputIterator> typename std::iterator_traits<_Iterator>::difference_type std::__distance(_InputIterator, _InputIterator, std::input_iterator_tag) [with _InputIterator = char*]’:
        /usr/include/c++/6/bits/stl_iterator_base_funcs.h:138:29:   required from ‘typename std::iterator_traits<_Iterator>::difference_type std::distance(_InputIterator, _InputIterator) [with _InputIterator = char*; typename std::iterator_traits<_Iterator>::difference_type = long int]’
        /usr/include/c++/6/bits/basic_string.tcc:575:63:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
        /usr/include/c++/6/bits/basic_string.h:4275:30:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
        /usr/include/c++/6/bits/basic_string.h:4296:27:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
        /usr/include/c++/6/bits/basic_string.tcc:669:31:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = char*; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
        /usr/include/c++/6/ext/string_conversions.h:105:14:   required from ‘_String __gnu_cxx::__to_xstring(int (*)(_CharT*, std::size_t, const _CharT*, __va_list_tag*), std::size_t, const _CharT*, ...) [with _String = std::basic_string<char>; _CharT = char; std::size_t = long unsigned int]’
        /usr/include/c++/6/bits/basic_string.h:5457:20:   required from here
        /usr/include/c++/6/bits/stl_iterator_base_funcs.h:79:5: internal compiler error: Segmentation fault
             __distance(_InputIterator __first, _InputIterator __last,
             ^~~~~~~~~~
        Makefile:550: recipe for target 'build/obj/lib/block_seed.o' failed
        make: *** [build/obj/lib/block_seed.o] Error 1

**Comment by pgnd** [comment]
fwiw

building/linking against a local openssl build (1.0.2j), rather that distro's  pkgs AND excluding modules

    "gost_28147,gost_3410,gost_3411,threefish,threefish_avx2,tiger,twofish"

from the config works around the build segfault(s),

    botan version --full
        Botan 1.11.34 (released, dated 20161128, revision git:b816a3652c1359028f59d64a2f742564547ab782, distribution unspecified)

**Comment by randombit** [comment]
> internal compiler error: Segmentation fault

Thanks for the report, but you should take this up with your compiler vendor (upstream Linux distro, or the GCC project itself if you are using one of their releases). There is not much we can do about the compiler crashing. It is interesting though, I have not run into a GCC ICE in a long time, and you appear to be using GCC 6 which works fine for me using the same build flags.
