### ISSUE TITLE
botan 1.10 - amalgamation build for arm generates c++11 code

### ISSUE THREAD

**Issue by adnan-kamili** [randombit/botan#773]
Hi,

I used botan 1.10 on mac, windows and linux. On linux the gcc compiler used is v4.7.2. When I create an amalgation build for 32 and 64 bit cpu arch it works fine and generates code with no c++11 functions:

`configure.py --cc=gcc --cpu=x86_32 --no-autoload --gen-amalgamation --enable-modules=rsa,eme_pkcs,emsa3,emsa4,sha1,auto_rng,cbc,kdf2,asm_engine,pthreads,unix_procs`

but when I use it to generate the amalgamation build for arm

`configure.py --cc=gcc --cpu=armv7-a --no-autoload --gen-amalgamation --enable-modules=rsa,eme_pkcs,emsa3,emsa4,sha1,auto_rng,cbc,kdf2,asm_engine,pthreads,unix_procs`

It generates file with c++11 function like std::to_string() and compilation fails. I also get a plethora of other others like

```
botan_all_gcc_arm.cpp:20662:13: error: redefinition of ‘std::__cxx11::string Botan::Charset::transcode(const string&, Botan::Character_Set, Botan::Character_Set)’
 std::string transcode(const std::string& str,...
```

**Comment by randombit** [comment]
This should have already been fixed in https://github.com/randombit/botan/commit/632e3478262ac85137266d05dc96b367418f36d4 but this fix has not been part of a new release yet (probably coming shortly). Can you verify the referencedchange fixes the problems you are seeing?

**Comment by adnan-kamili** [comment]
No it doesn't, I get other errors like

```
botan_all_gcc_arm.cpp:20662:13: error: redefinition of ‘std::__cxx11::string Botan::Charset::transcode(const string&, Botan::Character_Set, Botan::Character_Set)’
 std::string transcode(const std::string& str,...
```

and list is so long that console fails to display them all

**Comment by adnan-kamili** [comment]
My host OS is Debian 7, it has gcc compiler v4.7.2. I will look into it further and revert back. I hope my configure command is fine.

**Comment by adnan-kamili** [comment]
I get the redefinition error for every function:

```
error: redefinition of ‘void Botan::HMAC_RNG::add_entropy_source(Botan::EntropySource*)’
 void HMAC_RNG::add_entropy_source(EntropySource* src)
```

**Comment by adnan-kamili** [comment]
Do you know why it is happening?

**Comment by randombit** [comment]
No clue, sorry. Maybe try a clean rebuild, or use `nm` to find in which object(s) the symbols are being defined - why are there two copies and where are they coming from?

FWIW while GCC 4.7 probably works it is not tested by CI or developers, if possible upgrade to GCC 4.8 or later.

**Comment by randombit** [comment]
Closing as inactive. @adnan-kamili if you are still having issues with latest version feel free to open a new issue.
