### ISSUE TITLE
MSVC, Windows Phone and "error C2039: 'GetProcessWorkingSetSizeEx': is not a member of global namespace"

### ISSUE THREAD

**Issue by noloader** [randombit/botan#796]
And one more... Botan is doing very well. I usually see more problems than this when porting to Windows Phone and Windows Store.

```
cl  /MD /bigobj /FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP /DBOTAN_DLL=__declspec(dllexport) /EHs /GR /O2 /W4 /wd4250 /wd4251 /wd4275 /Ibuild\include /nologo /c C:\botan-src\src\lib\utils\os_utils.cpp /Fobuild\obj\lib\utils_os_utils.obj
os_utils.cpp
C:\botan-src\src\lib\utils\os_utils.cpp(193): error C2039: 'GetProcessWorkingSetSizeEx': is not a member of '`global namespace''
C:\botan-src\src\lib\utils\os_utils.cpp(193): error C3861: 'GetProcessWorkingSetSizeEx': identifier not found
C:\botan-src\src\lib\utils\os_utils.cpp(269): error C2039: 'VirtualLock': is not a member of '`global namespace''
C:\botan-src\src\lib\utils\os_utils.cpp(269): error C3861: 'VirtualLock': identifier not found
C:\botan-src\src\lib\utils\os_utils.cpp(293): error C2039: 'VirtualUnlock': is not a member of '`global namespace''
C:\botan-src\src\lib\utils\os_utils.cpp(293): error C3861: 'VirtualUnlock': identifier not found
```

**Comment by noloader** [comment]
I'm not sure what to do with the missing functions due to Windows Phone and Windows Store. Maybe you can use code similar to the following to detect a phone app, and then ensure defines like `BOTAN_TARGET_OS_HAS_VIRTUAL_LOCK` are not defined.

```
#if defined(WINAPI_FAMILY)
#  if (WINAPI_FAMILY_PARTITION(WINAPI_FAMILY_PHONE_APP))
      // Its a Windows Phone app
#  endif
#endif
```

**Comment by randombit** [comment]
If `VirtualLock` and co are not supported on Windows Phone (even as stubs) likely much more of Win32 is missing. To avoid conflating Windows (classic desktop Win32 API) with Windows phone (something else that's clearly only partially compatible, and presumably with its own security APIs), it would be better to add a specific windowsphone OS target. I'll do this.

Is there a better name for this target than `windowsphone`? I know very little about this OS product.

**Comment by randombit** [comment]
Fixing this touches parts of the build that I cannot easily test myself (eg, modifying for Windows Phone also means modifying for Windows, and I rely entirely on CI and other devs for Windows testing, and this involves a lot of turnaround time that I want to avoid right now), I'm deferring Windows Phone support (both this ticket and #794) to 2.1. It would be great to support it out of the box and it seems like it will not even be too much trouble to do. It is just again a problem of timing for 2.0. Thanks again for all this testing.

**Comment by noloader** [comment]
@randombit,

Ack, thanks.  Let me know when you want re-testing. I'd be happy to do it.

**Comment by noloader** [comment]
@randombit,

> Is there a better name for this target than windowsphone? I know very little about this OS product.

Lol... Microsoft has (what appears to me) at least three iterations of the updated APIs for phone and store apps. The latest iteration is [Universal Windows Platform (UWP)](https://msdn.microsoft.com/en-us/windows/uwp/layout/design-and-ui-intro) and its present in the Windows 10 gear for desktops, servers, phones and tablets.

Tracing things back, the first iteration appeared to be Windows Phone 7 or 8, and it only applied to Phones. Windows Phone 7 was mostly an experiment, and its probably not worth worrying about. Windows Phone 8 also applied to the Surface tablets for ARM around the same time. The Surface tablets were another experiment, and its probably not worth worrying about. (I purchased test gear for the ARM Surface tablets, and I was never been able to use them for anything. You could only load apps from the Microsoft App store, and Visual Studio never supported them. It was a waste of nearly $3500 USD).

For Windows Phone 8, if I am not mistaken, its simply known as the "Windows Phone Runtime" or "Windows Phone 8 API". Also see [Windows Phone Runtime API](https://msdn.microsoft.com/en-us/library/windows/apps/jj207212(v=vs.105).aspx). The macro or identifier that made sense was something like `WINDOWS_RT` for the newer runtime.

Windows Phone 8 crippled existing APIs and added some new ones. Some of the new ones were provided for desktops and server, too. That's why MSDN will list *"Minimum supported client"*, *"Minimum supported server"* and *"Minimum supported phone"*. See, for example, [MSDN GetTickCount64](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411(v=vs.85).aspx).

Between Windows Phone and Windows UWP saw something called Windows Universal CRT. This was short lived, and I think it became Windows UWP. It mostly included the earlier Windows Phone stuff, including the crippled APIs and adding some new ones.

We did not like saying "Windows Phone" or supplying macros like `MYLIB_WINDOWS_PHONE` or `MYLIB_WINDOWS_RT`, when it applied to the newer API set introduced with Windows Phone, especially when it applied to desktop and store apps, too. We kind of fell back to the identifier `WINDOWS_8_API`. Maybe Botan could use `BOTAN_WIN8_API` if/when `( _WIN32_WINNT >= 0x0602 || WINVER >= 0x0602)`.

***If*** you are a GUI programmer, then `BOTAN_WIN8_API` may be too coarse grained. However, I've found that `BOTAN_WIN8_API` works well for libraries like Botan, Crypto++ and OpenSSL. It is enough to know that the Bcrypt gear is available, and it is enough to know when to include different header files for 20 year old APIs. 

For completeness, below is an example of the *"different header files for 20 year old APIs"* issue. `GetCurrentThread` and `GetThreadTimes` are available from Windows XP, Server 2003 and forward. However, the header file changes depending on desktop, server, phone or tablet. XP/2003 can include `<windows.h>`, while Windows 8/Server 2012 requires `<processthreadsapi.h>`, and Windows Phone requires `<profileapi.h>`. This is why I kind of lean towards `MYLIB_WINDOWS_8`  (i.e., `BOTAN_WIN8_API`), and not `MYLIB_WINDOWS_PHONE` or `MYLIB_WINDOWS_RT`.

```
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#ifdef BOTAN_WIN8_API
# include <processthreadsapi.h>
# if defined(WINAPI_FAMILY)
#  if (WINAPI_FAMILY_PARTITION(WINAPI_FAMILY_PHONE_APP))
#   include <profileapi.h>
#  endif
# endif
#endif
```

-------

An underlying problem is getting the library in a good configuration, and knowing when you should do things like force include `<sdkddkver.h>` and `<winapifamily.h>`. These are needed for Windows Phone through Windows UWP (including Wwindows phone apps and windows store apps), and library defines like `BOTAN_WIN8_API`.

What I found that works best when using one of Microsoft's Command Developer Prompts is the following. Its used in Crypto++'s [cryptest.nmake](https://github.com/weidai11/cryptopp/blob/master/cryptest.nmake) makefile. It works because Microsoft sets the macros like `WINDOWSSDKDIR` in the environment of the command prompt, and `WINDOWSSDKDIR`  can be used to key on the include availability of `<sdkddkver.h>`.

```
# Attempt to detect when <sdkddkver.h> and <winapifamily.h> are available
#   http://stackoverflow.com/q/40577415 ?
!IF "$(WINDOWSSDKDIR)" != "" || "$(WINDOWSSDKLIBVERSION)" != ""
CXXFLAGS = $(CXXFLAGS) /FI sdkddkver.h
!ENDIF
!IF "$(WINDOWSPHONEKITDIR)" != "" || "$(UNIVERSALCRTSDKDIR)" != "" || "$(UCRTVERSION)" != ""
CXXFLAGS = $(CXXFLAGS) /FI winapifamily.h
!ENDIF
```

Botan is currently agnostic to `<sdkddkver.h>` and `<winapifamily.h>`, so I knew I had to configure with the following to get things in order for Windows Phone. If I did not perform the force include, then I knew goodness like [<winapifamily.h> and "fatal error C1012: unmatched parenthesis : missing ')'](http://stackoverflow.com/q/36912135) was lying in wait.

```
configure.py --cc=msvc --cpu=armv7a --cc-abi="/FI sdkddkver.h /FI winapifamily.h /DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP"
```

**Comment by randombit** [comment]
Should be fixed now
