### ISSUE TITLE
Use a different Sphinx theme for the website

### ISSUE THREAD

**Issue by cordney** [randombit/botan#822]
The Spinhx theme currently used for the website [agogo](http://www.sphinx-doc.org/en/1.5.1/theming.html) doesn't look very modern and sometimes text overflows boxes, e.g., some source code examples on the [PKCS11](https://botan.randombit.net/manual/pkcs11.html) page. The [index](https://botan.randombit.net/manual/genindex.html) page also looks really messed up.

There are some themes out there with better layouts, better typography and better mobile support that also feature a modern look. Some are [included](http://www.sphinx-doc.org/en/1.5.1/theming.html) in Sphinx, others are developed by 3rdparty devs, e.g., http://www.writethedocs.org/guide/tools/sphinx-themes/ and https://github.com/yoloseem/awesome-sphinxdoc#themes list some extra ones. Here's a curated list of my favs with a preview:

* agogo theme (current): http://botan.randombit.net/manual/
* [readthedocs.io](https://github.com/snide/sphinx_rtd_theme) theme: http://cordney.com/botan/themes/rtd/
* [sphinxjp.themes.basicstrap](https://github.com/tell-k/sphinxjp.themes.basicstrap) theme: http://cordney.com/botan/themes/basicstrap/
* [bootstrap](https://github.com/ryan-roemer/sphinx-bootstrap-theme) theme: http://cordney.com/botan/themes/bootstrap/
* [guzzle](https://github.com/guzzle/guzzle_sphinx_theme) theme: http://cordney.com/botan/themes/guzzle/

My favourite is currently the readthedocs theme, but I look forward to other proposals.

**Comment by randombit** [comment]
Thanks for pointing out these issues and generating the preview versions, from a brief glance rtd or guzzle themes both look fine to me. No particular love for the current theme, I picked it randomly years ago and haven't looked at it since.

Maybe let's do rtd, unless someone points out some problem I missed with it, since it is a common doc theme and so "looks like" a documentation website to a programmer.

**Comment by randombit** [comment]
#823 merged, website rebuilt.
