### ISSUE TITLE
FFI docs are incomplete

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#838]
The FFI handbook page is incomplete. It does not list all functions currently available and for the functions it lists, there is little to no usage documentation. Some example code would also certainly be helpful, for more examples we could link to the ffi tests.

**Comment by randombit** [comment]
An additional example of usage is the Python ctypes wrapper which calls FFI API.

**Comment by randombit** [comment]
FFI docs are in a much better state these days, closing this. Documentation PRs always welcome though! :)
