### ISSUE TITLE
FFI botan_pbkdf does not accept arbitrary input for pass

### ISSUE THREAD

**Issue by G3nna** [randombit/botan#855]
Lets say you want to use the generated key from a botan_pbkdf call as the pass in another call of botan_pbkdf (like sqlcipher, where I include botan into, does) and the generated key from the first call contains the null terminator somewhere in the middle. Then only the chars up to the null terminator are used (because of the std::string constructor) and the rest is discarded. The resulting key then of course differs from implementations which use all the provided chars (like openssl) and compatibility breaks. 
I don't think that this is how it should work. What we need is to be able to specify the amount of chars to read from the provided pass.

**Comment by randombit** [comment]
Thanks for pointing this out. Probably FFI needs an alternative API that takes both char* + size_t length

**Comment by randombit** [comment]
In upcoming 2.8 this has been implemented with a new interface `botan_pwdhash` (#1670) which accepts an explicit length.
