### ISSUE TITLE
Add OS X Travis CI build

### ISSUE THREAD

**Issue by cordney** [randombit/botan#86]
As a followup of #78, please add a OS X build in Travis CI. As we now have Linux and Windows builds, this would complete the coverage of all major platforms.

What you have to do:

* Request a multi-OS job for Botan as noted in the doc: http://docs.travis-ci.com/user/multi-os/
* Change the `.travis.yml` accordingly; in contrast to the doc, I had no luck with the `os: - osx` setting, but only setting `language: - objective-c` forced the build to run on an OS X runner

See https://github.com/cordney/botan/blob/travisci_osx/.travis.yml for an example yml which only builds on OS X. Maybe you have to experiment with the settings a bit.

**Comment by webmaster128** [comment]
Travis does not accept multi OS requests at the moment

> We are not currently accepting multi-OS requests

from [Testing Your Project on Multiple Operating Systems](http://docs.travis-ci.com/user/multi-os/)

**Comment by cordney** [comment]
See also #78. I asked for a multi-OS project by email 2 month ago, regardless of what the website stated. They were really kind and asked me to come back in a month again, when they have upgraded their infrastructure. I would at least try and ask again once more.

**Comment by webmaster128** [comment]
Thanks @cordney! I'm on it.

**Comment by webmaster128** [comment]
Just got the confirmation that multi-os is enabled. Could you restore this file somehow @cordney? https://github.com/cordney/botan/blob/travisci_osx/.travis.yml

**Comment by cordney** [comment]
This is great news! Ah yes, I dropped my whole fork, because it was easier to create a new one after the branches were renamed. But I found the commit I tested the OS X CI build with: https://github.com/cordney/botan/commit/fc9eb216eb9988819c83fe8b5e5200c21a6f05cc

There is no magic there, I simply dropped all the other OSes in the .travis.yml to only test OS X. The integration work still remains. If I can help with that, simply drop me a line.

**Comment by webmaster128** [comment]
Can you have a look at this PR, please? #159 There you see my current changes for the OS X configuration. The latest build output should be this one: https://travis-ci.org/randombit/botan/builds/69054398

Is there anything I am missing?

**Comment by webmaster128** [comment]
Thanks for pushing this. Done.

**Comment by cordney** [comment]
Sorry, had no time to review this yesterday. Looks fine to me. Thanks for merging.

**Comment by webmaster128** [comment]
No problem, I was just waiting for an answer from the Travis support about the following nice-to-know detail: There is a container-based and VM-based infrastructure at Travis. We force the VM-based one because we need sudo. This setting does not apply for OS X since there is only one kind of infrastructure.
