### ISSUE TITLE
False assertion 'The nonce is fresh for this message'

### ISSUE THREAD

**Issue by librehat** [randombit/botan#864]
We've hit an assertion failure which is introduced in botan 2.0 (since 1.11 dev branch). It breaks the behaviour in botan-1.10, with which we could re-use nonces for encryption. But with botan-2, an assertion failure is triggered.

However, this is how shadowsocks stream protocol is designed, and other cipher suites work perfectly well (including previous version of botan). The rationale behind this assertion is to enforce "better practice" and "better security". However, it should really be up to downstream developers rather than library providers.

This is not a programmatic error, can we remove this assertion? This is effectively breaking the back-compatibility with software that has been written with botan-1.10 that needs this particular behaviour.

References:
https://marc.info/?l=botan-devel&m=145755126216465&w=2
https://github.com/shadowsocks/libQtShadowsocks/issues/104

**Comment by randombit** [comment]
Can you be more clear about what you mean by "re-use nonces" in this context, and also which cipher mode Shadowsocks uses? I am thinking what Shadowsocks is doing here is probably not so great, but it's a deployed protocol and the code worked in 1.10.

The cipher mode implementations are completely different between 1.10 and 2.0, and the behavior from simply removing this assert would not be identical to the behavior in 1.10. It would result in the same (identical) nonce being used for each message. In 1.10, not calling set_iv between calls resulted in the nonce being 'carried over': for example with CBC this resulted in using the final CBC ciphertext block as the next IV.

In 2.0, the Filter cipher code (for all cipher types) is interacting with the new `Cipher_Mode` class, which doesn't support nonce carry over at all. I think what would have to happen is add a new method to `Cipher_Mode` to retrieve the current IV state for modes where that makes sense (CBC and CTR, mostly). Then if no new nonce is set, `Cipher_Mode_Filter` will call this to get the next nonce value.

**Comment by librehat** [comment]
I mean in my implementation, I use the filter cipher code to get a `pipe` and set key and nonce. After that, I simply use that `pipe` to encrypt all messages that belong to one TCP session. Thus, there is no `set_iv` call between two messages encryptions. It seems nonce was 'carried over' in 1.10.
The mode we currently have are CFB and CTR. (We also have plain Salsa20 and Chacha20, not sure how it affects them in this case?)

**Comment by randombit** [comment]
OK, I understand now. I have not tested this (there should be tests added covering all of these issues to make sure we got everything right) but the stream ciphers (Salsa20, ChaCha and also CTR which is implemented as a stream cipher class) actually should be unaffected. They go through a different class `StreamCipher_Filter` which does not require a new nonce between messages, and simply carries over the cipher's state. The `StreamCipher_Filter` exists basically unchanged in both 1.10 and 2.0. So, you should only be having problems with CFB mode, is this correct?

The concept of an implicit or carryover nonce makes no sense in the context of AEAD modes, or for XTS. But CFB and CBC are often used in this way, and the filters API makes it very easy to do. So 2.1 will remove the assert and (for CFB and CBC modes) handle carrying over the nonce if a new one was not explicitly set, so code works as in 1.10.

**Comment by librehat** [comment]
I call `Botan::get_cipher` to get a `Botan::Keyed_Filter` object, then create a `Pipe` with that filter. (If you wish to take a quick look, https://github.com/shadowsocks/libQtShadowsocks/blob/master/lib/cipher.cpp#L60). I've checked yesterday that even stream ciphers like ChaCha is also affected. I got the same assertion message.

**Comment by librehat** [comment]
I see it didn't make it for release 2.1, would it be in 2.2? Still waiting for the fix :)

**Comment by randombit** [comment]
Thank you for the ping and yes plan to fix this in 2.2. I have a patch that fixes the problem for CBC but need to also fix it for CFB and stream ciphers.
