### ISSUE TITLE
Decoding fails if optional entrys in BER-Encoding of EC-Curves are present.

### ISSUE THREAD

**Issue by fschueller-ifd** [randombit/botan#874]
The BER-Encoding of an elliptic Curve in explicit form is defined as
 ```
 ECParameters ::= SEQUENCE { -- Elliptic curve parameters
    version ECPVer,
    fieldID FieldID,
    curve Curve,
    base ECPoint, -- Base point G
    order INTEGER, -- Order n of the base point
    cofactor INTEGER OPTIONAL } -- The integer h = #E(Fq)/n

ECPVer ::= INTEGER {ecpVer1(1)}

Curve ::= SEQUENCE {
    a FieldElement, -- Elliptic curve coefficient a
    b FieldElement, -- Elliptic curve coefficient b
    seed BIT STRING OPTIONAL }
```
Botan fails to decode the BER if the optional BIT STRING "seed" is present. Botan may ignore this entry, but it should not fail to decode if present.

**Comment by randombit** [comment]
Thanks for the report. Do you happen to have a sample curve encoding on hand that can be used for testing?

**Comment by fschueller-ifd** [comment]
Thanks for your quick reaction.

> Do you happen to have a sample curve encoding on hand that can be used for testing?

Of course. This one hits the described problem.

[secp384r1.pem.txt](https://github.com/randombit/botan/files/763823/secp384r1.pem.txt)

**Comment by randombit** [comment]
Sorry this took so long to resolve, now fixed in master.
