### ISSUE TITLE
unfortunate behavior of Constructor EC_Group::EC_Group(const std::string& str) 

### ISSUE THREAD

**Issue by fschueller-ifd** [randombit/botan#875]
The constructor of an EC_GROUP from a string first tries to interpret the string as a pem-encoded group.
If this fails, it tries to interpret the string as an oid. If this also fails, an exception is thrown.

If now, the string is indeed a pem-encoded group, but the decoding fails for some reason (i.e. like in  #874),
the helpful exception is hidden, but an unhelpful exception is thrown.

**Comment by randombit** [comment]
This behavior of taking either a name or a PEM encoding in the single constructor is bogus. It would be better if there were separate APIs for these two distinct operations.

That said there is an easy distinguisher we can use in the EC_Group constructor: if the input string contains no newlines, it cannot possibly be a valid PEM input. And if it contain any newline chars, it cannot possibly be a valid OID. Then EC_Group would try just the one possibly-valid interpretation, and if that decoding operation throws give up immediately, and the application would see the relevant error.

**Comment by fschueller-ifd** [comment]
Or one could check whether the begin of the string is a valid PEM-label?

**Comment by randombit** [comment]
This is fixed now in master.
