### ISSUE TITLE
Compression filter documentation + default secure_vector buffer size

### ISSUE THREAD

**Issue by EricMCornelius** [randombit/botan#89]
I was playing around with this lib earlier today looking for something providing a more modern interface that Crypto++.  The documentation is in general fantastic, but I noticed that there's no mention of the recent shift to treat compression as Transform* instances.

After digging into what had changed, I discovered that the secure_vector buffer used inside the compression/decompression streams is default constructed, which causes zlib STREAM_ERROR failures because nothing is ever allocated for actual buffer space: https://github.com/randombit/botan/blob/net.randombit.botan/src/lib/filters/comp_filter.cpp#L44

Wanted to check in and see what would be useful as a fix for this.  Do you prefer to expose the buffer sizing as a constructor option?  Or stick with the current convention where nearly all existing filters are fixed at DEFAULT_BUFFERSIZE?

**Comment by randombit** [comment]
I've changed the constructor to expose this since I think applications may legitimately need to change this, since it seems like it could affect compression efficiency depending on usage and how the libraries are implemented.
