### ISSUE TITLE
BER_Decoder::verify_end() before BER_Decoder::end_cons() 

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#890]
In some code verify_end() is called before end_const(), eg:

https://github.com/randombit/botan/blob/master/src/lib/x509/x509_obj.cpp#L108

Since end_const would throw anyway if there is data left, what is the purpose of verify_end?

Thanks!

**Comment by randombit** [comment]
I think all `verify_end` calls are probably extraneous. IIRC, `end_cons` did not originally verify that there was no more data remaining, and `verify_end` was added to fix this in an ad-hoc manner.

**Comment by nunojpg** [comment]
Would you like me to pull request the removal of all verify_end immediatly before a end_cons?

**Comment by randombit** [comment]
PR for this would be great, thank you
