### ISSUE TITLE
Add coveralls.io support

### ISSUE THREAD

**Issue by cordney** [randombit/botan#91]
Please add support for https://coveralls.io code coverage reporting. I successfully enabled it for a branch in my fork: https://github.com/cordney/botan/tree/add-coveralls-support
See the resulting coveralls.io report: https://coveralls.io/builds/2524372

The following steps are necessary:

* Register at https://coveralls.io with your GitHub account
* Add the randombit/botan repo to coveralls.io
* Add code coverage support to `.travis.yml`, see https://github.com/cordney/botan/blob/add-coveralls-support/.travis.yml for an example; its basically:
  * Set link to `gcov` version matching the gcc version via `update-alternatives` (this is important, I had huge problems when the two don`t match)
  * Install latest `lcov` 1.11 from source (I had no success with the lcov version installed via apt) 
  * Install coveralls.io report upload tool `coveralls-lcov`
  * Reset all previous coverage data via `lcov --directory . --zerocounters` before building (normally, this should not be necessary, as Travis CI always starts with a clean build, but this may change in the future - who knows)
  * Build
  * Run tests (these take a bit longer with coverage reporting on)
  * Collect results using lcov
  * Remove includes of system headers and test code from reporting
  * Upload report to coveralls.io via `coveralls-lcov`
  * Last but not least, add the coveralls repo token to a environment variable in Travis CI (the repo token should not be public)
* Add coverage badge to GitHub README (instructions are on coveralls.io for your repo)

All changes to `.travis.yml` are largely inspired by http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/. The build runs at 18 mins now for a shared library build. I had no success running this on clang, I think you would have to use the gcov from clang as mentioned in PR 72. IMHO using code coverage only on the GCC build should be enough though.

As you are doing an out of source build, the coverage reports reference the headers in build/, which are also included in the report on coveralls.io. However, coveralls does not follow symlinks, so for these files, coveralls can not show the source online, which is not critical but it would ne nice to have. See for example https://coveralls.io/builds/2524372/source?filename=build%2Finclude%2Fbotan%2Finternal%2Fcompress_utils.h.

**Comment by randombit** [comment]
This looks great, however I'd want it to not conflict with the existing build matrix (clang/gcc and static/shared), hopefully there is some way to express that to travis via the yaml but I haven't looked into it further yet.

**Comment by cordney** [comment]
Yeah, I removed the build matrix as a short cut to test only the coverage build. If you want the coverage as an additional entry in the build matrix, this seems to be quite easy. I just added the shared and static builds to the build matrix on my branch and excluded a coverage build on clang using the matrix: exclude command, see https://github.com/cordney/botan/commit/b81448d3a6d0b46f5e6853dbb71bfc532577c71c. I now have a build matrix with five jobs: 
* clang shared
* gcc shared
* clang static
* gcc static
* gcc shared with coverage

See https://travis-ci.org/cordney/botan/builds/61952464 for the resulting build matrix on Travis and https://coveralls.io/builds/2528276 for the coverage report on coveralls.io. Hope this helps.

**Comment by cordney** [comment]
I just realized a mistake in the .travis.yml I referenced when doing bash string comparison. Find the fixed .travis.yml at https://github.com/cordney/botan/commit/a26141f315d9ea0fbfb662ce79fbd102fd10ca87#diff-354f30a63fb0907d4ad57269548329e3. The corresponding Travis build is here: https://travis-ci.org/cordney/botan/builds/61954524.

**Comment by randombit** [comment]
This is looking good now (besides the header sources not being available in the report) and is active on the main tree. Thanks so much for setting this up!
