### ISSUE TITLE
RDSEED and RDRAND benchmarks

### ISSUE THREAD

**Issue by noloader** [randombit/botan#911]
Please add RDSEED and RDRAND to the RNG speed test.

Most benchmark programs for the instructions are a bit contrived and produce inflated numbers. They maximize throughput without doing things like checking for failure; and writing the value to a memory location or caller buffer. Both practices are not too realistic since a crypto library has to ensure the operation succeeded and then write the value to a user supplied buffer.

Checking for failure requires 1 instruction, and writing a value to a buffer requires roughly 3 instructions (1 for the move, 1 to increment a pointer, and 1 to decrement a size). Including the instruction to generate the random value, that's at least 5 instructions that specialized benchmarks programs often don't perform.

Its also worth mentioning that RDRAND and RDSEED performance is highly dependent on the CPU and manufacturer. And RDSEED runs at a fraction of the rate RDRAND does on the same machine. For example, a realistic benchmark program using a single thread on a single core, and an early 3rd gen Ivy Bridge processor @ 2.4 GHz, could generate RDRAND at a rate of about 200 to 220 MiB/s (where the theoretical maximum is 800 MiB/s). However, moving to a low end Celeron @ 1.3 GHz generates at a rate of 6 MiB/s. And a low end Atom @ 1.5 GHz generates at a rate of 9 MiB/s. The most unusual reading I've seen is the [AMD Athlon X4 845 @ 3.5 GHz](http://www.cpu-world.com/CPUs/Bulldozer/AMD-Athlon%20X4%20845.html), which generates at 1 MiB/s (that's 4100+ cycles per byte).

**Comment by randombit** [comment]
Added a speed test for `RDRAND_RNG` (that is, RDRAND output fully converted into a bytestream for application use, with error checking, retries etc) in 5c4274fcc as part of `./botan speed RNG`.

There is already a test for `RDSEED` in the entropy tests - `./botan speed entropy`.

**Comment by noloader** [comment]
Perfect, thanks. Its nice to have it available to cross-check results.
