### ISSUE TITLE
BOTAN_TARGET_COMPILER_X macros

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#914]
Are they still used/defined?

For example in `test_os_utils.cpp` `BOTAN_TARGET_COMPILER_IS_MSVC` is used. I'm compiling with MSVC but this macro is not set. 

In some places there is a `BOTAN_BUILD_COMPILER_IS_MSVC` and this is set.

**Comment by randombit** [comment]
It's possible I just wrote the macro name incorrectly :/

**Comment by randombit** [comment]
Fixed?

The macro names should be shorter and snappier (`BOTAN_OS_IS_LINUX`, `BOTAN_CC_IS_MSVC`, etc) to avoid problems like this.

**Comment by neusdan** [comment]
There is still the wrong macro in os_utils.cpp line 381.

Thanks for 6817d1a. This fixed C2713. But C2712:

> __cannot use __try in functions that require object unwinding

is still there.

**Comment by neusdan** [comment]
Passing the `std::function` parameter object per const reference fixes this.

**Comment by randombit** [comment]
Fixed now
