### ISSUE TITLE
calendar_point::to_std_timepoint() does not support years after 2037

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#917]
Can we do something about this?

Since Visual Studio 2005 the size of time_t is always 64-bits. But i don't know about the others. Is this still a problem?

**Comment by randombit** [comment]
32-bit time_ts are still problem on 32-bit Linux, Solaris, maybe elsewhere. We are stuck with that until the OS vendor fixes it (knowing Linux, this will finally be fixed ~~ 2036). But any system with a 64-bit time_t doesn't have any such limitations, maybe this check should only apply if `sizeof(time_t) == 4`
