### ISSUE TITLE
Provide handbook as PDF download on the website

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#919]
I have heard various requests offline for the handbook also being provided in PDF format downloadable from the website, additionally to the online manual. The link could be available on the index page. Can we do that? Not sure if this could be automated.

**Comment by randombit** [comment]
Sounds good to me. The HTML version is built as part of the website builder script (`src/scripts/website.sh`) it could build the PDF at the same time.

Currently the website rebuild process is manual but I can install LaTeX and whatever else is needed.
