### ISSUE TITLE
Improve RDRAND performance

### ISSUE THREAD

**Issue by noloader** [randombit/botan#934]
This little patch adds x64 support when available. It increases RDRAND throughput from about 80 MiB/s to about 200 to 210 MiB/s. 200 to 210 MiB/s is what I expect to see based on testing with another library.

The patch does not add new class members to RDRAND so the ABI remains intact. Rather, it adds free-standing `rdrand64` and `rdrand_status64` functions that are called by `RDRAND_RNG::randomize`. It should serve as a good starting point if interested in the change. If not interested in the change, then discard it.

***RDRAND using 32-bit words***:

```
$ ./botan speed --msec=2000 RNG
AutoSeeded_RNG (periodic reseed) generate 18.303 MiB/sec 135.10 cycles/byte (36.61 MiB in 2000.17 ms)
System_RNG generate 15.072 MiB/sec 164.07 cycles/byte (30.14 MiB in 2000.10 ms)
RDRAND generate 83.152 MiB/sec 29.74 cycles/byte (166.30 MiB in 2000.01 ms)
HMAC_DRBG(HMAC(SHA-256)) generate 15.671 MiB/sec 157.81 cycles/byte (31.34 MiB in 2000.16 ms)
HMAC_DRBG(HMAC(SHA-384)) generate 20.249 MiB/sec 122.12 cycles/byte (40.50 MiB in 2000.09 ms)
HMAC_DRBG(HMAC(SHA-512)) generate 26.769 MiB/sec 92.37 cycles/byte (53.54 MiB in 2000.00 ms)
```

***RDRAND using 64-bit words***:

```
$ ./botan speed --msec=2000 RNG
AutoSeeded_RNG (periodic reseed) generate 18.674 MiB/sec 132.42 cycles/byte (37.35 MiB in 2000.18 ms)
System_RNG generate 15.072 MiB/sec 164.06 cycles/byte (30.14 MiB in 2000.00 ms)
RDRAND generate 200.218 MiB/sec 12.35 cycles/byte (400.44 MiB in 2000.02 ms)
HMAC_DRBG(HMAC(SHA-256)) generate 17.157 MiB/sec 144.12 cycles/byte (34.32 MiB in 2000.11 ms)
HMAC_DRBG(HMAC(SHA-384)) generate 20.080 MiB/sec 123.15 cycles/byte (40.16 MiB in 2000.16 ms)
HMAC_DRBG(HMAC(SHA-512)) generate 27.012 MiB/sec 91.55 cycles/byte (54.03 MiB in 2000.13 ms)
```

-----

```
$ cat rdrand.diff 
diff --git a/src/lib/rng/rdrand_rng/rdrand_rng.cpp b/src/lib/rng/rdrand_rng/rdrand_rng.cpp
index d807bd8..59fa055 100644
--- a/src/lib/rng/rdrand_rng/rdrand_rng.cpp
+++ b/src/lib/rng/rdrand_rng/rdrand_rng.cpp
@@ -35,6 +35,24 @@ uint32_t RDRAND_RNG::rdrand()
    return r;
    }
 
+#if defined(BOTAN_TARGET_ARCH_IS_X86_64)
+uint64_t rdrand_status64(bool& ok);
+
+//static
+uint64_t rdrand64()
+   {
+   bool ok = false;
+   uint64_t r = rdrand_status64(ok);
+
+   while(!ok)
+      {
+      r = rdrand_status64(ok);
+      }
+
+   return r;
+   }
+#endif
+
 //static
 BOTAN_FUNC_ISA("rdrnd")
 uint32_t RDRAND_RNG::rdrand_status(bool& ok)
@@ -63,8 +81,49 @@ uint32_t RDRAND_RNG::rdrand_status(bool& ok)
    return 0;
    }
 
+#if defined(BOTAN_TARGET_ARCH_IS_X86_64)
+//static
+BOTAN_FUNC_ISA("rdrnd")
+uint64_t rdrand_status64(bool& ok)
+   {
+   ok = false;
+   uint64_t r = 0;
+
+   for(size_t i = 0; i != BOTAN_ENTROPY_RDRAND_RETRIES; ++i)
+      {
+#if defined(BOTAN_USE_GCC_INLINE_ASM)
+      int cf = 0;
+
+      // Encoding of rdrand %rax
+      asm(".byte 0x48, 0x0F, 0xC7, 0xF0; adcl $0,%1" :
+          "=a" (r), "=r" (cf) : "0" (r), "1" (cf) : "cc");
+#else
+      int cf = _rdrand64_step(&r);
+#endif
+      if(1 == cf)
+         {
+         ok = true;
+         return r;
+         }
+      }
+
+   return 0;
+   }
+#endif
+
 void RDRAND_RNG::randomize(uint8_t out[], size_t out_len)
    {
+#if defined(BOTAN_TARGET_ARCH_IS_X86_64)
+   while(out_len >= 8)
+      {
+      uint64_t r = rdrand64();
+
+      store_le(r, out);
+      out += 8;
+      out_len -= 8;
+      }
+#endif
+
    while(out_len >= 4)
       {
       uint32_t r = RDRAND_RNG::rdrand();
```

-----

Two additional changes can pull another 5 to 8 MiB/s in performance. These changes are not is the patch above.

First, handle retries as close to the `rdrand` instruction as possible since it always succeeds, then stop tracking `BOTAN_ENTROPY_RDRAND_RETRIES` and `fOK`.

```
asm("again:\n .byte 0x48, 0x0F, 0xC7, 0xF0;\n jnc again;\n" : "=a" (r) : : "cc");
```

Second, when the size of the request is 32 or greater on 64-bit machines (16 on 32-bit machines), call the `rdrand` instruction 4 times in a row while only checking for failure as in the first suggestion. Write `%rax` to `out`, `out+8`, `out+16` and `out+24`. Then, increment the pointer and decrement the size. Anything more than 4 machine words appears to provide diminishing returns.

**Comment by randombit** [comment]
An easy doubling in performance on x86-64 by using 64 bit reads seems well worth the effort. Thanks for the note!

**Comment by noloader** [comment]
@randombit,

A quick test under Debian X32 with `BOTAN_USE_GCC_INLINE_ASM` *undefined* shows the 64-bit guard should be:

```
#if defined(BOTAN_TARGET_ARCH_IS_X86_64) && !defined(__ILP32__)
```

That's needed because GCC does not make `_rdrand64_step` available on X32. You can side step the missing `_rdrand64_step` by using the inline ASM. ASM is happy to use 64-bit operands. Or you can do like above and disable X64 on X32 when `_rdrand64_step` intrinsic will be used.

If you disable `_rdrand64_step`, then the generator will run about as fast as the 32-bit version.

**Comment by noloader** [comment]
@randombit,

I was able to test the code under X32. It looks like Botan selects the X64 implementation, which is a good thing. The code should be good on typical Linux and X32 builds, too.
