### ISSUE TITLE
Intrinsics support with MSVC

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#939]
The following warning is printed from configure.py if used with x64 MSVC:
`WARNING: Disabling support for sha intrinsics due to missing flag for compiler`

Is `sha    -> ""` missing in msvc.txt ?

If used with x86 the following warning is printed:
`WARNING: Disabling support for avx2 intrinsics due to missing flag for compiler`

**Comment by noloader** [comment]
SHA intrinsic support was added to VS2015, `cl.exe` version 19.00. No flags are needed as long as the compiler supports the instruction.

***Sample Program***

```
#include <immintrin.h>
int main(int argc, char* argv[])
{
    __m128i t1, t2, t3, t4;
    t4 =  _mm_sha256rnds2_epu32(t1, t2, t3);
    return 0;
}
```

***VS2013***

```
C:\Users\Test>cl /W3 /wd4700 /arch:SSE2 msvc-sha.c /c
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
msvc-sha.c
msvc-sha.c(5) : warning C4013: '_mm_sha256rnds2_epu32' undefined; assuming exter
n returning int
msvc-sha.c(5) : error C2440: '=' : cannot convert from 'int' to '__m128i'
```

***VS2015***

```
c:\Users\Test>cl /wd4700 /arch:SSE2 msvc-sha.c /c
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
msvc-sha.c
```

***VS2017***

```
c:\Users\Test >cl /wd4700 /arch:SSE2 msvc-sha.c /c
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25017 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

msvc-sha.c
```

**Comment by randombit** [comment]
AVX2 is only enabled for x86-64. I can't remember why. I just enabled SHA intrinsics for MSVC since we already had version guards in place.

**Comment by randombit** [comment]
SHA intrinsics seem to be enabled and working in 2015/2017 CI builds. Closing.
