### ISSUE TITLE
Operate on multiple --buf-size's in botan speed

### ISSUE THREAD

**Issue by SideChannel** [randombit/botan#968]
One of the stretch goals in Botan 2.1 Release plan is

- Write a script to measure performance against OpenSSL (probably just calling botan speed and openssl speed for different algorithms and parsing the outputs) and display or graph the results in some useful way.

Therefore, it would be fine if the outputs of openssl speed and botan speed become more comparable.  With openssl 1.1.0e we have (benchmarking AES CBC encryption assembler implementation)

./openssl speed aes-128-cbc aes-192-cbc aes-256-cbc
Doing aes-128 cbc for 3s on 16 size blocks: 29508872 aes-128 cbc's in 3.00s
Doing aes-128 cbc for 3s on 64 size blocks: 8177408 aes-128 cbc's in 3.00s
Doing aes-128 cbc for 3s on 256 size blocks: 2097128 aes-128 cbc's in 3.00s
Doing aes-128 cbc for 3s on 1024 size blocks: 529194 aes-128 cbc's in 3.00s
Doing aes-128 cbc for 3s on 8192 size blocks: 66361 aes-128 cbc's in 3.00s
Doing aes-128 cbc for 3s on 16384 size blocks: 33194 aes-128 cbc's in 3.00s
Doing aes-192 cbc for 3s on 16 size blocks: 25134929 aes-192 cbc's in 3.00s
Doing aes-192 cbc for 3s on 64 size blocks: 6836802 aes-192 cbc's in 3.00s
Doing aes-192 cbc for 3s on 256 size blocks: 1745476 aes-192 cbc's in 3.00s
Doing aes-192 cbc for 3s on 1024 size blocks: 439551 aes-192 cbc's in 3.00s
Doing aes-192 cbc for 3s on 8192 size blocks: 55106 aes-192 cbc's in 3.00s
Doing aes-192 cbc for 3s on 16384 size blocks: 27545 aes-192 cbc's in 3.00s
Doing aes-256 cbc for 3s on 16 size blocks: 21786300 aes-256 cbc's in 3.00s
Doing aes-256 cbc for 3s on 64 size blocks: 5872318 aes-256 cbc's in 3.00s
Doing aes-256 cbc for 3s on 256 size blocks: 1495040 aes-256 cbc's in 2.99s
Doing aes-256 cbc for 3s on 1024 size blocks: 376036 aes-256 cbc's in 3.00s
Doing aes-256 cbc for 3s on 8192 size blocks: 47130 aes-256 cbc's in 3.00s
Doing aes-256 cbc for 3s on 16384 size blocks: 23549 aes-256 cbc's in 3.00s
OpenSSL 1.1.0e  16 Feb 2017
built on: reproducible build, date unspecified
options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc-6 -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl/ssl\"" -DENGINESDIR="\"/usr/local/ssl/lib/engines-1.1\""  -Wa,--noexecstack -march=skylake -mtune=skylake
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128 cbc     157380.65k   174451.37k   178954.92k   180631.55k   181209.77k   181283.50k
aes-192 cbc     134052.95k   145851.78k   148947.29k   150033.41k   150476.12k   150432.43k
aes-256 cbc     116193.60k   125276.12k   128003.42k   128353.62k   128696.32k   128608.94k

i.e. six buffer sizes at once, each for 3sec.  Given a processor speed of 4GHz for Skylake, 4e9 divided by the output of openssl speed gives the usual cycles per byte benchmark table, see the attached slide

![benchmark-openssl-aes-cbc](https://cloud.githubusercontent.com/assets/26873237/24612861/be7abb60-1886-11e7-81d6-1a60efa9dc42.png)

Botan 2.0.1 does not give a cycles per byte measurement, current Botan master is much better, but is still restricted to one buffer size. For example

./botan speed --msec=3000 --buf-size=16384 AES-128/CBC
AES-128/CBC/PKCS7 [base] 675219 key schedule/sec; 0.00 ms/op 5906.50 cycles/op (2 ops in 0.00 ms)
AES-128/CBC/PKCS7 [base] 29411578 iv setup/sec; 0.00 ms/op 139.31 cycles/op (269282 ops in 9.16 ms)
AES-128/CBC/PKCS7 [base] encrypt 701.254 MiB/sec 5.45 cycles/byte (2103.77 MiB in 3000.01 ms)
AES-128/CBC/PKCS7 [base] decrypt 1520.429 MiB/sec 2.51 cycles/byte (2103.77 MiB in 1383.67 ms)

**It would be very nice if botan speed could process something like

./botan speed --msec=3000 --buf-size=16,64,256,1024,8192,16384 AES-128/CBC

simultaneously and would output a similar table as above in OpenSSL (1000s of bytes per second) or the final cycles per byte table as in the slide.**

Of course, one could think about making the above buffer sizes the default (or buffer sizes as in eBACS https://bench.cr.yp.to/), but this would lead to considerable more time for running botan speed.

**Comment by randombit** [comment]
This would be an excellent addition and a necessary step for any proper performance comparison.

**Comment by 0xdefaced** [comment]
#1084 
it is WIP but feedback is always appreciated...

**Comment by SideChannel** [comment]
I like the work done by 0xdefaced in PR #1084 
Just two proposals for cosmetic corrections and one functional, but very very minor issues.

1. First, the functional one. If you ask for 
`./botan speed --msec=3000 --buf-size=64,16,8192,256,1024,8192,16384 AES-128/CBC`
i.e. an unsorted list with repetitions then botan does exactly what is written on the command line. Wouldn't it be more useful to, first, sort the arguments of --buf-size and, second, make them unique. Because what numbers would be reported in this case for 8192? First or second measurement?
2. Could you please put a colon after 
`AES-128/GCM(16) [clmul] encrypt buffer size 16384 450.354 MiB/sec 8.49 cycles/byte (1346.61 MiB in 2990.12 ms)`
buffer size 16384: for better readability?
3. This has nothing to do with the PR, but wiih the general speed output. Right now Botan speed is not very consequent in using SI units, especially sec or msec versus s or ms. Could this be unified to s and ms? Here is an example output of the new speed implementation

./botan speed --msec=3000 --buf-size=16,64,256,1024,8192,16384 AES-128/GCM
AES-128/GCM(16) [clmul] 129726 key schedule/sec; 0.01 ms/op 30037 cycles/op (2 ops in 0 ms)
AES-128/GCM(16) [clmul] 3697321 iv setup/sec; 0.00 ms/op 1085.19 cycles/op (29095870 ops in 7869.44 ms)
AES-128/GCM(16) [clmul] encrypt buffer size 16 74.969 MiB/sec 51.07 cycles/byte (221.98 MiB in 2961.00 ms)
AES-128/GCM(16) [clmul] decrypt buffer size 16 73.995 MiB/sec 51.74 cycles/byte (221.98 MiB in 3000.00 ms)
AES-128/GCM(16) [clmul] 3686054 iv setup/sec; 0.00 ms/op 1090.55 cycles/op (19220036 ops in 5214.26 ms)
AES-128/GCM(16) [clmul] encrypt buffer size 64 195.736 MiB/sec 19.71 cycles/byte (586.55 MiB in 2996.64 ms)
AES-128/GCM(16) [clmul] decrypt buffer size 64 195.516 MiB/sec 19.57 cycles/byte (586.55 MiB in 3000.00 ms)
AES-128/GCM(16) [clmul] 3695282 iv setup/sec; 0.00 ms/op 1086.05 cycles/op (8098666 ops in 2191.62 ms)
AES-128/GCM(16) [clmul] encrypt buffer size 256 345.651 MiB/sec 11.06 cycles/byte (988.61 MiB in 2860.13 ms)
AES-128/GCM(16) [clmul] decrypt buffer size 256 329.536 MiB/sec 11.60 cycles/byte (988.61 MiB in 3000.00 ms)
AES-128/GCM(16) [clmul] 3686277 iv setup/sec; 0.00 ms/op 1088.78 cycles/op (2549046 ops in 691.50 ms)
AES-128/GCM(16) [clmul] encrypt buffer size 1024 430.283 MiB/sec 8.88 cycles/byte (1244.65 MiB in 2892.63 ms)
AES-128/GCM(16) [clmul] decrypt buffer size 1024 414.884 MiB/sec 9.21 cycles/byte (1244.65 MiB in 3000.00 ms)
AES-128/GCM(16) [clmul] 3540382 iv setup/sec; 0.00 ms/op 1124.39 cycles/op (342864 ops in 96.84 ms)
AES-128/GCM(16) [clmul] encrypt buffer size 8192 447.676 MiB/sec 8.54 cycles/byte (1339.31 MiB in 2991.70 ms)
AES-128/GCM(16) [clmul] decrypt buffer size 8192 446.436 MiB/sec 8.56 cycles/byte (1339.31 MiB in 3000.01 ms)
AES-128/GCM(16) [clmul] 3501870 iv setup/sec; 0.00 ms/op 1141.80 cycles/op (172366 ops in 49.22 ms)
AES-128/GCM(16) [clmul] encrypt buffer size 16384 450.354 MiB/sec 8.49 cycles/byte (1346.61 MiB in 2990.12 ms)
AES-128/GCM(16) [clmul] decrypt buffer size 16384 448.866 MiB/sec 8.52 cycles/byte (1346.61 MiB in 3000.03 ms)

algo                          operation  16 bytes       64 bytes       256 bytes      1024 bytes     8192 bytes     16384 bytes    
AES-128/GCM(16) [clmul]       decrypt    77588.98       205013.70      345543.03      435037.11      468122.04      470669.84      
AES-128/GCM(16) [clmul]       encrypt    78610.81       205243.63      362441.08      451184.33      469422.29      472230.01      
[results are the number of 1000s bytes processed per second]

Botan 2.2.0 (unreleased, revision unknown, distribution unspecified)

Finally, while testing `./botan speed --msec=3000 --buf-size=16,64,256,1024,8192,16384 ` I got

AES-128/XTS [base] 842105 key schedule/sec; 0.00 ms/op 4720.00 cycles/op (2 ops in 0.00 ms)
Error: False assertion 'Have sufficient final input' (expression sz >= minimum_final_size()) in finish @./src/lib/modes/xts/xts.cpp:176

Probably has nothing to do with PR #1084 but seems a bug anyway.

Thanks for your work, 0xdefaced.

**Comment by 0xdefaced** [comment]
Thx for your feedback. I updated the branch according to your suggestions.

**Comment by SideChannel** [comment]
@0xdefaced and @randombit 

I am fine with the updated branch in PR #1084. Almost everything as I expected. The cosmetic change with sec and msec versus s and ms is for @randombit to decide. US usage versus international usage. But in the moment both worlds are mixed. (Similar output with botan-test).

**But, more important** The patch seems to trigger a bug in xts, as I still have

`./botan  speed --msec=3000 --buf-size=16,64,256,1024,8192,16384` 

AES-128/XTS [base] 842105 key schedule/sec; 0.00 ms/op 4720.00 cycles/op (2 ops in 0.00 ms)
Error: False assertion 'Have sufficient final input' (expression sz >= minimum_final_size()) in finish @./src/lib/modes/xts/xts.cpp:176

If I only call 
`./botan speed --msec=3000 --buf-size=16384 AES-128/XTS` everything is fine. (The same is without the patch and botan speed --msec --buf-size=4096, everything run's through.) But above call is unfortunately the equivalent to openssl speed full benchmark. So, only this bug is preventing #1084 from being merged, IMHO.

**Comment by securitykernel** [comment]
This can be closed, right?
