### ISSUE TITLE
Labels for contributions

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#970]
Can we add some more labels for issues, e.g., "doing" and "accepting pull requests"? It is sometimes hard to tell from your comments whether you will be working on a particular issue raised or you would rather see it contributed from others via pull request. :smiley: A recent example for this is #968.

**Comment by randombit** [comment]
Added `accepting_pull_requests`, `doing`, `changes_needed_before_merge`, `missing_tests`, `missing_documentation`. I'm happy to accept additional label suggestions from anyone, just comment here.

**Comment by ksanderon** [comment]
label "discussion" could be great in my opinion for some kind of issues, especially for "milestone tracking issues"(like: #866) and to find things asked by others (like #941), but for which dedicated PR is not expected.

**Comment by securitykernel** [comment]
Thanks! As there are no more suggestions, I'll close here.
