### ISSUE TITLE
Cross-compilation to OpenWrt routers

### ISSUE THREAD

**Issue by steven-chien** [randombit/botan#971]
First of all I would like to thank the author for building this wonderfully easy to use library and developing everything in C++11. I am developing an application that uses Botan to handle some TLS connections on Raspberry Pi. The library has been working well so far. Now I am thinking of putting the application on OpenWrt routers. The idea is to build my application with the .a static library such that it can be directly used on the router. Since botan's Makefile generation uses neither autoconfig nor cmake, I have no idea how to properly configure the library build against my OpenWrt toolchain. The script doesn't seem to recognizing the os option OpenWrt and cpu architecture MIPS as well. Any help and recommendation would be greatly appreciated!

**Comment by randombit** [comment]
I'm not sure if OpenWRT works out of the box or not, but something like

```
configure.py --os=linux --cpu=mips32 --cc=gcc --cc-bin=path-to-openwrt-c++-compiler
```

should work. There may be some issue due to OpenWrt's use of uclibc instead of glibc, but musl libc builds also work with problem so I'm not expecting major problems.

**Comment by randombit** [comment]
@steven-chien Did you have any luck with the above configuration?

**Comment by steven-chien** [comment]
@randombit Yes, the instruction works with modification. One thing to note is that it cannot be built on OpenWrt but it can on LEDE(which is a fork of OpenWrt) because the latter uses musl libc which supports C++11. I will post the instructions here later.

**Comment by randombit** [comment]
Closing as resolved. Good to know that uclibc doesn't support C++11

**Comment by hbl0307106015** [comment]
@steven-chien, maybe my pull request can help you?

https://github.com/openwrt/packages/pull/4930
