### ISSUE TITLE
Botan::Algorithm_Not_Found exception when using AutoSeeded_RNG (Windows + MinGW)

### ISSUE THREAD

**Issue by lmiguelmh** [randombit/botan#98]
I downloaded Botan-1.11.16 and managed to compile it. After many tries I ended using: ``python.exe configure.py --cc=gcc --os=mingw --cpu=i386 --link-method=copy --disable-modules=tls``

I couldn't do ``make install``. I had the same issue as https://github.com/randombit/botan/issues/39. I didn't mind this because the lib ``libbotan-1.11.a`` was already compiled.

So, I decided to try http://botan.randombit.net/manual/filters.html, everything ok until I got this exception: ``terminate called after throwing an instance of 'Botan::Algorithm_Not_Found' what():  Could not find any algorithm named "HMAC(SHA-512)"`` when using this:

``Botan::AutoSeeded_RNG rng;``

Is this because I deactivated ``tls`` (mingw doesn't support sys/socket.h)? Or because I didn't finish the ``make install``? Or because the RNG in ``Windows`` need something else?

Thanks for your help.

**Comment by webmaster128** [comment]
Sorry for the late reply. I hope my answer still helps you.

`make install` should work better since 1.11.17 but I did not test it exhaustive using MinGW. It's worth trying it again.

The other point is that you're trying to use the .a file without amalgamation. This is a [problem discussed intensely](https://github.com/randombit/botan/issues/128) at the moment. As of now, you can only build a static lib using the amalgamation, i.e. `./configure.py --disable-shared --via-amalgamation`. Otherwise you need to use a dynamically linked .dll/.so file.

**Comment by webmaster128** [comment]
Closed due to inactivity. Question and answer probably outdated with current version. Please follow up with updated information in a new issue I you are still in trouble.

**Comment by njuFerret** [comment]
?

**Comment by njuFerret** [comment]
I have to say, it is too hard to compile botan under Windows with msys2. There's almost no usable reference on such platform. After several days' attempts, I managed to successfully compile the library. Steps are followed:
1、	The compiler is mingw-w64 x86 pthread version downloaded from sourceforge.net. ( do not user win32 version)
2、	configure with configure.py
./configure.py --prefix=/home/YourName/build --os=mingw --cc=gcc --cpu=i686 --link-method=copy
3、	using boost library for lacking “_mkgmtime” function, so modified the generated Makefile in step2:
line 22:
SCRIPTS_DIR    = .\src\scripts
To    SCRIPTS_DIR    = ./src/scripts
Line 1278:
build\obj\lib\utils_calendar.o: .\src\lib\utils\calendar.cpp
$(CXX) $(LIB_FLAGS) -Ibuild\include .\src\lib\utils\calendar.cpp -o $@
TO
build\obj\lib\utils_calendar.o: .\src\lib\utils\calendar.cpp
	$(CXX) $(LIB_FLAGS) -Ibuild\include -Ibuild\boost .\src\lib\utils\calendar.cpp -o $@
4、	add definition for boost function boost_timegm, edit  source file of calendar.cpp under  Botan-1.11.20\src\lib\utils:
#include <botan/calendar.h>
#include <botan/exceptn.h>
#include <ctime>
#include <sstream>
#include <iomanip>
#include <mutex>

// add these lines
#ifdef BOTAN_TARGET_OS_HAS_MKGMTIME
#undef BOTAN_TARGET_OS_HAS_MKGMTIME
#define BOTAN_HAS_BOOST_DATETIME
#endif
// add lines end

#if defined(BOTAN_HAS_BOOST_DATETIME)
#include <boost/date_time/posix_time/posix_time_types.hpp>
#endif

5、	now, after make & make install, the .a file and botan.exe and botan-test.exe can be generated and install under “prefix” dir.

Question: when run botan-test.exe, all tests that can do shows “failed”, then the application will abort.

my env:
g++ ver 4.9.3 dwarf posix version 
msys2,
python 3.4.3

**Comment by webmaster128** [comment]
@njuFerret Please open a new issue with [properly formatted](https://guides.github.com/features/mastering-markdown/) content. I am sure we can help you then.

**Comment by njuFerret** [comment]
thanks, i'll do that later.

**Comment by njuFerret** [comment]
The post was deleted,and new issue #274,has been posted.
