### ISSUE TITLE
Botan 2.1.0 does not compile under Cygwin 2.8.0 with g++ 5.4.0

### ISSUE THREAD

**Issue by SideChannel** [randombit/botan#982]
Hi,

the recent release 2.1.0 does not compile with my system at work while 2.0.1 does (same setup). It has problems compiling os_utils.cpp.

System
--------

- Windows 7 SP1, Cygwin 2.8.0, Compiler g++ 5.4.0

Steps to reproduce the problem
---------------------------------
tar xzvf Botan-2.1.0.tgz
cd Botan-2.1.0
./configure.py
   INFO: ./configure.py invoked with options ""
   INFO: Platform: OS="CYGWIN_NT-6.1" machine="x86_64" proc=""
   INFO: Guessing target OS is cygwin (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Detected CPU model "Intel(R) Xeon(R) CPU W3690 @ 3.47GHz" in /proc/cpuinfo
   INFO: Guessing target processor is a x86_64/x86_64 (use --cpu to set)
   INFO: Target is gcc-cygwin-x86_64-x86_64
   INFO: Found sphinx-build (use --without-sphinx to disable)
WARNING: Shared libs not supported on cygwin, disabling shared lib support
   INFO: Skipping, dependency failure - certstor_sqlite3 pkcs11 sessions_sqlite3
   INFO: Skipping, incompatible OS - darwin_secrandom dyn_load getentropy locking_allocator
   INFO: Skipping, no enabled compression schemes - compression
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlite3 tpm zlib
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 aont asn1 auto_rng base base64 bcrypt bigint blake2 block blowfish camellia cascade cast cbc cbc_mac
ccm cecpq1 certstor_sql cfb chacha chacha20poly1305 chacha_sse2 clmul cmac codec_filt comb4p crc24 crc32 cryptoapi_rng cryptobox ctr curve25519 des dev_random dh dl_algo dl_group dlies dsa eax ec_gfp ec_group ecc_key ecdh ecdsa ecgdsa ecies
 eckcdsa elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw
emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_drbg http_util idea idea_sse2 iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion mac mce mceies md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp newhope noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 proc_walk pubkey rc4 rdrand rdrand_rng rdseed rfc3394 rfc6979 rmd160 rng rsa salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_sse2 sha2_32 sha2_64
sha3 shake shake_cipher simd siphash siv skein sp800_108 sp800_56c srp6 stateful_rng stream system_rng threefish threefish_avx2 tiger tls tls_cbc tss twofish utils whirlpool win32_stats x509 x919_mac xmss xtea xts
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Botan 2.1.0 (VC git:7bdffd52a96e08e9452d1985258376a3925a497b) (released
 dated 20170404) build setup is complete
make
...
g++ -fstack-protector -m64 -pthread  -std=c++11 -D_REENTRANT -O3 -momit-leaf-fra
me-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast
-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer
-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/utils/mem_ops.cpp -o b
uild/obj/lib/utils_mem_ops.o
g++ -fstack-protector -m64 -pthread  -std=c++11 -D_REENTRANT -O3 -momit-leaf-fra
me-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast
-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer
-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/utils/os_utils.cpp -o
build/obj/lib/utils_os_utils.o
In file included from /usr/include/setjmp.h:10:0,
                 from ./src/lib/utils/os_utils.cpp:21:
./src/lib/utils/os_utils.cpp: In function 'void Botan::{anonymous}::botan_sigill
_handler(int)':
./src/lib/utils/os_utils.cpp:340:6: error: expected id-expression before '__exte
nsion__'
    ::siglongjmp(g_sigill_jmp_buf, /*non-zero return value*/1);
      ^
./src/lib/utils/os_utils.cpp:340:6: error: expected primary-expression before ')
' token
    ::siglongjmp(g_sigill_jmp_buf, /*non-zero return value*/1);
      ^
./src/lib/utils/os_utils.cpp: In function 'int Botan::OS::run_cpu_instruction_pr
obe(std::function<int()>)':
./src/lib/utils/os_utils.cpp:355:34: error: 'sigemptyset' was not declared in th
is scope
    sigemptyset(&sigaction.sa_mask);
                                  ^
./src/lib/utils/os_utils.cpp:358:59: error: no matching function for call to 'si
gaction::sigaction(int, sigaction*, sigaction*)'
    int rc = ::sigaction(SIGILL, &sigaction, &old_sigaction);
                                                           ^
In file included from /usr/include/sys/signal.h:112:0,
                 from /usr/include/signal.h:6,
                 from /usr/include/pthread.h:12,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr-default.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/ext/atomic
ity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/memory:73,

                 from build/include/botan/types.h:16,
                 from build/include/botan/internal/os_utils.h:11,
                 from ./src/lib/utils/os_utils.cpp:9:
/usr/include/cygwin/signal.h:317:8: note: candidate: sigaction::sigaction()
 struct sigaction
        ^
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 0 arguments, 3 pro
vided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(const sigaction&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(sigaction&&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
In file included from /usr/include/setjmp.h:10:0,
                 from ./src/lib/utils/os_utils.cpp:21:
./src/lib/utils/os_utils.cpp:363:11: error: expected id-expression before '__ext
ension__'
    rc = ::sigsetjmp(g_sigill_jmp_buf, /*save sigs*/1);
           ^
./src/lib/utils/os_utils.cpp:363:11: error: expected primary-expression before '
)' token
    rc = ::sigsetjmp(g_sigill_jmp_buf, /*save sigs*/1);
           ^
./src/lib/utils/os_utils.cpp:377:52: error: no matching function for call to 'si
gaction::sigaction(int, sigaction*, std::nullptr_t)'
    rc = ::sigaction(SIGILL, &old_sigaction, nullptr);
                                                    ^
In file included from /usr/include/sys/signal.h:112:0,
                 from /usr/include/signal.h:6,
                 from /usr/include/pthread.h:12,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr-default.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/ext/atomic
ity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/memory:73,

                 from build/include/botan/types.h:16,
                 from build/include/botan/internal/os_utils.h:11,
                 from ./src/lib/utils/os_utils.cpp:9:
/usr/include/cygwin/signal.h:317:8: note: candidate: sigaction::sigaction()
 struct sigaction
        ^
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 0 arguments, 3 pro
vided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(const sigaction&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(sigaction&&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
./src/lib/utils/os_utils.cpp: At global scope:
./src/lib/utils/os_utils.cpp:336:21: warning: 'Botan::{anonymous}::g_sigill_jmp_
buf' defined but not used [-Wunused-variable]
 static ::sigjmp_buf g_sigill_jmp_buf;
                     ^
make: *** [Makefile:1302: build/obj/lib/utils_os_utils.o] Error 1

BTW, versions between 2.0.1 and 2.1.0 from Github sometimes did not even finish configure.py.

**Comment by randombit** [comment]
It seems like Cygwin is missing sigaction? But the Cygwin docs I've read certainly seem to indicate Cygwin supports Unix style signals, and there is a patch from 1997 that added the prototype https://cygwin.com/ml/cygwin/1997-03/msg00419.html

The `run_cpu_instruction_probe` function can be simply skipped for Cygwin. It is only really necessary for CPUs such as ARM that do not provide a userspace accessible CPU feature indicator instruction, like x86's CPUID. I will create a PR fixing this sometime in next few days.

> BTW, versions between 2.0.1 and 2.1.0 from Github sometimes did not even finish configure.py.

It would be worth posting a bug when that happens, because CI does not check Cygwin builds, and  as far as I know none of the active developers use it either, so if `master` is broken for you it is likely in a Cygwin-specific way of which the developers are unaware.

To more easily detect such problems on CI, before it affects end users, we should add a new CI job to runs `configure.py` many times with different options (say each available OS * each available CPU * each available compiler, with/without shared libs, ...) and ensures that at least the Makefile is created and seems all right, without trying to actually build or run a binary. [PRs welcome]

**Comment by randombit** [comment]
@SideChannel can you try the patch posted in #987 I think this will resolve the issue but do not have any way of testing it.

**Comment by SideChannel** [comment]
@randombit : PR #987 does not quite solve the problem yet. Enclosed is the compilation output

g++ -fstack-protector -m64 -pthread  -std=c++11 -D_REENTRANT -O3 -momit-leaf-fra
me-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast
-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer
-constant -Wnon-virtual-dtor -Ibuild/include -c ./src/lib/utils/os_utils.cpp -o
build/obj/lib/utils_os_utils.o
./src/lib/utils/os_utils.cpp: In function 'int Botan::OS::run_cpu_instruction_pr
obe(std::function<int()>)':
./src/lib/utils/os_utils.cpp:355:38: error: 'sigemptyset' was not declared in th
is scope
    sigemptyset(&cur_sigaction.sa_mask);
                                      ^
./src/lib/utils/os_utils.cpp:358:61: error: no matching function for call to 'si
gaction::sigaction(int, sigaction*, sigaction*)'
    int rc = sigaction(SIGILL, &cur_sigaction, &old_sigaction);
                                                             ^
In file included from /usr/include/sys/signal.h:112:0,
                 from /usr/include/signal.h:6,
                 from /usr/include/pthread.h:12,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr-default.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/ext/atomic
ity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/memory:73,

                 from build/include/botan/types.h:16,
                 from build/include/botan/internal/os_utils.h:11,
                 from ./src/lib/utils/os_utils.cpp:9:
/usr/include/cygwin/signal.h:317:8: note: candidate: sigaction::sigaction()
 struct sigaction
        ^
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 0 arguments, 3 pro
vided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(const sigaction&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(sigaction&&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
./src/lib/utils/os_utils.cpp:377:50: error: no matching function for call to 'si
gaction::sigaction(int, sigaction*, std::nullptr_t)'
    rc = sigaction(SIGILL, &old_sigaction, nullptr);
                                                  ^
In file included from /usr/include/sys/signal.h:112:0,
                 from /usr/include/signal.h:6,
                 from /usr/include/pthread.h:12,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr-default.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/x86_64-pc-
cygwin/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/ext/atomic
ity.h:35,
                 from /usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/memory:73,

                 from build/include/botan/types.h:16,
                 from build/include/botan/internal/os_utils.h:11,
                 from ./src/lib/utils/os_utils.cpp:9:
/usr/include/cygwin/signal.h:317:8: note: candidate: sigaction::sigaction()
 struct sigaction
        ^
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 0 arguments, 3 pro
vided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(const sigaction&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
/usr/include/cygwin/signal.h:317:8: note: candidate: constexpr sigaction::sigact
ion(sigaction&&)
/usr/include/cygwin/signal.h:317:8: note:   candidate expects 1 argument, 3 prov
ided
make: *** [Makefile:1306: build/obj/lib/utils_os_utils.o] Error 1

**Comment by randombit** [comment]
Thanks, looks like my guess at the problem in #987 was incorrect, probably simpler to simply skip this function on Cygwin then.

**Comment by noloader** [comment]
Cygwin uses Newlib, not GNU's `libstdc++`. When there's no `-std=c++XX`, current GCC defaults to `-std-gnu++11` ([GCC 6 changes to `gnu++14`](https://gcc.gnu.org/gcc-6/changes.html) by default). I believe GNU sources ensures expected functions, like `sigaction` are available.

You might consider trying `-D_XOPEN_SOURCE=600`  or `-D_XOPEN_SOURCE=700`.

**Comment by SideChannel** [comment]
Thanks to @noloader Until now -std=c++11 was set in Makefile. The important info is in above mentioned thread on the Newlib mailing list. Yaakov Selkowitz wrote

> G++ defines _GNU_SOURCE on glibc targets, meaning that -std=c++NN is, contrary to the documentation, *not* strict ISO C++:

So, applying the patch #987 **AND** setting -std=gnu++11 works for me. I did not try the other -D options (I think the other fact is more fundamental). Summarizing, @randombit please apply the PR #987 and set -std=gnu++11 for gcc under Cygwin.

**Comment by SideChannel** [comment]
Hi,

long time not here. I just wanted to note that with recent Botan 2.4.0, Cygwin 2.10.0 and gcc 6.4.0 everything  runs fine out of the box under Windows 10. So problem solved and issue can be closed.

**Comment by webmaster128** [comment]
@SideChannel Good to know, feel free to close the issue yourself
