### ISSUE TITLE
Exceptions without visibility default

### ISSUE THREAD

**Issue by ksanderon** [randombit/botan#983]
I fund that in botan some internally defined exceptions don't have visibility default - at least:
* `Integer_Overflow_Detected`
* `TPM_Error`
* `PKCS11_Error`
* `PKCS11_ReturnError`
* `OpenSSL_Error`
* `FFI_Error`

For more I was able to produce exception from `tls::Client::received_data` which was not even detected as std::exception and only possible to catch in `catch(...)`.

**Comment by randombit** [comment]
Anything thrown should be exported. Exception handling across shared library boundaries is dicey in the best of circumstances.

`not even detected as std::exception and only possible to catch in catch(...)`

Ouch that is really bad, can you provide more details of what was happening? There should be a test that verifies Botan behaves nicely here.

**Comment by ksanderon** [comment]
Fully agree, so I will add it some where to #973 content + minimal example for exception thrown from received_data (Anyway I have no idea why there is this kind of problem - abi::__cxa_current_exception_type()->name() tell me that it is TLS_Exception :/ ).

**Comment by randombit** [comment]
I've marked all the exception types as exported, so closing this issue. If it is possible to reproduce the TLS problem that should certainly be fixed but can be handled as a distinct issue.
