### ISSUE TITLE
Can we remove --chost from configure?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#990]
While refactoring main() in configure.py, I came across the --chost option [added 5 years ago](https://github.com/randombit/botan/commit/b72900c62a5c27e588a5512e65ced402bb508871) as an undocumented convenience argument.

Is this option used anywhere or can it die in favor of less complex configure code?

**Comment by randombit** [comment]
Should be removed, idea was to take an GNU style triplet for better interop with application build systems that assume/use autoconf. But in practice configure.py won't understand most `config.guess` outputs, better not to set any expectations that it can.

**Comment by webmaster128** [comment]
ok thanks, I'll do that
