### ISSUE TITLE
destdir vs prefix confusion

### ISSUE THREAD

**Issue by danimo** [randombit/botan#996]
Due to Botan 2 using its own toolchain, it seems that some changes were introduced that get in the way of proper packaging. `configure.py` takes a `--destdir` optional argument, which the documentation advertises to be '/usr' or '/usr/local'.

This is what autotools-based build systems call `prefix`. It's the prefix to all other directories (`libdir`, `bindir`, etc), unless they are specified with an absolute path as well.

The purpose of `DESTDIR` (which is a shell variable) is to be able to relocate the entire tree relative to a given directory. This is used in packaging of all RPM and deb based distributions during build (note: It's _not_ meant to create relocatable binaries). `DESTDIR` should not be an argument passed to configure, it should only be evaluated by `install.py` (hence it usually is a shell variable).

We cannot use the current `destdir` for this, because it will cause the (temporary) DESTDIR prefix path to be included in e.g. header files.

**Comment by danimo** [comment]
Short update: This used to work in Botan 1.10.

**Comment by danimo** [comment]
Is there anything still missing here?

**Comment by webmaster128** [comment]
All the feedback from April 19 and April 27 in #997
